import Fermat.GenericIrregular.DeepReality
import Fermat.Irregular.CircularUnitFamily
import Fermat.Irregular.CyclotomicSinnottBridgePrime
import Fermat.Irregular.VandiverFiniteIndex
import Fermat.Irregular.VandiverLemmaTwoCore
import Fermat.Irregular.VandiverRealUnits
import Fermat.Irregular.VandiverUnitLemma
import FltRegular.NumberTheory.KummerFullValuation
import Mathlib.NumberTheory.ZetaValues

/-!
# Harness for the adaptive relevant-unit relation

This file develops the source side of the all-`p`-adic unit splice without
changing `FltRegular.CaseII.InductionStep`.

The finite family is not an exponent-specific certificate: it is the
canonical family of normalized circular units at an arbitrary odd prime.
The generic Sinnott--Kummer theorem already in the repository proves that
this family has finite index.  Thus the remaining arithmetic boundary is
only the adaptive logarithmic-derivative congruence for the exact relevant
unit.
-/

open scoped BigOperators NumberField

namespace Fermat.KummerIso.UnitAdaptiveRelationHarness

noncomputable section

open Fermat.GenericIrregular.DeepReality
open Fermat.Irregular.CircularUnitFamily
open Fermat.Irregular.CircularUnitIndex
open Fermat.Irregular.CyclotomicSinnottBridgePrime
open Fermat.Irregular.SinnottIndex
open Fermat.Irregular.VandiverLemmaTwoCore
open Fermat.Irregular.VandiverUnitLemma

variable {K : Type} {p : ℕ} [Fact p.Prime]
  [Field K] [NumberField K] [NumberField.IsCMField K]
  [IsCyclotomicExtension {p} ℚ K]

/-- The canonical circular units, bundled in the real-unit subgroup. -/
def realCircularUnitFamily
    {ζ : K} (hζ : IsPrimitiveRoot ζ p) (hp2 : p ≠ 2) :
    Fin ((p - 3) / 2) → NumberField.IsCMField.realUnits K :=
  fun i =>
    ⟨circularUnitFamily hζ hp2 i,
      circularUnitFamily_mem_realUnits hζ hp2 i⟩

omit [IsCyclotomicExtension {p} ℚ K] in
@[simp]
theorem realCircularUnitFamily_coe
    {ζ : K} (hζ : IsPrimitiveRoot ζ p) (hp2 : p ≠ 2)
    (i : Fin ((p - 3) / 2)) :
    ((realCircularUnitFamily hζ hp2 i :
      NumberField.IsCMField.realUnits K) : (𝓞 K)ˣ) =
      circularUnitFamily hζ hp2 i :=
  rfl

/-- The subgroup generated by the canonical circular units and torsion has
finite index in the full unit group.

The proof is prime-uniform: Sinnott's index formula identifies its relative
index in the real Hasse subgroup with the nonzero plus class number, and the
real Hasse subgroup itself has index one or two. -/
theorem ambient_sup_torsion_finiteIndex
    (hp3 : 2 < p) {ζ : K} (hζ : IsPrimitiveRoot ζ p) :
    (Subgroup.closure
        (Set.range (circularUnitFamily hζ (by omega))) ⊔
      NumberField.Units.torsion K).FiniteIndex := by
  letI : Fact (2 < p) := ⟨hp3⟩
  let C : Subgroup (𝓞 K)ˣ :=
    Subgroup.closure
        (Set.range (circularUnitFamily hζ (by omega))) ⊔
      NumberField.Units.torsion K
  let R : Subgroup (𝓞 K)ˣ :=
    NumberField.IsCMField.realUnits K ⊔
      NumberField.Units.torsion K
  have hCR : C ≤ R := by
    apply sup_le
    · apply (Subgroup.closure_le R).2
      rintro _ ⟨i, rfl⟩
      exact (show NumberField.IsCMField.realUnits K ≤ R from le_sup_left)
        (circularUnitFamily_mem_realUnits hζ (by omega) i)
    · exact le_sup_right
  have hrel :
      C.relIndex R =
        NumberField.classNumber
          (NumberField.maximalRealSubfield K) := by
    simpa only [C, R, realUnitRelIndex] using
      circularUnit_realIndex_eq_classNumber
        (p := p) (K := K) hζ
  have hR :
      R.index = NumberField.IsCMField.indexRealUnits K :=
    rfl
  have hindex :
      C.index =
        NumberField.classNumber
            (NumberField.maximalRealSubfield K) *
          NumberField.IsCMField.indexRealUnits K := by
    rw [← hrel, ← hR]
    exact (Subgroup.relIndex_mul_index hCR).symm
  rw [Subgroup.finiteIndex_iff, hindex]
  exact mul_ne_zero
    (NumberField.classNumber_ne_zero
      (NumberField.maximalRealSubfield K))
    (by
      rcases NumberField.IsCMField.indexRealUnits_eq_one_or_two
          (K := K) with h | h <;>
        simp [h])

/-- The canonical circular-unit family has finite-index closure in the full
unit group. -/
theorem ambient_closure_finiteIndex
    (hp3 : 2 < p) {ζ : K} (hζ : IsPrimitiveRoot ζ p) :
    (Subgroup.closure
      (Set.range (circularUnitFamily hζ (by omega)))).FiniteIndex := by
  exact
    (NumberField.Units.finiteIndex_iff_sup_torsion_finiteIndex
      (Subgroup.closure
        (Set.range (circularUnitFamily hζ (by omega))))).2
      (ambient_sup_torsion_finiteIndex hp3 hζ)

/-- The same canonical family has finite-index closure in the real-unit
subgroup, which is where odd `p`-power injectivity is available. -/
theorem real_closure_finiteIndex
    (hp3 : 2 < p) {ζ : K} (hζ : IsPrimitiveRoot ζ p) :
    (Subgroup.closure
      (Set.range (realCircularUnitFamily hζ (by omega)))).FiniteIndex := by
  have hp2 : p ≠ 2 := by omega
  letI :
      (Subgroup.closure
        (Set.range fun i : Fin ((p - 3) / 2) ↦
          ((realCircularUnitFamily hζ hp2 i :
            NumberField.IsCMField.realUnits K) : (𝓞 K)ˣ))).FiniteIndex := by
    simpa only [realCircularUnitFamily_coe] using
      ambient_closure_finiteIndex hp3 hζ
  exact
    Fermat.Irregular.VandiverFiniteIndex.closure_range_subtype
      (NumberField.IsCMField.realUnits K)
      (realCircularUnitFamily hζ hp2)

/-! ## Construction of the exact finite relation -/

/-- Adaptive logarithmic-derivative precision, stated only for the canonical
circular-unit family and one exact deeply congruent unit.

This is the arithmetic proposition which remains after the finite-index
family has been constructed.  It contains no root provider and no
per-prime data. -/
def CanonicalFullValuationCongruences
    (hp5 : 5 ≤ p) {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (u : (𝓞 K)ˣ) (hdeep : IsVandiverDeep hζ u)
    (C : KummerFullValuation.CoefficientFamily p
      (Fin ((p - 3) / 2))) : Prop :=
  KummerFullValuation.PrimitiveRelationFullValuationCongruences
    p (deepRealUnit hp5 hζ u hdeep)
      (realCircularUnitFamily hζ (by omega)) C

/-- Vandiver's actual Bernoulli coefficients, bundled for the
full-valuation kernel. -/
theorem bernoulli_two_mul_ne_zero (k : ℕ) (hk : k ≠ 0) :
    bernoulli (2 * k) ≠ 0 := by
  have hsum := hasSum_zeta_nat hk
  have hpositive :
      0 < ∑' n : ℕ, 1 / (n : ℝ) ^ (2 * k) := by
    exact hsum.summable.tsum_pos
      (fun n ↦ by positivity) 1 (by norm_num)
  have heq := hsum.tsum_eq
  intro hzero
  rw [hzero] at heq
  norm_num at heq
  have heq' :
      (∑' n : ℕ, 1 / (n : ℝ) ^ (2 * k)) = 0 := by
    simpa only [one_div] using heq
  rw [heq'] at hpositive
  exact lt_irrefl 0 hpositive

theorem vandiverBernoulliNumerator_ne_zero
    (i : SourceIndex p) :
    vandiverBernoulliNumerator p i ≠ 0 := by
  apply Rat.num_ne_zero.mpr
  rw [show (2 * sourceNumber i) * p =
      2 * (sourceNumber i * p) by ring]
  apply bernoulli_two_mul_ne_zero
  exact Nat.mul_ne_zero (by simp [sourceNumber])
    (Fact.out : p.Prime).ne_zero

def vandiverCoefficientFamily :
    KummerFullValuation.CoefficientFamily p (SourceIndex p) where
  B := vandiverBernoulliNumerator p
  B_ne_zero := vandiverBernoulliNumerator_ne_zero

/-- Compiler-ready statement of the remaining adaptive derivative theorem:
every primitive relation for the exact deep unit has precision one step
beyond the complete valuation of its Bernoulli coordinate. -/
def CanonicalBernoulliAdaptivePrecision
    (hp5 : 5 ≤ p) {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (u : (𝓞 K)ˣ) (hdeep : IsVandiverDeep hζ u) : Prop :=
  CanonicalFullValuationCongruences hp5 hζ u hdeep
    vandiverCoefficientFamily

/-- The adaptive precision demanded by full normalization is exactly
coordinatewise exponent divisibility.  This audit lemma prevents treating
the source congruence as if it were a weaker, automatic consequence of the
diagonal automorphism. -/
theorem fullPrecision_iff_exponents_dvd
    (C : KummerFullValuation.CoefficientFamily p
      (Fin ((p - 3) / 2)))
    (a : Fin ((p - 3) / 2) → ℤ) :
    (∀ i, (p : ℤ) ^ (C.valuation i + 1) ∣ a i * C.B i) ↔
      ∀ i, (p : ℤ) ∣ a i := by
  constructor
  · exact C.exponents_dvd_of_full_precision
      (Fact.out : p.Prime) a
  · intro hdiv i
    obtain ⟨b, hb⟩ := hdiv i
    refine ⟨b * C.normalizedQuotient i, ?_⟩
    rw [hb, C.B_eq_pow_mul_normalizedQuotient, pow_succ]
    ring

/-- The generic Sinnott family, odd-power normalization, and an adaptive
logarithmic-derivative theorem construct the literal primitive finite
relation expected by the all-`p`-adic kernel. -/
theorem exists_ambient_primitive_fullValuationRelation
    (hp5 : 5 ≤ p) {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (u : (𝓞 K)ˣ) (hdeep : IsVandiverDeep hζ u)
    (C : KummerFullValuation.CoefficientFamily p
      (Fin ((p - 3) / 2)))
    (hprecision :
      CanonicalFullValuationCongruences hp5 hζ u hdeep C) :
    ∃ (t : ℕ) (a : Fin ((p - 3) / 2) → ℤ),
      0 < t ∧
      u ^ t =
        ∏ i, circularUnitFamily hζ (by omega) i ^ a i ∧
      ¬(p ∣ t ∧ ∀ i, (p : ℤ) ∣ a i) ∧
      ∀ i, (p : ℤ) ^ (C.valuation i + 1) ∣ a i * C.B i := by
  let uReal : NumberField.IsCMField.realUnits K :=
    deepRealUnit hp5 hζ u hdeep
  let EReal :
      Fin ((p - 3) / 2) →
        NumberField.IsCMField.realUnits K :=
    realCircularUnitFamily hζ (by omega)
  letI :
      (Subgroup.closure (Set.range EReal)).FiniteIndex := by
    simpa only [EReal] using
      real_closure_finiteIndex (by omega : 2 < p) hζ
  obtain ⟨a, ht, hrel⟩ :=
    KummerFullValuation.RootExtraction.exists_index_relation
      EReal uReal
  obtain ⟨t, a, ht, hrel, hprimitive⟩ :=
    KummerFullValuation.RootExtraction.exists_primitive_relation_of_relation
      (Fact.out : p.Prime).two_le
      (Fermat.Irregular.VandiverRealUnits.odd_pow_injective
        (K := K) p
        ((Fact.out : p.Prime).odd_of_ne_two (by omega)))
      uReal EReal a ht hrel
  have hfull :
      ∀ i, (p : ℤ) ^ (C.valuation i + 1) ∣
        a i * C.B i :=
    hprecision t a ht hrel hprimitive
  refine ⟨t, a, ht, ?_, hprimitive, hfull⟩
  have hrel' := congrArg
    ((↑) : NumberField.IsCMField.realUnits K → (𝓞 K)ˣ) hrel
  simpa only [uReal, EReal, deepRealUnit_coe,
    realCircularUnitFamily_coe, Subgroup.coe_pow,
    Subgroup.coe_zpow, SubmonoidClass.coe_finsetProd] using hrel'

/-- Exact existential package currently requested by the Case-II splice,
now with its index, family, and coefficient system constructed
canonically. -/
theorem exists_canonicalBernoulli_fullValuationRelation
    (hp5 : 5 ≤ p) {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (u : (𝓞 K)ˣ) (hdeep : IsVandiverDeep hζ u)
    (hadaptive :
      CanonicalBernoulliAdaptivePrecision hp5 hζ u hdeep) :
    ∃ (n : ℕ) (E : Fin n → (𝓞 K)ˣ)
      (C : KummerFullValuation.CoefficientFamily p (Fin n))
      (t : ℕ) (a : Fin n → ℤ),
      0 < t ∧
      u ^ t = ∏ i, E i ^ a i ∧
      ¬(p ∣ t ∧ ∀ i, (p : ℤ) ∣ a i) ∧
      ∀ i, (p : ℤ) ^ (C.valuation i + 1) ∣ a i * C.B i := by
  obtain ⟨t, a, ht, hrel, hprimitive, hfull⟩ :=
    exists_ambient_primitive_fullValuationRelation
      hp5 hζ u hdeep vandiverCoefficientFamily hadaptive
  exact
    ⟨(p - 3) / 2, circularUnitFamily hζ (by omega),
      vandiverCoefficientFamily, t, a,
      ht, hrel, hprimitive, hfull⟩

/-- Direct root-extraction consequence of the same source theorem.  This
regresses that the finite family and the full-valuation automorphism compose
without any additional regular-prime assumption. -/
theorem isPower_of_deep_of_canonicalFullValuationCongruences
    (hp5 : 5 ≤ p) {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (u : (𝓞 K)ˣ) (hdeep : IsVandiverDeep hζ u)
    (C : KummerFullValuation.CoefficientFamily p
      (Fin ((p - 3) / 2)))
    (hprecision :
      CanonicalFullValuationCongruences hp5 hζ u hdeep C) :
    ∃ v : (𝓞 K)ˣ, u = v ^ p := by
  obtain ⟨t, a, _ht, hrel, hprimitive, hfull⟩ :=
    exists_ambient_primitive_fullValuationRelation
      hp5 hζ u hdeep C hprecision
  exact
    KummerFullValuation.isPower_of_primitive_relation_and_fullValuationCorrection
      (Fact.out : p.Prime) C u
        (circularUnitFamily hζ (by omega)) a
        hrel hprimitive hfull

end

end Fermat.KummerIso.UnitAdaptiveRelationHarness
