/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, Codex

# Selmer classes from integral ideal powers

An equality `I ^ n = (q)` of integral ideals forces the height-one
valuation of `q` to be divisible by `n` at every place.  This file turns
that elementary ideal-theoretic receipt into the literal empty-support
Dedekind Selmer class represented by `q` in the Kummer quotient.

The construction uses Mathlib's actual `IsDedekindDomain.selmerGroup` and
the public quotient-valuation criterion.  No parallel carrier or supplied
local condition is introduced.
-/
import Fermat.Conservation.SelmerEigenspace
import Fermat.Conservation.SelmerSequence

open scoped nonZeroDivisors

noncomputable section

namespace Fermat.Conservation.IdealPowerSelmer

universe uR uK

variable {R : Type uR} [CommRing R] [IsDedekindDomain R]
  {K : Type uK} [Field K] [Algebra R K] [IsFractionRing R K]

/-- A nonzero integral element, viewed as a unit of the fraction field. -/
noncomputable def integralFieldUnit (q : R) (hq : q ≠ 0) : Kˣ :=
  Units.mk0 (algebraMap R K q) (by
    intro hzero
    apply hq
    apply IsFractionRing.injective R K
    simpa using hzero)

/-- The underlying field element of `integralFieldUnit` is the original
integral element after the canonical algebra map. -/
@[simp]
theorem integralFieldUnit_val (q : R) (hq : q ≠ 0) :
    ((integralFieldUnit (K := K) q hq : Kˣ) : K) = algebraMap R K q :=
  rfl

/-- Public generic spelling of the principal-fractional-ideal coordinate
formula used privately in the Dedekind Selmer exact sequence. -/
theorem count_spanSingleton_eq_neg_valuation
    (v : IsDedekindDomain.HeightOneSpectrum R) (x : Kˣ) :
    FractionalIdeal.count K v
        (FractionalIdeal.spanSingleton R⁰ (x : K)) =
      -(v.valuationOfNeZero x).toAdd := by
  let s := IsLocalization.sec R⁰ (x : K)
  have hs : FractionalIdeal.spanSingleton R⁰ (x : K) =
      FractionalIdeal.spanSingleton R⁰
          (algebraMap R K (s.2 : R))⁻¹ *
        (Ideal.span {s.1} : FractionalIdeal R⁰ K) := by
    rw [FractionalIdeal.coeIdeal_span_singleton,
      FractionalIdeal.spanSingleton_mul_spanSingleton]
    congr 1
    symm
    rw [inv_mul_eq_iff_eq_mul₀ (map_ne_zero_of_mem_nonZeroDivisors _
      (IsFractionRing.injective R K) s.2.property)]
    exact IsLocalization.sec_spec' R⁰ (x : K)
  rw [FractionalIdeal.count_well_defined K v
    (FractionalIdeal.spanSingleton_ne_zero_iff.mpr x.ne_zero) hs]
  simp [IsDedekindDomain.HeightOneSpectrum.valuationOfNeZero,
    IsDedekindDomain.HeightOneSpectrum.valuationOfNeZeroToFun, s]
  ring

/-- If `I ^ n` is the principal ideal generated by a nonzero integral
element `q`, then every height-one valuation of `q` is divisible by `n`. -/
theorem valuation_dvd_of_ideal_pow_eq_span
    {n : ℕ} (q : R) (hq : q ≠ 0) (I : Ideal R)
    (hpow : I ^ n = Ideal.span {q})
    (v : IsDedekindDomain.HeightOneSpectrum R) :
    (n : ℤ) ∣
      (v.valuationOfNeZero (integralFieldUnit (K := K) q hq)).toAdd := by
  have hfractional :
      (I : FractionalIdeal R⁰ K) ^ n =
        FractionalIdeal.spanSingleton R⁰
          (integralFieldUnit (K := K) q hq : K) := by
    calc
      (I : FractionalIdeal R⁰ K) ^ n =
          ((I ^ n : Ideal R) : FractionalIdeal R⁰ K) := by
        rw [FractionalIdeal.coeIdeal_pow]
      _ = ((Ideal.span {q} : Ideal R) : FractionalIdeal R⁰ K) := by
        exact congrArg
          (fun J : Ideal R ↦ (J : FractionalIdeal R⁰ K)) hpow
      _ = FractionalIdeal.spanSingleton R⁰ (algebraMap R K q) := by
        exact FractionalIdeal.coeIdeal_span_singleton q
      _ = FractionalIdeal.spanSingleton R⁰
          (integralFieldUnit (K := K) q hq : K) := by
        rw [integralFieldUnit_val]
  have hcount := congrArg (FractionalIdeal.count K v) hfractional
  rw [FractionalIdeal.count_pow,
    count_spanSingleton_eq_neg_valuation] at hcount
  refine ⟨-FractionalIdeal.count K v (I : FractionalIdeal R⁰ K), ?_⟩
  linarith

/-- The literal empty-support Dedekind Selmer class represented by `q`.
Its local condition is manufactured from the ideal-power equality. -/
noncomputable def emptySelmerClassOfIdealPower
    {n : ℕ} [Fact n.Prime] (q : R) (hq : q ≠ 0) (I : Ideal R)
    (hpow : I ^ n = Ideal.span {q}) :
    IsDedekindDomain.selmerGroup
      (R := R) (K := K)
      (S := (∅ : Set (IsDedekindDomain.HeightOneSpectrum R))) (n := n) :=
  ⟨QuotientGroup.mk (integralFieldUnit (K := K) q hq), by
    intro v _
    exact
      (Fermat.Conservation.SelmerEigenspace.valuationOfNeZeroMod_mk_eq_one_iff_dvd
        (p := n) v (integralFieldUnit (K := K) q hq)).mpr
          (valuation_dvd_of_ideal_pow_eq_span q hq I hpow v)⟩

/-- Exact Kummer-quotient readback: the constructed Selmer class is the
class of the embedded integral element `q`. -/
@[simp]
theorem emptySelmerClassOfIdealPower_val
    {n : ℕ} [Fact n.Prime] (q : R) (hq : q ≠ 0) (I : Ideal R)
    (hpow : I ^ n = Ideal.span {q}) :
    (emptySelmerClassOfIdealPower (K := K) q hq I hpow).1 =
      QuotientGroup.mk (integralFieldUnit (K := K) q hq) :=
  rfl

/-- Exact local-condition readback at every height-one place. -/
theorem emptySelmerClassOfIdealPower_valuation
    {n : ℕ} [Fact n.Prime] (q : R) (hq : q ≠ 0) (I : Ideal R)
    (hpow : I ^ n = Ideal.span {q})
    (v : IsDedekindDomain.HeightOneSpectrum R) :
    v.valuationOfNeZeroMod n
        (emptySelmerClassOfIdealPower (K := K) q hq I hpow).1 = 1 :=
  (emptySelmerClassOfIdealPower (K := K) q hq I hpow).property v
    (Set.notMem_empty v)

/-! ## Class-group readback -/

omit [IsDedekindDomain R] in
/-- The allocated ideal in an ideal-power presentation is nonzero whenever
its principal generator is nonzero. -/
theorem ideal_ne_zero_of_pow_eq_span
    {n : ℕ} [Fact n.Prime] (q : R) (hq : q ≠ 0) (I : Ideal R)
    (hpow : I ^ n = Ideal.span {q}) : I ≠ 0 := by
  intro hzero
  have hspan : Ideal.span {q} = 0 := by
    rw [← hpow, hzero, zero_pow ((Fact.out : n.Prime).ne_zero)]
  change Ideal.span {q} = ⊥ at hspan
  rw [Ideal.span_singleton_eq_bot] at hspan
  exact hq hspan

/-- The nonzero integral ideal, bundled as a unit of the fractional-ideal
group used by the class-group quotient. -/
noncomputable def idealFractionalUnit
    (I : Ideal R) (hI : I ≠ 0) : (FractionalIdeal R⁰ K)ˣ :=
  Units.mk0 (I : FractionalIdeal R⁰ K) (by
    intro hzero
    rw [FractionalIdeal.coeIdeal_eq_zero] at hzero
    exact hI hzero)

@[simp]
theorem idealFractionalUnit_val
    (I : Ideal R) (hI : I ≠ 0) :
    ((idealFractionalUnit (K := K) I hI :
      (FractionalIdeal R⁰ K)ˣ) : FractionalIdeal R⁰ K) = I :=
  rfl

/-- The bundled allocated ideal is exactly an `n`th root of the principal
fractional ideal of the embedded radicand. -/
theorem idealFractionalUnit_pow_eq_toPrincipalIdeal
    {n : ℕ} [Fact n.Prime] (q : R) (hq : q ≠ 0) (I : Ideal R)
    (hpow : I ^ n = Ideal.span {q}) :
    idealFractionalUnit (K := K) I
          (ideal_ne_zero_of_pow_eq_span q hq I hpow) ^ n =
      toPrincipalIdeal R K
        (integralFieldUnit (K := K) q hq) := by
  apply Units.ext
  simp only [Units.val_pow_eq_pow_val, idealFractionalUnit_val,
    coe_toPrincipalIdeal]
  calc
    (I : FractionalIdeal R⁰ K) ^ n =
        ((I ^ n : Ideal R) : FractionalIdeal R⁰ K) := by
      rw [FractionalIdeal.coeIdeal_pow]
    _ = ((Ideal.span {q} : Ideal R) : FractionalIdeal R⁰ K) := by
      exact congrArg
        (fun J : Ideal R ↦ (J : FractionalIdeal R⁰ K)) hpow
    _ = FractionalIdeal.spanSingleton R⁰ (algebraMap R K q) := by
      exact FractionalIdeal.coeIdeal_span_singleton q
    _ = FractionalIdeal.spanSingleton R⁰
        (integralFieldUnit (K := K) q hq : K) := by
      rw [integralFieldUnit_val]

/-- Exact class-group receipt: the Selmer obstruction of the radicand is the
class of the same ideal whose `n`th power generated it. -/
theorem emptySelmerClassOfIdealPower_toClass
    {n : ℕ} [Fact n.Prime] [Fact (0 < n)]
    (q : R) (hq : q ≠ 0) (I : Ideal R)
    (hpow : I ^ n = Ideal.span {q}) :
    IsDedekindDomain.selmerGroup.toClass
        (R := R) (K := K) (n := n)
        (emptySelmerClassOfIdealPower (K := K) q hq I hpow) =
      ClassGroup.mk K
        (idealFractionalUnit (K := K) I
          (ideal_ne_zero_of_pow_eq_span q hq I hpow)) := by
  exact IsDedekindDomain.selmerGroup.toClass_eq_mk_of_representative_root
    (R := R) (K := K) (n := n)
    (emptySelmerClassOfIdealPower (K := K) q hq I hpow)
    (integralFieldUnit (K := K) q hq) rfl
    (idealFractionalUnit (K := K) I
      (ideal_ne_zero_of_pow_eq_span q hq I hpow))
    (idealFractionalUnit_pow_eq_toPrincipalIdeal q hq I hpow)

end Fermat.Conservation.IdealPowerSelmer
