/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, OpenAI

# Scalar readout only on actual Kummer cup classes

The discrete absolute-Galois `H²` used by the current Kummer--Tate algebra
contains classes unrelated to the Kummer inputs consumed by the wild pairing.
A total linear functional on that entire discrete cohomology group is therefore
stronger than the construction needs, and would require assigning values to
possibly discontinuous classes.

This file retains exactly the necessary cohomological receipt.  Given actual
left and right Kummer maps, `cupSpan` is the submodule of `H²` generated by
their oriented cup classes.  A linear scalar readout on only that submodule
already constructs the quotient-level wild pairing.  No continuous local
invariant, comparison theorem, reciprocity law, or value outside this span is
asserted here.
-/
import Fermat.Conservation.KummerOrientation
import Fermat.Conservation.WildKummerPairing

noncomputable section

namespace Fermat.Conservation.KummerCupSpanReadout

open groupCohomology
open Fermat.Conservation.TameSymbol

variable {p : ℕ} [Fact p.Prime]
variable {F G : Type} [Field F] [Group G]
variable (A : Rep (ZMod p) G)

/-- The degree-two class obtained by cupping the two actual Kummer images. -/
def cupClass
    (leftKummer : KummerClass p F →+
      H1 (KummerTateCup.trivialLine (k := ZMod p) (G := G)))
    (rightKummer : KummerClass p F →+ H1 A)
    (x y : KummerClass p F) : H2 A :=
  KummerTateCup.orientedCupH1Classes A (leftKummer x) (rightKummer y)

/-- The literal set of degree-two classes produced by pairs of actual Kummer
inputs.  Its linear span is the complete domain needed by a scalar readout. -/
def cupGenerators
    (leftKummer : KummerClass p F →+
      H1 (KummerTateCup.trivialLine (k := ZMod p) (G := G)))
    (rightKummer : KummerClass p F →+ H1 A) : Set (H2 A) :=
  {z | ∃ x y : KummerClass p F,
    z = cupClass A leftKummer rightKummer x y}

/-- The part of discrete `H²` actually visited by the Kummer--Tate pairing. -/
def cupSpan
    (leftKummer : KummerClass p F →+
      H1 (KummerTateCup.trivialLine (k := ZMod p) (G := G)))
    (rightKummer : KummerClass p F →+ H1 A) :
    Submodule (ZMod p) (H2 A) :=
  Submodule.span (ZMod p) (cupGenerators A leftKummer rightKummer)

/-- Every actual Kummer cup class lies in `cupSpan`. -/
theorem cupClass_mem_cupSpan
    (leftKummer : KummerClass p F →+
      H1 (KummerTateCup.trivialLine (k := ZMod p) (G := G)))
    (rightKummer : KummerClass p F →+ H1 A)
    (x y : KummerClass p F) :
    cupClass A leftKummer rightKummer x y ∈
      cupSpan A leftKummer rightKummer :=
  Submodule.subset_span ⟨x, y, rfl⟩

/-- An actual cup class, bundled with its proof of belonging to the retained
degree-two span. -/
def cupInSpan
    (leftKummer : KummerClass p F →+
      H1 (KummerTateCup.trivialLine (k := ZMod p) (G := G)))
    (rightKummer : KummerClass p F →+ H1 A)
    (x y : KummerClass p F) : cupSpan A leftKummer rightKummer :=
  ⟨cupClass A leftKummer rightKummer x y,
    cupClass_mem_cupSpan A leftKummer rightKummer x y⟩

@[simp]
theorem cupInSpan_coe
    (leftKummer : KummerClass p F →+
      H1 (KummerTateCup.trivialLine (k := ZMod p) (G := G)))
    (rightKummer : KummerClass p F →+ H1 A)
    (x y : KummerClass p F) :
    (cupInSpan A leftKummer rightKummer x y : H2 A) =
      cupClass A leftKummer rightKummer x y :=
  rfl

@[simp]
theorem cupInSpan_zero_left
    (leftKummer : KummerClass p F →+
      H1 (KummerTateCup.trivialLine (k := ZMod p) (G := G)))
    (rightKummer : KummerClass p F →+ H1 A)
    (y : KummerClass p F) :
    cupInSpan A leftKummer rightKummer 0 y = 0 := by
  apply Subtype.ext
  simp [cupInSpan, cupClass]

@[simp]
theorem cupInSpan_zero_right
    (leftKummer : KummerClass p F →+
      H1 (KummerTateCup.trivialLine (k := ZMod p) (G := G)))
    (rightKummer : KummerClass p F →+ H1 A)
    (x : KummerClass p F) :
    cupInSpan A leftKummer rightKummer x 0 = 0 := by
  apply Subtype.ext
  simp [cupInSpan, cupClass]

theorem cupInSpan_add_left
    (leftKummer : KummerClass p F →+
      H1 (KummerTateCup.trivialLine (k := ZMod p) (G := G)))
    (rightKummer : KummerClass p F →+ H1 A)
    (x₁ x₂ y : KummerClass p F) :
    cupInSpan A leftKummer rightKummer (x₁ + x₂) y =
      cupInSpan A leftKummer rightKummer x₁ y +
        cupInSpan A leftKummer rightKummer x₂ y := by
  apply Subtype.ext
  simp [cupInSpan, cupClass]

theorem cupInSpan_add_right
    (leftKummer : KummerClass p F →+
      H1 (KummerTateCup.trivialLine (k := ZMod p) (G := G)))
    (rightKummer : KummerClass p F →+ H1 A)
    (x y₁ y₂ : KummerClass p F) :
    cupInSpan A leftKummer rightKummer x (y₁ + y₂) =
      cupInSpan A leftKummer rightKummer x y₁ +
        cupInSpan A leftKummer rightKummer x y₂ := by
  apply Subtype.ext
  simp [cupInSpan, cupClass]

/-- A scalar readout defined only where the Kummer pairing needs it.  This is
not named or claimed to be the continuous local invariant. -/
abbrev SpanReadout
    (leftKummer : KummerClass p F →+
      H1 (KummerTateCup.trivialLine (k := ZMod p) (G := G)))
    (rightKummer : KummerClass p F →+ H1 A) :=
  cupSpan A leftKummer rightKummer →ₗ[ZMod p] ZMod p

/-- A linear readout on the actual Kummer cup span is sufficient to construct
the total bilinear pairing on Kummer quotients. -/
def localPairing
    (leftKummer : KummerClass p F →+
      H1 (KummerTateCup.trivialLine (k := ZMod p) (G := G)))
    (rightKummer : KummerClass p F →+ H1 A)
    (readout : SpanReadout A leftKummer rightKummer) :
    WildKummerPairing.Pairing p F where
  toFun x :=
    { toFun := fun y ↦ readout (cupInSpan A leftKummer rightKummer x y)
      map_zero' := by
        rw [cupInSpan_zero_right, map_zero]
      map_add' := by
        intro y₁ y₂
        rw [cupInSpan_add_right, map_add] }
  map_zero' := by
    apply AddMonoidHom.ext
    intro y
    change readout (cupInSpan A leftKummer rightKummer 0 y) = 0
    rw [cupInSpan_zero_left, map_zero]
  map_add' := by
    intro x₁ x₂
    apply AddMonoidHom.ext
    intro y
    change readout (cupInSpan A leftKummer rightKummer (x₁ + x₂) y) =
      readout (cupInSpan A leftKummer rightKummer x₁ y) +
        readout (cupInSpan A leftKummer rightKummer x₂ y)
    rw [cupInSpan_add_left, map_add]

/-- Readback of the span-restricted quotient pairing. -/
@[simp]
theorem localPairing_apply
    (leftKummer : KummerClass p F →+
      H1 (KummerTateCup.trivialLine (k := ZMod p) (G := G)))
    (rightKummer : KummerClass p F →+ H1 A)
    (readout : SpanReadout A leftKummer rightKummer)
    (x y : KummerClass p F) :
    localPairing A leftKummer rightKummer readout x y =
      readout (cupInSpan A leftKummer rightKummer x y) :=
  rfl

/-! ## Genuine discrete Kummer specialization -/

variable (F)

/-- The retained degree-two span for the genuine discrete Kummer maps. -/
abbrev discreteCupSpan
    (zeta : F) (hzeta : IsPrimitiveRoot zeta p) :
    Submodule (ZMod p)
      (H2 (LocalKummerH1.rootsRepresentation p F)) :=
  cupSpan (LocalKummerH1.rootsRepresentation p F)
    (KummerOrientation.leftKummerMap p F zeta hzeta)
    (LocalKummerH1.map p F)

/-- A primitive root and a scalar readout on only the genuine Kummer cup span
produce the discrete quotient pairing. -/
def discretePairing
    (zeta : F) (hzeta : IsPrimitiveRoot zeta p)
    (readout : discreteCupSpan F zeta hzeta →ₗ[ZMod p] ZMod p) :
    WildKummerPairing.Pairing p F :=
  localPairing (LocalKummerH1.rootsRepresentation p F)
    (KummerOrientation.leftKummerMap p F zeta hzeta)
    (LocalKummerH1.map p F) readout

/-- Quotient-level readback of the genuine span-restricted discrete pairing. -/
@[simp]
theorem discretePairing_apply
    (zeta : F) (hzeta : IsPrimitiveRoot zeta p)
    (readout : discreteCupSpan F zeta hzeta →ₗ[ZMod p] ZMod p)
    (x y : KummerClass p F) :
    discretePairing F zeta hzeta readout x y =
      readout
        (cupInSpan (LocalKummerH1.rootsRepresentation p F)
          (KummerOrientation.leftKummerMap p F zeta hzeta)
          (LocalKummerH1.map p F) x y) :=
  rfl

/-- Representative readback with both genuine Kummer classes exposed. -/
@[simp]
theorem discretePairing_classOfUnit
    (zeta : F) (hzeta : IsPrimitiveRoot zeta p)
    (readout : discreteCupSpan F zeta hzeta →ₗ[ZMod p] ZMod p)
    (a b : Fˣ) :
    discretePairing F zeta hzeta readout
        (WildKummerPairing.classOfUnit p F (Additive.ofMul a))
        (WildKummerPairing.classOfUnit p F (Additive.ofMul b)) =
      readout
        (cupInSpan (LocalKummerH1.rootsRepresentation p F)
          (KummerOrientation.leftKummerMap p F zeta hzeta)
          (LocalKummerH1.map p F)
          (WildKummerPairing.classOfUnit p F (Additive.ofMul a))
          (WildKummerPairing.classOfUnit p F (Additive.ofMul b))) :=
  rfl

end Fermat.Conservation.KummerCupSpanReadout
