/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, Fable

# Executable audit for the twisted linking stage

This non-imported leaf checks the linking W1--W5 and common-action W0--W3
public surfaces, the intended proof-value dependency direction, and the
standard-axiom boundary.  In particular, strict-route perfect return is
refuted upstream and is obtained only through the explicit swap quotient map.
-/
import Fermat.Conservation.GuardDependsOn
import Fermat.Conservation.CommonActionStage
import Fermat.Conservation.LinkingInterfaces
import Fermat.Conservation.SwapQuotient
import Fermat.Conservation.TransverseAnnihilator

open Fermat.Conservation

/-! ## Public linking surface -/

#check InvolutiveBase.TeichmullerData
#check InvolutiveBase.GroupAlgebra
#check InvolutiveBase.hash
#check InvolutiveBase.hash_apply
#check InvolutiveBase.hash_hash
#check InvolutiveBase.reflectionPairing
#check InvolutiveBase.reflection_conservation_law
#check InvolutiveBase.reflectedCharacter
#check InvolutiveBase.characterIdempotent
#check InvolutiveBase.characterIdempotent_isIdempotent
#check InvolutiveBase.hash_characterIdempotent
#check InvolutiveBase.hash_trivialCharacterIdempotent
#check InvolutiveBase.plusProjector
#check InvolutiveBase.minusProjector
#check InvolutiveBase.plusProjector_isIdempotent
#check InvolutiveBase.minusProjector_isIdempotent
#check InvolutiveBase.hash_conjugationElement
#check InvolutiveBase.plus_minus_projectors_exchanged

#check RouteAlgebra.HasSharp
#check RouteAlgebra.teichmullerSharp
#check RouteAlgebra.mathlibSkewPolynomialRoute
#check RouteAlgebra.Route
#check RouteAlgebra.route_covariance
#check RouteAlgebra.closedRoute
#check RouteAlgebra.closedRoute_central
#check RouteAlgebra.closedRoute_ne_one
#check RouteAlgebra.CanonicalPathPresentation
#check RouteAlgebra.CanonicalPathPresentation.closedAtChi
#check RouteAlgebra.CanonicalPathPresentation.closedAtReflected
#check RouteAlgebra.BaseCorner
#check RouteAlgebra.RouteCorner
#check RouteAlgebra.routeCorner_coeff_odd_eq_zero
#check RouteAlgebra.cornerClosedRoute
#check RouteAlgebra.cornerPolynomialMap
#check RouteAlgebra.cornerToPolynomial
#check RouteAlgebra.cornerPolynomialEquiv
#check RouteAlgebra.cornerPolynomialEquiv_X
#check RouteAlgebra.teichmullerSharp_characterIdempotent
#check RouteAlgebra.characterCornerPolynomialEquiv

#check SwapQuotient.swapIdeal
#check SwapQuotient.Swap
#check SwapQuotient.quotientMap
#check SwapQuotient.generator
#check SwapQuotient.coefficient
#check SwapQuotient.sevenARouteWord
#check SwapQuotient.sevenDRouteWord
#check SwapQuotient.sevenARelationWord
#check SwapQuotient.sevenDRelationWord
#check SwapQuotient.sevenARelationWord_image
#check SwapQuotient.sevenDRelationWord_image
#check SwapQuotient.quotientMap_closedRoute
#check SwapQuotient.generator_sq
#check SwapQuotient.generator_coefficient
#check SwapQuotient.flowElement
#check SwapQuotient.flowElement_two
#check SwapQuotient.piCommon
#check SwapQuotient.piDifference
#check SwapQuotient.piCommon_add_piDifference
#check SwapQuotient.piCommon_idempotent
#check SwapQuotient.piDifference_idempotent
#check SwapQuotient.piCommon_piDifference_orthogonal
#check SwapQuotient.sevenARelationWord_eigenspace
#check SwapQuotient.sevenDRelationWord_eigenspace
#check SwapQuotient.swapLinear
#check SwapQuotient.swapLinear_sq
#check SwapQuotient.commonDifference
#check SwapQuotient.commonDifference_swap
#check SwapQuotient.commonProjector_formula
#check SwapQuotient.differenceProjector_formula
#check SwapQuotient.sevenARelationOperator_apply
#check SwapQuotient.sevenDRelationOperator_apply
#check SwapQuotient.flowOperator
#check SwapQuotient.flowOperator_apply
#check SwapQuotient.flowOperator_two

#check TransverseAnnihilator.CornerService.BezoutCertificate
#check TransverseAnnihilator.CornerService.eq_zero_of_annihilates_of_bezout
#check TransverseAnnihilator.CornerService.bezout_identity_in_ambient
#check TransverseAnnihilator.CornerService.eq_zero_in_idempotentCorner
#check TransverseAnnihilator.CornerService.LivelockCarrier
#check TransverseAnnihilator.CornerService.livelockCarrier_subsingleton_iff
#check TransverseAnnihilator.CornerService.livelockCarrier_nontrivial_iff
#check TransverseAnnihilator.CornerService.CornerLivelockChannel
#check TransverseAnnihilator.CornerService.nonempty_cornerLivelockChannel_iff
#check TransverseAnnihilator.breaksCycle_iff_polynomialGCD_eq_one
#check TransverseAnnihilator.polynomial_livelockCarrier_subsingleton_iff
#check TransverseAnnihilator.nonempty_polynomial_cornerLivelockChannel_iff
#check TransverseAnnihilator.eq_zero_of_cycle_and_transverse_gcd_eq_one

#check LinkingInterfaces.IntegralPadicGroupAlgebra
#check LinkingInterfaces.IntegralStickelbergerIdeal
#check LinkingInterfaces.IntegralStickelbergerIdeal.SharpTransformationGuard
#check LinkingInterfaces.sharp_trivialProjector_eq_omegaProjector
#check LinkingInterfaces.FilteredStickelbergerCarrier
#check LinkingInterfaces.FilteredStickelbergerCarrier.smul_mem_unitRange
#check LinkingInterfaces.FilteredStickelbergerCarrier.classProjection_smul_eq_zero
#check LinkingInterfaces.FilteredStickelbergerCarrier.conversionReceipt
#check LinkingInterfaces.StrictRouteArithmeticRepresentation
#check LinkingInterfaces.WithheldStrictRouteArithmeticRepresentation
#check LinkingInterfaces.ReflectedSelmerArithmeticRepresentationTarget

/-! ## Common-action stage surface -/

#check CommonActionStage.UnitModP
#check CommonActionStage.Selmer
#check CommonActionStage.ClassPTorsion
#check CommonActionStage.unitInclusion
#check CommonActionStage.unitInclusion_injective
#check CommonActionStage.realUnitClass
#check CommonActionStage.realUnitInclusion
#check CommonActionStage.SelmerClassSequenceRealization
#check CommonActionStage.WithheldSelmerClassSequenceRealization
#check CommonActionStage.SelmerCharacterDual
#check CommonActionStage.ExactFilteredLeg
#check CommonActionStage.ReflectedDualRealization
#check CommonActionStage.ExactFilteredPair
#check CommonActionStage.ReflectedExactFilteredPair
#check CommonActionStage.ExactFilteredPair.Carrier
#check CommonActionStage.ExactFilteredPair.unitInclusion
#check CommonActionStage.ExactFilteredPair.classProjection
#check CommonActionStage.ExactFilteredPair.unitInclusion_injective
#check CommonActionStage.ExactFilteredPair.exact_at_carrier
#check CommonActionStage.ExactFilteredPair.classProjection_surjective
#check CommonActionStage.ExactFilteredPair.liftClassPair
#check CommonActionStage.ExactFilteredPair.classProjection_liftClassPair
#check CommonActionStage.ExactFilteredPair.filtration
#check CommonActionStage.ExactFilteredPair.antitone_filtration
#check CommonActionStage.ExactFilteredPair.class_p_torsion
#check CommonActionStage.KummerCharacterLegCompatibility
#check CommonActionStage.KummerPairedBinding
#check CommonActionStage.exactLegOfFilteredStickelbergerCarrier
#check CommonActionStage.IntegralReflectionInput
#check CommonActionStage.IntegralReflectionInput.sharpTransport
#check CommonActionStage.IntegralReflectionInput.sharpTransport_coe
#check CommonActionStage.GuardedPairedCarrier
#check CommonActionStage.GuardedPairedCarrier.exactPair
#check CommonActionStage.GuardedPairedCarrier.chiConversionReceipt
#check CommonActionStage.GuardedPairedCarrier.reflectedDualConversionReceipt
#check CommonActionStage.GuardedPairedCarrier.pairedConversionReceipts
#check CommonActionStage.lambdaAction
#check CommonActionStage.lambdaAction_apply
#check CommonActionStage.deltaAction
#check CommonActionStage.deltaAction_apply
#check CommonActionStage.RouteMaps
#check CommonActionStage.RouteMaps.closedAtChi
#check CommonActionStage.RouteMaps.closedAtReflected
#check CommonActionStage.RouteMaps.openRoute
#check CommonActionStage.RouteMaps.openRoute_apply
#check CommonActionStage.RouteMaps.openRoute_sq_apply
#check CommonActionStage.RouteMaps.ofArithmeticRepresentation
#check CommonActionStage.RouteMaps.rho_routeSquared_eq_closed
#check CommonActionStage.reflectionCycleCorner
#check CommonActionStage.reflectionCycleCorner_eq
#check CommonActionStage.StrictReflectionCycleReceipt
#check CommonActionStage.StrictReflectionCycleReceiptTarget
#check CommonActionStage.baseCornerProjection
#check CommonActionStage.stickelbergerCorner
#check CommonActionStage.stickelbergerCorner_val
#check CommonActionStage.cornerCoefficient_smul_eq
#check CommonActionStage.CornerConversionReceipt
#check CommonActionStage.cornerConversionReceipt
#check CommonActionStage.cornerConversionReceipt_beta
#check CommonActionStage.classProjection_cornerCoefficient_smul_eq_zero
#check CommonActionStage.StateConversionCompatibility
#check CommonActionStage.StateConversionCompatibility.conversionReceipt_beta_eq_state_beta
#check CommonActionStage.GuardedPairedCarrier.pairedCornerConversionReceipts
#check CommonActionStage.AllocatedClass
#check CommonActionStage.classSwap
#check CommonActionStage.sevenDClassOperator
#check CommonActionStage.classCornerIdempotent
#check CommonActionStage.ClassActionCorner
#check CommonActionStage.sevenDClassCornerElement
#check CommonActionStage.differenceGauge
#check CommonActionStage.sevenDClassShadowReceipt
#check CommonActionStage.allocatedRootSource
#check CommonActionStage.allocatedRootState
#check CommonActionStage.allocatedRootState_receipts
#check CommonActionStage.allocatedRootState_class
#check CommonActionStage.allocatedRootState_source_eq
#check CommonActionStage.allocatedClassObstruction
#check CommonActionStage.allocatedSevenDClassReceipt
#check CommonActionStage.allocatedSevenDReceiptedRootState
#check CommonActionStage.allocatedSevenDReceiptedRootState_receipt
#check CommonActionStage.allocatedSevenDClassReceipt_payload
#check CommonActionStage.allocatedRootClassPTorsion
#check CommonActionStage.CharacterClassAllocation
#check CommonActionStage.allocatedCharacterClassObstruction
#check CommonActionStage.allocatedSelmerObstruction
#check CommonActionStage.classProjection_allocatedSelmerObstruction
#check CommonActionStage.Outcome.UnitIdealResult
#check CommonActionStage.Outcome.unitIdealResult
#check CommonActionStage.Outcome.SurvivingChannelResult
#check CommonActionStage.Outcome.WallAddress
#check CommonActionStage.Outcome.LocalizedWall
#check CommonActionStage.Outcome.TypedResult
#check CommonActionStage.Outcome.PolynomialTypedResult
#check CommonActionStage.reflectedSelmerRhoWall
#check CommonActionStage.reflectedSelmerRhoWall_target

/-! ## Proof-value wiring -/

#guard_depends_on InvolutiveBase.hash_hash,
  InvolutiveBase.hashHom_comp_self
#guard_depends_on InvolutiveBase.reflection_conservation_law,
  InvolutiveBase.reflectionPairing
#guard_depends_on InvolutiveBase.characterIdempotent_isIdempotent,
  InvolutiveBase.groupAverage_isIdempotent
#guard_depends_on InvolutiveBase.hash_characterIdempotent,
  InvolutiveBase.reflectedCharacter
#guard_depends_on InvolutiveBase.hash_trivialCharacterIdempotent,
  InvolutiveBase.hash_characterIdempotent
#guard_depends_on InvolutiveBase.plus_minus_projectors_exchanged,
  InvolutiveBase.hash_conjugationElement

#guard_depends_on RouteAlgebra.closedRoute_central,
  RouteAlgebra.phi_sq
#guard_depends_on RouteAlgebra.closedRoute_ne_one,
  SkewPolynomial.coeff_monomial
#guard_depends_on RouteAlgebra.routeCorner_coeff_odd_eq_zero,
  RouteAlgebra.odd_smul
#guard_depends_on RouteAlgebra.cornerPolynomialMap_surjective,
  RouteAlgebra.routeCorner_coeff_odd_eq_zero
#guard_depends_on RouteAlgebra.cornerPolynomialEquiv,
  RouteAlgebra.cornerPolynomialMap_surjective
#guard_depends_on RouteAlgebra.cornerPolynomialEquiv_X,
  RouteAlgebra.cornerPolynomialMap
#guard_depends_on RouteAlgebra.characterCornerPolynomialEquiv,
  RouteAlgebra.cornerPolynomialEquiv
#guard_depends_on RouteAlgebra.characterCornerPolynomialEquiv,
  InvolutiveBase.hash_characterIdempotent

#guard_depends_on SwapQuotient.quotientMap_closedRoute,
  TwoSidedIdeal.subset_span
#guard_depends_on SwapQuotient.sevenARelationWord_image,
  SwapQuotient.quotientMap
#guard_depends_on SwapQuotient.sevenDRelationWord_image,
  SwapQuotient.quotientMap
#guard_depends_on SwapQuotient.generator_sq,
  SwapQuotient.quotientMap_closedRoute
#guard_depends_on SwapQuotient.piCommon_idempotent,
  SwapQuotient.generator_sq
#guard_depends_on SwapQuotient.piDifference_idempotent,
  SwapQuotient.generator_sq
#guard_depends_on SwapQuotient.piCommon_piDifference_orthogonal,
  SwapQuotient.generator_sq
#guard_depends_on SwapQuotient.sevenARelationWord_eigenspace,
  SwapQuotient.sevenARelationWord_image
#guard_depends_on SwapQuotient.sevenARelationWord_eigenspace,
  SwapQuotient.generator_sq
#guard_depends_on SwapQuotient.sevenARelationWord_eigenspace,
  SwapQuotient.coefficientHalf_add_self
#guard_depends_on SwapQuotient.sevenDRelationWord_eigenspace,
  SwapQuotient.sevenDRelationWord_image
#guard_depends_on SwapQuotient.sevenDRelationWord_eigenspace,
  SwapQuotient.generator_sq
#guard_depends_on SwapQuotient.sevenDRelationWord_eigenspace,
  SwapQuotient.coefficientHalf_add_self
#guard_depends_on SwapQuotient.flowElement_two,
  SwapQuotient.flowElement
#guard_depends_on SwapQuotient.commonDifference_swap,
  SwapQuotient.swapLinear
#guard_depends_on SwapQuotient.commonProjector_formula,
  SwapQuotient.commonProjector
#guard_depends_on SwapQuotient.differenceProjector_formula,
  SwapQuotient.differenceProjector
#guard_depends_on SwapQuotient.sevenARelationOperator_apply,
  SwapQuotient.swapLinear
#guard_depends_on SwapQuotient.sevenDRelationOperator_apply,
  SwapQuotient.swapLinear
#guard_depends_on SwapQuotient.flowOperator_apply,
  Interaction.TwoAccount.step
#guard_depends_on SwapQuotient.flowOperator_two,
  Interaction.TwoAccount.step_two_eq_swap

#guard_depends_on
  TransverseAnnihilator.eq_zero_of_cycle_and_transverse_gcd_eq_one,
  TransverseAnnihilator.CornerService.eq_zero_of_annihilates_of_bezout
#guard_depends_on
  TransverseAnnihilator.CornerService.eq_zero_in_idempotentCorner,
  TransverseAnnihilator.CornerService.eq_zero_of_annihilates_of_bezout
#guard_depends_on
  TransverseAnnihilator.eq_zero_of_cycle_and_transverse_gcd_eq_one,
  TransverseAnnihilator.breaksCycle_iff_polynomialGCD_eq_one
#guard_depends_on
  TransverseAnnihilator.polynomial_livelockCarrier_subsingleton_iff,
  TransverseAnnihilator.CornerService.livelockCarrier_subsingleton_iff

#guard_depends_on
  LinkingInterfaces.sharp_trivialProjector_eq_omegaProjector,
  InvolutiveBase.hash_trivialCharacterIdempotent
#guard_depends_on
  LinkingInterfaces.FilteredStickelbergerCarrier.smul_mem_unitRange,
  LinkingInterfaces.FilteredStickelbergerCarrier.stickelberger_conversion
#guard_depends_on
  LinkingInterfaces.FilteredStickelbergerCarrier.classProjection_smul_eq_zero,
  LinkingInterfaces.FilteredStickelbergerCarrier.exact_at_carrier
#guard_depends_on
  LinkingInterfaces.FilteredStickelbergerCarrier.conversionReceipt,
  ClassCarrier.PrincipalizationReceipt.mk
#guard_depends_on
  LinkingInterfaces.FilteredStickelbergerCarrier.conversionReceipt_source_eq,
  ClassCarrier.PrincipalizationReceipt.source_eq
#guard_depends_on
  LinkingInterfaces.ArithmeticRepresentation.rho_routeSquared,
  LinkingInterfaces.ArithmeticRepresentation.rho_route
#guard_depends_on
  LinkingInterfaces.StrictRouteArithmeticRepresentation.rho_closedRoute,
  LinkingInterfaces.ArithmeticRepresentation.rho_routeSquared

/-! ## Common-action proof-value wiring -/

#guard_depends_on CommonActionStage.unitInclusion_injective,
  IsDedekindDomain.selmerGroup.fromUnitLift_injective
#guard_depends_on CommonActionStage.realUnitInclusion,
  CommonActionStage.realUnitClass
#guard_depends_on CommonActionStage.realUnitInclusion,
  CommonActionStage.unitInclusion
#guard_depends_on CommonActionStage.ExactFilteredPair.unitInclusion_injective,
  CommonActionStage.ExactFilteredLeg.unitInclusion_injective
#guard_depends_on CommonActionStage.ExactFilteredPair.exact_at_carrier,
  CommonActionStage.ExactFilteredLeg.exact_at_carrier
#guard_depends_on CommonActionStage.ExactFilteredPair.classProjection_surjective,
  CommonActionStage.ExactFilteredLeg.classProjection_surjective
#guard_depends_on CommonActionStage.ExactFilteredPair.classProjection_liftClassPair,
  CommonActionStage.ExactFilteredPair.classProjection_surjective
#guard_depends_on CommonActionStage.ExactFilteredPair.antitone_filtration,
  CommonActionStage.ExactFilteredLeg.antitone_filtration
#guard_depends_on CommonActionStage.ExactFilteredPair.class_p_torsion,
  CommonActionStage.ExactFilteredLeg.class_p_torsion
#guard_depends_on CommonActionStage.IntegralReflectionInput.sharpTransport,
  LinkingInterfaces.IntegralStickelbergerIdeal.SharpTransformationGuard.sharp_image_eq_omega_reflected
#guard_depends_on CommonActionStage.IntegralReflectionInput.sharpTransport,
  Ideal.mem_map_of_mem
#guard_depends_on CommonActionStage.IntegralReflectionInput.sharpTransport_coe,
  CommonActionStage.IntegralReflectionInput.sharpTransport
#guard_depends_on CommonActionStage.GuardedPairedCarrier.exactPair,
  CommonActionStage.exactLegOfFilteredStickelbergerCarrier
#guard_depends_on CommonActionStage.GuardedPairedCarrier.chiConversionReceipt,
  LinkingInterfaces.FilteredStickelbergerCarrier.conversionReceipt
#guard_depends_on
  CommonActionStage.GuardedPairedCarrier.reflectedDualConversionReceipt,
  LinkingInterfaces.FilteredStickelbergerCarrier.conversionReceipt
#guard_depends_on CommonActionStage.GuardedPairedCarrier.pairedConversionReceipts,
  CommonActionStage.IntegralReflectionInput.sharpTransport
#guard_depends_on CommonActionStage.GuardedPairedCarrier.pairedConversionReceipts,
  LinkingInterfaces.FilteredStickelbergerCarrier.conversionReceipt
#guard_depends_on CommonActionStage.lambdaAction_apply,
  CommonActionStage.lambdaAction
#guard_depends_on CommonActionStage.deltaAction,
  CommonActionStage.lambdaAction
#guard_depends_on CommonActionStage.deltaAction_apply,
  CommonActionStage.deltaAction
#guard_depends_on CommonActionStage.RouteMaps.closedAtChi,
  LinearMap.comp
#guard_depends_on CommonActionStage.RouteMaps.closedAtReflected,
  LinearMap.comp
#guard_depends_on CommonActionStage.RouteMaps.openRoute_apply,
  CommonActionStage.RouteMaps.openRoute
#guard_depends_on CommonActionStage.RouteMaps.openRoute_sq_apply,
  CommonActionStage.RouteMaps.openRoute_apply
#guard_depends_on CommonActionStage.RouteMaps.ofArithmeticRepresentation,
  LinkingInterfaces.ArithmeticRepresentation.routeChiToReflected
#guard_depends_on CommonActionStage.RouteMaps.rho_routeSquared_eq_closed,
  LinkingInterfaces.ArithmeticRepresentation.rho_routeSquared
#guard_depends_on CommonActionStage.reflectionCycleCorner_eq,
  CommonActionStage.reflectionCycleCorner
#guard_depends_on CommonActionStage.reflectionCycleCorner_eq,
  TransverseAnnihilator.cyclePolynomial
#guard_depends_on CommonActionStage.stickelbergerCorner,
  CommonActionStage.baseCornerProjection
#guard_depends_on CommonActionStage.stickelbergerCorner_val,
  CommonActionStage.stickelbergerCorner
#guard_depends_on CommonActionStage.cornerCoefficient_smul_eq,
  smul_comm
#guard_depends_on CommonActionStage.cornerConversionReceipt,
  LinkingInterfaces.FilteredStickelbergerCarrier.stickelberger_conversion
#guard_depends_on CommonActionStage.cornerConversionReceipt,
  LinkingInterfaces.FilteredStickelbergerCarrier.conversionReceipt
#guard_depends_on CommonActionStage.cornerConversionReceipt_beta,
  CommonActionStage.cornerConversionReceipt
#guard_depends_on
  CommonActionStage.classProjection_cornerCoefficient_smul_eq_zero,
  LinkingInterfaces.FilteredStickelbergerCarrier.classProjection_smul_eq_zero
#guard_depends_on CommonActionStage.sevenDClassOperator,
  CommonActionStage.classSwap
#guard_depends_on CommonActionStage.sevenDClassCornerElement,
  CommonActionStage.sevenDClassOperator
#guard_depends_on CommonActionStage.sevenDClassShadowReceipt,
  CommonActionStage.sevenDClassCornerElement
#guard_depends_on CommonActionStage.allocatedRootState,
  ClassCarrier.numberFieldBoundedRepresentative
#guard_depends_on CommonActionStage.allocatedRootState_receipts,
  CommonActionStage.allocatedRootState
#guard_depends_on CommonActionStage.allocatedRootState_class,
  ClassCarrier.idealClassProjection_eq_source_class
#guard_depends_on CommonActionStage.allocatedRootState_source_eq,
  ClassCarrier.State.source_eq_principal_mul_reduced
#guard_depends_on CommonActionStage.allocatedSevenDClassReceipt,
  CommonActionStage.sevenDClassShadowReceipt
#guard_depends_on CommonActionStage.allocatedSevenDReceiptedRootState,
  CommonActionStage.allocatedSevenDClassReceipt
#guard_depends_on CommonActionStage.allocatedSevenDReceiptedRootState_receipt,
  CommonActionStage.allocatedSevenDReceiptedRootState
#guard_depends_on CommonActionStage.allocatedSevenDClassReceipt_payload,
  CommonActionStage.allocatedSevenDClassReceipt
#guard_depends_on CommonActionStage.allocatedRootClassPTorsion,
  KummerDrain.AllocatedFactorLedger.rootClass_torsion
#guard_depends_on CommonActionStage.allocatedSelmerObstruction,
  CommonActionStage.ExactFilteredPair.liftClassPair
#guard_depends_on CommonActionStage.classProjection_allocatedSelmerObstruction,
  CommonActionStage.ExactFilteredPair.classProjection_liftClassPair
#guard_depends_on CommonActionStage.Outcome.unitIdealResult,
  TransverseAnnihilator.CornerService.eq_zero_of_annihilates_of_bezout
#guard_depends_on
  CommonActionStage.StateConversionCompatibility.conversionReceipt_beta_eq_state_beta,
  CommonActionStage.StateConversionCompatibility.beta_eq
#guard_depends_on
  CommonActionStage.GuardedPairedCarrier.pairedCornerConversionReceipts,
  CommonActionStage.IntegralReflectionInput.sharpTransport
#guard_depends_on
  CommonActionStage.GuardedPairedCarrier.pairedCornerConversionReceipts,
  CommonActionStage.cornerConversionReceipt
#guard_depends_on CommonActionStage.reflectedSelmerRhoWall_target,
  CommonActionStage.reflectedSelmerRhoWall

/-! ## Exhaustive axiom boundary

Every declaration created below each W1--W5 namespace is inspected.  This is
exhaustive rather than a hand-maintained theorem sample, so newly added public
declarations are automatically audited as well. -/

open Lean Elab Command

/-- Fail if any declaration under a namespace prefix uses an axiom beyond
Lean's standard extensionality, choice, and quotient-soundness boundary. -/
elab "#guard_standard_axioms_prefix " p:ident : command => do
  let env ← getEnv
  let auditedPrefix := p.getId
  let allowed : Array Name :=
    #[``propext, ``Classical.choice, ``Quot.sound]
  let declarations :=
    env.constants.toList
      |>.map Prod.fst
      |>.filter auditedPrefix.isPrefixOf
  for declaration in declarations do
    let axioms ← Lean.collectAxioms declaration
    let unexpected := axioms.filter fun ax =>
      !allowed.contains ax
    unless unexpected.isEmpty do
      throwError
        "{declaration} depends on nonstandard axioms: {unexpected}"

#guard_standard_axioms_prefix Fermat.Conservation.InvolutiveBase
#guard_standard_axioms_prefix Fermat.Conservation.RouteAlgebra
#guard_standard_axioms_prefix Fermat.Conservation.SwapQuotient
#guard_standard_axioms_prefix Fermat.Conservation.TransverseAnnihilator.CornerService
#guard_standard_axioms_prefix Fermat.Conservation.LinkingInterfaces
#guard_standard_axioms_prefix Fermat.Conservation.CommonActionStage
