/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, Fable

# Executable audit for the twisted linking stage

This non-imported leaf checks the linking W1--W5 and common-action W0--W3
public surfaces, the intended proof-value dependency direction, and the
standard-axiom boundary.  In particular, strict-route perfect return is
refuted upstream and is obtained only through the explicit swap quotient map.
-/
import Fermat.Conservation.GuardDependsOn
import Fermat.Conservation.CommonActionStage
import Fermat.Conservation.LinkingInterfaces
import Fermat.Conservation.SelmerSequence
import Fermat.Conservation.SelmerEigenspace
import Fermat.Conservation.SwapQuotient
import Fermat.Conservation.TatePairing
import Fermat.Conservation.TamePlacePairing
import Fermat.Conservation.TameSymbol
import Fermat.Conservation.TransverseAnnihilator

open Fermat.Conservation

/-! ## Public linking surface -/

#check InvolutiveBase.TeichmullerData
#check InvolutiveBase.GroupAlgebra
#check InvolutiveBase.hash
#check InvolutiveBase.hash_apply
#check InvolutiveBase.hash_hash
#check InvolutiveBase.reflectionPairing
#check InvolutiveBase.reflection_conservation_law
#check InvolutiveBase.reflectedCharacter
#check InvolutiveBase.characterIdempotent
#check InvolutiveBase.characterIdempotent_isIdempotent
#check InvolutiveBase.hash_characterIdempotent
#check InvolutiveBase.hash_trivialCharacterIdempotent
#check InvolutiveBase.plusProjector
#check InvolutiveBase.minusProjector
#check InvolutiveBase.plusProjector_isIdempotent
#check InvolutiveBase.minusProjector_isIdempotent
#check InvolutiveBase.hash_conjugationElement
#check InvolutiveBase.plus_minus_projectors_exchanged

#check RouteAlgebra.HasSharp
#check RouteAlgebra.teichmullerSharp
#check RouteAlgebra.mathlibSkewPolynomialRoute
#check RouteAlgebra.Route
#check RouteAlgebra.route_covariance
#check RouteAlgebra.closedRoute
#check RouteAlgebra.closedRoute_central
#check RouteAlgebra.closedRoute_ne_one
#check RouteAlgebra.CanonicalPathPresentation
#check RouteAlgebra.CanonicalPathPresentation.closedAtChi
#check RouteAlgebra.CanonicalPathPresentation.closedAtReflected
#check RouteAlgebra.BaseCorner
#check RouteAlgebra.RouteCorner
#check RouteAlgebra.routeCorner_coeff_odd_eq_zero
#check RouteAlgebra.cornerClosedRoute
#check RouteAlgebra.cornerPolynomialMap
#check RouteAlgebra.cornerToPolynomial
#check RouteAlgebra.cornerPolynomialEquiv
#check RouteAlgebra.cornerPolynomialEquiv_X
#check RouteAlgebra.teichmullerSharp_characterIdempotent
#check RouteAlgebra.characterCornerPolynomialEquiv

#check SwapQuotient.swapIdeal
#check SwapQuotient.Swap
#check SwapQuotient.quotientMap
#check SwapQuotient.generator
#check SwapQuotient.coefficient
#check SwapQuotient.sevenARouteWord
#check SwapQuotient.sevenDRouteWord
#check SwapQuotient.sevenARelationWord
#check SwapQuotient.sevenDRelationWord
#check SwapQuotient.sevenARelationWord_image
#check SwapQuotient.sevenDRelationWord_image
#check SwapQuotient.quotientMap_closedRoute
#check SwapQuotient.generator_sq
#check SwapQuotient.generator_coefficient
#check SwapQuotient.flowElement
#check SwapQuotient.flowElement_two
#check SwapQuotient.piCommon
#check SwapQuotient.piDifference
#check SwapQuotient.piCommon_add_piDifference
#check SwapQuotient.piCommon_idempotent
#check SwapQuotient.piDifference_idempotent
#check SwapQuotient.piCommon_piDifference_orthogonal
#check SwapQuotient.sevenARelationWord_eigenspace
#check SwapQuotient.sevenDRelationWord_eigenspace
#check SwapQuotient.swapLinear
#check SwapQuotient.swapLinear_sq
#check SwapQuotient.commonDifference
#check SwapQuotient.commonDifference_swap
#check SwapQuotient.commonProjector_formula
#check SwapQuotient.differenceProjector_formula
#check SwapQuotient.sevenARelationOperator_apply
#check SwapQuotient.sevenDRelationOperator_apply
#check SwapQuotient.flowOperator
#check SwapQuotient.flowOperator_apply
#check SwapQuotient.flowOperator_two

#check TransverseAnnihilator.CornerService.BezoutCertificate
#check TransverseAnnihilator.CornerService.eq_zero_of_annihilates_of_bezout
#check TransverseAnnihilator.CornerService.bezout_identity_in_ambient
#check TransverseAnnihilator.CornerService.eq_zero_in_idempotentCorner
#check TransverseAnnihilator.CornerService.LivelockCarrier
#check TransverseAnnihilator.CornerService.livelockCarrier_subsingleton_iff
#check TransverseAnnihilator.CornerService.livelockCarrier_nontrivial_iff
#check TransverseAnnihilator.CornerService.CornerLivelockChannel
#check TransverseAnnihilator.CornerService.nonempty_cornerLivelockChannel_iff
#check TransverseAnnihilator.breaksCycle_iff_polynomialGCD_eq_one
#check TransverseAnnihilator.polynomial_livelockCarrier_subsingleton_iff
#check TransverseAnnihilator.nonempty_polynomial_cornerLivelockChannel_iff
#check TransverseAnnihilator.eq_zero_of_cycle_and_transverse_gcd_eq_one

#check LinkingInterfaces.IntegralPadicGroupAlgebra
#check LinkingInterfaces.IntegralStickelbergerIdeal
#check LinkingInterfaces.IntegralStickelbergerIdeal.SharpTransformationGuard
#check LinkingInterfaces.sharp_trivialProjector_eq_omegaProjector
#check LinkingInterfaces.FilteredStickelbergerCarrier
#check LinkingInterfaces.FilteredStickelbergerCarrier.smul_mem_unitRange
#check LinkingInterfaces.FilteredStickelbergerCarrier.classProjection_smul_eq_zero
#check LinkingInterfaces.FilteredStickelbergerCarrier.conversionReceipt
#check LinkingInterfaces.StrictRouteArithmeticRepresentation
#check LinkingInterfaces.WithheldStrictRouteArithmeticRepresentation
#check LinkingInterfaces.ReflectedSelmerArithmeticRepresentationTarget

/-! ## Place-indexed Tate pairing and reciprocity surface -/

#check TatePairing.character_mul_reflectedCharacter
#check TatePairing.PlaceIndexedLocalPairing
#check TatePairing.PlaceIndexedLocalPairing.pairAt
#check TatePairing.PlaceIndexedLocalPairing.pairAt_smul_adjoint
#check TatePairing.PlaceIndexedLocalPairing.pairAt_hash_smul_adjoint
#check TatePairing.PlaceIndexedLocalPairing.finite_support
#check TatePairing.PlaceLedger
#check TatePairing.PlaceLedger.toLedger
#check TatePairing.PlaceLedger.toVacuumTransfer
#check TatePairing.PlaceLedger.toVacuumTransfer_L1
#check TatePairing.GlobalReciprocityLaw
#check TatePairing.GlobalReciprocityLaw.placeLedger
#check TatePairing.GlobalReciprocityLaw.ledger_conservation_identity
#check TatePairing.GlobalReciprocityLaw.reciprocityTransfer
#check TatePairing.GlobalReciprocityLaw.reciprocity_L1_conservation
#check TatePairing.GlobalReciprocityLaw.pairAt_eq_zero_of_other_places
#check TatePairing.LocalOrthogonalityGuard
#check TatePairing.LocalOrthogonalityGuard.pairAt_eq_zero

/-! ## Explicit tame Hilbert-symbol surface -/

#check TameSymbol.KummerClass
#check TameSymbol.Context
#check TameSymbol.Context.residueCard
#check TameSymbol.Context.tameExponent
#check TameSymbol.Context.raw
#check TameSymbol.Context.raw_one_left
#check TameSymbol.Context.raw_one_right
#check TameSymbol.Context.raw_mul_left
#check TameSymbol.Context.raw_mul_right
#check TameSymbol.Context.raw_swap
#check TameSymbol.Context.residue_power_pow_eq_one
#check TameSymbol.Context.powerToRoots
#check TameSymbol.Context.rootsEquivZPowers
#check TameSymbol.Context.residueCharacter
#check TameSymbol.Context.residueCharacter_one
#check TameSymbol.Context.residueCharacter_mul
#check TameSymbol.Context.value
#check TameSymbol.Context.value_eq_explicit_formula
#check TameSymbol.Context.value_one_left
#check TameSymbol.Context.value_one_right
#check TameSymbol.Context.value_mul_left
#check TameSymbol.Context.value_mul_right
#check TameSymbol.Context.value_swap
#check TameSymbol.Context.toAddMonoidHom
#check TameSymbol.Context.toAddMonoidHom_apply
#check TameSymbol.Context.raw_eq_one_of_ord_eq_zero
#check TameSymbol.Context.both_units_silence
#check TameSymbol.Context.value_eq_zero_of_ord_eq_zero
#check TameSymbol.Context.raw_eq_pth_power_of_p_dvd_ord
#check TameSymbol.Context.value_eq_zero_of_p_dvd_ord
#check TameSymbol.Context.value_pow_left
#check TameSymbol.Context.value_pow_right
#check TameSymbol.Context.value_pth_power_left
#check TameSymbol.Context.value_pth_power_right
#check TameSymbol.Context.rightMonoidHom
#check TameSymbol.Context.ordModPRep
#check TameSymbol.Context.ordModP
#check TameSymbol.Context.ordModP_mk
#check TameSymbol.Context.rightModP
#check TameSymbol.Context.rightModP_mk
#check TameSymbol.Context.rightModPFamily
#check TameSymbol.Context.modPMul
#check TameSymbol.Context.modP
#check TameSymbol.Context.modP_mk_mk
#check TameSymbol.Context.modP_eq_zero_of_ordModP_eq_zero
#check TameSymbol.Context.SteinbergValuationCases
#check TameSymbol.Context.SteinbergValuationCases.raw_eq_one
#check TameSymbol.Context.SteinbergValuationCases.steinberg_of_cases
#check TameSymbol.Context.SteinbergRealization
#check TameSymbol.Context.steinberg
#check TameSymbol.Context.PlaceGaloisData
#check TameSymbol.Context.PlaceGaloisData.raw_place_action
#check TameSymbol.Context.PlaceGaloisData.value_place_galois_equivariant
#check TameSymbol.Context.GaloisData
#check TameSymbol.Context.GaloisData.raw_action
#check TameSymbol.Context.GaloisData.value_galois_equivariant
#check TameSymbol.Context.GaloisData.value_action_adjoint

/-! ## Seated Selmer-eigenspace surface -/

#check SelmerEigenspace.SelmerCarrier
#check SelmerEigenspace.selmerCarrier_eq_commonActionStage
#check SelmerEigenspace.p_nsmul_eq_zero
#check SelmerEigenspace.instModuleZMod
#check SelmerEigenspace.instModulePadicInt
#check SelmerEigenspace.padicInt_smul_eq_toZMod_smul
#check SelmerEigenspace.SelmerDeltaRepresentation
#check SelmerEigenspace.characterEigenspace
#check SelmerEigenspace.instCharacterEigenspaceAddCommGroup
#check SelmerEigenspace.mem_characterEigenspace_iff
#check SelmerEigenspace.SelmerChi
#check SelmerEigenspace.SelmerChiStar
#check SelmerEigenspace.characterEigenspaceRepresentation
#check SelmerEigenspace.instCharacterEigenspaceGroupAlgebraModule
#check SelmerEigenspace.coe_groupElement_smul
#check SelmerEigenspace.toSeatedCarrier
#check SelmerEigenspace.toAdditiveSelmer
#check SelmerEigenspace.toConcreteSelmer
#check SelmerEigenspace.toKummerQuotient
#check SelmerEigenspace.toKummerClass
#check SelmerEigenspace.toSeatedCarrier_apply
#check SelmerEigenspace.toAdditiveSelmer_apply
#check SelmerEigenspace.toConcreteSelmer_apply
#check SelmerEigenspace.toKummerQuotient_apply
#check SelmerEigenspace.toKummerClass_apply
#check SelmerEigenspace.toAdditiveSelmer_injective
#check SelmerEigenspace.toConcreteSelmer_injective
#check SelmerEigenspace.toKummerQuotient_injective
#check SelmerEigenspace.valuationOfNeZeroMod_eq_one
#check SelmerEigenspace.valuationOfNeZeroMod_mk_eq_one_iff_dvd
#check SelmerEigenspace.representative_valuation_dvd
#check SelmerEigenspace.quotientRepresentative
#check SelmerEigenspace.quotientRepresentative_mk
#check SelmerEigenspace.quotientRepresentative_valuation_dvd
#check SelmerEigenspace.exists_representative_valuation_dvd
#check SelmerEigenspace.DOmegaSelmerChiStar
#check SelmerEigenspace.ReflectedDualCharacterGlue
#check SelmerEigenspace.ReflectedDualCharacterGlue.carrierDualEquiv_smul
#check SelmerEigenspace.ReflectedSelmerPair

/-! ## Tame place-indexed realization surface -/

#check TamePlacePairing.PlaceIndexedTameRealization
#check TamePlacePairing.PlaceIndexedTameRealization.SelectedValuationsZeroAt
#check TamePlacePairing.PlaceIndexedTameRealization.pairAt_eq_zero_of_p_dvd_ord
#check TamePlacePairing.PlaceIndexedTameRealization.OutsideTwoTameBookkeeping
#check TamePlacePairing.PlaceIndexedTameRealization.OutsideTwoTameBookkeeping.outside_two_readings_at_tame_places
#check TamePlacePairing.PlaceIndexedTameRealization.OutsideTwoTameBookkeeping.outside_two_readings_of_tame_and_residual
#check TamePlacePairing.WildLocalInterface
#check TamePlacePairing.WildLocalInterface.toPlaceIndexedLocalPairing
#check TamePlacePairing.WildLocalInterface.pairAt_distinguished
#check TamePlacePairing.WildLocalInterface.pairAt_eq_zero_of_ne
#check TamePlacePairing.Seated.Place
#check TamePlacePairing.Seated.Primal
#check TamePlacePairing.Seated.ReflectedDual
#check TamePlacePairing.Seated.Pairing
#check TamePlacePairing.Seated.WildInterface
#check TamePlacePairing.Seated.ordModP_toKummerClass_eq_zero_of_ord_eq_valuation
#check TamePlacePairing.Seated.Realization
#check TamePlacePairing.Seated.Realization.ofWild
#check TamePlacePairing.Seated.Realization.toPlaceIndexedTameRealization
#check TamePlacePairing.Seated.Realization.toPlaceIndexedTameRealization_primalClass
#check TamePlacePairing.Seated.Realization.toPlaceIndexedTameRealization_dualClass
#check TamePlacePairing.Seated.Realization.ordModP_toKummerClass_eq_zero
#check TamePlacePairing.Seated.Realization.selectedValuationsZeroAt
#check TamePlacePairing.Seated.Realization.pairAt_eq_zero_at_tame_place
#check TamePlacePairing.Seated.Realization.outsideTwoTameBookkeeping
#check TamePlacePairing.Seated.Realization.outside_two_readings_at_tame_places
#check TamePlacePairing.Seated.Realization.outside_two_readings_of_residual

/-! ## Vendored Selmer class-sequence surface -/

#check IsDedekindDomain.selmerGroup.toClass
#check IsDedekindDomain.selmerGroup.toClass_ker
#check IsDedekindDomain.selmerGroup.toClass_range

/-! ## Common-action stage surface -/

#check CommonActionStage.UnitModP
#check CommonActionStage.Selmer
#check CommonActionStage.ClassPTorsion
#check CommonActionStage.unitInclusion
#check CommonActionStage.unitInclusion_injective
#check CommonActionStage.selmerClassProjection
#check CommonActionStage.selmerClassSequenceRealization
#check CommonActionStage.realUnitClass
#check CommonActionStage.realUnitInclusion
#check CommonActionStage.SelmerClassSequenceRealization
#check CommonActionStage.WithheldSelmerClassSequenceRealization
#check CommonActionStage.SelmerCharacterDual
#check CommonActionStage.ExactFilteredLeg
#check CommonActionStage.ReflectedDualRealization
#check CommonActionStage.ExactFilteredPair
#check CommonActionStage.ReflectedExactFilteredPair
#check CommonActionStage.ExactFilteredPair.Carrier
#check CommonActionStage.ExactFilteredPair.unitInclusion
#check CommonActionStage.ExactFilteredPair.classProjection
#check CommonActionStage.ExactFilteredPair.unitInclusion_injective
#check CommonActionStage.ExactFilteredPair.exact_at_carrier
#check CommonActionStage.ExactFilteredPair.classProjection_surjective
#check CommonActionStage.ExactFilteredPair.liftClassPair
#check CommonActionStage.ExactFilteredPair.classProjection_liftClassPair
#check CommonActionStage.ExactFilteredPair.filtration
#check CommonActionStage.ExactFilteredPair.antitone_filtration
#check CommonActionStage.ExactFilteredPair.class_p_torsion
#check CommonActionStage.KummerCharacterLegCompatibility
#check CommonActionStage.KummerPairedBinding
#check CommonActionStage.exactLegOfFilteredStickelbergerCarrier
#check CommonActionStage.IntegralReflectionInput
#check CommonActionStage.IntegralReflectionInput.sharpTransport
#check CommonActionStage.IntegralReflectionInput.sharpTransport_coe
#check CommonActionStage.GuardedPairedCarrier
#check CommonActionStage.GuardedPairedCarrier.exactPair
#check CommonActionStage.GuardedPairedCarrier.chiConversionReceipt
#check CommonActionStage.GuardedPairedCarrier.reflectedDualConversionReceipt
#check CommonActionStage.GuardedPairedCarrier.pairedConversionReceipts
#check CommonActionStage.lambdaAction
#check CommonActionStage.lambdaAction_apply
#check CommonActionStage.deltaAction
#check CommonActionStage.deltaAction_apply
#check CommonActionStage.RouteMaps
#check CommonActionStage.RouteMaps.closedAtChi
#check CommonActionStage.RouteMaps.closedAtReflected
#check CommonActionStage.RouteMaps.openRoute
#check CommonActionStage.RouteMaps.openRoute_apply
#check CommonActionStage.RouteMaps.openRoute_sq_apply
#check CommonActionStage.RouteMaps.ofArithmeticRepresentation
#check CommonActionStage.RouteMaps.rho_routeSquared_eq_closed
#check CommonActionStage.reflectionCycleCorner
#check CommonActionStage.reflectionCycleCorner_eq
#check CommonActionStage.StrictReflectionCycleReceipt
#check CommonActionStage.StrictReflectionCycleReceiptTarget
#check CommonActionStage.baseCornerProjection
#check CommonActionStage.stickelbergerCorner
#check CommonActionStage.stickelbergerCorner_val
#check CommonActionStage.cornerCoefficient_smul_eq
#check CommonActionStage.CornerConversionReceipt
#check CommonActionStage.cornerConversionReceipt
#check CommonActionStage.cornerConversionReceipt_beta
#check CommonActionStage.classProjection_cornerCoefficient_smul_eq_zero
#check CommonActionStage.StateConversionCompatibility
#check CommonActionStage.StateConversionCompatibility.conversionReceipt_beta_eq_state_beta
#check CommonActionStage.GuardedPairedCarrier.pairedCornerConversionReceipts
#check CommonActionStage.AllocatedClass
#check CommonActionStage.classSwap
#check CommonActionStage.sevenDClassOperator
#check CommonActionStage.classCornerIdempotent
#check CommonActionStage.ClassActionCorner
#check CommonActionStage.sevenDClassCornerElement
#check CommonActionStage.differenceGauge
#check CommonActionStage.sevenDClassShadowReceipt
#check CommonActionStage.allocatedRootSource
#check CommonActionStage.allocatedRootState
#check CommonActionStage.allocatedRootState_receipts
#check CommonActionStage.allocatedRootState_class
#check CommonActionStage.allocatedRootState_source_eq
#check CommonActionStage.allocatedClassObstruction
#check CommonActionStage.allocatedSevenDClassReceipt
#check CommonActionStage.allocatedSevenDReceiptedRootState
#check CommonActionStage.allocatedSevenDReceiptedRootState_receipt
#check CommonActionStage.allocatedSevenDClassReceipt_payload
#check CommonActionStage.allocatedRootClassPTorsion
#check CommonActionStage.CharacterClassAllocation
#check CommonActionStage.allocatedCharacterClassObstruction
#check CommonActionStage.allocatedSelmerObstruction
#check CommonActionStage.classProjection_allocatedSelmerObstruction
#check CommonActionStage.Outcome.UnitIdealResult
#check CommonActionStage.Outcome.unitIdealResult
#check CommonActionStage.Outcome.SurvivingChannelResult
#check CommonActionStage.Outcome.WallAddress
#check CommonActionStage.Outcome.LocalizedWall
#check CommonActionStage.Outcome.TypedResult
#check CommonActionStage.Outcome.PolynomialTypedResult
#check CommonActionStage.reflectedSelmerRhoWall
#check CommonActionStage.reflectedSelmerRhoWall_target

/-! ## Proof-value wiring -/

#guard_depends_on InvolutiveBase.hash_hash,
  InvolutiveBase.hashHom_comp_self
#guard_depends_on InvolutiveBase.reflection_conservation_law,
  InvolutiveBase.reflectionPairing
#guard_depends_on InvolutiveBase.characterIdempotent_isIdempotent,
  InvolutiveBase.groupAverage_isIdempotent
#guard_depends_on InvolutiveBase.hash_characterIdempotent,
  InvolutiveBase.reflectedCharacter
#guard_depends_on InvolutiveBase.hash_trivialCharacterIdempotent,
  InvolutiveBase.hash_characterIdempotent
#guard_depends_on InvolutiveBase.plus_minus_projectors_exchanged,
  InvolutiveBase.hash_conjugationElement

#guard_depends_on RouteAlgebra.closedRoute_central,
  RouteAlgebra.phi_sq
#guard_depends_on RouteAlgebra.closedRoute_ne_one,
  SkewPolynomial.coeff_monomial
#guard_depends_on RouteAlgebra.routeCorner_coeff_odd_eq_zero,
  RouteAlgebra.odd_smul
#guard_depends_on RouteAlgebra.cornerPolynomialMap_surjective,
  RouteAlgebra.routeCorner_coeff_odd_eq_zero
#guard_depends_on RouteAlgebra.cornerPolynomialEquiv,
  RouteAlgebra.cornerPolynomialMap_surjective
#guard_depends_on RouteAlgebra.cornerPolynomialEquiv_X,
  RouteAlgebra.cornerPolynomialMap
#guard_depends_on RouteAlgebra.characterCornerPolynomialEquiv,
  RouteAlgebra.cornerPolynomialEquiv
#guard_depends_on RouteAlgebra.characterCornerPolynomialEquiv,
  InvolutiveBase.hash_characterIdempotent

#guard_depends_on SwapQuotient.quotientMap_closedRoute,
  TwoSidedIdeal.subset_span
#guard_depends_on SwapQuotient.sevenARelationWord_image,
  SwapQuotient.quotientMap
#guard_depends_on SwapQuotient.sevenDRelationWord_image,
  SwapQuotient.quotientMap
#guard_depends_on SwapQuotient.generator_sq,
  SwapQuotient.quotientMap_closedRoute
#guard_depends_on SwapQuotient.piCommon_idempotent,
  SwapQuotient.generator_sq
#guard_depends_on SwapQuotient.piDifference_idempotent,
  SwapQuotient.generator_sq
#guard_depends_on SwapQuotient.piCommon_piDifference_orthogonal,
  SwapQuotient.generator_sq
#guard_depends_on SwapQuotient.sevenARelationWord_eigenspace,
  SwapQuotient.sevenARelationWord_image
#guard_depends_on SwapQuotient.sevenARelationWord_eigenspace,
  SwapQuotient.generator_sq
#guard_depends_on SwapQuotient.sevenARelationWord_eigenspace,
  SwapQuotient.coefficientHalf_add_self
#guard_depends_on SwapQuotient.sevenDRelationWord_eigenspace,
  SwapQuotient.sevenDRelationWord_image
#guard_depends_on SwapQuotient.sevenDRelationWord_eigenspace,
  SwapQuotient.generator_sq
#guard_depends_on SwapQuotient.sevenDRelationWord_eigenspace,
  SwapQuotient.coefficientHalf_add_self
#guard_depends_on SwapQuotient.flowElement_two,
  SwapQuotient.flowElement
#guard_depends_on SwapQuotient.commonDifference_swap,
  SwapQuotient.swapLinear
#guard_depends_on SwapQuotient.commonProjector_formula,
  SwapQuotient.commonProjector
#guard_depends_on SwapQuotient.differenceProjector_formula,
  SwapQuotient.differenceProjector
#guard_depends_on SwapQuotient.sevenARelationOperator_apply,
  SwapQuotient.swapLinear
#guard_depends_on SwapQuotient.sevenDRelationOperator_apply,
  SwapQuotient.swapLinear
#guard_depends_on SwapQuotient.flowOperator_apply,
  Interaction.TwoAccount.step
#guard_depends_on SwapQuotient.flowOperator_two,
  Interaction.TwoAccount.step_two_eq_swap

#guard_depends_on
  TransverseAnnihilator.eq_zero_of_cycle_and_transverse_gcd_eq_one,
  TransverseAnnihilator.CornerService.eq_zero_of_annihilates_of_bezout
#guard_depends_on
  TransverseAnnihilator.CornerService.eq_zero_in_idempotentCorner,
  TransverseAnnihilator.CornerService.eq_zero_of_annihilates_of_bezout
#guard_depends_on
  TransverseAnnihilator.eq_zero_of_cycle_and_transverse_gcd_eq_one,
  TransverseAnnihilator.breaksCycle_iff_polynomialGCD_eq_one
#guard_depends_on
  TransverseAnnihilator.polynomial_livelockCarrier_subsingleton_iff,
  TransverseAnnihilator.CornerService.livelockCarrier_subsingleton_iff

#guard_depends_on
  LinkingInterfaces.sharp_trivialProjector_eq_omegaProjector,
  InvolutiveBase.hash_trivialCharacterIdempotent
#guard_depends_on
  LinkingInterfaces.FilteredStickelbergerCarrier.smul_mem_unitRange,
  LinkingInterfaces.FilteredStickelbergerCarrier.stickelberger_conversion
#guard_depends_on
  LinkingInterfaces.FilteredStickelbergerCarrier.classProjection_smul_eq_zero,
  LinkingInterfaces.FilteredStickelbergerCarrier.exact_at_carrier
#guard_depends_on
  LinkingInterfaces.FilteredStickelbergerCarrier.conversionReceipt,
  ClassCarrier.PrincipalizationReceipt.mk
#guard_depends_on
  LinkingInterfaces.FilteredStickelbergerCarrier.conversionReceipt_source_eq,
  ClassCarrier.PrincipalizationReceipt.source_eq
#guard_depends_on
  LinkingInterfaces.ArithmeticRepresentation.rho_routeSquared,
  LinkingInterfaces.ArithmeticRepresentation.rho_route
#guard_depends_on
  LinkingInterfaces.StrictRouteArithmeticRepresentation.rho_closedRoute,
  LinkingInterfaces.ArithmeticRepresentation.rho_routeSquared

/-! ## Tate pairing proof-value wiring -/

#guard_depends_on TatePairing.character_mul_reflectedCharacter,
  InvolutiveBase.reflectedCharacter
#guard_depends_on
  TatePairing.PlaceIndexedLocalPairing.pairAt_smul_adjoint,
  TatePairing.PlaceIndexedLocalPairing.adjoint_law
#guard_depends_on
  TatePairing.PlaceIndexedLocalPairing.pairAt_hash_smul_adjoint,
  TatePairing.PlaceIndexedLocalPairing.pairAt_smul_adjoint
#guard_depends_on
  TatePairing.PlaceIndexedLocalPairing.pairAt_hash_smul_adjoint,
  InvolutiveBase.hash_hash
#guard_depends_on TatePairing.PlaceIndexedLocalPairing.finite_support,
  TatePairing.PlaceIndexedLocalPairing.pairAt
#guard_depends_on TatePairing.PlaceLedger.toLedger_stock,
  TatePairing.PlaceLedger.toLedger
#guard_depends_on TatePairing.PlaceLedger.toLedger_credit,
  TatePairing.PlaceLedger.toLedger
#guard_depends_on TatePairing.PlaceLedger.toLedger_converted,
  TatePairing.PlaceLedger.toLedger
#guard_depends_on TatePairing.PlaceLedger.toLedger_total,
  TatePairing.PlaceLedger.toLedger
#guard_depends_on TatePairing.PlaceLedger.toVacuumTransfer,
  Fermat.Conservation.Ledger.conservation_identity
#guard_depends_on TatePairing.PlaceLedger.toVacuumTransfer_before,
  TatePairing.PlaceLedger.toVacuumTransfer
#guard_depends_on TatePairing.PlaceLedger.toVacuumTransfer_after,
  TatePairing.PlaceLedger.toVacuumTransfer
#guard_depends_on TatePairing.PlaceLedger.toVacuumTransfer_spent,
  TatePairing.PlaceLedger.toVacuumTransfer
#guard_depends_on TatePairing.PlaceLedger.toVacuumTransfer_L1,
  IsoConserveBridge.transfer_L1_conservation
#guard_depends_on TatePairing.GlobalReciprocityLaw.placeLedger,
  TatePairing.PlaceLedger.mk
#guard_depends_on
  TatePairing.GlobalReciprocityLaw.ledger_conservation_identity,
  Fermat.Conservation.Ledger.conservation_identity
#guard_depends_on TatePairing.GlobalReciprocityLaw.reciprocityTransfer,
  TatePairing.PlaceLedger.toVacuumTransfer
#guard_depends_on
  TatePairing.GlobalReciprocityLaw.reciprocity_L1_conservation,
  IsoConserveBridge.transfer_L1_conservation
#guard_depends_on
  TatePairing.GlobalReciprocityLaw.pairAt_eq_zero_of_other_places,
  TatePairing.PlaceIndexedLocalPairing.pairAt
#guard_depends_on TatePairing.LocalOrthogonalityGuard.pairAt_eq_zero,
  TatePairing.LocalOrthogonalityGuard.orthogonal

/-! ## Explicit tame Hilbert-symbol proof-value wiring -/

#guard_depends_on TameSymbol.Context.raw_one_left,
  TameSymbol.Context.raw
#guard_depends_on TameSymbol.Context.raw_one_right,
  TameSymbol.Context.raw
#guard_depends_on TameSymbol.Context.raw_mul_left,
  TameSymbol.Context.raw
#guard_depends_on TameSymbol.Context.raw_mul_right,
  TameSymbol.Context.raw
#guard_depends_on TameSymbol.Context.raw_swap,
  TameSymbol.Context.raw
#guard_depends_on TameSymbol.Context.residue_power_pow_eq_one,
  FiniteField.pow_card_sub_one_eq_one
#guard_depends_on TameSymbol.Context.residueCharacter_one,
  TameSymbol.Context.residueCharacter
#guard_depends_on TameSymbol.Context.residueCharacter_mul,
  TameSymbol.Context.residueCharacter
#guard_depends_on TameSymbol.Context.value_eq_explicit_formula,
  TameSymbol.Context.value
#guard_depends_on TameSymbol.Context.value_one_left,
  TameSymbol.Context.value
#guard_depends_on TameSymbol.Context.value_one_right,
  TameSymbol.Context.value
#guard_depends_on TameSymbol.Context.value_mul_left,
  TameSymbol.Context.raw_mul_left
#guard_depends_on TameSymbol.Context.value_mul_right,
  TameSymbol.Context.raw_mul_right
#guard_depends_on TameSymbol.Context.value_swap,
  TameSymbol.Context.raw_swap
#guard_depends_on TameSymbol.Context.toAddMonoidHom_apply,
  TameSymbol.Context.toAddMonoidHom
#guard_depends_on TameSymbol.Context.raw_eq_one_of_ord_eq_zero,
  TameSymbol.Context.raw
#guard_depends_on TameSymbol.Context.both_units_silence,
  TameSymbol.Context.raw_eq_one_of_ord_eq_zero
#guard_depends_on TameSymbol.Context.value_eq_zero_of_ord_eq_zero,
  TameSymbol.Context.both_units_silence
#guard_depends_on TameSymbol.Context.raw_eq_pth_power_of_p_dvd_ord,
  TameSymbol.Context.raw
#guard_depends_on TameSymbol.Context.value_eq_zero_of_p_dvd_ord,
  TameSymbol.Context.raw_eq_pth_power_of_p_dvd_ord
#guard_depends_on TameSymbol.Context.value_pow_left,
  TameSymbol.Context.toAddMonoidHom
#guard_depends_on TameSymbol.Context.value_pow_right,
  TameSymbol.Context.toAddMonoidHom
#guard_depends_on TameSymbol.Context.value_pth_power_left,
  TameSymbol.Context.value_pow_left
#guard_depends_on TameSymbol.Context.value_pth_power_right,
  TameSymbol.Context.value_pow_right
#guard_depends_on TameSymbol.Context.ordModP_mk,
  TameSymbol.Context.ordModP
#guard_depends_on TameSymbol.Context.rightModP_mk,
  QuotientGroup.lift_mk'
#guard_depends_on TameSymbol.Context.modP_mk_mk,
  TameSymbol.Context.modP
#guard_depends_on TameSymbol.Context.modP_eq_zero_of_ordModP_eq_zero,
  TameSymbol.Context.value_eq_zero_of_p_dvd_ord
#guard_depends_on TameSymbol.Context.SteinbergValuationCases.raw_eq_one,
  TameSymbol.Context.raw_eq_one_of_ord_eq_zero
#guard_depends_on TameSymbol.Context.SteinbergValuationCases.steinberg_of_cases,
  TameSymbol.Context.SteinbergValuationCases.raw_eq_one
#guard_depends_on TameSymbol.Context.steinberg,
  TameSymbol.Context.SteinbergValuationCases.steinberg_of_cases
#guard_depends_on TameSymbol.Context.PlaceGaloisData.raw_place_action,
  TameSymbol.Context.raw
#guard_depends_on
  TameSymbol.Context.PlaceGaloisData.value_place_galois_equivariant,
  TameSymbol.Context.PlaceGaloisData.raw_place_action
#guard_depends_on TameSymbol.Context.GaloisData.raw_action,
  TameSymbol.Context.raw
#guard_depends_on TameSymbol.Context.GaloisData.value_galois_equivariant,
  TameSymbol.Context.GaloisData.raw_action
#guard_depends_on TameSymbol.Context.GaloisData.value_action_adjoint,
  TameSymbol.Context.GaloisData.value_galois_equivariant
#guard_depends_on TameSymbol.Context.GaloisData.value_action_adjoint,
  TameSymbol.Context.value_pow_right

/-! ## Seated Selmer-eigenspace proof-value wiring -/

#guard_depends_on SelmerEigenspace.selmerCarrier_eq_commonActionStage,
  Eq.refl
#guard_depends_on SelmerEigenspace.p_nsmul_eq_zero,
  QuotientGroup.eq_one_iff
#guard_depends_on SelmerEigenspace.padicInt_smul_eq_toZMod_smul,
  PadicInt.toZMod
#guard_depends_on SelmerEigenspace.mem_characterEigenspace_iff,
  SelmerEigenspace.characterEigenspace
#guard_depends_on SelmerEigenspace.coe_groupElement_smul,
  Representation.asAlgebraHom_of
#guard_depends_on SelmerEigenspace.toSeatedCarrier_apply,
  SelmerEigenspace.toSeatedCarrier
#guard_depends_on SelmerEigenspace.toAdditiveSelmer_apply,
  SelmerEigenspace.toAdditiveSelmer
#guard_depends_on SelmerEigenspace.toConcreteSelmer_apply,
  SelmerEigenspace.toConcreteSelmer
#guard_depends_on SelmerEigenspace.toKummerQuotient_apply,
  SelmerEigenspace.toKummerQuotient
#guard_depends_on SelmerEigenspace.toKummerClass_apply,
  SelmerEigenspace.toKummerClass
#guard_depends_on SelmerEigenspace.toAdditiveSelmer_injective,
  Subtype.ext
#guard_depends_on SelmerEigenspace.toConcreteSelmer_injective,
  SelmerEigenspace.toAdditiveSelmer_injective
#guard_depends_on SelmerEigenspace.toKummerQuotient_injective,
  SelmerEigenspace.toConcreteSelmer_injective
#guard_depends_on SelmerEigenspace.valuationOfNeZeroMod_eq_one,
  SelmerEigenspace.toConcreteSelmer
#guard_depends_on SelmerEigenspace.valuationOfNeZeroMod_mk_eq_one_iff_dvd,
  ZMod.intCast_zmod_eq_zero_iff_dvd
#guard_depends_on SelmerEigenspace.representative_valuation_dvd,
  SelmerEigenspace.valuationOfNeZeroMod_mk_eq_one_iff_dvd
#guard_depends_on SelmerEigenspace.representative_valuation_dvd,
  SelmerEigenspace.valuationOfNeZeroMod_eq_one
#guard_depends_on SelmerEigenspace.quotientRepresentative_mk,
  QuotientGroup.out_eq'
#guard_depends_on SelmerEigenspace.quotientRepresentative_valuation_dvd,
  SelmerEigenspace.representative_valuation_dvd
#guard_depends_on SelmerEigenspace.exists_representative_valuation_dvd,
  SelmerEigenspace.quotientRepresentative_valuation_dvd
#guard_depends_on
  SelmerEigenspace.ReflectedDualCharacterGlue.carrierDualEquiv_smul,
  SelmerEigenspace.ReflectedDualCharacterGlue.omegaTwistedAction

/-! ## Tame place-indexed realization proof-value wiring -/

#guard_depends_on
  TamePlacePairing.PlaceIndexedTameRealization.pairAt_eq_zero_of_p_dvd_ord,
  TameSymbol.Context.modP_eq_zero_of_ordModP_eq_zero
#guard_depends_on
  TamePlacePairing.PlaceIndexedTameRealization.OutsideTwoTameBookkeeping.outside_two_readings_at_tame_places,
  TamePlacePairing.PlaceIndexedTameRealization.pairAt_eq_zero_of_p_dvd_ord
#guard_depends_on
  TamePlacePairing.PlaceIndexedTameRealization.OutsideTwoTameBookkeeping.outside_two_readings_of_tame_and_residual,
  TamePlacePairing.PlaceIndexedTameRealization.OutsideTwoTameBookkeeping.outside_two_readings_at_tame_places
#guard_depends_on TamePlacePairing.WildLocalInterface.pairAt_distinguished,
  TamePlacePairing.WildLocalInterface.toPlaceIndexedLocalPairing
#guard_depends_on TamePlacePairing.WildLocalInterface.pairAt_eq_zero_of_ne,
  TamePlacePairing.WildLocalInterface.toPlaceIndexedLocalPairing
#guard_depends_on
  TamePlacePairing.Seated.ordModP_toKummerClass_eq_zero_of_ord_eq_valuation,
  SelmerEigenspace.quotientRepresentative_valuation_dvd
#guard_depends_on
  TamePlacePairing.Seated.ordModP_toKummerClass_eq_zero_of_ord_eq_valuation,
  TameSymbol.Context.ordModP_mk
#guard_depends_on
  TamePlacePairing.Seated.Realization.toPlaceIndexedTameRealization_primalClass,
  TamePlacePairing.Seated.Realization.toPlaceIndexedTameRealization
#guard_depends_on
  TamePlacePairing.Seated.Realization.toPlaceIndexedTameRealization_dualClass,
  TamePlacePairing.Seated.Realization.toPlaceIndexedTameRealization
#guard_depends_on
  TamePlacePairing.Seated.Realization.ordModP_toKummerClass_eq_zero,
  TamePlacePairing.Seated.ordModP_toKummerClass_eq_zero_of_ord_eq_valuation
#guard_depends_on
  TamePlacePairing.Seated.Realization.pairAt_eq_zero_at_tame_place,
  TamePlacePairing.PlaceIndexedTameRealization.pairAt_eq_zero_of_p_dvd_ord
#guard_depends_on
  TamePlacePairing.Seated.Realization.pairAt_eq_zero_at_tame_place,
  TamePlacePairing.Seated.Realization.selectedValuationsZeroAt
#guard_depends_on
  TamePlacePairing.Seated.Realization.outside_two_readings_at_tame_places,
  TamePlacePairing.PlaceIndexedTameRealization.OutsideTwoTameBookkeeping.outside_two_readings_at_tame_places
#guard_depends_on
  TamePlacePairing.Seated.Realization.outside_two_readings_at_tame_places,
  TamePlacePairing.Seated.Realization.outsideTwoTameBookkeeping
#guard_depends_on
  TamePlacePairing.Seated.Realization.outside_two_readings_of_residual,
  TamePlacePairing.PlaceIndexedTameRealization.OutsideTwoTameBookkeeping.outside_two_readings_of_tame_and_residual
#guard_depends_on
  TamePlacePairing.Seated.Realization.outside_two_readings_of_residual,
  TamePlacePairing.Seated.Realization.outsideTwoTameBookkeeping

/-! ## Common-action proof-value wiring -/

#guard_depends_on IsDedekindDomain.selmerGroup.toClass_ker,
  IsDedekindDomain.selmerGroup.toClass
#guard_depends_on IsDedekindDomain.selmerGroup.toClass_range,
  IsDedekindDomain.selmerGroup.toClass
#guard_depends_on CommonActionStage.selmerClassProjection,
  IsDedekindDomain.selmerGroup.toClass
#guard_depends_on CommonActionStage.selmerClassProjection,
  IsDedekindDomain.selmerGroup.toClass_range
#guard_depends_on CommonActionStage.selmerClassSequenceRealization,
  CommonActionStage.selmerClassProjection
#guard_depends_on CommonActionStage.selmerClassSequenceRealization,
  IsDedekindDomain.selmerGroup.toClass_ker
#guard_depends_on CommonActionStage.selmerClassSequenceRealization,
  IsDedekindDomain.selmerGroup.toClass_range
#guard_depends_on CommonActionStage.WithheldSelmerClassSequenceRealization,
  CommonActionStage.selmerClassSequenceRealization

#guard_depends_on CommonActionStage.unitInclusion_injective,
  IsDedekindDomain.selmerGroup.fromUnitLift_injective
#guard_depends_on CommonActionStage.realUnitInclusion,
  CommonActionStage.realUnitClass
#guard_depends_on CommonActionStage.realUnitInclusion,
  CommonActionStage.unitInclusion
#guard_depends_on CommonActionStage.ExactFilteredPair.unitInclusion_injective,
  CommonActionStage.ExactFilteredLeg.unitInclusion_injective
#guard_depends_on CommonActionStage.ExactFilteredPair.exact_at_carrier,
  CommonActionStage.ExactFilteredLeg.exact_at_carrier
#guard_depends_on CommonActionStage.ExactFilteredPair.classProjection_surjective,
  CommonActionStage.ExactFilteredLeg.classProjection_surjective
#guard_depends_on CommonActionStage.ExactFilteredPair.classProjection_liftClassPair,
  CommonActionStage.ExactFilteredPair.classProjection_surjective
#guard_depends_on CommonActionStage.ExactFilteredPair.antitone_filtration,
  CommonActionStage.ExactFilteredLeg.antitone_filtration
#guard_depends_on CommonActionStage.ExactFilteredPair.class_p_torsion,
  CommonActionStage.ExactFilteredLeg.class_p_torsion
#guard_depends_on CommonActionStage.IntegralReflectionInput.sharpTransport,
  LinkingInterfaces.IntegralStickelbergerIdeal.SharpTransformationGuard.sharp_image_eq_omega_reflected
#guard_depends_on CommonActionStage.IntegralReflectionInput.sharpTransport,
  Ideal.mem_map_of_mem
#guard_depends_on CommonActionStage.IntegralReflectionInput.sharpTransport_coe,
  CommonActionStage.IntegralReflectionInput.sharpTransport
#guard_depends_on CommonActionStage.GuardedPairedCarrier.exactPair,
  CommonActionStage.exactLegOfFilteredStickelbergerCarrier
#guard_depends_on CommonActionStage.GuardedPairedCarrier.chiConversionReceipt,
  LinkingInterfaces.FilteredStickelbergerCarrier.conversionReceipt
#guard_depends_on
  CommonActionStage.GuardedPairedCarrier.reflectedDualConversionReceipt,
  LinkingInterfaces.FilteredStickelbergerCarrier.conversionReceipt
#guard_depends_on CommonActionStage.GuardedPairedCarrier.pairedConversionReceipts,
  CommonActionStage.IntegralReflectionInput.sharpTransport
#guard_depends_on CommonActionStage.GuardedPairedCarrier.pairedConversionReceipts,
  LinkingInterfaces.FilteredStickelbergerCarrier.conversionReceipt
#guard_depends_on CommonActionStage.lambdaAction_apply,
  CommonActionStage.lambdaAction
#guard_depends_on CommonActionStage.deltaAction,
  CommonActionStage.lambdaAction
#guard_depends_on CommonActionStage.deltaAction_apply,
  CommonActionStage.deltaAction
#guard_depends_on CommonActionStage.RouteMaps.closedAtChi,
  LinearMap.comp
#guard_depends_on CommonActionStage.RouteMaps.closedAtReflected,
  LinearMap.comp
#guard_depends_on CommonActionStage.RouteMaps.openRoute_apply,
  CommonActionStage.RouteMaps.openRoute
#guard_depends_on CommonActionStage.RouteMaps.openRoute_sq_apply,
  CommonActionStage.RouteMaps.openRoute_apply
#guard_depends_on CommonActionStage.RouteMaps.ofArithmeticRepresentation,
  LinkingInterfaces.ArithmeticRepresentation.routeChiToReflected
#guard_depends_on CommonActionStage.RouteMaps.rho_routeSquared_eq_closed,
  LinkingInterfaces.ArithmeticRepresentation.rho_routeSquared
#guard_depends_on CommonActionStage.reflectionCycleCorner_eq,
  CommonActionStage.reflectionCycleCorner
#guard_depends_on CommonActionStage.reflectionCycleCorner_eq,
  TransverseAnnihilator.cyclePolynomial
#guard_depends_on CommonActionStage.stickelbergerCorner,
  CommonActionStage.baseCornerProjection
#guard_depends_on CommonActionStage.stickelbergerCorner_val,
  CommonActionStage.stickelbergerCorner
#guard_depends_on CommonActionStage.cornerCoefficient_smul_eq,
  smul_comm
#guard_depends_on CommonActionStage.cornerConversionReceipt,
  LinkingInterfaces.FilteredStickelbergerCarrier.stickelberger_conversion
#guard_depends_on CommonActionStage.cornerConversionReceipt,
  LinkingInterfaces.FilteredStickelbergerCarrier.conversionReceipt
#guard_depends_on CommonActionStage.cornerConversionReceipt_beta,
  CommonActionStage.cornerConversionReceipt
#guard_depends_on
  CommonActionStage.classProjection_cornerCoefficient_smul_eq_zero,
  LinkingInterfaces.FilteredStickelbergerCarrier.classProjection_smul_eq_zero
#guard_depends_on CommonActionStage.sevenDClassOperator,
  CommonActionStage.classSwap
#guard_depends_on CommonActionStage.sevenDClassCornerElement,
  CommonActionStage.sevenDClassOperator
#guard_depends_on CommonActionStage.sevenDClassShadowReceipt,
  CommonActionStage.sevenDClassCornerElement
#guard_depends_on CommonActionStage.allocatedRootState,
  ClassCarrier.numberFieldBoundedRepresentative
#guard_depends_on CommonActionStage.allocatedRootState_receipts,
  CommonActionStage.allocatedRootState
#guard_depends_on CommonActionStage.allocatedRootState_class,
  ClassCarrier.idealClassProjection_eq_source_class
#guard_depends_on CommonActionStage.allocatedRootState_source_eq,
  ClassCarrier.State.source_eq_principal_mul_reduced
#guard_depends_on CommonActionStage.allocatedSevenDClassReceipt,
  CommonActionStage.sevenDClassShadowReceipt
#guard_depends_on CommonActionStage.allocatedSevenDReceiptedRootState,
  CommonActionStage.allocatedSevenDClassReceipt
#guard_depends_on CommonActionStage.allocatedSevenDReceiptedRootState_receipt,
  CommonActionStage.allocatedSevenDReceiptedRootState
#guard_depends_on CommonActionStage.allocatedSevenDClassReceipt_payload,
  CommonActionStage.allocatedSevenDClassReceipt
#guard_depends_on CommonActionStage.allocatedRootClassPTorsion,
  KummerDrain.AllocatedFactorLedger.rootClass_torsion
#guard_depends_on CommonActionStage.allocatedSelmerObstruction,
  CommonActionStage.ExactFilteredPair.liftClassPair
#guard_depends_on CommonActionStage.classProjection_allocatedSelmerObstruction,
  CommonActionStage.ExactFilteredPair.classProjection_liftClassPair
#guard_depends_on CommonActionStage.Outcome.unitIdealResult,
  TransverseAnnihilator.CornerService.eq_zero_of_annihilates_of_bezout
#guard_depends_on
  CommonActionStage.StateConversionCompatibility.conversionReceipt_beta_eq_state_beta,
  CommonActionStage.StateConversionCompatibility.beta_eq
#guard_depends_on
  CommonActionStage.GuardedPairedCarrier.pairedCornerConversionReceipts,
  CommonActionStage.IntegralReflectionInput.sharpTransport
#guard_depends_on
  CommonActionStage.GuardedPairedCarrier.pairedCornerConversionReceipts,
  CommonActionStage.cornerConversionReceipt
#guard_depends_on CommonActionStage.reflectedSelmerRhoWall_target,
  CommonActionStage.reflectedSelmerRhoWall

/-! ## Vendored and realized sequence axiom boundary -/

/--
info: 'IsDedekindDomain.selmerGroup.toClass' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.toClass

/--
info: 'IsDedekindDomain.selmerGroup.toClass_ker' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.toClass_ker

/--
info: 'IsDedekindDomain.selmerGroup.toClass_range' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.toClass_range

/--
info: 'Fermat.Conservation.CommonActionStage.WithheldSelmerClassSequenceRealization' depends on axioms: [propext,
 Classical.choice,
 Quot.sound]
-/
#guard_msgs in
#print axioms CommonActionStage.WithheldSelmerClassSequenceRealization

/-! ## Exhaustive axiom boundary

Every declaration created below each W1--W5 namespace is inspected.  This is
exhaustive rather than a hand-maintained theorem sample, so newly added public
declarations are automatically audited as well. -/

open Lean Elab Command

/-- Fail if any declaration under a namespace prefix uses an axiom beyond
Lean's standard extensionality, choice, and quotient-soundness boundary. -/
elab "#guard_standard_axioms_prefix " p:ident : command => do
  let env ← getEnv
  let auditedPrefix := p.getId
  let allowed : Array Name :=
    #[``propext, ``Classical.choice, ``Quot.sound]
  let declarations :=
    env.constants.toList
      |>.map Prod.fst
      |>.filter auditedPrefix.isPrefixOf
  for declaration in declarations do
    let axioms ← Lean.collectAxioms declaration
    let unexpected := axioms.filter fun ax =>
      !allowed.contains ax
    unless unexpected.isEmpty do
      throwError
        "{declaration} depends on nonstandard axioms: {unexpected}"

#guard_standard_axioms_prefix Fermat.Conservation.InvolutiveBase
#guard_standard_axioms_prefix Fermat.Conservation.RouteAlgebra
#guard_standard_axioms_prefix Fermat.Conservation.SwapQuotient
#guard_standard_axioms_prefix Fermat.Conservation.TransverseAnnihilator.CornerService
#guard_standard_axioms_prefix Fermat.Conservation.LinkingInterfaces
#guard_standard_axioms_prefix Fermat.Conservation.CommonActionStage
#guard_standard_axioms_prefix Fermat.Conservation.TatePairing
#guard_standard_axioms_prefix Fermat.Conservation.TameSymbol
#guard_standard_axioms_prefix Fermat.Conservation.SelmerEigenspace
#guard_standard_axioms_prefix Fermat.Conservation.TamePlacePairing
