/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, Fable

# Executable audit for the twisted linking stage

This non-imported leaf checks the linking W1--W5 and common-action W0--W3
public surfaces, the intended proof-value dependency direction, and the
standard-axiom boundary.  In particular, strict-route perfect return is
refuted upstream and is obtained only through the explicit swap quotient map.
-/
import Fermat.Conservation.GuardDependsOn
import Fermat.Conservation.CohomologyLedger
import Fermat.Conservation.CommonActionStage
import Fermat.Conservation.LinkingInterfaces
import Fermat.Conservation.PowerRootObstruction
import Fermat.Conservation.PowerRootExactSequence
import Fermat.Conservation.PowerRootNaturality
import Fermat.Conservation.SelmerSequence
import Fermat.Conservation.SelmerEigenspace
import Fermat.Conservation.SteeringFiber
import Fermat.Conservation.SwapQuotient
import Fermat.Conservation.TatePairing
import Fermat.Conservation.TamePlacePairing
import Fermat.Conservation.TameSymbol
import Fermat.Conservation.TransverseAnnihilator

open Fermat.Conservation

/-! ## Silent-fiber steering surface -/

#check SteeringFiber.SurjectiveLinearMap
#check SteeringFiber.K_T
#check SteeringFiber.CompatibleLift
#check SteeringFiber.readingDirections
#check SteeringFiber.attainableReadings
#check SteeringFiber.readingCoset
#check SteeringFiber.reachableReadings
#check SteeringFiber.CanPrescribeCoordinate
#check SteeringFiber.canPrescribeCoordinate_iff
#check SteeringFiber.FixedAttention
#check SteeringFiber.readingDirections_eq_bot_iff_fixed
#check SteeringFiber.jointObservation
#check SteeringFiber.exists_jointDual_of_fixed
#check SteeringFiber.rhoDual
#check SteeringFiber.rhoDual_pullback_of_silence
#check SteeringFiber.reading_preimage_independent
#check SteeringFiber.TransverseDirection
#check SteeringFiber.readingDirections_eq_top_of_transverse
#check SteeringFiber.steeringAmount
#check SteeringFiber.focusedPoint
#check SteeringFiber.FocusedLift
#check SteeringFiber.focusedLift
#check SteeringFiber.focusedLift_point
#check SteeringFiber.canPrescribeCoordinate_of_transverse
#check SteeringFiber.fixed_or_steerable

#guard_depends_on SteeringFiber.exists_jointDual_of_fixed,
  LinearMap.range_dualMap_eq_dualAnnihilator_ker
#guard_depends_on SteeringFiber.focusedLift, SteeringFiber.focusedPoint

/-! ## Vendored PowerRoot generator surface -/

#check PowerRoot.Factorization
#check PowerRoot.Factorization.isMulTorsionFree
#check PowerRoot.powerSubgroup
#check PowerRoot.mem_powerSubgroup
#check PowerRoot.mapOnPowerQuotients
#check PowerRoot.mapOnPowerQuotients_mk
#check PowerRoot.divisibleElements
#check PowerRoot.divisibleClasses
#check PowerRoot.Factorization.mem_powerSubgroup_iff
#check PowerRoot.Factorization.mk_mem_divisibleClasses_iff
#check PowerRoot.Factorization.mem_divisibleElements_iff
#check PowerRoot.toDivisibleClasses
#check PowerRoot.toDivisibleClasses_apply
#check PowerRoot.toDivisibleClasses_surjective
#check PowerRoot.exists_root
#check PowerRoot.root
#check PowerRoot.root_power
#check PowerRoot.root_eq_of_pow_eq
#check PowerRoot.root_one
#check PowerRoot.root_mul
#check PowerRoot.shift
#check PowerRoot.coe_shift
#check PowerRoot.root_shift
#check PowerRoot.rootHom
#check PowerRoot.rootHom_apply
#check PowerRoot.fromKernel
#check PowerRoot.fromKernel_mk
#check PowerRoot.fromKernel_injective
#check PowerRoot.obstruction
#check PowerRoot.obstruction_toDivisibleClasses
#check PowerRoot.obstruction_ker
#check PowerRoot.obstruction_range

/-! ## Principal-ideal complex and unsplit extension surface -/

#check PowerRootExactSequence.TwoTermComplex
#check PowerRootExactSequence.TwoTermComplex.PiOne
#check PowerRootExactSequence.TwoTermComplex.PiZero
#check PowerRootExactSequence.principalIdealArrow
#check PowerRootExactSequence.principalIdealComplex
#check PowerRootExactSequence.PrincipalIdealPiOne
#check PowerRootExactSequence.PrincipalIdealPiZero
#check PowerRootExactSequence.principalIdealFactorization
#check PowerRootExactSequence.unitsToPiOne
#check PowerRootExactSequence.unitsEquivPiOne
#check PowerRootExactSequence.piOneEquivUnits
#check PowerRootExactSequence.piZeroEquivClassGroup
#check PowerRootExactSequence.UnitPowerClasses
#check PowerRootExactSequence.ClassPowerTorsion
#check PowerRootExactSequence.SelmerMiddle
#check PowerRootExactSequence.unitReceipt
#check PowerRootExactSequence.componentShadow
#check PowerRootExactSequence.UnsplitExtensionClass
#check PowerRootExactSequence.principalIdealExtensionClass
#check PowerRootExactSequence.unitReceipt_injective
#check PowerRootExactSequence.componentShadow_ker
#check PowerRootExactSequence.componentShadow_surjective
#check PowerRootExactSequence.componentShadow_unitReceipt

/-! ## PowerRoot cube naturality surface -/

#check PowerRootNaturality.ArrowMorphism
#check PowerRootNaturality.ArrowMorphism.ext
#check PowerRootNaturality.ArrowMorphism.identity
#check PowerRootNaturality.ArrowMorphism.comp
#check PowerRootNaturality.ArrowMorphism.identity_sourceMap_apply
#check PowerRootNaturality.ArrowMorphism.identity_targetMap_apply
#check PowerRootNaturality.ArrowMorphism.comp_sourceMap_apply
#check PowerRootNaturality.ArrowMorphism.comp_targetMap_apply
#check PowerRootNaturality.ArrowMorphism.endomorphismMonoid
#check PowerRootNaturality.ArrowMorphism.one_sourceMap_apply
#check PowerRootNaturality.ArrowMorphism.one_targetMap_apply
#check PowerRootNaturality.ArrowMorphism.mul_sourceMap_apply
#check PowerRootNaturality.ArrowMorphism.mul_targetMap_apply
#check PowerRootNaturality.ArrowMorphism.mul_eq_comp
#check PowerRootNaturality.ArrowMorphism.mapOnPowerQuotients_natural
#check PowerRootNaturality.ArrowMorphism.mapDivisibleElements
#check PowerRootNaturality.ArrowMorphism.mapDivisibleElements_apply
#check PowerRootNaturality.ArrowMorphism.mapDivisibleClasses
#check PowerRootNaturality.ArrowMorphism.mapDivisibleClasses_apply_coe
#check PowerRootNaturality.ArrowMorphism.mapDivisibleClasses_toDivisibleClasses
#check PowerRootNaturality.ArrowMorphism.mapCokernel
#check PowerRootNaturality.ArrowMorphism.mapCokernel_mk
#check PowerRootNaturality.ArrowMorphism.root_natural
#check PowerRootNaturality.ArrowMorphism.root_mul_natural
#check PowerRootNaturality.ArrowMorphism.mapDivisibleElements_shift
#check PowerRootNaturality.ArrowMorphism.root_shift_natural
#check PowerRootNaturality.ArrowMorphism.obstruction_natural
#check PowerRootNaturality.GroupRingEquivariance
#check PowerRootNaturality.GroupRingEquivariance.arrowMorphism
#check PowerRootNaturality.GroupRingEquivariance.arrowMorphism_one
#check PowerRootNaturality.GroupRingEquivariance.arrowMorphism_mul
#check PowerRootNaturality.GroupRingEquivariance.action
#check PowerRootNaturality.GroupRingEquivariance.action_apply
#check PowerRootNaturality.GroupRingEquivariance.actOnDivisibleClasses
#check PowerRootNaturality.GroupRingEquivariance.actOnCokernel
#check PowerRootNaturality.GroupRingEquivariance.root_equivariant
#check PowerRootNaturality.GroupRingEquivariance.obstruction_equivariant
#check PowerRootNaturality.ReflectionInterface
#check PowerRootNaturality.ReflectionInterface.toArrowMorphism
#check PowerRootNaturality.ReflectionInterface.symmArrowMorphism
#check PowerRootNaturality.ReflectionInterface.reflectDivisibleClasses
#check PowerRootNaturality.ReflectionInterface.reflectCokernel
#check PowerRootNaturality.ReflectionInterface.root_reflection
#check PowerRootNaturality.ReflectionInterface.obstruction_reflection
#check PowerRootNaturality.LocalizationInterface
#check PowerRootNaturality.LocalizationInterface.toArrowMorphism
#check PowerRootNaturality.LocalizationInterface.localizeDivisibleClasses
#check PowerRootNaturality.LocalizationInterface.localizeCokernel
#check PowerRootNaturality.LocalizationInterface.ObstructionSquareLaw
#check PowerRootNaturality.LocalizationInterface.localObstructionAfterLocalization
#check PowerRootNaturality.LocalizationInterface.localizationAfterGlobalObstruction
#check PowerRootNaturality.LocalizationInterface.obstruction_square
#check PowerRootNaturality.LocalizationInterface.powerRootObstructionSquareLaw

/-! ## Public linking surface -/

#check InvolutiveBase.TeichmullerData
#check InvolutiveBase.GroupAlgebra
#check InvolutiveBase.hash
#check InvolutiveBase.hash_apply
#check InvolutiveBase.hash_hash
#check InvolutiveBase.reflectionPairing
#check InvolutiveBase.reflection_conservation_law
#check InvolutiveBase.reflectedCharacter
#check InvolutiveBase.characterIdempotent
#check InvolutiveBase.characterIdempotent_isIdempotent
#check InvolutiveBase.groupElement_mul_characterIdempotent
#check InvolutiveBase.hash_characterIdempotent
#check InvolutiveBase.hash_trivialCharacterIdempotent
#check InvolutiveBase.plusProjector
#check InvolutiveBase.minusProjector
#check InvolutiveBase.plusProjector_isIdempotent
#check InvolutiveBase.minusProjector_isIdempotent
#check InvolutiveBase.hash_conjugationElement
#check InvolutiveBase.plus_minus_projectors_exchanged

#check RouteAlgebra.HasSharp
#check RouteAlgebra.teichmullerSharp
#check RouteAlgebra.mathlibSkewPolynomialRoute
#check RouteAlgebra.Route
#check RouteAlgebra.route_covariance
#check RouteAlgebra.closedRoute
#check RouteAlgebra.closedRoute_central
#check RouteAlgebra.closedRoute_ne_one
#check RouteAlgebra.CanonicalPathPresentation
#check RouteAlgebra.CanonicalPathPresentation.closedAtChi
#check RouteAlgebra.CanonicalPathPresentation.closedAtReflected
#check RouteAlgebra.BaseCorner
#check RouteAlgebra.RouteCorner
#check RouteAlgebra.routeCorner_coeff_odd_eq_zero
#check RouteAlgebra.cornerClosedRoute
#check RouteAlgebra.cornerPolynomialMap
#check RouteAlgebra.cornerToPolynomial
#check RouteAlgebra.cornerPolynomialEquiv
#check RouteAlgebra.cornerPolynomialEquiv_X
#check RouteAlgebra.teichmullerSharp_characterIdempotent
#check RouteAlgebra.characterCornerPolynomialEquiv

#check SwapQuotient.swapIdeal
#check SwapQuotient.Swap
#check SwapQuotient.quotientMap
#check SwapQuotient.generator
#check SwapQuotient.coefficient
#check SwapQuotient.sevenARouteWord
#check SwapQuotient.sevenDRouteWord
#check SwapQuotient.sevenARelationWord
#check SwapQuotient.sevenDRelationWord
#check SwapQuotient.sevenARelationWord_image
#check SwapQuotient.sevenDRelationWord_image
#check SwapQuotient.quotientMap_closedRoute
#check SwapQuotient.generator_sq
#check SwapQuotient.generator_coefficient
#check SwapQuotient.flowElement
#check SwapQuotient.flowElement_two
#check SwapQuotient.piCommon
#check SwapQuotient.piDifference
#check SwapQuotient.piCommon_add_piDifference
#check SwapQuotient.piCommon_idempotent
#check SwapQuotient.piDifference_idempotent
#check SwapQuotient.piCommon_piDifference_orthogonal
#check SwapQuotient.sevenARelationWord_eigenspace
#check SwapQuotient.sevenDRelationWord_eigenspace
#check SwapQuotient.swapLinear
#check SwapQuotient.swapLinear_sq
#check SwapQuotient.commonDifference
#check SwapQuotient.commonDifference_swap
#check SwapQuotient.commonProjector_formula
#check SwapQuotient.differenceProjector_formula
#check SwapQuotient.sevenARelationOperator_apply
#check SwapQuotient.sevenDRelationOperator_apply
#check SwapQuotient.flowOperator
#check SwapQuotient.flowOperator_apply
#check SwapQuotient.flowOperator_two

#check TransverseAnnihilator.CornerService.BezoutCertificate
#check TransverseAnnihilator.CornerService.eq_zero_of_annihilates_of_bezout
#check TransverseAnnihilator.CornerService.bezout_identity_in_ambient
#check TransverseAnnihilator.CornerService.eq_zero_in_idempotentCorner
#check TransverseAnnihilator.CornerService.LivelockCarrier
#check TransverseAnnihilator.CornerService.livelockCarrier_subsingleton_iff
#check TransverseAnnihilator.CornerService.livelockCarrier_nontrivial_iff
#check TransverseAnnihilator.CornerService.CornerLivelockChannel
#check TransverseAnnihilator.CornerService.nonempty_cornerLivelockChannel_iff
#check TransverseAnnihilator.breaksCycle_iff_polynomialGCD_eq_one
#check TransverseAnnihilator.polynomial_livelockCarrier_subsingleton_iff
#check TransverseAnnihilator.nonempty_polynomial_cornerLivelockChannel_iff
#check TransverseAnnihilator.eq_zero_of_cycle_and_transverse_gcd_eq_one

#check LinkingInterfaces.IntegralPadicGroupAlgebra
#check LinkingInterfaces.IntegralStickelbergerIdeal
#check LinkingInterfaces.IntegralStickelbergerIdeal.SharpTransformationGuard
#check LinkingInterfaces.sharp_trivialProjector_eq_omegaProjector
#check LinkingInterfaces.FilteredStickelbergerCarrier
#check LinkingInterfaces.FilteredStickelbergerCarrier.smul_mem_unitRange
#check LinkingInterfaces.FilteredStickelbergerCarrier.classProjection_smul_eq_zero
#check LinkingInterfaces.FilteredStickelbergerCarrier.conversionReceipt
#check LinkingInterfaces.PrincipalIdealArrowEnd
#check LinkingInterfaces.ArithmeticRepresentation
#check LinkingInterfaces.ArithmeticRepresentation.rho_preserves_principal_arrow
#check LinkingInterfaces.ArithmeticRepresentation.rho_root_square
#check LinkingInterfaces.ArithmeticRepresentation.rho_powerRoot_square
#check LinkingInterfaces.ArithmeticRepresentation.selmerAction_routeSquared
#check LinkingInterfaces.StrictRouteArithmeticRepresentation
#check LinkingInterfaces.StrictRouteArithmeticRepresentation.selmerAction_closedRoute
#check LinkingInterfaces.WithheldStrictRouteArithmeticRepresentation
#check LinkingInterfaces.ReflectedSelmerArithmeticRepresentationTarget

/-! ## Place-indexed Tate pairing and reciprocity surface -/

#check TatePairing.character_mul_reflectedCharacter
#check TatePairing.PlaceIndexedLocalPairing
#check TatePairing.PlaceIndexedLocalPairing.pairAt
#check TatePairing.PlaceIndexedLocalPairing.pairAt_smul_adjoint
#check TatePairing.PlaceIndexedLocalPairing.pairAt_hash_smul_adjoint
#check TatePairing.PlaceIndexedLocalPairing.finite_support
#check TatePairing.PlaceLedger
#check TatePairing.PlaceLedger.toLedger
#check TatePairing.PlaceLedger.toVacuumTransfer
#check TatePairing.PlaceLedger.toVacuumTransfer_L1
#check TatePairing.GlobalReciprocityLaw
#check TatePairing.GlobalReciprocityLaw.placeLedger
#check TatePairing.GlobalReciprocityLaw.ledger_conservation_identity
#check TatePairing.GlobalReciprocityLaw.reciprocityTransfer
#check TatePairing.GlobalReciprocityLaw.reciprocity_L1_conservation
#check TatePairing.GlobalReciprocityLaw.pairAt_eq_zero_of_other_places
#check TatePairing.LocalOrthogonalityGuard
#check TatePairing.LocalOrthogonalityGuard.pairAt_eq_zero

/-! ## Explicit tame Hilbert-symbol surface -/

#check TameSymbol.KummerClass
#check TameSymbol.Context
#check TameSymbol.Context.residueCard
#check TameSymbol.Context.tameExponent
#check TameSymbol.Context.raw
#check TameSymbol.Context.raw_one_left
#check TameSymbol.Context.raw_one_right
#check TameSymbol.Context.raw_mul_left
#check TameSymbol.Context.raw_mul_right
#check TameSymbol.Context.raw_swap
#check TameSymbol.Context.residue_power_pow_eq_one
#check TameSymbol.Context.powerToRoots
#check TameSymbol.Context.rootsEquivZPowers
#check TameSymbol.Context.residueCharacter
#check TameSymbol.Context.residueCharacter_one
#check TameSymbol.Context.residueCharacter_mul
#check TameSymbol.Context.value
#check TameSymbol.Context.value_eq_explicit_formula
#check TameSymbol.Context.value_one_left
#check TameSymbol.Context.value_one_right
#check TameSymbol.Context.value_mul_left
#check TameSymbol.Context.value_mul_right
#check TameSymbol.Context.value_swap
#check TameSymbol.Context.toAddMonoidHom
#check TameSymbol.Context.toAddMonoidHom_apply
#check TameSymbol.Context.toAddMonoidHomDualFirst
#check TameSymbol.Context.toAddMonoidHomDualFirst_apply
#check TameSymbol.Context.raw_eq_one_of_ord_eq_zero
#check TameSymbol.Context.both_units_silence
#check TameSymbol.Context.value_eq_zero_of_ord_eq_zero
#check TameSymbol.Context.raw_eq_pth_power_of_p_dvd_ord
#check TameSymbol.Context.value_eq_zero_of_p_dvd_ord
#check TameSymbol.Context.value_pow_left
#check TameSymbol.Context.value_pow_right
#check TameSymbol.Context.value_pth_power_left
#check TameSymbol.Context.value_pth_power_right
#check TameSymbol.Context.rightMonoidHom
#check TameSymbol.Context.ordModPRep
#check TameSymbol.Context.ordModP
#check TameSymbol.Context.ordModP_mk
#check TameSymbol.Context.rightModP
#check TameSymbol.Context.rightModP_mk
#check TameSymbol.Context.rightModPFamily
#check TameSymbol.Context.modPMul
#check TameSymbol.Context.modP
#check TameSymbol.Context.modP_mk_mk
#check TameSymbol.Context.modP_eq_zero_of_ordModP_eq_zero
#check TameSymbol.Context.SteinbergValuationCases
#check TameSymbol.Context.SteinbergValuationCases.raw_eq_one
#check TameSymbol.Context.SteinbergValuationCases.steinberg_of_cases
#check TameSymbol.Context.SteinbergRealization
#check TameSymbol.Context.steinberg
#check TameSymbol.Context.PlaceGaloisData
#check TameSymbol.Context.PlaceGaloisData.raw_place_action
#check TameSymbol.Context.PlaceGaloisData.value_place_galois_equivariant
#check TameSymbol.Context.GaloisData
#check TameSymbol.Context.GaloisData.raw_action
#check TameSymbol.Context.GaloisData.value_galois_equivariant
#check TameSymbol.Context.GaloisData.value_action_adjoint

/-! ## Seated Selmer-eigenspace surface -/

#check SelmerEigenspace.SelmerCarrier
#check SelmerEigenspace.selmerCarrier_eq_commonActionStage
#check SelmerEigenspace.p_nsmul_eq_zero
#check SelmerEigenspace.instModuleZMod
#check SelmerEigenspace.instModulePadicInt
#check SelmerEigenspace.padicInt_smul_eq_toZMod_smul
#check SelmerEigenspace.SelmerDeltaRepresentation
#check SelmerEigenspace.characterEigenspace
#check SelmerEigenspace.instCharacterEigenspaceAddCommGroup
#check SelmerEigenspace.mem_characterEigenspace_iff
#check SelmerEigenspace.SelmerChi
#check SelmerEigenspace.SelmerChiStar
#check SelmerEigenspace.characterEigenspaceRepresentation
#check SelmerEigenspace.instCharacterEigenspaceGroupAlgebraModule
#check SelmerEigenspace.coe_groupElement_smul
#check SelmerEigenspace.toSeatedCarrier
#check SelmerEigenspace.toAdditiveSelmer
#check SelmerEigenspace.toConcreteSelmer
#check SelmerEigenspace.toKummerQuotient
#check SelmerEigenspace.toKummerClass
#check SelmerEigenspace.toSeatedCarrier_apply
#check SelmerEigenspace.toAdditiveSelmer_apply
#check SelmerEigenspace.toConcreteSelmer_apply
#check SelmerEigenspace.toKummerQuotient_apply
#check SelmerEigenspace.toKummerClass_apply
#check SelmerEigenspace.toAdditiveSelmer_injective
#check SelmerEigenspace.toConcreteSelmer_injective
#check SelmerEigenspace.toKummerQuotient_injective
#check SelmerEigenspace.valuationOfNeZeroMod_eq_one
#check SelmerEigenspace.valuationOfNeZeroMod_mk_eq_one_iff_dvd
#check SelmerEigenspace.representative_valuation_dvd
#check SelmerEigenspace.quotientRepresentative
#check SelmerEigenspace.quotientRepresentative_mk
#check SelmerEigenspace.quotientRepresentative_valuation_dvd
#check SelmerEigenspace.exists_representative_valuation_dvd
#check SelmerEigenspace.DOmegaSelmerChiStar
#check SelmerEigenspace.ReflectedDualCharacterGlue
#check SelmerEigenspace.ReflectedDualCharacterGlue.carrierDualEquiv_smul
#check SelmerEigenspace.ReflectedSelmerPair

/-! ### Arbitrary-support Selmer-eigenspace surface -/

#check SelmerEigenspace.SelmerCarrierAt
#check SelmerEigenspace.SelmerDeltaRepresentationAt
#check SelmerEigenspace.characterEigenspaceAt
#check SelmerEigenspace.instCharacterEigenspaceAtAddCommGroup
#check SelmerEigenspace.mem_characterEigenspaceAt_iff
#check SelmerEigenspace.characterIdempotent_action_mem_characterEigenspaceAt
#check SelmerEigenspace.characterProjectorAt
#check SelmerEigenspace.characterProjectorAt_apply
#check SelmerEigenspace.characterProjectorAt_idempotent
#check SelmerEigenspace.SelmerChiAt
#check SelmerEigenspace.SelmerChiStarAt
#check SelmerEigenspace.characterEigenspaceRepresentationAt
#check SelmerEigenspace.instCharacterEigenspaceAtGroupAlgebraModule
#check SelmerEigenspace.toSupportedCarrier
#check SelmerEigenspace.toConcreteSelmerAt
#check SelmerEigenspace.toKummerQuotientAt
#check SelmerEigenspace.toKummerClassAt
#check SelmerEigenspace.toKummerClassAt_apply
#check SelmerEigenspace.quotientRepresentativeAt
#check SelmerEigenspace.quotientRepresentativeAt_mk
#check SelmerEigenspace.valuationOfNeZeroMod_eq_one_of_not_mem
#check SelmerEigenspace.quotientRepresentativeAt_valuation_dvd_of_not_mem
#check SelmerEigenspace.supportValuation
#check SelmerEigenspace.supportValuationAt
#check SelmerEigenspace.supportValuation_apply
#check SelmerEigenspace.emptySupportInclusion
#check SelmerEigenspace.supportValuation_emptySupportInclusion_eq_zero
#check SelmerEigenspace.supportValuation_ker_eq_range_emptySupportInclusion
#check SelmerEigenspace.eigenspaceSupportValuation
#check SelmerEigenspace.eigenspaceSupportValuationAt
#check SelmerEigenspace.eigenspaceSupportValuation_apply
#check SelmerEigenspace.DOmegaSelmerChiStarAt

/-! ## Tame place-indexed realization surface -/

#check TamePlacePairing.PlaceIndexedTameRealization
#check TamePlacePairing.PlaceIndexedTameRealization.SelectedValuationsZeroAt
#check TamePlacePairing.PlaceIndexedTameRealization.pairAt_eq_zero_of_p_dvd_ord
#check TamePlacePairing.PlaceIndexedTameRealization.OutsideTwoTameBookkeeping
#check TamePlacePairing.PlaceIndexedTameRealization.OutsideTwoTameBookkeeping.outside_two_readings_at_tame_places
#check TamePlacePairing.PlaceIndexedTameRealization.OutsideTwoTameBookkeeping.outside_two_readings_of_tame_and_residual
#check TamePlacePairing.WildLocalInterface
#check TamePlacePairing.WildLocalInterface.toPlaceIndexedLocalPairing
#check TamePlacePairing.WildLocalInterface.pairAt_distinguished
#check TamePlacePairing.WildLocalInterface.pairAt_eq_zero_of_ne
#check TamePlacePairing.Seated.Place
#check TamePlacePairing.Seated.Primal
#check TamePlacePairing.Seated.ReflectedDual
#check TamePlacePairing.Seated.Pairing
#check TamePlacePairing.Seated.WildInterface
#check TamePlacePairing.Seated.ordModP_toKummerClass_eq_zero_of_ord_eq_valuation
#check TamePlacePairing.Seated.Realization
#check TamePlacePairing.Seated.Realization.ofWild
#check TamePlacePairing.Seated.Realization.toPlaceIndexedTameRealization
#check TamePlacePairing.Seated.Realization.toPlaceIndexedTameRealization_primalClass
#check TamePlacePairing.Seated.Realization.toPlaceIndexedTameRealization_dualClass
#check TamePlacePairing.Seated.Realization.ordModP_toKummerClass_eq_zero
#check TamePlacePairing.Seated.Realization.selectedValuationsZeroAt
#check TamePlacePairing.Seated.Realization.pairAt_eq_zero_at_tame_place
#check TamePlacePairing.Seated.Realization.outsideTwoTameBookkeeping
#check TamePlacePairing.Seated.Realization.outside_two_readings_at_tame_places
#check TamePlacePairing.Seated.Realization.outside_two_readings_of_residual

/-! ## Vendored Selmer class-sequence surface -/

#check IsDedekindDomain.selmerGroup.fractionalIdealFactorization
#check IsDedekindDomain.selmerGroup.fractionalIdealFactorization_apply
#check IsDedekindDomain.selmerGroup.toClass
#check IsDedekindDomain.selmerGroup.toClass_ker
#check IsDedekindDomain.selmerGroup.toClass_range
#check IsDedekindDomain.selmerGroup.DivisorAway
#check IsDedekindDomain.selmerGroup.fractionalIdealToDivisorAway
#check IsDedekindDomain.selmerGroup.fractionalIdealToDivisorAway_apply
#check IsDedekindDomain.selmerGroup.principalDivisorAway
#check IsDedekindDomain.selmerGroup.principalDivisorAway_apply
#check IsDedekindDomain.selmerGroup.eq_divisibleClasses
#check IsDedekindDomain.selmerGroup.equivDivisibleClasses
#check IsDedekindDomain.selmerGroup.principalDivisorAway_ker
#check IsDedekindDomain.selmerGroup.sUnitEquivPrincipalDivisorAwayKer
#check IsDedekindDomain.selmerGroup.sUnitClassesEquivPrincipalDivisorAwayKer
#check IsDedekindDomain.selmerGroup.sUnitClassesEquivIntegerUnits
#check IsDedekindDomain.selmerGroup.fromSUnitLift
#check IsDedekindDomain.selmerGroup.fromSIntegerUnitLift
#check IsDedekindDomain.selmerGroup.fromSUnitLift_injective
#check IsDedekindDomain.selmerGroup.fromSIntegerUnitLift_injective
#check IsDedekindDomain.selmerGroup.obstructionTarget
#check IsDedekindDomain.selmerGroup.toSClass
#check IsDedekindDomain.selmerGroup.toSClass_ker
#check IsDedekindDomain.selmerGroup.toSClass_ker_integerUnits
#check IsDedekindDomain.selmerGroup.toSClass_range
#check IsDedekindDomain.selmerGroup.fractionalIdealToDivisorAway_surjective
#check IsDedekindDomain.selmerGroup.classGroupToObstructionTarget
#check IsDedekindDomain.selmerGroup.classGroupToObstructionTarget_mk
#check IsDedekindDomain.selmerGroup.classGroupToObstructionTarget_surjective
#check IsDedekindDomain.selmerGroup.invertedPrimeClasses
#check IsDedekindDomain.selmerGroup.primeClass
#check IsDedekindDomain.selmerGroup.classesOfPrimesIn
#check IsDedekindDomain.selmerGroup.SClassGroup
#check IsDedekindDomain.selmerGroup.classGroupToObstructionTarget_primeClass
#check IsDedekindDomain.selmerGroup.invertedPrimeClasses_eq_classesOfPrimesIn
#check IsDedekindDomain.selmerGroup.obstructionTargetEquivSClassGroup
#check IsDedekindDomain.selmerGroup.classGroupToObstructionTarget_empty_injective
#check IsDedekindDomain.selmerGroup.obstructionTargetEmptyEquivClassGroup
#check IsDedekindDomain.selmerGroup.obstructionTargetEmptyEquivClassGroup_toSClass
#check IsDedekindDomain.selmerGroup.obstructionTargetEmptyEquivClassGroup_comp_toSClass
#check IsDedekindDomain.selmerGroup.toSClass_empty_ker_eq_toClass_ker
#check IsDedekindDomain.selmerGroup.map_toSClass_empty_range_eq_toClass_range

/-! ## Common-action stage surface -/

#check CommonActionStage.UnitModP
#check CommonActionStage.Selmer
#check CommonActionStage.ClassPTorsion
#check CommonActionStage.unitInclusion
#check CommonActionStage.unitInclusion_injective
#check CommonActionStage.selmerClassProjection
#check CommonActionStage.selmerClassSequenceRealization
#check CommonActionStage.realUnitClass
#check CommonActionStage.realUnitInclusion
#check CommonActionStage.SelmerClassSequenceRealization
#check CommonActionStage.WithheldSelmerClassSequenceRealization
#check CommonActionStage.SelmerCharacterDual
#check CommonActionStage.ExactFilteredLeg
#check CommonActionStage.ReflectedDualRealization
#check CommonActionStage.ExactFilteredPair
#check CommonActionStage.ReflectedExactFilteredPair
#check CommonActionStage.ExactFilteredPair.Carrier
#check CommonActionStage.ExactFilteredPair.unitInclusion
#check CommonActionStage.ExactFilteredPair.classProjection
#check CommonActionStage.ExactFilteredPair.unitInclusion_injective
#check CommonActionStage.ExactFilteredPair.exact_at_carrier
#check CommonActionStage.ExactFilteredPair.classProjection_surjective
#check CommonActionStage.ExactFilteredPair.liftClassPair
#check CommonActionStage.ExactFilteredPair.classProjection_liftClassPair
#check CommonActionStage.ExactFilteredPair.filtration
#check CommonActionStage.ExactFilteredPair.antitone_filtration
#check CommonActionStage.ExactFilteredPair.class_p_torsion
#check CommonActionStage.KummerCharacterLegCompatibility
#check CommonActionStage.KummerPairedBinding
#check CommonActionStage.exactLegOfFilteredStickelbergerCarrier
#check CommonActionStage.IntegralReflectionInput
#check CommonActionStage.IntegralReflectionInput.sharpTransport
#check CommonActionStage.IntegralReflectionInput.sharpTransport_coe
#check CommonActionStage.GuardedPairedCarrier
#check CommonActionStage.GuardedPairedCarrier.exactPair
#check CommonActionStage.GuardedPairedCarrier.chiConversionReceipt
#check CommonActionStage.GuardedPairedCarrier.reflectedDualConversionReceipt
#check CommonActionStage.GuardedPairedCarrier.pairedConversionReceipts
#check CommonActionStage.lambdaAction
#check CommonActionStage.lambdaAction_apply
#check CommonActionStage.deltaAction
#check CommonActionStage.deltaAction_apply
#check CommonActionStage.RouteMaps
#check CommonActionStage.RouteMaps.closedAtChi
#check CommonActionStage.RouteMaps.closedAtReflected
#check CommonActionStage.RouteMaps.openRoute
#check CommonActionStage.RouteMaps.openRoute_apply
#check CommonActionStage.RouteMaps.openRoute_sq_apply
#check CommonActionStage.RouteMaps.ofArithmeticRepresentation
#check CommonActionStage.RouteMaps.selmerAction_routeSquared_eq_closed
#check CommonActionStage.reflectionCycleCorner
#check CommonActionStage.reflectionCycleCorner_eq
#check CommonActionStage.StrictReflectionCycleReceipt
#check CommonActionStage.StrictReflectionCycleReceiptTarget
#check CommonActionStage.baseCornerProjection
#check CommonActionStage.stickelbergerCorner
#check CommonActionStage.stickelbergerCorner_val
#check CommonActionStage.cornerCoefficient_smul_eq
#check CommonActionStage.CornerConversionReceipt
#check CommonActionStage.cornerConversionReceipt
#check CommonActionStage.cornerConversionReceipt_beta
#check CommonActionStage.classProjection_cornerCoefficient_smul_eq_zero
#check CommonActionStage.StateConversionCompatibility
#check CommonActionStage.StateConversionCompatibility.conversionReceipt_beta_eq_state_beta
#check CommonActionStage.GuardedPairedCarrier.pairedCornerConversionReceipts
#check CommonActionStage.AllocatedClass
#check CommonActionStage.classSwap
#check CommonActionStage.sevenDClassOperator
#check CommonActionStage.classCornerIdempotent
#check CommonActionStage.ClassActionCorner
#check CommonActionStage.sevenDClassCornerElement
#check CommonActionStage.differenceGauge
#check CommonActionStage.sevenDClassShadowReceipt
#check CommonActionStage.allocatedRootSource
#check CommonActionStage.allocatedRootState
#check CommonActionStage.allocatedRootState_receipts
#check CommonActionStage.allocatedRootState_class
#check CommonActionStage.allocatedRootState_source_eq
#check CommonActionStage.allocatedClassObstruction
#check CommonActionStage.allocatedSevenDClassReceipt
#check CommonActionStage.allocatedSevenDReceiptedRootState
#check CommonActionStage.allocatedSevenDReceiptedRootState_receipt
#check CommonActionStage.allocatedSevenDClassReceipt_payload
#check CommonActionStage.allocatedRootClassPTorsion
#check CommonActionStage.CharacterClassAllocation
#check CommonActionStage.allocatedCharacterClassObstruction
#check CommonActionStage.allocatedSelmerObstruction
#check CommonActionStage.classProjection_allocatedSelmerObstruction
#check CommonActionStage.Outcome.UnitIdealResult
#check CommonActionStage.Outcome.unitIdealResult
#check CommonActionStage.Outcome.SurvivingChannelResult
#check CommonActionStage.Outcome.WallAddress
#check CommonActionStage.Outcome.LocalizedWall
#check CommonActionStage.Outcome.TypedResult
#check CommonActionStage.Outcome.PolynomialTypedResult
#check CommonActionStage.reflectedSelmerRhoWall
#check CommonActionStage.reflectedSelmerRhoWall_target

/-! ## Proof-value wiring -/

/-! ### Vendored PowerRoot generator wiring -/

#guard_depends_on PowerRoot.Factorization.isMulTorsionFree,
  MulEquiv.toMonoidHom
#guard_depends_on PowerRoot.mem_powerSubgroup,
  powMonoidHom_apply
#guard_depends_on PowerRoot.mapOnPowerQuotients_mk,
  PowerRoot.mapOnPowerQuotients
#guard_depends_on PowerRoot.Factorization.mem_powerSubgroup_iff,
  Int.ediv_mul_cancel
#guard_depends_on PowerRoot.Factorization.mk_mem_divisibleClasses_iff,
  PowerRoot.Factorization.mem_powerSubgroup_iff
#guard_depends_on PowerRoot.Factorization.mem_divisibleElements_iff,
  PowerRoot.Factorization.mem_powerSubgroup_iff
#guard_depends_on PowerRoot.toDivisibleClasses_apply,
  PowerRoot.toDivisibleClasses
#guard_depends_on PowerRoot.toDivisibleClasses_surjective,
  QuotientGroup.out_eq'
#guard_depends_on PowerRoot.exists_root,
  PowerRoot.mem_powerSubgroup
#guard_depends_on PowerRoot.root_power,
  PowerRoot.Factorization.mem_powerSubgroup_iff
#guard_depends_on PowerRoot.root_eq_of_pow_eq,
  PowerRoot.root_power
#guard_depends_on PowerRoot.root_one,
  PowerRoot.root_eq_of_pow_eq
#guard_depends_on PowerRoot.root_mul,
  PowerRoot.root_eq_of_pow_eq
#guard_depends_on PowerRoot.coe_shift,
  PowerRoot.shift
#guard_depends_on PowerRoot.root_shift,
  PowerRoot.root_eq_of_pow_eq
#guard_depends_on PowerRoot.rootHom_apply,
  PowerRoot.rootHom
#guard_depends_on PowerRoot.fromKernel_mk,
  PowerRoot.fromKernel
#guard_depends_on PowerRoot.fromKernel_injective,
  PowerRoot.Factorization.isMulTorsionFree
#guard_depends_on PowerRoot.obstruction_toDivisibleClasses,
  PowerRoot.obstruction
#guard_depends_on PowerRoot.obstruction_ker,
  PowerRoot.obstruction_toDivisibleClasses
#guard_depends_on PowerRoot.obstruction_range,
  PowerRoot.obstruction_toDivisibleClasses

/-! ### Principal-ideal unsplit extension wiring -/

#guard_depends_on PowerRootExactSequence.unitReceipt_injective,
  PowerRootExactSequence.principalIdealExtensionClass
#guard_depends_on PowerRootExactSequence.componentShadow_ker,
  PowerRootExactSequence.principalIdealExtensionClass
#guard_depends_on PowerRootExactSequence.componentShadow_surjective,
  PowerRootExactSequence.principalIdealExtensionClass
#guard_depends_on PowerRootExactSequence.componentShadow_unitReceipt,
  PowerRootExactSequence.componentShadow_ker

/-! ### PowerRoot naturality wiring -/

#guard_depends_on PowerRootNaturality.ArrowMorphism.ext,
  PowerRootNaturality.ArrowMorphism.rec
#guard_depends_on PowerRootNaturality.ArrowMorphism.identity_sourceMap_apply,
  PowerRootNaturality.ArrowMorphism.identity
#guard_depends_on PowerRootNaturality.ArrowMorphism.identity_targetMap_apply,
  PowerRootNaturality.ArrowMorphism.identity
#guard_depends_on PowerRootNaturality.ArrowMorphism.comp_sourceMap_apply,
  PowerRootNaturality.ArrowMorphism.comp
#guard_depends_on PowerRootNaturality.ArrowMorphism.comp_targetMap_apply,
  PowerRootNaturality.ArrowMorphism.comp
#guard_depends_on PowerRootNaturality.ArrowMorphism.one_sourceMap_apply,
  PowerRootNaturality.ArrowMorphism.identity
#guard_depends_on PowerRootNaturality.ArrowMorphism.one_targetMap_apply,
  PowerRootNaturality.ArrowMorphism.identity
#guard_depends_on PowerRootNaturality.ArrowMorphism.mul_sourceMap_apply,
  PowerRootNaturality.ArrowMorphism.endomorphismMonoid
#guard_depends_on PowerRootNaturality.ArrowMorphism.mul_targetMap_apply,
  PowerRootNaturality.ArrowMorphism.endomorphismMonoid
#guard_depends_on PowerRootNaturality.ArrowMorphism.mul_eq_comp,
  PowerRootNaturality.ArrowMorphism.comp
#guard_depends_on PowerRootNaturality.ArrowMorphism.mapOnPowerQuotients_natural,
  PowerRootNaturality.ArrowMorphism.preserves_arrow
#guard_depends_on PowerRootNaturality.ArrowMorphism.mapDivisibleElements_apply,
  PowerRootNaturality.ArrowMorphism.mapDivisibleElements
#guard_depends_on PowerRootNaturality.ArrowMorphism.mapDivisibleClasses_apply_coe,
  PowerRootNaturality.ArrowMorphism.mapDivisibleClasses
#guard_depends_on
  PowerRootNaturality.ArrowMorphism.mapDivisibleClasses_toDivisibleClasses,
  PowerRootNaturality.ArrowMorphism.mapDivisibleClasses
#guard_depends_on PowerRootNaturality.ArrowMorphism.mapCokernel_mk,
  PowerRootNaturality.ArrowMorphism.mapCokernel
#guard_depends_on PowerRootNaturality.ArrowMorphism.root_natural,
  PowerRoot.root_eq_of_pow_eq
#guard_depends_on PowerRootNaturality.ArrowMorphism.root_mul_natural,
  PowerRoot.root_mul
#guard_depends_on PowerRootNaturality.ArrowMorphism.mapDivisibleElements_shift,
  map_pow
#guard_depends_on PowerRootNaturality.ArrowMorphism.root_shift_natural,
  PowerRoot.root_shift
#guard_depends_on PowerRootNaturality.ArrowMorphism.obstruction_natural,
  PowerRoot.obstruction_toDivisibleClasses
#guard_depends_on PowerRootNaturality.GroupRingEquivariance.arrowMorphism_one,
  PowerRootNaturality.ArrowMorphism.ext
#guard_depends_on PowerRootNaturality.GroupRingEquivariance.arrowMorphism_mul,
  PowerRootNaturality.ArrowMorphism.ext
#guard_depends_on PowerRootNaturality.GroupRingEquivariance.action_apply,
  PowerRootNaturality.GroupRingEquivariance.action
#guard_depends_on PowerRootNaturality.GroupRingEquivariance.root_equivariant,
  PowerRootNaturality.ArrowMorphism.root_natural
#guard_depends_on PowerRootNaturality.GroupRingEquivariance.obstruction_equivariant,
  PowerRootNaturality.ArrowMorphism.obstruction_natural
#guard_depends_on PowerRootNaturality.ReflectionInterface.root_reflection,
  PowerRootNaturality.ArrowMorphism.root_natural
#guard_depends_on PowerRootNaturality.ReflectionInterface.obstruction_reflection,
  PowerRootNaturality.ArrowMorphism.obstruction_natural
#guard_depends_on PowerRootNaturality.LocalizationInterface.obstruction_square,
  PowerRootNaturality.ArrowMorphism.obstruction_natural
#guard_depends_on
  PowerRootNaturality.LocalizationInterface.powerRootObstructionSquareLaw,
  PowerRootNaturality.LocalizationInterface.obstruction_square

#guard_depends_on InvolutiveBase.hash_hash,
  InvolutiveBase.hashHom_comp_self
#guard_depends_on InvolutiveBase.reflection_conservation_law,
  InvolutiveBase.reflectionPairing
#guard_depends_on InvolutiveBase.characterIdempotent_isIdempotent,
  InvolutiveBase.groupAverage_isIdempotent
#guard_depends_on InvolutiveBase.groupElement_mul_characterIdempotent,
  InvolutiveBase.characterIdempotent
#guard_depends_on InvolutiveBase.hash_characterIdempotent,
  InvolutiveBase.reflectedCharacter
#guard_depends_on InvolutiveBase.hash_trivialCharacterIdempotent,
  InvolutiveBase.hash_characterIdempotent
#guard_depends_on InvolutiveBase.plus_minus_projectors_exchanged,
  InvolutiveBase.hash_conjugationElement

#guard_depends_on RouteAlgebra.closedRoute_central,
  RouteAlgebra.phi_sq
#guard_depends_on RouteAlgebra.closedRoute_ne_one,
  SkewPolynomial.coeff_monomial
#guard_depends_on RouteAlgebra.routeCorner_coeff_odd_eq_zero,
  RouteAlgebra.odd_smul
#guard_depends_on RouteAlgebra.cornerPolynomialMap_surjective,
  RouteAlgebra.routeCorner_coeff_odd_eq_zero
#guard_depends_on RouteAlgebra.cornerPolynomialEquiv,
  RouteAlgebra.cornerPolynomialMap_surjective
#guard_depends_on RouteAlgebra.cornerPolynomialEquiv_X,
  RouteAlgebra.cornerPolynomialMap
#guard_depends_on RouteAlgebra.characterCornerPolynomialEquiv,
  RouteAlgebra.cornerPolynomialEquiv
#guard_depends_on RouteAlgebra.characterCornerPolynomialEquiv,
  InvolutiveBase.hash_characterIdempotent

#guard_depends_on SwapQuotient.quotientMap_closedRoute,
  TwoSidedIdeal.subset_span
#guard_depends_on SwapQuotient.sevenARelationWord_image,
  SwapQuotient.quotientMap
#guard_depends_on SwapQuotient.sevenDRelationWord_image,
  SwapQuotient.quotientMap
#guard_depends_on SwapQuotient.generator_sq,
  SwapQuotient.quotientMap_closedRoute
#guard_depends_on SwapQuotient.piCommon_idempotent,
  SwapQuotient.generator_sq
#guard_depends_on SwapQuotient.piDifference_idempotent,
  SwapQuotient.generator_sq
#guard_depends_on SwapQuotient.piCommon_piDifference_orthogonal,
  SwapQuotient.generator_sq
#guard_depends_on SwapQuotient.sevenARelationWord_eigenspace,
  SwapQuotient.sevenARelationWord_image
#guard_depends_on SwapQuotient.sevenARelationWord_eigenspace,
  SwapQuotient.generator_sq
#guard_depends_on SwapQuotient.sevenARelationWord_eigenspace,
  SwapQuotient.coefficientHalf_add_self
#guard_depends_on SwapQuotient.sevenDRelationWord_eigenspace,
  SwapQuotient.sevenDRelationWord_image
#guard_depends_on SwapQuotient.sevenDRelationWord_eigenspace,
  SwapQuotient.generator_sq
#guard_depends_on SwapQuotient.sevenDRelationWord_eigenspace,
  SwapQuotient.coefficientHalf_add_self
#guard_depends_on SwapQuotient.flowElement_two,
  SwapQuotient.flowElement
#guard_depends_on SwapQuotient.commonDifference_swap,
  SwapQuotient.swapLinear
#guard_depends_on SwapQuotient.commonProjector_formula,
  SwapQuotient.commonProjector
#guard_depends_on SwapQuotient.differenceProjector_formula,
  SwapQuotient.differenceProjector
#guard_depends_on SwapQuotient.sevenARelationOperator_apply,
  SwapQuotient.swapLinear
#guard_depends_on SwapQuotient.sevenDRelationOperator_apply,
  SwapQuotient.swapLinear
#guard_depends_on SwapQuotient.flowOperator_apply,
  Interaction.TwoAccount.step
#guard_depends_on SwapQuotient.flowOperator_two,
  Interaction.TwoAccount.step_two_eq_swap

#guard_depends_on
  TransverseAnnihilator.eq_zero_of_cycle_and_transverse_gcd_eq_one,
  TransverseAnnihilator.CornerService.eq_zero_of_annihilates_of_bezout
#guard_depends_on
  TransverseAnnihilator.CornerService.eq_zero_in_idempotentCorner,
  TransverseAnnihilator.CornerService.eq_zero_of_annihilates_of_bezout
#guard_depends_on
  TransverseAnnihilator.eq_zero_of_cycle_and_transverse_gcd_eq_one,
  TransverseAnnihilator.breaksCycle_iff_polynomialGCD_eq_one
#guard_depends_on
  TransverseAnnihilator.polynomial_livelockCarrier_subsingleton_iff,
  TransverseAnnihilator.CornerService.livelockCarrier_subsingleton_iff

#guard_depends_on
  LinkingInterfaces.sharp_trivialProjector_eq_omegaProjector,
  InvolutiveBase.hash_trivialCharacterIdempotent
#guard_depends_on
  LinkingInterfaces.FilteredStickelbergerCarrier.smul_mem_unitRange,
  LinkingInterfaces.FilteredStickelbergerCarrier.stickelberger_conversion
#guard_depends_on
  LinkingInterfaces.FilteredStickelbergerCarrier.classProjection_smul_eq_zero,
  LinkingInterfaces.FilteredStickelbergerCarrier.exact_at_carrier
#guard_depends_on
  LinkingInterfaces.FilteredStickelbergerCarrier.conversionReceipt,
  ClassCarrier.PrincipalizationReceipt.mk
#guard_depends_on
  LinkingInterfaces.FilteredStickelbergerCarrier.conversionReceipt_source_eq,
  ClassCarrier.PrincipalizationReceipt.source_eq
#guard_depends_on
  LinkingInterfaces.ArithmeticRepresentation.rho_preserves_principal_arrow,
  PowerRootNaturality.ArrowMorphism.preserves_arrow
#guard_depends_on
  LinkingInterfaces.ArithmeticRepresentation.rho_root_square,
  PowerRootNaturality.ArrowMorphism.root_natural
#guard_depends_on
  LinkingInterfaces.ArithmeticRepresentation.rho_powerRoot_square,
  PowerRootNaturality.ArrowMorphism.obstruction_natural
#guard_depends_on
  LinkingInterfaces.ArithmeticRepresentation.selmerAction_routeSquared,
  LinkingInterfaces.ArithmeticRepresentation.selmerAction_route
#guard_depends_on
  LinkingInterfaces.StrictRouteArithmeticRepresentation.selmerAction_closedRoute,
  LinkingInterfaces.ArithmeticRepresentation.selmerAction_routeSquared

/-! ## Tate pairing proof-value wiring -/

#guard_depends_on TatePairing.character_mul_reflectedCharacter,
  InvolutiveBase.reflectedCharacter
#guard_depends_on
  TatePairing.PlaceIndexedLocalPairing.pairAt_smul_adjoint,
  TatePairing.PlaceIndexedLocalPairing.adjoint_law
#guard_depends_on
  TatePairing.PlaceIndexedLocalPairing.pairAt_hash_smul_adjoint,
  TatePairing.PlaceIndexedLocalPairing.pairAt_smul_adjoint
#guard_depends_on
  TatePairing.PlaceIndexedLocalPairing.pairAt_hash_smul_adjoint,
  InvolutiveBase.hash_hash
#guard_depends_on TatePairing.PlaceIndexedLocalPairing.finite_support,
  TatePairing.PlaceIndexedLocalPairing.pairAt
#guard_depends_on TatePairing.PlaceLedger.toLedger_stock,
  TatePairing.PlaceLedger.toLedger
#guard_depends_on TatePairing.PlaceLedger.toLedger_credit,
  TatePairing.PlaceLedger.toLedger
#guard_depends_on TatePairing.PlaceLedger.toLedger_converted,
  TatePairing.PlaceLedger.toLedger
#guard_depends_on TatePairing.PlaceLedger.toLedger_total,
  TatePairing.PlaceLedger.toLedger
#guard_depends_on TatePairing.PlaceLedger.toVacuumTransfer,
  Fermat.Conservation.Ledger.conservation_identity
#guard_depends_on TatePairing.PlaceLedger.toVacuumTransfer_before,
  TatePairing.PlaceLedger.toVacuumTransfer
#guard_depends_on TatePairing.PlaceLedger.toVacuumTransfer_after,
  TatePairing.PlaceLedger.toVacuumTransfer
#guard_depends_on TatePairing.PlaceLedger.toVacuumTransfer_spent,
  TatePairing.PlaceLedger.toVacuumTransfer
#guard_depends_on TatePairing.PlaceLedger.toVacuumTransfer_L1,
  IsoConserveBridge.transfer_L1_conservation
#guard_depends_on TatePairing.GlobalReciprocityLaw.placeLedger,
  TatePairing.PlaceLedger.mk
#guard_depends_on
  TatePairing.GlobalReciprocityLaw.ledger_conservation_identity,
  Fermat.Conservation.Ledger.conservation_identity
#guard_depends_on TatePairing.GlobalReciprocityLaw.reciprocityTransfer,
  TatePairing.PlaceLedger.toVacuumTransfer
#guard_depends_on
  TatePairing.GlobalReciprocityLaw.reciprocity_L1_conservation,
  IsoConserveBridge.transfer_L1_conservation
#guard_depends_on
  TatePairing.GlobalReciprocityLaw.pairAt_eq_zero_of_other_places,
  TatePairing.PlaceIndexedLocalPairing.pairAt
#guard_depends_on TatePairing.LocalOrthogonalityGuard.pairAt_eq_zero,
  TatePairing.LocalOrthogonalityGuard.orthogonal

/-! ## Explicit tame Hilbert-symbol proof-value wiring -/

#guard_depends_on TameSymbol.Context.raw_one_left,
  TameSymbol.Context.raw
#guard_depends_on TameSymbol.Context.raw_one_right,
  TameSymbol.Context.raw
#guard_depends_on TameSymbol.Context.raw_mul_left,
  TameSymbol.Context.raw
#guard_depends_on TameSymbol.Context.raw_mul_right,
  TameSymbol.Context.raw
#guard_depends_on TameSymbol.Context.raw_swap,
  TameSymbol.Context.raw
#guard_depends_on TameSymbol.Context.residue_power_pow_eq_one,
  FiniteField.pow_card_sub_one_eq_one
#guard_depends_on TameSymbol.Context.residueCharacter_one,
  TameSymbol.Context.residueCharacter
#guard_depends_on TameSymbol.Context.residueCharacter_mul,
  TameSymbol.Context.residueCharacter
#guard_depends_on TameSymbol.Context.value_eq_explicit_formula,
  TameSymbol.Context.value
#guard_depends_on TameSymbol.Context.value_one_left,
  TameSymbol.Context.value
#guard_depends_on TameSymbol.Context.value_one_right,
  TameSymbol.Context.value
#guard_depends_on TameSymbol.Context.value_mul_left,
  TameSymbol.Context.raw_mul_left
#guard_depends_on TameSymbol.Context.value_mul_right,
  TameSymbol.Context.raw_mul_right
#guard_depends_on TameSymbol.Context.value_swap,
  TameSymbol.Context.raw_swap
#guard_depends_on TameSymbol.Context.toAddMonoidHom_apply,
  TameSymbol.Context.toAddMonoidHom
#guard_depends_on TameSymbol.Context.toAddMonoidHomDualFirst_apply,
  TameSymbol.Context.toAddMonoidHomDualFirst
#guard_depends_on TameSymbol.Context.raw_eq_one_of_ord_eq_zero,
  TameSymbol.Context.raw
#guard_depends_on TameSymbol.Context.both_units_silence,
  TameSymbol.Context.raw_eq_one_of_ord_eq_zero
#guard_depends_on TameSymbol.Context.value_eq_zero_of_ord_eq_zero,
  TameSymbol.Context.both_units_silence
#guard_depends_on TameSymbol.Context.raw_eq_pth_power_of_p_dvd_ord,
  TameSymbol.Context.raw
#guard_depends_on TameSymbol.Context.value_eq_zero_of_p_dvd_ord,
  TameSymbol.Context.raw_eq_pth_power_of_p_dvd_ord
#guard_depends_on TameSymbol.Context.value_pow_left,
  TameSymbol.Context.toAddMonoidHom
#guard_depends_on TameSymbol.Context.value_pow_right,
  TameSymbol.Context.toAddMonoidHom
#guard_depends_on TameSymbol.Context.value_pth_power_left,
  TameSymbol.Context.value_pow_left
#guard_depends_on TameSymbol.Context.value_pth_power_right,
  TameSymbol.Context.value_pow_right
#guard_depends_on TameSymbol.Context.ordModP_mk,
  TameSymbol.Context.ordModP
#guard_depends_on TameSymbol.Context.rightModP_mk,
  QuotientGroup.lift_mk'
#guard_depends_on TameSymbol.Context.modP_mk_mk,
  TameSymbol.Context.modP
#guard_depends_on TameSymbol.Context.modP_eq_zero_of_ordModP_eq_zero,
  TameSymbol.Context.value_eq_zero_of_p_dvd_ord
#guard_depends_on TameSymbol.Context.SteinbergValuationCases.raw_eq_one,
  TameSymbol.Context.raw_eq_one_of_ord_eq_zero
#guard_depends_on TameSymbol.Context.SteinbergValuationCases.steinberg_of_cases,
  TameSymbol.Context.SteinbergValuationCases.raw_eq_one
#guard_depends_on TameSymbol.Context.steinberg,
  TameSymbol.Context.SteinbergValuationCases.steinberg_of_cases
#guard_depends_on TameSymbol.Context.PlaceGaloisData.raw_place_action,
  TameSymbol.Context.raw
#guard_depends_on
  TameSymbol.Context.PlaceGaloisData.value_place_galois_equivariant,
  TameSymbol.Context.PlaceGaloisData.raw_place_action
#guard_depends_on TameSymbol.Context.GaloisData.raw_action,
  TameSymbol.Context.raw
#guard_depends_on TameSymbol.Context.GaloisData.value_galois_equivariant,
  TameSymbol.Context.GaloisData.raw_action
#guard_depends_on TameSymbol.Context.GaloisData.value_action_adjoint,
  TameSymbol.Context.GaloisData.value_galois_equivariant
#guard_depends_on TameSymbol.Context.GaloisData.value_action_adjoint,
  TameSymbol.Context.value_pow_right

/-! ## Seated Selmer-eigenspace proof-value wiring -/

#guard_depends_on SelmerEigenspace.selmerCarrier_eq_commonActionStage,
  Eq.refl
#guard_depends_on SelmerEigenspace.p_nsmul_eq_zero,
  QuotientGroup.eq_one_iff
#guard_depends_on SelmerEigenspace.padicInt_smul_eq_toZMod_smul,
  PadicInt.toZMod
#guard_depends_on SelmerEigenspace.mem_characterEigenspace_iff,
  SelmerEigenspace.characterEigenspace
#guard_depends_on SelmerEigenspace.coe_groupElement_smul,
  Representation.asAlgebraHom_of
#guard_depends_on SelmerEigenspace.toSeatedCarrier_apply,
  SelmerEigenspace.toSeatedCarrier
#guard_depends_on SelmerEigenspace.toAdditiveSelmer_apply,
  SelmerEigenspace.toAdditiveSelmer
#guard_depends_on SelmerEigenspace.toConcreteSelmer_apply,
  SelmerEigenspace.toConcreteSelmer
#guard_depends_on SelmerEigenspace.toKummerQuotient_apply,
  SelmerEigenspace.toKummerQuotient
#guard_depends_on SelmerEigenspace.toKummerClass_apply,
  SelmerEigenspace.toKummerClass
#guard_depends_on SelmerEigenspace.toAdditiveSelmer_injective,
  Subtype.ext
#guard_depends_on SelmerEigenspace.toConcreteSelmer_injective,
  SelmerEigenspace.toAdditiveSelmer_injective
#guard_depends_on SelmerEigenspace.toKummerQuotient_injective,
  SelmerEigenspace.toConcreteSelmer_injective
#guard_depends_on SelmerEigenspace.valuationOfNeZeroMod_eq_one,
  SelmerEigenspace.toConcreteSelmer
#guard_depends_on SelmerEigenspace.valuationOfNeZeroMod_mk_eq_one_iff_dvd,
  ZMod.intCast_zmod_eq_zero_iff_dvd
#guard_depends_on SelmerEigenspace.representative_valuation_dvd,
  SelmerEigenspace.valuationOfNeZeroMod_mk_eq_one_iff_dvd
#guard_depends_on SelmerEigenspace.representative_valuation_dvd,
  SelmerEigenspace.valuationOfNeZeroMod_eq_one
#guard_depends_on SelmerEigenspace.quotientRepresentative_mk,
  QuotientGroup.out_eq'
#guard_depends_on SelmerEigenspace.quotientRepresentative_valuation_dvd,
  SelmerEigenspace.representative_valuation_dvd
#guard_depends_on SelmerEigenspace.exists_representative_valuation_dvd,
  SelmerEigenspace.quotientRepresentative_valuation_dvd
#guard_depends_on
  SelmerEigenspace.ReflectedDualCharacterGlue.carrierDualEquiv_smul,
  SelmerEigenspace.ReflectedDualCharacterGlue.omegaTwistedAction

/-! ### Arbitrary-support Selmer-eigenspace proof-value wiring -/

#guard_depends_on SelmerEigenspace.mem_characterEigenspaceAt_iff,
  SelmerEigenspace.characterEigenspaceAt
#guard_depends_on
  SelmerEigenspace.characterIdempotent_action_mem_characterEigenspaceAt,
  InvolutiveBase.groupElement_mul_characterIdempotent
#guard_depends_on SelmerEigenspace.characterProjectorAt,
  SelmerEigenspace.characterIdempotent_action_mem_characterEigenspaceAt
#guard_depends_on SelmerEigenspace.characterProjectorAt_apply,
  SelmerEigenspace.characterProjectorAt
#guard_depends_on SelmerEigenspace.characterProjectorAt_idempotent,
  InvolutiveBase.characterIdempotent_isIdempotent
#guard_depends_on SelmerEigenspace.characterEigenspaceRepresentationAt,
  SelmerEigenspace.mem_characterEigenspaceAt_iff
#guard_depends_on SelmerEigenspace.toKummerClassAt_apply,
  SelmerEigenspace.toKummerClassAt
#guard_depends_on SelmerEigenspace.quotientRepresentativeAt_mk,
  QuotientGroup.out_eq'
#guard_depends_on SelmerEigenspace.valuationOfNeZeroMod_eq_one_of_not_mem,
  SelmerEigenspace.toConcreteSelmerAt
#guard_depends_on
  SelmerEigenspace.quotientRepresentativeAt_valuation_dvd_of_not_mem,
  SelmerEigenspace.valuationOfNeZeroMod_eq_one_of_not_mem
#guard_depends_on SelmerEigenspace.supportValuation_apply,
  SelmerEigenspace.supportValuation
#guard_depends_on
  SelmerEigenspace.supportValuation_emptySupportInclusion_eq_zero,
  SelmerEigenspace.emptySupportInclusion
#guard_depends_on
  SelmerEigenspace.supportValuation_ker_eq_range_emptySupportInclusion,
  SelmerEigenspace.supportValuation_emptySupportInclusion_eq_zero
#guard_depends_on SelmerEigenspace.eigenspaceSupportValuation_apply,
  SelmerEigenspace.eigenspaceSupportValuation

/-! ## Tame place-indexed realization proof-value wiring -/

#guard_depends_on
  TamePlacePairing.PlaceIndexedTameRealization.pairAt_eq_zero_of_p_dvd_ord,
  TameSymbol.Context.modP_eq_zero_of_ordModP_eq_zero
#guard_depends_on
  TamePlacePairing.PlaceIndexedTameRealization.OutsideTwoTameBookkeeping.outside_two_readings_at_tame_places,
  TamePlacePairing.PlaceIndexedTameRealization.pairAt_eq_zero_of_p_dvd_ord
#guard_depends_on
  TamePlacePairing.PlaceIndexedTameRealization.OutsideTwoTameBookkeeping.outside_two_readings_of_tame_and_residual,
  TamePlacePairing.PlaceIndexedTameRealization.OutsideTwoTameBookkeeping.outside_two_readings_at_tame_places
#guard_depends_on TamePlacePairing.WildLocalInterface.pairAt_distinguished,
  TamePlacePairing.WildLocalInterface.toPlaceIndexedLocalPairing
#guard_depends_on TamePlacePairing.WildLocalInterface.pairAt_eq_zero_of_ne,
  TamePlacePairing.WildLocalInterface.toPlaceIndexedLocalPairing
#guard_depends_on
  TamePlacePairing.Seated.ordModP_toKummerClass_eq_zero_of_ord_eq_valuation,
  SelmerEigenspace.quotientRepresentative_valuation_dvd
#guard_depends_on
  TamePlacePairing.Seated.ordModP_toKummerClass_eq_zero_of_ord_eq_valuation,
  TameSymbol.Context.ordModP_mk
#guard_depends_on
  TamePlacePairing.Seated.Realization.toPlaceIndexedTameRealization_primalClass,
  TamePlacePairing.Seated.Realization.toPlaceIndexedTameRealization
#guard_depends_on
  TamePlacePairing.Seated.Realization.toPlaceIndexedTameRealization_dualClass,
  TamePlacePairing.Seated.Realization.toPlaceIndexedTameRealization
#guard_depends_on
  TamePlacePairing.Seated.Realization.ordModP_toKummerClass_eq_zero,
  TamePlacePairing.Seated.ordModP_toKummerClass_eq_zero_of_ord_eq_valuation
#guard_depends_on
  TamePlacePairing.Seated.Realization.pairAt_eq_zero_at_tame_place,
  TamePlacePairing.PlaceIndexedTameRealization.pairAt_eq_zero_of_p_dvd_ord
#guard_depends_on
  TamePlacePairing.Seated.Realization.pairAt_eq_zero_at_tame_place,
  TamePlacePairing.Seated.Realization.selectedValuationsZeroAt
#guard_depends_on
  TamePlacePairing.Seated.Realization.outside_two_readings_at_tame_places,
  TamePlacePairing.PlaceIndexedTameRealization.OutsideTwoTameBookkeeping.outside_two_readings_at_tame_places
#guard_depends_on
  TamePlacePairing.Seated.Realization.outside_two_readings_at_tame_places,
  TamePlacePairing.Seated.Realization.outsideTwoTameBookkeeping
#guard_depends_on
  TamePlacePairing.Seated.Realization.outside_two_readings_of_residual,
  TamePlacePairing.PlaceIndexedTameRealization.OutsideTwoTameBookkeeping.outside_two_readings_of_tame_and_residual
#guard_depends_on
  TamePlacePairing.Seated.Realization.outside_two_readings_of_residual,
  TamePlacePairing.Seated.Realization.outsideTwoTameBookkeeping

/-! ## Vendored finite-S Selmer proof-value wiring -/

#guard_depends_on IsDedekindDomain.selmerGroup.eq_divisibleClasses,
  PowerRoot.Factorization.mk_mem_divisibleClasses_iff
#guard_depends_on IsDedekindDomain.selmerGroup.principalDivisorAway_ker,
  IsDedekindDomain.selmerGroup.principalDivisorAway_apply
#guard_depends_on IsDedekindDomain.selmerGroup.fromSUnitLift_injective,
  PowerRoot.fromKernel_injective
#guard_depends_on IsDedekindDomain.selmerGroup.fromSIntegerUnitLift_injective,
  IsDedekindDomain.selmerGroup.fromSUnitLift_injective
#guard_depends_on IsDedekindDomain.selmerGroup.toSClass_ker,
  PowerRoot.obstruction_ker
#guard_depends_on IsDedekindDomain.selmerGroup.toSClass_ker,
  IsDedekindDomain.selmerGroup.toSClass
#guard_depends_on IsDedekindDomain.selmerGroup.toSClass_ker_integerUnits,
  IsDedekindDomain.selmerGroup.toSClass_ker
#guard_depends_on IsDedekindDomain.selmerGroup.toSClass_range,
  PowerRoot.obstruction_range
#guard_depends_on IsDedekindDomain.selmerGroup.toSClass_range,
  IsDedekindDomain.selmerGroup.toSClass
#guard_depends_on
  IsDedekindDomain.selmerGroup.fractionalIdealToDivisorAway_surjective,
  IsDedekindDomain.selmerGroup.fractionalIdealToDivisorAway_apply
#guard_depends_on
  IsDedekindDomain.selmerGroup.classGroupToObstructionTarget_surjective,
  IsDedekindDomain.selmerGroup.fractionalIdealToDivisorAway_surjective
#guard_depends_on
  IsDedekindDomain.selmerGroup.classGroupToObstructionTarget_primeClass,
  IsDedekindDomain.selmerGroup.classGroupToObstructionTarget_mk
#guard_depends_on
  IsDedekindDomain.selmerGroup.invertedPrimeClasses_eq_classesOfPrimesIn,
  IsDedekindDomain.selmerGroup.classGroupToObstructionTarget_primeClass
#guard_depends_on
  IsDedekindDomain.selmerGroup.obstructionTargetEquivSClassGroup,
  IsDedekindDomain.selmerGroup.invertedPrimeClasses_eq_classesOfPrimesIn
#guard_depends_on
  IsDedekindDomain.selmerGroup.obstructionTargetEquivSClassGroup,
  IsDedekindDomain.selmerGroup.classGroupToObstructionTarget_surjective
#guard_depends_on
  IsDedekindDomain.selmerGroup.classGroupToObstructionTarget_empty_injective,
  IsDedekindDomain.selmerGroup.classGroupToObstructionTarget_mk
#guard_depends_on
  IsDedekindDomain.selmerGroup.obstructionTargetEmptyEquivClassGroup,
  IsDedekindDomain.selmerGroup.classGroupToObstructionTarget_empty_injective
#guard_depends_on
  IsDedekindDomain.selmerGroup.obstructionTargetEmptyEquivClassGroup_toSClass,
  PowerRoot.obstruction_toDivisibleClasses
#guard_depends_on
  IsDedekindDomain.selmerGroup.obstructionTargetEmptyEquivClassGroup_comp_toSClass,
  IsDedekindDomain.selmerGroup.obstructionTargetEmptyEquivClassGroup_toSClass
#guard_depends_on
  IsDedekindDomain.selmerGroup.toSClass_empty_ker_eq_toClass_ker,
  IsDedekindDomain.selmerGroup.obstructionTargetEmptyEquivClassGroup_comp_toSClass
#guard_depends_on
  IsDedekindDomain.selmerGroup.map_toSClass_empty_range_eq_toClass_range,
  IsDedekindDomain.selmerGroup.obstructionTargetEmptyEquivClassGroup_comp_toSClass

/-! ## Common-action proof-value wiring -/

#guard_depends_on IsDedekindDomain.selmerGroup.toClass,
  PowerRoot.obstruction
#guard_depends_on IsDedekindDomain.selmerGroup.toClass_ker,
  PowerRoot.obstruction_ker
#guard_depends_on IsDedekindDomain.selmerGroup.toClass_ker,
  IsDedekindDomain.selmerGroup.toClass
#guard_depends_on IsDedekindDomain.selmerGroup.toClass_range,
  PowerRoot.obstruction_range
#guard_depends_on IsDedekindDomain.selmerGroup.toClass_range,
  IsDedekindDomain.selmerGroup.toClass
#guard_depends_on CommonActionStage.selmerClassProjection,
  IsDedekindDomain.selmerGroup.toClass
#guard_depends_on CommonActionStage.selmerClassProjection,
  IsDedekindDomain.selmerGroup.toClass_range
#guard_depends_on CommonActionStage.selmerClassSequenceRealization,
  CommonActionStage.selmerClassProjection
#guard_depends_on CommonActionStage.selmerClassSequenceRealization,
  IsDedekindDomain.selmerGroup.toClass_ker
#guard_depends_on CommonActionStage.selmerClassSequenceRealization,
  IsDedekindDomain.selmerGroup.toClass_range
#guard_depends_on CommonActionStage.WithheldSelmerClassSequenceRealization,
  CommonActionStage.selmerClassSequenceRealization

#guard_depends_on CommonActionStage.unitInclusion_injective,
  IsDedekindDomain.selmerGroup.fromUnitLift_injective
#guard_depends_on CommonActionStage.realUnitInclusion,
  CommonActionStage.realUnitClass
#guard_depends_on CommonActionStage.realUnitInclusion,
  CommonActionStage.unitInclusion
#guard_depends_on CommonActionStage.ExactFilteredPair.unitInclusion_injective,
  CommonActionStage.ExactFilteredLeg.unitInclusion_injective
#guard_depends_on CommonActionStage.ExactFilteredPair.exact_at_carrier,
  CommonActionStage.ExactFilteredLeg.exact_at_carrier
#guard_depends_on CommonActionStage.ExactFilteredPair.classProjection_surjective,
  CommonActionStage.ExactFilteredLeg.classProjection_surjective
#guard_depends_on CommonActionStage.ExactFilteredPair.classProjection_liftClassPair,
  CommonActionStage.ExactFilteredPair.classProjection_surjective
#guard_depends_on CommonActionStage.ExactFilteredPair.antitone_filtration,
  CommonActionStage.ExactFilteredLeg.antitone_filtration
#guard_depends_on CommonActionStage.ExactFilteredPair.class_p_torsion,
  CommonActionStage.ExactFilteredLeg.class_p_torsion
#guard_depends_on CommonActionStage.IntegralReflectionInput.sharpTransport,
  LinkingInterfaces.IntegralStickelbergerIdeal.SharpTransformationGuard.sharp_image_eq_omega_reflected
#guard_depends_on CommonActionStage.IntegralReflectionInput.sharpTransport,
  Ideal.mem_map_of_mem
#guard_depends_on CommonActionStage.IntegralReflectionInput.sharpTransport_coe,
  CommonActionStage.IntegralReflectionInput.sharpTransport
#guard_depends_on CommonActionStage.GuardedPairedCarrier.exactPair,
  CommonActionStage.exactLegOfFilteredStickelbergerCarrier
#guard_depends_on CommonActionStage.GuardedPairedCarrier.chiConversionReceipt,
  LinkingInterfaces.FilteredStickelbergerCarrier.conversionReceipt
#guard_depends_on
  CommonActionStage.GuardedPairedCarrier.reflectedDualConversionReceipt,
  LinkingInterfaces.FilteredStickelbergerCarrier.conversionReceipt
#guard_depends_on CommonActionStage.GuardedPairedCarrier.pairedConversionReceipts,
  CommonActionStage.IntegralReflectionInput.sharpTransport
#guard_depends_on CommonActionStage.GuardedPairedCarrier.pairedConversionReceipts,
  LinkingInterfaces.FilteredStickelbergerCarrier.conversionReceipt
#guard_depends_on CommonActionStage.lambdaAction_apply,
  CommonActionStage.lambdaAction
#guard_depends_on CommonActionStage.deltaAction,
  CommonActionStage.lambdaAction
#guard_depends_on CommonActionStage.deltaAction_apply,
  CommonActionStage.deltaAction
#guard_depends_on CommonActionStage.RouteMaps.closedAtChi,
  LinearMap.comp
#guard_depends_on CommonActionStage.RouteMaps.closedAtReflected,
  LinearMap.comp
#guard_depends_on CommonActionStage.RouteMaps.openRoute_apply,
  CommonActionStage.RouteMaps.openRoute
#guard_depends_on CommonActionStage.RouteMaps.openRoute_sq_apply,
  CommonActionStage.RouteMaps.openRoute_apply
#guard_depends_on CommonActionStage.RouteMaps.ofArithmeticRepresentation,
  LinkingInterfaces.ArithmeticRepresentation.routeChiToReflected
#guard_depends_on CommonActionStage.RouteMaps.selmerAction_routeSquared_eq_closed,
  LinkingInterfaces.ArithmeticRepresentation.selmerAction_routeSquared
#guard_depends_on CommonActionStage.reflectionCycleCorner_eq,
  CommonActionStage.reflectionCycleCorner
#guard_depends_on CommonActionStage.reflectionCycleCorner_eq,
  TransverseAnnihilator.cyclePolynomial
#guard_depends_on CommonActionStage.stickelbergerCorner,
  CommonActionStage.baseCornerProjection
#guard_depends_on CommonActionStage.stickelbergerCorner_val,
  CommonActionStage.stickelbergerCorner
#guard_depends_on CommonActionStage.cornerCoefficient_smul_eq,
  smul_comm
#guard_depends_on CommonActionStage.cornerConversionReceipt,
  LinkingInterfaces.FilteredStickelbergerCarrier.stickelberger_conversion
#guard_depends_on CommonActionStage.cornerConversionReceipt,
  LinkingInterfaces.FilteredStickelbergerCarrier.conversionReceipt
#guard_depends_on CommonActionStage.cornerConversionReceipt_beta,
  CommonActionStage.cornerConversionReceipt
#guard_depends_on
  CommonActionStage.classProjection_cornerCoefficient_smul_eq_zero,
  LinkingInterfaces.FilteredStickelbergerCarrier.classProjection_smul_eq_zero
#guard_depends_on CommonActionStage.sevenDClassOperator,
  CommonActionStage.classSwap
#guard_depends_on CommonActionStage.sevenDClassCornerElement,
  CommonActionStage.sevenDClassOperator
#guard_depends_on CommonActionStage.sevenDClassShadowReceipt,
  CommonActionStage.sevenDClassCornerElement
#guard_depends_on CommonActionStage.allocatedRootState,
  ClassCarrier.numberFieldBoundedRepresentative
#guard_depends_on CommonActionStage.allocatedRootState_receipts,
  CommonActionStage.allocatedRootState
#guard_depends_on CommonActionStage.allocatedRootState_class,
  ClassCarrier.idealClassProjection_eq_source_class
#guard_depends_on CommonActionStage.allocatedRootState_source_eq,
  ClassCarrier.State.source_eq_principal_mul_reduced
#guard_depends_on CommonActionStage.allocatedSevenDClassReceipt,
  CommonActionStage.sevenDClassShadowReceipt
#guard_depends_on CommonActionStage.allocatedSevenDReceiptedRootState,
  CommonActionStage.allocatedSevenDClassReceipt
#guard_depends_on CommonActionStage.allocatedSevenDReceiptedRootState_receipt,
  CommonActionStage.allocatedSevenDReceiptedRootState
#guard_depends_on CommonActionStage.allocatedSevenDClassReceipt_payload,
  CommonActionStage.allocatedSevenDClassReceipt
#guard_depends_on CommonActionStage.allocatedRootClassPTorsion,
  KummerDrain.AllocatedFactorLedger.rootClass_torsion
#guard_depends_on CommonActionStage.allocatedSelmerObstruction,
  CommonActionStage.ExactFilteredPair.liftClassPair
#guard_depends_on CommonActionStage.classProjection_allocatedSelmerObstruction,
  CommonActionStage.ExactFilteredPair.classProjection_liftClassPair
#guard_depends_on CommonActionStage.Outcome.unitIdealResult,
  TransverseAnnihilator.CornerService.eq_zero_of_annihilates_of_bezout
#guard_depends_on
  CommonActionStage.StateConversionCompatibility.conversionReceipt_beta_eq_state_beta,
  CommonActionStage.StateConversionCompatibility.beta_eq
#guard_depends_on
  CommonActionStage.GuardedPairedCarrier.pairedCornerConversionReceipts,
  CommonActionStage.IntegralReflectionInput.sharpTransport
#guard_depends_on
  CommonActionStage.GuardedPairedCarrier.pairedCornerConversionReceipts,
  CommonActionStage.cornerConversionReceipt
#guard_depends_on CommonActionStage.reflectedSelmerRhoWall_target,
  CommonActionStage.reflectedSelmerRhoWall

/-! ## Vendored and realized sequence axiom boundary -/

/--
info: 'IsDedekindDomain.selmerGroup.toClass' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.toClass

/--
info: 'IsDedekindDomain.selmerGroup.toClass_ker' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.toClass_ker

/--
info: 'IsDedekindDomain.selmerGroup.toClass_range' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.toClass_range

/--
info: 'IsDedekindDomain.selmerGroup.fractionalIdealFactorization_apply' depends on axioms: [propext,
 Classical.choice,
 Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.fractionalIdealFactorization_apply

/--
info: 'IsDedekindDomain.selmerGroup.fractionalIdealToDivisorAway_apply' depends on axioms: [propext,
 Classical.choice,
 Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.fractionalIdealToDivisorAway_apply

/--
info: 'IsDedekindDomain.selmerGroup.principalDivisorAway_apply' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.principalDivisorAway_apply

/--
info: 'IsDedekindDomain.selmerGroup.eq_divisibleClasses' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.eq_divisibleClasses

/--
info: 'IsDedekindDomain.selmerGroup.principalDivisorAway_ker' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.principalDivisorAway_ker

/--
info: 'IsDedekindDomain.selmerGroup.fromSUnitLift_injective' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.fromSUnitLift_injective

/--
info: 'IsDedekindDomain.selmerGroup.fromSIntegerUnitLift_injective' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.fromSIntegerUnitLift_injective

/--
info: 'IsDedekindDomain.selmerGroup.toSClass_ker' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.toSClass_ker

/--
info: 'IsDedekindDomain.selmerGroup.toSClass_ker_integerUnits' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.toSClass_ker_integerUnits

/--
info: 'IsDedekindDomain.selmerGroup.toSClass_range' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.toSClass_range

/--
info: 'IsDedekindDomain.selmerGroup.fractionalIdealToDivisorAway_surjective' depends on axioms: [propext,
 Classical.choice,
 Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.fractionalIdealToDivisorAway_surjective

/--
info: 'IsDedekindDomain.selmerGroup.classGroupToObstructionTarget_mk' depends on axioms: [propext,
 Classical.choice,
 Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.classGroupToObstructionTarget_mk

/--
info: 'IsDedekindDomain.selmerGroup.classGroupToObstructionTarget_surjective' depends on axioms: [propext,
 Classical.choice,
 Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.classGroupToObstructionTarget_surjective

/--
info: 'IsDedekindDomain.selmerGroup.classGroupToObstructionTarget_primeClass' depends on axioms: [propext,
 Classical.choice,
 Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.classGroupToObstructionTarget_primeClass

/--
info: 'IsDedekindDomain.selmerGroup.invertedPrimeClasses_eq_classesOfPrimesIn' depends on axioms: [propext,
 Classical.choice,
 Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.invertedPrimeClasses_eq_classesOfPrimesIn

/--
info: 'IsDedekindDomain.selmerGroup.classGroupToObstructionTarget_empty_injective' depends on axioms: [propext,
 Classical.choice,
 Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.classGroupToObstructionTarget_empty_injective

/--
info: 'IsDedekindDomain.selmerGroup.obstructionTargetEmptyEquivClassGroup_toSClass' depends on axioms: [propext,
 Classical.choice,
 Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.obstructionTargetEmptyEquivClassGroup_toSClass

/--
info: 'IsDedekindDomain.selmerGroup.obstructionTargetEmptyEquivClassGroup_comp_toSClass' depends on axioms: [propext,
 Classical.choice,
 Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.obstructionTargetEmptyEquivClassGroup_comp_toSClass

/--
info: 'IsDedekindDomain.selmerGroup.toSClass_empty_ker_eq_toClass_ker' depends on axioms: [propext,
 Classical.choice,
 Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.toSClass_empty_ker_eq_toClass_ker

/--
info: 'IsDedekindDomain.selmerGroup.map_toSClass_empty_range_eq_toClass_range' depends on axioms: [propext,
 Classical.choice,
 Quot.sound]
-/
#guard_msgs in
#print axioms IsDedekindDomain.selmerGroup.map_toSClass_empty_range_eq_toClass_range

/--
info: 'Fermat.Conservation.CommonActionStage.WithheldSelmerClassSequenceRealization' depends on axioms: [propext,
 Classical.choice,
 Quot.sound]
-/
#guard_msgs in
#print axioms CommonActionStage.WithheldSelmerClassSequenceRealization

/-! ## Exhaustive axiom boundary

Every declaration created below each W1--W5 namespace is inspected.  This is
exhaustive rather than a hand-maintained theorem sample, so newly added public
declarations are automatically audited as well. -/

open Lean Elab Command

/-- Fail if any declaration under a namespace prefix uses an axiom beyond
Lean's standard extensionality, choice, and quotient-soundness boundary. -/
elab "#guard_standard_axioms_prefix " p:ident : command => do
  let env ← getEnv
  let auditedPrefix := p.getId
  let allowed : Array Name :=
    #[``propext, ``Classical.choice, ``Quot.sound]
  let declarations :=
    env.constants.toList
      |>.map Prod.fst
      |>.filter auditedPrefix.isPrefixOf
  for declaration in declarations do
    let axioms ← Lean.collectAxioms declaration
    let unexpected := axioms.filter fun ax =>
      !allowed.contains ax
    unless unexpected.isEmpty do
      throwError
        "{declaration} depends on nonstandard axioms: {unexpected}"

#guard_standard_axioms_prefix Fermat.Conservation.InvolutiveBase
#guard_standard_axioms_prefix Fermat.Conservation.RouteAlgebra
#guard_standard_axioms_prefix Fermat.Conservation.SwapQuotient
#guard_standard_axioms_prefix Fermat.Conservation.TransverseAnnihilator.CornerService
#guard_standard_axioms_prefix PowerRoot
#guard_standard_axioms_prefix IsDedekindDomain.selmerGroup
#guard_standard_axioms_prefix Fermat.Conservation.PowerRootExactSequence
#guard_standard_axioms_prefix Fermat.Conservation.PowerRootNaturality
#guard_standard_axioms_prefix Fermat.Conservation.LinkingInterfaces
#guard_standard_axioms_prefix Fermat.Conservation.CommonActionStage
#guard_standard_axioms_prefix Fermat.Conservation.TatePairing
#guard_standard_axioms_prefix Fermat.Conservation.TameSymbol
#guard_standard_axioms_prefix Fermat.Conservation.SelmerEigenspace
#guard_standard_axioms_prefix Fermat.Conservation.TamePlacePairing
#guard_standard_axioms_prefix Fermat.Conservation.CohomologyExactCell
#guard_standard_axioms_prefix Fermat.Conservation.SteeringFiber
#guard_standard_axioms_prefix Fermat.Conservation.IsoConserveBridge.cohomologyBalancedStep
#guard_standard_axioms_prefix Fermat.Conservation.IsoConserveBridge.cohomology_L1_conservation

/-! The PowerRoot extension and cohomology filtration must stay exact without
exposing or consuming a chosen equivalence between either middle object and a
product of its ends. -/

#audit_no_product_equiv_types_prefix Fermat.Conservation.PowerRootExactSequence
#audit_no_product_equiv_types_prefix Fermat.Conservation.CohomologyExactCell
#audit_no_product_equiv_types_prefix Fermat.Conservation.SteeringFiber
