/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, OpenAI

# The converse Albert criterion at an arbitrary prime

A compatible lift of the concrete Kummer character from `C_p` to `C_(p²)`
cuts out a cyclic degree-`p²` field.  The `p`-th power of a generator has a
`zeta`-eigenvector; its successive-orbit ratio lies in the Kummer subfield
and has norm `zeta` by telescoping.

`PerfectField F` is the honest scope required by Mathlib's infinite-Galois
fixed-field correspondence.
-/
import Fermat.Conservation.PrimeAlbertCyclicCompatibility
import Mathlib.FieldTheory.Galois.Infinite
import Mathlib.FieldTheory.KummerExtension
import Mathlib.LinearAlgebra.Eigenspace.Minpoly
import Mathlib.Tactic

open Polynomial

noncomputable section

namespace Fermat.Conservation.PrimeAlbertCyclicConverse

open Fermat.Conservation.PrimeAlbertCyclicCompatibility
open Fermat.Conservation.PrimeAlbertExtension
open Fermat.Conservation.PrimeCyclicExtension
open Fermat.Conservation.PrimeKummerCyclicQuotient

variable (p : ℕ) [Fact p.Prime]

local instance : NeZero p := ⟨(Fact.out : Nat.Prime p).ne_zero⟩
local instance : NeZero (p ^ 2) :=
  ⟨pow_ne_zero 2 (Fact.out : Nat.Prime p).ne_zero⟩

local instance : TopologicalSpace (CyclicGroup p) := ⊥
local instance : DiscreteTopology (CyclicGroup p) := ⟨rfl⟩
local instance : TopologicalSpace (CyclicGroupSquared p) := ⊥
local instance : DiscreteTopology (CyclicGroupSquared p) := ⟨rfl⟩

/-- The kernel of reduction `C_(p²) → C_p` is generated by the additive
coordinate `p`. -/
theorem reduction_ker_eq_zpowers :
    (reduction p).toMonoidHom.ker =
      Subgroup.zpowers (Multiplicative.ofAdd (p : ZMod (p ^ 2))) := by
  apply le_antisymm
  · intro q hq
    have hcast : (q.toAdd.val : ZMod p) = 0 := by
      have h := congrArg Multiplicative.toAdd ((MonoidHom.mem_ker).1 hq)
      change ZMod.castHom (p_dvd_p_sq p) (ZMod p) q.toAdd = 0 at h
      rw [ZMod.castHom_apply, ZMod.cast_eq_val] at h
      exact h
    have hdvd : p ∣ q.toAdd.val :=
      (ZMod.natCast_eq_zero_iff q.toAdd.val p).1 hcast
    obtain ⟨k, hk⟩ := hdvd
    have hqPow : q =
        (Multiplicative.ofAdd (p : ZMod (p ^ 2))) ^ k := by
      apply Multiplicative.toAdd.injective
      change q.toAdd = k • (p : ZMod (p ^ 2))
      rw [← ZMod.natCast_zmod_val q.toAdd, hk, Nat.cast_mul]
      simp [nsmul_eq_mul, mul_comm]
    rw [hqPow]
    exact Subgroup.pow_mem _ (Subgroup.mem_zpowers _) k
  · apply Subgroup.zpowers_le.2
    apply (MonoidHom.mem_ker).2
    apply Multiplicative.toAdd.injective
    change ZMod.castHom (p_dvd_p_sq p) (ZMod p)
      (p : ZMod (p ^ 2)) = 0
    rw [ZMod.castHom_apply,
      ZMod.cast_natCast (R := ZMod p) (p_dvd_p_sq p),
      ZMod.natCast_self]

/-- An element reducing to the standard generator modulo `p` has a unit
additive coordinate modulo `p²`. -/
theorem reduction_preimage_generator_isUnit
    (x : CyclicGroupSquared p)
    (hx : reduction p x = Multiplicative.ofAdd (1 : ZMod p)) :
    IsUnit x.toAdd := by
  rw [← ZMod.natCast_zmod_val x.toAdd]
  rw [ZMod.isUnit_iff_coprime]
  have hnot : ¬p ∣ x.toAdd.val := by
    intro hdvd
    have hxzero : (x.toAdd.val : ZMod p) = 0 := by
      rw [ZMod.natCast_eq_zero_iff]
      exact hdvd
    have hxone : (x.toAdd.val : ZMod p) = 1 := by
      have h := congrArg Multiplicative.toAdd hx
      change ZMod.castHom (p_dvd_p_sq p) (ZMod p) x.toAdd = 1 at h
      rw [ZMod.castHom_apply, ZMod.cast_eq_val] at h
      exact h
    rw [hxzero] at hxone
    exact zero_ne_one hxone
  exact Nat.Prime.coprime_pow_of_not_dvd
    (Fact.out : Nat.Prime p) hnot

/-- Surjectivity after reduction already forces surjectivity in `C_(p²)`. -/
theorem surjective_of_reduction_comp_surjective
    {G : Type} [Group G]
    (psi : G →* CyclicGroupSquared p)
    (hsurj : Function.Surjective
      ((reduction p).toMonoidHom.comp psi)) :
    Function.Surjective psi := by
  obtain ⟨g, hg⟩ := hsurj (Multiplicative.ofAdd (1 : ZMod p))
  let x := psi g
  have hxred : reduction p x = Multiplicative.ofAdd (1 : ZMod p) := hg
  have hxunit : IsUnit x.toAdd :=
    reduction_preimage_generator_isUnit p x hxred
  intro y
  let u : (ZMod (p ^ 2))ˣ := hxunit.unit
  let n : ℕ := (((u⁻¹ : (ZMod (p ^ 2))ˣ) : ZMod (p ^ 2)) * y.toAdd).val
  refine ⟨g ^ n, ?_⟩
  rw [map_pow]
  apply Multiplicative.toAdd.injective
  change n • x.toAdd = y.toAdd
  have hu : (u : ZMod (p ^ 2)) = x.toAdd := hxunit.unit_spec
  rw [← hu, nsmul_eq_mul]
  change (n : ZMod (p ^ 2)) * (u : ZMod (p ^ 2)) = y.toAdd
  rw [show (n : ZMod (p ^ 2)) =
      ((u⁻¹ : (ZMod (p ^ 2))ˣ) : ZMod (p ^ 2)) * y.toAdd by
    exact ZMod.natCast_zmod_val _]
  calc
    (((u⁻¹ : (ZMod (p ^ 2))ˣ) : ZMod (p ^ 2)) * y.toAdd) *
        (u : ZMod (p ^ 2)) =
      (((u⁻¹ : (ZMod (p ^ 2))ˣ) : ZMod (p ^ 2)) *
        (u : ZMod (p ^ 2))) * y.toAdd := by ac_rfl
    _ = y.toAdd := by simp

/-- Continuous specialization of
`surjective_of_reduction_comp_surjective`. -/
theorem continuous_surjective_of_reduction_comp_surjective
    {G : Type} [Group G] [TopologicalSpace G]
    (psi : G →ₜ* CyclicGroupSquared p)
    (hsurj : Function.Surjective ((reduction p).comp psi)) :
    Function.Surjective psi :=
  surjective_of_reduction_comp_surjective p psi.toMonoidHom hsurj

section RatioFixed

variable {F M : Type*} [Field F] [Field M] [Algebra F M]

omit [Fact p.Prime] in
/-- If `tau^p` scales `y` by a nonzero base-field scalar, then it fixes the
successive-orbit ratio `tau(y) / y`. -/
theorem prime_pow_fixes_successive_ratio
    (tau : M ≃ₐ[F] M) (zeta : F) (y : M)
    (hzeta : zeta ≠ 0)
    (hy : (tau ^ p) y = algebraMap F M zeta * y) :
    (tau ^ p) (tau y / y) = tau y / y := by
  have hcomm : (tau ^ p) * tau = tau * (tau ^ p) :=
    (Commute.self_pow tau p).symm.eq
  have hcommApply : (tau ^ p) (tau y) = tau ((tau ^ p) y) := by
    rw [← AlgEquiv.mul_apply, hcomm, AlgEquiv.mul_apply]
  have hzetaM : algebraMap F M zeta ≠ 0 := by
    intro hzero
    apply hzeta
    apply (algebraMap F M).injective
    simpa using hzero
  calc
    (tau ^ p) (tau y / y) =
        (tau ^ p) (tau y) / (tau ^ p) y :=
      map_div₀ (tau ^ p) (tau y) y
    _ = tau ((tau ^ p) y) / (tau ^ p) y := by rw [hcommApply]
    _ = tau (algebraMap F M zeta * y) /
        (algebraMap F M zeta * y) := by rw [hy]
    _ = (algebraMap F M zeta * tau y) /
        (algebraMap F M zeta * y) := by rw [map_mul, tau.commutes]
    _ = tau y / y := by
      field_simp [hzetaM]

/-- The product of successive orbit ratios telescopes exactly. -/
theorem orbitProduct_successive_ratio
    (tau : M ≃ₐ[F] M) (y : M) (hy : y ≠ 0) (n : ℕ) :
    (∏ i ∈ Finset.range n, (tau ^ i) (tau y / y)) =
      (tau ^ n) y / y := by
  induction n with
  | zero => simp [hy]
  | succ n ih =>
      rw [Finset.prod_range_succ, ih, map_div₀,
        pow_succ, AlgEquiv.mul_apply]
      have hpow : (tau ^ n) y ≠ 0 := by
        simpa using (tau ^ n).injective.ne hy
      field_simp [hy, hpow]

end RatioFixed

section FixedField

variable (F : Type) [Field F]

/-- The closed kernel of a continuous `C_(p²)` character. -/
def cyclicSquaredKernel
    (psi : Field.absoluteGaloisGroup F →ₜ* CyclicGroupSquared p) :
    ClosedSubgroup (Field.absoluteGaloisGroup F) where
  toSubgroup := psi.toMonoidHom.ker
  isClosed' := by
    change IsClosed (psi ⁻¹' ({1} : Set (CyclicGroupSquared p)))
    exact isClosed_singleton.preimage psi.continuous

theorem cyclicSquaredKernel_isOpen
    (psi : Field.absoluteGaloisGroup F →ₜ* CyclicGroupSquared p) :
    IsOpen ((cyclicSquaredKernel p F psi : ClosedSubgroup
      (Field.absoluteGaloisGroup F)) : Set (Field.absoluteGaloisGroup F)) := by
  change IsOpen (psi ⁻¹' ({1} : Set (CyclicGroupSquared p)))
  exact (isOpen_discrete {1}).preimage psi.continuous

/-- The finite field cut out by a continuous `C_(p²)` character. -/
def cyclicSquaredFixedField
    (psi : Field.absoluteGaloisGroup F →ₜ* CyclicGroupSquared p) :
    IntermediateField F (AlgebraicClosure F) :=
  IntermediateField.fixedField (cyclicSquaredKernel p F psi).toSubgroup

instance cyclicSquaredKernel.instNormal
    (psi : Field.absoluteGaloisGroup F →ₜ* CyclicGroupSquared p) :
    (cyclicSquaredKernel p F psi).toSubgroup.Normal := by
  dsimp [cyclicSquaredKernel]
  exact MonoidHom.normal_ker psi.toMonoidHom

variable [PerfectField F]

theorem cyclicSquaredFixedField_finiteDimensional
    (psi : Field.absoluteGaloisGroup F →ₜ* CyclicGroupSquared p) :
    FiniteDimensional F (cyclicSquaredFixedField p F psi) := by
  apply (InfiniteGalois.isOpen_iff_finite (cyclicSquaredFixedField p F psi)).mp
  unfold cyclicSquaredFixedField
  rw [InfiniteGalois.fixingSubgroup_fixedField (cyclicSquaredKernel p F psi)]
  exact cyclicSquaredKernel_isOpen p F psi

theorem cyclicSquaredFixedField_isGalois
    (psi : Field.absoluteGaloisGroup F →ₜ* CyclicGroupSquared p) :
    IsGalois F (cyclicSquaredFixedField p F psi) := by
  apply (InfiniteGalois.normal_iff_isGalois
    (cyclicSquaredFixedField p F psi)).mp
  unfold cyclicSquaredFixedField
  rw [InfiniteGalois.fixingSubgroup_fixedField (cyclicSquaredKernel p F psi)]
  exact MonoidHom.normal_ker psi.toMonoidHom

noncomputable instance cyclicSquaredFixedField.instFiniteDimensional
    (psi : Field.absoluteGaloisGroup F →ₜ* CyclicGroupSquared p) :
    FiniteDimensional F (cyclicSquaredFixedField p F psi) :=
  cyclicSquaredFixedField_finiteDimensional p F psi

noncomputable instance cyclicSquaredFixedField.instIsGalois
    (psi : Field.absoluteGaloisGroup F →ₜ* CyclicGroupSquared p) :
    IsGalois F (cyclicSquaredFixedField p F psi) :=
  cyclicSquaredFixedField_isGalois p F psi

/-- The finite Galois group of the fixed field, identified with the target
of a surjective character. -/
def cyclicSquaredFixedFieldGalEquiv
    (psi : Field.absoluteGaloisGroup F →ₜ* CyclicGroupSquared p)
    (hsurj : Function.Surjective psi) :
    ((cyclicSquaredFixedField p F psi) ≃ₐ[F]
      (cyclicSquaredFixedField p F psi)) ≃* CyclicGroupSquared p := by
  let H := cyclicSquaredKernel p F psi
  let hnormal : (↑H : Subgroup (Field.absoluteGaloisGroup F)).Normal := by
    dsimp [H, cyclicSquaredKernel]
    exact MonoidHom.normal_ker psi.toMonoidHom
  letI : (↑H : Subgroup (Field.absoluteGaloisGroup F)).Normal := hnormal
  let q0 := @InfiniteGalois.normalAutEquivQuotient
    F (AlgebraicClosure F) _ _ _ (by infer_instance) H hnormal
  have hH : (↑H : Subgroup (Field.absoluteGaloisGroup F)) =
      psi.toMonoidHom.ker := by
    rfl
  let hle : (↑H : Subgroup (Field.absoluteGaloisGroup F)) ≤
      psi.toMonoidHom.ker := hH.le
  let lift : (Field.absoluteGaloisGroup F ⧸
      (↑H : Subgroup (Field.absoluteGaloisGroup F))) →* CyclicGroupSquared p :=
    QuotientGroup.lift (↑H : Subgroup (Field.absoluteGaloisGroup F))
      psi.toMonoidHom hle
  have hliftSurj : Function.Surjective lift :=
    QuotientGroup.lift_surjective_of_surjective
      (↑H : Subgroup (Field.absoluteGaloisGroup F))
      psi.toMonoidHom hsurj hle
  have hliftKer : lift.ker = ⊥ := by
    dsimp [lift]
    rw [QuotientGroup.ker_lift]
    change Subgroup.map
      (QuotientGroup.mk' (↑H : Subgroup (Field.absoluteGaloisGroup F)))
        psi.toMonoidHom.ker = ⊥
    rw [← hH, QuotientGroup.map_mk'_self]
  have hliftInj : Function.Injective lift :=
    lift.ker_eq_bot_iff.mp hliftKer
  let eLift : (Field.absoluteGaloisGroup F ⧸
      (↑H : Subgroup (Field.absoluteGaloisGroup F))) ≃* CyclicGroupSquared p :=
    MulEquiv.ofBijective lift ⟨hliftInj, hliftSurj⟩
  let qsymm :
      ((IntermediateField.fixedField (↑H : Subgroup
        (Field.absoluteGaloisGroup F))) ≃ₐ[F]
          (IntermediateField.fixedField (↑H : Subgroup
            (Field.absoluteGaloisGroup F)))) ≃*
        (Field.absoluteGaloisGroup F ⧸
          (↑H : Subgroup (Field.absoluteGaloisGroup F))) :=
    @MulEquiv.symm
      (Field.absoluteGaloisGroup F ⧸
        (↑H : Subgroup (Field.absoluteGaloisGroup F)))
      ((IntermediateField.fixedField (↑H : Subgroup
        (Field.absoluteGaloisGroup F))) ≃ₐ[F]
          (IntermediateField.fixedField (↑H : Subgroup
            (Field.absoluteGaloisGroup F))))
      (@QuotientGroup.Quotient.group (Field.absoluteGaloisGroup F) _
        (↑H : Subgroup (Field.absoluteGaloisGroup F)) hnormal).toMulOneClass.toMul
      (@AlgEquiv.aut F (IntermediateField.fixedField (↑H : Subgroup
        (Field.absoluteGaloisGroup F))) _ _ _).toMulOneClass.toMul
      q0
  change ((IntermediateField.fixedField (↑H : Subgroup
      (Field.absoluteGaloisGroup F))) ≃ₐ[F]
        (IntermediateField.fixedField (↑H : Subgroup
          (Field.absoluteGaloisGroup F)))) ≃* CyclicGroupSquared p
  exact @MulEquiv.trans _ _ _
    (@AlgEquiv.aut F (IntermediateField.fixedField (↑H : Subgroup
      (Field.absoluteGaloisGroup F))) _ _ _).toMulOneClass.toMul
    (@QuotientGroup.Quotient.group (Field.absoluteGaloisGroup F) _
      (↑H : Subgroup (Field.absoluteGaloisGroup F)) hnormal).toMulOneClass.toMul
    (@Multiplicative.group (ZMod (p ^ 2)) _).toMulOneClass.toMul
    qsymm eLift

theorem cyclicSquaredFixedField_finrank
    (psi : Field.absoluteGaloisGroup F →ₜ* CyclicGroupSquared p)
    (hsurj : Function.Surjective psi) :
    Module.finrank F (cyclicSquaredFixedField p F psi) = p ^ 2 := by
  rw [← IsGalois.card_aut_eq_finrank]
  calc
    Nat.card ((cyclicSquaredFixedField p F psi) ≃ₐ[F]
        (cyclicSquaredFixedField p F psi)) =
        Nat.card (CyclicGroupSquared p) :=
      Nat.card_congr (cyclicSquaredFixedFieldGalEquiv p F psi hsurj).toEquiv
    _ = p ^ 2 := by simp

theorem cyclicSquaredFixedField_fixingSubgroup
    (psi : Field.absoluteGaloisGroup F →ₜ* CyclicGroupSquared p) :
    (cyclicSquaredFixedField p F psi).fixingSubgroup =
      psi.toMonoidHom.ker := by
  unfold cyclicSquaredFixedField
  rw [InfiniteGalois.fixingSubgroup_fixedField (cyclicSquaredKernel p F psi)]
  rfl

end FixedField

section KummerInsideFixedField

variable (F : Type) [Field F]

/-- Exact compatibility forces the degree-`p` Kummer field to lie inside
the degree-`p²` field cut out by the lifted character. -/
theorem concreteKummer_le_cyclicSquaredFixedField
    (zeta a : F)
    (hzeta : IsPrimitiveRoot zeta p)
    (ha : ∀ b : F, b ^ p ≠ a)
    (psi : Field.absoluteGaloisGroup F →ₜ* CyclicGroupSquared p)
    (hpsi : (reduction p).comp psi =
      kummerCharacter p F zeta a hzeta ha) :
    kummerExtension p F a ≤ cyclicSquaredFixedField p F psi := by
  let K := kummerExtension p F a
  letI : IsSplittingField F K (kummerPolynomial p F a) :=
    kummerExtension_isSplittingField p F a
  letI : FiniteDimensional F K :=
    Polynomial.IsSplittingField.finiteDimensional K
      (kummerPolynomial p F a)
  letI : IsGalois F K :=
    isGalois_of_isSplittingField_X_pow_sub_C
      ⟨zeta, (mem_primitiveRoots (Fact.out : Nat.Prime p).pos).2 hzeta⟩
      (kummerPolynomial_irreducible p F a ha) K
  change K ≤ IntermediateField.fixedField psi.toMonoidHom.ker
  apply (IntermediateField.le_iff_le psi.toMonoidHom.ker K).2
  intro g hg
  have hpg : psi g = 1 := (MonoidHom.mem_ker).1 hg
  have hchi : kummerCharacter p F zeta a hzeta ha g = 1 := by
    rw [← hpsi]
    change reduction p (psi g) = 1
    rw [hpg, map_one]
  have hresChar :
      (kummerGalEquiv p F zeta a hzeta ha)
        (AlgEquiv.restrictNormalHom K g) = 1 := by
    change Fermat.Conservation.ContinuousCyclicQuotient.cyclicQuotient
      F p K (kummerGalEquiv p F zeta a hzeta ha) g = 1 at hchi
    rw [Fermat.Conservation.ContinuousCyclicQuotient.cyclicQuotient_apply]
      at hchi
    exact hchi
  have hres : AlgEquiv.restrictNormalHom K g = 1 := by
    apply (kummerGalEquiv p F zeta a hzeta ha).injective
    simpa using hresChar
  rw [← K.restrictNormalHom_ker]
  exact (MonoidHom.mem_ker).2 hres

theorem kummerCharacter_eq_one_of_mem_fixingSubgroup
    (F : Type) [Field F]
    (zeta a : F)
    (hzeta : IsPrimitiveRoot zeta p)
    (ha : ∀ b : F, b ^ p ≠ a)
    (g : AlgebraicClosure F ≃ₐ[F] AlgebraicClosure F)
    (hg : g ∈ (kummerExtension p F a).fixingSubgroup) :
    kummerCharacter p F zeta a hzeta ha g = 1 := by
  let K := kummerExtension p F a
  letI : IsSplittingField F K (kummerPolynomial p F a) :=
    kummerExtension_isSplittingField p F a
  letI : FiniteDimensional F K :=
    Polynomial.IsSplittingField.finiteDimensional K
      (kummerPolynomial p F a)
  letI : IsGalois F K :=
    isGalois_of_isSplittingField_X_pow_sub_C
      ⟨zeta, (mem_primitiveRoots (Fact.out : Nat.Prime p).pos).2 hzeta⟩
      (kummerPolynomial_irreducible p F a ha) K
  have hres : AlgEquiv.restrictNormalHom K g = 1 := by
    apply (MonoidHom.mem_ker).1
    rw [K.restrictNormalHom_ker]
    exact hg
  change Fermat.Conservation.ContinuousCyclicQuotient.cyclicQuotient
    F p K (kummerGalEquiv p F zeta a hzeta ha) g = 1
  rw [Fermat.Conservation.ContinuousCyclicQuotient.cyclicQuotient_apply,
    hres, map_one]

end KummerInsideFixedField

section ReductionKernelAction

variable (F : Type) [Field F] [PerfectField F]

/-- If an absolute-Galois element has trivial reduction modulo `p`, its
action on the field cut out by `psi` is a power of the `p`-th power of a
chosen lift generator. -/
theorem fixedField_restriction_mem_zpowers_prime
    (psi : Field.absoluteGaloisGroup F →ₜ* CyclicGroupSquared p)
    (g h : AlgebraicClosure F ≃ₐ[F] AlgebraicClosure F)
    (hg : psi g = Multiplicative.ofAdd (1 : ZMod (p ^ 2)))
    (hh : reduction p (psi h) = 1) :
    AlgEquiv.restrictNormalHom (cyclicSquaredFixedField p F psi) h ∈
      Subgroup.zpowers
        ((AlgEquiv.restrictNormalHom
          (cyclicSquaredFixedField p F psi) g) ^ p) := by
  let M := cyclicSquaredFixedField p F psi
  have hqKer : psi h ∈ (reduction p).toMonoidHom.ker :=
    (MonoidHom.mem_ker).2 hh
  rw [reduction_ker_eq_zpowers p] at hqKer
  obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp hqKer
  have hgPow : psi (g ^ p) =
      Multiplicative.ofAdd (p : ZMod (p ^ 2)) := by
    calc
      psi (g ^ p) = (psi g) ^ p := map_pow psi g p
      _ = (Multiplicative.ofAdd (1 : ZMod (p ^ 2))) ^ p := by rw [hg]
      _ = Multiplicative.ofAdd (p : ZMod (p ^ 2)) := by
        apply Multiplicative.toAdd.injective
        simp [nsmul_eq_mul]
  have hpsiEq : psi ((g ^ p) ^ n) = psi h := by
    calc
      psi ((g ^ p) ^ n) = (psi (g ^ p)) ^ n := map_zpow psi (g ^ p) n
      _ = (Multiplicative.ofAdd (p : ZMod (p ^ 2))) ^ n := by rw [hgPow]
      _ = psi h := hn
  have heq : AlgEquiv.restrictNormalHom M ((g ^ p) ^ n) =
      AlgEquiv.restrictNormalHom M h := by
    apply (AlgEquiv.restrictNormalHom M).eq_iff.2
    rw [M.restrictNormalHom_ker,
      cyclicSquaredFixedField_fixingSubgroup p F psi]
    exact psi.toMonoidHom.eq_iff.1 hpsiEq
  have hzpow : (g ^ p) ^ n ∈
      Subgroup.zpowers (g ^ p) := ⟨n, rfl⟩
  have hmap : AlgEquiv.restrictNormalHom M ((g ^ p) ^ n) ∈
      (Subgroup.zpowers (g ^ p)).map
        (AlgEquiv.restrictNormalHom M) := ⟨_, hzpow, rfl⟩
  rw [MonoidHom.map_zpowers, map_pow] at hmap
  rw [← heq]
  exact hmap

end ReductionKernelAction

section RatioInKummerField

variable (F : Type) [Field F] [PerfectField F]

set_option maxRecDepth 10000 in
/-- A point of the `C_(p²)` fixed field fixed by the `p`-th power of a lift
generator belongs to the concrete Kummer subfield. -/
theorem fixedBy_prime_mem_kummerExtension
    (zeta a : F)
    (hzeta : IsPrimitiveRoot zeta p)
    (ha : ∀ b : F, b ^ p ≠ a)
    (psi : Field.absoluteGaloisGroup F →ₜ* CyclicGroupSquared p)
    (hpsi : (reduction p).comp psi =
      kummerCharacter p F zeta a hzeta ha)
    (g : AlgebraicClosure F ≃ₐ[F] AlgebraicClosure F)
    (hg : psi g = Multiplicative.ofAdd (1 : ZMod (p ^ 2)))
    (x : cyclicSquaredFixedField p F psi)
    (hx : ((AlgEquiv.restrictNormalHom
      (cyclicSquaredFixedField p F psi) g) ^ p) x = x) :
    (x : AlgebraicClosure F) ∈ kummerExtension p F a := by
  let K := kummerExtension p F a
  let M := cyclicSquaredFixedField p F psi
  letI : IsSplittingField F K (kummerPolynomial p F a) :=
    kummerExtension_isSplittingField p F a
  letI : FiniteDimensional F K :=
    Polynomial.IsSplittingField.finiteDimensional K
      (kummerPolynomial p F a)
  letI : IsGalois F K :=
    isGalois_of_isSplittingField_X_pow_sub_C
      ⟨zeta, (mem_primitiveRoots (Fact.out : Nat.Prime p).pos).2 hzeta⟩
      (kummerPolynomial_irreducible p F a ha) K
  change (x : AlgebraicClosure F) ∈ K
  rw [← InfiniteGalois.fixedField_fixingSubgroup K]
  intro h
  rcases h with ⟨h, hh⟩
  have hchi : kummerCharacter p F zeta a hzeta ha h = 1 :=
    kummerCharacter_eq_one_of_mem_fixingSubgroup
      p F zeta a hzeta ha h hh
  have heval := DFunLike.congr_fun hpsi h
  have hred : reduction p (psi h) = 1 := by
    change reduction p (psi h) =
      kummerCharacter p F zeta a hzeta ha h at heval
    rw [heval, hchi]
  have hmem := fixedField_restriction_mem_zpowers_prime
    p F psi g h hg hred
  have hfixedM : AlgEquiv.restrictNormalHom M h x = x := by
    have hsmul := smul_eq_self_of_mem_zpowers hmem
      (a := x) (by
        change ((AlgEquiv.restrictNormalHom M g) ^ p) x = x
        exact hx)
    simpa [AlgEquiv.smul_def] using hsmul
  calc
    h (x : AlgebraicClosure F) =
        ((AlgEquiv.restrictNormalHom M h) x : M) := by
      symm
      exact AlgEquiv.restrictNormalHom_apply M h x
    _ = (x : AlgebraicClosure F) := congrArg Subtype.val hfixedM

end RatioInKummerField

section LiftGeneratorEigenvector

variable (F : Type) [Field F] [PerfectField F]

set_option maxRecDepth 10000 in
/-- A compatible lift supplies a generator whose `p`-th power has an honest
nonzero `zeta`-eigenvector in its fixed field. -/
theorem exists_cyclicSquared_generator_eigenvector
    (zeta a : F)
    (hzeta : IsPrimitiveRoot zeta p)
    (ha : ∀ b : F, b ^ p ≠ a)
    (psi : Field.absoluteGaloisGroup F →ₜ* CyclicGroupSquared p)
    (hpsi : (reduction p).comp psi =
      kummerCharacter p F zeta a hzeta ha) :
    ∃ g : Field.absoluteGaloisGroup F,
      ∃ y : cyclicSquaredFixedField p F psi,
        psi g = Multiplicative.ofAdd (1 : ZMod (p ^ 2)) ∧
        orderOf (AlgEquiv.restrictNormalHom
          (cyclicSquaredFixedField p F psi) g) = p ^ 2 ∧
        y ≠ 0 ∧
        ((AlgEquiv.restrictNormalHom
          (cyclicSquaredFixedField p F psi) g) ^ p) y =
          algebraMap F (cyclicSquaredFixedField p F psi) zeta * y := by
  let M := cyclicSquaredFixedField p F psi
  have hredSurj : Function.Surjective ((reduction p).comp psi) := by
    rw [hpsi]
    exact kummerCharacter_surjective p F zeta a hzeta ha
  have hsurj : Function.Surjective psi :=
    continuous_surjective_of_reduction_comp_surjective p psi hredSurj
  obtain ⟨g, hg⟩ := hsurj (Multiplicative.ofAdd (1 : ZMod (p ^ 2)))
  let tau : M ≃ₐ[F] M := AlgEquiv.restrictNormalHom M g
  have hpCast : (p : ZMod (p ^ 2)) ≠ 0 := by
    intro hp0
    have hdvd : p ^ 2 ∣ p :=
      (ZMod.natCast_eq_zero_iff p (p ^ 2)).1 hp0
    have hle : p ^ 2 ≤ p :=
      Nat.le_of_dvd (Fact.out : Nat.Prime p).pos hdvd
    nlinarith [(Fact.out : Nat.Prime p).two_le]
  have hgenPow :
      (Multiplicative.ofAdd (1 : ZMod (p ^ 2))) ^ p ≠ 1 := by
    intro h
    apply hpCast
    have hadd := congrArg Multiplicative.toAdd h
    change p • (1 : ZMod (p ^ 2)) = 0 at hadd
    simpa [nsmul_eq_mul] using hadd
  have htauPow_ne : tau ^ p ≠ 1 := by
    intro htau
    have hrestrict : AlgEquiv.restrictNormalHom M (g ^ p) = 1 := by
      change (AlgEquiv.restrictNormalHom M g) ^ p = 1 at htau
      rw [← map_pow] at htau
      exact htau
    have hgFix : g ^ p ∈ M.fixingSubgroup := by
      rw [← M.restrictNormalHom_ker]
      exact (MonoidHom.mem_ker).2 hrestrict
    have hgKer : g ^ p ∈ psi.toMonoidHom.ker := by
      change g ^ p ∈ (cyclicSquaredFixedField p F psi).fixingSubgroup at hgFix
      rwa [cyclicSquaredFixedField_fixingSubgroup p F psi] at hgFix
    have hpsiPow : psi (g ^ p) = 1 := (MonoidHom.mem_ker).1 hgKer
    apply hgenPow
    simpa [map_pow, hg] using hpsiPow
  have hcard : Nat.card (M ≃ₐ[F] M) = p ^ 2 := by
    rw [IsGalois.card_aut_eq_finrank]
    exact cyclicSquaredFixedField_finrank p F psi hsurj
  have hdiv : orderOf tau ∣ p ^ 2 := by
    have hdiv0 := orderOf_dvd_natCard tau
    rwa [hcard] at hdiv0
  obtain ⟨k, hk, horder⟩ :=
    (Nat.dvd_prime_pow (Fact.out : Nat.Prime p)).1 hdiv
  have htauOrder : orderOf tau = p ^ 2 := by
    interval_cases k
    · have hsmall : orderOf tau ∣ p := by simp [horder]
      exact (htauPow_ne (orderOf_dvd_iff_pow_eq_one.mp hsmall)).elim
    · have hsmall : orderOf tau ∣ p := by simp [horder]
      exact (htauPow_ne (orderOf_dvd_iff_pow_eq_one.mp hsmall)).elim
    · simpa using horder
  let rho : M ≃ₐ[F] M := tau ^ p
  have hrhoOrder : orderOf rho = p := by
    dsimp [rho]
    rw [orderOf_pow, htauOrder]
    simp [pow_two, (Fact.out : Nat.Prime p).ne_zero]
  have hroot : IsRoot (minpoly F rho.toLinearMap) zeta := by
    rw [minpoly_algEquiv_toLinearMap rho (isOfFinOrder_of_finite rho),
      hrhoOrder]
    simpa [sub_eq_zero] using hzeta.pow_eq_one
  obtain ⟨y, hy⟩ :=
    (Module.End.hasEigenvalue_of_isRoot hroot).exists_hasEigenvector
  refine ⟨g, y, hg, htauOrder, hy.2, ?_⟩
  calc
    ((AlgEquiv.restrictNormalHom M g) ^ p) y = rho y := rfl
    _ = zeta • y := hy.apply_eq_smul
    _ = algebraMap F M zeta * y := by rw [Algebra.smul_def]

end LiftGeneratorEigenvector

section AlbertConverse

variable (F : Type) [Field F] [PerfectField F]

set_option maxRecDepth 10000 in
/-- Converse Albert criterion for the concrete degree-`p` Kummer extension:
an exact lift of its Kummer character to `C_(p²)` produces an element whose
norm is the supplied primitive `p`-th root of unity. -/
theorem concreteKummer_exists_norm_of_albertCharacter
    (zeta a : F)
    (hzeta : IsPrimitiveRoot zeta p)
    (ha : ∀ b : F, b ^ p ≠ a)
    (psi : Field.absoluteGaloisGroup F →ₜ* CyclicGroupSquared p)
    (hpsi : (reduction p).comp psi =
      kummerCharacter p F zeta a hzeta ha) :
    ∃ beta : kummerExtension p F a,
      Algebra.norm F beta = zeta := by
  let K := kummerExtension p F a
  let M := cyclicSquaredFixedField p F psi
  letI : IsSplittingField F K (kummerPolynomial p F a) :=
    kummerExtension_isSplittingField p F a
  letI : FiniteDimensional F K :=
    Polynomial.IsSplittingField.finiteDimensional K
      (kummerPolynomial p F a)
  letI : IsGalois F K :=
    isGalois_of_isSplittingField_X_pow_sub_C
      ⟨zeta, (mem_primitiveRoots (Fact.out : Nat.Prime p).pos).2 hzeta⟩
      (kummerPolynomial_irreducible p F a ha) K
  obtain ⟨g, y, hg, htauOrder, hy0, hy⟩ :=
    exists_cyclicSquared_generator_eigenvector
      p F zeta a hzeta ha psi hpsi
  let gamma : AlgebraicClosure F ≃ₐ[F] AlgebraicClosure F := g
  have hgamma : psi gamma =
      Multiplicative.ofAdd (1 : ZMod (p ^ 2)) := hg
  let tau : M ≃ₐ[F] M := AlgEquiv.restrictNormalHom M gamma
  have hy' : (tau ^ p) y = algebraMap F M zeta * y := hy
  let betaM : M := tau y / y
  have hzeta0 : zeta ≠ 0 :=
    hzeta.ne_zero (Fact.out : Nat.Prime p).ne_zero
  have hbetaMFix : (tau ^ p) betaM = betaM := by
    exact prime_pow_fixes_successive_ratio p tau zeta y hzeta0 hy'
  have hbetaMem : (betaM : AlgebraicClosure F) ∈ K := by
    exact fixedBy_prime_mem_kummerExtension
      p F zeta a hzeta ha psi hpsi gamma hgamma betaM hbetaMFix
  let beta : K := ⟨(betaM : AlgebraicClosure F), hbetaMem⟩
  refine ⟨beta, ?_⟩
  have hKM : K ≤ M :=
    concreteKummer_le_cyclicSquaredFixedField
      p F zeta a hzeta ha psi hpsi
  let inc : K →ₐ[F] M := IntermediateField.inclusion hKM
  let sigma : K ≃ₐ[F] K := AlgEquiv.restrictNormalHom K gamma
  have hfinrank : Module.finrank F K = p :=
    finrank_of_isSplittingField_X_pow_sub_C
      ⟨zeta, (mem_primitiveRoots (Fact.out : Nat.Prime p).pos).2 hzeta⟩
      (kummerPolynomial_irreducible p F a ha) K
  have hchi : kummerCharacter p F zeta a hzeta ha gamma =
      Multiplicative.ofAdd (1 : ZMod p) := by
    have heval := DFunLike.congr_fun hpsi gamma
    change reduction p (psi gamma) =
      kummerCharacter p F zeta a hzeta ha gamma at heval
    rw [← heval, hgamma, reduction_ofAdd_one]
  have hgenNe : Multiplicative.ofAdd (1 : ZMod p) ≠ 1 := by
    intro h
    have hadd := congrArg Multiplicative.toAdd h
    change (1 : ZMod p) = 0 at hadd
    exact one_ne_zero hadd
  have hsigmaNe : sigma ≠ 1 := by
    intro hsigma
    have hchiOne : kummerCharacter p F zeta a hzeta ha gamma = 1 := by
      change Fermat.Conservation.ContinuousCyclicQuotient.cyclicQuotient
        F p K (kummerGalEquiv p F zeta a hzeta ha) gamma = 1
      rw [Fermat.Conservation.ContinuousCyclicQuotient.cyclicQuotient_apply]
      change (kummerGalEquiv p F zeta a hzeta ha) sigma = 1
      rw [hsigma, map_one]
    exact hgenNe (hchi.symm.trans hchiOne)
  have hcard : Nat.card (K ≃ₐ[F] K) = p := by
    rw [IsGalois.card_aut_eq_finrank, hfinrank]
  have hsigma : ∀ eta : K ≃ₐ[F] K,
      eta ∈ Subgroup.zpowers sigma := by
    intro eta
    exact mem_zpowers_of_prime_card hcard hsigmaNe
  have htelescope :
      (∏ i ∈ Finset.range p, (tau ^ i) betaM) =
        algebraMap F M zeta := by
    calc
      (∏ i ∈ Finset.range p, (tau ^ i) betaM) =
          (tau ^ p) y / y :=
        orbitProduct_successive_ratio tau y hy0 p
      _ = (algebraMap F M zeta * y) / y := by rw [hy']
      _ = algebraMap F M zeta := by field_simp [hy0]
  have hpowMap (i : ℕ) :
      inc ((sigma ^ i) beta) = (tau ^ i) betaM := by
    apply Subtype.ext
    have hKapply := AlgEquiv.restrictNormalHom_apply K (gamma ^ i) beta
    have hMapply := AlgEquiv.restrictNormalHom_apply M (gamma ^ i) betaM
    rw [map_pow] at hKapply hMapply
    calc
      (((sigma ^ i) beta : K) : AlgebraicClosure F) =
          (gamma ^ i) (beta : AlgebraicClosure F) := hKapply
      _ = (gamma ^ i) (betaM : AlgebraicClosure F) := rfl
      _ = (((tau ^ i) betaM : M) : AlgebraicClosure F) := hMapply.symm
  have horbitMap : inc (orbitProduct sigma beta p) =
      ∏ i ∈ Finset.range p, (tau ^ i) betaM := by
    simp only [orbitProduct, map_prod]
    apply Finset.prod_congr rfl
    intro i hi
    exact hpowMap i
  have horbitNorm : orbitProduct sigma beta p =
      algebraMap F K (Algebra.norm F beta) :=
    orbitProduct_eq_algebraMap_norm p sigma beta hsigma hfinrank
  have hnormMap : algebraMap F M (Algebra.norm F beta) =
      algebraMap F M zeta := by
    calc
      algebraMap F M (Algebra.norm F beta) =
          inc (algebraMap F K (Algebra.norm F beta)) :=
        (inc.commutes (Algebra.norm F beta)).symm
      _ = inc (orbitProduct sigma beta p) := by rw [horbitNorm]
      _ = ∏ i ∈ Finset.range p, (tau ^ i) betaM := horbitMap
      _ = algebraMap F M zeta := htelescope
  exact (algebraMap F M).injective hnormMap

/-- The generic concrete Albert criterion: the primitive-root norm condition
is equivalent to exact liftability from `C_p` to `C_(p²)`. -/
theorem concreteKummer_norm_iff_exists_albertCharacter
    (zeta a : F)
    (hzeta : IsPrimitiveRoot zeta p)
    (ha : ∀ b : F, b ^ p ≠ a) :
    (∃ beta : kummerExtension p F a,
        Algebra.norm F beta = zeta) ↔
      ∃ psi : Field.absoluteGaloisGroup F →ₜ* CyclicGroupSquared p,
        (reduction p).comp psi =
          kummerCharacter p F zeta a hzeta ha := by
  constructor
  · rintro ⟨beta, hbeta⟩
    exact concreteKummer_exists_albertCharacter
      p F zeta a hzeta ha beta hbeta
  · rintro ⟨psi, hpsi⟩
    exact concreteKummer_exists_norm_of_albertCharacter
      p F zeta a hzeta ha psi hpsi

end AlbertConverse

end Fermat.Conservation.PrimeAlbertCyclicConverse
