name = "fermat"
version = "0.1.0"
defaultTargets = ["Fermat"]

[[require]]
name = "flt-regular"
git = "https://github.com/leanprover-community/flt-regular.git"
rev = "edd24b3f160b0fd5ce0ee489b69f8247117ff1ed"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "0531bb79fea20efc9ce6942db46b96be5a919400"

[[require]]
name = "KummerCriterion"
git = "https://github.com/riccardobrasca/KummerCriterion.git"
rev = "88e6dd6748a1ba5baac97244aeb27b3e1a5e6286"

[[lean_lib]]
name = "Fermat"
