import Fermat.Descent.Irregular.CircularUnitResidues
import Fermat.Descent.Irregular.CyclotomicCharactersPrime
import Fermat.Descent.Irregular.CyclotomicLogDetPrime
import Fermat.Descent.Irregular.FiniteCyclicCofactor
import Fermat.Descent.Irregular.CanonicalKummerChannels

/-!
# Basis-free auxiliary residue character factorization

The even power-residue weight descends through the sign quotient to an
intrinsic phase on `(ZMod p)ˣ / {±1}`. Every finite-field circular-unit
certificate matrix is the deleted difference matrix of that phase, and its
character projections factor through the same canonical Kummer rows,
independently of the auxiliary prime.
-/

open scoped BigOperators Matrix

namespace Fermat.Irregular.CircularUnitResidues

noncomputable section

open Fermat.Irregular.CyclotomicCharactersPrime
open Fermat.Irregular.CyclotomicLogDetPrime
open Fermat.Irregular.FiniteCyclicCofactor
open Fermat.Irregular.AuxiliaryResidueChannels
open KummerCriterion.CyclotomicUnits

variable {p q h : ℕ} [Fact p.Prime] [Fact q.Prime]

local instance : Fintype (RealResidueGroup p) := Fintype.ofFinite _

namespace Certificate

/-- Canonical half of the even power-residue exponent. -/
def symbolHalf (C : Certificate p q) : ℕ :=
  C.symbolExponent_even.choose

theorem symbolExponent_eq_two_mul_symbolHalf (C : Certificate p q) :
    C.symbolExponent = 2 * C.symbolHalf := by
  have h := C.symbolExponent_even.choose_spec
  simpa only [symbolHalf, two_mul] using h

/-- Evaluate the chosen primitive `p`th residue root at an exponent unit
modulo `p`. -/
def rootAtExponent (C : Certificate p q) (u : (ZMod p)ˣ) : ZMod q :=
  C.root ^ (u : ZMod p).val

theorem rootAtExponent_ne_zero (C : Certificate p q) (u : (ZMod p)ˣ) :
    C.rootAtExponent u ≠ 0 :=
  pow_ne_zero _ (C.root_isPrimitive.ne_zero (Fact.out : p.Prime).ne_zero)

theorem rootAtExponent_ne_one (C : Certificate p q) (u : (ZMod p)ˣ) :
    C.rootAtExponent u ≠ 1 := by
  intro hone
  have hdvd : p ∣ (u : ZMod p).val :=
    (C.root_isPrimitive.pow_eq_one_iff_dvd _).mp hone
  have hval : (u : ZMod p).val = 0 :=
    Nat.eq_zero_of_dvd_of_lt hdvd (ZMod.val_lt _)
  apply Units.ne_zero u
  rw [← ZMod.natCast_zmod_val (u : ZMod p), hval]
  norm_num

theorem rootAtExponent_pow_eq_one (C : Certificate p q)
    (u : (ZMod p)ˣ) : C.rootAtExponent u ^ p = 1 := by
  simp only [rootAtExponent, ← pow_mul]
  rw [Nat.mul_comm, pow_mul, C.root_isPrimitive.pow_eq_one, one_pow]

theorem rootAtExponent_mul (C : Certificate p q)
    (u v : (ZMod p)ˣ) :
    C.rootAtExponent (u * v) =
      C.rootAtExponent u ^ (v : ZMod p).val := by
  have hmod : ((u * v : (ZMod p)ˣ) : ZMod p).val ≡
      (u : ZMod p).val * (v : ZMod p).val [MOD p] := by
    rw [← ZMod.natCast_eq_natCast_iff]
    simp only [ZMod.natCast_zmod_val, Units.val_mul, Nat.cast_mul]
  simpa only [rootAtExponent, pow_mul] using
    pow_eq_pow_of_modEq hmod C.root_isPrimitive.pow_eq_one

theorem rootAtExponent_neg (C : Certificate p q) (u : (ZMod p)ˣ) :
    C.rootAtExponent (-u) = (C.rootAtExponent u)⁻¹ := by
  have hmod : ((-u : (ZMod p)ˣ) : ZMod p).val + (u : ZMod p).val ≡ 0 [MOD p] := by
    rw [← ZMod.natCast_eq_natCast_iff]
    simp
  have hpow := pow_eq_pow_of_modEq hmod C.root_isPrimitive.pow_eq_one
  have hroot0 : C.root ≠ 0 :=
    C.root_isPrimitive.ne_zero (Fact.out : p.Prime).ne_zero
  apply (mul_eq_one_iff_eq_inv₀ (pow_ne_zero _ hroot0)).mp
  simpa only [rootAtExponent, pow_add, pow_zero] using hpow

/-- The even symbol weight evaluated on the residue root belonging to an
exponent unit. -/
def exponentWeight (C : Certificate p q) (h : ℕ) (u : (ZMod p)ˣ) : ZMod q :=
  evenSymbolWeight h (C.rootAtExponent u)

theorem exponentWeight_ne_zero (C : Certificate p q)
    (u : (ZMod p)ˣ) : C.exponentWeight h u ≠ 0 := by
  apply div_ne_zero
  · exact pow_ne_zero _ (sub_ne_zero.mpr (Ne.symm (C.rootAtExponent_ne_one u)))
  · exact pow_ne_zero _ (C.rootAtExponent_ne_zero u)

theorem exponentWeight_neg (C : Certificate p q) (u : (ZMod p)ˣ) :
    C.exponentWeight h (-u) = C.exponentWeight h u := by
  rw [exponentWeight, exponentWeight, C.rootAtExponent_neg]
  exact evenSymbolWeight_inv _ (C.rootAtExponent_ne_zero u)

/-- The even weight as a unit of the auxiliary residue field. -/
def exponentWeightUnit (C : Certificate p q) (h : ℕ)
    (u : (ZMod p)ˣ) : (ZMod q)ˣ :=
  Units.mk0 (C.exponentWeight h u) (C.exponentWeight_ne_zero u)

theorem exponentWeightUnit_neg (C : Certificate p q) (u : (ZMod p)ˣ) :
    C.exponentWeightUnit h (-u) = C.exponentWeightUnit h u := by
  apply Units.ext
  exact C.exponentWeight_neg u

/-- The even weight lies in the `p`th roots generated by the certificate
root, provided the certificate symbol exponent is `2*h`. -/
def exponentWeightRootPower (C : Certificate p q)
    (hm : C.symbolExponent = 2 * h) (u : (ZMod p)ˣ) :
    Subgroup.zpowers C.rootUnit :=
  ⟨C.exponentWeightUnit h u, by
    rw [C.rootUnit_isPrimitive.zpowers_eq]
    rw [mem_rootsOfUnity]
    apply Units.ext
    simp only [Units.val_pow_eq_pow_val, Units.val_one,
      exponentWeightUnit]
    exact C.evenSymbolWeight_pow_eq_one hm _
      (C.rootAtExponent_pow_eq_one u) (C.rootAtExponent_ne_one u)⟩

theorem exponentWeightRootPower_neg (C : Certificate p q)
    (hm : C.symbolExponent = 2 * h) (u : (ZMod p)ˣ) :
    C.exponentWeightRootPower hm (-u) = C.exponentWeightRootPower hm u := by
  apply Subtype.ext
  exact C.exponentWeightUnit_neg u

/-- Discrete logarithm of the even weight before descending through signs. -/
def exponentPhase (C : Certificate p q)
    (hm : C.symbolExponent = 2 * h) (u : (ZMod p)ˣ) : ZMod p :=
  C.rootUnit_isPrimitive.zmodEquivZPowers.symm
    (Additive.ofMul (C.exponentWeightRootPower hm u))

theorem exponentPhase_neg (C : Certificate p q)
    (hm : C.symbolExponent = 2 * h) (u : (ZMod p)ˣ) :
    C.exponentPhase hm (-u) = C.exponentPhase hm u := by
  rw [exponentPhase, exponentPhase, C.exponentWeightRootPower_neg]

/-- Taking the root logarithm converts a quotient of two even weights into
the difference of their phases. -/
theorem exponentPhase_sub_eq_of_weight_ratio_eq_root_pow
    (C : Certificate p q) (hm : C.symbolExponent = 2 * h)
    (u v : (ZMod p)ˣ) (m : ZMod p)
    (hweight : C.exponentWeight h v / C.exponentWeight h u =
      C.root ^ m.val) :
    C.exponentPhase hm v - C.exponentPhase hm u = m := by
  let target : Subgroup.zpowers C.rootUnit :=
    ⟨C.rootUnit ^ m.val, m.val, rfl⟩
  calc
    C.exponentPhase hm v - C.exponentPhase hm u =
        C.rootUnit_isPrimitive.zmodEquivZPowers.symm
          (Additive.ofMul (C.exponentWeightRootPower hm v) -
            Additive.ofMul (C.exponentWeightRootPower hm u)) := by
      rw [exponentPhase, exponentPhase, map_sub]
    _ = C.rootUnit_isPrimitive.zmodEquivZPowers.symm
        (Additive.ofMul target) := by
      congr 1
      apply Subtype.ext
      apply Units.ext
      exact hweight
    _ = (m.val : ZMod p) :=
      C.rootUnit_isPrimitive.zmodEquivZPowers_symm_apply_pow m.val
    _ = m := ZMod.natCast_zmod_val m

/-- The auxiliary symbol phase descended to the real residue group. -/
def realSymbolPhase (C : Certificate p q) (hp_three : 3 ≤ p)
    (hm : C.symbolExponent = 2 * h) : RealResidueGroup p → ZMod p := by
  letI : Fact (2 < p) := ⟨by omega⟩
  exact Quotient.lift (C.exponentPhase hm) (by
    intro u v huv
    change QuotientGroup.leftRel (signSubgroup p) u v at huv
    rw [QuotientGroup.leftRel_apply] at huv
    rcases (signSubgroup_mem_iff (p := p) (u⁻¹ * v)).mp huv with hone | hneg
    · have huv_eq : v = u := by
        calc
          v = u * (u⁻¹ * v) := by simp
          _ = u * 1 := by rw [hone]
          _ = u := by simp
      rw [huv_eq]
    · have huv_eq : v = -u := by
        calc
          v = u * (u⁻¹ * v) := by simp
          _ = u * (-1) := by rw [hneg]
          _ = -u := by simp
      rw [huv_eq, C.exponentPhase_neg])

@[simp]
theorem realSymbolPhase_mk (C : Certificate p q) (hp_three : 3 ≤ p)
    (hm : C.symbolExponent = 2 * h) (u : (ZMod p)ˣ) :
    C.realSymbolPhase hp_three hm (QuotientGroup.mk u) =
      C.exponentPhase hm u := by
  rw [realSymbolPhase]
  exact Quotient.lift_mk _ _ u

theorem rootAtExponent_standardUnit (C : Certificate p q)
    [Fact (2 < p)] (k : Fin ((p - 3) / 2 + 1)) :
    C.rootAtExponent (standardUnit (p := p) k) =
      C.root ^ (k.val + 1) := by
  unfold rootAtExponent
  congr 1
  rw [show ((standardUnit (p := p) k : (ZMod p)ˣ) : ZMod p) =
      (k.val + 1 : ℕ) by exact standardUnit_coe k]
  exact ZMod.val_natCast_of_lt
    (Fermat.Irregular.CyclotomicPlacesPrime.standardExponent_lt
      (p := p) k)

/-- Every certificate matrix entry is a difference of the descended
basis-free phase on the standard real-residue orbit. -/
theorem matrix_entry_eq_realSymbolPhase_difference
    (C : Certificate p q) [Fact (2 < p)] (hp_three : 3 ≤ p)
    (hm : C.symbolExponent = 2 * h)
    (j i : Fin ((p - 3) / 2)) :
    C.matrix j i =
      C.realSymbolPhase hp_three hm
          (standardRealResiduesEquiv (p := p) i.succ *
            standardRealResiduesEquiv (p := p) j.castSucc) -
        C.realSymbolPhase hp_three hm
          (standardRealResiduesEquiv (p := p) j.castSucc) := by
  let row : (ZMod p)ˣ := standardUnit (p := p) j.castSucc
  let column : (ZMod p)ˣ := standardUnit (p := p) i.succ
  have hrow : C.rootAtExponent row = embeddingRoot C.root j := by
    simpa only [row, embeddingRoot, Fin.val_castSucc, Fin.val_succ]
      using C.rootAtExponent_standardUnit j.castSucc
  have hcolumn : (column : ZMod p).val = i.val + 2 := by
    dsimp only [column]
    rw [standardUnit_coe]
    exact ZMod.val_natCast_of_lt
      (Fermat.Irregular.CyclotomicPlacesPrime.standardExponent_lt
        (p := p) i.succ)
  have hproduct : C.rootAtExponent (row * column) =
      embeddingRoot C.root j ^ (i.val + 2) := by
    rw [C.rootAtExponent_mul, hrow, hcolumn]
  have hweight : C.exponentWeight h (row * column) /
      C.exponentWeight h row = C.root ^ (C.matrix j i).val := by
    rw [exponentWeight, exponentWeight, hproduct, hrow]
    calc
      evenSymbolWeight h (embeddingRoot C.root j ^ (i.val + 2)) /
          evenSymbolWeight h (embeddingRoot C.root j) =
          normalizedUnitValue C.root j i ^ (2 * h) :=
        (normalizedUnitValue_pow_two_mul_eq_weight_ratio
          C.hp2 C.root_isPrimitive j i).symm
      _ = normalizedUnitValue C.root j i ^ C.symbolExponent := by rw [hm]
      _ = C.root ^ (C.matrix j i).val := C.entry_certificate j i
  have hphase := C.exponentPhase_sub_eq_of_weight_ratio_eq_root_pow
    hm row (row * column) (C.matrix j i) hweight
  rw [standardRealResiduesEquiv_apply, standardRealResiduesEquiv_apply,
    standardRealResidue, standardRealResidue, ← QuotientGroup.mk_mul,
    C.realSymbolPhase_mk, C.realSymbolPhase_mk]
  simpa only [row, column, mul_comm] using hphase.symm

/-- The canonical Kummer column node is the standard real-residue orbit
point with representative `i + 2`. -/
theorem canonicalColumnNode_eq_standardRealResidue_succ
    [Fact (2 < p)] (hp_three : 3 ≤ p)
    (i : Fin (kummerLogRank p)) :
    canonicalColumnNode (p := p) hp_three i =
      standardRealResiduesEquiv (p := p) i.succ := by
  rw [standardRealResiduesEquiv_apply, standardRealResidue,
    canonicalColumnNode]
  apply congrArg QuotientGroup.mk
  apply Units.ext
  rw [standardUnit_coe]
  rfl

/-- The whole source-order certificate matrix is the transpose of the
basis-free real-residue phase cofactor. -/
theorem matrix_eq_transpose_inverseAlignedRealResidueCofactor
    (C : Certificate p q) [Fact (2 < p)] (hp_three : 3 ≤ p)
    (hm : C.symbolExponent = 2 * h) :
    C.matrix = Matrix.transpose
      (inverseAlignedRealResidueCofactor (C.realSymbolPhase hp_three hm)) := by
  ext j i
  rw [Matrix.transpose_apply,
    inverseAlignedRealResidueCofactor_apply]
  exact C.matrix_entry_eq_realSymbolPhase_difference hp_three hm j i

/-- The single standard real-residue point omitted by certificate rows. -/
def omittedStandardRealResidue (p : ℕ) [Fact p.Prime] [Fact (2 < p)] :
    RealResidueGroup p :=
  standardRealResiduesEquiv (p := p) (Fin.last (kummerLogRank p))

/-- Character weights on the `N - 1` certificate rows, normalized to vanish
at the omitted standard orbit point. -/
def certificateCharacterWeights [Fact (2 < p)]
    (chi : RealResidueGroup p →* (ZMod p)ˣ)
    (j : Fin (kummerLogRank p)) : ZMod p :=
  (((chi (standardRealResiduesEquiv (p := p) j.castSucc))⁻¹ :
      (ZMod p)ˣ) : ZMod p) -
    (((chi (omittedStandardRealResidue p))⁻¹ : (ZMod p)ˣ) : ZMod p)

/-- The actual weighted certificate detector is exactly the basis-free
deleted-orbit detector of its descended auxiliary phase. -/
theorem certificateDetector_eq_deletedOrbitDetector
    (C : Certificate p q) [Fact (2 < p)] (hp_three : 3 ≤ p)
    (hm : C.symbolExponent = 2 * h)
    (chi : RealResidueGroup p →* (ZMod p)ˣ)
    (e : Fin (kummerLogRank p) → ZMod p) :
    dotProduct (certificateCharacterWeights (p := p) chi)
        (C.matrix *ᵥ e) =
      deletedOrbitDetector chi (C.realSymbolPhase hp_three hm)
        (omittedStandardRealResidue p)
        (canonicalColumnNode (p := p) hp_three) e := by
  classical
  let phase := C.realSymbolPhase hp_three hm
  let base := omittedStandardRealResidue p
  let F : RealResidueGroup p → ZMod p := fun x ↦
    ((((chi x)⁻¹ : (ZMod p)ˣ) : ZMod p) -
        (((chi base)⁻¹ : (ZMod p)ˣ) : ZMod p)) *
      ∑ i : Fin (kummerLogRank p),
        (phase (x * canonicalColumnNode (p := p) hp_three i) - phase x) * e i
  change
    (∑ j : Fin (kummerLogRank p),
      certificateCharacterWeights (p := p) chi j *
        ∑ i : Fin (kummerLogRank p), C.matrix j i * e i) =
      ∑ x : RealResidueGroup p, F x
  rw [← Equiv.sum_comp (standardRealResiduesEquiv (p := p)) F,
    Fin.sum_univ_castSucc]
  have hlast : F (standardRealResiduesEquiv (p := p)
      (Fin.last (kummerLogRank p))) = 0 := by
    simp only [F, base, omittedStandardRealResidue, sub_self, zero_mul]
  rw [hlast, add_zero]
  apply Finset.sum_congr rfl
  intro j _
  rw [show certificateCharacterWeights (p := p) chi j =
      (((chi (standardRealResiduesEquiv (p := p) j.castSucc))⁻¹ :
        (ZMod p)ˣ) : ZMod p) -
        (((chi base)⁻¹ : (ZMod p)ˣ) : ZMod p) by rfl]
  congr 1
  apply Finset.sum_congr rfl
  intro i _
  rw [C.matrix_entry_eq_realSymbolPhase_difference hp_three hm,
    canonicalColumnNode_eq_standardRealResidue_succ hp_three]
  simp only [phase]
  rw [mul_comm (standardRealResiduesEquiv (p := p) j.castSucc)
    (standardRealResiduesEquiv (p := p) i.succ)]

/-- Universal certificate constructor: every split-prime circular-unit
certificate factors, without choosing a cyclic generator or coordinate
permutations, through the same intrinsic Kummer row. The only auxiliary-prime
datum remaining in the projection is the orbit Fourier scalar. -/
def basisFreeFactorization (C : Certificate p q) [Fact (2 < p)]
    (hp_three : 3 ≤ p) (hm : C.symbolExponent = 2 * h)
    (channelRow : Fin (kummerLogRank p)) :
    Factorization p q hp_three C channelRow where
  weights := certificateCharacterWeights (p := p)
    (evenPowerCharacter (p := p) hp_three channelRow)
  scalar := orbitScalar
    (evenPowerCharacter (p := p) hp_three channelRow)
    (C.realSymbolPhase hp_three hm)
  factors := by
    intro e
    rw [C.certificateDetector_eq_deletedOrbitDetector hp_three hm,
      deletedOrbitDetector_eq_orbitDetector,
      orbitDetector_evenPowerCharacter_eq_scalar_mul_canonicalKummerChannel]

/-- The universal factorization with the even half-exponent recovered
canonically from the certificate itself. -/
def canonicalBasisFreeFactorization (C : Certificate p q) [Fact (2 < p)]
    (hp_three : 3 ≤ p) (channelRow : Fin (kummerLogRank p)) :
    Factorization p q hp_three C channelRow :=
  C.basisFreeFactorization hp_three
    C.symbolExponent_eq_two_mul_symbolHalf channelRow

end Certificate

end

end Fermat.Irregular.CircularUnitResidues
