import Mathlib.GroupTheory.FiniteAbelian.Basic
import Mathlib.LinearAlgebra.Matrix.Adjugate

/-!
# Finite-index transport under an integer exponent matrix

Let a finite family `base` generate a finite-index subgroup of a
commutative group.  If a second family is obtained by applying a square
integer exponent matrix with nonzero determinant, then the second family
also generates a finite-index subgroup.

The proof is purely group-theoretic.  The adjugate identity shows that the
subgroup generated by the transformed family contains a fixed nonzero
power of every base generator.  The subgroup of those fixed powers has
finite relative index because the base subgroup is finitely generated.

This module deliberately has no number-field, cyclotomic, or certificate
imports.  It is intended for transporting finite-index unit-family facts
without reusing an auxiliary-prime determinant certificate.
-/

open scoped BigOperators

namespace Fermat.Irregular.FiniteIndexExponentTransform

private theorem prod_zpow_eq_zpow_sum
    {G ι : Type*} [CommGroup G] [DecidableEq ι]
    (x : G) (f : ι → ℤ) (s : Finset ι) :
    (∏ i ∈ s, x ^ f i) = x ^ (∑ i ∈ s, f i) := by
  induction s using Finset.induction_on with
  | empty => simp
  | @insert a s ha ih =>
      rw [Finset.prod_insert ha, Finset.sum_insert ha, ih, zpow_add]

private theorem exponent_transform_adjugate
    {G ι : Type*} [CommGroup G] [Fintype ι] [DecidableEq ι]
    (base target : ι → G) (A : Matrix ι ι ℤ)
    (htarget : ∀ i, target i = ∏ j, base j ^ A j i)
    (k : ι) :
    (∏ i, target i ^ A.adjugate i k) = base k ^ A.det := by
  calc
    (∏ i, target i ^ A.adjugate i k) =
        ∏ i, (∏ j, base j ^ A j i) ^ A.adjugate i k := by
      apply Finset.prod_congr rfl
      intro i _
      rw [htarget i]
    _ = ∏ i, ∏ j, (base j ^ A j i) ^ A.adjugate i k := by
      apply Finset.prod_congr rfl
      intro i _
      rw [← Finset.prod_zpow]
    _ = ∏ j, ∏ i, (base j ^ A j i) ^ A.adjugate i k := by
      rw [Finset.prod_comm]
    _ = ∏ j, base j ^ (∑ i, A j i * A.adjugate i k) := by
      apply Finset.prod_congr rfl
      intro j _
      simp_rw [← zpow_mul]
      exact prod_zpow_eq_zpow_sum (base j)
        (fun i ↦ A j i * A.adjugate i k) Finset.univ
    _ = ∏ j, base j ^ (A * A.adjugate) j k := by
      simp only [Matrix.mul_apply]
    _ = ∏ j, base j ^ (A.det • (1 : Matrix ι ι ℤ)) j k := by
      rw [A.mul_adjugate]
    _ = base k ^ A.det := by
      classical
      simp [Matrix.smul_apply, Matrix.one_apply]

/-- A nonsingular square integer exponent transform preserves finite-index
generation in a commutative group.

The matrix convention is column-oriented: `target i` has exponent
`A j i` on `base j`.  No assertion is made that either generated subgroup
has the same index as the other; only finiteness of the index is transported.
-/
theorem closure_range_finiteIndex_of_exponent_transform
    {G ι : Type*} [CommGroup G] [Fintype ι] [DecidableEq ι]
    (base target : ι → G) (A : Matrix ι ι ℤ)
    [hbase : (Subgroup.closure (Set.range base)).FiniteIndex]
    (htarget : ∀ i, target i = ∏ j, base j ^ A j i)
    (hdet : A.det ≠ 0) :
    (Subgroup.closure (Set.range target)).FiniteIndex := by
  let H : Subgroup G := Subgroup.closure (Set.range base)
  let L : Subgroup G := Subgroup.closure (Set.range target)
  let n : ℕ := A.det.natAbs
  let P : Subgroup G := H.map (powMonoidHom n)
  have hn : n ≠ 0 := by
    exact Int.natAbs_ne_zero.mpr hdet
  have hHfg : H.FG := by
    rw [Subgroup.fg_iff]
    exact ⟨Set.range base, rfl, Set.finite_range base⟩
  letI : P.IsFiniteRelIndex H := by
    exact Subgroup.isFiniteRelIndex_map_powMonoidHom_of_fg hHfg hn
  have hPH : P ≤ H := by
    rintro x ⟨y, hy, rfl⟩
    exact H.pow_mem hy n
  letI : P.FiniteIndex := by
    rw [Subgroup.finiteIndex_iff, ← Subgroup.relIndex_mul_index hPH]
    exact mul_ne_zero Subgroup.relIndex_ne_zero hbase.index_ne_zero
  apply Subgroup.finiteIndex_of_le (H := P)
  rw [Subgroup.map_le_iff_le_comap]
  change H ≤ Subgroup.comap (powMonoidHom n) L
  rw [show H = Subgroup.closure (Set.range base) by rfl,
    Subgroup.closure_le]
  rintro _ ⟨k, rfl⟩
  change base k ^ n ∈ L
  have hprod : (∏ i, target i ^ A.adjugate i k) ∈ L := by
    apply Subgroup.prod_mem
    intro i _
    exact L.zpow_mem (Subgroup.subset_closure ⟨i, rfl⟩) _
  have hdetPow : base k ^ A.det ∈ L := by
    rw [exponent_transform_adjugate base target A htarget k] at hprod
    exact hprod
  have hsign : (base k ^ A.det) ^ A.det.sign ∈ L :=
    L.zpow_mem hdetPow A.det.sign
  simpa only [← zpow_mul, mul_comm A.det A.det.sign,
    Int.sign_mul_self_eq_natAbs, zpow_natCast, n] using hsign

end Fermat.Irregular.FiniteIndexExponentTransform
