import Fermat.Descent.Irregular.TakagiReflectionPrime
import Fermat.Descent.Irregular.VandiverHistoricalPrime
import Fermat.Descent.Irregular.VandiverTakagiPairPrime
import Fermat.Descent.Irregular.VandiverEquationEightAFactorizationPrime
import Fermat.Descent.Irregular.VandiverEquationEightAGeneratorPrime
import Fermat.Descent.Irregular.VandiverEquationTenPrime

set_option maxRecDepth 50000

/-!
# Prime-generic Takagi step for prepared historical factors

This module isolates the common content of the exponent-`587` and
exponent-`691` historical Takagi files.  A prepared conjugate factor pair
records the two allocated ideals, their literal generators, the local
Kummer-primary congruence, and the conjugation congruence used to make the
coefficient in equation (8) real.

For every prime `p ≥ 5`, an explicitly supplied nondivisibility

`p ∤ h(K⁺)`

then gives:

* the historical equation (7a), through the conjugation-fixed Kummer
  extension and Hilbert 94;
* equation (7d), by the plus-class calculation;
* equation (8), by the prime-generic Bézout ideal argument; and
* a real coefficient unit, hence the full conjugate equation-(8) pair.

The finite Sinnott--Kummer certificate is deliberately not imported.
Concrete exponent modules pass its conclusion through
`PlusClassNondivisibility K p`.
-/

open scoped NumberField

namespace Fermat.Irregular.TakagiHistoricalPrime

noncomputable section

open Fermat.Irregular.VandiverLemmaOne
open Fermat.Irregular.VandiverCriterion
open Fermat.Irregular.VandiverHistoricalDescent
open Fermat.Irregular.VandiverHistoricalPrime
open Fermat.Irregular.VandiverHistoricalStatePrime
open Fermat.Irregular.VandiverEquationEightAFactorizationPrime
open Fermat.Irregular.VandiverEquationEightAGeneratorPrime
open Fermat.Irregular.VandiverHistoricalEquationEightAPrime
open Fermat.Irregular.VandiverEquationTenPrime
open Fermat.Irregular.VandiverTakagiPairPrime
open Fermat.Irregular.TakagiReflectionPrime

variable {K : Type} {p : ℕ} [Fact p.Prime]
  [Field K] [NumberField K] [NumberField.IsCMField K]
  [IsCyclotomicExtension {p} ℚ K]

local notation3 "K⁺" => NumberField.maximalRealSubfield K

/-! ## Preparing the literal historical conjugate factors -/

/-- The fixed-denominator conjugate linear factor at `ζ⁻¹`. -/
noncomputable def historicalInverseZetaFactor
    (hp2 : p ≠ 2)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ) : 𝓞 K :=
  div_zeta_sub_one hp2 hζ
    (historicalState_regularEquation hζ s)
    (inverseZetaNthRoot (K := K) (p := p) hζ)

/-- The inverse factor normalized to be the literal conjugate of the
factor at `ζ`. -/
noncomputable def normalizedHistoricalInverseZetaFactor
    (hp2 : p ≠ 2)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ) : 𝓞 K :=
  ((-hζ.unit' : (𝓞 K)ˣ) : 𝓞 K) *
    historicalInverseZetaFactor hp2 hζ s

/-- The allocated ideal root of the conjugate factor at `ζ⁻¹`. -/
noncomputable def historicalInverseZetaFactorIdeal
    (hp2 : p ≠ 2)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ) : Ideal (𝓞 K) :=
  root_div_zeta_sub_one_dvd_gcd hp2 hζ
    (historicalState_regularEquation hζ s)
    (historicalState_theta_not_dvd hζ s)
    (inverseZetaNthRoot (K := K) (p := p) hζ)

/-- Multiplying the prepared factor at `ζ` by its fixed denominator
recovers the corresponding historical linear factor. -/
theorem historicalZetaFactor_mul_zeta_sub_one
    (hp2 : p ≠ 2)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ) :
    historicalZetaFactor hp2 hζ s *
        ((hζ.unit' : 𝓞 K) - 1) =
      s.omega + s.theta * (hζ.unit' : 𝓞 K) := by
  exact
    div_zeta_sub_one_mul_zeta_sub_one
      hp2 hζ
      (historicalState_regularEquation hζ s)
      (zetaNthRoot (K := K) (p := p) hζ)

set_option maxRecDepth 50000 in
/-- The allocated inverse ideal has `p`-th power generated by the
unit-normalized inverse factor. -/
theorem historicalInverseZetaFactorIdeal_pow
    (hp2 : p ≠ 2)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ) :
    historicalInverseZetaFactorIdeal hp2 hζ s ^ p =
      Ideal.span
        {normalizedHistoricalInverseZetaFactor hp2 hζ s} := by
  calc
    historicalInverseZetaFactorIdeal hp2 hζ s ^ p =
        Ideal.span {historicalInverseZetaFactor hp2 hζ s} :=
      (linearFactorQuotient_span_eq_factorRoot_pow
        hp2 hζ
        (historicalState_regularEquation hζ s)
        (historicalState_theta_not_dvd hζ s)
        s.coprime_omega_theta
        (inverseZetaNthRoot (K := K) (p := p) hζ)).symm
    _ =
        Ideal.span
          {normalizedHistoricalInverseZetaFactor hp2 hζ s} :=
      Ideal.span_singleton_eq_span_singleton.mpr
        (associated_unit_mul_right _ _ (-hζ.unit').isUnit)

/-- The full historical depth contains the `p+1` powers needed by the
local conjugate-factor comparison. -/
theorem historicalState_omega_add_theta_primaryDepth
    (hp5 : 5 ≤ p)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ)
    (hs : RealSourceAdmissible hζ s) :
    ((hζ.unit' : 𝓞 K) - 1) ^ (p + 1) ∣
      s.omega + s.theta := by
  have hfull :=
    historicalState_omega_add_theta_fullHighDivisibility
      (by omega : p ≠ 2) hζ s hs
  exact
    (pow_dvd_pow_of_dvd_of_le
      (dvd_refl ((hζ.unit' : 𝓞 K) - 1))
      (by
        have hm := s.one_lt_m
        have hcoef : 1 ≤ 2 * s.m - 1 := by omega
        have hpmul : p ≤ (2 * s.m - 1) * p := by
          simpa only [one_mul] using Nat.mul_le_mul_right p hcoef
        omega :
        p + 1 ≤ (2 * s.m - 1) * p + 1)).trans hfull

/-- Complex conjugation sends the fixed-denominator factor at `ζ`
exactly to the normalized inverse factor. -/
theorem ringOfIntegersComplexConj_historicalZetaFactor
    (hp2 : p ≠ 2)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ)
    (hs : RealSourceAdmissible hζ s) :
    NumberField.IsCMField.ringOfIntegersComplexConj K
        (historicalZetaFactor hp2 hζ s) =
      normalizedHistoricalInverseZetaFactor hp2 hζ s := by
  let π : 𝓞 K := (hζ.unit' : 𝓞 K) - 1
  let qplus : 𝓞 K := historicalZetaFactor hp2 hζ s
  let qminus : 𝓞 K :=
    historicalInverseZetaFactor hp2 hζ s
  let u : (𝓞 K)ˣ := -hζ.unit'⁻¹
  have hπ0 : π ≠ 0 :=
    hζ.unit'_coe.sub_one_ne_zero
      (Fact.out : Nat.Prime p).one_lt
  have hconjζ :
      NumberField.IsCMField.ringOfIntegersComplexConj K
          (hζ.unit' : 𝓞 K) =
        (hζ.unit'⁻¹ : (𝓞 K)ˣ) :=
    congrArg ((↑) : (𝓞 K)ˣ → 𝓞 K)
      (Fermat.Irregular.VandiverRealNormalizationPrime.unitsComplexConj_zeta
        hζ)
  have hconjπ :
      NumberField.IsCMField.ringOfIntegersComplexConj K π =
        (u : 𝓞 K) * π := by
    dsimp [π, u]
    rw [map_sub, map_one, hconjζ]
    have hinv :
        (hζ.unit'⁻¹ : (𝓞 K)ˣ) *
            (hζ.unit' : 𝓞 K) = 1 := by
      rw [← Units.val_mul]
      simp
    simp only [neg_mul, mul_sub, hinv]
    ring
  have hqplusMul :
      qplus * π =
        s.omega + s.theta * (hζ.unit' : 𝓞 K) := by
    exact div_zeta_sub_one_mul_zeta_sub_one
      hp2 hζ
      (historicalState_regularEquation hζ s)
      (zetaNthRoot (K := K) (p := p) hζ)
  have hqminusMul :
      qminus * π =
        s.omega + s.theta *
          (hζ.unit'⁻¹ : (𝓞 K)ˣ) := by
    exact div_zeta_sub_one_mul_zeta_sub_one
      hp2 hζ
      (historicalState_regularEquation hζ s)
      (inverseZetaNthRoot (K := K) (p := p) hζ)
  have hconjFactor := congrArg
    (NumberField.IsCMField.ringOfIntegersComplexConj K)
      hqplusMul
  rw [map_mul, map_add, map_mul, hs.1, hs.2.1,
    hconjζ, hconjπ] at hconjFactor
  have hquotient :
      NumberField.IsCMField.ringOfIntegersComplexConj K qplus *
          (u : 𝓞 K) =
        qminus := by
    apply mul_right_cancel₀ hπ0
    calc
      (NumberField.IsCMField.ringOfIntegersComplexConj K qplus *
          (u : 𝓞 K)) * π =
          NumberField.IsCMField.ringOfIntegersComplexConj K qplus *
            ((u : 𝓞 K) * π) := by ring
      _ = s.omega + s.theta *
          (hζ.unit'⁻¹ : (𝓞 K)ˣ) :=
        hconjFactor
      _ = qminus * π := hqminusMul.symm
  have huinv : u⁻¹ = -hζ.unit' := by
    dsimp [u]
    simp
  change
    NumberField.IsCMField.ringOfIntegersComplexConj K qplus =
      ((-hζ.unit' : (𝓞 K)ˣ) : 𝓞 K) * qminus
  calc
    NumberField.IsCMField.ringOfIntegersComplexConj K qplus =
        (NumberField.IsCMField.ringOfIntegersComplexConj K qplus *
          (u : 𝓞 K)) * (u⁻¹ : (𝓞 K)ˣ) := by
      rw [mul_assoc, ← Units.val_mul]
      simp
    _ = qminus * (u⁻¹ : (𝓞 K)ˣ) := by rw [hquotient]
    _ = ((-hζ.unit' : (𝓞 K)ˣ) : 𝓞 K) * qminus := by
      rw [huinv]
      ring

/-- The literal normalized conjugate product is Kummer-primary in every
admissible historical state. -/
theorem historicalConjugateFactorProduct_isKummerPrimary
    (hp5 : 5 ≤ p)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ)
    (hs : RealSourceAdmissible hζ s) :
    IsKummerPrimary hζ
      (historicalZetaFactor (by omega : p ≠ 2) hζ s *
        normalizedHistoricalInverseZetaFactor
          (by omega : p ≠ 2) hζ s ^ (p - 1)) := by
  simpa only [historicalZetaFactor,
    normalizedHistoricalInverseZetaFactor,
    historicalInverseZetaFactor] using
    normalizedConjugateLinearFactor_isKummerPrimary
      (by omega : p ≠ 2) hζ
      (historicalState_regularEquation hζ s)
      (historicalState_theta_not_dvd hζ s)
      (historicalState_omega_add_theta_primaryDepth
        hp5 hζ s hs)

/-- The factor at `ζ` agrees with its conjugate modulo
`(ζ - 1)^p`. -/
theorem historicalZetaFactor_sub_conj_highDivisibility
    (hp5 : 5 ≤ p)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ)
    (hs : RealSourceAdmissible hζ s) :
    ((hζ.unit' : 𝓞 K) - 1) ^ p ∣
      historicalZetaFactor (by omega : p ≠ 2) hζ s -
        NumberField.IsCMField.ringOfIntegersComplexConj K
          (historicalZetaFactor (by omega : p ≠ 2) hζ s) := by
  have hlocal :=
    normalizedConjugateLinearFactors
      (by omega : p ≠ 2) hζ
      (historicalState_regularEquation hζ s)
      (historicalState_theta_not_dvd hζ s)
      (historicalState_omega_add_theta_primaryDepth
        hp5 hζ s hs)
  rw [ringOfIntegersComplexConj_historicalZetaFactor
    (by omega : p ≠ 2) hζ s hs]
  simpa only [historicalZetaFactor,
    historicalInverseZetaFactor,
    normalizedHistoricalInverseZetaFactor] using hlocal.2.2

/-- The maximal prepared input shared by the historical equation-(7a)
and equation-(8) arguments.

The fields before `plusFactor_sub_conj_high` are exactly the conjugate
ideal pair to which Takagi--Furtwängler reflection applies.  The final
field is elementary local compatibility; it is needed only to make the
coefficient unit in equation (8) literally real. -/
structure PreparedHistoricalEquationData
    {ζ : K} (hζ : IsPrimitiveRoot ζ p) where
  plusIdeal : Ideal (𝓞 K)
  minusIdeal : Ideal (𝓞 K)
  plusFactor : 𝓞 K
  minusFactor : 𝓞 K
  plusIdeal_pow :
    plusIdeal ^ p = Ideal.span {plusFactor}
  minusIdeal_pow :
    minusIdeal ^ p = Ideal.span {minusFactor}
  factor_conjugate :
    NumberField.IsCMField.ringOfIntegersComplexConj K plusFactor =
      minusFactor
  primary :
    IsKummerPrimary hζ
      (plusFactor * minusFactor ^ (p - 1))
  plusFactor_sub_conj_high :
    ((hζ.unit' : 𝓞 K) - 1) ^ p ∣
      plusFactor -
        NumberField.IsCMField.ringOfIntegersComplexConj K plusFactor

/-- Every admissible historical state canonically supplies the prepared
conjugate factor package.  No class-number input occurs here. -/
noncomputable def preparedHistoricalEquationData
    (hp5 : 5 ≤ p)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ)
    (hs : RealSourceAdmissible hζ s) :
    PreparedHistoricalEquationData hζ where
  plusIdeal :=
    historicalZetaFactorIdeal (by omega : p ≠ 2) hζ s
  minusIdeal :=
    historicalInverseZetaFactorIdeal
      (by omega : p ≠ 2) hζ s
  plusFactor :=
    historicalZetaFactor (by omega : p ≠ 2) hζ s
  minusFactor :=
    normalizedHistoricalInverseZetaFactor
      (by omega : p ≠ 2) hζ s
  plusIdeal_pow :=
    historicalZetaFactorIdeal_pow
      (by omega : p ≠ 2) hζ s
  minusIdeal_pow :=
    historicalInverseZetaFactorIdeal_pow
      (by omega : p ≠ 2) hζ s
  factor_conjugate :=
    ringOfIntegersComplexConj_historicalZetaFactor
      (by omega : p ≠ 2) hζ s hs
  primary :=
    historicalConjugateFactorProduct_isKummerPrimary
      hp5 hζ s hs
  plusFactor_sub_conj_high :=
    historicalZetaFactor_sub_conj_highDivisibility
      hp5 hζ s hs

namespace PreparedHistoricalEquationData

variable {ζ : K} (hζ : IsPrimitiveRoot ζ p)
  (d : PreparedHistoricalEquationData hζ)

/-- Vandiver's historical equation (7a), discharged by the explicit
conjugation-fixed Kummer reflection theorem. -/
theorem exists_equationSevenA
    (hp2 : p ≠ 2)
    (hplus : PlusClassNondivisibility K p) :
    ∃ r : 𝓞 K,
      d.plusIdeal * d.minusIdeal ^ (p - 1) =
        Ideal.span {r} := by
  exact
    exists_conjugatePairEquationSevenAGenerator
      hp2 hζ hplus
      d.plusIdeal d.minusIdeal d.plusFactor d.minusFactor
      d.plusIdeal_pow d.minusIdeal_pow d.factor_conjugate d.primary

set_option maxRecDepth 50000 in
/-- Equation (7d) for the prepared conjugate ideal pair.

The plus-class calculation principalizes the relative norm of the first
ideal.  Conjugacy of the two displayed factors then identifies that norm
with the product of the prepared ideals. -/
theorem exists_equationSevenD
    (hplus : PlusClassNondivisibility K p) :
    ∃ r : 𝓞 K,
      d.plusIdeal * d.minusIdeal = Ideal.span {r} := by
  let I : Ideal (𝓞 K) := d.plusIdeal
  let J : Ideal (𝓞 K) := d.minusIdeal
  let a : 𝓞 K := d.plusFactor
  let b : 𝓞 K := d.minusFactor
  have hIpow : I ^ p = Ideal.span {a} := by
    simpa only [I, a] using d.plusIdeal_pow
  have hJpow : J ^ p = Ideal.span {b} := by
    simpa only [J, b] using d.minusIdeal_pow
  have hbconj :
      NumberField.IsCMField.ringOfIntegersComplexConj K a = b := by
    simpa only [a, b] using d.factor_conjugate
  obtain ⟨ρ, ε, -, -, hnorm⟩ :=
    exists_equationSevenD_of_idealPower
      hplus I a hIpow
  let ρK : 𝓞 K := algebraMap (𝓞 K⁺) (𝓞 K) ρ
  let εK : (𝓞 K)ˣ :=
    Units.map (algebraMap (𝓞 K⁺) (𝓞 K)).toMonoidHom ε
  have hnorm' : a * b = (εK : 𝓞 K) * ρK ^ p := by
    rw [← hbconj]
    change
      a * NumberField.IsCMField.ringOfIntegersComplexConj K a =
        algebraMap (𝓞 K⁺) (𝓞 K) (ε : 𝓞 K⁺) *
          (algebraMap (𝓞 K⁺) (𝓞 K) ρ) ^ p
    exact hnorm
  have hpow :
      (I * J) ^ p = (Ideal.span {ρK}) ^ p := by
    calc
      (I * J) ^ p = I ^ p * J ^ p := by rw [mul_pow]
      _ = Ideal.span {a} * Ideal.span {b} := by rw [hIpow, hJpow]
      _ = Ideal.span {a * b} :=
        Ideal.span_singleton_mul_span_singleton a b
      _ = Ideal.span {(εK : 𝓞 K) * ρK ^ p} := by rw [hnorm']
      _ = Ideal.span {ρK ^ p} :=
        Ideal.span_singleton_eq_span_singleton.mpr
          (associated_unit_mul_left _ _ εK.isUnit)
      _ = (Ideal.span {ρK}) ^ p :=
        (Ideal.span_singleton_pow ρK p).symm
  exact
    ⟨ρK,
      pow_left_injective (M := Ideal (𝓞 K))
        (Fact.out : Nat.Prime p).ne_zero hpow⟩

/-- The prepared factor ideals are nonzero.  This follows directly from
the primeness-to-`ζ-1` clause of Kummer primarity. -/
theorem ideals_ne_zero :
    d.plusIdeal ≠ 0 ∧ d.minusIdeal ≠ 0 := by
  have hab0 :
      d.plusFactor * d.minusFactor ^ (p - 1) ≠ 0 := by
    intro hzero
    apply d.primary.1
    rw [hzero]
    exact dvd_zero _
  have ha0 : d.plusFactor ≠ 0 :=
    left_ne_zero_of_mul hab0
  have hbpow0 : d.minusFactor ^ (p - 1) ≠ 0 :=
    right_ne_zero_of_mul hab0
  have hb0 : d.minusFactor ≠ 0 := by
    intro hzero
    apply hbpow0
    rw [hzero]
    have hp1 : p - 1 ≠ 0 := by
      have hp := (Fact.out : Nat.Prime p).one_lt
      omega
    exact zero_pow hp1
  have hspanA :
      Ideal.span {d.plusFactor} ≠ (0 : Ideal (𝓞 K)) := by
    simpa only [ne_eq, Ideal.zero_eq_bot,
      Ideal.span_singleton_eq_bot] using ha0
  have hspanB :
      Ideal.span {d.minusFactor} ≠ (0 : Ideal (𝓞 K)) := by
    simpa only [ne_eq, Ideal.zero_eq_bot,
      Ideal.span_singleton_eq_bot] using hb0
  constructor
  · intro hzero
    apply hspanA
    rw [← d.plusIdeal_pow, hzero]
    exact zero_pow (Fact.out : Nat.Prime p).ne_zero
  · intro hzero
    apply hspanB
    rw [← d.minusIdeal_pow, hzero]
    exact zero_pow (Fact.out : Nat.Prime p).ne_zero

set_option maxRecDepth 50000 in
/-- Vandiver's equation (8) for a prepared historical factor pair.

Both uses of the class group are exposed through the single explicit
plus-class nondivisibility hypothesis. -/
theorem exists_equationEight
    (hp5 : 5 ≤ p)
    (hplus : PlusClassNondivisibility K p) :
    ∃ (ρ : 𝓞 K) (η : (𝓞 K)ˣ),
      d.plusIdeal = Ideal.span {ρ} ∧
      d.plusFactor = η * ρ ^ p := by
  have hp2 : p ≠ 2 := by omega
  obtain ⟨r, hsevenA⟩ :=
    d.exists_equationSevenA hζ hp2 hplus
  obtain ⟨t, hsevenD⟩ :=
    d.exists_equationSevenD hζ hplus
  obtain ⟨hI0, hJ0⟩ := d.ideals_ne_zero hζ
  exact
    exists_equationEight_of_sevenASevenD hp5
      d.plusIdeal d.minusIdeal d.plusFactor d.minusFactor
      r t hI0 hJ0 d.plusIdeal_pow d.minusIdeal_pow
      hsevenA hsevenD

end PreparedHistoricalEquationData

/-! ## Prime-generic reality of the equation-(8) coefficient -/

/-- Every `p`-th power is fixed by complex conjugation modulo
`(ζ - 1)^p`. -/
lemma zeta_sub_one_pow_dvd_pow_sub_conj_pow
    {ζ : K} (hζ : IsPrimitiveRoot ζ p) (a : 𝓞 K) :
    ((hζ.unit' : 𝓞 K) - 1) ^ p ∣
      a ^ p -
        NumberField.IsCMField.ringOfIntegersComplexConj K a ^ p := by
  obtain ⟨c, hc⟩ := exists_int_pow_congruent_mod_primary hζ a
  have hcconj :=
    zeta_sub_one_pow_dvd_conj_of_dvd hζ p
      (a ^ p - (c : 𝓞 K) ^ p) hc
  have hcconj' :
      ((hζ.unit' : 𝓞 K) - 1) ^ p ∣
        NumberField.IsCMField.ringOfIntegersComplexConj K a ^ p -
          (c : 𝓞 K) ^ p := by
    simpa only [map_sub, map_pow, map_intCast] using hcconj
  convert dvd_sub hc hcconj' using 1
  ring

/-- A `p`-th root of unity which is `1` modulo `(ζ - 1)^2` is
literally `1`. -/
lemma zeta_pow_sq_eq_one_of_zeta_sub_one_sq_dvd
    {ζ : K} (hζ : IsPrimitiveRoot ζ p) (j : ℕ)
    (hdiv :
      ((hζ.unit' : 𝓞 K) - 1) ^ 2 ∣
        ((((hζ.unit' ^ j) ^ 2 : (𝓞 K)ˣ) : 𝓞 K) - 1)) :
    (hζ.unit' ^ j) ^ 2 = 1 := by
  let k : ℕ := (2 * j) % p
  have hklt : k < p := by
    dsimp [k]
    exact Nat.mod_lt _ (Fact.out : Nat.Prime p).pos
  have hpowmod :
      ((((hζ.unit' ^ j) ^ 2 : (𝓞 K)ˣ) : 𝓞 K)) =
        (hζ.unit' : 𝓞 K) ^ k := by
    simp only [Units.val_pow_eq_pow_val]
    rw [← pow_mul]
    have hmod := pow_mod_orderOf (hζ.unit' : 𝓞 K) (2 * j)
    rw [← hζ.unit'_coe.eq_orderOf] at hmod
    simpa only [k, mul_comm] using hmod.symm
  by_cases hk : k = 0
  · apply Units.ext
    change ((((hζ.unit' ^ j) ^ 2 : (𝓞 K)ˣ) : 𝓞 K)) = 1
    rw [hpowmod, hk, pow_zero]
  · have hknotdvd : ¬ p ∣ k := by
      intro h
      have hle : p ≤ k :=
        Nat.le_of_dvd (Nat.pos_of_ne_zero hk) h
      omega
    have hkcoprime : k.Coprime p := by
      apply Nat.coprime_comm.mpr
      exact
        (Fact.out : Nat.Prime p).coprime_iff_not_dvd.mpr hknotdvd
    have hassoc :
        Associated
          ((hζ.unit' : 𝓞 K) - 1)
          ((hζ.unit' : 𝓞 K) ^ k - 1) :=
      hζ.unit'_coe.associated_sub_one_pow_sub_one_of_coprime
        hkcoprime
    have hsquare :
        ((hζ.unit' : 𝓞 K) - 1) ^ 2 ∣
          (hζ.unit' : 𝓞 K) - 1 :=
      hassoc.dvd_iff_dvd_right.mpr
        (by simpa only [hpowmod] using hdiv)
    obtain ⟨c, hc⟩ := hsquare
    have hπ0 : (hζ.unit' : 𝓞 K) - 1 ≠ 0 :=
      hζ.unit'_coe.sub_one_ne_zero
        (Fact.out : Nat.Prime p).one_lt
    have hone :
        (1 : 𝓞 K) = ((hζ.unit' : 𝓞 K) - 1) * c := by
      apply mul_left_cancel₀ hπ0
      calc
        ((hζ.unit' : 𝓞 K) - 1) * 1 =
            (hζ.unit' : 𝓞 K) - 1 := by ring
        _ = ((hζ.unit' : 𝓞 K) - 1) ^ 2 * c := hc
        _ = ((hζ.unit' : 𝓞 K) - 1) *
            (((hζ.unit' : 𝓞 K) - 1) * c) := by ring
    exact False.elim <| hζ.zeta_sub_one_prime'.not_unit
      (isUnit_iff_dvd_one.mpr ⟨c, hone⟩)

/-- A cyclotomic unit whose conjugation defect is divisible by
`(ζ - 1)^2` is real. -/
lemma unit_fixed_of_zeta_sub_one_sq_dvd_sub_conj
    (hp2 : 2 < p)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p) (u : (𝓞 K)ˣ)
    (hdiv :
      ((hζ.unit' : 𝓞 K) - 1) ^ 2 ∣
        (u : 𝓞 K) -
          NumberField.IsCMField.ringOfIntegersComplexConj K
            (u : 𝓞 K)) :
    NumberField.IsCMField.unitsComplexConj K u = u := by
  obtain ⟨j, hj⟩ :=
    unit_inv_conj_is_root_of_unity hζ u hp2
  let cu : (𝓞 K)ˣ :=
    NumberField.IsCMField.unitsComplexConj K u
  have hcu :
      NumberField.IsCMField.ringOfIntegersComplexConj K (u : 𝓞 K) =
        (cu : 𝓞 K) := by
    apply NumberField.RingOfIntegers.ext
    rfl
  let r : (𝓞 K)ˣ := (hζ.unit' ^ j) ^ 2
  have hu : u = r * cu := by
    calc
      u = (u * cu⁻¹) * cu := by simp
      _ = r * cu := by
        simpa only [cu, r] using congrArg (· * cu) hj
  have hu' := congrArg ((↑) : (𝓞 K)ˣ → 𝓞 K) hu
  have hfactor :
      (u : 𝓞 K) - (cu : 𝓞 K) =
        (((((hζ.unit' ^ j) ^ 2 : (𝓞 K)ˣ) : 𝓞 K) - 1) *
          (cu : 𝓞 K)) := by
    change
      (u : 𝓞 K) - (cu : 𝓞 K) =
        ((r : 𝓞 K) - 1) * (cu : 𝓞 K)
    rw [hu']
    simp only [Units.val_mul]
    ring
  have hassoc :
      Associated
        (((((hζ.unit' ^ j) ^ 2 : (𝓞 K)ˣ) : 𝓞 K)) - 1)
        ((u : 𝓞 K) - (cu : 𝓞 K)) :=
    ⟨cu, by simpa only [hfactor]⟩
  have hrootdiv :
      ((hζ.unit' : 𝓞 K) - 1) ^ 2 ∣
        (((((hζ.unit' ^ j) ^ 2 : (𝓞 K)ˣ) : 𝓞 K)) - 1) :=
    hassoc.dvd_iff_dvd_right.mpr (hcu ▸ hdiv)
  have hroot :=
    zeta_pow_sq_eq_one_of_zeta_sub_one_sq_dvd hζ j hrootdiv
  rw [hroot] at hj
  have hucu : u = cu := by
    calc
      u = (u * cu⁻¹) * cu := by simp
      _ = 1 * cu := by rw [hj]
      _ = cu := by simp
  exact hucu.symm

namespace PreparedHistoricalEquationData

variable {ζ : K} (hζ : IsPrimitiveRoot ζ p)
  (d : PreparedHistoricalEquationData hζ)

set_option maxRecDepth 50000 in
/-- The coefficient unit in equation (8) is fixed by complex
conjugation. -/
theorem equationEight_unit_real
    (hp5 : 5 ≤ p)
    (ρ : 𝓞 K) (η : (𝓞 K)ˣ)
    (heq : d.plusFactor = η * ρ ^ p) :
    NumberField.IsCMField.unitsComplexConj K η = η := by
  let π : 𝓞 K := (hζ.unit' : 𝓞 K) - 1
  have hqnot : ¬ π ∣ d.plusFactor := by
    intro hq
    apply d.primary.1
    exact dvd_mul_of_dvd_left hq _
  have hρnot : ¬ π ∣ ρ := by
    intro hρ
    apply hqnot
    rw [heq]
    exact dvd_mul_of_dvd_right
      (dvd_pow (n := p) hρ (Fact.out : Nat.Prime p).ne_zero) _
  have hρpowNot : ¬ π ∣ ρ ^ p := by
    intro h
    exact hρnot
      ((hζ.zeta_sub_one_prime'.dvd_pow_iff_dvd
        (Fact.out : Nat.Prime p).ne_zero).mp h)
  have hq2 :
      π ^ 2 ∣
        d.plusFactor -
          NumberField.IsCMField.ringOfIntegersComplexConj K
            d.plusFactor := by
    exact
      (pow_dvd_pow_of_dvd_of_le
        (dvd_refl π) (by omega : 2 ≤ p)).trans
        (by simpa only [π] using d.plusFactor_sub_conj_high)
  have hρp :=
    zeta_sub_one_pow_dvd_pow_sub_conj_pow hζ ρ
  have hρ2 :
      π ^ 2 ∣
        ρ ^ p -
          NumberField.IsCMField.ringOfIntegersComplexConj K ρ ^ p := by
    exact
      (pow_dvd_pow_of_dvd_of_le
        (dvd_refl π) (by omega : 2 ≤ p)).trans
        (by simpa only [π] using hρp)
  have herror :
      π ^ 2 ∣
        NumberField.IsCMField.ringOfIntegersComplexConj K
            (η : 𝓞 K) *
          (ρ ^ p -
            NumberField.IsCMField.ringOfIntegersComplexConj K ρ ^ p) :=
    dvd_mul_of_dvd_right hρ2 _
  have hmul :
      π ^ 2 ∣
        ((η : 𝓞 K) -
          NumberField.IsCMField.ringOfIntegersComplexConj K
            (η : 𝓞 K)) *
          ρ ^ p := by
    have h := dvd_sub hq2 herror
    convert h using 1
    rw [heq]
    simp only [map_mul, map_pow]
    ring
  have hunit :
      π ^ 2 ∣
        (η : 𝓞 K) -
          NumberField.IsCMField.ringOfIntegersComplexConj K
            (η : 𝓞 K) := by
    let e : 𝓞 K :=
      (η : 𝓞 K) -
        NumberField.IsCMField.ringOfIntegersComplexConj K
          (η : 𝓞 K)
    have hπ0 : π ≠ 0 :=
      hζ.unit'_coe.sub_one_ne_zero
        (Fact.out : Nat.Prime p).one_lt
    have hπmul : π ∣ e * ρ ^ p :=
      (dvd_pow_self π (by norm_num : 2 ≠ 0)).trans
        (by simpa only [e] using hmul)
    have he : π ∣ e := by
      rcases hζ.zeta_sub_one_prime'.dvd_mul.mp hπmul with he | hρ
      · exact he
      · exact False.elim (hρpowNot hρ)
    obtain ⟨e₁, he₁⟩ := he
    obtain ⟨c, hc⟩ := hmul
    have hcancel : e₁ * ρ ^ p = π * c := by
      apply mul_left_cancel₀ hπ0
      calc
        π * (e₁ * ρ ^ p) = e * ρ ^ p := by rw [he₁]; ring
        _ = π ^ 2 * c := hc
        _ = π * (π * c) := by ring
    have he₁div : π ∣ e₁ := by
      have hπe₁ : π ∣ e₁ * ρ ^ p := ⟨c, hcancel⟩
      rcases hζ.zeta_sub_one_prime'.dvd_mul.mp hπe₁ with he₁ | hρ
      · exact he₁
      · exact False.elim (hρpowNot hρ)
    obtain ⟨e₂, he₂⟩ := he₁div
    refine ⟨e₂, ?_⟩
    change e = π ^ 2 * e₂
    rw [he₁, he₂]
    ring
  exact
    unit_fixed_of_zeta_sub_one_sq_dvd_sub_conj
      (by omega : 2 < p) hζ η
      (by simpa only [π] using hunit)

set_option maxRecDepth 50000 in
/-- Equation (8) with a coefficient unit fixed by complex conjugation. -/
theorem exists_equationEight_realUnit
    (hp5 : 5 ≤ p)
    (hplus : PlusClassNondivisibility K p) :
    ∃ (ρ : 𝓞 K) (η : (𝓞 K)ˣ),
      d.plusIdeal = Ideal.span {ρ} ∧
      d.plusFactor = η * ρ ^ p ∧
      NumberField.IsCMField.unitsComplexConj K η = η := by
  obtain ⟨ρ, η, hI, heq⟩ :=
    d.exists_equationEight hζ hp5 hplus
  exact
    ⟨ρ, η, hI, heq,
      d.equationEight_unit_real hζ hp5 ρ η heq⟩

set_option maxRecDepth 50000 in
/-- A prepared factor identity upgrades equation (8) to its complete
conjugate pair at `ζ` and `ζ⁻¹`.

The theorem is independent of the origin of `omega` and `theta`; a
historical state supplies the three displayed hypotheses directly. -/
theorem exists_conjugateEquationEightPair
    (hp5 : 5 ≤ p)
    (hplus : PlusClassNondivisibility K p)
    {omega theta : 𝓞 K}
    (homega :
      NumberField.IsCMField.ringOfIntegersComplexConj K omega = omega)
    (htheta :
      NumberField.IsCMField.ringOfIntegersComplexConj K theta = theta)
    (hfactor :
      d.plusFactor * ((hζ.unit' : 𝓞 K) - 1) =
        omega + theta * (hζ.unit' : 𝓞 K)) :
    Nonempty
      (ConjugateEquationEightPair
        hζ omega theta hζ.unit') := by
  obtain ⟨ρ, η₀, -, heq, hη₀real⟩ :=
    d.exists_equationEight_realUnit hζ hp5 hplus
  let η : (𝓞 K)ˣ := -η₀
  have hηreal :
      NumberField.IsCMField.unitsComplexConj K η = η := by
    apply Units.ext
    change
      NumberField.IsCMField.ringOfIntegersComplexConj K
          (-(η₀ : 𝓞 K)) =
        -(η₀ : 𝓞 K)
    rw [map_neg]
    exact congrArg Neg.neg
      (congrArg ((↑) : (𝓞 K)ˣ → 𝓞 K) hη₀real)
  have hplusEquation :
      omega + (hζ.unit' : 𝓞 K) * theta =
        (1 - (hζ.unit' : 𝓞 K)) * η * ρ ^ p := by
    calc
      omega + (hζ.unit' : 𝓞 K) * theta =
          omega + theta * (hζ.unit' : 𝓞 K) := by ring
      _ = d.plusFactor * ((hζ.unit' : 𝓞 K) - 1) :=
        hfactor.symm
      _ = ((η₀ : 𝓞 K) * ρ ^ p) *
          ((hζ.unit' : 𝓞 K) - 1) := by rw [heq]
      _ = (1 - (hζ.unit' : 𝓞 K)) * η * ρ ^ p := by
        dsimp [η]
        ring
  have hqnot :
      ¬ (hζ.unit' : 𝓞 K) - 1 ∣ d.plusFactor := by
    intro hq
    apply d.primary.1
    exact dvd_mul_of_dvd_left hq _
  have hρnot :
      ¬ (hζ.unit' : 𝓞 K) - 1 ∣ ρ := by
    intro hρ
    apply hqnot
    rw [heq]
    exact dvd_mul_of_dvd_right
      (dvd_pow (n := p) hρ (Fact.out : Nat.Prime p).ne_zero) _
  have hpair :=
    conjugateEquationEightPair_of_zetaPow_plus
      hζ 1 η homega htheta hηreal
      (by simpa only [pow_one] using hplusEquation)
      hρnot
  simpa only [pow_one] using hpair

end PreparedHistoricalEquationData

/-! ## The distinguished real equation (8a) -/

set_option maxRecDepth 50000 in
/-- Historical equation (8a), including exactly the squared conjugation
data used in equation (10).

The same explicit plus-class witness principalizes the real residual
ideal; no assumption that its generator is prime to `ζ-1` is needed. -/
theorem exists_historicalEquationEightA
    (hplus : PlusClassNondivisibility K p)
    (hp5 : 5 ≤ p) (hcop2 : Nat.Coprime 2 p)
    {r : ℕ} (hr : p = 2 * r + 1)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ)
    (hs : RealSourceAdmissible hζ s) :
    ∃ (ρzero : 𝓞 K) (ηzero : (𝓞 K)ˣ) (jzero : ℕ),
      s.omega + s.theta =
        ηzero * kappa hζ ^ (p * s.m - r) * ρzero ^ p ∧
      historicalEquationEightAIdeal
          (by omega : p ≠ 2) hζ s =
        Ideal.span {ρzero} ∧
      NumberField.IsCMField.ringOfIntegersComplexConj K
          (ρzero ^ 2) =
        (hζ.unit' ^ jzero : (𝓞 K)ˣ) * ρzero ^ 2 ∧
      NumberField.IsCMField.unitsComplexConj K (ηzero ^ 2) =
        ηzero ^ 2 := by
  let J : Ideal (𝓞 K) :=
    historicalEquationEightAIdeal
      (by omega : p ≠ 2) hζ s
  let q : 𝓞 K :=
    historicalEquationEightAQuotient
      (by omega : p ≠ 2) hr hζ s hs
  obtain ⟨ρ, η, j, hJ, hq, hρconj⟩ :=
    exists_squaredConjugationGenerator_of_real_pow
      hplus (by omega : 2 < p) hcop2 hζ J q
      (by
        simpa only [q] using
          historicalEquationEightAQuotient_ne_zero
            (by omega : p ≠ 2) hr hζ s hs)
      (by
        simpa only [q] using
          historicalEquationEightAQuotient_real
            (by omega : p ≠ 2) hr hζ s hs)
      (by
        simpa only [J, q] using
          historicalEquationEightAIdeal_pow
            (by omega : p ≠ 2) hr hζ s hs)
  have hq0 : q ≠ 0 := by
    simpa only [q] using
      historicalEquationEightAQuotient_ne_zero
        (by omega : p ≠ 2) hr hζ s hs
  have hρ0 : ρ ≠ 0 := by
    intro hρ
    apply hq0
    rw [hq, hρ]
    simp only [zero_pow (Fact.out : Nat.Prime p).ne_zero, mul_zero]
  have hzetaP : hζ.unit' ^ p = 1 := by
    apply Units.ext
    apply NumberField.RingOfIntegers.ext
    change ζ ^ p = 1
    exact hζ.pow_eq_one
  have hrootP : (hζ.unit' ^ j) ^ p = 1 := by
    rw [← pow_mul]
    rw [Nat.mul_comm j p, pow_mul, hzetaP, one_pow]
  have hρtwoPReal :
      NumberField.IsCMField.ringOfIntegersComplexConj K
          (ρ ^ (2 * p)) =
        ρ ^ (2 * p) := by
    have htwoP : ρ ^ (2 * p) = (ρ ^ 2) ^ p := by
      rw [← pow_mul]
    rw [htwoP, map_pow, hρconj, mul_pow,
      ← Units.val_pow_eq_pow_val, hrootP, Units.val_one,
      one_mul, ← htwoP]
  have hq2 :
      q ^ 2 =
        ((η ^ 2 : (𝓞 K)ˣ) : 𝓞 K) * ρ ^ (2 * p) := by
    rw [hq, mul_pow, ← Units.val_pow_eq_pow_val, ← pow_mul]
    rw [show p * 2 = 2 * p by omega]
  have hηsqVal :
      NumberField.IsCMField.ringOfIntegersComplexConj K
          ((η ^ 2 : (𝓞 K)ˣ) : 𝓞 K) =
        ((η ^ 2 : (𝓞 K)ˣ) : 𝓞 K) := by
    apply mul_right_cancel₀
      (pow_ne_zero (2 * p) hρ0)
    calc
      NumberField.IsCMField.ringOfIntegersComplexConj K
            ((η ^ 2 : (𝓞 K)ˣ) : 𝓞 K) *
          ρ ^ (2 * p) =
        NumberField.IsCMField.ringOfIntegersComplexConj K
          (((η ^ 2 : (𝓞 K)ˣ) : 𝓞 K) *
            ρ ^ (2 * p)) := by
              rw [map_mul, hρtwoPReal]
      _ =
          NumberField.IsCMField.ringOfIntegersComplexConj K
            (q ^ 2) := by rw [hq2]
      _ = q ^ 2 := by
        rw [map_pow,
          historicalEquationEightAQuotient_real
            (by omega : p ≠ 2) hr hζ s hs]
      _ =
          ((η ^ 2 : (𝓞 K)ˣ) : 𝓞 K) *
            ρ ^ (2 * p) := hq2
  have hηsq :
      NumberField.IsCMField.unitsComplexConj K (η ^ 2) =
        η ^ 2 := by
    apply Units.ext
    exact hηsqVal
  refine ⟨ρ, η, j, ?_, ?_, hρconj, hηsq⟩
  · calc
      s.omega + s.theta =
          kappa hζ ^ (p * s.m - r) * q :=
        historicalEquationEightAQuotient_spec
          (by omega : p ≠ 2) hr hζ s hs
      _ =
          kappa hζ ^ (p * s.m - r) *
            ((η : 𝓞 K) * ρ ^ p) := by rw [hq]
      _ =
          (η : 𝓞 K) * kappa hζ ^ (p * s.m - r) *
            ρ ^ p := by ring
  · simpa only [J] using hJ

/-! ## Transporting a historical state to the primitive root `ζ²` -/

/-- The same historical equation expressed with primitive root `ζ²`.
The real cyclotomic unit introduced into `κ` is removed from `ξ`, so all
nonvanishing and coprimality fields are preserved. -/
noncomputable def historicalStateAtTwo
    (hp5 : 5 ≤ p)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ) :
    HistoricalState
      (hζ.pow_of_coprime 2 (coprime_two_prime hp5)) :=
  let u := equationTenTraceTwoUnit hp5 hζ
  { omega := s.omega
    theta := s.theta
    xi := (((u⁻¹) ^ s.m : (𝓞 K)ˣ) : 𝓞 K) * s.xi
    eta := s.eta
    m := s.m
    one_lt_m := s.one_lt_m
    xi_ne_zero :=
      mul_ne_zero (u⁻¹ ^ s.m).isUnit.ne_zero s.xi_ne_zero
    coprime_omega_theta := s.coprime_omega_theta
    coprime_theta_xi :=
      (isCoprime_mul_unit_left_right (u⁻¹ ^ s.m).isUnit
        s.theta s.xi).mpr s.coprime_theta_xi
    coprime_omega_xi :=
      (isCoprime_mul_unit_left_right (u⁻¹ ^ s.m).isUnit
        s.omega s.xi).mpr s.coprime_omega_xi
    equation := by
      rw [s.equation]
      have hu :
          (u : 𝓞 K) ^ s.m *
              ((u⁻¹ : (𝓞 K)ˣ) : 𝓞 K) ^ s.m =
            1 := by
        rw [← mul_pow, ← Units.val_mul]
        simp
      have hbase :
          kappa
                (hζ.pow_of_coprime 2
                  (coprime_two_prime hp5)) ^ s.m *
              ((((u⁻¹) ^ s.m : (𝓞 K)ˣ) : 𝓞 K) * s.xi) =
            kappa hζ ^ s.m * s.xi := by
        rw [kappa_powTwoPrimitiveRoot hp5 hζ, mul_pow]
        simp only [Units.val_pow_eq_pow_val]
        calc
          (kappa hζ ^ s.m * (u : 𝓞 K) ^ s.m) *
                (((u⁻¹ : (𝓞 K)ˣ) : 𝓞 K) ^ s.m * s.xi) =
              kappa hζ ^ s.m *
                (((u : 𝓞 K) ^ s.m *
                  ((u⁻¹ : (𝓞 K)ˣ) : 𝓞 K) ^ s.m) *
                    s.xi) := by ring
          _ = kappa hζ ^ s.m * s.xi := by
            rw [hu, one_mul]
      rw [hbase] }

/-- Real admissibility is preserved by the change of primitive root from
`ζ` to `ζ²`. -/
theorem historicalStateAtTwo_admissible
    (hp5 : 5 ≤ p)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ)
    (hs : RealSourceAdmissible hζ s) :
    RealSourceAdmissible
      (hζ.pow_of_coprime 2 (coprime_two_prime hp5))
      (historicalStateAtTwo hp5 hζ s) := by
  let u := equationTenTraceTwoUnit hp5 hζ
  have hureal :
      NumberField.IsCMField.unitsComplexConj K u = u := by
    simpa only [u] using equationTenTraceTwoUnit_real hp5 hζ
  have huinvpow :
      NumberField.IsCMField.ringOfIntegersComplexConj K
          (((u⁻¹) ^ s.m : (𝓞 K)ˣ) : 𝓞 K) =
        (((u⁻¹) ^ s.m : (𝓞 K)ˣ) : 𝓞 K) := by
    have huinvpowU :
        NumberField.IsCMField.unitsComplexConj K
            ((u⁻¹) ^ s.m) =
          (u⁻¹) ^ s.m := by
      rw [map_pow, map_inv, hureal]
    exact congrArg ((↑) : (𝓞 K)ˣ → 𝓞 K) huinvpowU
  refine ⟨hs.1, hs.2.1, ?_, hs.2.2.2⟩
  change
    NumberField.IsCMField.ringOfIntegersComplexConj K
        ((((u⁻¹) ^ s.m : (𝓞 K)ˣ) : 𝓞 K) * s.xi) =
      (((u⁻¹) ^ s.m : (𝓞 K)ˣ) : 𝓞 K) * s.xi
  rw [map_mul, huinvpow, hs.2.2.1]

/-- The transported state therefore also has its canonical prepared
Takagi factor package. -/
noncomputable def preparedHistoricalEquationDataAtTwo
    (hp5 : 5 ≤ p)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ)
    (hs : RealSourceAdmissible hζ s) :
    PreparedHistoricalEquationData
      (hζ.pow_of_coprime 2 (coprime_two_prime hp5)) :=
  preparedHistoricalEquationData hp5
    (hζ.pow_of_coprime 2 (coprime_two_prime hp5))
    (historicalStateAtTwo hp5 hζ s)
    (historicalStateAtTwo_admissible hp5 hζ s hs)

end

end Fermat.Irregular.TakagiHistoricalPrime
