import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.Group.Subgroup.Finsupp
import Mathlib.Data.Int.GCD
import Mathlib.GroupTheory.Index
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.RingTheory.Int.Basic

/-!
# The unit-power algebra in Vandiver's Lemma 2

This module formalizes the group-theoretic and divisibility part of
Vandiver's 1929 Lemma 2.  For a finite family of units `E i`, it proves:

* finite index supplies a relation `u^t = ∏ i, E i ^ a i` with `t > 0`;
* if the `p`-power map is injective, common factors of `p` can be divided out
  until the relation is primitive;
* the congruences `p^3 ∣ a i * B i`, in the absence of `p^3 ∣ B i`, force
  every exponent `a i` to be divisible by `p`;
* primitivity then makes `t` coprime to `p`, and Bézout's identity extracts
  an explicit `p`-th root of `u`.

The final theorem leaves only the sharply stated historical calculation
that a deep local congruence produces `p^3 ∣ a i * B i` for a primitive
relation.  No unit-power conclusion is assumed.
-/

namespace Fermat.Irregular.VandiverUnitPower

open scoped BigOperators

/-- A finite-index family supplies Vandiver's initial power/product
relation.  The exponent is the index of the subgroup generated by the
family, and is strictly positive. -/
theorem exists_index_relation
    {G ι : Type*} [CommGroup G] [Fintype ι]
    (E : ι → G) (u : G)
    [hfinite : (Subgroup.closure (Set.range E)).FiniteIndex] :
    ∃ a : ι → ℤ,
      0 < (Subgroup.closure (Set.range E)).index ∧
        u ^ (Subgroup.closure (Set.range E)).index =
          ∏ i, E i ^ a i := by
  obtain ⟨a, ha⟩ := Subgroup.exists_of_mem_closure_range E
    (u ^ (Subgroup.closure (Set.range E)).index)
    (Subgroup.pow_index_mem (Subgroup.closure (Set.range E)) u)
  exact ⟨a, Nat.pos_of_ne_zero hfinite.index_ne_zero, ha⟩

/-- Vandiver's final Bézout argument.  If `t` and `p` are coprime and
`u^t` is a `p`-th power, then `u` is itself a `p`-th power. -/
theorem isPower_of_coprime_power_eq_power
    {G : Type*} [CommGroup G] {u d : G} {t p : ℕ}
    (hcop : t.Coprime p) (hrel : u ^ t = d ^ p) :
    ∃ v : G, u = v ^ p := by
  let v : G := d ^ (Nat.gcdA t p) * u ^ (Nat.gcdB t p)
  refine ⟨v, ?_⟩
  have hbezout : (1 : ℤ) =
      (t : ℤ) * Nat.gcdA t p + (p : ℤ) * Nat.gcdB t p := by
    rw [← Nat.gcd_eq_gcd_ab, hcop]
    simp
  rw [show u = u ^ (1 : ℤ) by simp, hbezout]
  simp only [v, zpow_add, zpow_mul, zpow_natCast]
  rw [hrel, mul_pow]
  simp only [← zpow_natCast, ← zpow_mul]
  congr 1 <;> simp [mul_comm]

/-- If `p^3` divides `a * b` but does not divide `b`, then the prime `p`
must divide `a`.  This is the arithmetic forcing used on each exponent in
Vandiver's relation. -/
theorem prime_dvd_of_cube_dvd_mul_of_not_cube_dvd
    {p : ℕ} (hp : p.Prime) {a b : ℤ}
    (hprod : (p : ℤ) ^ 3 ∣ a * b)
    (hb : ¬(p : ℤ) ^ 3 ∣ b) :
    (p : ℤ) ∣ a := by
  by_contra ha
  apply hb
  have hna : ¬p ∣ a.natAbs := by
    simpa [Int.natCast_dvd] using ha
  have hnat : Nat.Coprime (p ^ 3) a.natAbs :=
    (hp.coprime_pow_of_not_dvd hna).symm
  have hint : IsCoprime ((p : ℤ) ^ 3) a := by
    rw [Int.isCoprime_iff_nat_coprime]
    simpa [Int.natAbs_pow] using hnat
  exact hint.dvd_of_dvd_mul_right (by simpa [mul_comm] using hprod)

/-- Multiplying every exponent in a finite unit product by `p` gives the
`p`-th power of the original product. -/
theorem product_zpow_mul_exponents
    {G ι : Type*} [CommGroup G] [Fintype ι]
    (E : ι → G) (b : ι → ℤ) (p : ℕ) :
    (∏ i, E i ^ ((p : ℤ) * b i)) = (∏ i, E i ^ b i) ^ p := by
  rw [← Finset.prod_pow Finset.univ p]
  apply Finset.prod_congr rfl
  intro i hi
  simp only [← zpow_natCast, ← zpow_mul]
  congr 1
  ring

/-- If every exponent is divisible by `p`, the corresponding finite unit
product is a `p`-th power. -/
theorem product_zpow_is_pow_of_exponents_divisible
    {G ι : Type*} [CommGroup G] [Fintype ι]
    (E : ι → G) (a : ι → ℤ) (p : ℕ)
    (hdiv : ∀ i, (p : ℤ) ∣ a i) :
    ∃ d : G, (∏ i, E i ^ a i) = d ^ p := by
  classical
  choose b hb using hdiv
  refine ⟨∏ i, E i ^ b i, ?_⟩
  simpa only [hb] using product_zpow_mul_exponents E b p

/-- Vandiver's normalization of the exponent relation.  Whenever `p`
divides `t` and every `a i`, injectivity of the `p`-power map lets us divide
the entire relation by `p`.  Strong induction on the positive exponent `t`
therefore yields a primitive relation. -/
theorem exists_primitive_relation_of_relation
    {G ι : Type*} [CommGroup G] [Fintype ι]
    {p t : ℕ} (hp2 : 2 ≤ p)
    (hpow : Function.Injective (fun x : G ↦ x ^ p))
    (u : G) (E : ι → G) (a : ι → ℤ)
    (ht : 0 < t) (hrel : u ^ t = ∏ i, E i ^ a i) :
    ∃ (t' : ℕ) (a' : ι → ℤ),
      0 < t' ∧ u ^ t' = ∏ i, E i ^ a' i ∧
        ¬(p ∣ t' ∧ ∀ i, (p : ℤ) ∣ a' i) := by
  induction t using Nat.strong_induction_on generalizing a with
  | h t ih =>
      by_cases hprimitive : ¬(p ∣ t ∧ ∀ i, (p : ℤ) ∣ a i)
      · exact ⟨t, a, ht, hrel, hprimitive⟩
      · push Not at hprimitive
        obtain ⟨hpt, ha⟩ := hprimitive
        obtain ⟨t', rfl⟩ := hpt
        classical
        choose b hb using ha
        have ht' : 0 < t' := Nat.pos_of_mul_pos_left ht
        have hp1 : 1 < p := by omega
        have hlt : t' < p * t' := by
          simpa using Nat.mul_lt_mul_of_pos_right hp1 ht'
        apply ih t' hlt b ht'
        apply hpow
        calc
          (u ^ t') ^ p = u ^ (p * t') := by
            rw [← pow_mul, Nat.mul_comm]
          _ = ∏ i, E i ^ a i := hrel
          _ = ∏ i, E i ^ ((p : ℤ) * b i) := by
            apply Finset.prod_congr rfl
            intro i hi
            rw [hb i]
          _ = (∏ i, E i ^ b i) ^ p :=
            product_zpow_mul_exponents E b p

/-- The last half of Vandiver's Lemma 2 for a fixed primitive relation.
The cube congruences force all family exponents to be multiples of `p`;
primitivity then forces `t` to be coprime to `p`, and Bézout finishes. -/
theorem isPower_of_primitive_relation_and_cube_congruences
    {G ι : Type*} [CommGroup G] [Fintype ι]
    {p t : ℕ} (hp : p.Prime) (u : G) (E : ι → G)
    (a B : ι → ℤ)
    (hrel : u ^ t = ∏ i, E i ^ a i)
    (hprimitive : ¬(p ∣ t ∧ ∀ i, (p : ℤ) ∣ a i))
    (hcong : ∀ i, (p : ℤ) ^ 3 ∣ a i * B i)
    (hno : ∀ i, ¬(p : ℤ) ^ 3 ∣ B i) :
    ∃ v : G, u = v ^ p := by
  have hdiv : ∀ i, (p : ℤ) ∣ a i := fun i ↦
    prime_dvd_of_cube_dvd_mul_of_not_cube_dvd hp (hcong i) (hno i)
  have hpt : ¬p ∣ t := fun h ↦ hprimitive ⟨h, hdiv⟩
  have hcop : t.Coprime p :=
    (hp.coprime_iff_not_dvd.mpr hpt).symm
  obtain ⟨d, hd⟩ :=
    product_zpow_is_pow_of_exponents_divisible E a p hdiv
  exact isPower_of_coprime_power_eq_power hcop (hrel.trans hd)

/-- Generic algebraic core of Vandiver's Lemma 2.

The sole proof-specific input `hcong` says exactly what remains to be
obtained from Vandiver's polynomial remainder and high logarithmic
derivatives: every positive primitive relation has
`p^3 ∣ a i * B i`.  All finite-index, normalization, divisibility, and
unit-root extraction steps are proved here. -/
theorem isPower_of_finiteIndex_family_and_cube_congruences
    {G ι : Type*} [CommGroup G] [Fintype ι]
    {p : ℕ} (hp : p.Prime)
    (hpow : Function.Injective (fun x : G ↦ x ^ p))
    (u : G) (E : ι → G) (B : ι → ℤ)
    [hfinite : (Subgroup.closure (Set.range E)).FiniteIndex]
    (hcong : ∀ (t : ℕ) (a : ι → ℤ),
      0 < t →
      u ^ t = ∏ i, E i ^ a i →
      ¬(p ∣ t ∧ ∀ i, (p : ℤ) ∣ a i) →
      ∀ i, (p : ℤ) ^ 3 ∣ a i * B i)
    (hno : ∀ i, ¬(p : ℤ) ^ 3 ∣ B i) :
    ∃ v : G, u = v ^ p := by
  obtain ⟨a, ht, hrel⟩ := exists_index_relation E u
  obtain ⟨t', a', ht', hrel', hprimitive⟩ :=
    exists_primitive_relation_of_relation hp.two_le hpow u E a ht hrel
  exact isPower_of_primitive_relation_and_cube_congruences
    hp u E a' B hrel' hprimitive
      (hcong t' a' ht' hrel' hprimitive) hno

end Fermat.Irregular.VandiverUnitPower
