import Fermat.SixHundredSeven.CircularUnitResidues
import Fermat.SixHundredSeven.VandiverDiagonalArithmetic607
import Mathlib.LinearAlgebra.Vandermonde

/-!
# Residue and Fourier certificates for Vandiver's diagonal units at 607

This module derives the residue matrix of Vandiver's 302 diagonal units
from the already certified circular-unit matrix at `q = 20639`.

The 303 basic factors form the edges of the cyclic ordering generated by
`813` modulo sign. Their positive integral weights are the nontrivial even
characters of that cycle. Consequently the change of basis is a scaled
transpose Vandermonde matrix. This avoids both a `302 × 303` Cartesian
certificate and a second explicit dense inverse.
-/

namespace Fermat.SixHundredSeven.VandiverDiagonalUnitResidues

open Fermat.SixHundredSeven.VandiverDiagonalArithmetic
open Fermat.SixHundredSeven.CircularUnitCyclic
open Fermat.SixHundredSeven.CircularUnitEntryCertificate
open Fermat.SixHundredSeven.CircularUnitMatrix
open Fermat.Irregular.CircularUnitFamily
open Fermat.Irregular.CircularUnitResidues
open Fermat.Irregular.CircularUnitResidues.Certificate

local instance : Fact (Nat.Prime 607) :=
  ⟨Fermat.SixHundredSeven.prime_607⟩
local instance : Fact (Nat.Prime 20639) :=
  ⟨Fermat.SixHundredSeven.prime_20639⟩

set_option maxHeartbeats 3000000
set_option maxRecDepth 1000000

/-- The canonical circular-unit column corresponding to the real class
of `813^(j+1)`. -/
def cycleColumn607 (j : Fin 302) : Fin 302 :=
  let s := ((teichmullerRoot607 : ZMod 607) ^ (j.val + 1)).val
  let a := min s (607 - s)
  ⟨(a - 2) % 302, Nat.mod_lt _ (by norm_num)⟩

/-- The powers of `813` visit every nontrivial real class exactly once. -/
theorem cycleColumn607_bijective :
    Function.Bijective cycleColumn607 := by decide

noncomputable def cycleColumnEquiv607 : Fin 302 ≃ Fin 302 :=
  Equiv.ofBijective cycleColumn607 cycleColumn607_bijective

/-- The nontrivial even Fourier nodes `813^(-2n)`, `1 ≤ n ≤ 302`. -/
def vandermondeNode607 (i : Fin 302) : ZMod 607 :=
  (teichmullerRoot607 : ZMod 607) ^ (604 - 2 * i.val)

theorem vandermondeNode607_injective :
    Function.Injective vandermondeNode607 := by
  intro i j hij
  have hi : 604 - 2 * i.val < 606 := by omega
  have hj : 604 - 2 * j.val < 606 := by omega
  have hexp : 604 - 2 * i.val = 604 - 2 * j.val :=
    teichmullerRoot607_isPrimitive.pow_inj hi hj hij
  apply Fin.ext
  omega

/-- Column scale converting powers `0, ..., 301` to Vandiver's edge
coefficients. -/
def fourierScale607 (i : Fin 302) : ZMod 607 :=
  ((teichmullerRoot607 : ZMod 607) ^ (2 * (i.val + 1)) - 1) *
    (teichmullerRoot607 : ZMod 607) * vandermondeNode607 i

theorem fourierScale607_ne_zero (i : Fin 302) :
    fourierScale607 i ≠ 0 := by
  have hpos : 0 < 2 * (i.val + 1) := by omega
  have hlt : 2 * (i.val + 1) < 606 := by omega
  have hpow :
      (teichmullerRoot607 : ZMod 607) ^ (2 * (i.val + 1)) ≠ 1 :=
    teichmullerRoot607_isPrimitive.pow_ne_one_of_pos_of_lt
      hpos.ne' hlt
  exact mul_ne_zero
    (mul_ne_zero (sub_ne_zero.mpr hpow)
      (teichmullerRoot607_isPrimitive.ne_zero (by norm_num)))
    (pow_ne_zero _
      (teichmullerRoot607_isPrimitive.ne_zero (by norm_num)))

/-- The edge-to-diagonal change of basis. -/
def fourierChange607 : Matrix (Fin 302) (Fin 302) (ZMod 607) :=
  (Matrix.vandermonde vandermondeNode607).transpose *
    Matrix.diagonal fourierScale607

theorem fourierChange607_apply (row i : Fin 302) :
    fourierChange607 row i =
      vandermondeNode607 i ^ row.val * fourierScale607 i := by
  rw [fourierChange607, Matrix.mul_diagonal]
  rfl

/-- The scaled Fourier matrix is nonsingular. -/
theorem fourierChange607_det_ne_zero :
    fourierChange607.det ≠ 0 := by
  rw [fourierChange607, Matrix.det_mul, Matrix.det_transpose,
    Matrix.det_diagonal]
  exact mul_ne_zero
    (Matrix.det_vandermonde_ne_zero_iff.mpr
      vandermondeNode607_injective)
    (Finset.prod_ne_zero_iff.mpr
      (fun i _ ↦ fourierScale607_ne_zero i))

abbrev certificate607 : Certificate 607 20639 :=
  Fermat.SixHundredSeven.CircularUnitResidues.certificate

/-- Extend the circular-unit cycle by the trivial class at positions zero
and 303. -/
def cycleClassSymbol607 (row : Fin 302) (ell : ℕ) : ZMod 607 :=
  if h : 1 ≤ ell ∧ ell ≤ 302 then
    Fermat.SixHundredSeven.CircularUnitMatrix.matrix row
      (cycleColumn607 ⟨ell - 1, by omega⟩)
  else 0

/-- The symbol of the `j`th basic factor is the difference of adjacent
circular-unit symbols. -/
def basicEdgeSymbol607 (row : Fin 302) (j : Fin 303) : ZMod 607 :=
  cycleClassSymbol607 row (j.val + 1) -
    cycleClassSymbol607 row j.val

/-- Literal source exponent `813^j`. -/
def conjugateExponent607 (j : Fin 303) : ℕ :=
  teichmullerRoot607 ^ j.val

/-- Its small reduction modulo `607`. -/
def reducedConjugateExponent607 (j : Fin 303) : ℕ :=
  ((teichmullerRoot607 : ZMod 607) ^ j.val).val

theorem conjugateExponent607_modEq_reduced (j : Fin 303) :
    conjugateExponent607 j ≡ reducedConjugateExponent607 j [MOD 607] := by
  rw [← ZMod.natCast_eq_natCast_iff]
  simp [conjugateExponent607, reducedConjugateExponent607]

theorem pow_conjugateExponent607_eq_reduced {G : Type*} [Monoid G]
    (x : G) (hx : x ^ 607 = 1) (j : Fin 303) :
    x ^ conjugateExponent607 j = x ^ reducedConjugateExponent607 j :=
  pow_eq_pow_of_modEq (conjugateExponent607_modEq_reduced j) hx

/-- The literal 813-term geometric sum in the finite-field reduction. -/
def basicResidueGeomSum607 (row : Fin 302) (j : Fin 303) : ZMod 20639 :=
  let w := embeddingRoot (p := 607) certificate607.root row ^
    conjugateExponent607 j
  ∑ k ∈ Finset.range 813, w ^ k

/-- Reduction of the normalized basic factor. -/
def basicResidueValue607 (row : Fin 302) (j : Fin 303) : ZMod 20639 :=
  let w := embeddingRoot (p := 607) certificate607.root row ^
    conjugateExponent607 j
  w ^ 201 * basicResidueGeomSum607 row j

/-- The literal source sum is kept at the chosen Teichmüller representative
`813`; no unrecorded period reduction is performed. -/
theorem basicResidueGeomSum607_eq (row : Fin 302) (j : Fin 303) :
    basicResidueGeomSum607 row j =
      ∑ k ∈ Finset.range 813,
        (embeddingRoot (p := 607) certificate607.root row ^
          conjugateExponent607 j) ^ k := by
  rfl

/-! ## Compact cyclic provenance

The real residue group is cyclic of order 303. Thus the edge-symbol and
normalized-value identities factor through two one-variable certificates
and an algebraic phase argument. -/

/-- In the real cyclic quotient generated by `3`, multiplication by `813`
is translation by `142`; equivalently, `3^142 = -813 (mod 607)`. -/
theorem cycleColumn607_coord (ell : Fin 302) :
    coord (columnPermutation (cycleColumn607 ell)) =
      ((142 * (ell.val + 1) : ℕ) : Cyc) := by
  decide +revert

/-- The stored column is the canonical representative of
`813^(ell+1)` up to the harmless real-class sign. -/
theorem cycleColumn607_realRepresentative (ell : Fin 302) :
    let a := ((cycleColumn607 ell).val + 2 : ZMod 607)
    let d := (teichmullerRoot607 : ZMod 607) ^ (ell.val + 1)
    a = d ∨ a = -d := by
  decide +revert

/-- Cyclic coordinate of an original embedding row. -/
def rowCycleCoord607 (row : Fin 302) : Cyc :=
  coord (rowPermutation row)

/-- Extend the literal conjugate powers through the wrap at exponent
`303`. -/
def extendedConjugateExponent607 (ell : Fin 304) : ℕ :=
  teichmullerRoot607 ^ ell.val

/-- Its cyclic real-residue coordinate. -/
def extendedCycleCoord607 (ell : Fin 304) : Cyc :=
  ((142 * ell.val : ℕ) : Cyc)

private theorem weight_eq_of_eq_or_inv {x y : ZMod 20639}
    (hy : y ≠ 0) (h : x = y ∨ x = y⁻¹) :
    weight x = weight y := by
  rcases h with h | h
  · rw [h]
  · rw [h, weight_inv y hy]

private theorem pow_eq_inv_pow_of_cast_eq_neg
    {x : ZMod 20639} (hx : IsPrimitiveRoot x 607)
    {a b : ℕ}
    (h : (a : ZMod 607) = -(b : ZMod 607)) :
    x ^ a = (x ^ b)⁻¹ := by
  have hab : a + b ≡ 0 [MOD 607] := by
    rw [← ZMod.natCast_eq_natCast_iff]
    simpa only [Nat.cast_add, Nat.cast_zero, add_eq_zero_iff_eq_neg] using h
  have hp : x ^ (a + b) = 1 := by
    simpa using pow_eq_pow_of_modEq hab hx.pow_eq_one
  apply (mul_eq_one_iff_eq_inv₀
    (pow_ne_zero b (hx.ne_zero (by norm_num)))).mp
  rw [← pow_add]
  exact hp

private theorem pow_eq_or_inv_pow_of_cast_eq_or_neg
    {x : ZMod 20639} (hx : IsPrimitiveRoot x 607)
    {a b : ℕ}
    (h : (a : ZMod 607) = b ∨
      (a : ZMod 607) = -(b : ZMod 607)) :
    x ^ a = x ^ b ∨ x ^ a = (x ^ b)⁻¹ := by
  rcases h with h | h
  · left
    apply pow_eq_pow_of_modEq _ hx.pow_eq_one
    rw [← ZMod.natCast_eq_natCast_iff]
    exact h
  · exact Or.inr (pow_eq_inv_pow_of_cast_eq_neg hx h)

/-- The weight of every conjugated root is its cyclic phase weight. This
is parametric in the row; only the two column-orientation facts above are
checked finitely. -/
theorem extendedConjugateWeight607 (row : Fin 302) (ell : Fin 304) :
    let x := embeddingRoot (p := 607) (14674 : ZMod 20639) row
    weight (x ^ extendedConjugateExponent607 ell) =
      weight
        (classRoot (rowCycleCoord607 row + extendedCycleCoord607 ell)) := by
  let x := embeddingRoot (p := 607) (14674 : ZMod 20639) row
  change
    weight (x ^ extendedConjugateExponent607 ell) =
      weight
        (classRoot (rowCycleCoord607 row + extendedCycleCoord607 ell))
  have hxprim : IsPrimitiveRoot x 607 :=
    embeddingRoot_isPrimitive (p := 607) (q := 20639) (by norm_num)
      root_isPrimitive row
  have hx0 : x ≠ 0 := hxprim.ne_zero (by norm_num)
  by_cases hzero : ell.val = 0
  · have hell : ell = ⟨0, by norm_num⟩ := Fin.ext hzero
    subst ell
    have hrow :
        classRoot (rowCycleCoord607 row) = x ∨
          classRoot (rowCycleCoord607 row) = x⁻¹ := by
      simpa [x, rowCycleCoord607] using row_root_relation row
    have hw := weight_eq_of_eq_or_inv hx0 hrow
    simpa [x, rowCycleCoord607, extendedConjugateExponent607,
      extendedCycleCoord607] using hw.symm
  by_cases hlast : ell.val = 303
  · have hell : ell = ⟨303, by norm_num⟩ := Fin.ext hlast
    subst ell
    have hpowLast :
        x ^ extendedConjugateExponent607 ⟨303, by norm_num⟩ = x⁻¹ := by
      have hcast :
          (extendedConjugateExponent607 ⟨303, by norm_num⟩ : ZMod 607) =
            -(1 : ZMod 607) := by
        decide +kernel
      simpa only [pow_one] using
        pow_eq_inv_pow_of_cast_eq_neg hxprim hcast
    have hrow :
        classRoot (rowCycleCoord607 row) = x ∨
          classRoot (rowCycleCoord607 row) = x⁻¹ := by
      simpa [x, rowCycleCoord607] using row_root_relation row
    have hw := weight_eq_of_eq_or_inv hx0 hrow
    have hcoordlast :
        extendedCycleCoord607 ⟨303, by norm_num⟩ = 0 := by
      decide
    calc
      weight
          (x ^ extendedConjugateExponent607 ⟨303, by norm_num⟩) =
          weight x⁻¹ := congrArg weight hpowLast
      _ = weight x := weight_inv x hx0
      _ = weight
          (classRoot
            (rowCycleCoord607 row +
              extendedCycleCoord607 ⟨303, by norm_num⟩)) := by
        rw [hcoordlast, add_zero]
        exact hw.symm
  · have hpos : 1 ≤ ell.val := by omega
    have hle : ell.val ≤ 302 := by omega
    let k : Fin 302 := ⟨ell.val - 1, by omega⟩
    have hk : k.val + 1 = ell.val := by simp [k]; omega
    let a := (cycleColumn607 k).val + 2
    have hrep := cycleColumn607_realRepresentative k
    have hcast :
        (a : ZMod 607) =
            (extendedConjugateExponent607 ell : ZMod 607) ∨
          (a : ZMod 607) =
            -(extendedConjugateExponent607 ell : ZMod 607) := by
      simpa [a, extendedConjugateExponent607, hk] using hrep
    have hpow := pow_eq_or_inv_pow_of_cast_eq_or_neg hxprim hcast
    have hpowWeight :
        weight (x ^ a) =
          weight (x ^ extendedConjugateExponent607 ell) :=
      weight_eq_of_eq_or_inv
        (pow_ne_zero (extendedConjugateExponent607 ell) hx0) hpow
    have hprod :
        classRoot
            (rowCycleCoord607 row +
              coord (columnPermutation (cycleColumn607 k))) =
            x ^ a ∨
          classRoot
            (rowCycleCoord607 row +
              coord (columnPermutation (cycleColumn607 k))) =
            (x ^ a)⁻¹ := by
      simpa [x, a, rowCycleCoord607] using
        product_root_relation row (cycleColumn607 k)
    have hprodWeight :
        weight
            (classRoot
              (rowCycleCoord607 row +
                coord (columnPermutation (cycleColumn607 k)))) =
          weight (x ^ a) := by
      exact weight_eq_of_eq_or_inv (pow_ne_zero a hx0) hprod
    rw [cycleColumn607_coord k] at hprodWeight
    have hcoord :
        ((142 * (k.val + 1) : ℕ) : Cyc) =
          extendedCycleCoord607 ell := by
      simp only [extendedCycleCoord607, hk]
    rw [hcoord] at hprodWeight
    exact (hprodWeight.trans hpowWeight).symm

private theorem normalizedGeom_pow_eq_weight_ratio
    (w : ZMod 20639) (hw : IsPrimitiveRoot w 607) (a e : ℕ)
    (hexp : 34 * e + 17 * a ≡ 17 [MOD 607]) :
    (w ^ e * ∑ k ∈ Finset.range a, w ^ k) ^ 34 =
      weight (w ^ a) / weight w := by
  have hw0 : w ≠ 0 := hw.ne_zero (by norm_num)
  have hw1 : 1 - w ≠ 0 :=
    sub_ne_zero.mpr (Ne.symm (hw.ne_one (by norm_num)))
  have hgeom :
      ∑ k ∈ Finset.range a, w ^ k = (1 - w ^ a) / (1 - w) := by
    apply (eq_div_iff hw1).2
    calc
      (∑ k ∈ Finset.range a, w ^ k) * (1 - w) =
          -((w - 1) * ∑ k ∈ Finset.range a, w ^ k) := by ring
      _ = -(w ^ a - 1) := by rw [mul_geom_sum]
      _ = 1 - w ^ a := by ring
  rw [hgeom, ← mul_div_assoc]
  change (w ^ e * (1 - w ^ a) / (1 - w)) ^ 34 =
    weight (w ^ a) / weight w
  have hpow : w ^ (34 * e + 17 * a) = w ^ 17 :=
    pow_eq_pow_of_modEq hexp hw.pow_eq_one
  simp only [weight, mul_pow, div_pow]
  field_simp [hw0, hw1]
  have hpow' : w ^ (e * 34) * w ^ (a * 17) = w ^ 17 := by
    rw [← pow_add]
    simpa [Nat.mul_comm] using hpow
  calc
    _ = (w ^ (e * 34) * w ^ (a * 17)) * (1 - w ^ a) ^ 34 := by ring
    _ = w ^ 17 * (1 - w ^ a) ^ 34 := by rw [hpow']
    _ = _ := by ring

theorem normalizedLength813_pow_eq_weight_ratio
    (w : ZMod 20639) (hw : IsPrimitiveRoot w 607) :
    (w ^ 201 * ∑ k ∈ Finset.range 813, w ^ k) ^ 34 =
      weight (w ^ 813) / weight w :=
  normalizedGeom_pow_eq_weight_ratio w hw 813 201 (by norm_num)

/-- The extended cycle symbols are ordinary differences of the compressed
phase vector. -/
theorem cycleClassSymbol607_succ_phase (row ell : Fin 302) :
    cycleClassSymbol607 row (ell.val + 1) =
      symbolPhase
          (rowCycleCoord607 row +
            ((142 * (ell.val + 1) : ℕ) : Cyc)) -
        symbolPhase (rowCycleCoord607 row) := by
  rw [cycleClassSymbol607, dif_pos]
  · change
      symbolPhase
            (coord (rowPermutation row) +
              coord (columnPermutation (cycleColumn607 ell))) -
          symbolPhase (coord (rowPermutation row)) =
        _
    rw [cycleColumn607_coord]
    rfl
  · omega

theorem cycleClassSymbol607_phase (row : Fin 302) (ell : ℕ)
    (hell : ell ≤ 303) :
    cycleClassSymbol607 row ell =
      symbolPhase
          (rowCycleCoord607 row + ((142 * ell : ℕ) : Cyc)) -
        symbolPhase (rowCycleCoord607 row) := by
  by_cases hzero : ell = 0
  · subst ell
    simp [cycleClassSymbol607]
  by_cases hlast : ell = 303
  · subst ell
    have hcoord : (((142 * 303 : ℕ) : Cyc)) = 0 := by decide
    rw [cycleClassSymbol607, dif_neg (by omega), hcoord, add_zero, sub_self]
  · have hpos : 1 ≤ ell := by omega
    have hle : ell ≤ 302 := by omega
    let k : Fin 302 := ⟨ell - 1, by omega⟩
    have hk : k.val + 1 = ell := by simp [k]; omega
    simpa only [hk] using cycleClassSymbol607_succ_phase row k

theorem basicEdgeSymbol607_phase (row : Fin 302) (j : Fin 303) :
    basicEdgeSymbol607 row j =
      symbolPhase
          ((rowCycleCoord607 row +
              extendedCycleCoord607 j.castSucc) + 142) -
        symbolPhase
          (rowCycleCoord607 row +
            extendedCycleCoord607 j.castSucc) := by
  rw [basicEdgeSymbol607,
    cycleClassSymbol607_phase row (j.val + 1) (by omega),
    cycleClassSymbol607_phase row j.val (by omega)]
  simp only [extendedCycleCoord607, Fin.val_castSucc]
  have hstep :
      rowCycleCoord607 row + ((142 * (j.val + 1) : ℕ) : Cyc) =
        (rowCycleCoord607 row + ((142 * j.val : ℕ) : Cyc)) + 142 := by
    push_cast
    ring
  rw [hstep]
  ring

theorem extendedConjugateStep607
    (x : ZMod 20639) (hx : IsPrimitiveRoot x 607) (j : Fin 303) :
    (x ^ extendedConjugateExponent607 j.castSucc) ^ 813 =
      x ^ extendedConjugateExponent607 j.succ := by
  rw [← pow_mul]
  apply pow_eq_pow_of_modEq _ hx.pow_eq_one
  change
    teichmullerRoot607 ^ j.val * 813 ≡
      teichmullerRoot607 ^ (j.val + 1) [MOD 607]
  rw [pow_succ]
  exact (by norm_num [teichmullerRoot607] :
    813 ≡ teichmullerRoot607 [MOD 607]).mul_left _

private def reducedBasicResidueValue607
    (row : Fin 302) (j : Fin 303) : ZMod 20639 :=
  let x := embeddingRoot (p := 607) (14674 : ZMod 20639) row
  let w := x ^ extendedConjugateExponent607 j.castSucc
  w ^ 201 * ∑ k ∈ Finset.range 813, w ^ k

private theorem reducedBasicResidueValue607_symbol
    (row : Fin 302) (j : Fin 303) :
    reducedBasicResidueValue607 row j ^ 34 =
      (14674 : ZMod 20639) ^ (basicEdgeSymbol607 row j).val := by
  let x := embeddingRoot (p := 607) (14674 : ZMod 20639) row
  let w := x ^ extendedConjugateExponent607 j.castSucc
  have hxprim : IsPrimitiveRoot x 607 :=
    embeddingRoot_isPrimitive (p := 607) (q := 20639) (by norm_num)
      root_isPrimitive row
  have hwprim : IsPrimitiveRoot w 607 := by
    apply hxprim.pow_of_coprime
    exact (by norm_num : Nat.Coprime 813 607).pow_left j.val
  change (w ^ 201 * ∑ k ∈ Finset.range 813, w ^ k) ^ 34 = _
  rw [normalizedLength813_pow_eq_weight_ratio w hwprim]
  have hcur :
      weight w =
        weight
          (classRoot
            (rowCycleCoord607 row +
              extendedCycleCoord607 j.castSucc)) := by
    simpa [x, w] using extendedConjugateWeight607 row j.castSucc
  have hnext :
      weight (x ^ extendedConjugateExponent607 j.succ) =
        weight
          (classRoot
            (rowCycleCoord607 row +
              extendedCycleCoord607 j.succ)) := by
    simpa [x] using extendedConjugateWeight607 row j.succ
  have hstep := extendedConjugateStep607 x hxprim j
  rw [hstep, hnext, hcur]
  have hcoord :
      rowCycleCoord607 row + extendedCycleCoord607 j.succ =
        (rowCycleCoord607 row +
          extendedCycleCoord607 j.castSucc) + 142 := by
    simp only [extendedCycleCoord607, Fin.val_succ, Fin.val_castSucc]
    push_cast
    ring
  rw [hcoord, weight_ratio_eq_phase_ratio,
    phase_value_certificate, phase_value_certificate,
    ← root_pow_sub_val]
  rw [basicEdgeSymbol607_phase]

/-- Complete provenance of every basic-factor residue symbol, derived from
the one-variable cyclic certificates rather than a Cartesian case split. -/
theorem basicResidueValue607_symbol (row : Fin 302) (j : Fin 303) :
    basicResidueValue607 row j ^ 34 =
      certificate607.root ^ (basicEdgeSymbol607 row j).val := by
  rw [basicResidueValue607, basicResidueGeomSum607_eq]
  simpa [reducedBasicResidueValue607, extendedConjugateExponent607,
    conjugateExponent607, certificate607,
    Fermat.SixHundredSeven.CircularUnitResidues.certificate] using
    reducedBasicResidueValue607_symbol row j

end Fermat.SixHundredSeven.VandiverDiagonalUnitResidues
