/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, OpenAI

# Adic completeness of the local cyclotomic integer ring at 59

The local valuation integer ring is the closed unit ball inside the complete
`lambda`-adic field.  This module proves that its inherited norm topology is
exactly the topology generated by powers of the principal `lambda` ideal.
It follows that the integer ring is complete for the filtration used by the
formal Dwork completion.
-/
import Fermat.Exponents.FiftyNine.Conservation.TwistedArtinHasse59
import Mathlib.RingTheory.AdicCompletion.Topology

open scoped NumberField Topology Valued WithZero

noncomputable section

set_option maxRecDepth 10000
set_option maxHeartbeats 1200000

namespace Fermat.FiftyNine.Conservation.AdicCompleteValuedInteger59

open KummerCriterion.Furtwaengler.DieudonneDwork
open KummerCriterion.CyclotomicUnits.PadicLogSetup
open KummerCriterion.CyclotomicUnits.PadicLogSetup.DworkParameter
open Fermat.FiftyNine.Conservation.TwistedArtinHasse59

local instance : Fact (Nat.Prime 59) := ⟨by decide⟩

variable (K : Type) [Field K] [NumberField K]
variable [IsCyclotomicExtension {59} ℚ K]

/-- The integer ring is a closed unit ball inside the complete local field. -/
noncomputable instance instCompleteSpaceValuedIntegerRing59 :
    CompleteSpace (ValuedIntegerRing 59 K) := by
  letI : IsClosed
      (↑(KummerCriterion.Furtwaengler.KummerArtinHasse.lambdaHeightOneSpectrum 59 K
        |>.adicCompletionIntegers K) : Set (ValuedCompletion 59 K)) := by
    change IsClosed {x : ValuedCompletion 59 K | Valued.v x ≤ 1}
    convert Valued.isClosed_closedBall (ValuedCompletion 59 K)
        (Valued.v.restrict (1 : ValuedCompletion 59 K)) using 1
    ext x
    change (Valued.v x ≤ (1 : ℤᵐ⁰)) ↔
      Valued.v.restrict x ≤ Valued.v.restrict (1 : ValuedCompletion 59 K)
    rw [Valuation.restrict_le_iff, map_one]
  exact IsClosed.completeSpace_coe

/-- Membership in `lambda^n` is exactly the corresponding valuation bound. -/
theorem mem_lambdaIdeal_pow_iff_valuation_le
    (n : ℕ) (x : ValuedIntegerRing 59 K) :
    x ∈ (lambdaIdeal 59 K) ^ n ↔
      Valued.v (x : ValuedCompletion 59 K) ≤
        Valued.v (((valuedCyclotomicLambdaInteger 59 K) ^ n :
          ValuedIntegerRing 59 K) : ValuedCompletion 59 K) := by
  change x ∈ Ideal.span ({valuedCyclotomicLambdaInteger 59 K} :
      Set (ValuedIntegerRing 59 K)) ^ n ↔ _
  rw [Ideal.span_singleton_pow, Ideal.mem_span_singleton]
  exact (IsDedekindDomain.HeightOneSpectrum.adicCompletionIntegers.integers K
    (KummerCriterion.Furtwaengler.KummerArtinHasse.lambdaHeightOneSpectrum 59 K)).dvd_iff_le

/-- The cyclotomic uniformizer has norm strictly below one. -/
theorem norm_valuedCyclotomicLambdaInteger_lt_one :
    ‖valuedCyclotomicLambdaInteger 59 K‖ < 1 := by
  change ‖valuedCyclotomicLambda 59 K‖ < 1
  rw [Valued.toNormedField.norm_lt_one_iff]
  rw [valuedCyclotomicLambda_valuation]
  rw [← WithZero.exp_zero, WithZero.exp_lt_exp]
  norm_num

/-- An element of `lambda^n` has norm at most the norm of `lambda^n`. -/
theorem norm_le_norm_lambda_pow_of_mem
    (n : ℕ) {x : ValuedIntegerRing 59 K}
    (hx : x ∈ (lambdaIdeal 59 K) ^ n) :
    ‖x‖ ≤ ‖(valuedCyclotomicLambdaInteger 59 K) ^ n‖ := by
  change x ∈ Ideal.span ({valuedCyclotomicLambdaInteger 59 K} :
      Set (ValuedIntegerRing 59 K)) ^ n at hx
  rw [Ideal.span_singleton_pow, Ideal.mem_span_singleton] at hx
  obtain ⟨c, rfl⟩ := hx
  have hc : ‖c‖ ≤ 1 := by
    change ‖(c : ValuedCompletion 59 K)‖ ≤ 1
    rw [Valued.toNormedField.norm_le_one_iff]
    exact c.property
  rw [norm_mul]
  exact mul_le_of_le_one_right (norm_nonneg _) hc

/-- The norm topology on the local integer ring is exactly its
`lambda`-adic topology. -/
theorem lambdaIdeal59_isAdic : IsAdic (lambdaIdeal 59 K) := by
  rw [isAdic_iff]
  constructor
  · intro n
    apply ((lambdaIdeal 59 K) ^ n).toAddSubgroup.isOpen_of_mem_nhds
    have hpow_ne : (valuedCyclotomicLambdaInteger 59 K) ^ n ≠ 0 :=
      pow_ne_zero n (valuedCyclotomicLambdaInteger_ne_zero (p := 59) (K := K))
    have hnorm_pos :
        0 < ‖(valuedCyclotomicLambdaInteger 59 K) ^ n‖ :=
      norm_pos_iff.mpr hpow_ne
    refine Filter.mem_of_superset (Metric.ball_mem_nhds 0 hnorm_pos) ?_
    intro x hx
    apply (mem_lambdaIdeal_pow_iff_valuation_le K n x).mpr
    have hnorm :
        ‖(x : ValuedCompletion 59 K)‖ <
          ‖(((valuedCyclotomicLambdaInteger 59 K) ^ n :
            ValuedIntegerRing 59 K) : ValuedCompletion 59 K)‖ := by
      simpa [Metric.mem_ball, dist_zero] using hx
    exact (Valued.toNormedField.norm_lt_iff.mp hnorm).le
  · intro s hs
    obtain ⟨ε, hε, hball⟩ := Metric.mem_nhds_iff.mp hs
    obtain ⟨n, hn⟩ := exists_pow_lt_of_lt_one hε
      (norm_valuedCyclotomicLambdaInteger_lt_one K)
    refine ⟨n, ?_⟩
    intro x hx
    apply hball
    rw [Metric.mem_ball, dist_zero_right]
    exact (norm_le_norm_lambda_pow_of_mem K n hx).trans_lt (by
      simpa only [norm_pow] using hn)

/-- The actual local valuation integer ring is complete for the same
`lambda`-adic filtration used by the formal Dwork completion. -/
noncomputable instance instIsAdicCompleteLambdaIdealValuedInteger59 :
    IsAdicComplete (lambdaIdeal 59 K) (ValuedIntegerRing 59 K) :=
  (IsAdic.isAdicComplete_iff (lambdaIdeal59_isAdic K)).mpr
    ⟨inferInstance, inferInstance⟩

end Fermat.FiftyNine.Conservation.AdicCompleteValuedInteger59
