/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, Codex

# A meter-parametric lambda plus 827 Poitou--Tate engine

The first pointed Poitou--Tate implementation fixed its wild local state to
the explicit W1 receipt.  The genuine cyclotomic audit later showed that
this particular state has power-one character, whereas the irregular
reflected meter must have power-44 character.

The Poitou--Tate mechanism itself does not depend on that representative.
This file extracts it for an arbitrary actual roots-valued local Kummer
meter.  Its wild carrier is the smallest submodule containing all genuine
reflected global localizations and the supplied meter.  Global reciprocity
proves `range <= kernel`; the reverse inclusion remains the visible PT
exactness seam.  A cancelling state produces only an existential global
lift, and the unique allowed normalization freedom is retained as a unit
wild scale.

No meter is selected here, no character law is assumed, and no action,
provider, reciprocity law, or PT exactness theorem is manufactured.
-/
import Fermat.Exponents.FiftyNine.Conservation.RequiredCarrierW1PointedPoitouTate827

open scoped BigOperators NumberField

noncomputable section

set_option maxRecDepth 10000
set_option maxHeartbeats 2000000

namespace Fermat.FiftyNine.Conservation.LambdaMeterPointedPoitouTate827

open Fermat.Conservation
open Fermat.Conservation.SelmerEigenspace
open Fermat.Conservation.TatePairing
open CanonicalFullOrbitLocalPairing827
open CanonicalIrregularMode827
open CanonicalW1PointedIncidenceBridge827
open CanonicalW1PoitouTateReduction827
open ContinuousKummerTateLocalization59
open CyclotomicSelmerAction59
open DetectorWitness827
open ExplicitTameOrbitReciprocity827
open LambdaOrbitAffineKernelCriterion827
open LambdaOrbitLocalizationFiber827
open LocalKummerFrobeniusFactorization827
open NormalizedFullOrbitEigenprofile827
open PointedTateIncidence
open ScaledW1PointedPoitouTate827
open SplitPrimeFourier827
open VostokovLocalization59
open WildOrbitBoundaryComparison827

local instance : Fact (Nat.Prime 59) := ⟨by norm_num⟩

variable {K : Type} [Field K] [NumberField K]
  [IsCyclotomicExtension {59} ℚ K]
  [Invertible (Fintype.card GaloisIndex59 : PadicInt 59)]

omit [Invertible (Fintype.card GaloisIndex59 : PadicInt 59)] in
private theorem oldPrimal59_nsmul_eq_zero
    (x : OldPrimal59 (cyclotomicStrictSelmerRepresentation59 K)
      irregularCharacter59) :
    59 • x = 0 := by
  apply Subtype.ext
  exact SelmerEigenspace.p_nsmul_eq_zero x.1

noncomputable local instance instOldPrimal59ModuleZMod :
    Module (ZMod 59)
      (OldPrimal59 (cyclotomicStrictSelmerRepresentation59 K)
        irregularCharacter59) :=
  AddCommGroup.zmodModule oldPrimal59_nsmul_eq_zero

noncomputable local instance instQRelaxedReflectedDual827ModuleZMod :
    Module (ZMod 59)
      (QRelaxedReflectedDual827
        (cyclotomicQRelaxedSelmerRepresentation827 K)
        canonicalTeichmullerCharacter59 irregularCharacter59) :=
  AddCommGroup.zmodModule
    (qRelaxedReflectedDual827_nsmul_eq_zero
      (cyclotomicQRelaxedSelmerRepresentation827 K)
      canonicalTeichmullerCharacter59 irregularCharacter59)

/-! ## The carrier generated by one supplied meter -/

/-- The smallest honest local carrier containing every genuine reflected
global localization and one supplied wild meter. -/
def lambdaMeterRequiredCarrier827
    (meter : LambdaRootsContinuousH1 K) :
    Submodule (ZMod 59) (LambdaRootsContinuousH1 K) :=
  LinearMap.range
      (lambdaReflectedLocalizationLinear827 (K := K)
        canonicalTeichmullerCharacter59 irregularCharacter59) ⊔
    Submodule.span (ZMod 59) {meter}

omit [Invertible (Fintype.card GaloisIndex59 : PadicInt 59)] in
/-- Every genuine reflected global localization belongs to the carrier
generated by any supplied meter. -/
theorem lambdaReflectedLocalization_mem_meterRequiredCarrier827
    (meter : LambdaRootsContinuousH1 K)
    (y : QRelaxedReflectedDual827
      (cyclotomicQRelaxedSelmerRepresentation827 K)
      canonicalTeichmullerCharacter59 irregularCharacter59) :
    lambdaReflectedLocalizationLinear827 (K := K)
        canonicalTeichmullerCharacter59 irregularCharacter59 y ∈
      lambdaMeterRequiredCarrier827 (K := K) meter := by
  unfold lambdaMeterRequiredCarrier827
  apply (le_sup_left :
    LinearMap.range
        (lambdaReflectedLocalizationLinear827 (K := K)
          canonicalTeichmullerCharacter59 irregularCharacter59) ≤ _)
  exact ⟨y, rfl⟩

omit [Invertible (Fintype.card GaloisIndex59 : PadicInt 59)] in
/-- The supplied meter belongs to its generated carrier. -/
theorem meter_mem_lambdaMeterRequiredCarrier827
    (meter : LambdaRootsContinuousH1 K) :
    meter ∈ lambdaMeterRequiredCarrier827 (K := K) meter := by
  unfold lambdaMeterRequiredCarrier827
  apply (le_sup_right : Submodule.span (ZMod 59) {meter} ≤ _)
  exact Submodule.subset_span (Set.mem_singleton meter)

/-- Genuine lambda localization, with codomain restricted to the carrier
generated by the supplied meter. -/
noncomputable def lambdaMeterRequiredLocalization827
    (meter : LambdaRootsContinuousH1 K) :
    QRelaxedReflectedDual827
        (cyclotomicQRelaxedSelmerRepresentation827 K)
        canonicalTeichmullerCharacter59 irregularCharacter59 →ₗ[ZMod 59]
      lambdaMeterRequiredCarrier827 (K := K) meter where
  toFun y :=
    ⟨lambdaReflectedLocalizationLinear827 (K := K)
        canonicalTeichmullerCharacter59 irregularCharacter59 y,
      lambdaReflectedLocalization_mem_meterRequiredCarrier827
        (K := K) meter y⟩
  map_add' x y := by
    apply Subtype.ext
    exact (lambdaReflectedLocalizationLinear827 (K := K)
      canonicalTeichmullerCharacter59 irregularCharacter59).map_add x y
  map_smul' a y := by
    apply Subtype.ext
    exact (lambdaReflectedLocalizationLinear827 (K := K)
      canonicalTeichmullerCharacter59 irregularCharacter59).map_smul a y

omit [Invertible (Fintype.card GaloisIndex59 : PadicInt 59)] in
@[simp]
theorem lambdaMeterRequiredLocalization827_apply_coe
    (meter : LambdaRootsContinuousH1 K)
    (y : QRelaxedReflectedDual827
      (cyclotomicQRelaxedSelmerRepresentation827 K)
      canonicalTeichmullerCharacter59 irregularCharacter59) :
    (lambdaMeterRequiredLocalization827 (K := K) meter y :
      LambdaRootsContinuousH1 K) =
        lambdaReflectedLocalization827 (K := K)
          canonicalTeichmullerCharacter59 irregularCharacter59 y :=
  rfl

/-- The supplied meter as an element of its minimal required carrier. -/
noncomputable def meterRequiredElement827
    (meter : LambdaRootsContinuousH1 K) :
    lambdaMeterRequiredCarrier827 (K := K) meter :=
  ⟨meter, meter_mem_lambdaMeterRequiredCarrier827 (K := K) meter⟩

omit [Invertible (Fintype.card GaloisIndex59 : PadicInt 59)] in
@[simp]
theorem meterRequiredElement827_coe
    (meter : LambdaRootsContinuousH1 K) :
    (meterRequiredElement827 (K := K) meter :
      LambdaRootsContinuousH1 K) = meter :=
  rfl

/-! ## Meter-parametric simultaneous localization and boundary -/

/-- Simultaneous genuine localization into the meter-generated wild
carrier and the selected `827` coordinate. -/
noncomputable def lambdaMeterPointedLocalization827
    (meter : LambdaRootsContinuousH1 K) :
    QRelaxedReflectedDual827
        (cyclotomicQRelaxedSelmerRepresentation827 K)
        canonicalTeichmullerCharacter59 irregularCharacter59 →ₗ[ZMod 59]
      (lambdaMeterRequiredCarrier827 (K := K) meter × ZMod 59) :=
  (lambdaMeterRequiredLocalization827 (K := K) meter).prod
    (reflectedPointedLocalization827
      (cyclotomicQRelaxedSelmerRepresentation827 K)
      canonicalTeichmullerCharacter59 irregularCharacter59
      (tameOrbitBasePlace827 (K := K)))

omit [Invertible (Fintype.card GaloisIndex59 : PadicInt 59)] in
@[simp]
theorem lambdaMeterPointedLocalization827_apply
    (meter : LambdaRootsContinuousH1 K)
    (y : QRelaxedReflectedDual827
      (cyclotomicQRelaxedSelmerRepresentation827 K)
      canonicalTeichmullerCharacter59 irregularCharacter59) :
    lambdaMeterPointedLocalization827 (K := K) meter y =
      (lambdaMeterRequiredLocalization827 (K := K) meter y,
        reflectedPointedLocalization827
          (cyclotomicQRelaxedSelmerRepresentation827 K)
          canonicalTeichmullerCharacter59 irregularCharacter59
          (tameOrbitBasePlace827 (K := K)) y) :=
  rfl

/-- The two-charge PT boundary with the lambda input honestly restricted to
the carrier generated by the supplied meter. -/
noncomputable def lambdaMeterPointedPoitouTateBoundary827
    (meter : LambdaRootsContinuousH1 K) :
    (lambdaMeterRequiredCarrier827 (K := K) meter × ZMod 59) →ₗ[ZMod 59]
      Module.Dual (ZMod 59)
        (OldPrimal59 (cyclotomicStrictSelmerRepresentation59 K)
          irregularCharacter59) where
  toFun state :=
    (irregularPrimalLambdaTestMap827 (K := K)).flip
        (state.1 : LambdaRootsContinuousH1 K) +
      state.2 • irregularPrimalFrobeniusFunctional827 (K := K)
  map_add' left right := by
    ext x
    simp
    ring
  map_smul' a state := by
    ext x
    simp
    ring

@[simp]
theorem lambdaMeterPointedPoitouTateBoundary827_apply
    (meter : LambdaRootsContinuousH1 K)
    (state : lambdaMeterRequiredCarrier827 (K := K) meter × ZMod 59)
    (x : OldPrimal59 (cyclotomicStrictSelmerRepresentation59 K)
      irregularCharacter59) :
    lambdaMeterPointedPoitouTateBoundary827 (K := K) meter state x =
      irregularPrimalLambdaTestMap827 (K := K) x
          (state.1 : LambdaRootsContinuousH1 K) +
        state.2 * irregularPrimalFrobeniusFunctional827 (K := K) x :=
  rfl

/-- Restriction changes only the type: the meter-carrier boundary is the
ambient boundary after forgetting its subtype proof. -/
theorem lambdaMeterPointedPoitouTateBoundary827_eq_ambient
    (meter : LambdaRootsContinuousH1 K)
    (state : lambdaMeterRequiredCarrier827 (K := K) meter × ZMod 59) :
    lambdaMeterPointedPoitouTateBoundary827 (K := K) meter state =
      lambdaPointedPoitouTateBoundary827 (K := K)
        ((state.1 : LambdaRootsContinuousH1 K), state.2) :=
  rfl

/-! ## Exactness and existential lifting -/

/-- Global reciprocity proves the easy half of PT exactness for every
supplied local meter. -/
theorem lambdaMeterPointedLocalization827_range_le_boundary_ker
    (meter : LambdaRootsContinuousH1 K)
    (reciprocity : GlobalReciprocityLaw
      (canonicalFullOrbitLocalPairing827 K
        canonicalTeichmullerCharacter59 irregularCharacter59)) :
    LinearMap.range (lambdaMeterPointedLocalization827 (K := K) meter) ≤
      LinearMap.ker
        (lambdaMeterPointedPoitouTateBoundary827 (K := K) meter) := by
  rintro _ ⟨y, rfl⟩
  rw [LinearMap.mem_ker]
  have hambient :=
    lambdaPointedLocalization827_range_le_poitouTateBoundary_ker
      (K := K) reciprocity
      (show lambdaPointedLocalization827 (K := K) y ∈
        LinearMap.range (lambdaPointedLocalization827 (K := K)) from
          ⟨y, rfl⟩)
  rw [LinearMap.mem_ker] at hambient
  exact hambient

/-- With `range <= kernel` proved by reciprocity, full PT exactness is
equivalent to the one missing reverse inclusion. -/
theorem lambdaMeterPointedLocalization827_range_eq_ker_iff_kernel_lifts
    (meter : LambdaRootsContinuousH1 K)
    (reciprocity : GlobalReciprocityLaw
      (canonicalFullOrbitLocalPairing827 K
        canonicalTeichmullerCharacter59 irregularCharacter59)) :
    LinearMap.range (lambdaMeterPointedLocalization827 (K := K) meter) =
        LinearMap.ker
          (lambdaMeterPointedPoitouTateBoundary827 (K := K) meter) ↔
      LinearMap.ker
          (lambdaMeterPointedPoitouTateBoundary827 (K := K) meter) ≤
        LinearMap.range
          (lambdaMeterPointedLocalization827 (K := K) meter) := by
  constructor
  · intro h
    rw [h]
  · intro h
    exact le_antisymm
      (lambdaMeterPointedLocalization827_range_le_boundary_ker
        meter reciprocity)
      h

/-- Reverse PT exactness lifts any cancelling meter state.  The result is
existential; no global lift is selected. -/
theorem exists_reflected_lift_of_meter_pt_kernel_lifts
    (meter : LambdaRootsContinuousH1 K)
    (kernel_lifts :
      LinearMap.ker
          (lambdaMeterPointedPoitouTateBoundary827 (K := K) meter) ≤
        LinearMap.range
          (lambdaMeterPointedLocalization827 (K := K) meter))
    (r : lambdaMeterRequiredCarrier827 (K := K) meter) (a : ZMod 59)
    (cancels :
      lambdaMeterPointedPoitouTateBoundary827 (K := K) meter (r, a) = 0) :
    ∃ y : QRelaxedReflectedDual827
        (cyclotomicQRelaxedSelmerRepresentation827 K)
        canonicalTeichmullerCharacter59 irregularCharacter59,
      lambdaMeterRequiredLocalization827 (K := K) meter y = r ∧
        reflectedPointedLocalization827
          (cyclotomicQRelaxedSelmerRepresentation827 K)
          canonicalTeichmullerCharacter59 irregularCharacter59
          (tameOrbitBasePlace827 (K := K)) y = a := by
  have hker : (r, a) ∈
      LinearMap.ker
        (lambdaMeterPointedPoitouTateBoundary827 (K := K) meter) :=
    LinearMap.mem_ker.mpr cancels
  obtain ⟨y, hy⟩ := kernel_lifts hker
  exact ⟨y, congrArg Prod.fst hy, congrArg Prod.snd hy⟩

/-! ## The single-scale meter consumer -/

/-- The wild boundary functional obtained by currying the actual local cup
against a supplied meter on the genuine irregular primal test space. -/
noncomputable def lambdaMeterPrimalBoundaryFunctional827
    (meter : LambdaRootsContinuousH1 K) :
    Module.Dual (ZMod 59)
      (OldPrimal59 (cyclotomicStrictSelmerRepresentation59 K)
        irregularCharacter59) :=
  (irregularPrimalLambdaTestMap827 (K := K)).flip meter

omit [Invertible (Fintype.card GaloisIndex59 : PadicInt 59)] in
@[simp]
theorem lambdaMeterPrimalBoundaryFunctional827_apply
    (meter : LambdaRootsContinuousH1 K)
    (x : OldPrimal59 (cyclotomicStrictSelmerRepresentation59 K)
      irregularCharacter59) :
    lambdaMeterPrimalBoundaryFunctional827 (K := K) meter x =
      irregularPrimalLambdaTestMap827 (K := K) x meter :=
  rfl

/-- A normalized reflected global lift for an arbitrary supplied local
meter, retaining the one honest unit-valued wild scale. -/
structure NormalizedOrbitScaledLambdaMeterLift827
    (meter : LambdaRootsContinuousH1 K) where
  wildScale : (ZMod 59)ˣ
  carrier : QRelaxedReflectedDual827
    (cyclotomicQRelaxedSelmerRepresentation827 K)
    canonicalTeichmullerCharacter59 irregularCharacter59
  lambda_eq :
    lambdaMeterRequiredLocalization827 (K := K) meter carrier =
      (wildScale : ZMod 59) • meterRequiredElement827 (K := K) meter
  selected_eq :
    reflectedPointedLocalization827
        (cyclotomicQRelaxedSelmerRepresentation827 K)
        canonicalTeichmullerCharacter59 irregularCharacter59
        (tameOrbitBasePlace827 (K := K)) carrier = 1

/-- Evaluating the two-charge boundary at a scaled supplied meter and the
normalized `827` coordinate gives the scaled wild functional plus the
local Frobenius functional. -/
theorem lambdaMeterPointedPoitouTateBoundary827_scaledMeter_one
    (meter : LambdaRootsContinuousH1 K) (scale : ZMod 59) :
    lambdaMeterPointedPoitouTateBoundary827 (K := K) meter
        (scale • meterRequiredElement827 (K := K) meter, 1) =
      scale • lambdaMeterPrimalBoundaryFunctional827 (K := K) meter +
        irregularPrimalFrobeniusFunctional827 (K := K) := by
  apply LinearMap.ext
  intro x
  simp only [lambdaMeterPointedPoitouTateBoundary827_apply, one_mul,
    LinearMap.add_apply, LinearMap.smul_apply]
  change irregularPrimalLambdaTestMap827 (K := K) x (scale • meter) +
      irregularPrimalFrobeniusFunctional827 (K := K) x =
    scale • irregularPrimalLambdaTestMap827 (K := K) x meter +
      irregularPrimalFrobeniusFunctional827 (K := K) x
  rw [map_smul]

/-- A cancelling scaled-meter state and reverse PT exactness produce an
existential normalized global lift. -/
theorem nonempty_scaledLambdaMeterLift827_of_boundary_cancels
    (meter : LambdaRootsContinuousH1 K)
    (kernel_lifts :
      LinearMap.ker
          (lambdaMeterPointedPoitouTateBoundary827 (K := K) meter) ≤
        LinearMap.range
          (lambdaMeterPointedLocalization827 (K := K) meter))
    (scale : (ZMod 59)ˣ)
    (cancels :
      lambdaMeterPointedPoitouTateBoundary827 (K := K) meter
        ((scale : ZMod 59) • meterRequiredElement827 (K := K) meter, 1) =
          0) :
    Nonempty (NormalizedOrbitScaledLambdaMeterLift827
      (K := K) meter) := by
  obtain ⟨y, hlambda, hselected⟩ :=
    exists_reflected_lift_of_meter_pt_kernel_lifts
      (K := K) meter kernel_lifts
      ((scale : ZMod 59) • meterRequiredElement827 (K := K) meter)
      1 cancels
  exact ⟨⟨scale, y, hlambda, hselected⟩⟩

/-- **Meter-parametric scaled PT consumer.**  If the supplied meter's wild
functional is a unit multiple of the local Frobenius functional, the inverse
unit is the unique normalization scale that cancels the two charges. -/
theorem nonempty_scaledLambdaMeterLift827_of_pt_and_unitComparison
    (meter : LambdaRootsContinuousH1 K)
    (kernel_lifts :
      LinearMap.ker
          (lambdaMeterPointedPoitouTateBoundary827 (K := K) meter) ≤
        LinearMap.range
          (lambdaMeterPointedLocalization827 (K := K) meter))
    (comparisonUnit : (ZMod 59)ˣ)
    (comparison :
      lambdaMeterPrimalBoundaryFunctional827 (K := K) meter =
        (comparisonUnit : ZMod 59) •
          irregularPrimalFrobeniusFunctional827 (K := K)) :
    Nonempty (NormalizedOrbitScaledLambdaMeterLift827
      (K := K) meter) := by
  let scale := cancelingWildScale827 comparisonUnit
  apply nonempty_scaledLambdaMeterLift827_of_boundary_cancels
    (K := K) meter kernel_lifts scale
  rw [lambdaMeterPointedPoitouTateBoundary827_scaledMeter_one,
    comparison, smul_smul, cancelingWildScale827_mul]
  simp

/-! ## Exact specialization to the historical ambient W1 receipt -/

omit [Invertible (Fintype.card GaloisIndex59 : PadicInt 59)] in
/-- Supplying the old W1 right factor recovers its previously defined
minimal required carrier definitionally.  This specialization is retained
only as a compatibility theorem; it does not repair the character mismatch
of that factor. -/
theorem lambdaMeterRequiredCarrier827_w1_eq :
    lambdaMeterRequiredCarrier827 (K := K)
        (twistedLambdaCupReceipt59 K).reflected =
      LambdaReflectedLocalSeatAudit827.lambdaReflectedRequiredCarrier827
        (K := K) :=
  rfl

omit [Invertible (Fintype.card GaloisIndex59 : PadicInt 59)] in
/-- The generic meter functional specializes exactly to the old ambient W1
functional. -/
theorem lambdaMeterPrimalBoundaryFunctional827_w1_eq :
    lambdaMeterPrimalBoundaryFunctional827 (K := K)
        (twistedLambdaCupReceipt59 K).reflected =
      w1ReceiptPrimalBoundaryFunctional827 (K := K) := by
  apply LinearMap.ext
  intro x
  rfl

/-! ## Kernel-trust audit -/

/--
info: 'Fermat.FiftyNine.Conservation.LambdaMeterPointedPoitouTate827.lambdaMeterPointedLocalization827_range_le_boundary_ker' depends on axioms: [propext,
 Classical.choice,
 Quot.sound]
-/
#guard_msgs in
#print axioms lambdaMeterPointedLocalization827_range_le_boundary_ker

/--
info: 'Fermat.FiftyNine.Conservation.LambdaMeterPointedPoitouTate827.lambdaMeterPointedLocalization827_range_eq_ker_iff_kernel_lifts' depends on axioms: [propext,
 Classical.choice,
 Quot.sound]
-/
#guard_msgs in
#print axioms lambdaMeterPointedLocalization827_range_eq_ker_iff_kernel_lifts

/--
info: 'Fermat.FiftyNine.Conservation.LambdaMeterPointedPoitouTate827.nonempty_scaledLambdaMeterLift827_of_pt_and_unitComparison' depends on axioms: [propext,
 Classical.choice,
 Quot.sound]
-/
#guard_msgs in
#print axioms nonempty_scaledLambdaMeterLift827_of_pt_and_unitComparison

/--
info: 'Fermat.FiftyNine.Conservation.LambdaMeterPointedPoitouTate827.lambdaMeterPrimalBoundaryFunctional827_w1_eq' depends on axioms: [propext,
 Classical.choice,
 Quot.sound]
-/
#guard_msgs in
#print axioms lambdaMeterPrimalBoundaryFunctional827_w1_eq

end Fermat.FiftyNine.Conservation.LambdaMeterPointedPoitouTate827
