/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, Fable

# C2: generated credit capacity

Credit is generated by a periodic recursion, not by a list of entries.  A
cycle with `rank + 1` nodes supplies `rank` successive edge ratios.  Those
edges generate a subgroup, and C2 defines capacity to be its finite relative
index in a stated ambient ledger.

This is route-neutral group theory.  Numerical certificates may prove an
equality about `capacity`; neither a certificate nor its matrix occurs in the
definition.
-/
import Mathlib.GroupTheory.Index
import Mathlib.Logic.Function.Iterate

namespace Fermat.Conservation.Credit

/-- One seed and one recursion, closing after `rank + 1` steps.  The extra
node is the generator seed in the level-3 `rank + 1` anatomy. -/
structure Cycle (α : Type*) where
  rank : ℕ
  seed : α
  step : α → α
  closes : (step^[rank + 1]) seed = seed

namespace Cycle

variable {α G : Type*}

/-- The `n`th node is produced by iterating the single recursion from its
seed. -/
def point (cycle : Cycle α) (n : ℕ) : α :=
  (cycle.step^[n]) cycle.seed

@[simp]
theorem point_zero (cycle : Cycle α) :
    cycle.point 0 = cycle.seed := by
  simp [point]

theorem point_succ (cycle : Cycle α) (n : ℕ) :
    cycle.point (n + 1) = cycle.step (cycle.point n) := by
  simpa only [point, Nat.succ_eq_add_one] using
    Function.iterate_succ_apply' cycle.step n cycle.seed

/-- The recursion returns to its seed only after the displayed closing
step.  Exactness of the period is a separate arithmetic fact at each
instantiation. -/
theorem point_closes (cycle : Cycle α) :
    cycle.point (cycle.rank + 1) = cycle.seed :=
  cycle.closes

section Group

variable [Group G]

/-- Realizing the nodes in a group turns each successive pair into one
generated edge ratio.  There are `rank` such edges; none is supplied
independently. -/
def edge (cycle : Cycle α) (realize : α → G)
    (i : Fin cycle.rank) : G :=
  realize (cycle.point (i.val + 1)) *
    (realize (cycle.point i.val))⁻¹

/-- The subgroup generated by the orbit edges is the generated
sub-ledger. -/
def generatedSubledger (cycle : Cycle α) (realize : α → G) :
    Subgroup G :=
  Subgroup.closure (Set.range (cycle.edge realize))

theorem edge_mem_generatedSubledger (cycle : Cycle α)
    (realize : α → G) (i : Fin cycle.rank) :
    cycle.edge realize i ∈ cycle.generatedSubledger realize :=
  Subgroup.subset_closure (Set.mem_range_self i)

/-- The generated edge subgroup together with structurally named
collateral, such as torsion units. -/
def generatedSubledgerWith (cycle : Cycle α) (realize : α → G)
    (collateral : Subgroup G) : Subgroup G :=
  cycle.generatedSubledger realize ⊔ collateral

/-- The raw C2 index.  It is defined before any claim that the index is
finite or has a particular numerical value. -/
noncomputable def capacityIndex (cycle : Cycle α) (realize : α → G)
    (collateral ambient : Subgroup G) : ℕ :=
  (cycle.generatedSubledgerWith realize collateral).relIndex ambient

theorem capacityIndex_eq_relIndex (cycle : Cycle α)
    (realize : α → G) (collateral ambient : Subgroup G) :
    cycle.capacityIndex realize collateral ambient =
      (cycle.generatedSubledgerWith realize collateral).relIndex ambient :=
  rfl

/-- A node-pair transfer.  Reversing the pair gives the inverse entry, so
debit and receivable are the two orientations of one generated object. -/
def transfer (cycle : Cycle α) (realize : α → G)
    (i j : Fin cycle.rank) : G :=
  cycle.edge realize i * (cycle.edge realize j)⁻¹

@[simp]
theorem transfer_self (cycle : Cycle α) (realize : α → G)
    (i : Fin cycle.rank) :
    cycle.transfer realize i i = 1 := by
  simp [transfer]

theorem transfer_opposite (cycle : Cycle α) (realize : α → G)
    (i j : Fin cycle.rank) :
    cycle.transfer realize j i =
      (cycle.transfer realize i j)⁻¹ := by
  simp [transfer]

/-- C2 data names the ambient ledger and proves that the generated
sub-ledger has genuinely finite index inside it. -/
structure CapacityData (cycle : Cycle α) (realize : α → G) where
  ambient : Subgroup G
  generated_le : cycle.generatedSubledger realize ≤ ambient
  finite :
    (cycle.generatedSubledger realize).IsFiniteRelIndex ambient

namespace CapacityData

variable {cycle : Cycle α} {realize : α → G}

/-- **C2 capacity.** This definition precedes, and is independent of, every
finite certificate: it is the index of the sub-ledger generated by the
orbit edges. -/
noncomputable def capacity
    (data : CapacityData cycle realize) : ℕ :=
  (cycle.generatedSubledger realize).relIndex data.ambient

theorem capacity_eq_relIndex
    (data : CapacityData cycle realize) :
    data.capacity =
      (cycle.generatedSubledger realize).relIndex data.ambient :=
  rfl

/-- A finite capacity cannot be the sentinel value zero used by `relIndex`
for an infinite quotient. -/
theorem capacity_pos (data : CapacityData cycle realize) :
    0 < data.capacity := by
  apply Nat.pos_of_ne_zero
  exact data.finite.relIndex_ne_zero

end CapacityData

/-- Certificate data check a previously generated capacity; the claimed
number is not used to define the sub-ledger or its index. -/
structure CapacityCertificate
    {cycle : Cycle α} {realize : α → G}
    (data : CapacityData cycle realize) (claimed : ℕ) : Prop where
  checks : data.capacity = claimed

theorem CapacityCertificate.sound
    {cycle : Cycle α} {realize : α → G}
    {data : CapacityData cycle realize} {claimed : ℕ}
    (certificate : CapacityCertificate data claimed) :
    data.capacity = claimed :=
  certificate.checks

/-- A raw-index certificate likewise checks an index already defined from
the generator, collateral, and ambient ledger. -/
structure IndexCertificate
    (cycle : Cycle α) (realize : α → G)
    (collateral ambient : Subgroup G) (claimed : ℕ) : Prop where
  checks :
    cycle.capacityIndex realize collateral ambient = claimed

theorem IndexCertificate.sound
    {cycle : Cycle α} {realize : α → G}
    {collateral ambient : Subgroup G} {claimed : ℕ}
    (certificate :
      IndexCertificate cycle realize collateral ambient claimed) :
    cycle.capacityIndex realize collateral ambient = claimed :=
  certificate.checks

end Group

section MultiplicationCycle

variable [Group G]

/-- Iterating left multiplication is a power of the one multiplier. -/
theorem iterate_mul_left (g x : G) (n : ℕ) :
    ((fun y : G => g * y)^[n]) x = g ^ n * x := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [Function.iterate_succ_apply', ih]
      simp only [← mul_assoc, ← pow_succ']

/-- A group element whose displayed power is one produces a cycle from the
single seed `1` and the single recursion "multiply by `g`". -/
def ofMul (rank : ℕ) (g : G) (hclose : g ^ (rank + 1) = 1) :
    Cycle G where
  rank := rank
  seed := 1
  step := fun x => g * x
  closes := by
    rw [iterate_mul_left, hclose, one_mul]

@[simp]
theorem ofMul_point (rank : ℕ) (g : G)
    (hclose : g ^ (rank + 1) = 1) (n : ℕ) :
    (ofMul rank g hclose).point n = g ^ n := by
  simp [point, ofMul, iterate_mul_left]

end MultiplicationCycle

end Cycle

end Fermat.Conservation.Credit
