/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, Fable

# W1: generated real cyclotomic nodes

The actual multiplicative nodes read by credit flow are generated directly
from a primitive root: take the geometric cyclotomic unit at a residue and
fold it with complex conjugation.  The fold is bundled as a homomorphism, so
product conservation is structural rather than a supplied law.

This file contains no conductor-specific data.  A per-prime instance only
chooses an indexed residue orbit.
-/
import Fermat.Conservation.Credit.DepthFlow
import Mathlib.NumberTheory.NumberField.CMField
import Mathlib.RingTheory.RootsOfUnity.CyclotomicUnits

open scoped NumberField

namespace Fermat.Conservation.Credit.Flow

open NumberField

variable {p : ℕ} [Fact p.Prime]
variable {K : Type*} [Field K] [NumberField K]
  [IsCyclotomicExtension {p} ℚ K]

/-- The geometric cyclotomic unit at one nonzero residue node. -/
noncomputable def cyclotomicOrbitNodeUnit
    {ζ : K} (hζ : IsPrimitiveRoot ζ p) (a : (ZMod p)ˣ) : (𝓞 K)ˣ :=
  (hζ.toInteger_isPrimitiveRoot.geom_sum_isUnit
    (Fact.out : p.Prime).one_lt (ZMod.val_coe_unit_coprime a)).unit

omit [NumberField K] [IsCyclotomicExtension {p} ℚ K] in
@[simp] theorem cyclotomicOrbitNodeUnit_val
    {ζ : K} (hζ : IsPrimitiveRoot ζ p) (a : (ZMod p)ˣ) :
    (cyclotomicOrbitNodeUnit hζ a : 𝓞 K) =
      ∑ i ∈ Finset.range (a : ZMod p).val, hζ.toInteger ^ i :=
  rfl

section Real

variable [NumberField.IsCMField K]

/-- Fold a unit with its conjugate into the real-unit subgroup. -/
noncomputable def realProjection (u : (𝓞 K)ˣ) :
    NumberField.IsCMField.realUnits K :=
  ⟨u * NumberField.IsCMField.unitsComplexConj K u, by
    rw [← NumberField.IsCMField.unitsComplexConj_eq_self_iff]
    simp only [map_mul]
    apply Units.ext
    apply NumberField.RingOfIntegers.ext
    simp [mul_comm]⟩

/-- The real node generated by a nonzero residue. -/
noncomputable def realCyclotomicOrbitNode
    {ζ : K} (hζ : IsPrimitiveRoot ζ p) (a : (ZMod p)ˣ) :
    NumberField.IsCMField.realUnits K :=
  realProjection (cyclotomicOrbitNodeUnit hζ a)

omit [IsCyclotomicExtension {p} ℚ K] in
@[simp] theorem realCyclotomicOrbitNode_val
    {ζ : K} (hζ : IsPrimitiveRoot ζ p) (a : (ZMod p)ˣ) :
    (realCyclotomicOrbitNode hζ a :
        (𝓞 K)ˣ) =
      cyclotomicOrbitNodeUnit hζ a *
        NumberField.IsCMField.unitsComplexConj K
          (cyclotomicOrbitNodeUnit hζ a) :=
  rfl

/-- Product conservation for the real projection. -/
theorem realProjection_mul (u v : (𝓞 K)ˣ) :
    realProjection (u * v) =
      realProjection u * realProjection v := by
  apply Subtype.ext
  change
    (u * v) *
        NumberField.IsCMField.unitsComplexConj K (u * v) =
      (u * NumberField.IsCMField.unitsComplexConj K u) *
        (v * NumberField.IsCMField.unitsComplexConj K v)
  rw [map_mul]
  ac_rfl

@[simp]
theorem realProjection_one :
    realProjection (1 : (𝓞 K)ˣ) = 1 := by
  apply Subtype.ext
  change
    (1 : (𝓞 K)ˣ) *
        NumberField.IsCMField.unitsComplexConj K 1 = 1
  simp

/-- Folding with conjugation, bundled as the product-conserving map read by
the generated flow. -/
noncomputable def realProjectionHom :
    (𝓞 K)ˣ →* NumberField.IsCMField.realUnits K where
  toFun := realProjection
  map_one' := realProjection_one
  map_mul' := realProjection_mul

end Real

end Fermat.Conservation.Credit.Flow
