/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, Fable

# W1: integral cyclotomic depth

Mathlib's integral cyclotomic power basis turns depth `2 * p` at `1 - ζ`
into literal divisibility by `p ^ 2` in the global ring of integers.  The
same basis then represents the quotient by an integral polynomial, so a
depth error can be replaced by `p²` times a polynomial correction and the
prime cyclotomic polynomial divides the corrected relation exactly.

This is the ramification primitive used by the generator-derived flow.  It
is generic over every prime and imports no classical Vandiver assembly.
-/
import Fermat.Conservation.Credit.Flow
import Mathlib.NumberTheory.NumberField.Cyclotomic.Ideal

open scoped NumberField

namespace Fermat.Conservation.Credit.Flow

open Ideal NumberField Polynomial

variable {p : ℕ} [Fact p.Prime]
variable {K : Type*} [Field K] [NumberField K]
  [IsCyclotomicExtension {p} ℚ K]
variable {ζ : K} (hζ : IsPrimitiveRoot ζ p)

/-- In a prime cyclotomic field, the principal ideal generated by `p` is
the `(p - 1)`st power of the ideal generated by `1 - ζ`. -/
theorem span_prime_eq_span_one_sub_pow_pred :
    Ideal.span ({(p : 𝓞 K)} : Set (𝓞 K)) =
      Ideal.span ({(1 : 𝓞 K) - hζ.toInteger} : Set (𝓞 K)) ^ (p - 1) := by
  letI : NeZero p := ⟨(Fact.out : p.Prime).ne_zero⟩
  letI : IsCyclotomicExtension {p ^ (0 + 1)} ℚ K := by
    simpa using (inferInstance : IsCyclotomicExtension {p} ℚ K)
  have hζ' : IsPrimitiveRoot ζ (p ^ (0 + 1)) := by
    simpa using hζ
  have hram :=
    IsCyclotomicExtension.Rat.map_eq_span_zeta_sub_one_pow
      p 0 hζ'
  have hfin : Module.finrank ℚ K = p - 1 := by
    rw [IsCyclotomicExtension.finrank (K := ℚ) (L := K)
      (Polynomial.cyclotomic.irreducible_rat
        (Fact.out : p.Prime).pos),
      Nat.totient_prime (Fact.out : p.Prime)]
  have hram' :
      Ideal.span ({(p : 𝓞 K)} : Set (𝓞 K)) =
        Ideal.span ({hζ.toInteger - 1} : Set (𝓞 K)) ^ (p - 1) := by
    simpa only [hfin, Ideal.map_span, Set.image_singleton,
      map_natCast] using hram
  have hspan :
      Ideal.span ({(1 : 𝓞 K) - hζ.toInteger} : Set (𝓞 K)) =
        Ideal.span ({hζ.toInteger - 1} : Set (𝓞 K)) := by
    rw [show (1 : 𝓞 K) - hζ.toInteger =
      -(hζ.toInteger - 1) by ring, Ideal.span_singleton_neg]
  rw [hram', hspan]

/-- Two prime cyclotomic depth blocks contain a literal square of the
rational prime. -/
theorem span_one_sub_pow_two_mul_pred_eq_span_prime_sq :
    Ideal.span ({(1 : 𝓞 K) - hζ.toInteger} : Set (𝓞 K)) ^
        (2 * (p - 1)) =
      Ideal.span ({(p : 𝓞 K) ^ 2} : Set (𝓞 K)) := by
  rw [show 2 * (p - 1) = (p - 1) * 2 by omega, pow_mul]
  rw [← span_prime_eq_span_one_sub_pow_pred hζ]
  exact Ideal.span_singleton_pow (p : 𝓞 K) 2

/-- Exact depth `2 * p` forces literal divisibility by `p²`; the two
surplus lambda factors are harmless. -/
theorem prime_sq_dvd_of_one_sub_pow_two_mul_prime_dvd
    {x : 𝓞 K}
    (hx : ((1 : 𝓞 K) - hζ.toInteger) ^ (2 * p) ∣ x) :
    (p : 𝓞 K) ^ 2 ∣ x := by
  have hxmem :
      x ∈ Ideal.span
        ({((1 : 𝓞 K) - hζ.toInteger) ^ (2 * p)} : Set (𝓞 K)) :=
    Ideal.mem_span_singleton.mpr hx
  rw [← Ideal.span_singleton_pow] at hxmem
  have hle : 2 * (p - 1) ≤ 2 * p := by omega
  have hxmem' :
      x ∈ Ideal.span ({(1 : 𝓞 K) - hζ.toInteger} : Set (𝓞 K)) ^
        (2 * (p - 1)) :=
    Ideal.pow_le_pow_right hle hxmem
  rw [span_one_sub_pow_two_mul_pred_eq_span_prime_sq hζ] at hxmem'
  exact Ideal.mem_span_singleton.mp hxmem'

/-- A depth error can be removed by `p²` times an integral polynomial in
the primitive root.  The corrected polynomial then vanishes exactly. -/
theorem exists_polynomial_correction_of_depth
    (A : ℤ[X])
    (hdepth :
      ((1 : 𝓞 K) - hζ.toInteger) ^ (2 * p) ∣
        Polynomial.eval₂ (algebraMap ℤ (𝓞 K)) hζ.toInteger A) :
    ∃ H : ℤ[X],
      Polynomial.eval₂ (algebraMap ℤ (𝓞 K)) hζ.toInteger
        (A - Polynomial.C ((p : ℤ) ^ 2) * H) = 0 := by
  obtain ⟨y, hy⟩ :=
    prime_sq_dvd_of_one_sub_pow_two_mul_prime_dvd hζ hdepth
  obtain ⟨H, hH⟩ :=
    hζ.integralPowerBasis.exists_eq_aeval' y
  have hH' :
      y = Polynomial.eval₂ (algebraMap ℤ (𝓞 K))
        hζ.toInteger H := by
    simpa only [hζ.integralPowerBasis_gen, Polynomial.aeval_def] using hH
  refine ⟨H, ?_⟩
  rw [Polynomial.eval₂_sub, Polynomial.eval₂_mul,
    Polynomial.eval₂_C]
  simp only [map_pow, map_natCast]
  rw [hy, hH']
  ring

/-- Consequently the exact correction is a multiple of the prime
cyclotomic polynomial over `ℤ`. -/
theorem exists_cyclotomic_dvd_correction_of_depth
    (A : ℤ[X])
    (hdepth :
      ((1 : 𝓞 K) - hζ.toInteger) ^ (2 * p) ∣
        Polynomial.eval₂ (algebraMap ℤ (𝓞 K)) hζ.toInteger A) :
    ∃ H : ℤ[X],
      Polynomial.cyclotomic p ℤ ∣
        A - Polynomial.C ((p : ℤ) ^ 2) * H := by
  obtain ⟨H, hroot⟩ :=
    exists_polynomial_correction_of_depth hζ A hdepth
  refine ⟨H, ?_⟩
  have hroot' :
      Polynomial.aeval hζ.toInteger
        (A - Polynomial.C ((p : ℤ) ^ 2) * H) = 0 := by
    simpa only [Polynomial.aeval_def] using hroot
  have hdvd :
      minpoly ℤ hζ.toInteger ∣
        A - Polynomial.C ((p : ℤ) ^ 2) * H :=
    minpoly.isIntegrallyClosed_dvd
      (RingOfIntegers.isIntegral hζ.toInteger) hroot'
  have hmin :
      minpoly ℤ hζ.toInteger = Polynomial.cyclotomic p ℤ := by
    have hmap :=
      minpoly.algHom_eq
        (IsScalarTower.toAlgHom ℤ (𝓞 K) K)
        RingOfIntegers.coe_injective hζ.toInteger
    calc
      minpoly ℤ hζ.toInteger =
          minpoly ℤ
            ((IsScalarTower.toAlgHom ℤ (𝓞 K) K) hζ.toInteger) :=
        hmap.symm
      _ = minpoly ℤ ζ := by rfl
      _ = Polynomial.cyclotomic p ℤ :=
        (Polynomial.cyclotomic_eq_minpoly hζ
          (Fact.out : p.Prime).pos).symm
  rwa [hmin] at hdvd

end Fermat.Conservation.Credit.Flow
