/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, Fable

# W3: generic flow forcing

The high flow is read first in character coordinates.  Its eigenvalue in
row `k` is the numerator of the coefficient generated at index
`2 * (k + 1) * p`.  A cube-free eigenvalue turns the integral high-flow
congruence into vanishing modulo `p`; the generator-derived C5 gauge then
turns character-coordinate vanishing into raw exponent divisibility.

Only the cube-freeness statement is certificate data.  The character
matrix, its integral lift, and every eigenvalue are definitions derived from
the gauge generator and the Bernoulli generator.
-/
import Fermat.Conservation.Credit.Flow
import Fermat.Conservation.Credit.Gauge
import Fermat.Conservation.Credit.Repayment

open scoped BigOperators

namespace Fermat.Conservation.Credit.Flow

open Gauge

/-- The reusable per-prime assembly boundary.

The forcing theorem uses only `gauge`, but a campaign instance records the
generation tower, the independently checked lamp, and its irregular row in
the same object.  Thus a later prime supplies one record instead of adding
numeric facts to the generic core. -/
structure CreditData (p : ℕ) where
  gauge : GaugeData p
  generationSeed : ℕ
  generationMiddle : ℕ
  innerStep : ℕ
  outerStep : ℕ
  rank_generated :
    gauge.rank = innerStep * generationSeed
  middle_generated :
    generationMiddle = innerStep * generationSeed + 1
  conductor_generated :
    p = outerStep * generationMiddle + 1
  attestationPrime : ℕ
  attestationPrime_prime : attestationPrime.Prime
  attestationRoot : ZMod attestationPrime
  attestationRootValue : ℕ
  attestationRoot_value :
    attestationRoot = attestationRootValue
  attestationRoot_order :
    orderOf attestationRoot = p
  irregularIndex : ℕ
  irregularRow : Fin gauge.rank
  irregularIndex_eq_row :
    irregularIndex = 2 * (irregularRow.val + 1)

/-- The high Bernoulli index selected by row `k` of the credit flow. -/
def highIndex {p : ℕ} {data : GaugeData p}
    (k : Fin data.rank) : ℕ :=
  2 * (k.val + 1) * p

/-- The integral eigenvalue generated in row `k`.  It is a definition from
the Bernoulli generator, not a field of the certificate. -/
def highEigenvalue {p : ℕ} {data : GaugeData p}
    (k : Fin data.rank) : ℤ :=
  (bernoulli (highIndex k)).num

/-- An integral lift of the generator-derived character coordinate.
Reducing this expression modulo `p` is exactly the C5 gauge transform. -/
def integralCharacterCoordinate {p : ℕ} (data : GaugeData p)
    (raw : Fin data.rank → ℤ) (row : Fin data.rank) : ℤ :=
  ∑ i, (data.characterMatrix row i).val * raw i

/-- The integral coordinate above really lifts the generator-derived
finite-field gauge coordinate. -/
theorem intCast_integralCharacterCoordinate {p : ℕ}
    (data : GaugeData p) (raw : Fin data.rank → ℤ)
    (row : Fin data.rank) :
    ((integralCharacterCoordinate data raw row : ℤ) : ZMod p) =
      data.characterCoordinates (fun i ↦ (raw i : ZMod p)) row := by
  letI : NeZero p := ⟨data.prime.ne_zero⟩
  simp only [integralCharacterCoordinate, Int.cast_sum, Int.cast_mul,
    Int.cast_natCast, GaugeData.characterCoordinates, Matrix.mulVec,
    dotProduct]
  apply Finset.sum_congr rfl
  intro i _
  rw [ZMod.natCast_zmod_val]

/-- The exact integral output of W1's depth law for one exponent vector:
every character coordinate times its generated high eigenvalue vanishes
modulo the prime cube. -/
def HighFlowVanishes {p : ℕ} (data : GaugeData p)
    (raw : Fin data.rank → ℤ) : Prop :=
  ∀ row, (p : ℤ) ^ 3 ∣
    integralCharacterCoordinate data raw row *
      highEigenvalue (data := data) row

/-- The per-prime certificate boundary.  The vector of eigenvalues is
generated by `highEigenvalue`; an instance certifies only that none of those
generated values is killed by the prime cube. -/
structure FlowCertificate {p : ℕ} (data : GaugeData p) : Prop where
  eigenvalue_cubeFree :
    ∀ row, ¬(p : ℤ) ^ 3 ∣ highEigenvalue (data := data) row

private theorem prime_dvd_left_of_cube_dvd_mul_of_cube_free
    {p : ℕ} (hp : p.Prime) {a b : ℤ}
    (hprod : (p : ℤ) ^ 3 ∣ a * b)
    (hb : ¬(p : ℤ) ^ 3 ∣ b) :
    (p : ℤ) ∣ a := by
  by_contra ha
  apply hb
  have hna : ¬p ∣ a.natAbs := by
    simpa [Int.natCast_dvd] using ha
  have hnat : Nat.Coprime (p ^ 3) a.natAbs :=
    (hp.coprime_pow_of_not_dvd hna).symm
  have hint : IsCoprime ((p : ℤ) ^ 3) a := by
    rw [Int.isCoprime_iff_nat_coprime]
    simpa [Int.natAbs_pow] using hnat
  exact hint.dvd_of_dvd_mul_right (by simpa [mul_comm] using hprod)

/-- W2 plus the cube-free certificate invert a vanished high flow: every
raw exponent is divisible by `p`. -/
theorem exponent_dvd_of_highFlowVanishes {p : ℕ}
    (data : GaugeData p) (certificate : FlowCertificate data)
    (raw : Fin data.rank → ℤ) (hflow : HighFlowVanishes data raw) :
    ∀ i, (p : ℤ) ∣ raw i := by
  have hcharacterDvd :
      ∀ row, (p : ℤ) ∣ integralCharacterCoordinate data raw row :=
    fun row ↦
      prime_dvd_left_of_cube_dvd_mul_of_cube_free data.prime
        (hflow row) (certificate.eigenvalue_cubeFree row)
  have hcharacter :
      data.characterCoordinates (fun i ↦ (raw i : ZMod p)) = 0 := by
    funext row
    rw [← intCast_integralCharacterCoordinate]
    exact
      (ZMod.intCast_zmod_eq_zero_iff_dvd
        (integralCharacterCoordinate data raw row) p).2
        (hcharacterDvd row)
  have hraw :
      (fun i ↦ (raw i : ZMod p)) = 0 :=
    data.raw_eq_zero_of_character_eq_zero _ hcharacter
  intro i
  exact
    (ZMod.intCast_zmod_eq_zero_iff_dvd (raw i) p).1
      (by simpa using congrFun hraw i)

/-- W1's relation-level L4 output.  This predicate does not contain
exponent divisibility or a repayment conclusion: it says only that a deep
generated relation has the integral high-flow congruences defined above. -/
def DeepFlowLaw {p : ℕ} {G : Type*} [CommGroup G]
    (data : GaugeData p)
    (realize : (ZMod p)ˣ → G) (deep : G → Prop) : Prop :=
  ∀ (u : G), deep u →
    ∀ (t : ℕ) (raw : Fin data.rank → ℤ),
      0 < t →
      u ^ t = ∏ i, data.cycle.edge realize i ^ raw i →
      ¬(p ∣ t ∧ ∀ i, (p : ℤ) ∣ raw i) →
      HighFlowVanishes data raw

/-- **Generic W3 forcing.** W1 supplies high-flow vanishing, the certificate
supplies only cube-free generated eigenvalues, and W2 supplies the
generator-derived inverse gauge.  The result is precisely the exponent
divisibility consumed by repayment. -/
theorem deepExponentForcing {p : ℕ} {G : Type*} [CommGroup G]
    (data : GaugeData p)
    (realize : (ZMod p)ˣ → G) (deep : G → Prop)
    (certificate : FlowCertificate data)
    (hL4 : DeepFlowLaw data realize deep) :
    Repayment.DeepExponentForcing data.cycle realize p deep := by
  intro u hdeep t raw ht hrelation hprimitive
  exact exponent_dvd_of_highFlowVanishes data certificate raw
    (hL4 u hdeep t raw ht hrelation hprimitive)

end Fermat.Conservation.Credit.Flow
