/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, Fable

# Gauge quotient of the generated credit ledger

This file is the route-neutral W1 shell.  It quotients a charged carrier by
the subgroup generated by C2's orbit edges.  Every generated transfer then
vanishes in the quotient, so C1 reads the residual ledger as vacuum.

The prime-data record keeps the three permits separate: faithful finite
capacity, C3 repayment, and the exact depth-two certificate.  Charge descends
only after a Jacobian bridge proves that the generated gauge action preserves
the chosen charge.  The bridge is deliberately not hidden in `PrimeData`:
depth two and charge invariance are different types, and an arithmetic
instance must prove their connection.
-/
import Fermat.Conservation.Credit.Capacity
import Fermat.Conservation.Credit.DepthCertificate
import Fermat.Conservation.Credit.Repayment
import Fermat.Conservation.Credit.Vacuum
import Mathlib.GroupTheory.GroupAction.Defs
import Mathlib.GroupTheory.QuotientGroup.Basic

namespace Fermat.Conservation.Credit.GaugeQuotient

open Fermat.Conservation.Credit

universe uG uα uX

variable {G : Type uG} {α : Type uα} [CommGroup G]

/-- C2 faithfulness: the generated gauge quotient has cardinality prime to
the selected prime. -/
def FaithfulAt (p : ℕ) (cycle : Cycle α) (realize : α → G) : Prop :=
  (Nat.card (G ⧸ cycle.generatedSubledger realize)).Coprime p

/-- A charge is constant along the action of a stated gauge subgroup. -/
def ChargeInvariant {X : Type*} [MulAction G X]
    (H : Subgroup G) (charge : X → ℕ) : Prop :=
  ∀ (g : H) (state : X), charge (g • state) = charge state

/-- The three independently audited W1 permits at an arbitrary prime. -/
structure PrimeData (p : ℕ)
    (cycle : Cycle α) (realize : α → G) (deep : G → Prop)
    (gauge : RealGauge.RealGaugeData p) where
  prime : p.Prime
  capacity : Cycle.CapacityData cycle realize
  capacity_ambient : capacity.ambient = ⊤
  faithfulAtPrime : FaithfulAt p cycle realize
  repayment_of_capacity_and_flow :
    ∀ {u : G}, deep u → Repayment.IsRepaid p u
  depthTwo : RealFlow.DepthTwoCertificate gauge

namespace PrimeData

variable {p : ℕ} {cycle : Cycle α} {realize : α → G}
  {deep : G → Prop} {gauge : RealGauge.RealGaugeData p}

/-- The subgroup divided out by the W1 gauge quotient. -/
abbrev generatedGauge
    (_data : PrimeData p cycle realize deep gauge) : Subgroup G :=
  cycle.generatedSubledger realize

/-- The value-level gauge quotient of the generated C2 sub-ledger. -/
abbrev GaugeQuotient
    (data : PrimeData p cycle realize deep gauge) : Type uG :=
  G ⧸ data.generatedGauge

/-- A generated node-pair transfer viewed in the gauge quotient. -/
def quotientTransfer
    (data : PrimeData p cycle realize deep gauge)
    (i j : Fin cycle.rank) : data.GaugeQuotient :=
  QuotientGroup.mk' data.generatedGauge (cycle.transfer realize i j)

private theorem transfer_mem_generatedGauge
    (data : PrimeData p cycle realize deep gauge)
    (i j : Fin cycle.rank) :
    cycle.transfer realize i j ∈ data.generatedGauge := by
  exact
    data.generatedGauge.mul_mem
      (cycle.edge_mem_generatedSubledger realize i)
      (data.generatedGauge.inv_mem
        (cycle.edge_mem_generatedSubledger realize j))

/-- Every generated transfer becomes the identity after dividing out the
generated gauge. -/
theorem quotientTransfer_eq_one
    (data : PrimeData p cycle realize deep gauge)
    (i j : Fin cycle.rank) :
    data.quotientTransfer i j = 1 := by
  exact
    (QuotientGroup.eq_one_iff
      (cycle.transfer realize i j)).2
      (transfer_mem_generatedGauge data i j)

/-- Node pairs whose generated transfer remains nontrivial after quotient. -/
def quotientFunded
    (data : PrimeData p cycle realize deep gauge) :
    Set (Fin cycle.rank × Fin cycle.rank) :=
  {pair | data.quotientTransfer pair.1 pair.2 ≠ 1}

/-- The generated ledger before quotient.  Every node-pair generator is
present; the quotient predicate evaluates its corresponding transfer in the
generated gauge. -/
def sourceLedger
    (_data : PrimeData p cycle realize deep gauge) :
    Ledger (Fin cycle.rank) (Fin cycle.rank × Fin cycle.rank) :=
  generated id Set.univ

/-- Intersect each ledger entry with the transfers that survive the value
quotient.  This is a genuine semilattice-with-bottom morphism, so quotient
commutes with ledger composition and sends vacuum to vacuum. -/
def quotientLedgerMorphism
    (data : PrimeData p cycle realize deep gauge) :
    SupBotHom
      (Ledger (Fin cycle.rank) (Fin cycle.rank × Fin cycle.rank))
      (Ledger (Fin cycle.rank) (Fin cycle.rank × Fin cycle.rank)) where
  toFun := fun ledger debtor creditor =>
    ledger debtor creditor ∩ data.quotientFunded
  map_sup' := by
    intro left right
    ext debtor creditor generator
    change
      ((generator ∈ left debtor creditor ∨
          generator ∈ right debtor creditor) ∧
        generator ∈ data.quotientFunded) ↔
        (generator ∈ left debtor creditor ∧
          generator ∈ data.quotientFunded) ∨
        (generator ∈ right debtor creditor ∧
          generator ∈ data.quotientFunded)
    tauto
  map_bot' := by
    ext debtor creditor generator
    change (False ∧ generator ∈ data.quotientFunded) ↔ False
    tauto

/-- The residual two-sided ledger after the generated gauge is divided out. -/
def quotientLedger
    (data : PrimeData p cycle realize deep gauge) :
    Ledger (Fin cycle.rank) (Fin cycle.rank × Fin cycle.rank) :=
  generated id data.quotientFunded

/-- The residual ledger is literally the image of the generated source
ledger under the quotient morphism. -/
theorem quotientLedger_eq_morphism
    (data : PrimeData p cycle realize deep gauge) :
    data.quotientLedger =
      data.quotientLedgerMorphism data.sourceLedger := by
  ext debtor creditor generator
  simp only [quotientLedger, sourceLedger, quotientLedgerMorphism,
    mem_generated, SupBotHom.coe_mk, SupHom.coe_mk, Set.mem_inter_iff,
    Set.mem_univ, true_and]
  tauto

private theorem no_quotientFunded
    (data : PrimeData p cycle realize deep gauge) :
    ¬HasFundedGenerator data.quotientFunded := by
  rintro ⟨⟨i, j⟩, hfunded⟩
  change data.quotientTransfer i j ≠ 1 at hfunded
  exact hfunded (data.quotientTransfer_eq_one i j)

/-- **W1 vacuum.** Re-generating the value-aware ledger after quotient
leaves no funded transfer. -/
theorem quotientLedger_eq_bot
    (data : PrimeData p cycle realize deep gauge) :
    data.quotientLedger = ⊥ :=
  kummer_credit_vacuum id data.quotientFunded
    (no_quotientFunded data)

/-- The canonical root selected from the already-proved C3 repayment
permit. -/
noncomputable def repaymentRoot
    (data : PrimeData p cycle realize deep gauge)
    {u : G} (hdeep : deep u) : G :=
  (data.repayment_of_capacity_and_flow hdeep).choose

/-- C3's selected root repays the original deep draw exactly. -/
theorem debt_eq_repaymentRoot_pow
    (data : PrimeData p cycle realize deep gauge)
    {u : G} (hdeep : deep u) :
    u = (data.repaymentRoot hdeep) ^ p :=
  (data.repayment_of_capacity_and_flow hdeep).choose_spec

/-- Charged states modulo the generated unit gauge. -/
abbrev GaugeState (data : PrimeData p cycle realize deep gauge)
    (X : Type uX) [MulAction G X] : Type uX :=
  MulAction.orbitRel.Quotient data.generatedGauge X

/-- The quotient image of a charged stock state. -/
def quotientState (data : PrimeData p cycle realize deep gauge)
    {X : Type uX} [MulAction G X] (state : X) :
    data.GaugeState X :=
  Quotient.mk'' state

/-- Descend a charge to the gauge quotient.  Well-definedness is proved
from gauge invariance rather than stored as a quotient-state field. -/
def quotientCharge (data : PrimeData p cycle realize deep gauge)
    {X : Type uX} [MulAction G X] (charge : X → ℕ)
    (hinvariant : ChargeInvariant data.generatedGauge charge) :
    data.GaugeState X → ℕ :=
  Quotient.lift charge (by
    intro left right hrel
    obtain ⟨g, hg⟩ := MulAction.mem_orbit_iff.mp hrel
    rw [← hg]
    simpa only [MulAction.subgroup_smul_def] using
      hinvariant g right)

/-- **W1 equal charge.** The quotient representative has exactly the source
charge once the depth-two Jacobian bridge supplies gauge invariance. -/
@[simp]
theorem quotientCharge_quotientState
    (data : PrimeData p cycle realize deep gauge)
    {X : Type uX} [MulAction G X] (charge : X → ℕ)
    (hinvariant : ChargeInvariant data.generatedGauge charge)
    (state : X) :
    data.quotientCharge charge hinvariant (data.quotientState state) =
      charge state :=
  rfl

/-- The still-visible arithmetic seam between the typed depth-two reading
and charge preservation for a concrete stock action. -/
def DepthTwoJacobianBridge
    (data : PrimeData p cycle realize deep gauge)
    {X : Type uX} [MulAction G X] (charge : X → ℕ) : Prop :=
  RealFlow.DepthTwoCertificate gauge →
    ChargeInvariant data.generatedGauge charge

/-- W1's two requested conclusions, once the arithmetic Jacobian bridge is
available.  C1 supplies vacuum and gauge invariance supplies literal charge
equality. -/
theorem quotient_vacuum_and_charge_eq
    (data : PrimeData p cycle realize deep gauge)
    {X : Type uX} [MulAction G X] (charge : X → ℕ)
    (hjacobian : data.DepthTwoJacobianBridge charge)
    (state : X) :
    data.quotientLedger = ⊥ ∧
      data.quotientCharge charge (hjacobian data.depthTwo)
          (data.quotientState state) =
        charge state :=
  ⟨data.quotientLedger_eq_bot,
    data.quotientCharge_quotientState charge
      (hjacobian data.depthTwo) state⟩

end PrimeData

end Fermat.Conservation.Credit.GaugeQuotient
