/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, Fable

# W1: generator-derived high flow

The high flow is derived from the Bernoulli generator and the C5 cycle.
Each gauge row selects the high index `2 * (row + 1) * p`; the formal
generator orbit then factors its exponent flow into the exact
canonical-lift edge coefficient and the corresponding Bernoulli quotient.

The canonical integer representatives are retained until after taking the
high powers.  Reducing the resulting exact coefficient modulo `p` recovers
the finite-field gauge coordinate used by W2.
-/
import Fermat.Conservation.Credit.Flow
import Fermat.Conservation.Credit.Gauge

open scoped BigOperators

namespace Fermat.Conservation.Credit.Flow

open Gauge

/-- The high Bernoulli index selected by row `k` of the credit flow. -/
def highIndex {p : ℕ} {data : GaugeData p}
    (k : Fin data.rank) : ℕ :=
  2 * (k.val + 1) * p

/-- The integral eigenvalue generated in row `k`.  It is a definition from
the Bernoulli generator, not a field of a certificate. -/
def highEigenvalue {p : ℕ} {data : GaugeData p}
    (k : Fin data.rank) : ℤ :=
  (bernoulli (highIndex k)).num

/-- The canonical integer representative of a node in the generated orbit. -/
def canonicalNodeValue {p : ℕ} (data : GaugeData p) (i : ℕ) : ℤ :=
  (((data.cycle.point i : (ZMod p)ˣ) : ZMod p).val : ℤ)

/-- The generator-derived Teichmüller-style integer lift used by W1.
Raising the canonical representative to `p` preserves its reduction modulo
`p` and gives the additional prime-square torsion congruence needed by the
local depth calculation. -/
def teichNodeValue {p : ℕ} (data : GaugeData p) (i : ℕ) : ℤ :=
  canonicalNodeValue data i ^ p

/-- The exact generator-derived high edge coefficient.  This is deliberately
not formed by choosing representatives of the already reduced C5 matrix:
those representatives agree only modulo `p`, whereas W1 supplies a
prime-cube congruence for this exact integer. -/
def exactHighEdgeCoefficient {p : ℕ} (data : GaugeData p)
    (raw : Fin data.rank → ℤ) (row : Fin data.rank) : ℤ :=
  ∑ i, raw i *
    (teichNodeValue data (i.val + 1) ^
        highIndex (data := data) row -
      teichNodeValue data i.val ^
        highIndex (data := data) row)

/-- Reducing a canonical node representative recovers the generated node. -/
theorem intCast_canonicalNodeValue {p : ℕ}
    (data : GaugeData p) (i : ℕ) :
    ((canonicalNodeValue data i : ℤ) : ZMod p) =
      ((data.cycle.point i : (ZMod p)ˣ) : ZMod p) := by
  letI : NeZero p := ⟨data.prime.ne_zero⟩
  simp only [canonicalNodeValue, Int.cast_natCast, ZMod.natCast_zmod_val]

/-- The Teichmüller-style lift represents the same generated node modulo
`p`; this is Frobenius on the prime field. -/
theorem intCast_teichNodeValue {p : ℕ}
    (data : GaugeData p) (i : ℕ) :
    ((teichNodeValue data i : ℤ) : ZMod p) =
      ((data.cycle.point i : (ZMod p)ˣ) : ZMod p) := by
  letI : Fact p.Prime := ⟨data.prime⟩
  rw [teichNodeValue, Int.cast_pow, intCast_canonicalNodeValue,
    ZMod.pow_card]

/-- The exact integral high edge coefficient reduces to the
generator-derived finite-field gauge coordinate. -/
theorem intCast_exactHighEdgeCoefficient {p : ℕ}
    (data : GaugeData p) (raw : Fin data.rank → ℤ)
    (row : Fin data.rank) :
    ((exactHighEdgeCoefficient data raw row : ℤ) : ZMod p) =
      data.characterCoordinates (fun i ↦ (raw i : ZMod p)) row := by
  letI : NeZero p := ⟨data.prime.ne_zero⟩
  simp only [exactHighEdgeCoefficient, Int.cast_sum, Int.cast_mul,
    Int.cast_sub, Int.cast_pow, intCast_teichNodeValue,
    GaugeData.characterCoordinates, Matrix.mulVec, dotProduct]
  apply Finset.sum_congr rfl
  intro i _
  rw [data.characterMatrix_eq_high_edge_difference]
  simp [highIndex, mul_comm]

/-- The lifted formal orbit generated by exactly the C2/C5 cycle. -/
noncomputable abbrev gaugeGeneratorOrbit {p : ℕ} (data : GaugeData p) :
    GeneratorOrbit p ((ZMod p)ˣ) where
  cycle := data.cycle
  scale := fun a ↦ ((((a : ZMod p).val : ℤ) ^ p : ℤ) : ℚ)
  prime := data.prime
  odd := data.odd
  coordinateDegree := fun row ↦ highIndex (data := data) row - 1

theorem gaugeGeneratorOrbit_coordinateDegree_add_one {p : ℕ}
    (data : GaugeData p) (row : Fin data.rank) :
    (gaugeGeneratorOrbit data).coordinateDegree row + 1 =
      highIndex (data := data) row := by
  apply Nat.sub_add_cancel
  unfold highIndex
  exact Nat.one_le_iff_ne_zero.mpr
    (Nat.mul_ne_zero
      (Nat.mul_ne_zero (by norm_num) (Nat.succ_ne_zero row.val))
      data.prime.ne_zero)

/-- Each formal edge weight is its exact lifted integer coefficient
times the high Bernoulli quotient. -/
theorem gaugeGeneratorOrbit_weight_eq_exactHighEdge {p : ℕ}
    (data : GaugeData p) (row i : Fin data.rank) :
    (gaugeGeneratorOrbit data).weight i row =
      ((teichNodeValue data (i.val + 1) ^
          highIndex (data := data) row -
        teichNodeValue data i.val ^
          highIndex (data := data) row : ℤ) : ℚ) *
        (bernoulli (highIndex (data := data) row) /
          (highIndex (data := data) row : ℚ)) := by
  rw [GeneratorOrbit.weight_eq_bernoulli,
    gaugeGeneratorOrbit_coordinateDegree_add_one]
  have heven : Even (highIndex (data := data) row) := by
    simp [highIndex]
  rw [bernoulli'_eq_bernoulli, heven.neg_one_pow, one_mul]
  simp only [gaugeGeneratorOrbit, GeneratorOrbit.nodeScale,
    teichNodeValue, canonicalNodeValue]
  have hpos : 1 ≤ highIndex (data := data) row := by
    unfold highIndex
    exact Nat.one_le_iff_ne_zero.mpr
      (Nat.mul_ne_zero
        (Nat.mul_ne_zero (by norm_num) (Nat.succ_ne_zero row.val))
        data.prime.ne_zero)
  have hdegreeQ :
      ((highIndex (data := data) row - 1 : ℕ) : ℚ) + 1 =
        (highIndex (data := data) row : ℕ) := by
    exact_mod_cast Nat.sub_add_cancel hpos
  rw [hdegreeQ]
  norm_cast

/-- Regard a full finite raw vector as W1's finitely supported exponent
vector. -/
noncomputable def exponentVectorOfRaw {p : ℕ} (data : GaugeData p)
    (raw : Fin data.rank → ℤ) :
    (gaugeGeneratorOrbit data).ExponentVector :=
  Finsupp.equivFunOnFinite.symm raw

@[simp]
theorem exponentVectorOfRaw_apply {p : ℕ} (data : GaugeData p)
    (raw : Fin data.rank → ℤ) (i : Fin data.cycle.rank) :
    exponentVectorOfRaw data raw i = raw i :=
  rfl

/-- The generated formal flow row factors through the exact integer edge
coefficient used by W3, with no arbitrary lift of the reduced gauge matrix. -/
theorem gaugeGeneratorOrbit_exponentFlow_eq_exactHighEdgeCoefficient
    {p : ℕ} (data : GaugeData p) (raw : Fin data.rank → ℤ)
    (row : Fin data.rank) :
    (gaugeGeneratorOrbit data).exponentFlow
        (exponentVectorOfRaw data raw) row =
      (exactHighEdgeCoefficient data raw row : ℚ) *
        (bernoulli (highIndex (data := data) row) /
          (highIndex (data := data) row : ℚ)) := by
  simp only [GeneratorOrbit.exponentFlow, GeneratorOrbit.rationalFlow,
    GeneratorOrbit.castExponent, Finsupp.linearCombination_apply,
    AddMonoidHom.comp_apply, LinearMap.toAddMonoidHom_coe,
    Finsupp.mapRange.addMonoidHom_apply]
  rw [Finsupp.sum_fintype _ _ (by simp), Finset.sum_apply]
  have hcast (z : ℤ) : (Int.castAddHom ℚ) z = (z : ℚ) := rfl
  simp only [Finsupp.mapRange_apply, Pi.smul_apply, smul_eq_mul, hcast,
    gaugeGeneratorOrbit_weight_eq_exactHighEdge]
  rw [exactHighEdgeCoefficient]
  push_cast
  rw [Finset.sum_mul]
  apply Finset.sum_congr rfl
  intro i _
  rw [exponentVectorOfRaw_apply]
  ring

/-- The exact integral output of W1's depth law for one exponent vector:
every character coordinate times its generated high eigenvalue vanishes
modulo the prime cube. -/
def HighFlowVanishes {p : ℕ} (data : GaugeData p)
    (raw : Fin data.rank → ℤ) : Prop :=
  ∀ row, (p : ℤ) ^ 3 ∣
    exactHighEdgeCoefficient data raw row *
      highEigenvalue (data := data) row

end Fermat.Conservation.Credit.Flow
