/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, Fable

# W1: relation-to-moment depth assembly

This layer joins the integral cyclotomic depth primitive to the polynomial
moment flow.  A deep numerator relation is corrected by an explicit
`p²`-multiple; the corrected relation has an exact prime-cyclotomic factor
and retains its `p²` value at one.  These are precisely the two inputs of
the nonlinear moment bridge.

The construction is generic over the prime and contains no
conductor-specific arithmetic.
-/
import Fermat.Conservation.Credit.DepthFlow
import Fermat.Conservation.Credit.NonlinearFlow
import Fermat.Conservation.Credit.RealHighFlow

open scoped NumberField

namespace Fermat.Conservation.Credit.RealFlow

open Ideal NumberField Polynomial

variable {p : ℕ} [Fact p.Prime]
variable {K : Type*} [Field K] [NumberField K]
  [IsCyclotomicExtension {p} ℚ K]
variable {ζ : K} (hζ : IsPrimitiveRoot ζ p)

/-! ## Scalar normalization forced by depth -/

/-- The rational prime lies in the principal ideal generated by the
cyclotomic uniformizer. -/
theorem one_sub_zeta_dvd_prime :
    (1 : 𝓞 K) - hζ.toInteger ∣ (p : 𝓞 K) := by
  have hpMem :
      (p : 𝓞 K) ∈ Ideal.span ({(p : 𝓞 K)} : Set (𝓞 K)) :=
    Ideal.subset_span (Set.mem_singleton _)
  rw [Flow.span_prime_eq_span_one_sub_pow_pred hζ] at hpMem
  have hpgt : 1 < p := (Fact.out : p.Prime).one_lt
  have hpPred : p - 1 ≠ 0 := by
    omega
  have hpMem' :
      (p : 𝓞 K) ∈
        Ideal.span ({(1 : 𝓞 K) - hζ.toInteger} : Set (𝓞 K)) :=
    (Ideal.pow_le_self hpPred) hpMem
  exact Ideal.mem_span_singleton.mp hpMem'

/-- A scalar deeply congruent to a global unit cannot be divisible by the
rational prime. -/
theorem not_prime_dvd_scalar_of_deep_unit
    (u : (𝓞 K)ˣ) (c : ℤ)
    (hdeep :
      ((1 : 𝓞 K) - hζ.toInteger) ^ (2 * p) ∣
        (u : 𝓞 K) - (c : 𝓞 K) ^ p) :
    ¬(p : ℤ) ∣ c := by
  intro hc
  let π : 𝓞 K := (1 : 𝓞 K) - hζ.toInteger
  have hπp : π ∣ (p : 𝓞 K) := by
    simpa only [π] using one_sub_zeta_dvd_prime hζ
  obtain ⟨d, rfl⟩ := hc
  have hπc : π ∣ (((p : ℤ) * d : ℤ) : 𝓞 K) := by
    push_cast
    exact dvd_mul_of_dvd_left hπp _
  have hπcpow : π ∣ ((((p : ℤ) * d : ℤ) : 𝓞 K) ^ p) :=
    hπc.trans (dvd_pow_self _ (Fact.out : p.Prime).ne_zero)
  have hπdeep :
      π ∣ (u : 𝓞 K) - ((((p : ℤ) * d : ℤ) : 𝓞 K) ^ p) := by
    exact
      (dvd_pow_self π (mul_ne_zero (by norm_num)
        (Fact.out : p.Prime).ne_zero)).trans hdeep
  have hπu : π ∣ (u : 𝓞 K) := by
    convert dvd_add hπdeep hπcpow using 1
    ring
  have hπNotUnit : ¬IsUnit π := by
    rw [show π = -(hζ.toInteger - 1) by simp [π]]
    intro hunit
    exact hζ.zeta_sub_one_prime'.not_unit ((IsUnit.neg_iff _).mp hunit)
  exact hπNotUnit (isUnit_of_dvd_unit hπu u.isUnit)

/-- Euler normalization at `p²`, in the exponent created by raising a
`p`th-power deep scalar through a `(p - 1)`-normalized relation. -/
theorem scalar_power_mod_prime_sq
    (c : ℤ) (t : ℕ) (hc : ¬(p : ℤ) ∣ c) :
    ((c ^ (p * t * (p - 1)) : ℤ) : ZMod (p ^ 2)) = 1 := by
  let m := c.natAbs
  have hmnot : ¬p ∣ m := by
    intro hm
    apply hc
    rw [← Int.natAbs_dvd_natAbs]
    simpa [m] using hm
  have hcopPrime : m.Coprime p :=
    ((Fact.out : p.Prime).coprime_iff_not_dvd.mpr hmnot).symm
  have hcop : m.Coprime (p ^ 2) := hcopPrime.pow_right 2
  have hmUnit : IsUnit (m : ZMod (p ^ 2)) :=
    (ZMod.isUnit_iff_coprime m (p ^ 2)).mpr hcop
  have hcUnit : IsUnit ((c : ℤ) : ZMod (p ^ 2)) := by
    rcases Int.natAbs_eq c with h | h
    · rw [h]
      push_cast
      simpa [m] using hmUnit
    · rw [h]
      push_cast
      simpa [m] using hmUnit.neg
  let U : (ZMod (p ^ 2))ˣ := hcUnit.unit
  have hU : ((U : ZMod (p ^ 2)) ^ (p ^ 2).totient) = 1 := by
    simpa only [Units.val_pow_eq_pow_val, Units.val_one] using
      congrArg ((↑) : (ZMod (p ^ 2))ˣ → ZMod (p ^ 2))
        (ZMod.pow_totient U)
  have htotient : (p ^ 2).totient = p * (p - 1) := by
    simpa using Nat.totient_prime_pow
      (Fact.out : p.Prime) (n := 2) (by omega)
  have hbase :
      (((c : ℤ) : ZMod (p ^ 2))) ^ (p * (p - 1)) = 1 := by
    rw [hcUnit.unit_spec] at hU
    simpa only [htotient] using hU
  push_cast
  rw [show p * t * (p - 1) = (p * (p - 1)) * t by ring,
    pow_mul, hbase, one_pow]

/-- Integer divisibility form of the scalar Euler normalization. -/
theorem prime_sq_dvd_scalar_power_sub_one
    (c : ℤ) (t : ℕ) (hc : ¬(p : ℤ) ∣ c) :
    (p : ℤ) ^ 2 ∣ c ^ (p * t * (p - 1)) - 1 := by
  apply
    (ZMod.intCast_zmod_eq_zero_iff_dvd
      (c ^ (p * t * (p - 1)) - 1) (p ^ 2)).mp
  simp only [Int.cast_sub, Int.cast_one,
    scalar_power_mod_prime_sq c t hc, sub_self]

/-- Direct scalar normalization obtained from a deep unit congruence. -/
theorem deep_scalar_power_mod_prime_sq
    (u : (𝓞 K)ˣ) (c : ℤ) (t : ℕ)
    (hdeep :
      ((1 : 𝓞 K) - hζ.toInteger) ^ (2 * p) ∣
        (u : 𝓞 K) - (c : 𝓞 K) ^ p) :
    ((c ^ (p * t * (p - 1)) : ℤ) : ZMod (p ^ 2)) = 1 :=
  scalar_power_mod_prime_sq c t
    (not_prime_dvd_scalar_of_deep_unit hζ u c hdeep)

/-! ## Generator-derived integral node polynomials -/

/-- The canonical Teichmüller lift attached to a nonzero residue.  It is
formed from the indexed lift itself, before any quotient representative is
forgotten. -/
def teichLift (p : ℕ) (a : (ZMod p)ˣ) : ℕ :=
  (a : ZMod p).val ^ p

/-- The Teichmüller lift has the same reduction as its source node. -/
theorem natCast_teichLift {p : ℕ} [Fact p.Prime]
    (a : (ZMod p)ˣ) :
    (teichLift p a : ZMod p) = (a : ZMod p) := by
  simp [teichLift, ZMod.pow_card]

/-- Euler normalization modulo `p²` for the canonical lift. -/
theorem teichLift_pow_pred_modEq_one {p : ℕ} (hp : p.Prime)
    (a : (ZMod p)ˣ) :
    (teichLift p a) ^ (p - 1) ≡ 1 [MOD p ^ 2] := by
  have hcop : (a : ZMod p).val.Coprime (p ^ 2) :=
    (ZMod.val_coe_unit_coprime a).pow_right 2
  have heuler := Nat.ModEq.pow_totient hcop
  rw [Nat.totient_prime_pow hp (by omega)] at heuler
  norm_num at heuler
  simpa only [teichLift, ← pow_mul] using heuler

/-- Integer divisibility form of Teichmüller normalization. -/
theorem prime_sq_dvd_teichLift_pow_pred_sub_one {p : ℕ}
    (hp : p.Prime) (a : (ZMod p)ˣ) :
    ((p : ℤ) ^ 2) ∣
      ((teichLift p a : ℤ) ^ (p - 1) - 1) := by
  have hnegative :
      ((p ^ 2 : ℕ) : ℤ) ∣
        1 - ((teichLift p a : ℕ) ^ (p - 1) : ℤ) :=
    (teichLift_pow_pred_modEq_one hp a).dvd
  have hpositive := dvd_neg.mpr hnegative
  simpa only [Nat.cast_pow, neg_sub] using hpositive

/-- Integral geometric-sum polynomial of length `r`. -/
noncomputable def geometricPolynomial (r : ℕ) : ℤ[X] :=
  ∑ j ∈ Finset.range r, X ^ j

@[simp]
theorem geometricPolynomial_eval_one (r : ℕ) :
    (geometricPolynomial r).eval 1 = (r : ℤ) := by
  simp [geometricPolynomial]

/-- Polynomial representative of a folded real cyclotomic node.

The geometric sum uses the full Teichmüller lift.  Its residue is still
`a`, while its value at one now has the prime-square Euler normalization.
The monomial records the conjugation fold and has value one at `X = 1`. -/
noncomputable def foldedTeichNodePolynomial
    (p : ℕ) (a : (ZMod p)ˣ) : ℤ[X] :=
  X ^ (p + 1 - (a : ZMod p).val) *
    geometricPolynomial (teichLift p a) ^ 2

@[simp]
theorem foldedTeichNodePolynomial_eval_one
    (p : ℕ) (a : (ZMod p)ˣ) :
    (foldedTeichNodePolynomial p a).eval 1 =
      (teichLift p a : ℤ) ^ 2 := by
  simp [foldedTeichNodePolynomial]

/-- The normalized folded node is the `(p - 1)`st power. -/
noncomputable def normalizedFoldedNodePolynomial
    (p : ℕ) (a : (ZMod p)ˣ) : ℤ[X] :=
  foldedTeichNodePolynomial p a ^ (p - 1)

/-- Every normalized folded node has value one modulo `p²`. -/
theorem prime_sq_dvd_normalizedFoldedNodePolynomial_eval_one_sub_one
    {p : ℕ} (hp : p.Prime) (a : (ZMod p)ˣ) :
    ((p : ℤ) ^ 2) ∣
      (normalizedFoldedNodePolynomial p a).eval 1 - 1 := by
  have hmod := (teichLift_pow_pred_modEq_one hp a).pow 2
  have hnegative :
      ((p ^ 2 : ℕ) : ℤ) ∣
        1 - (((teichLift p a) ^ (p - 1)) ^ 2 : ℕ) :=
    hmod.dvd
  have hpositive := dvd_neg.mpr hnegative
  have hpositive' :
      ((p : ℤ) ^ 2) ∣
        (((teichLift p a : ℤ) ^ (p - 1)) ^ 2 - 1) := by
    simpa only [Nat.cast_pow, neg_sub] using hpositive
  convert hpositive' using 1
  simp only [normalizedFoldedNodePolynomial, Polynomial.eval_pow,
    foldedTeichNodePolynomial_eval_one, ← pow_mul]
  rw [Nat.mul_comm 2 (p - 1)]

/-- The normalized polynomial for the `i`th indexed real-residue lift. -/
noncomputable def normalizedNodePolynomial {p : ℕ}
    (data : RealGauge.RealGaugeData p) (i : ℕ) : ℤ[X] :=
  normalizedFoldedNodePolynomial p (data.nodeLift i)

/-- Positive part of an integral exponent. -/
def positiveExponent (z : ℤ) : ℕ :=
  z.toNat

/-- Negative part of an integral exponent. -/
def negativeExponent (z : ℤ) : ℕ :=
  (-z).toNat

/-- Numerator of the normalized generated-edge relation. -/
noncomputable def relationNumerator {p : ℕ}
    (data : RealGauge.RealGaugeData p)
    (raw : Fin data.rank → ℤ) : ℤ[X] :=
  ∏ i,
    normalizedNodePolynomial data (i.val + 1) ^
        positiveExponent (raw i) *
      normalizedNodePolynomial data i.val ^
        negativeExponent (raw i)

/-- Denominator of the normalized generated-edge relation. -/
noncomputable def relationDenominator {p : ℕ}
    (data : RealGauge.RealGaugeData p)
    (raw : Fin data.rank → ℤ) : ℤ[X] :=
  ∏ i,
    normalizedNodePolynomial data i.val ^
        positiveExponent (raw i) *
      normalizedNodePolynomial data (i.val + 1) ^
        negativeExponent (raw i)

private theorem dvd_pow_sub_one_of_dvd_sub_one
    {m x : ℤ} (n : ℕ) (h : m ∣ x - 1) :
    m ∣ x ^ n - 1 := by
  exact h.trans (by
    simpa using sub_dvd_pow_sub_pow x (1 : ℤ) n)

private theorem dvd_mul_sub_one_of_dvd_sub_one
    {m x y : ℤ} (hx : m ∣ x - 1) (hy : m ∣ y - 1) :
    m ∣ x * y - 1 := by
  have hxy : m ∣ x * (y - 1) + (x - 1) :=
    (dvd_mul_of_dvd_right hy x).add hx
  convert hxy using 1
  ring

private theorem dvd_finset_prod_sub_one_of_dvd_sub_one
    {ι : Type*} {m : ℤ} (s : Finset ι) (f : ι → ℤ)
    (hf : ∀ i ∈ s, m ∣ f i - 1) :
    m ∣ (∏ i ∈ s, f i) - 1 := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | @insert a s ha ih =>
      rw [Finset.prod_insert ha]
      exact dvd_mul_sub_one_of_dvd_sub_one
        (hf a (by simp)) (ih fun i hi ↦ hf i (by simp [hi]))

/-- Each indexed normalized node has value one modulo `p²`. -/
theorem prime_sq_dvd_normalizedNodePolynomial_eval_one_sub_one
    {p : ℕ} (data : RealGauge.RealGaugeData p) (i : ℕ) :
    ((p : ℤ) ^ 2) ∣
      (normalizedNodePolynomial data i).eval 1 - 1 := by
  exact
    prime_sq_dvd_normalizedFoldedNodePolynomial_eval_one_sub_one
      data.prime (data.nodeLift i)

/-- The generated numerator is automatically one modulo `p²` at
`X = 1`. -/
theorem prime_sq_dvd_relationNumerator_eval_one_sub_one
    {p : ℕ} (data : RealGauge.RealGaugeData p)
    (raw : Fin data.rank → ℤ) :
    ((p : ℤ) ^ 2) ∣ (relationNumerator data raw).eval 1 - 1 := by
  rw [relationNumerator, Polynomial.eval_prod]
  apply dvd_finset_prod_sub_one_of_dvd_sub_one
  intro i _
  rw [Polynomial.eval_mul, Polynomial.eval_pow, Polynomial.eval_pow]
  apply dvd_mul_sub_one_of_dvd_sub_one
  · exact dvd_pow_sub_one_of_dvd_sub_one _
      (prime_sq_dvd_normalizedNodePolynomial_eval_one_sub_one
        data (i.val + 1))
  · exact dvd_pow_sub_one_of_dvd_sub_one _
      (prime_sq_dvd_normalizedNodePolynomial_eval_one_sub_one
        data i.val)

/-- The generated denominator is automatically one modulo `p²` at
`X = 1`. -/
theorem prime_sq_dvd_relationDenominator_eval_one_sub_one
    {p : ℕ} (data : RealGauge.RealGaugeData p)
    (raw : Fin data.rank → ℤ) :
    ((p : ℤ) ^ 2) ∣ (relationDenominator data raw).eval 1 - 1 := by
  rw [relationDenominator, Polynomial.eval_prod]
  apply dvd_finset_prod_sub_one_of_dvd_sub_one
  intro i _
  rw [Polynomial.eval_mul, Polynomial.eval_pow, Polynomial.eval_pow]
  apply dvd_mul_sub_one_of_dvd_sub_one
  · exact dvd_pow_sub_one_of_dvd_sub_one _
      (prime_sq_dvd_normalizedNodePolynomial_eval_one_sub_one
        data i.val)
  · exact dvd_pow_sub_one_of_dvd_sub_one _
      (prime_sq_dvd_normalizedNodePolynomial_eval_one_sub_one
        data (i.val + 1))

/-- The numerator-minus-denominator relation has the value-at-one layer
required by the nonlinear bridge, without any per-prime certificate. -/
theorem prime_sq_dvd_relation_difference_eval_one
    {p : ℕ} (data : RealGauge.RealGaugeData p)
    (raw : Fin data.rank → ℤ) :
    ((p : ℤ) ^ 2) ∣
      (relationNumerator data raw -
        relationDenominator data raw).eval 1 := by
  rw [Polynomial.eval_sub]
  have hnum :=
    prime_sq_dvd_relationNumerator_eval_one_sub_one data raw
  have hden :=
    prime_sq_dvd_relationDenominator_eval_one_sub_one data raw
  convert hnum.sub hden using 1
  ring

/-- The normalized denominator has unit constant jet modulo `p²`. -/
theorem relationDenominator_moment_zero_isUnit
    {p : ℕ} (data : RealGauge.RealGaugeData p)
    (raw : Fin data.rank → ℤ) :
    IsUnit
      (Flow.momentModPrimeSq p 0 (relationDenominator data raw)) := by
  have hzero :
      (((relationDenominator data raw).eval 1 - 1 : ℤ) :
          ZMod (p ^ 2)) = 0 :=
    Flow.intCast_eq_zero_of_prime_sq_dvd
      (prime_sq_dvd_relationDenominator_eval_one_sub_one data raw)
  have hone :
      (((relationDenominator data raw).eval 1 : ℤ) :
          ZMod (p ^ 2)) = 1 := by
    apply sub_eq_zero.mp
    simpa only [Int.cast_sub, Int.cast_one] using hzero
  rw [Flow.momentModPrimeSq,
    Flow.exponentialMoment_zero_eq_eval_one, hone]
  exact isUnit_one

/-- A depth-corrected polynomial has both forms needed downstream: an exact
prime-cyclotomic factor and a prime-square-divisible value at one. -/
theorem exists_moment_ready_correction_of_depth
    (A : ℤ[X])
    (hdepth :
      ((1 : 𝓞 K) - hζ.toInteger) ^ (2 * p) ∣
        Polynomial.eval₂ (algebraMap ℤ (𝓞 K)) hζ.toInteger A)
    (heval : ((p : ℤ) ^ 2) ∣ A.eval 1) :
    ∃ H B : ℤ[X],
      A - Polynomial.C ((p : ℤ) ^ 2) * H =
        Polynomial.cyclotomic p ℤ * B ∧
      ((p : ℤ) ^ 2) ∣
        (A - Polynomial.C ((p : ℤ) ^ 2) * H).eval 1 := by
  obtain ⟨H, hdvd⟩ :=
    Flow.exists_cyclotomic_dvd_correction_of_depth hζ A hdepth
  obtain ⟨B, hfactor⟩ := hdvd
  refine ⟨H, B, hfactor, ?_⟩
  rw [Polynomial.eval_sub, Polynomial.eval_mul, Polynomial.eval_C]
  exact heval.sub (dvd_mul_right ((p : ℤ) ^ 2) (H.eval 1))

/-- Relation form of `exists_moment_ready_correction_of_depth`.

The correction is absorbed into the numerator.  Thus the denominator and
the rational scalar are unchanged, while the numerator difference becomes
an exact cyclotomic multiple suitable for `NonlinearFlow`. -/
theorem exists_moment_ready_relation_of_depth
    (P Q : ℤ[X]) (c : ℤ)
    (hdepth :
      ((1 : 𝓞 K) - hζ.toInteger) ^ (2 * p) ∣
        Polynomial.eval₂ (algebraMap ℤ (𝓞 K)) hζ.toInteger
          (P - Polynomial.C c * Q))
    (heval :
      ((p : ℤ) ^ 2) ∣ (P - Polynomial.C c * Q).eval 1) :
    ∃ H B : ℤ[X],
      (P - Polynomial.C ((p : ℤ) ^ 2) * H) -
          Polynomial.C c * Q =
        Polynomial.cyclotomic p ℤ * B ∧
      ((p : ℤ) ^ 2) ∣
        ((P - Polynomial.C ((p : ℤ) ^ 2) * H) -
          Polynomial.C c * Q).eval 1 := by
  obtain ⟨H, B, hfactor, heval'⟩ :=
    exists_moment_ready_correction_of_depth hζ
      (P - Polynomial.C c * Q) hdepth heval
  refine ⟨H, B, ?_, ?_⟩
  · calc
      (P - Polynomial.C ((p : ℤ) ^ 2) * H) -
            Polynomial.C c * Q =
          (P - Polynomial.C c * Q) -
            Polynomial.C ((p : ℤ) ^ 2) * H := by ring
      _ = Polynomial.cyclotomic p ℤ * B := hfactor
  · have heq :
        (P - Polynomial.C ((p : ℤ) ^ 2) * H) -
            Polynomial.C c * Q =
          (P - Polynomial.C c * Q) -
            Polynomial.C ((p : ℤ) ^ 2) * H := by
      ring
    rw [heq]
    exact heval'

/-- A deep generated relation is converted mechanically into the exact
factorization and value-at-one layer consumed by `NonlinearFlow`. -/
theorem exists_moment_ready_generated_relation_of_depth
    (data : RealGauge.RealGaugeData p)
    (raw : Fin data.rank → ℤ)
    (hdepth :
      ((1 : 𝓞 K) - hζ.toInteger) ^ (2 * p) ∣
        Polynomial.eval₂ (algebraMap ℤ (𝓞 K)) hζ.toInteger
          (relationNumerator data raw -
            relationDenominator data raw)) :
    ∃ H B : ℤ[X],
      (relationNumerator data raw -
          Polynomial.C ((p : ℤ) ^ 2) * H) -
          relationDenominator data raw =
        Polynomial.cyclotomic p ℤ * B ∧
      ((p : ℤ) ^ 2) ∣
        ((relationNumerator data raw -
          Polynomial.C ((p : ℤ) ^ 2) * H) -
          relationDenominator data raw).eval 1 := by
  simpa using
    exists_moment_ready_relation_of_depth hζ
      (relationNumerator data raw) (relationDenominator data raw) 1
      (by simpa using hdepth)
      (by
        simpa using prime_sq_dvd_relation_difference_eval_one data raw)

end Fermat.Conservation.Credit.RealFlow
