/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, Fable

# C3: repayment through a generated unit cycle

This is a credited reconstruction of the group-theoretic half of Vandiver's
Lemma II (1929).  Its public theorem is specialized to the edge family
generated by C2's single cycle.

Finite index produces a power/product relation.  Primitive normalization,
Vandiver's coefficient-cube congruences, and Bézout then produce an actual
`p`-th root.  The one proof-specific arithmetic input remains visible under
the name `DeepCoefficientForcing`: a deep local congruence must force the
coefficient congruences for every primitive generated relation.  No
repayment function or power conclusion is assumed.
-/
import Fermat.Conservation.Credit.Capacity
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.Group.Subgroup.Finsupp
import Mathlib.Data.Int.GCD
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.RingTheory.Int.Basic

namespace Fermat.Conservation.Credit

open scoped BigOperators

namespace Repayment

/-- The exact local depth in Vandiver's Lemma II. -/
def IsVandiverDeep {R : Type*} [CommRing R]
    (p : ℕ) (ramified : R) (u : Rˣ) : Prop :=
  ∃ c : ℤ,
    ramified ^ (2 * p) ∣ (u : R) - (c : R) ^ p

/-- A debt is repaid when the checked unit is an actual `p`-th power. -/
def IsRepaid {G : Type*} [Group G] (p : ℕ) (u : G) : Prop :=
  ∃ v : G, u = v ^ p

private theorem exists_index_relation
    {G ι : Type*} [CommGroup G] [Fintype ι]
    (E : ι → G) (u : G)
    [hfinite : (Subgroup.closure (Set.range E)).FiniteIndex] :
    ∃ a : ι → ℤ,
      0 < (Subgroup.closure (Set.range E)).index ∧
        u ^ (Subgroup.closure (Set.range E)).index =
          ∏ i, E i ^ a i := by
  obtain ⟨a, ha⟩ := Subgroup.exists_of_mem_closure_range E
    (u ^ (Subgroup.closure (Set.range E)).index)
    (Subgroup.pow_index_mem (Subgroup.closure (Set.range E)) u)
  exact ⟨a, Nat.pos_of_ne_zero hfinite.index_ne_zero, ha⟩

private theorem isPower_of_coprime_power_eq_power
    {G : Type*} [CommGroup G] {u d : G} {t p : ℕ}
    (hcop : t.Coprime p) (hrel : u ^ t = d ^ p) :
    IsRepaid p u := by
  let v : G := d ^ (Nat.gcdA t p) * u ^ (Nat.gcdB t p)
  refine ⟨v, ?_⟩
  have hbezout : (1 : ℤ) =
      (t : ℤ) * Nat.gcdA t p + (p : ℤ) * Nat.gcdB t p := by
    rw [← Nat.gcd_eq_gcd_ab, hcop]
    simp
  rw [show u = u ^ (1 : ℤ) by simp, hbezout]
  simp only [v, zpow_add, zpow_mul, zpow_natCast]
  rw [hrel, mul_pow]
  simp only [← zpow_natCast, ← zpow_mul]
  congr 1 <;> simp [mul_comm]

private theorem prime_dvd_of_cube_dvd_mul_of_not_cube_dvd
    {p : ℕ} (hp : p.Prime) {a b : ℤ}
    (hprod : (p : ℤ) ^ 3 ∣ a * b)
    (hb : ¬(p : ℤ) ^ 3 ∣ b) :
    (p : ℤ) ∣ a := by
  by_contra ha
  apply hb
  have hna : ¬p ∣ a.natAbs := by
    simpa [Int.natCast_dvd] using ha
  have hnat : Nat.Coprime (p ^ 3) a.natAbs :=
    (hp.coprime_pow_of_not_dvd hna).symm
  have hint : IsCoprime ((p : ℤ) ^ 3) a := by
    rw [Int.isCoprime_iff_nat_coprime]
    simpa [Int.natAbs_pow] using hnat
  exact hint.dvd_of_dvd_mul_right (by simpa [mul_comm] using hprod)

private theorem product_zpow_mul_exponents
    {G ι : Type*} [CommGroup G] [Fintype ι]
    (E : ι → G) (b : ι → ℤ) (p : ℕ) :
    (∏ i, E i ^ ((p : ℤ) * b i)) = (∏ i, E i ^ b i) ^ p := by
  rw [← Finset.prod_pow Finset.univ p]
  apply Finset.prod_congr rfl
  intro i _
  simp only [← zpow_natCast, ← zpow_mul]
  congr 1
  ring

private theorem product_zpow_is_pow_of_exponents_divisible
    {G ι : Type*} [CommGroup G] [Fintype ι]
    (E : ι → G) (a : ι → ℤ) (p : ℕ)
    (hdiv : ∀ i, (p : ℤ) ∣ a i) :
    ∃ d : G, (∏ i, E i ^ a i) = d ^ p := by
  classical
  choose b hb using hdiv
  refine ⟨∏ i, E i ^ b i, ?_⟩
  simpa only [hb] using product_zpow_mul_exponents E b p

private theorem exists_primitive_relation_of_relation
    {G ι : Type*} [CommGroup G] [Fintype ι]
    {p t : ℕ} (hp2 : 2 ≤ p)
    (hpow : Function.Injective (fun x : G ↦ x ^ p))
    (u : G) (E : ι → G) (a : ι → ℤ)
    (ht : 0 < t) (hrel : u ^ t = ∏ i, E i ^ a i) :
    ∃ (t' : ℕ) (a' : ι → ℤ),
      0 < t' ∧ u ^ t' = ∏ i, E i ^ a' i ∧
        ¬(p ∣ t' ∧ ∀ i, (p : ℤ) ∣ a' i) := by
  induction t using Nat.strong_induction_on generalizing a with
  | h t ih =>
      by_cases hprimitive : ¬(p ∣ t ∧ ∀ i, (p : ℤ) ∣ a i)
      · exact ⟨t, a, ht, hrel, hprimitive⟩
      · push Not at hprimitive
        obtain ⟨hpt, ha⟩ := hprimitive
        obtain ⟨t', rfl⟩ := hpt
        classical
        choose b hb using ha
        have ht' : 0 < t' := Nat.pos_of_mul_pos_left ht
        have hp1 : 1 < p := by omega
        have hlt : t' < p * t' := by
          simpa using Nat.mul_lt_mul_of_pos_right hp1 ht'
        apply ih t' hlt b ht'
        apply hpow
        calc
          (u ^ t') ^ p = u ^ (p * t') := by
            rw [← pow_mul, Nat.mul_comm]
          _ = ∏ i, E i ^ a i := hrel
          _ = ∏ i, E i ^ ((p : ℤ) * b i) := by
            apply Finset.prod_congr rfl
            intro i _
            rw [hb i]
          _ = (∏ i, E i ^ b i) ^ p :=
            product_zpow_mul_exponents E b p

private theorem isPower_of_primitive_relation_and_cube_congruences
    {G ι : Type*} [CommGroup G] [Fintype ι]
    {p t : ℕ} (hp : p.Prime) (u : G) (E : ι → G)
    (a B : ι → ℤ)
    (hrel : u ^ t = ∏ i, E i ^ a i)
    (hprimitive : ¬(p ∣ t ∧ ∀ i, (p : ℤ) ∣ a i))
    (hcong : ∀ i, (p : ℤ) ^ 3 ∣ a i * B i)
    (hno : ∀ i, ¬(p : ℤ) ^ 3 ∣ B i) :
    IsRepaid p u := by
  have hdiv : ∀ i, (p : ℤ) ∣ a i := fun i ↦
    prime_dvd_of_cube_dvd_mul_of_not_cube_dvd hp (hcong i) (hno i)
  have hpt : ¬p ∣ t := fun h ↦ hprimitive ⟨h, hdiv⟩
  have hcop : t.Coprime p :=
    (hp.coprime_iff_not_dvd.mpr hpt).symm
  obtain ⟨d, hd⟩ :=
    product_zpow_is_pow_of_exponents_divisible E a p hdiv
  exact isPower_of_coprime_power_eq_power hcop (hrel.trans hd)

/-- The exact arithmetic input left by the generated algebra: Vandiver's
deep congruence forces coefficient-cube divisibility for every primitive
relation in the cycle's edge family.  This predicate assumes no root and no
repayment conclusion. -/
def DeepCoefficientForcing
    {R α : Type*} [CommRing R]
    (cycle : Cycle α) (realize : α → Rˣ)
    (p : ℕ) (ramified : R) (B : Fin cycle.rank → ℤ) : Prop :=
  ∀ (u : Rˣ), IsVandiverDeep p ramified u →
    ∀ (t : ℕ) (a : Fin cycle.rank → ℤ),
      0 < t →
      u ^ t = ∏ i, cycle.edge realize i ^ a i →
      ¬(p ∣ t ∧ ∀ i, (p : ℤ) ∣ a i) →
      ∀ i, (p : ℤ) ^ 3 ∣ a i * B i

/-- **C3 repayment.** A finite C2 capacity for the one generated edge
family, together with Vandiver's exact coefficient calculation, constructs
the repayment root. -/
theorem repay_of_deep_generated_cycle
    {R α : Type*} [CommRing R]
    {cycle : Cycle α} {realize : α → Rˣ}
    {p : ℕ} (hp : p.Prime)
    (data : Cycle.CapacityData cycle realize)
    (hambient : data.ambient = ⊤)
    (hpow : Function.Injective (fun x : Rˣ ↦ x ^ p))
    (ramified : R) (B : Fin cycle.rank → ℤ)
    (hforcing : DeepCoefficientForcing cycle realize p ramified B)
    (hno : ∀ i, ¬(p : ℤ) ^ 3 ∣ B i)
    {u : Rˣ} (hdeep : IsVandiverDeep p ramified u) :
    IsRepaid p u := by
  letI hfiniteGenerated :
      (cycle.generatedSubledger realize).FiniteIndex := by
    rw [← Subgroup.isFiniteRelIndex_top_iff]
    rw [← hambient]
    exact data.finite
  letI :
      (Subgroup.closure
        (Set.range (cycle.edge realize))).FiniteIndex := by
    simpa only [Cycle.generatedSubledger] using hfiniteGenerated
  obtain ⟨a, ht, hrel⟩ :=
    exists_index_relation (cycle.edge realize) u
  obtain ⟨t', a', ht', hrel', hprimitive⟩ :=
    exists_primitive_relation_of_relation hp.two_le hpow
      u (cycle.edge realize) a ht hrel
  exact isPower_of_primitive_relation_and_cube_congruences
    hp u (cycle.edge realize) a' B hrel' hprimitive
      (hforcing u hdeep t' a' ht' hrel' hprimitive) hno

end Repayment

end Fermat.Conservation.Credit
