/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, Fable

# C1: Kummer's credit vacuum

Credit lives on ordered pairs of nodes.  A funded generator contributes to
exactly the entry selected by its route; a ledger is therefore generated by
fibres of one route, rather than by an independently supplied matrix.

The semilattice operation is pointwise union.  The receivable view is the
transpose of the debit view, so it carries no second collection of data.
The final theorem records Kummer's regular-case lemma in this generated
language: if there is no funded generator, every fibre is empty and hence
the whole credit ledger is bottom.

This is only the route-neutral C1 accounting principle.  An arithmetic
instantiation must prove that its relevant set of funded generators is
empty; that premise is not hidden here as data or a postulate.
-/
import Mathlib.Data.Matrix.Basic
import Mathlib.Data.Set.Lattice

namespace Fermat.Conservation.Credit

universe u v

/-- A generator chooses one ordered debtor/creditor pair. -/
abbrev Route (Node : Type u) (Generator : Type v) :=
  Generator → Node × Node

/-- A two-sided credit ledger: each node pair contains the generators that
fund that entry. -/
abbrev Ledger (Node : Type u) (Generator : Type v) :=
  Matrix Node Node (Set Generator)

/-- The pointwise set lattice on a ledger.  In particular, its supremum is
entrywise union and its bottom has no generator in any entry. -/
instance ledgerCompleteAtomicBooleanAlgebra
    (Node : Type u) (Generator : Type v) :
    CompleteAtomicBooleanAlgebra (Ledger Node Generator) :=
  inferInstanceAs
    (CompleteAtomicBooleanAlgebra
      (Node → Node → Set Generator))

/-- The ledger generated by the funded generators and their routes. -/
def generated {Node : Type u} {Generator : Type v}
    (route : Route Node Generator) (funded : Set Generator) :
    Ledger Node Generator :=
  fun debtor creditor =>
    {generator | generator ∈ funded ∧
      route generator = (debtor, creditor)}

/-- Semilattice merge of two credit ledgers. -/
def merge {Node : Type u} {Generator : Type v}
    (left right : Ledger Node Generator) : Ledger Node Generator :=
  left ⊔ right

/-- The same ledger viewed from the opposite side. -/
def opposite {Node : Type u} {Generator : Type v}
    (ledger : Ledger Node Generator) : Ledger Node Generator :=
  ledger.transpose

/-- Reverse a route by swapping its debtor and creditor.  This is derived
from the original route; it is not independently supplied data. -/
def reverseRoute {Node : Type u} {Generator : Type v}
    (route : Route Node Generator) : Route Node Generator :=
  fun generator => (route generator).swap

/-- There is at least one generator capable of funding an entry. -/
def HasFundedGenerator {Generator : Type v}
    (funded : Set Generator) : Prop :=
  ∃ generator, generator ∈ funded

@[simp]
theorem mem_generated {Node : Type u} {Generator : Type v}
    (route : Route Node Generator) (funded : Set Generator)
    (debtor creditor : Node) (generator : Generator) :
    generator ∈ generated route funded debtor creditor ↔
      generator ∈ funded ∧ route generator = (debtor, creditor) :=
  Iff.rfl

@[simp]
theorem mem_merge {Node : Type u} {Generator : Type v}
    (left right : Ledger Node Generator)
    (debtor creditor : Node) (generator : Generator) :
    generator ∈ merge left right debtor creditor ↔
      generator ∈ left debtor creditor ∨
        generator ∈ right debtor creditor := by
  rfl

@[simp]
theorem merge_self {Node : Type u} {Generator : Type v}
    (ledger : Ledger Node Generator) :
    merge ledger ledger = ledger := by
  simpa only [merge] using (sup_idem ledger)

theorem merge_comm {Node : Type u} {Generator : Type v}
    (left right : Ledger Node Generator) :
    merge left right = merge right left := by
  simpa only [merge] using (sup_comm left right)

theorem merge_assoc {Node : Type u} {Generator : Type v}
    (first second third : Ledger Node Generator) :
    merge (merge first second) third =
      merge first (merge second third) := by
  simpa only [merge] using (sup_assoc first second third)

@[simp]
theorem merge_bot_left {Node : Type u} {Generator : Type v}
    (ledger : Ledger Node Generator) :
    merge (⊥ : Ledger Node Generator) ledger = ledger := by
  simpa only [merge] using (bot_sup_eq ledger)

@[simp]
theorem merge_bot_right {Node : Type u} {Generator : Type v}
    (ledger : Ledger Node Generator) :
    merge ledger (⊥ : Ledger Node Generator) = ledger := by
  simpa only [merge] using (sup_bot_eq ledger)

/-- Generating from a union is exactly semilattice merge. -/
@[simp]
theorem generated_union {Node : Type u} {Generator : Type v}
    (route : Route Node Generator) (left right : Set Generator) :
    generated route (left ∪ right) =
      merge (generated route left) (generated route right) := by
  ext debtor creditor generator
  simp only [mem_generated, mem_merge, Set.mem_union]
  tauto

@[simp]
theorem opposite_apply {Node : Type u} {Generator : Type v}
    (ledger : Ledger Node Generator) (debtor creditor : Node) :
    opposite ledger creditor debtor = ledger debtor creditor :=
  rfl

/-- Debit and receivable views are structurally two-sided: changing sides
twice recovers the one original ledger. -/
@[simp]
theorem opposite_opposite {Node : Type u} {Generator : Type v}
    (ledger : Ledger Node Generator) :
    opposite (opposite ledger) = ledger := by
  exact Matrix.transpose_transpose ledger

/-- Viewing from the opposite side preserves semilattice merge. -/
@[simp]
theorem opposite_merge {Node : Type u} {Generator : Type v}
    (left right : Ledger Node Generator) :
    opposite (merge left right) =
      merge (opposite left) (opposite right) :=
  rfl

@[simp]
theorem reverseRoute_reverseRoute {Node : Type u} {Generator : Type v}
    (route : Route Node Generator) :
    reverseRoute (reverseRoute route) = route := by
  funext generator
  exact Prod.swap_swap (route generator)

/-- Transposing a generated ledger is the same as reversing its one route.
No second ledger or independently seeded opposite route appears. -/
theorem opposite_generated {Node : Type u} {Generator : Type v}
    (route : Route Node Generator) (funded : Set Generator) :
    opposite (generated route funded) =
      generated (reverseRoute route) funded := by
  ext debtor creditor generator
  rcases hroute : route generator with ⟨source, target⟩
  simp [opposite, generated, reverseRoute, hroute, Prod.ext_iff]
  tauto

/-- The generated ledger is empty when no funded generator exists. -/
theorem generated_eq_bot_of_no_generator
    {Node : Type u} {Generator : Type v}
    (route : Route Node Generator) (funded : Set Generator)
    (hno : ¬ HasFundedGenerator funded) :
    generated route funded = ⊥ := by
  ext debtor creditor generator
  simp only [mem_generated]
  constructor
  · intro hgenerator
    exact (hno ⟨generator, hgenerator.1⟩).elim
  · intro hgenerator
    exact hgenerator.elim

/-- Kummer's regular-case credit vacuum, stated in generated form:
absence of a funded generator makes the entire credit matrix empty. -/
theorem kummer_credit_vacuum
    {Node : Type u} {Generator : Type v}
    (route : Route Node Generator) (funded : Set Generator)
    (kummerNoGenerator : ¬ HasFundedGenerator funded) :
    generated route funded = ⊥ :=
  generated_eq_bot_of_no_generator route funded kummerNoGenerator

end Fermat.Conservation.Credit
