import Fermat.Descent.Irregular.CyclicNatFourier
import Fermat.Exponents.OneThousandEightHundredThirtyOne.CircularUnitCyclic
import Mathlib.Tactic.NormNum.Prime

/-!
# Selective Case-II.1 residue data for p = 1831, q = 18311

This module is an independent auxiliary-prime receipt for comparison
with the existing q = 358877 receipt. The phase convention is exactly the
repository's real cycle generated by 3 modulo 1831.

The 915 entries use rho = 2^10 = 1024 modulo 18311,
W(x) = (1 - x)^10 / x^5, e_r = 915 * 3^r modulo 1831, and
phase[r] = log_rho (W(rho^e_r) / W(rho^915)).

Generated-vector SHA-256 (comma-separated decimal representatives):
07b37f3d2ec47e492dad3ba2ffe71ded2e05a099ec5250d6a4d7665bb8eb41e6.

The irregular numerical Fourier fact exposed here is actual frequency 278
(zero-based storage slot 277), whose coefficient is 1165 modulo 1831.  A
second regression records that regular frequency 636 vanishes. Thus this
auxiliary prime supports the selective channel proof but cannot support the
stronger full-determinant proof.
-/

namespace Fermat.OneThousandEightHundredThirtyOne.CircularUnitIrregularChannel1831AtQ18311

open Fermat.Irregular.CyclicDifferenceMatrix
open Fermat.Irregular.CyclicNatFourier
open Fermat.OneThousandEightHundredThirtyOne.CircularUnitCyclic

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

local instance : Fact (Nat.Prime 1831) := ⟨by decide⟩
local instance : Fact (Nat.Prime 18311) := ⟨by norm_num⟩

/-- The symbol exponent in 18311 - 1 = 10 * 1831. -/
def symbolExponent : ℕ := 10

/-- The order-1831 residue root 2^10 modulo 18311. -/
def residueRoot : ZMod 18311 := 1024

/-- The chosen residue root has exact order 1831. -/
theorem residueRoot_isPrimitive : IsPrimitiveRoot residueRoot 1831 := by
  rw [IsPrimitiveRoot.iff_orderOf]
  apply orderOf_eq_prime
  · change (1024 : ZMod 18311) ^ 1831 = 1
    calc
      (1024 : ZMod 18311) ^ 1831 = ((2 : ZMod 18311) ^ 10) ^ 1831 := by
        norm_num
      _ = (2 : ZMod 18311) ^ (10 * 1831) := by rw [pow_mul]
      _ = (2 : ZMod 18311) ^ (18311 - 1) := by norm_num
      _ = 1 := ZMod.pow_card_sub_one_eq_one (by decide)
  · change (1024 : ZMod 18311) ≠ 1
    decide

/-- The q-dependent phase in the fixed p-dependent cyclic coordinates. -/
def symbolPhaseData : Array Nat :=
  #[0,1477,1811,721,1742,1693,854,1314,284,868,243,963,1069,1206,176,123,1369,1110,1170,260,1811,1155,532,65,1322,263,1592,1325,681,1050,1540,737,1489,1303,1813,1544,1396,955,1651,600,573,867,163,1102,1183,829,1083,13,544,1105,1681,1565,1601,1331,111,966,1478,1818,554,1196,28,1711,1204,1500,1423,788,1344,1780,1065,1738,1746,651,946,709,1215,1251,763,172,204,121,1526,1154,818,1770,46,1085,1197,237,1363,1229,802,266,102,1229,469,1590,1739,580,887,1481,1313,1439,1272,1524,904,1791,1194,853,425,1138,1653,477,821,384,1314,1027,908,164,1140,219,1024,1735,997,1323,1326,639,842,413,102,953,1361,759,1252,790,1148,11,1391,1503,1562,670,1360,191,1622,445,1372,996,279,1529,298,113,280,959,126,1817,671,290,1121,1304,696,1620,722,1240,513,1342,237,0,627,634,1694,1163,925,473,1704,685,1180,922,789,964,1355,363,976,1688,1618,974,563,275,349,1563,1166,1453,431,675,107,1759,695,886,1609,404,468,1787,1541,1612,180,860,1814,1264,351,661,1583,775,587,890,94,1761,598,1130,1076,278,960,1446,40,1338,3,1657,1410,1277,730,209,1149,1117,630,312,400,354,364,779,305,697,181,404,709,1354,1173,631,949,1210,1578,86,854,52,142,574,281,1295,473,1520,465,660,282,1787,525,896,445,184,811,473,644,1625,921,1431,1258,183,1631,62,1538,903,487,226,1386,1321,785,457,1382,672,359,568,326,903,374,1018,116,177,453,1264,984,10,1107,259,1656,67,423,1196,1252,889,561,574,546,1250,1765,1567,173,1021,14,111,9,763,139,1081,1569,1774,1435,1713,1586,1186,327,1411,731,420,504,564,281,142,1428,777,49,1431,54,471,1115,1167,1650,1798,136,358,252,822,68,1026,1740,414,390,1537,1594,370,1239,1566,1750,1553,995,1187,857,143,1439,1624,865,512,1633,1304,952,7,1646,1013,61,875,292,572,1316,1278,650,1170,275,1340,174,1165,1011,87,1462,549,33,1564,1516,440,162,338,80,1503,1378,676,1574,1633,932,217,1162,873,1131,1297,258,1428,1375,1161,1550,573,1034,835,1659,270,1580,494,1443,438,16,671,134,1467,1666,764,1573,1133,295,1445,44,888,502,1015,117,1715,1438,1765,751,1627,1268,282,209,1095,1546,554,1647,1243,1682,1550,1522,760,758,212,792,744,29,1275,684,278,1601,421,1614,789,586,1645,27,1089,1299,1709,81,54,1036,797,859,1058,1335,606,125,1738,1364,214,1135,1433,1704,741,1518,695,985,10,742,663,758,130,1161,1208,608,260,1709,1356,451,1150,1418,1037,1416,1434,823,1511,1199,1288,1343,960,511,589,288,1546,393,1090,286,385,238,1566,1199,37,166,1407,746,1400,296,1287,523,1222,95,798,1480,516,1736,737,1818,575,216,833,1505,63,137,1092,377,1100,1238,1278,2,316,1412,396,675,1303,1,987,777,1043,1177,1426,146,1176,604,976,1252,20,1707,625,311,1321,904,1558,798,1602,1613,1074,1698,1338,708,264,903,227,1588,1298,362,1528,1155,954,190,694,1497,137,421,187,835,809,1715,375,562,497,219,1562,1579,844,300,33,807,1521,946,301,1006,948,324,1533,1775,1199,1650,644,1261,951,35,958,1595,1260,1287,882,1044,137,1382,231,353,757,426,704,95,614,438,1780,765,1384,949,270,1332,898,294,938,1171,1596,836,1544,864,788,167,1520,830,1179,189,1224,458,833,136,678,67,689,163,414,557,1190,1274,464,86,1104,322,1600,274,878,1282,1300,1698,1067,1764,1729,1301,338,1495,1815,1114,1282,1748,1768,1572,1299,1025,598,1510,1712,1236,1755,347,473,980,105,1361,1205,989,1607,598,601,485,23,460,1540,1655,1672,835,339,319,25,133,1219,140,3,112,238,1400,222,1058,806,1160,1494,1493,1190,1257,369,1284,900,1727,229,504,599,996,532,1608,1263,1160,63,1067,420,1633,1190,1411,1225,359,254,185,40,1192,1237,209,1232,1207,1247,857,1723,1803,673,892,486,365,612,203,1747,1715,1388,119,172,1064,993,660,964,621,1127,584,1250,472,1121,830,995,1710,938,1559,1112,933,1432,1262,529,1311,1358,1747,710,1033,196,1141,1462,1567,617,1558,1751,856,1377,225,1178,556,1618,1715,159,1091,1371,110,1166,1630,1451,905,835,1249,1609,661,82,646,24,884,174,1722,610,175,455,1598,1800,297,1476,242,1192,977,485,1159,1430,1010,396,206,1056,1553,915,1699,1420,704,616,1385,1052,422,335,418,1321,828,612,544,1476,1809,1360,1261,1801,843,608,787,666,843,1460,874,1030,140,781,1559,1580,666,674,190,1714,434,44,727,1038,755,1243,1499,380,1100,1789,1481,761,1320,872,39,1371,1707,49,1129,115,428,722,765,1383,1447,1717,1094]

/-- The normalized power-residue phase on the real cyclic quotient. -/
def symbolPhase (x : Cyc) : ZMod 1831 :=
  symbolPhaseData[x.val]!

/-- 9 = 3 squared has exact order 915 modulo 1831. -/
theorem fourierRoot_isPrimitive : IsPrimitiveRoot (9 : ZMod 1831) 915 := by
  rw [IsPrimitiveRoot.iff_orderOf]
  apply orderOf_eq_of_pow_and_pow_div_prime (by norm_num) (by decide)
  intro q hq hqdiv
  have hfac : q ∣ 3 * (5 * 61) := by
    simpa using hqdiv
  have hcases : q = 3 ∨ q = 5 ∨ q = 61 := by
    rcases (hq.dvd_mul).mp hfac with h3 | hrest
    · exact Or.inl ((Nat.prime_dvd_prime_iff_eq hq (by decide)).mp h3)
    rcases (hq.dvd_mul).mp hrest with h5 | h61
    · exact Or.inr <| Or.inl
        ((Nat.prime_dvd_prime_iff_eq hq (by decide)).mp h5)
    · exact Or.inr <| Or.inr
        ((Nat.prime_dvd_prime_iff_eq hq (by decide)).mp h61)
  rcases hcases with rfl | rfl | rfl <;> decide

/-- Nontrivial Fourier slot k represents actual frequency k + 1. -/
abbrev coefficient (k : Fin 914) : ZMod 1831 :=
  fourierCoeff (9 : ZMod 1831)
    fourierRoot_isPrimitive.pow_eq_one symbolPhase k

/-- Actual frequency 278, in zero-based storage convention. -/
def slot : Fin 914 := 277

private theorem coefficient_eq_of_evaluate (k : Fin 914)
    (root value : ℕ)
    (hroot : (root : ZMod 1831) =
      (9 : ZMod 1831) ^ (k.val + 1))
    (heval : evaluate 1831 root symbolPhaseData.toList = value) :
    coefficient k = value := by
  change fourierCoeff (9 : ZMod 1831)
    fourierRoot_isPrimitive.pow_eq_one symbolPhase k = value
  rw [fourierCoeff_eq_sum_pow]
  have hcast := congrArg (fun x : ℕ ↦ (x : ZMod 1831)) heval
  rw [cast_evaluate_toList_eq_cyclicSum
    1831 915 root symbolPhaseData (by decide)] at hcast
  simpa only [symbolPhase, hroot, pow_mul, Nat.cast_ofNat] using hcast

/-- At actual frequency 278, the q=18311 detector is 1165. -/
theorem fhat_277_eq : coefficient slot = 1165 :=
  coefficient_eq_of_evaluate slot 878 1165
    (by decide) (by decide)

/-- The q=18311 detector on the unique irregular channel is nonzero. -/
theorem fhat_277_ne_zero : coefficient slot ≠ 0 := by
  rw [fhat_277_eq]
  decide

/-- Zero-based storage slot for the regular actual frequency `636`. -/
def regularZeroSlot : Fin 914 := 635

/-- The `q = 18311` residue matrix has a blind regular mode at frequency
`636`. This is why it cannot certify full matrix nonsingularity. -/
theorem fhat_635_eq_zero : coefficient regularZeroSlot = 0 :=
  coefficient_eq_of_evaluate regularZeroSlot 453 0
    (by decide) (by decide)

end Fermat.OneThousandEightHundredThirtyOne.CircularUnitIrregularChannel1831AtQ18311
