import Fermat.FourHundredNinetyOne.CircularUnitResidues
import Fermat.FourHundredNinetyOne.VandiverDiagonalArithmetic491
import Mathlib.LinearAlgebra.Vandermonde

/-!
# Residue and Fourier certificates for Vandiver's diagonal units at 491

This module derives the residue matrix of Vandiver's 244 diagonal units
from the already certified circular-unit matrix at `q = 983`.

The 245 basic factors form the edges of the cyclic ordering generated by
`57` modulo sign.  Their positive integral weights are the nontrivial even
characters of that cycle.  Consequently the change of basis is a scaled
transpose Vandermonde matrix.  This avoids both a `244 × 245` Cartesian
certificate and a second explicit dense inverse.
-/

namespace Fermat.FourHundredNinetyOne.VandiverDiagonalUnitResidues

open Fermat.FourHundredNinetyOne.VandiverDiagonalArithmetic
open Fermat.FourHundredNinetyOne.CircularUnitCyclic
open Fermat.FourHundredNinetyOne.CircularUnitEntryCertificate
open Fermat.FourHundredNinetyOne.CircularUnitMatrix
open Fermat.Irregular.CircularUnitFamily
open Fermat.Irregular.CircularUnitResidues
open Fermat.Irregular.CircularUnitResidues.Certificate

local instance : Fact (Nat.Prime 491) := ⟨by norm_num⟩
local instance : Fact (Nat.Prime 983) := ⟨by norm_num⟩

set_option maxHeartbeats 3000000
set_option maxRecDepth 1000000

/-- The canonical circular-unit column corresponding to the real class
of `57^(j+1)`. -/
def cycleColumn491 (j : Fin 244) : Fin 244 :=
  let s := ((teichmullerRoot491 : ZMod 491) ^ (j.val + 1)).val
  let a := min s (491 - s)
  ⟨(a - 2) % 244, Nat.mod_lt _ (by norm_num)⟩

/-- The powers of `57` visit every nontrivial real class exactly once. -/
theorem cycleColumn491_bijective :
    Function.Bijective cycleColumn491 := by decide

noncomputable def cycleColumnEquiv491 : Fin 244 ≃ Fin 244 :=
  Equiv.ofBijective cycleColumn491 cycleColumn491_bijective

/-- The nontrivial even Fourier nodes `57^(-2n)`, `1 ≤ n ≤ 244`. -/
def vandermondeNode491 (i : Fin 244) : ZMod 491 :=
  (teichmullerRoot491 : ZMod 491) ^ (488 - 2 * i.val)

theorem vandermondeNode491_injective :
    Function.Injective vandermondeNode491 := by decide

/-- Column scale converting powers `0, ..., 243` to Vandiver's edge
coefficients. -/
def fourierScale491 (i : Fin 244) : ZMod 491 :=
  ((teichmullerRoot491 : ZMod 491) ^ (2 * (i.val + 1)) - 1) *
    (teichmullerRoot491 : ZMod 491) * vandermondeNode491 i

theorem fourierScale491_ne_zero (i : Fin 244) :
    fourierScale491 i ≠ 0 := by
  fin_cases i <;> decide

/-- The edge-to-diagonal change of basis. -/
def fourierChange491 : Matrix (Fin 244) (Fin 244) (ZMod 491) :=
  (Matrix.vandermonde vandermondeNode491).transpose *
    Matrix.diagonal fourierScale491

theorem fourierChange491_apply (row i : Fin 244) :
    fourierChange491 row i =
      vandermondeNode491 i ^ row.val * fourierScale491 i := by
  rw [fourierChange491, Matrix.mul_diagonal]
  rfl

/-- The scaled Fourier matrix is nonsingular. -/
theorem fourierChange491_det_ne_zero :
    fourierChange491.det ≠ 0 := by
  rw [fourierChange491, Matrix.det_mul, Matrix.det_transpose,
    Matrix.det_diagonal]
  exact mul_ne_zero
    (Matrix.det_vandermonde_ne_zero_iff.mpr
      vandermondeNode491_injective)
    (Finset.prod_ne_zero_iff.mpr
      (fun i _ ↦ fourierScale491_ne_zero i))

abbrev certificate491 : Certificate 491 983 :=
  Fermat.FourHundredNinetyOne.CircularUnitResidues.certificate

/-- Extend the circular-unit cycle by the trivial class at positions zero
and 245. -/
def cycleClassSymbol491 (row : Fin 244) (ell : ℕ) : ZMod 491 :=
  if h : 1 ≤ ell ∧ ell ≤ 244 then
    Fermat.FourHundredNinetyOne.CircularUnitMatrix.matrix row
      (cycleColumn491 ⟨ell - 1, by omega⟩)
  else 0

/-- The symbol of the `j`th basic factor is the difference of adjacent
circular-unit symbols. -/
def basicEdgeSymbol491 (row : Fin 244) (j : Fin 245) : ZMod 491 :=
  cycleClassSymbol491 row (j.val + 1) -
    cycleClassSymbol491 row j.val

/-- Literal source exponent `2512^j`. -/
def conjugateExponent491 (j : Fin 245) : ℕ :=
  teichmullerRoot491 ^ j.val

/-- Its small reduction modulo `491`. -/
def reducedConjugateExponent491 (j : Fin 245) : ℕ :=
  ((teichmullerRoot491 : ZMod 491) ^ j.val).val

theorem conjugateExponent491_modEq_reduced (j : Fin 245) :
    conjugateExponent491 j ≡ reducedConjugateExponent491 j [MOD 491] := by
  rw [← ZMod.natCast_eq_natCast_iff]
  simp [conjugateExponent491, reducedConjugateExponent491]

theorem pow_conjugateExponent491_eq_reduced {G : Type*} [Monoid G]
    (x : G) (hx : x ^ 491 = 1) (j : Fin 245) :
    x ^ conjugateExponent491 j = x ^ reducedConjugateExponent491 j :=
  pow_eq_pow_of_modEq (conjugateExponent491_modEq_reduced j) hx

/-- The literal 2512-term geometric sum in the finite-field reduction. -/
def basicResidueGeomSum491 (row : Fin 244) (j : Fin 245) : ZMod 983 :=
  let w := embeddingRoot (p := 491) certificate491.root row ^
    conjugateExponent491 j
  ∑ k ∈ Finset.range 2512, w ^ k

/-- Reduction of the normalized basic factor. -/
def basicResidueValue491 (row : Fin 244) (j : Fin 245) : ZMod 983 :=
  let w := embeddingRoot (p := 491) certificate491.root row ^
    conjugateExponent491 j
  w ^ 463 * basicResidueGeomSum491 row j

/-- Since `2512 = 5 * 491 + 57`, the literal source sum reduces to
length 57 at a 491st root. -/
theorem basicResidueGeomSum491_eq (row : Fin 244) (j : Fin 245) :
    basicResidueGeomSum491 row j =
      ∑ k ∈ Finset.range 57,
        (embeddingRoot (p := 491) certificate491.root row ^
          conjugateExponent491 j) ^ k := by
  let w : ZMod 983 :=
    embeddingRoot (p := 491) certificate491.root row ^
      conjugateExponent491 j
  have hwroot : IsPrimitiveRoot w 491 := by
    apply (embeddingRoot_isPrimitive certificate491.hp2
      certificate491.root_isPrimitive row).pow_of_coprime
    exact (by norm_num : Nat.Coprime 2512 491).pow_left j.val
  have hwne : w - 1 ≠ 0 :=
    sub_ne_zero.mpr (hwroot.ne_one (by norm_num))
  apply mul_left_cancel₀ (a := w - 1) hwne
  rw [show (w - 1) * basicResidueGeomSum491 row j = w ^ 2512 - 1 by
    simpa [basicResidueGeomSum491, w] using (mul_geom_sum w 2512)]
  rw [show (w - 1) *
      (∑ k ∈ Finset.range 57,
        (embeddingRoot (p := 491) certificate491.root row ^
          conjugateExponent491 j) ^ k) = w ^ 57 - 1 by
    simpa [w] using (mul_geom_sum w 57)]
  rw [show 2512 = 491 * 5 + 57 by norm_num, pow_add, pow_mul,
    hwroot.pow_eq_one, one_pow, one_mul]

/-! ## Compact cyclic provenance

The real residue group is cyclic of order 245.  Thus the edge-symbol and
normalized-value identities factor through two one-variable certificates
and an algebraic phase argument. -/

/-- In the real cyclic quotient, multiplication by `57` is translation by
`62`; equivalently, `2^62 = -57 (mod 491)`. -/
theorem cycleColumn491_coord (ell : Fin 244) :
    coord (columnPermutation (cycleColumn491 ell)) =
      ((62 * (ell.val + 1) : ℕ) : Cyc) := by
  decide +revert

/-- The stored column is the canonical representative of
`57^(ell+1)` up to the harmless real-class sign. -/
theorem cycleColumn491_realRepresentative (ell : Fin 244) :
    let a := ((cycleColumn491 ell).val + 2 : ZMod 491)
    let d := (teichmullerRoot491 : ZMod 491) ^ (ell.val + 1)
    a = d ∨ a = -d := by
  decide +revert

/-- Cyclic coordinate of an original embedding row. -/
def rowCycleCoord491 (row : Fin 244) : Cyc :=
  coord (rowPermutation row)

/-- Extend the literal conjugate powers through the wrap at exponent
`245`. -/
def extendedConjugateExponent491 (ell : Fin 246) : ℕ :=
  teichmullerRoot491 ^ ell.val

/-- Its cyclic real-residue coordinate. -/
def extendedCycleCoord491 (ell : Fin 246) : Cyc :=
  ((62 * ell.val : ℕ) : Cyc)

private theorem weight_eq_of_eq_or_inv {x y : ZMod 983}
    (hy : y ≠ 0) (h : x = y ∨ x = y⁻¹) :
    weight x = weight y := by
  rcases h with h | h
  · rw [h]
  · rw [h, weight_inv y hy]

private theorem pow_eq_inv_pow_of_cast_eq_neg
    {x : ZMod 983} (hx : IsPrimitiveRoot x 491)
    {a b : ℕ}
    (h : (a : ZMod 491) = -(b : ZMod 491)) :
    x ^ a = (x ^ b)⁻¹ := by
  have hab : a + b ≡ 0 [MOD 491] := by
    rw [← ZMod.natCast_eq_natCast_iff]
    simpa only [Nat.cast_add, Nat.cast_zero, add_eq_zero_iff_eq_neg] using h
  have hp : x ^ (a + b) = 1 := by
    simpa using pow_eq_pow_of_modEq hab hx.pow_eq_one
  apply (mul_eq_one_iff_eq_inv₀
    (pow_ne_zero b (hx.ne_zero (by norm_num)))).mp
  rw [← pow_add]
  exact hp

private theorem pow_eq_or_inv_pow_of_cast_eq_or_neg
    {x : ZMod 983} (hx : IsPrimitiveRoot x 491)
    {a b : ℕ}
    (h : (a : ZMod 491) = b ∨ (a : ZMod 491) = -(b : ZMod 491)) :
    x ^ a = x ^ b ∨ x ^ a = (x ^ b)⁻¹ := by
  rcases h with h | h
  · left
    apply pow_eq_pow_of_modEq _ hx.pow_eq_one
    rw [← ZMod.natCast_eq_natCast_iff]
    exact h
  · exact Or.inr (pow_eq_inv_pow_of_cast_eq_neg hx h)

/-- The weight of every conjugated root is its cyclic phase weight.  This
is parametric in the row; only the two column-orientation facts above are
checked finitely. -/
theorem extendedConjugateWeight491 (row : Fin 244) (ell : Fin 246) :
    let x := embeddingRoot (p := 491) (2 : ZMod 983) row
    weight (x ^ extendedConjugateExponent491 ell) =
      weight (classRoot (rowCycleCoord491 row + extendedCycleCoord491 ell)) := by
  let x := embeddingRoot (p := 491) (2 : ZMod 983) row
  change
    weight (x ^ extendedConjugateExponent491 ell) =
      weight (classRoot (rowCycleCoord491 row + extendedCycleCoord491 ell))
  have hxprim : IsPrimitiveRoot x 491 :=
    embeddingRoot_isPrimitive (p := 491) (q := 983) (by norm_num)
      root_isPrimitive row
  have hx0 : x ≠ 0 := hxprim.ne_zero (by norm_num)
  by_cases hzero : ell.val = 0
  · have hell : ell = ⟨0, by norm_num⟩ := Fin.ext hzero
    subst ell
    have hrow :
        classRoot (rowCycleCoord491 row) = x ∨
          classRoot (rowCycleCoord491 row) = x⁻¹ := by
      simpa [x, rowCycleCoord491] using row_root_relation row
    have hw := weight_eq_of_eq_or_inv hx0 hrow
    simpa [x, rowCycleCoord491, extendedConjugateExponent491,
      extendedCycleCoord491] using hw.symm
  by_cases hlast : ell.val = 245
  · have hell : ell = ⟨245, by norm_num⟩ := Fin.ext hlast
    subst ell
    have hpow245 :
        x ^ extendedConjugateExponent491 ⟨245, by norm_num⟩ = x⁻¹ := by
      have hcast :
          (extendedConjugateExponent491 ⟨245, by norm_num⟩ : ZMod 491) =
            -(1 : ZMod 491) := by
        decide +kernel
      simpa only [pow_one] using
        pow_eq_inv_pow_of_cast_eq_neg hxprim hcast
    have hrow :
        classRoot (rowCycleCoord491 row) = x ∨
          classRoot (rowCycleCoord491 row) = x⁻¹ := by
      simpa [x, rowCycleCoord491] using row_root_relation row
    have hw := weight_eq_of_eq_or_inv hx0 hrow
    have hcoordlast :
        extendedCycleCoord491 ⟨245, by norm_num⟩ = 0 := by
      decide
    calc
      weight
          (x ^ extendedConjugateExponent491 ⟨245, by norm_num⟩) =
          weight x⁻¹ := congrArg weight hpow245
      _ = weight x := weight_inv x hx0
      _ = weight
          (classRoot
            (rowCycleCoord491 row +
              extendedCycleCoord491 ⟨245, by norm_num⟩)) := by
        rw [hcoordlast, add_zero]
        exact hw.symm
  · have hpos : 1 ≤ ell.val := by omega
    have hle : ell.val ≤ 244 := by omega
    let k : Fin 244 := ⟨ell.val - 1, by omega⟩
    have hk : k.val + 1 = ell.val := by simp [k]; omega
    let a := (cycleColumn491 k).val + 2
    have hrep := cycleColumn491_realRepresentative k
    have hcast :
        (a : ZMod 491) =
            (extendedConjugateExponent491 ell : ZMod 491) ∨
          (a : ZMod 491) =
            -(extendedConjugateExponent491 ell : ZMod 491) := by
      simpa [a, extendedConjugateExponent491, hk] using hrep
    have hpow := pow_eq_or_inv_pow_of_cast_eq_or_neg hxprim hcast
    have hpowWeight :
      weight (x ^ a) =
          weight (x ^ extendedConjugateExponent491 ell) :=
      weight_eq_of_eq_or_inv
        (pow_ne_zero (extendedConjugateExponent491 ell) hx0) hpow
    have hprod :
        classRoot
            (rowCycleCoord491 row +
              coord (columnPermutation (cycleColumn491 k))) =
            x ^ a ∨
          classRoot
            (rowCycleCoord491 row +
              coord (columnPermutation (cycleColumn491 k))) =
            (x ^ a)⁻¹ := by
      simpa [x, a, rowCycleCoord491] using
        product_root_relation row (cycleColumn491 k)
    have hprodWeight :
        weight
            (classRoot
              (rowCycleCoord491 row +
                coord (columnPermutation (cycleColumn491 k)))) =
          weight (x ^ a) := by
      exact weight_eq_of_eq_or_inv (pow_ne_zero a hx0) hprod
    rw [cycleColumn491_coord k] at hprodWeight
    have hcoord :
        ((62 * (k.val + 1) : ℕ) : Cyc) = extendedCycleCoord491 ell := by
      simp only [extendedCycleCoord491, hk]
    rw [hcoord] at hprodWeight
    exact (hprodWeight.trans hpowWeight).symm

private theorem normalizedGeom_pow_eq_weight_ratio
    (w : ZMod 983) (hw : IsPrimitiveRoot w 491) (a e : ℕ)
    (hexp : 2 * e + a ≡ 1 [MOD 491]) :
    (w ^ e * ∑ k ∈ Finset.range a, w ^ k) ^ 2 =
      weight (w ^ a) / weight w := by
  have hw0 : w ≠ 0 := hw.ne_zero (by norm_num)
  have hw1 : 1 - w ≠ 0 :=
    sub_ne_zero.mpr (Ne.symm (hw.ne_one (by norm_num)))
  have hgeom :
      ∑ k ∈ Finset.range a, w ^ k = (1 - w ^ a) / (1 - w) := by
    apply (eq_div_iff hw1).2
    calc
      (∑ k ∈ Finset.range a, w ^ k) * (1 - w) =
          -((w - 1) * ∑ k ∈ Finset.range a, w ^ k) := by ring
      _ = -(w ^ a - 1) := by rw [mul_geom_sum]
      _ = 1 - w ^ a := by ring
  rw [hgeom, ← mul_div_assoc]
  change (w ^ e * (1 - w ^ a) / (1 - w)) ^ 2 =
    weight (w ^ a) / weight w
  have hpow : w ^ (2 * e + a) = w := by
    simpa using pow_eq_pow_of_modEq hexp hw.pow_eq_one
  simp only [weight, mul_pow, div_pow]
  field_simp [hw0, hw1]
  have hpow' : w ^ (e * 2) * w ^ a = w := by
    rw [← pow_add]
    simpa [Nat.mul_comm] using hpow
  calc
    _ = (w ^ (e * 2) * w ^ a) * (1 - w ^ a) ^ 2 := by ring
    _ = w * (1 - w ^ a) ^ 2 := by rw [hpow']
    _ = _ := by ring

theorem normalizedLength57_pow_eq_weight_ratio
    (w : ZMod 983) (hw : IsPrimitiveRoot w 491) :
    (w ^ 463 * ∑ k ∈ Finset.range 57, w ^ k) ^ 2 =
      weight (w ^ 57) / weight w :=
  normalizedGeom_pow_eq_weight_ratio w hw 57 463 (by norm_num)

/-- The extended cycle symbols are ordinary differences of the compressed
phase vector. -/
theorem cycleClassSymbol491_succ_phase (row ell : Fin 244) :
    cycleClassSymbol491 row (ell.val + 1) =
      symbolPhase
          (rowCycleCoord491 row +
            ((62 * (ell.val + 1) : ℕ) : Cyc)) -
        symbolPhase (rowCycleCoord491 row) := by
  rw [cycleClassSymbol491, dif_pos]
  · change
      symbolPhase
            (coord (rowPermutation row) +
              coord (columnPermutation (cycleColumn491 ell))) -
          symbolPhase (coord (rowPermutation row)) =
        _
    rw [cycleColumn491_coord]
    rfl
  · omega

theorem cycleClassSymbol491_phase (row : Fin 244) (ell : ℕ)
    (hell : ell ≤ 245) :
    cycleClassSymbol491 row ell =
      symbolPhase
          (rowCycleCoord491 row + ((62 * ell : ℕ) : Cyc)) -
        symbolPhase (rowCycleCoord491 row) := by
  by_cases hzero : ell = 0
  · subst ell
    simp [cycleClassSymbol491]
  by_cases hlast : ell = 245
  · subst ell
    have hcoord : (((62 * 245 : ℕ) : Cyc)) = 0 := by decide
    rw [cycleClassSymbol491, dif_neg (by omega), hcoord, add_zero, sub_self]
  · have hpos : 1 ≤ ell := by omega
    have hle : ell ≤ 244 := by omega
    let k : Fin 244 := ⟨ell - 1, by omega⟩
    have hk : k.val + 1 = ell := by simp [k]; omega
    simpa only [hk] using cycleClassSymbol491_succ_phase row k

theorem basicEdgeSymbol491_phase (row : Fin 244) (j : Fin 245) :
    basicEdgeSymbol491 row j =
      symbolPhase
          ((rowCycleCoord491 row +
              extendedCycleCoord491 j.castSucc) + 62) -
        symbolPhase
          (rowCycleCoord491 row +
            extendedCycleCoord491 j.castSucc) := by
  rw [basicEdgeSymbol491,
    cycleClassSymbol491_phase row (j.val + 1) (by omega),
    cycleClassSymbol491_phase row j.val (by omega)]
  simp only [extendedCycleCoord491, Fin.val_castSucc]
  have hstep :
      rowCycleCoord491 row + ((62 * (j.val + 1) : ℕ) : Cyc) =
        (rowCycleCoord491 row + ((62 * j.val : ℕ) : Cyc)) + 62 := by
    push_cast
    ring
  rw [hstep]
  ring

theorem extendedConjugateStep491
    (x : ZMod 983) (hx : IsPrimitiveRoot x 491) (j : Fin 245) :
    (x ^ extendedConjugateExponent491 j.castSucc) ^ 57 =
      x ^ extendedConjugateExponent491 j.succ := by
  rw [← pow_mul]
  apply pow_eq_pow_of_modEq _ hx.pow_eq_one
  change
    teichmullerRoot491 ^ j.val * 57 ≡
      teichmullerRoot491 ^ (j.val + 1) [MOD 491]
  rw [pow_succ]
  exact (by norm_num [teichmullerRoot491] :
    57 ≡ teichmullerRoot491 [MOD 491]).mul_left _

private def reducedBasicResidueValue491
    (row : Fin 244) (j : Fin 245) : ZMod 983 :=
  let x := embeddingRoot (p := 491) (2 : ZMod 983) row
  let w := x ^ extendedConjugateExponent491 j.castSucc
  w ^ 463 * ∑ k ∈ Finset.range 57, w ^ k

private theorem reducedBasicResidueValue491_symbol
    (row : Fin 244) (j : Fin 245) :
    reducedBasicResidueValue491 row j ^ 2 =
      (2 : ZMod 983) ^ (basicEdgeSymbol491 row j).val := by
  let x := embeddingRoot (p := 491) (2 : ZMod 983) row
  let w := x ^ extendedConjugateExponent491 j.castSucc
  have hxprim : IsPrimitiveRoot x 491 :=
    embeddingRoot_isPrimitive (p := 491) (q := 983) (by norm_num)
      root_isPrimitive row
  have hwprim : IsPrimitiveRoot w 491 := by
    apply hxprim.pow_of_coprime
    exact (by norm_num : Nat.Coprime 2512 491).pow_left j.val
  change (w ^ 463 * ∑ k ∈ Finset.range 57, w ^ k) ^ 2 = _
  rw [normalizedLength57_pow_eq_weight_ratio w hwprim]
  have hcur :
      weight w =
        weight
          (classRoot
            (rowCycleCoord491 row +
              extendedCycleCoord491 j.castSucc)) := by
    simpa [x, w] using extendedConjugateWeight491 row j.castSucc
  have hnext :
      weight (x ^ extendedConjugateExponent491 j.succ) =
        weight
          (classRoot
            (rowCycleCoord491 row +
              extendedCycleCoord491 j.succ)) := by
    simpa [x] using extendedConjugateWeight491 row j.succ
  have hstep := extendedConjugateStep491 x hxprim j
  rw [hstep, hnext, hcur]
  have hcoord :
      rowCycleCoord491 row + extendedCycleCoord491 j.succ =
        (rowCycleCoord491 row +
          extendedCycleCoord491 j.castSucc) + 62 := by
    simp only [extendedCycleCoord491, Fin.val_succ, Fin.val_castSucc]
    push_cast
    ring
  rw [hcoord, weight_ratio_eq_phase_ratio,
    phase_value_certificate, phase_value_certificate,
    ← root_pow_sub_val]
  rw [basicEdgeSymbol491_phase]

/-- Complete provenance of every basic-factor residue symbol, derived from
the one-variable cyclic certificates rather than a Cartesian case split. -/
theorem basicResidueValue491_symbol (row : Fin 244) (j : Fin 245) :
    basicResidueValue491 row j ^ 2 =
      certificate491.root ^ (basicEdgeSymbol491 row j).val := by
  rw [basicResidueValue491, basicResidueGeomSum491_eq]
  simpa [reducedBasicResidueValue491, extendedConjugateExponent491,
    conjugateExponent491, certificate491,
    Fermat.FourHundredNinetyOne.CircularUnitResidues.certificate] using
    reducedBasicResidueValue491_symbol row j

end Fermat.FourHundredNinetyOne.VandiverDiagonalUnitResidues
