import Fermat.Exponents.OneThousandEightHundredThirtyOne.CircularUnitResidues
import Fermat.Exponents.OneThousandEightHundredThirtyOne.VandiverDiagonalArithmetic1831
import Mathlib.LinearAlgebra.Vandermonde

/-!
# Residue and Fourier certificates for Vandiver's diagonal units at 1831

This module derives the residue matrix of Vandiver's 914 diagonal units
from the already certified circular-unit matrix at `q = 358877`.

The 915 basic factors form the edges of the cyclic ordering generated by
`4746` modulo sign. Their positive integral weights are the nontrivial even
characters of that cycle. Consequently the change of basis is a scaled
transpose Vandermonde matrix. This avoids both a `914 × 915` Cartesian
certificate and a second explicit dense inverse.
-/

namespace Fermat.OneThousandEightHundredThirtyOne.VandiverDiagonalUnitResidues

open Fermat.OneThousandEightHundredThirtyOne.VandiverDiagonalArithmetic
open Fermat.OneThousandEightHundredThirtyOne.CircularUnitCyclic
open Fermat.OneThousandEightHundredThirtyOne.CircularUnitEntryCertificate
open Fermat.OneThousandEightHundredThirtyOne.CircularUnitMatrix
open Fermat.Irregular.CircularUnitFamily
open Fermat.Irregular.CircularUnitResidues
open Fermat.Irregular.CircularUnitResidues.Certificate

local instance : Fact (Nat.Prime 1831) :=
  ⟨Fermat.OneThousandEightHundredThirtyOne.prime_1831⟩
local instance : Fact (Nat.Prime 358877) :=
  ⟨Fermat.OneThousandEightHundredThirtyOne.prime_358877⟩

set_option maxHeartbeats 3000000
set_option maxRecDepth 1000000

/-- The canonical circular-unit column corresponding to the real class
of `4746^(j+1)`. -/
def cycleColumn1831 (j : Fin 914) : Fin 914 :=
  let s := ((teichmullerRoot1831 : ZMod 1831) ^ (j.val + 1)).val
  let a := min s (1831 - s)
  ⟨(a - 2) % 914, Nat.mod_lt _ (by norm_num)⟩

/-- The powers of `4746` visit every nontrivial real class exactly once. -/
theorem cycleColumn1831_bijective :
    Function.Bijective cycleColumn1831 := by decide

noncomputable def cycleColumnEquiv1831 : Fin 914 ≃ Fin 914 :=
  Equiv.ofBijective cycleColumn1831 cycleColumn1831_bijective

/-- The nontrivial even Fourier nodes `4746^(-2n)`, `1 ≤ n ≤ 914`. -/
def vandermondeNode1831 (i : Fin 914) : ZMod 1831 :=
  (teichmullerRoot1831 : ZMod 1831) ^ (1828 - 2 * i.val)

theorem vandermondeNode1831_injective :
    Function.Injective vandermondeNode1831 := by
  intro i j hij
  have hi : 1828 - 2 * i.val < 1830 := by omega
  have hj : 1828 - 2 * j.val < 1830 := by omega
  have hexp : 1828 - 2 * i.val = 1828 - 2 * j.val :=
    teichmullerRoot1831_isPrimitive.pow_inj hi hj hij
  apply Fin.ext
  omega

/-- Column scale converting powers `0, ..., 913` to Vandiver's edge
coefficients. -/
def fourierScale1831 (i : Fin 914) : ZMod 1831 :=
  ((teichmullerRoot1831 : ZMod 1831) ^ (2 * (i.val + 1)) - 1) *
    (teichmullerRoot1831 : ZMod 1831) * vandermondeNode1831 i

theorem fourierScale1831_ne_zero (i : Fin 914) :
    fourierScale1831 i ≠ 0 := by
  have hpos : 0 < 2 * (i.val + 1) := by omega
  have hlt : 2 * (i.val + 1) < 1830 := by omega
  have hpow :
      (teichmullerRoot1831 : ZMod 1831) ^ (2 * (i.val + 1)) ≠ 1 :=
    teichmullerRoot1831_isPrimitive.pow_ne_one_of_pos_of_lt
      hpos.ne' hlt
  exact mul_ne_zero
    (mul_ne_zero (sub_ne_zero.mpr hpow)
      (teichmullerRoot1831_isPrimitive.ne_zero (by norm_num)))
    (pow_ne_zero _
      (teichmullerRoot1831_isPrimitive.ne_zero (by norm_num)))

/-- The edge-to-diagonal change of basis. -/
def fourierChange1831 : Matrix (Fin 914) (Fin 914) (ZMod 1831) :=
  (Matrix.vandermonde vandermondeNode1831).transpose *
    Matrix.diagonal fourierScale1831

theorem fourierChange1831_apply (row i : Fin 914) :
    fourierChange1831 row i =
      vandermondeNode1831 i ^ row.val * fourierScale1831 i := by
  rw [fourierChange1831, Matrix.mul_diagonal]
  rfl

/-- The scaled Fourier matrix is nonsingular. -/
theorem fourierChange1831_det_ne_zero :
    fourierChange1831.det ≠ 0 := by
  rw [fourierChange1831, Matrix.det_mul, Matrix.det_transpose,
    Matrix.det_diagonal]
  exact mul_ne_zero
    (Matrix.det_vandermonde_ne_zero_iff.mpr
      vandermondeNode1831_injective)
    (Finset.prod_ne_zero_iff.mpr
      (fun i _ ↦ fourierScale1831_ne_zero i))

abbrev certificate1831 : Certificate 1831 358877 :=
  Fermat.OneThousandEightHundredThirtyOne.CircularUnitResidues.certificate

/-- Extend the circular-unit cycle by the trivial class at positions zero
and 915. -/
def cycleClassSymbol1831 (row : Fin 914) (ell : ℕ) : ZMod 1831 :=
  if h : 1 ≤ ell ∧ ell ≤ 914 then
    Fermat.OneThousandEightHundredThirtyOne.CircularUnitMatrix.matrix row
      (cycleColumn1831 ⟨ell - 1, by omega⟩)
  else 0

/-- The symbol of the `j`th basic factor is the difference of adjacent
circular-unit symbols. -/
def basicEdgeSymbol1831 (row : Fin 914) (j : Fin 915) : ZMod 1831 :=
  cycleClassSymbol1831 row (j.val + 1) -
    cycleClassSymbol1831 row j.val

/-- Literal source exponent `4746^j`. -/
def conjugateExponent1831 (j : Fin 915) : ℕ :=
  teichmullerRoot1831 ^ j.val

/-- Its small reduction modulo `1831`. -/
def reducedConjugateExponent1831 (j : Fin 915) : ℕ :=
  ((teichmullerRoot1831 : ZMod 1831) ^ j.val).val

theorem conjugateExponent1831_modEq_reduced (j : Fin 915) :
    conjugateExponent1831 j ≡ reducedConjugateExponent1831 j [MOD 1831] := by
  rw [← ZMod.natCast_eq_natCast_iff]
  simp [conjugateExponent1831, reducedConjugateExponent1831]

theorem pow_conjugateExponent1831_eq_reduced {G : Type*} [Monoid G]
    (x : G) (hx : x ^ 1831 = 1) (j : Fin 915) :
    x ^ conjugateExponent1831 j = x ^ reducedConjugateExponent1831 j :=
  pow_eq_pow_of_modEq (conjugateExponent1831_modEq_reduced j) hx

/-- The literal 4746-term geometric sum in the finite-field reduction. -/
def basicResidueGeomSum1831 (row : Fin 914) (j : Fin 915) : ZMod 358877 :=
  let w := embeddingRoot (p := 1831) certificate1831.root row ^
    conjugateExponent1831 j
  ∑ k ∈ Finset.range 4746, w ^ k

/-- Reduction of the normalized basic factor. -/
def basicResidueValue1831 (row : Fin 914) (j : Fin 915) : ZMod 358877 :=
  let w := embeddingRoot (p := 1831) certificate1831.root row ^
    conjugateExponent1831 j
  w ^ 374 * basicResidueGeomSum1831 row j

/-- The chosen Teichmüller representative is already the small reduction
`4746`, so the literal source sum needs no period removal. -/
theorem basicResidueGeomSum1831_eq (row : Fin 914) (j : Fin 915) :
    basicResidueGeomSum1831 row j =
      ∑ k ∈ Finset.range 4746,
        (embeddingRoot (p := 1831) certificate1831.root row ^
          conjugateExponent1831 j) ^ k := by
  rfl

/-! ## Compact cyclic provenance

The real residue group is cyclic of order 915. Thus the edge-symbol and
normalized-value identities factor through two one-variable certificates
and an algebraic phase argument. -/

/-- In the real cyclic quotient generated by `3`, multiplication by `4746`
is translation by `772`; equivalently, `3^772 = -4746 (mod 1831)`. -/
theorem cycleColumn1831_coord (ell : Fin 914) :
    coord (columnPermutation (cycleColumn1831 ell)) =
      ((772 * (ell.val + 1) : ℕ) : Cyc) := by
  decide +revert

/-- The stored column is the canonical representative of
`4746^(ell+1)` up to the harmless real-class sign. -/
theorem cycleColumn1831_realRepresentative (ell : Fin 914) :
    let a := ((cycleColumn1831 ell).val + 2 : ZMod 1831)
    let d := (teichmullerRoot1831 : ZMod 1831) ^ (ell.val + 1)
    a = d ∨ a = -d := by
  decide +revert

/-- Cyclic coordinate of an original embedding row. -/
def rowCycleCoord1831 (row : Fin 914) : Cyc :=
  coord (rowPermutation row)

/-- Extend the literal conjugate powers through the wrap at exponent
`915`. -/
def extendedConjugateExponent1831 (ell : Fin 916) : ℕ :=
  teichmullerRoot1831 ^ ell.val

/-- Its cyclic real-residue coordinate. -/
def extendedCycleCoord1831 (ell : Fin 916) : Cyc :=
  ((772 * ell.val : ℕ) : Cyc)

private theorem weight_eq_of_eq_or_inv {x y : ZMod 358877}
    (hy : y ≠ 0) (h : x = y ∨ x = y⁻¹) :
    weight x = weight y := by
  rcases h with h | h
  · rw [h]
  · rw [h, weight_inv y hy]

private theorem pow_eq_inv_pow_of_cast_eq_neg
    {x : ZMod 358877} (hx : IsPrimitiveRoot x 1831)
    {a b : ℕ}
    (h : (a : ZMod 1831) = -(b : ZMod 1831)) :
    x ^ a = (x ^ b)⁻¹ := by
  have hab : a + b ≡ 0 [MOD 1831] := by
    rw [← ZMod.natCast_eq_natCast_iff]
    simpa only [Nat.cast_add, Nat.cast_zero, add_eq_zero_iff_eq_neg] using h
  have hp : x ^ (a + b) = 1 := by
    simpa using pow_eq_pow_of_modEq hab hx.pow_eq_one
  apply (mul_eq_one_iff_eq_inv₀
    (pow_ne_zero b (hx.ne_zero (by norm_num)))).mp
  rw [← pow_add]
  exact hp

private theorem pow_eq_or_inv_pow_of_cast_eq_or_neg
    {x : ZMod 358877} (hx : IsPrimitiveRoot x 1831)
    {a b : ℕ}
    (h : (a : ZMod 1831) = b ∨
      (a : ZMod 1831) = -(b : ZMod 1831)) :
    x ^ a = x ^ b ∨ x ^ a = (x ^ b)⁻¹ := by
  rcases h with h | h
  · left
    apply pow_eq_pow_of_modEq _ hx.pow_eq_one
    rw [← ZMod.natCast_eq_natCast_iff]
    exact h
  · exact Or.inr (pow_eq_inv_pow_of_cast_eq_neg hx h)

/-- The weight of every conjugated root is its cyclic phase weight. This
is parametric in the row; only the two column-orientation facts above are
checked finitely. -/
theorem extendedConjugateWeight1831 (row : Fin 914) (ell : Fin 916) :
    let x := embeddingRoot (p := 1831) (266093 : ZMod 358877) row
    weight (x ^ extendedConjugateExponent1831 ell) =
      weight
        (classRoot (rowCycleCoord1831 row + extendedCycleCoord1831 ell)) := by
  let x := embeddingRoot (p := 1831) (266093 : ZMod 358877) row
  change
    weight (x ^ extendedConjugateExponent1831 ell) =
      weight
        (classRoot (rowCycleCoord1831 row + extendedCycleCoord1831 ell))
  have hxprim : IsPrimitiveRoot x 1831 :=
    embeddingRoot_isPrimitive (p := 1831) (q := 358877) (by norm_num)
      root_isPrimitive row
  have hx0 : x ≠ 0 := hxprim.ne_zero (by norm_num)
  by_cases hzero : ell.val = 0
  · have hell : ell = ⟨0, by norm_num⟩ := Fin.ext hzero
    subst ell
    have hrow :
        classRoot (rowCycleCoord1831 row) = x ∨
          classRoot (rowCycleCoord1831 row) = x⁻¹ := by
      simpa [x, rowCycleCoord1831] using row_root_relation row
    have hw := weight_eq_of_eq_or_inv hx0 hrow
    simpa [x, rowCycleCoord1831, extendedConjugateExponent1831,
      extendedCycleCoord1831] using hw.symm
  by_cases hlast : ell.val = 915
  · have hell : ell = ⟨915, by norm_num⟩ := Fin.ext hlast
    subst ell
    have hpowLast :
        x ^ extendedConjugateExponent1831 ⟨915, by norm_num⟩ = x⁻¹ := by
      have hcast :
          (extendedConjugateExponent1831 ⟨915, by norm_num⟩ : ZMod 1831) =
            -(1 : ZMod 1831) := by
        decide +kernel
      simpa only [pow_one] using
        pow_eq_inv_pow_of_cast_eq_neg hxprim hcast
    have hrow :
        classRoot (rowCycleCoord1831 row) = x ∨
          classRoot (rowCycleCoord1831 row) = x⁻¹ := by
      simpa [x, rowCycleCoord1831] using row_root_relation row
    have hw := weight_eq_of_eq_or_inv hx0 hrow
    have hcoordlast :
        extendedCycleCoord1831 ⟨915, by norm_num⟩ = 0 := by
      decide
    calc
      weight
          (x ^ extendedConjugateExponent1831 ⟨915, by norm_num⟩) =
          weight x⁻¹ := congrArg weight hpowLast
      _ = weight x := weight_inv x hx0
      _ = weight
          (classRoot
            (rowCycleCoord1831 row +
              extendedCycleCoord1831 ⟨915, by norm_num⟩)) := by
        rw [hcoordlast, add_zero]
        exact hw.symm
  · have hpos : 1 ≤ ell.val := by omega
    have hle : ell.val ≤ 914 := by omega
    let k : Fin 914 := ⟨ell.val - 1, by omega⟩
    have hk : k.val + 1 = ell.val := by simp [k]; omega
    let a := (cycleColumn1831 k).val + 2
    have hrep := cycleColumn1831_realRepresentative k
    have hcast :
        (a : ZMod 1831) =
            (extendedConjugateExponent1831 ell : ZMod 1831) ∨
          (a : ZMod 1831) =
            -(extendedConjugateExponent1831 ell : ZMod 1831) := by
      simpa [a, extendedConjugateExponent1831, hk] using hrep
    have hpow := pow_eq_or_inv_pow_of_cast_eq_or_neg hxprim hcast
    have hpowWeight :
        weight (x ^ a) =
          weight (x ^ extendedConjugateExponent1831 ell) :=
      weight_eq_of_eq_or_inv
        (pow_ne_zero (extendedConjugateExponent1831 ell) hx0) hpow
    have hprod :
        classRoot
            (rowCycleCoord1831 row +
              coord (columnPermutation (cycleColumn1831 k))) =
            x ^ a ∨
          classRoot
            (rowCycleCoord1831 row +
              coord (columnPermutation (cycleColumn1831 k))) =
            (x ^ a)⁻¹ := by
      simpa [x, a, rowCycleCoord1831] using
        product_root_relation row (cycleColumn1831 k)
    have hprodWeight :
        weight
            (classRoot
              (rowCycleCoord1831 row +
                coord (columnPermutation (cycleColumn1831 k)))) =
          weight (x ^ a) := by
      exact weight_eq_of_eq_or_inv (pow_ne_zero a hx0) hprod
    rw [cycleColumn1831_coord k] at hprodWeight
    have hcoord :
        ((772 * (k.val + 1) : ℕ) : Cyc) =
          extendedCycleCoord1831 ell := by
      simp only [extendedCycleCoord1831, hk]
    rw [hcoord] at hprodWeight
    exact (hprodWeight.trans hpowWeight).symm

private theorem normalizedGeom_pow_eq_weight_ratio
    (w : ZMod 358877) (hw : IsPrimitiveRoot w 1831) (a e : ℕ)
    (hexp : 196 * e + 98 * a ≡ 98 [MOD 1831]) :
    (w ^ e * ∑ k ∈ Finset.range a, w ^ k) ^ 196 =
      weight (w ^ a) / weight w := by
  have hw0 : w ≠ 0 := hw.ne_zero (by norm_num)
  have hw1 : 1 - w ≠ 0 :=
    sub_ne_zero.mpr (Ne.symm (hw.ne_one (by norm_num)))
  have hgeom :
      ∑ k ∈ Finset.range a, w ^ k = (1 - w ^ a) / (1 - w) := by
    apply (eq_div_iff hw1).2
    calc
      (∑ k ∈ Finset.range a, w ^ k) * (1 - w) =
          -((w - 1) * ∑ k ∈ Finset.range a, w ^ k) := by ring
      _ = -(w ^ a - 1) := by rw [mul_geom_sum]
      _ = 1 - w ^ a := by ring
  rw [hgeom, ← mul_div_assoc]
  change (w ^ e * (1 - w ^ a) / (1 - w)) ^ 196 =
    weight (w ^ a) / weight w
  have hpow : w ^ (196 * e + 98 * a) = w ^ 98 :=
    pow_eq_pow_of_modEq hexp hw.pow_eq_one
  simp only [weight, mul_pow, div_pow]
  field_simp [hw0, hw1]
  have hpow' : w ^ (e * 196) * w ^ (a * 98) = w ^ 98 := by
    rw [← pow_add]
    simpa [Nat.mul_comm] using hpow
  calc
    _ = (w ^ (e * 196) * w ^ (a * 98)) * (1 - w ^ a) ^ 196 := by ring
    _ = w ^ 98 * (1 - w ^ a) ^ 196 := by rw [hpow']
    _ = _ := by ring

theorem normalizedLength4746_pow_eq_weight_ratio
    (w : ZMod 358877) (hw : IsPrimitiveRoot w 1831) :
    (w ^ 374 * ∑ k ∈ Finset.range 4746, w ^ k) ^ 196 =
      weight (w ^ 4746) / weight w :=
  normalizedGeom_pow_eq_weight_ratio w hw 4746 374 (by norm_num)

/-- The extended cycle symbols are ordinary differences of the compressed
phase vector. -/
theorem cycleClassSymbol1831_succ_phase (row ell : Fin 914) :
    cycleClassSymbol1831 row (ell.val + 1) =
      symbolPhase
          (rowCycleCoord1831 row +
            ((772 * (ell.val + 1) : ℕ) : Cyc)) -
        symbolPhase (rowCycleCoord1831 row) := by
  rw [cycleClassSymbol1831, dif_pos]
  · change
      symbolPhase
            (coord (rowPermutation row) +
              coord (columnPermutation (cycleColumn1831 ell))) -
          symbolPhase (coord (rowPermutation row)) =
        _
    rw [cycleColumn1831_coord]
    rfl
  · omega

theorem cycleClassSymbol1831_phase (row : Fin 914) (ell : ℕ)
    (hell : ell ≤ 915) :
    cycleClassSymbol1831 row ell =
      symbolPhase
          (rowCycleCoord1831 row + ((772 * ell : ℕ) : Cyc)) -
        symbolPhase (rowCycleCoord1831 row) := by
  by_cases hzero : ell = 0
  · subst ell
    simp [cycleClassSymbol1831]
  by_cases hlast : ell = 915
  · subst ell
    have hcoord : (((772 * 915 : ℕ) : Cyc)) = 0 := by decide
    rw [cycleClassSymbol1831, dif_neg (by omega), hcoord, add_zero, sub_self]
  · have hpos : 1 ≤ ell := by omega
    have hle : ell ≤ 914 := by omega
    let k : Fin 914 := ⟨ell - 1, by omega⟩
    have hk : k.val + 1 = ell := by simp [k]; omega
    simpa only [hk] using cycleClassSymbol1831_succ_phase row k

theorem basicEdgeSymbol1831_phase (row : Fin 914) (j : Fin 915) :
    basicEdgeSymbol1831 row j =
      symbolPhase
          ((rowCycleCoord1831 row +
              extendedCycleCoord1831 j.castSucc) + 772) -
        symbolPhase
          (rowCycleCoord1831 row +
            extendedCycleCoord1831 j.castSucc) := by
  rw [basicEdgeSymbol1831,
    cycleClassSymbol1831_phase row (j.val + 1) (by omega),
    cycleClassSymbol1831_phase row j.val (by omega)]
  simp only [extendedCycleCoord1831, Fin.val_castSucc]
  have hstep :
      rowCycleCoord1831 row + ((772 * (j.val + 1) : ℕ) : Cyc) =
        (rowCycleCoord1831 row + ((772 * j.val : ℕ) : Cyc)) + 772 := by
    push_cast
    ring
  rw [hstep]
  ring

theorem extendedConjugateStep1831
    (x : ZMod 358877) (hx : IsPrimitiveRoot x 1831) (j : Fin 915) :
    (x ^ extendedConjugateExponent1831 j.castSucc) ^ 4746 =
      x ^ extendedConjugateExponent1831 j.succ := by
  rw [← pow_mul]
  apply pow_eq_pow_of_modEq _ hx.pow_eq_one
  change
    teichmullerRoot1831 ^ j.val * 4746 ≡
      teichmullerRoot1831 ^ (j.val + 1) [MOD 1831]
  rw [pow_succ]
  exact (by norm_num [teichmullerRoot1831] :
    4746 ≡ teichmullerRoot1831 [MOD 1831]).mul_left _

private def reducedBasicResidueValue1831
    (row : Fin 914) (j : Fin 915) : ZMod 358877 :=
  let x := embeddingRoot (p := 1831) (266093 : ZMod 358877) row
  let w := x ^ extendedConjugateExponent1831 j.castSucc
  w ^ 374 * ∑ k ∈ Finset.range 4746, w ^ k

private theorem reducedBasicResidueValue1831_symbol
    (row : Fin 914) (j : Fin 915) :
    reducedBasicResidueValue1831 row j ^ 196 =
      (266093 : ZMod 358877) ^ (basicEdgeSymbol1831 row j).val := by
  let x := embeddingRoot (p := 1831) (266093 : ZMod 358877) row
  let w := x ^ extendedConjugateExponent1831 j.castSucc
  have hxprim : IsPrimitiveRoot x 1831 :=
    embeddingRoot_isPrimitive (p := 1831) (q := 358877) (by norm_num)
      root_isPrimitive row
  have hwprim : IsPrimitiveRoot w 1831 := by
    apply hxprim.pow_of_coprime
    exact (by norm_num : Nat.Coprime 4746 1831).pow_left j.val
  change (w ^ 374 * ∑ k ∈ Finset.range 4746, w ^ k) ^ 196 = _
  rw [normalizedLength4746_pow_eq_weight_ratio w hwprim]
  have hcur :
      weight w =
        weight
          (classRoot
            (rowCycleCoord1831 row +
              extendedCycleCoord1831 j.castSucc)) := by
    simpa [x, w] using extendedConjugateWeight1831 row j.castSucc
  have hnext :
      weight (x ^ extendedConjugateExponent1831 j.succ) =
        weight
          (classRoot
            (rowCycleCoord1831 row +
              extendedCycleCoord1831 j.succ)) := by
    simpa [x] using extendedConjugateWeight1831 row j.succ
  have hstep := extendedConjugateStep1831 x hxprim j
  rw [hstep, hnext, hcur]
  have hcoord :
      rowCycleCoord1831 row + extendedCycleCoord1831 j.succ =
        (rowCycleCoord1831 row +
          extendedCycleCoord1831 j.castSucc) + 772 := by
    simp only [extendedCycleCoord1831, Fin.val_succ, Fin.val_castSucc]
    push_cast
    ring
  rw [hcoord, weight_ratio_eq_phase_ratio,
    phase_value_certificate, phase_value_certificate,
    ← root_pow_sub_val]
  rw [basicEdgeSymbol1831_phase]

/-- Complete provenance of every basic-factor residue symbol, derived from
the one-variable cyclic certificates rather than a Cartesian case split. -/
theorem basicResidueValue1831_symbol (row : Fin 914) (j : Fin 915) :
    basicResidueValue1831 row j ^ 196 =
      certificate1831.root ^ (basicEdgeSymbol1831 row j).val := by
  rw [basicResidueValue1831, basicResidueGeomSum1831_eq]
  simpa [reducedBasicResidueValue1831, extendedConjugateExponent1831,
    conjugateExponent1831, certificate1831,
    Fermat.OneThousandEightHundredThirtyOne.CircularUnitResidues.certificate] using
    reducedBasicResidueValue1831_symbol row j

end Fermat.OneThousandEightHundredThirtyOne.VandiverDiagonalUnitResidues
