import Fermat.OneThousandThreeHundredEightyOne.CircularUnitResidues
import Fermat.OneThousandThreeHundredEightyOne.VandiverDiagonalArithmetic1381
import Mathlib.LinearAlgebra.Vandermonde

/-!
# Residue and Fourier certificates for Vandiver's diagonal units at 1381

This module derives the residue matrix of Vandiver's 689 diagonal units
from the already certified circular-unit matrix at `q = 38669`.

The 690 basic factors form the edges of the cyclic ordering generated by
`653` modulo sign. Their positive integral weights are the nontrivial even
characters of that cycle. Consequently the change of basis is a scaled
transpose Vandermonde matrix. This avoids both a `689 × 690` Cartesian
certificate and a second explicit dense inverse.
-/

namespace Fermat.OneThousandThreeHundredEightyOne.VandiverDiagonalUnitResidues

open Fermat.OneThousandThreeHundredEightyOne.VandiverDiagonalArithmetic
open Fermat.OneThousandThreeHundredEightyOne.CircularUnitCyclic
open Fermat.OneThousandThreeHundredEightyOne.CircularUnitEntryCertificate
open Fermat.OneThousandThreeHundredEightyOne.CircularUnitMatrix
open Fermat.Irregular.CircularUnitFamily
open Fermat.Irregular.CircularUnitResidues
open Fermat.Irregular.CircularUnitResidues.Certificate

local instance : Fact (Nat.Prime 1381) :=
  ⟨Fermat.OneThousandThreeHundredEightyOne.prime_1381⟩
local instance : Fact (Nat.Prime 38669) :=
  ⟨Fermat.OneThousandThreeHundredEightyOne.prime_38669⟩

set_option maxHeartbeats 3000000
set_option maxRecDepth 1000000

/-- The canonical circular-unit column corresponding to the real class
of `653^(j+1)`. -/
def cycleColumn1381 (j : Fin 689) : Fin 689 :=
  let s := ((teichmullerRoot1381 : ZMod 1381) ^ (j.val + 1)).val
  let a := min s (1381 - s)
  ⟨(a - 2) % 689, Nat.mod_lt _ (by norm_num)⟩

/-- The powers of `653` visit every nontrivial real class exactly once. -/
theorem cycleColumn1381_bijective :
    Function.Bijective cycleColumn1381 := by decide

noncomputable def cycleColumnEquiv1381 : Fin 689 ≃ Fin 689 :=
  Equiv.ofBijective cycleColumn1381 cycleColumn1381_bijective

/-- The nontrivial even Fourier nodes `653^(-2n)`, `1 ≤ n ≤ 689`. -/
def vandermondeNode1381 (i : Fin 689) : ZMod 1381 :=
  (teichmullerRoot1381 : ZMod 1381) ^ (1378 - 2 * i.val)

theorem vandermondeNode1381_injective :
    Function.Injective vandermondeNode1381 := by
  intro i j hij
  have hi : 1378 - 2 * i.val < 1380 := by omega
  have hj : 1378 - 2 * j.val < 1380 := by omega
  have hexp : 1378 - 2 * i.val = 1378 - 2 * j.val :=
    teichmullerRoot1381_isPrimitive.pow_inj hi hj hij
  apply Fin.ext
  omega

/-- Column scale converting powers `0, ..., 688` to Vandiver's edge
coefficients. -/
def fourierScale1381 (i : Fin 689) : ZMod 1381 :=
  ((teichmullerRoot1381 : ZMod 1381) ^ (2 * (i.val + 1)) - 1) *
    (teichmullerRoot1381 : ZMod 1381) * vandermondeNode1381 i

theorem fourierScale1381_ne_zero (i : Fin 689) :
    fourierScale1381 i ≠ 0 := by
  have hpos : 0 < 2 * (i.val + 1) := by omega
  have hlt : 2 * (i.val + 1) < 1380 := by omega
  have hpow :
      (teichmullerRoot1381 : ZMod 1381) ^ (2 * (i.val + 1)) ≠ 1 :=
    teichmullerRoot1381_isPrimitive.pow_ne_one_of_pos_of_lt
      hpos.ne' hlt
  exact mul_ne_zero
    (mul_ne_zero (sub_ne_zero.mpr hpow)
      (teichmullerRoot1381_isPrimitive.ne_zero (by norm_num)))
    (pow_ne_zero _
      (teichmullerRoot1381_isPrimitive.ne_zero (by norm_num)))

/-- The edge-to-diagonal change of basis. -/
def fourierChange1381 : Matrix (Fin 689) (Fin 689) (ZMod 1381) :=
  (Matrix.vandermonde vandermondeNode1381).transpose *
    Matrix.diagonal fourierScale1381

theorem fourierChange1381_apply (row i : Fin 689) :
    fourierChange1381 row i =
      vandermondeNode1381 i ^ row.val * fourierScale1381 i := by
  rw [fourierChange1381, Matrix.mul_diagonal]
  rfl

/-- The scaled Fourier matrix is nonsingular. -/
theorem fourierChange1381_det_ne_zero :
    fourierChange1381.det ≠ 0 := by
  rw [fourierChange1381, Matrix.det_mul, Matrix.det_transpose,
    Matrix.det_diagonal]
  exact mul_ne_zero
    (Matrix.det_vandermonde_ne_zero_iff.mpr
      vandermondeNode1381_injective)
    (Finset.prod_ne_zero_iff.mpr
      (fun i _ ↦ fourierScale1381_ne_zero i))

abbrev certificate1381 : Certificate 1381 38669 :=
  Fermat.OneThousandThreeHundredEightyOne.CircularUnitResidues.certificate

/-- Extend the circular-unit cycle by the trivial class at positions zero
and 690. -/
def cycleClassSymbol1381 (row : Fin 689) (ell : ℕ) : ZMod 1381 :=
  if h : 1 ≤ ell ∧ ell ≤ 689 then
    Fermat.OneThousandThreeHundredEightyOne.CircularUnitMatrix.matrix row
      (cycleColumn1381 ⟨ell - 1, by omega⟩)
  else 0

/-- The symbol of the `j`th basic factor is the difference of adjacent
circular-unit symbols. -/
def basicEdgeSymbol1381 (row : Fin 689) (j : Fin 690) : ZMod 1381 :=
  cycleClassSymbol1381 row (j.val + 1) -
    cycleClassSymbol1381 row j.val

/-- Literal source exponent `653^j`. -/
def conjugateExponent1381 (j : Fin 690) : ℕ :=
  teichmullerRoot1381 ^ j.val

/-- Its small reduction modulo `1381`. -/
def reducedConjugateExponent1381 (j : Fin 690) : ℕ :=
  ((teichmullerRoot1381 : ZMod 1381) ^ j.val).val

theorem conjugateExponent1381_modEq_reduced (j : Fin 690) :
    conjugateExponent1381 j ≡ reducedConjugateExponent1381 j [MOD 1381] := by
  rw [← ZMod.natCast_eq_natCast_iff]
  simp [conjugateExponent1381, reducedConjugateExponent1381]

theorem pow_conjugateExponent1381_eq_reduced {G : Type*} [Monoid G]
    (x : G) (hx : x ^ 1381 = 1) (j : Fin 690) :
    x ^ conjugateExponent1381 j = x ^ reducedConjugateExponent1381 j :=
  pow_eq_pow_of_modEq (conjugateExponent1381_modEq_reduced j) hx

/-- The literal 653-term geometric sum in the finite-field reduction. -/
def basicResidueGeomSum1381 (row : Fin 689) (j : Fin 690) : ZMod 38669 :=
  let w := embeddingRoot (p := 1381) certificate1381.root row ^
    conjugateExponent1381 j
  ∑ k ∈ Finset.range 653, w ^ k

/-- Reduction of the normalized basic factor. -/
def basicResidueValue1381 (row : Fin 689) (j : Fin 690) : ZMod 38669 :=
  let w := embeddingRoot (p := 1381) certificate1381.root row ^
    conjugateExponent1381 j
  w ^ 1055 * basicResidueGeomSum1381 row j

/-- The chosen Teichmüller representative is already the small reduction
`653`, so the literal source sum needs no period removal. -/
theorem basicResidueGeomSum1381_eq (row : Fin 689) (j : Fin 690) :
    basicResidueGeomSum1381 row j =
      ∑ k ∈ Finset.range 653,
        (embeddingRoot (p := 1381) certificate1381.root row ^
          conjugateExponent1381 j) ^ k := by
  rfl

/-! ## Compact cyclic provenance

The real residue group is cyclic of order 690. Thus the edge-symbol and
normalized-value identities factor through two one-variable certificates
and an algebraic phase argument. -/

/-- In the real cyclic quotient generated by `2`, multiplication by `653`
is translation by `137`; equivalently, `2^137 = 653 (mod 1381)`. -/
theorem cycleColumn1381_coord (ell : Fin 689) :
    coord (columnPermutation (cycleColumn1381 ell)) =
      ((137 * (ell.val + 1) : ℕ) : Cyc) := by
  decide +revert

/-- The stored column is the canonical representative of
`653^(ell+1)` up to the harmless real-class sign. -/
theorem cycleColumn1381_realRepresentative (ell : Fin 689) :
    let a := ((cycleColumn1381 ell).val + 2 : ZMod 1381)
    let d := (teichmullerRoot1381 : ZMod 1381) ^ (ell.val + 1)
    a = d ∨ a = -d := by
  decide +revert

/-- Cyclic coordinate of an original embedding row. -/
def rowCycleCoord1381 (row : Fin 689) : Cyc :=
  coord (rowPermutation row)

/-- Extend the literal conjugate powers through the wrap at exponent
`690`. -/
def extendedConjugateExponent1381 (ell : Fin 691) : ℕ :=
  teichmullerRoot1381 ^ ell.val

/-- Its cyclic real-residue coordinate. -/
def extendedCycleCoord1381 (ell : Fin 691) : Cyc :=
  ((137 * ell.val : ℕ) : Cyc)

private theorem weight_eq_of_eq_or_inv {x y : ZMod 38669}
    (hy : y ≠ 0) (h : x = y ∨ x = y⁻¹) :
    weight x = weight y := by
  rcases h with h | h
  · rw [h]
  · rw [h, weight_inv y hy]

private theorem pow_eq_inv_pow_of_cast_eq_neg
    {x : ZMod 38669} (hx : IsPrimitiveRoot x 1381)
    {a b : ℕ}
    (h : (a : ZMod 1381) = -(b : ZMod 1381)) :
    x ^ a = (x ^ b)⁻¹ := by
  have hab : a + b ≡ 0 [MOD 1381] := by
    rw [← ZMod.natCast_eq_natCast_iff]
    simpa only [Nat.cast_add, Nat.cast_zero, add_eq_zero_iff_eq_neg] using h
  have hp : x ^ (a + b) = 1 := by
    simpa using pow_eq_pow_of_modEq hab hx.pow_eq_one
  apply (mul_eq_one_iff_eq_inv₀
    (pow_ne_zero b (hx.ne_zero (by norm_num)))).mp
  rw [← pow_add]
  exact hp

private theorem pow_eq_or_inv_pow_of_cast_eq_or_neg
    {x : ZMod 38669} (hx : IsPrimitiveRoot x 1381)
    {a b : ℕ}
    (h : (a : ZMod 1381) = b ∨
      (a : ZMod 1381) = -(b : ZMod 1381)) :
    x ^ a = x ^ b ∨ x ^ a = (x ^ b)⁻¹ := by
  rcases h with h | h
  · left
    apply pow_eq_pow_of_modEq _ hx.pow_eq_one
    rw [← ZMod.natCast_eq_natCast_iff]
    exact h
  · exact Or.inr (pow_eq_inv_pow_of_cast_eq_neg hx h)

/-- The weight of every conjugated root is its cyclic phase weight. This
is parametric in the row; only the two column-orientation facts above are
checked finitely. -/
theorem extendedConjugateWeight1381 (row : Fin 689) (ell : Fin 691) :
    let x := embeddingRoot (p := 1381) (33927 : ZMod 38669) row
    weight (x ^ extendedConjugateExponent1381 ell) =
      weight
        (classRoot (rowCycleCoord1381 row + extendedCycleCoord1381 ell)) := by
  let x := embeddingRoot (p := 1381) (33927 : ZMod 38669) row
  change
    weight (x ^ extendedConjugateExponent1381 ell) =
      weight
        (classRoot (rowCycleCoord1381 row + extendedCycleCoord1381 ell))
  have hxprim : IsPrimitiveRoot x 1381 :=
    embeddingRoot_isPrimitive (p := 1381) (q := 38669) (by norm_num)
      root_isPrimitive row
  have hx0 : x ≠ 0 := hxprim.ne_zero (by norm_num)
  by_cases hzero : ell.val = 0
  · have hell : ell = ⟨0, by norm_num⟩ := Fin.ext hzero
    subst ell
    have hrow :
        classRoot (rowCycleCoord1381 row) = x ∨
          classRoot (rowCycleCoord1381 row) = x⁻¹ := by
      simpa [x, rowCycleCoord1381] using row_root_relation row
    have hw := weight_eq_of_eq_or_inv hx0 hrow
    simpa [x, rowCycleCoord1381, extendedConjugateExponent1381,
      extendedCycleCoord1381] using hw.symm
  by_cases hlast : ell.val = 690
  · have hell : ell = ⟨690, by norm_num⟩ := Fin.ext hlast
    subst ell
    have hpowLast :
        x ^ extendedConjugateExponent1381 ⟨690, by norm_num⟩ = x⁻¹ := by
      have hcast :
          (extendedConjugateExponent1381 ⟨690, by norm_num⟩ : ZMod 1381) =
            -(1 : ZMod 1381) := by
        decide +kernel
      simpa only [pow_one] using
        pow_eq_inv_pow_of_cast_eq_neg hxprim hcast
    have hrow :
        classRoot (rowCycleCoord1381 row) = x ∨
          classRoot (rowCycleCoord1381 row) = x⁻¹ := by
      simpa [x, rowCycleCoord1381] using row_root_relation row
    have hw := weight_eq_of_eq_or_inv hx0 hrow
    have hcoordlast :
        extendedCycleCoord1381 ⟨690, by norm_num⟩ = 0 := by
      decide
    calc
      weight
          (x ^ extendedConjugateExponent1381 ⟨690, by norm_num⟩) =
          weight x⁻¹ := congrArg weight hpowLast
      _ = weight x := weight_inv x hx0
      _ = weight
          (classRoot
            (rowCycleCoord1381 row +
              extendedCycleCoord1381 ⟨690, by norm_num⟩)) := by
        rw [hcoordlast, add_zero]
        exact hw.symm
  · have hpos : 1 ≤ ell.val := by omega
    have hle : ell.val ≤ 689 := by omega
    let k : Fin 689 := ⟨ell.val - 1, by omega⟩
    have hk : k.val + 1 = ell.val := by simp [k]; omega
    let a := (cycleColumn1381 k).val + 2
    have hrep := cycleColumn1381_realRepresentative k
    have hcast :
        (a : ZMod 1381) =
            (extendedConjugateExponent1381 ell : ZMod 1381) ∨
          (a : ZMod 1381) =
            -(extendedConjugateExponent1381 ell : ZMod 1381) := by
      simpa [a, extendedConjugateExponent1381, hk] using hrep
    have hpow := pow_eq_or_inv_pow_of_cast_eq_or_neg hxprim hcast
    have hpowWeight :
        weight (x ^ a) =
          weight (x ^ extendedConjugateExponent1381 ell) :=
      weight_eq_of_eq_or_inv
        (pow_ne_zero (extendedConjugateExponent1381 ell) hx0) hpow
    have hprod :
        classRoot
            (rowCycleCoord1381 row +
              coord (columnPermutation (cycleColumn1381 k))) =
            x ^ a ∨
          classRoot
            (rowCycleCoord1381 row +
              coord (columnPermutation (cycleColumn1381 k))) =
            (x ^ a)⁻¹ := by
      simpa [x, a, rowCycleCoord1381] using
        product_root_relation row (cycleColumn1381 k)
    have hprodWeight :
        weight
            (classRoot
              (rowCycleCoord1381 row +
                coord (columnPermutation (cycleColumn1381 k)))) =
          weight (x ^ a) := by
      exact weight_eq_of_eq_or_inv (pow_ne_zero a hx0) hprod
    rw [cycleColumn1381_coord k] at hprodWeight
    have hcoord :
        ((137 * (k.val + 1) : ℕ) : Cyc) =
          extendedCycleCoord1381 ell := by
      simp only [extendedCycleCoord1381, hk]
    rw [hcoord] at hprodWeight
    exact (hprodWeight.trans hpowWeight).symm

private theorem normalizedGeom_pow_eq_weight_ratio
    (w : ZMod 38669) (hw : IsPrimitiveRoot w 1381) (a e : ℕ)
    (hexp : 28 * e + 14 * a ≡ 14 [MOD 1381]) :
    (w ^ e * ∑ k ∈ Finset.range a, w ^ k) ^ 28 =
      weight (w ^ a) / weight w := by
  have hw0 : w ≠ 0 := hw.ne_zero (by norm_num)
  have hw1 : 1 - w ≠ 0 :=
    sub_ne_zero.mpr (Ne.symm (hw.ne_one (by norm_num)))
  have hgeom :
      ∑ k ∈ Finset.range a, w ^ k = (1 - w ^ a) / (1 - w) := by
    apply (eq_div_iff hw1).2
    calc
      (∑ k ∈ Finset.range a, w ^ k) * (1 - w) =
          -((w - 1) * ∑ k ∈ Finset.range a, w ^ k) := by ring
      _ = -(w ^ a - 1) := by rw [mul_geom_sum]
      _ = 1 - w ^ a := by ring
  rw [hgeom, ← mul_div_assoc]
  change (w ^ e * (1 - w ^ a) / (1 - w)) ^ 28 =
    weight (w ^ a) / weight w
  have hpow : w ^ (28 * e + 14 * a) = w ^ 14 :=
    pow_eq_pow_of_modEq hexp hw.pow_eq_one
  simp only [weight, mul_pow, div_pow]
  field_simp [hw0, hw1]
  have hpow' : w ^ (e * 28) * w ^ (a * 14) = w ^ 14 := by
    rw [← pow_add]
    simpa [Nat.mul_comm] using hpow
  calc
    _ = (w ^ (e * 28) * w ^ (a * 14)) * (1 - w ^ a) ^ 28 := by ring
    _ = w ^ 14 * (1 - w ^ a) ^ 28 := by rw [hpow']
    _ = _ := by ring

theorem normalizedLength653_pow_eq_weight_ratio
    (w : ZMod 38669) (hw : IsPrimitiveRoot w 1381) :
    (w ^ 1055 * ∑ k ∈ Finset.range 653, w ^ k) ^ 28 =
      weight (w ^ 653) / weight w :=
  normalizedGeom_pow_eq_weight_ratio w hw 653 1055 (by norm_num)

/-- The extended cycle symbols are ordinary differences of the compressed
phase vector. -/
theorem cycleClassSymbol1381_succ_phase (row ell : Fin 689) :
    cycleClassSymbol1381 row (ell.val + 1) =
      symbolPhase
          (rowCycleCoord1381 row +
            ((137 * (ell.val + 1) : ℕ) : Cyc)) -
        symbolPhase (rowCycleCoord1381 row) := by
  rw [cycleClassSymbol1381, dif_pos]
  · change
      symbolPhase
            (coord (rowPermutation row) +
              coord (columnPermutation (cycleColumn1381 ell))) -
          symbolPhase (coord (rowPermutation row)) =
        _
    rw [cycleColumn1381_coord]
    rfl
  · omega

theorem cycleClassSymbol1381_phase (row : Fin 689) (ell : ℕ)
    (hell : ell ≤ 690) :
    cycleClassSymbol1381 row ell =
      symbolPhase
          (rowCycleCoord1381 row + ((137 * ell : ℕ) : Cyc)) -
        symbolPhase (rowCycleCoord1381 row) := by
  by_cases hzero : ell = 0
  · subst ell
    simp [cycleClassSymbol1381]
  by_cases hlast : ell = 690
  · subst ell
    have hcoord : (((137 * 690 : ℕ) : Cyc)) = 0 := by decide
    rw [cycleClassSymbol1381, dif_neg (by omega), hcoord, add_zero, sub_self]
  · have hpos : 1 ≤ ell := by omega
    have hle : ell ≤ 689 := by omega
    let k : Fin 689 := ⟨ell - 1, by omega⟩
    have hk : k.val + 1 = ell := by simp [k]; omega
    simpa only [hk] using cycleClassSymbol1381_succ_phase row k

theorem basicEdgeSymbol1381_phase (row : Fin 689) (j : Fin 690) :
    basicEdgeSymbol1381 row j =
      symbolPhase
          ((rowCycleCoord1381 row +
              extendedCycleCoord1381 j.castSucc) + 137) -
        symbolPhase
          (rowCycleCoord1381 row +
            extendedCycleCoord1381 j.castSucc) := by
  rw [basicEdgeSymbol1381,
    cycleClassSymbol1381_phase row (j.val + 1) (by omega),
    cycleClassSymbol1381_phase row j.val (by omega)]
  simp only [extendedCycleCoord1381, Fin.val_castSucc]
  have hstep :
      rowCycleCoord1381 row + ((137 * (j.val + 1) : ℕ) : Cyc) =
        (rowCycleCoord1381 row + ((137 * j.val : ℕ) : Cyc)) + 137 := by
    push_cast
    ring
  rw [hstep]
  ring

theorem extendedConjugateStep1381
    (x : ZMod 38669) (hx : IsPrimitiveRoot x 1381) (j : Fin 690) :
    (x ^ extendedConjugateExponent1381 j.castSucc) ^ 653 =
      x ^ extendedConjugateExponent1381 j.succ := by
  rw [← pow_mul]
  apply pow_eq_pow_of_modEq _ hx.pow_eq_one
  change
    teichmullerRoot1381 ^ j.val * 653 ≡
      teichmullerRoot1381 ^ (j.val + 1) [MOD 1381]
  rw [pow_succ]
  exact (by norm_num [teichmullerRoot1381] :
    653 ≡ teichmullerRoot1381 [MOD 1381]).mul_left _

private def reducedBasicResidueValue1381
    (row : Fin 689) (j : Fin 690) : ZMod 38669 :=
  let x := embeddingRoot (p := 1381) (33927 : ZMod 38669) row
  let w := x ^ extendedConjugateExponent1381 j.castSucc
  w ^ 1055 * ∑ k ∈ Finset.range 653, w ^ k

private theorem reducedBasicResidueValue1381_symbol
    (row : Fin 689) (j : Fin 690) :
    reducedBasicResidueValue1381 row j ^ 28 =
      (33927 : ZMod 38669) ^ (basicEdgeSymbol1381 row j).val := by
  let x := embeddingRoot (p := 1381) (33927 : ZMod 38669) row
  let w := x ^ extendedConjugateExponent1381 j.castSucc
  have hxprim : IsPrimitiveRoot x 1381 :=
    embeddingRoot_isPrimitive (p := 1381) (q := 38669) (by norm_num)
      root_isPrimitive row
  have hwprim : IsPrimitiveRoot w 1381 := by
    apply hxprim.pow_of_coprime
    exact (by norm_num : Nat.Coprime 653 1381).pow_left j.val
  change (w ^ 1055 * ∑ k ∈ Finset.range 653, w ^ k) ^ 28 = _
  rw [normalizedLength653_pow_eq_weight_ratio w hwprim]
  have hcur :
      weight w =
        weight
          (classRoot
            (rowCycleCoord1381 row +
              extendedCycleCoord1381 j.castSucc)) := by
    simpa [x, w] using extendedConjugateWeight1381 row j.castSucc
  have hnext :
      weight (x ^ extendedConjugateExponent1381 j.succ) =
        weight
          (classRoot
            (rowCycleCoord1381 row +
              extendedCycleCoord1381 j.succ)) := by
    simpa [x] using extendedConjugateWeight1381 row j.succ
  have hstep := extendedConjugateStep1381 x hxprim j
  rw [hstep, hnext, hcur]
  have hcoord :
      rowCycleCoord1381 row + extendedCycleCoord1381 j.succ =
        (rowCycleCoord1381 row +
          extendedCycleCoord1381 j.castSucc) + 137 := by
    simp only [extendedCycleCoord1381, Fin.val_succ, Fin.val_castSucc]
    push_cast
    ring
  rw [hcoord, weight_ratio_eq_phase_ratio,
    phase_value_certificate, phase_value_certificate,
    ← root_pow_sub_val]
  rw [basicEdgeSymbol1381_phase]

/-- Complete provenance of every basic-factor residue symbol, derived from
the one-variable cyclic certificates rather than a Cartesian case split. -/
theorem basicResidueValue1381_symbol (row : Fin 689) (j : Fin 690) :
    basicResidueValue1381 row j ^ 28 =
      certificate1381.root ^ (basicEdgeSymbol1381 row j).val := by
  rw [basicResidueValue1381, basicResidueGeomSum1381_eq]
  simpa [reducedBasicResidueValue1381, extendedConjugateExponent1381,
    conjugateExponent1381, certificate1381,
    Fermat.OneThousandThreeHundredEightyOne.CircularUnitResidues.certificate] using
    reducedBasicResidueValue1381_symbol row j

end Fermat.OneThousandThreeHundredEightyOne.VandiverDiagonalUnitResidues
