import Fermat.Irregular.CircularUnitIndex
import Fermat.ThirtySeven.CircularUnitResidues
import FltRegular.NumberTheory.Cyclotomic.UnitLemmas

/-!
# Residue homomorphisms for the exponent-thirty-seven unit certificate

This file constructs the characteristic-`149` specialization of the ring of
integers of a `37`th cyclotomic field.  The specialization sends a chosen
primitive root `ζ` to the row root `16^(j+1)` from the uploaded circular-unit
matrix.

The later power-residue map must be corrected by complex conjugation before it
is passed to units modulo torsion: the raw residue character is nontrivial on
`ζ`.  Keeping the specialization itself separate makes that descent issue
explicit.
-/

namespace Fermat.ThirtySeven.ResidueHomomorphisms

open Polynomial
open scoped NumberField
open Fermat.Irregular.CircularUnitIndex
open Fermat.ThirtySeven.CircularUnitResidues

local instance : Fact (Nat.Prime 149) := ⟨by norm_num⟩
local instance : Fact (Nat.Prime 37) := ⟨by norm_num⟩

/-- Every row root `16^(j+1)` is again a primitive `37`th root modulo `149`. -/
theorem embeddingRoot_isPrimitive (j : Fin 17) :
    IsPrimitiveRoot (embeddingRoot j) 37 := by
  have h16 : IsPrimitiveRoot (16 : ZMod 149) 37 :=
    IsPrimitiveRoot.iff_orderOf.mpr root_order
  apply h16.pow_of_coprime
  exact Nat.Coprime.symm <| Nat.coprime_of_lt_prime
    (by omega) (by omega) (by norm_num)

/-- The fixed root `16`, bundled as a finite-field unit. -/
def rootUnit : (ZMod 149)ˣ := Units.mk0 16 (by decide)

/-- The bundled root still has exact order `37`. -/
theorem rootUnit_isPrimitive : IsPrimitiveRoot rootUnit 37 := by
  apply IsPrimitiveRoot.coe_units_iff.mp
  simpa [rootUnit] using
    (IsPrimitiveRoot.iff_orderOf.mpr root_order :
      IsPrimitiveRoot (16 : ZMod 149) 37)

/-- The fourth power of every nonzero residue modulo `149` belongs to the
order-`37` subgroup generated by `16`. -/
noncomputable def fourthPowerToRootPowers :
    (ZMod 149)ˣ →* Subgroup.zpowers rootUnit where
  toFun u := ⟨u ^ 4, by
    rw [rootUnit_isPrimitive.zpowers_eq]
    rw [mem_rootsOfUnity]
    calc
      (u ^ 4) ^ 37 = u ^ (149 - 1) := by rw [← pow_mul]
      _ = 1 := ZMod.units_pow_card_sub_one_eq_one 149 u⟩
  map_one' := by ext; simp
  map_mul' u v := by ext; simp [mul_pow]

/-- Discrete logarithm of the fourth-power residue symbol, normalized by
the root `16`. -/
noncomputable def residueLog : Additive (ZMod 149)ˣ →+ ZMod 37 :=
  rootUnit_isPrimitive.zmodEquivZPowers.symm.toAddMonoidHom.comp
    fourthPowerToRootPowers.toAdditive

/-- A certificate `u⁴ = 16^m` is exactly what the residue logarithm
consumes. -/
theorem residueLog_eq_of_pow_eq (u : (ZMod 149)ˣ) (m : ℕ)
    (h : ((u : ZMod 149) ^ 4) = (16 : ZMod 149) ^ m) :
    residueLog (Additive.ofMul u) = (m : ZMod 37) := by
  have hsub : fourthPowerToRootPowers u =
      (⟨rootUnit ^ m, m, rfl⟩ : Subgroup.zpowers rootUnit) := by
    unfold fourthPowerToRootPowers
    apply Subtype.ext
    change u ^ 4 = rootUnit ^ m
    apply Units.ext
    simpa [rootUnit] using h
  change rootUnit_isPrimitive.zmodEquivZPowers.symm
    (Additive.ofMul (fourthPowerToRootPowers u)) = (m : ZMod 37)
  rw [hsub, rootUnit_isPrimitive.zmodEquivZPowers_symm_apply_pow]

variable {K : Type*} [Field K] [NumberField K]
variable [IsCyclotomicExtension {37} ℚ K]
variable {ζ : K} (hζ : IsPrimitiveRoot ζ 37)

omit [IsCyclotomicExtension {37} ℚ K] in
/-- The integral cyclotomic generator has the expected minimal polynomial
over `ℤ`. -/
private theorem minpoly_toInteger_eq_cyclotomic :
    minpoly ℤ hζ.toInteger = cyclotomic 37 ℤ := by
  apply Polynomial.map_injective (algebraMap ℤ ℚ)
    (RingHom.injective_int (algebraMap ℤ ℚ))
  rw [← minpoly.isIntegrallyClosed_eq_field_fractions ℚ K,
    show algebraMap (𝓞 K) K hζ.toInteger = ζ from rfl,
    ← cyclotomic_eq_minpoly_rat hζ (by norm_num), map_cyclotomic]
  exact IsIntegralClosure.isIntegral _ K _

/-- Evaluation of cyclotomic integers at the row root `16^(j+1)` modulo
`149`. -/
noncomputable def reductionHom (j : Fin 17) : 𝓞 K →+* ZMod 149 :=
  (hζ.integralPowerBasis.lift (embeddingRoot j) (by
    rw [hζ.integralPowerBasis_gen, minpoly_toInteger_eq_cyclotomic hζ]
    simpa [aeval_def, eval₂_eq_eval_map, map_cyclotomic, IsRoot.def] using
      (embeddingRoot_isPrimitive j).isRoot_cyclotomic (by norm_num))).toRingHom

/-- The reduction homomorphism has the prescribed value on the cyclotomic
generator. -/
@[simp]
theorem reductionHom_zeta (j : Fin 17) :
    reductionHom hζ j hζ.toInteger = embeddingRoot j := by
  rw [reductionHom, ← hζ.integralPowerBasis_gen]
  exact PowerBasis.lift_gen _ _ _

/-- Specializing the concrete circular unit gives exactly the normalized
finite-field value used in the uploaded matrix. -/
theorem reductionHom_circularUnit37 (j i : Fin 17) :
    reductionHom hζ j (circularUnit37 hζ i : 𝓞 K) =
      normalizedUnitValue j i := by
  rw [circularUnit37_val]
  simp only [map_mul, map_pow, map_sum, reductionHom_zeta]
  rw [normalizedUnitValue]
  simp only [normalizationExponent37, normalizationExponent, unitIndex]
  have hne : 1 - embeddingRoot j ≠ 0 :=
    sub_ne_zero.mpr (Ne.symm ((embeddingRoot_isPrimitive j).ne_one (by norm_num)))
  apply (eq_div_iff hne).2
  rw [mul_assoc, geom_sum_mul_neg]

section CM

variable [NumberField.IsCMField K]

local instance : Module ℤ (UnitsModTorsion K) :=
  @AddCommGroup.toIntModule (UnitsModTorsion K) (inferInstance)

/-- The multiplicative norm from a CM unit to its real part.  On roots of
unity this is one; on a real unit it is its square. -/
noncomputable def realUnitNorm : (𝓞 K)ˣ →* (𝓞 K)ˣ where
  toFun u := u * NumberField.IsCMField.unitsComplexConj K u
  map_one' := by simp
  map_mul' u v := by
    simp only [map_mul]
    ac_rfl

omit [IsCyclotomicExtension {37} ℚ K] in
/-- The real norm kills every root of unity. -/
theorem realUnitNorm_eq_one_of_mem_torsion (u : (𝓞 K)ˣ)
    (hu : u ∈ NumberField.Units.torsion K) : realUnitNorm u = 1 := by
  have hconj : NumberField.IsCMField.unitsComplexConj K u = u⁻¹ := by
    simpa using
      (NumberField.IsCMField.unitsComplexConj_torsion (K := K)
        (⟨u, hu⟩ : NumberField.Units.torsion K))
  change u * NumberField.IsCMField.unitsComplexConj K u = 1
  rw [hconj, mul_inv_cancel]

omit [IsCyclotomicExtension {37} ℚ K] in
/-- The real norm squares each normalized circular unit. -/
@[simp]
theorem realUnitNorm_circularUnit37 (i : Fin 17) :
    realUnitNorm (circularUnit37 hζ i) = circularUnit37 hζ i ^ 2 := by
  change circularUnit37 hζ i *
    NumberField.IsCMField.unitsComplexConj K (circularUnit37 hζ i) = _
  rw [circularUnit37_unitsComplexConj hζ]
  exact (pow_two _).symm

/-- Multiplication by the inverse of `2` in `ZMod 37`. -/
def halfScale : ZMod 37 →+ ZMod 37 where
  toFun x := 19 * x
  map_zero' := by simp
  map_add' x y := by ring

/-- The corrected residue character on the full cyclotomic unit group.

The real norm kills cyclotomic torsion but squares real circular units.  The
factor `19 = 2⁻¹ mod 37` removes that square, so the values on the uploaded
circular units remain the original matrix entries. -/
noncomputable def correctedResidueLog (j : Fin 17) :
    Additive (𝓞 K)ˣ →+ ZMod 37 :=
  halfScale.comp <| residueLog.comp <|
    ((Units.map (reductionHom hζ j)).comp (realUnitNorm (K := K))).toAdditive

/-- The corrected residue character vanishes on the torsion subgroup, which
is the exact well-definedness fact needed to descend to units modulo
torsion. -/
theorem correctedResidueLog_eq_zero_of_mem_torsion (j : Fin 17)
    (u : (𝓞 K)ˣ) (hu : u ∈ NumberField.Units.torsion K) :
    correctedResidueLog (hζ := hζ) j (Additive.ofMul u) = 0 := by
  rw [correctedResidueLog]
  simp [realUnitNorm_eq_one_of_mem_torsion (K := K) u hu]

/-- On a circular unit, the conjugation correction and the factor `19`
cancel, leaving precisely the uploaded matrix entry. -/
theorem correctedResidueLog_circularUnit37 (j i : Fin 17) :
    correctedResidueLog (hζ := hζ) j
        (Additive.ofMul (circularUnit37 hζ i)) =
      Fermat.ThirtySeven.CircularUnitCertificate.matrix j i := by
  let u : (ZMod 149)ˣ :=
    Units.map (reductionHom hζ j)
      (realUnitNorm (circularUnit37 hζ i))
  have huval : (u : ZMod 149) = normalizedUnitValue j i ^ 2 := by
    simp [u, reductionHom_circularUnit37 hζ]
  have hpow : ((u : ZMod 149) ^ 4) =
      (16 : ZMod 149) ^
        ((Fermat.ThirtySeven.CircularUnitCertificate.matrix j i).val * 2) := by
    calc
      (u : ZMod 149) ^ 4 = (normalizedUnitValue j i ^ 2) ^ 4 := by rw [huval]
      _ = (normalizedUnitValue j i ^ 4) ^ 2 := by ring
      _ = ((16 : ZMod 149) ^
          (Fermat.ThirtySeven.CircularUnitCertificate.matrix j i).val) ^ 2 := by
            rw [matrix_entry_certificate]
      _ = (16 : ZMod 149) ^
          ((Fermat.ThirtySeven.CircularUnitCertificate.matrix j i).val * 2) := by
            rw [pow_mul]
  change 19 * residueLog (Additive.ofMul u) =
    Fermat.ThirtySeven.CircularUnitCertificate.matrix j i
  rw [residueLog_eq_of_pow_eq u _ hpow]
  rw [Nat.cast_mul, ZMod.natCast_zmod_val]
  have hhalf : (19 : ZMod 37) * 2 = 1 := by decide
  calc
    19 * (Fermat.ThirtySeven.CircularUnitCertificate.matrix j i * 2) =
        (19 * 2) * Fermat.ThirtySeven.CircularUnitCertificate.matrix j i := by ring
    _ = Fermat.ThirtySeven.CircularUnitCertificate.matrix j i := by rw [hhalf, one_mul]

/-- Multiplicative presentation of `correctedResidueLog`, used to descend
through the multiplicative quotient by torsion. -/
noncomputable def correctedResidueLogMul (j : Fin 17) :
    (𝓞 K)ˣ →* Multiplicative (ZMod 37) where
  toFun u := Multiplicative.ofAdd <|
    correctedResidueLog (hζ := hζ) j (Additive.ofMul u)
  map_one' := by
    apply Multiplicative.toAdd.injective
    simp
  map_mul' u v := by
    apply Multiplicative.toAdd.injective
    exact map_add (correctedResidueLog (hζ := hζ) j)
      (Additive.ofMul u) (Additive.ofMul v)

/-- The torsion subgroup lies in the kernel of the multiplicative corrected
residue character. -/
theorem torsion_le_correctedResidueLogMul_ker (j : Fin 17) :
    NumberField.Units.torsion K ≤ (correctedResidueLogMul hζ j).ker := by
  intro u hu
  rw [MonoidHom.mem_ker]
  apply Multiplicative.toAdd.injective
  exact correctedResidueLog_eq_zero_of_mem_torsion hζ j u hu

/-- The corrected residue character on units modulo roots of unity. -/
noncomputable def quotientResidueLogMul (j : Fin 17) :
    ((𝓞 K)ˣ ⧸ NumberField.Units.torsion K) →* Multiplicative (ZMod 37) :=
  QuotientGroup.lift (NumberField.Units.torsion K)
    (correctedResidueLogMul hζ j)
    (torsion_le_correctedResidueLogMul_ker hζ j)

/-- Additive form of the corrected character on the Dirichlet unit
lattice. -/
noncomputable def quotientResidueLog (j : Fin 17) :
    UnitsModTorsion K →+ ZMod 37 where
  toFun q := Multiplicative.toAdd (quotientResidueLogMul hζ j q.toMul)
  map_zero' := by simp [quotientResidueLogMul]
  map_add' x y := by
    change Multiplicative.toAdd
      (quotientResidueLogMul hζ j (x.toMul * y.toMul)) = _
    rw [map_mul]
    rfl

/-- The `ℤ`-linear residue functional consumed by the circular-unit matrix
certificate. -/
noncomputable def quotientResidueLinear (j : Fin 17) :
    UnitsModTorsion K →ₗ[ℤ] ZMod 37 :=
  { quotientResidueLog hζ j with
    map_smul' := fun n x ↦ (quotientResidueLog hζ j).map_zsmul n x }

/-- Evaluation on the class of a unit agrees with the corrected character
before quotienting. -/
@[simp]
theorem quotientResidueLog_classOfUnit (j : Fin 17) (u : (𝓞 K)ˣ) :
    quotientResidueLog hζ j (classOfUnit u) =
      correctedResidueLog (hζ := hζ) j (Additive.ofMul u) := by
  rfl

/-- The quotient functional evaluates the concrete circular units to the
uploaded matrix. -/
@[simp]
theorem quotientResidueLinear_circularUnit37 (j i : Fin 17) :
    quotientResidueLinear hζ j (classOfUnit (circularUnit37 hζ i)) =
      Fermat.ThirtySeven.CircularUnitCertificate.matrix j i := by
  change quotientResidueLog hζ j (classOfUnit (circularUnit37 hζ i)) = _
  rw [quotientResidueLog_classOfUnit]
  exact correctedResidueLog_circularUnit37 hζ j i

/-- The seventeen corrected residue functionals, one for each row of the
uploaded certificate. -/
noncomputable def residueFunctionals :
    Fin 17 → UnitsModTorsion K →ₗ[ℤ] ZMod 37 :=
  fun j ↦ quotientResidueLinear hζ j

/-- The constructed functionals realize the entire uploaded matrix on the
concrete circular units. -/
theorem evalMatrix_circularUnit37 :
    Fermat.Irregular.CircularUnits.evalMatrix
        (classOfUnit ∘ circularUnit37 hζ) (residueFunctionals hζ) =
      Fermat.ThirtySeven.CircularUnitCertificate.matrix := by
  ext j i
  exact quotientResidueLinear_circularUnit37 hζ j i

/-- Consequently, the concrete circular units generate a subgroup of full
unit index prime to `37`. -/
theorem not_dvd_circularUnit37_full_index :
    ¬37 ∣ (Subgroup.closure (Set.range (circularUnit37 hζ)) ⊔
      NumberField.Units.torsion K).index := by
  apply not_dvd_circularUnit37_index_of_evalMatrix_eq hζ (residueFunctionals hζ)
  exact evalMatrix_circularUnit37 hζ

/-- The same concrete certificate gives relative index prime to `37` inside
the real-unit subgroup (with the full-field torsion adjoined). -/
theorem not_dvd_circularUnit37_real_index :
    ¬37 ∣ (Subgroup.closure (Set.range (circularUnit37 hζ)) ⊔
      NumberField.Units.torsion K).relIndex
        (NumberField.IsCMField.realUnits K ⊔ NumberField.Units.torsion K) := by
  apply not_dvd_circularUnit37_realUnitRelIndex_of_evalMatrix_eq
    hζ (residueFunctionals hζ)
  exact evalMatrix_circularUnit37 hζ

end CM

/-- The CM structure needed above is automatic for a `37`th cyclotomic
number field. -/
theorem not_dvd_circularUnit37_full_index_of_cyclotomic :
    ¬37 ∣ (Subgroup.closure (Set.range (circularUnit37 hζ)) ⊔
      NumberField.Units.torsion K).index := by
  letI : NumberField.IsCMField K := cyclotomic37_isCMField (K := K)
  exact not_dvd_circularUnit37_full_index hζ

/-- Unconditional cyclotomic-field form of the real-unit relative-index
certificate. -/
theorem not_dvd_circularUnit37_real_index_of_cyclotomic :
    letI : NumberField.IsCMField K := cyclotomic37_isCMField (K := K)
    ¬37 ∣ (Subgroup.closure (Set.range (circularUnit37 hζ)) ⊔
      NumberField.Units.torsion K).relIndex
        (NumberField.IsCMField.realUnits K ⊔ NumberField.Units.torsion K) := by
  letI : NumberField.IsCMField K := cyclotomic37_isCMField (K := K)
  exact not_dvd_circularUnit37_real_index hζ

end Fermat.ThirtySeven.ResidueHomomorphisms
