import Fermat.ThirtySeven.VandiverHistorical

set_option maxHeartbeats 800000
set_option maxRecDepth 3000

namespace Fermat.ThirtySeven.VandiverHistorical

open scoped NumberField nonZeroDivisors

open Fermat.Irregular.VandiverHistoricalDescent
open Fermat.Irregular.VandiverCriterion
open Fermat.Irregular.VandiverLemmaOne

noncomputable section

variable {K : Type} [Field K] [NumberField K]
  [IsCyclotomicExtension {37} ℚ K]

local instance : Fact (Nat.Prime 37) := ⟨by norm_num⟩

local instance : NumberField.IsCMField K :=
  IsCyclotomicExtension.IsCMField (p := 37) K (by norm_num)

/-- The normalized pair immediately after equation (9a), together with
the exact source equation needed to allocate its fixed-denominator factor. -/
structure PostEquationNineNormalizedData37
    {ζ : K} (hζ : IsPrimitiveRoot ζ 37) where
  m : ℕ
  one_lt_m : 1 < m
  rplus : 𝓞 K
  rminus : 𝓞 K
  rzero : 𝓞 K
  epsilon : (𝓞 K)ˣ
  equation :
    rplus ^ 37 - rminus ^ 37 =
      epsilon * (((hζ.unit' : 𝓞 K) - 1) ^ (2 * m - 1) * rzero) ^ 37
  conjugate :
    NumberField.IsCMField.ringOfIntegersComplexConj K rplus = rminus
  coprime : IsCoprime rplus rminus
  rminus_not_ramified : ¬ (hζ.unit' : 𝓞 K) - 1 ∣ rminus
  depth : ℕ
  two_le_depth : 2 ≤ depth
  close :
    ((hζ.unit' : 𝓞 K) - 1) ^ depth ∣ rplus - rminus

namespace PostEquationNineNormalizedData37

variable {ζ : K} (hζ : IsPrimitiveRoot ζ 37)
  (d : PostEquationNineNormalizedData37 hζ)

lemma regularEquation :
    d.rplus ^ 37 + (-d.rminus) ^ 37 =
      d.epsilon *
        (((hζ.unit' : 𝓞 K) - 1) ^ ((2 * d.m - 2) + 1) * d.rzero) ^ 37 := by
  have hexp : 2 * d.m - 1 = (2 * d.m - 2) + 1 := by
    have hm := d.one_lt_m
    omega
  rw [← hexp]
  simpa only [Odd.neg_pow (by norm_num : Odd 37), sub_eq_add_neg] using d.equation

lemma neg_rminus_not_ramified :
    ¬ (hζ.unit' : 𝓞 K) - 1 ∣ -d.rminus := by
  simpa using d.rminus_not_ramified

/-- Vandiver's literal quotient `(rplus - ζ*rminus)/(1-ζ)`.
`div_zeta_sub_one` uses the associated denominator `ζ-1`, hence the
outer minus sign. -/
noncomputable def quotient : 𝓞 K :=
  -div_zeta_sub_one (by norm_num : 37 ≠ 2) hζ
    (d.regularEquation hζ)
    (zetaNthRoot (K := K) (p := 37) hζ)

/-- The allocated ideal whose 37th power is generated by `quotient`. -/
noncomputable def quotientIdeal : Ideal (𝓞 K) :=
  root_div_zeta_sub_one_dvd_gcd (by norm_num : 37 ≠ 2) hζ
    (d.regularEquation hζ) (d.neg_rminus_not_ramified hζ)
    (zetaNthRoot (K := K) (p := 37) hζ)

lemma quotient_mul_one_sub_zeta :
    quotient hζ d * (1 - (hζ.unit' : 𝓞 K)) =
      d.rplus - (hζ.unit' : 𝓞 K) * d.rminus := by
  have hmul := div_zeta_sub_one_mul_zeta_sub_one
    (by norm_num : 37 ≠ 2) hζ
    (d.regularEquation hζ)
    (zetaNthRoot (K := K) (p := 37) hζ)
  calc
    quotient hζ d * (1 - (hζ.unit' : 𝓞 K)) =
        div_zeta_sub_one (by norm_num : 37 ≠ 2) hζ
          (d.regularEquation hζ)
          (zetaNthRoot (K := K) (p := 37) hζ) *
            ((hζ.unit' : 𝓞 K) - 1) := by
      dsimp [quotient]
      ring
    _ = d.rplus +
        (-d.rminus) *
          (zetaNthRoot (K := K) (p := 37) hζ : 𝓞 K) := hmul
    _ = d.rplus - (hζ.unit' : 𝓞 K) * d.rminus := by
      dsimp [zetaNthRoot]
      ring

lemma quotientIdeal_pow37 :
    quotientIdeal hζ d ^ 37 = Ideal.span {quotient hζ d} := by
  have hpow := linearFactorQuotient_span_eq_factorRoot_pow
    (by norm_num : 37 ≠ 2) hζ
    (d.regularEquation hζ) (d.neg_rminus_not_ramified hζ)
    d.coprime.neg_right
    (zetaNthRoot (K := K) (p := 37) hζ)
  calc
    quotientIdeal hζ d ^ 37 =
        Ideal.span
          {div_zeta_sub_one (by norm_num : 37 ≠ 2) hζ
            (d.regularEquation hζ)
            (zetaNthRoot (K := K) (p := 37) hζ)} := hpow.symm
    _ = Ideal.span {quotient hζ d} := by
      apply Ideal.span_singleton_eq_span_singleton.mpr
      refine ⟨-1, ?_⟩
      simp [quotient]

lemma quotient_real :
    NumberField.IsCMField.ringOfIntegersComplexConj K (quotient hζ d) =
      quotient hζ d := by
  let q : 𝓞 K := quotient hζ d
  let t : 𝓞 K := (hζ.unit' : 𝓞 K)
  have htinv : t * (hζ.unit'⁻¹ : (𝓞 K)ˣ) = 1 := by
    dsimp [t]
    rw [← Units.val_mul]
    simp
  have ht0 : 1 - t ≠ 0 := by
    dsimp [t]
    exact sub_ne_zero.mpr (hζ.unit'_coe.ne_one (by norm_num)).symm
  have hconjt :
      NumberField.IsCMField.ringOfIntegersComplexConj K t =
        (hζ.unit'⁻¹ : (𝓞 K)ˣ) := by
    exact congrArg ((↑) : (𝓞 K)ˣ → 𝓞 K)
      (unitsComplexConj_zeta37 hζ)
  have hconjminus :
      NumberField.IsCMField.ringOfIntegersComplexConj K d.rminus =
        d.rplus := by
    have hcc :
        NumberField.IsCMField.ringOfIntegersComplexConj K
          (NumberField.IsCMField.ringOfIntegersComplexConj K d.rplus) =
            d.rplus := by
      ext
      exact NumberField.IsCMField.complexConj_apply_apply K d.rplus
    rw [d.conjugate] at hcc
    exact hcc
  have hq :
      q * (1 - t) = d.rplus - t * d.rminus := by
    simpa only [q, t] using d.quotient_mul_one_sub_zeta hζ
  have hc := congrArg
    (NumberField.IsCMField.ringOfIntegersComplexConj K) hq
  have hc' :
      NumberField.IsCMField.ringOfIntegersComplexConj K q *
          (1 - (hζ.unit'⁻¹ : (𝓞 K)ˣ)) =
        d.rminus - (hζ.unit'⁻¹ : (𝓞 K)ˣ) * d.rplus := by
    simpa only [map_mul, map_sub, map_one, hconjt, d.conjugate,
      hconjminus] using hc
  have hden :
      1 - t = (-t) * (1 - (hζ.unit'⁻¹ : (𝓞 K)ˣ)) := by
    calc
      1 - t = -t + 1 := by ring
      _ = -t + t * (hζ.unit'⁻¹ : (𝓞 K)ˣ) := by rw [htinv]
      _ = (-t) * (1 - (hζ.unit'⁻¹ : (𝓞 K)ˣ)) := by ring
  apply mul_right_cancel₀ ht0
  calc
    NumberField.IsCMField.ringOfIntegersComplexConj K q * (1 - t) =
        NumberField.IsCMField.ringOfIntegersComplexConj K q *
          ((-t) * (1 - (hζ.unit'⁻¹ : (𝓞 K)ˣ))) := by
      rw [hden]
    _ = (-t) *
          (NumberField.IsCMField.ringOfIntegersComplexConj K q *
            (1 - (hζ.unit'⁻¹ : (𝓞 K)ˣ))) := by ring
    _ = (-t) *
        (d.rminus - (hζ.unit'⁻¹ : (𝓞 K)ˣ) * d.rplus) := by
      rw [hc']
    _ = d.rplus - t * d.rminus := by
      rw [mul_sub, neg_mul, neg_mul, ← mul_assoc, htinv, one_mul]
      ring
    _ = q * (1 - t) := hq.symm

/-- The fixed-denominator quotient differs from the normalized inverse
root by one fewer power of the uniformizer. -/
lemma pow_pred_dvd_rminus_sub_quotient :
    ((hζ.unit' : 𝓞 K) - 1) ^ (d.depth - 1) ∣
      d.rminus - quotient hζ d := by
  let π : 𝓞 K := (hζ.unit' : 𝓞 K) - 1
  let q : 𝓞 K := quotient hζ d
  have hπ0 : π ≠ 0 :=
    hζ.unit'_coe.sub_one_ne_zero (by norm_num)
  have hq :
      q * (1 - (hζ.unit' : 𝓞 K)) =
        d.rplus - (hζ.unit' : 𝓞 K) * d.rminus := by
    simpa only [q] using d.quotient_mul_one_sub_zeta hζ
  have hqπ :
      q * π =
        -(d.rplus - (hζ.unit' : 𝓞 K) * d.rminus) := by
    calc
      q * π = -(q * (1 - (hζ.unit' : 𝓞 K))) := by
        dsimp [π]
        ring
      _ = -(d.rplus - (hζ.unit' : 𝓞 K) * d.rminus) := by rw [hq]
  have hmul :
      (d.rminus - q) * π = d.rplus - d.rminus := by
    rw [sub_mul, hqπ]
    dsimp [π]
    ring
  obtain ⟨c, hc⟩ := d.close
  refine ⟨c, ?_⟩
  apply mul_right_cancel₀ hπ0
  calc
    (d.rminus - q) * π = d.rplus - d.rminus := hmul
    _ = π ^ d.depth * c := by simpa only [π] using hc
    _ = (π ^ (d.depth - 1) * c) * π := by
      have hdepth : d.depth = (d.depth - 1) + 1 := by
        have hd := d.two_le_depth
        omega
      have hp : π ^ d.depth = π ^ (d.depth - 1) * π := by
        have hp0 :
            π ^ d.depth = π ^ ((d.depth - 1) + 1) :=
          congrArg (fun n : ℕ => π ^ n) hdepth
        calc
          π ^ d.depth = π ^ ((d.depth - 1) + 1) := hp0
          _ = π ^ (d.depth - 1) * π := pow_succ _ _
      rw [hp]
      ring

lemma quotient_not_ramified :
    ¬ (hζ.unit' : 𝓞 K) - 1 ∣ quotient hζ d := by
  intro hq
  apply d.rminus_not_ramified
  have hpredPos : d.depth - 1 ≠ 0 := by
    have hd := d.two_le_depth
    omega
  have hdiff :
      (hζ.unit' : 𝓞 K) - 1 ∣
        d.rminus - quotient hζ d :=
    (dvd_pow_self ((hζ.unit' : 𝓞 K) - 1) hpredPos).trans
      (d.pow_pred_dvd_rminus_sub_quotient hζ)
  have hadd := dvd_add hdiff hq
  convert hadd using 1
  ring

lemma quotientIdeal_not_ramified :
    ¬ Ideal.span
        ({(hζ.unit' : 𝓞 K) - 1} : Set (𝓞 K)) ∣
      quotientIdeal hζ d := by
  intro hJ
  apply d.quotient_not_ramified hζ
  rw [← Ideal.mem_span_singleton, ← Ideal.dvd_span_singleton,
    ← d.quotientIdeal_pow37 hζ]
  exact dvd_pow (n := 37) hJ (by norm_num)

/-- The complete post-(9) generator extraction. The quotient uses
Vandiver's literal denominator `1-ζ`; its allocated ideal is principalized
by a real generator, and both normalized roots agree with the resulting
unit times a 37th power to depth `depth - 1`. -/
theorem exists_real_generator :
    ∃ (μ : 𝓞 K) (η : (𝓞 K)ˣ),
      quotientIdeal hζ d = Ideal.span {μ} ∧
      NumberField.IsCMField.ringOfIntegersComplexConj K μ = μ ∧
      quotient hζ d = η * μ ^ 37 ∧
      ¬ (hζ.unit' : 𝓞 K) - 1 ∣ μ ∧
      ((hζ.unit' : 𝓞 K) - 1) ^ (d.depth - 1) ∣
        d.rminus - quotient hζ d ∧
      ((hζ.unit' : 𝓞 K) - 1) ^ (d.depth - 1) ∣
        d.rplus - η * μ ^ 37 := by
  obtain ⟨μ, η, hJ, hμreal, hq⟩ :=
    exists_realEquationNineGenerator37 hζ
      (quotientIdeal hζ d) (quotient hζ d)
      (d.quotientIdeal_not_ramified hζ)
      (d.quotient_real hζ)
      (d.quotientIdeal_pow37 hζ)
  have hμnot : ¬ (hζ.unit' : 𝓞 K) - 1 ∣ μ := by
    intro hμ
    apply d.quotient_not_ramified hζ
    rw [hq]
    exact dvd_mul_of_dvd_right
      (dvd_pow (n := 37) hμ (by norm_num)) _
  have hminus := d.pow_pred_dvd_rminus_sub_quotient hζ
  have hplusMinus :
      ((hζ.unit' : 𝓞 K) - 1) ^ (d.depth - 1) ∣
        d.rplus - d.rminus := by
    exact (pow_dvd_pow_of_dvd_of_le dvd_rfl (Nat.sub_le d.depth 1)).trans
      d.close
  have hplusQ :
      ((hζ.unit' : 𝓞 K) - 1) ^ (d.depth - 1) ∣
        d.rplus - quotient hζ d := by
    have hadd := dvd_add hplusMinus hminus
    convert hadd using 1
    ring
  refine ⟨μ, η, hJ, hμreal, hq, hμnot, hminus, ?_⟩
  simpa only [hq] using hplusQ

/-- After absorbing the quotient unit, the normalized inverse root is
literally close to a 37th power. -/
lemma pow_pred_dvd_inv_unit_mul_rminus_sub_pow
    (μ : 𝓞 K) (η : (𝓞 K)ˣ)
    (hq : quotient hζ d = η * μ ^ 37) :
    ((hζ.unit' : 𝓞 K) - 1) ^ (d.depth - 1) ∣
      (η⁻¹ : (𝓞 K)ˣ) * d.rminus - μ ^ 37 := by
  have h := dvd_mul_of_dvd_right
    (d.pow_pred_dvd_rminus_sub_quotient hζ)
    (η⁻¹ : (𝓞 K)ˣ)
  convert h using 1
  rw [hq]
  have hinv : (η⁻¹ : (𝓞 K)ˣ) * (η : 𝓞 K) = 1 := by
    rw [← Units.val_mul]
    simp
  rw [mul_sub, ← mul_assoc, hinv, one_mul]

/-- The same unit absorption makes the normalized positive root close to
the identical real 37th power. -/
lemma pow_pred_dvd_inv_unit_mul_rplus_sub_pow
    (μ : 𝓞 K) (η : (𝓞 K)ˣ)
    (hplus :
      ((hζ.unit' : 𝓞 K) - 1) ^ (d.depth - 1) ∣
        d.rplus - η * μ ^ 37) :
    ((hζ.unit' : 𝓞 K) - 1) ^ (d.depth - 1) ∣
      (η⁻¹ : (𝓞 K)ˣ) * d.rplus - μ ^ 37 := by
  have h := dvd_mul_of_dvd_right hplus (η⁻¹ : (𝓞 K)ˣ)
  convert h using 1
  have hinv : (η⁻¹ : (𝓞 K)ˣ) * (η : 𝓞 K) = 1 := by
    rw [← Units.val_mul]
    simp
  rw [mul_sub, ← mul_assoc, hinv, one_mul]

/-- Rescaling both normalized roots by the inverse quotient unit preserves
their equation, with the coefficient multiplied by the corresponding
inverse 37th power. -/
lemma inv_unit_rescaled_equation
    (η : (𝓞 K)ˣ) :
    ((η⁻¹ : (𝓞 K)ˣ) * d.rplus) ^ 37 -
        ((η⁻¹ : (𝓞 K)ˣ) * d.rminus) ^ 37 =
      (d.epsilon * η⁻¹ ^ 37) *
        (((hζ.unit' : 𝓞 K) - 1) ^ (2 * d.m - 1) * d.rzero) ^ 37 := by
  simp only [mul_pow]
  rw [← mul_sub, d.equation]
  ring

end PostEquationNineNormalizedData37

end

end Fermat.ThirtySeven.VandiverHistorical
