import Mathlib.LinearAlgebra.FreeModule.Finite.CardQuotient

/-!
# Residue-symbol determinants and lattice indices

This file isolates the algebraic part of the circular-unit residue-symbol method.  If a square
family of additive maps from a free `ℤ`-lattice to `ZMod p` has a nonsingular evaluation matrix
on a family of lattice vectors, then those vectors generate a sublattice of index prime to `p`.

Applied to units modulo torsion, the vectors are circular units and the maps are discrete
logarithms of power-residue symbols.  Two bridges are deliberately not asserted here because they
are absent from Mathlib and `flt-regular`:

* the realization of the finite-field evaluations as power-residue homomorphisms on cyclotomic
  units modulo torsion; and
* Kummer's circular-unit index formula identifying the resulting unit-lattice index with the
  class number of the maximal real cyclotomic subfield.
-/

namespace Fermat.Irregular.CircularUnits

noncomputable section

open Module

variable {p : ℕ} {M ι : Type*}
variable [Fintype ι]
variable [AddCommGroup M]

/-- The matrix obtained by evaluating each vector with each mod-`p` additive functional. -/
def evalMatrix (u : ι → M) (f : ι → M →ₗ[ℤ] ZMod p) : Matrix ι ι (ZMod p) :=
  fun j i ↦ f j (u i)

/-- The values of the additive functionals on a fixed integral basis. -/
def basisEvalMatrix (b : Basis ι ℤ M) (f : ι → M →ₗ[ℤ] ZMod p) :
    Matrix ι ι (ZMod p) :=
  fun j k ↦ f j (b k)

/-- Integral coordinates of a vector family, reduced modulo `p`. -/
def coordinateMatrixMod (b : Basis ι ℤ M) (u : ι → M) : Matrix ι ι (ZMod p) :=
  fun k i ↦ (b.repr (u i) k : ZMod p)

/-- Evaluation factors through the matrix of the functionals on a basis and the coordinate
matrix of the evaluated vectors. -/
theorem evalMatrix_eq_mul (b : Basis ι ℤ M) (u : ι → M) (f : ι → M →ₗ[ℤ] ZMod p) :
    evalMatrix u f = basisEvalMatrix b f * coordinateMatrixMod b u := by
  ext j i
  simp only [evalMatrix, basisEvalMatrix, coordinateMatrixMod, Matrix.mul_apply]
  calc
    f j (u i) = f j (∑ k, (b.repr (u i) k) • b k) := by
      congr 1
      exact (b.sum_repr (u i)).symm
    _ = ∑ k, f j ((b.repr (u i) k) • b k) := by rw [map_sum]
    _ = ∑ k, f j (b k) * (b.repr (u i) k : ZMod p) := by
      apply Finset.sum_congr rfl
      intro k _
      rw [map_zsmul]
      simp [mul_comm]

variable [DecidableEq ι]

/-- The determinant of the reduced coordinate matrix is the reduction of the integral
coordinate determinant. -/
theorem det_coordinateMatrixMod (b : Basis ι ℤ M) (u : ι → M) :
    (coordinateMatrixMod (p := p) b u).det = (b.det u : ZMod p) := by
  rw [b.det_apply]
  symm
  calc
    ((b.toMatrix u).det : ZMod p) =
        ((Int.castRingHom (ZMod p)).mapMatrix (b.toMatrix u)).det :=
      RingHom.map_det (Int.castRingHom (ZMod p)) (b.toMatrix u)
    _ = (coordinateMatrixMod (p := p) b u).det := by
      congr

/-- A nonsingular evaluation matrix forces the integral coordinate determinant to remain
nonzero modulo `p`. -/
theorem det_mod_ne_zero_of_eval_det_ne_zero (b : Basis ι ℤ M) (u : ι → M)
    (f : ι → M →ₗ[ℤ] ZMod p) (h : (evalMatrix u f).det ≠ 0) :
    (b.det u : ZMod p) ≠ 0 := by
  intro hb
  apply h
  rw [evalMatrix_eq_mul b u f, Matrix.det_mul, det_coordinateMatrixMod, hb, mul_zero]

/-- In particular, the vectors tested by a nonsingular square evaluation matrix are linearly
independent over `ℤ`. -/
theorem linearIndependent_of_eval_det_ne_zero (b : Basis ι ℤ M) (u : ι → M)
    (f : ι → M →ₗ[ℤ] ZMod p) (h : (evalMatrix u f).det ≠ 0) :
    LinearIndependent ℤ u := by
  have hmod := det_mod_ne_zero_of_eval_det_ne_zero b u f h
  have hdet : b.det u ≠ 0 := by
    intro hz
    apply hmod
    simp [hz]
  letI : Module.Free ℤ M := Module.Free.of_basis b
  letI : Module.Finite ℤ M := Module.Finite.of_basis b
  let g : M →ₗ[ℤ] M := b.constr ℕ u
  have hgdet : LinearMap.det g = b.det u := by
    calc
      LinearMap.det g = ((LinearMap.toMatrix b b) g).det :=
        (LinearMap.det_toMatrix b g).symm
      _ = (b.toMatrix u).det := congr_arg Matrix.det (b.toMatrix_eq_toMatrix_constr u).symm
      _ = b.det u := (b.det_apply u).symm
  have hgker : LinearMap.ker g = ⊥ := by
    by_contra hg
    exact hdet (hgdet ▸ LinearMap.det_eq_zero_iff_ker_ne_bot.mpr hg)
  have hi := b.linearIndependent.map' g hgker
  have hgu : g ∘ b = u := by
    funext i
    exact b.constr_basis ℕ u i
  rw [hgu] at hi
  exact hi

/-- A square family of mod-`p` additive evaluations with nonzero determinant certifies that
the lattice generated by the evaluated vectors has index prime to `p`.

This is the abstract determinant-to-index implication used by circular-unit residue-symbol
certificates. -/
theorem not_dvd_card_quotient_span_of_eval_det_ne_zero (b : Basis ι ℤ M) (u : ι → M)
    (f : ι → M →ₗ[ℤ] ZMod p) (h : (evalMatrix u f).det ≠ 0) :
    ¬ (p ∣ Nat.card (M ⧸ Submodule.span ℤ (Set.range u))) := by
  have hli := linearIndependent_of_eval_det_ne_zero b u f h
  let bN : Basis ι ℤ (Submodule.span ℤ (Set.range u)) := Basis.span hli
  letI : Module.Free ℤ M := Module.Free.of_basis b
  letI : Module.Finite ℤ M := Module.Finite.of_basis b
  have hcard := Submodule.natAbs_det_basis_change b (Submodule.span ℤ (Set.range u)) bN
  have hdet_family : ((↑) ∘ bN : ι → M) = u := by
    funext i
    simp [bN]
  rw [hdet_family] at hcard
  rw [← hcard, ← Int.natCast_dvd]
  exact fun hp ↦ det_mod_ne_zero_of_eval_det_ne_zero b u f h <|
    (ZMod.intCast_zmod_eq_zero_iff_dvd (b.det u) p).mpr hp

/-- Interface matching the uploaded exponent-`37` certificate: a `17 × 17` evaluation matrix
whose determinant is `-1` modulo `37` proves only that the corresponding unit-lattice index is
prime to `37`.  The two number-theoretic bridges listed in the module documentation are still
needed before this can imply `37 ∤ h⁺`. -/
theorem thirtySeven_not_dvd_card_quotient_span_of_eval_det_eq_neg_one
    {M : Type*} [AddCommGroup M] (b : Basis (Fin 17) ℤ M) (u : Fin 17 → M)
    (f : Fin 17 → M →ₗ[ℤ] ZMod 37) (h : (evalMatrix u f).det = -1) :
    ¬ (37 ∣ Nat.card (M ⧸ Submodule.span ℤ (Set.range u))) := by
  apply not_dvd_card_quotient_span_of_eval_det_ne_zero b u f
  rw [h]
  decide

end

end Fermat.Irregular.CircularUnits
