import Fermat.ThirtySeven.CircularUnitCertificate
import Fermat.Irregular.CircularUnitFamily
import Mathlib.NumberTheory.NumberField.CMField
import Mathlib.NumberTheory.NumberField.Cyclotomic.Basic
import Mathlib.NumberTheory.NumberField.Cyclotomic.Embeddings
import Mathlib.NumberTheory.NumberField.Units.Regulator
import Mathlib.RingTheory.RootsOfUnity.CyclotomicUnits

/-!
# Cyclotomic units and their full unit-group index

This file realizes the lattice in `Fermat.Irregular.CircularUnits` as the quotient of the
*full* unit group of a number field by its torsion subgroup.  For any family of units, the
cardinality of the quotient by the span of their classes is proved equal to the multiplicative
index of the subgroup generated by those units and torsion.  Thus a nonsingular residue-symbol
matrix certifies the actual full unit-group index, not merely an abstract lattice index.

For exponent `37` we also:

* define the seventeen normalized cyclotomic units
  `zeta^((1-a)/2) * (1-zeta^a)/(1-zeta)`, for `2 ≤ a ≤ 18`, as units of the ring of
  integers of the full cyclotomic field;
* prove that a `37`th cyclotomic number field has unit rank `17`; and
* specialize the uploaded `17 × 17` certificate to the multiplicative index of this concrete
  family.

Mathlib's regulator theorem then identifies the same index with the regulator ratio.  The final
arithmetic bridge to the real class number is not asserted here: it is Sinnott--Kummer's
cyclotomic-unit index formula (the odd-primary part of this index is the corresponding part of
`h⁺`).  Neither that formula nor an equivalent cyclotomic factorization of the Dedekind zeta
residue is currently present in Mathlib.
-/

open scoped NumberField

namespace Fermat.Irregular.CircularUnitIndex

noncomputable section

open Module NumberField NumberField.InfinitePlace NumberField.Units
open Fermat.Irregular.CircularUnits

variable {K : Type*} [Field K]

/-- The additive integral lattice of units modulo roots of unity. -/
abbrev UnitsModTorsion (K : Type*) [Field K] :=
  Additive ((𝓞 K)ˣ ⧸ NumberField.Units.torsion K)

/- Typeclass search does not unfold the quotient's commutative group structure while looking for
the canonical `ℤ`-module in this particular nested type.  Stating the canonical instance locally
keeps all subsequent objects definitionally on `AddCommGroup.toIntModule`. -/
local instance : Module ℤ (UnitsModTorsion K) :=
  @AddCommGroup.toIntModule (UnitsModTorsion K) (inferInstance)

/-- The class of a unit modulo the torsion subgroup, written additively. -/
def classOfUnit (u : (𝓞 K)ˣ) : UnitsModTorsion K :=
  Additive.ofMul (QuotientGroup.mk u)

/-- The quotient-cardinality used by the lattice certificate is exactly the multiplicative index
of the subgroup generated by the original units together with all roots of unity.

This equality also covers the infinite-index case: both sides use `Nat.card`, hence are zero
there. -/
theorem card_quotient_span_classes_eq_unitIndex {iota : Type*} (u : iota → (𝓞 K)ˣ) :
    Nat.card (UnitsModTorsion K ⧸
      Submodule.span ℤ (Set.range (classOfUnit ∘ u))) =
      (Subgroup.closure (Set.range u) ⊔ NumberField.Units.torsion K).index := by
  change (Submodule.span ℤ (Set.range (classOfUnit ∘ u))).toAddSubgroup.index = _
  have h := Subgroup.index_map (Subgroup.closure (Set.range u))
    (QuotientGroup.mk' (NumberField.Units.torsion K))
  rw [QuotientGroup.ker_mk', QuotientGroup.range_mk', Subgroup.index_top, mul_one] at h
  rw [← h, ← Subgroup.index_toAddSubgroup]
  congr 1
  rw [Submodule.span_int_eq_addSubgroupClosure, MonoidHom.map_closure,
    Subgroup.toAddSubgroup_closure]
  congr 1
  ext x
  simp only [Set.mem_range, Function.comp_apply, classOfUnit, Set.mem_preimage,
    Set.mem_image]
  constructor
  · rintro ⟨i, hi⟩
    exact ⟨u i, ⟨⟨i, rfl⟩, congrArg Additive.toMul hi⟩⟩
  · rintro ⟨a, ⟨⟨i, hai⟩, hax⟩⟩
    subst a
    exact ⟨i, congrArg Additive.ofMul hax⟩

/-- A nonsingular family of additive evaluations on units modulo torsion proves that the
multiplicative unit index is prime to `p`. -/
theorem not_dvd_unitIndex_of_eval_det_ne_zero {p : ℕ} {iota : Type*} [Fintype iota]
    [DecidableEq iota] (b : Basis iota ℤ (UnitsModTorsion K)) (u : iota → (𝓞 K)ˣ)
    (f : iota → UnitsModTorsion K →ₗ[ℤ] ZMod p)
    (h : (evalMatrix (classOfUnit ∘ u) f).det ≠ 0) :
    ¬ p ∣ (Subgroup.closure (Set.range u) ⊔ NumberField.Units.torsion K).index := by
  rw [← card_quotient_span_classes_eq_unitIndex u]
  exact not_dvd_card_quotient_span_of_eval_det_ne_zero b (classOfUnit ∘ u) f h

section NumberField

variable [NumberField K]

/-- When the family has the full unit rank, nonsingularity also proves maximal rank in the
logarithmic embedding. -/
theorem isMaxRank_of_eval_det_ne_zero {p : ℕ}
    (u : Fin (NumberField.Units.rank K) → (𝓞 K)ˣ)
    (f : Fin (NumberField.Units.rank K) → UnitsModTorsion K →ₗ[ℤ] ZMod p)
    (h : (evalMatrix (classOfUnit ∘ u) f).det ≠ 0) :
    NumberField.Units.IsMaxRank u := by
  have hnot := not_dvd_unitIndex_of_eval_det_ne_zero
    (NumberField.Units.basisModTorsion K) u f h
  have hindex :
      (Subgroup.closure (Set.range u) ⊔ NumberField.Units.torsion K).index ≠ 0 := by
    intro hz
    apply hnot
    rw [hz]
    exact dvd_zero p
  apply NumberField.Units.isMaxRank_iff_closure_finiteIndex.mpr
  apply (NumberField.Units.finiteIndex_iff_sup_torsion_finiteIndex (K := K) _).mpr
  rw [Subgroup.finiteIndex_iff]
  exact hindex

/-- The same quotient-cardinality is the regulator of the family divided by the field
regulator.  This is Mathlib's regulator-index theorem expressed in the lattice language used by
the residue-symbol certificate. -/
theorem regOfFamily_div_regulator_eq_card_quotient_span
    (u : Fin (NumberField.Units.rank K) → (𝓞 K)ˣ) :
    NumberField.Units.regOfFamily u / NumberField.Units.regulator K =
      Nat.card (UnitsModTorsion K ⧸
        Submodule.span ℤ (Set.range (classOfUnit ∘ u))) := by
  rw [NumberField.Units.regOfFamily_div_regulator,
    card_quotient_span_classes_eq_unitIndex]

end NumberField

section ThirtySeven

open Fermat.Irregular.CircularUnitFamily

local instance : Fact (Nat.Prime 37) := ⟨by decide⟩

/-- The exponent representing `(1-a)/2` modulo `37` for the column indexed by
`a = i + 2`. -/
def normalizationExponent37 (i : Fin 17) : ℕ :=
  ((38 - (i.val + 2)) * 19) % 37

/-- The standard seventeen normalized cyclotomic units for exponent `37`, realized as units in
the ring of integers of the *full* cyclotomic field. -/
def circularUnit37 {zeta : K} (hzeta : IsPrimitiveRoot zeta 37) (i : Fin 17) : (𝓞 K)ˣ := by
  let a : ℕ := i.val + 2
  have ha : a.Coprime 37 := by
    fin_cases i <;> decide
  let rootUnit : (𝓞 K)ˣ :=
    (hzeta.toInteger_isPrimitiveRoot.isUnit (by norm_num)).unit
  let geomUnit : (𝓞 K)ˣ :=
    (hzeta.toInteger_isPrimitiveRoot.geom_sum_isUnit (by norm_num) ha).unit
  exact rootUnit ^ normalizationExponent37 i * geomUnit

/-- The value of `circularUnit37` in the ring of integers is its normalized geometric sum. -/
theorem circularUnit37_val {zeta : K} (hzeta : IsPrimitiveRoot zeta 37) (i : Fin 17) :
    (circularUnit37 hzeta i : 𝓞 K) =
      hzeta.toInteger ^ normalizationExponent37 i *
        ∑ j ∈ Finset.range (i.val + 2), hzeta.toInteger ^ j := by
  simp [circularUnit37]

/-- In the ambient cyclotomic field, `circularUnit37` is exactly the normalized quotient used by
the uploaded finite-field residue certificate. -/
theorem circularUnit37_coe {zeta : K} (hzeta : IsPrimitiveRoot zeta 37) (i : Fin 17) :
    ((circularUnit37 hzeta i : 𝓞 K) : K) =
      zeta ^ normalizationExponent37 i *
        (1 - zeta ^ (i.val + 2)) / (1 - zeta) := by
  rw [circularUnit37_val]
  simp only [map_mul, map_pow, map_sum, ← RingOfIntegers.coe_eq_algebraMap]
  have hne : 1 - zeta ≠ 0 := sub_ne_zero.mpr (Ne.symm (hzeta.ne_one (by norm_num)))
  apply mul_left_cancel₀ (a := 1 - zeta) hne
  rw [mul_div_cancel₀ _ hne]
  calc
    (1 - zeta) *
        (zeta ^ normalizationExponent37 i *
          ∑ j ∈ Finset.range (i.val + 2), zeta ^ j) =
        zeta ^ normalizationExponent37 i *
          ((1 - zeta) * ∑ j ∈ Finset.range (i.val + 2), zeta ^ j) := by ring
    _ = zeta ^ normalizationExponent37 i * (1 - zeta ^ (i.val + 2)) := by
      rw [show (1 - zeta) * ∑ j ∈ Finset.range (i.val + 2), zeta ^ j =
          1 - zeta ^ (i.val + 2) by
        calc
          (1 - zeta) * ∑ j ∈ Finset.range (i.val + 2), zeta ^ j =
              -((zeta - 1) * ∑ j ∈ Finset.range (i.val + 2), zeta ^ j) := by ring
          _ = -(zeta ^ (i.val + 2) - 1) := by rw [mul_geom_sum]
          _ = 1 - zeta ^ (i.val + 2) := by ring]

/-- The original exponent-`37` normalization agrees with the canonical
odd-prime normalization used by every later certificate. -/
theorem normalizationExponent37_eq_canonical (i : Fin 17) :
    normalizationExponent37 i =
      canonicalNormalizationExponent (p := 37) (i.val + 2) := by
  fin_cases i <;> decide

/-- Backward compatibility is exact: the original seventeen units are the
specialization of the generic odd-prime family, not merely associated
generators of the same subgroup. -/
theorem circularUnit37_eq_circularUnitFamily {zeta : K}
    (hzeta : IsPrimitiveRoot zeta 37) (i : Fin 17) :
    circularUnit37 hzeta i = circularUnitFamily hzeta (by norm_num) i := by
  apply Units.ext
  apply RingOfIntegers.ext
  rw [circularUnit37_coe, circularUnitFamily_coe,
    normalizationExponent37_eq_canonical]

section ComplexConjugation

variable [NumberField K] [NumberField.IsCMField K] [Algebra.IsIntegral ℚ K]

/-- Complex conjugation sends the chosen primitive `37`th root to its inverse. -/
theorem complexConj_zeta37_inv {zeta : K} (hzeta : IsPrimitiveRoot zeta 37) :
    NumberField.IsCMField.complexConj K zeta = zeta⁻¹ := by
  let rootUnit : (𝓞 K)ˣ :=
    (hzeta.toInteger_isPrimitiveRoot.isUnit (by norm_num)).unit
  have hpow : rootUnit ^ 37 = 1 := by
    apply Units.ext
    apply RingOfIntegers.ext
    simpa [rootUnit] using hzeta.pow_eq_one
  have ht : rootUnit ∈ NumberField.Units.torsion K := by
    rw [NumberField.Units.torsion, CommGroup.mem_torsion, isOfFinOrder_iff_pow_eq_one]
    exact ⟨37, by norm_num, hpow⟩
  have hc := NumberField.IsCMField.unitsComplexConj_torsion K ⟨rootUnit, ht⟩
  have hc' : NumberField.IsCMField.unitsComplexConj K rootUnit = rootUnit⁻¹ := by
    simpa using hc
  have hv := congrArg Units.val hc'
  simpa [rootUnit, NumberField.IsCMField.unitsComplexConj,
    NumberField.IsCMField.ringOfIntegersComplexConj,
    NumberField.RingOfIntegers.ext_iff] using congrArg ((↑) : 𝓞 K → K) hv

/-- The normalization exponent makes each of the seventeen circular units real: it is fixed by
the CM-field complex conjugation. -/
theorem circularUnit37_unitsComplexConj {zeta : K} (hzeta : IsPrimitiveRoot zeta 37)
    (i : Fin 17) :
    NumberField.IsCMField.unitsComplexConj K (circularUnit37 hzeta i) =
      circularUnit37 hzeta i := by
  apply Units.ext
  apply RingOfIntegers.ext
  change NumberField.IsCMField.complexConj K
      (((circularUnit37 hzeta i : (𝓞 K)ˣ) : 𝓞 K) : K) =
    (((circularUnit37 hzeta i : (𝓞 K)ˣ) : 𝓞 K) : K)
  rw [circularUnit37_coe]
  simp only [div_eq_mul_inv, map_mul, map_inv₀, map_pow, map_sub, map_one,
    complexConj_zeta37_inv hzeta]
  have h74 : zeta ^ 74 = 1 := by
    rw [show 74 = 37 * 2 by norm_num, pow_mul, hzeta.pow_eq_one, one_pow]
  have hne₁ : zeta - 1 ≠ 0 := sub_ne_zero.mpr (hzeta.ne_one (by norm_num))
  have hne₂ : 1 - zeta ≠ 0 := sub_ne_zero.mpr (Ne.symm (hzeta.ne_one (by norm_num)))
  fin_cases i <;> norm_num [normalizationExponent37] <;>
    field_simp [hzeta.ne_zero, hne₁, hne₂] <;>
    simp only [hzeta.pow_eq_one, h74] <;>
    ring

/-- Equivalently, every `circularUnit37` belongs to Mathlib's subgroup of real units. -/
theorem circularUnit37_mem_realUnits {zeta : K} (hzeta : IsPrimitiveRoot zeta 37)
    (i : Fin 17) :
    circularUnit37 hzeta i ∈ NumberField.IsCMField.realUnits K :=
  (NumberField.IsCMField.unitsComplexConj_eq_self_iff K _).mp
    (circularUnit37_unitsComplexConj hzeta i)

omit [NumberField K] [NumberField.IsCMField K] [Algebra.IsIntegral ℚ K] in
/-- If a family consists of real units, primality of its full unit-group index implies
primality of its relative index inside the subgroup generated by all real units and torsion.
This is the exact index-tower step needed before applying the cyclotomic-unit class-number
formula. -/
theorem not_dvd_realUnitRelIndex_of_not_dvd_unitIndex {p : ℕ} {iota : Type*}
    (u : iota → (𝓞 K)ˣ)
    (hu : ∀ i, u i ∈ NumberField.IsCMField.realUnits K)
    (hnot : ¬ p ∣ (Subgroup.closure (Set.range u) ⊔ NumberField.Units.torsion K).index) :
    ¬ p ∣ (Subgroup.closure (Set.range u) ⊔ NumberField.Units.torsion K).relIndex
      (NumberField.IsCMField.realUnits K ⊔ NumberField.Units.torsion K) := by
  let C := Subgroup.closure (Set.range u) ⊔ NumberField.Units.torsion K
  let R := NumberField.IsCMField.realUnits K ⊔ NumberField.Units.torsion K
  have hle : C ≤ R := by
    apply sup_le
    · apply (Subgroup.closure_le _).mpr
      rintro _ ⟨i, rfl⟩
      exact (show NumberField.IsCMField.realUnits K ≤ R from le_sup_left) (hu i)
    · exact le_sup_right
  have htower := Subgroup.relIndex_mul_index hle
  intro hp
  apply hnot
  rw [← htower]
  exact dvd_mul_of_dvd_left hp _

omit [NumberField K] [NumberField.IsCMField K] [Algebra.IsIntegral ℚ K] in
/-- A nonsingular evaluation matrix on a full basis, together with reality
of the chosen units, proves that their relative index inside the real units
is prime to `p`.  This packages the two generic index steps used by every
odd-prime circular-unit certificate. -/
theorem not_dvd_realUnitRelIndex_of_eval_det_ne_zero
    {p : ℕ} {iota : Type*} [Fintype iota] [DecidableEq iota]
    (b : Basis iota ℤ (UnitsModTorsion K)) (u : iota → (𝓞 K)ˣ)
    (hu : ∀ i, u i ∈ NumberField.IsCMField.realUnits K)
    (f : iota → UnitsModTorsion K →ₗ[ℤ] ZMod p)
    (hdet : (evalMatrix (classOfUnit ∘ u) f).det ≠ 0) :
    ¬ p ∣ (Subgroup.closure (Set.range u) ⊔
        NumberField.Units.torsion K).relIndex
      (NumberField.IsCMField.realUnits K ⊔
        NumberField.Units.torsion K) :=
  not_dvd_realUnitRelIndex_of_not_dvd_unitIndex u hu
    (not_dvd_unitIndex_of_eval_det_ne_zero b u f hdet)

end ComplexConjugation

variable [NumberField K]

/-- A `37`th cyclotomic field is a CM field.  This named theorem lets residue-map constructions
install the required instance locally. -/
theorem cyclotomic37_isCMField [IsCyclotomicExtension {37} ℚ K] :
    NumberField.IsCMField K :=
  IsCyclotomicExtension.Rat.isCMField K (S := ({37} : Set ℕ))
    ⟨37, Set.mem_singleton 37, by norm_num⟩

/-- A `37`th cyclotomic number field has unit rank `17`. -/
theorem cyclotomic37_unitRank [IsCyclotomicExtension {37} ℚ K] :
    NumberField.Units.rank K = 17 := by
  rw [NumberField.Units.rank, card_eq_nrRealPlaces_add_nrComplexPlaces,
    IsCyclotomicExtension.Rat.nrRealPlaces_eq_zero K (n := 37) (by norm_num),
    IsCyclotomicExtension.Rat.nrComplexPlaces_eq_totient_div_two (K := K) 37]
  decide

/-- The Dirichlet basis of units modulo torsion, reindexed by the seventeen columns of the
exponent-`37` certificate. -/
def basisModTorsion37 [IsCyclotomicExtension {37} ℚ K] :
    Basis (Fin 17) ℤ (UnitsModTorsion K) :=
  (NumberField.Units.basisModTorsion K).reindex (finCongr (cyclotomic37_unitRank (K := K)))

/-- The uploaded matrix, once realized by actual residue-symbol homomorphisms on the concrete
cyclotomic units, proves that their multiplicative index in the full unit group is prime to
`37`. -/
theorem not_dvd_circularUnit37_index_of_evalMatrix_eq
    [IsCyclotomicExtension {37} ℚ K] {zeta : K} (hzeta : IsPrimitiveRoot zeta 37)
    (f : Fin 17 → UnitsModTorsion K →ₗ[ℤ] ZMod 37)
    (heval : evalMatrix (classOfUnit ∘ circularUnit37 hzeta) f =
      Fermat.ThirtySeven.CircularUnitCertificate.matrix) :
    ¬ 37 ∣ (Subgroup.closure (Set.range (circularUnit37 hzeta)) ⊔
      NumberField.Units.torsion K).index := by
  apply not_dvd_unitIndex_of_eval_det_ne_zero (basisModTorsion37 (K := K))
    (circularUnit37 hzeta) f
  rw [heval]
  exact Fermat.ThirtySeven.CircularUnitCertificate.matrix_det_ne_zero

/-- The uploaded certificate also proves that the circular units have relative index prime to
`37` inside the real units (with full-field torsion adjoined).  Sinnott--Kummer's index formula
would identify the odd-primary part of this relative index with that of `h⁺`. -/
theorem not_dvd_circularUnit37_realUnitRelIndex_of_evalMatrix_eq
    [IsCyclotomicExtension {37} ℚ K] {zeta : K} (hzeta : IsPrimitiveRoot zeta 37)
    (f : Fin 17 → UnitsModTorsion K →ₗ[ℤ] ZMod 37)
    (heval : evalMatrix (classOfUnit ∘ circularUnit37 hzeta) f =
      Fermat.ThirtySeven.CircularUnitCertificate.matrix) :
    ¬ 37 ∣ (Subgroup.closure (Set.range (circularUnit37 hzeta)) ⊔
      NumberField.Units.torsion K).relIndex
        (NumberField.IsCMField.realUnits K ⊔ NumberField.Units.torsion K) := by
  letI : NumberField.IsCMField K := cyclotomic37_isCMField (K := K)
  apply not_dvd_realUnitRelIndex_of_not_dvd_unitIndex (circularUnit37 hzeta)
  · exact circularUnit37_mem_realUnits hzeta
  · exact not_dvd_circularUnit37_index_of_evalMatrix_eq hzeta f heval

end ThirtySeven

end

end Fermat.Irregular.CircularUnitIndex
