import Fermat.ThirtySeven.CircularUnitCertificate
import Mathlib.NumberTheory.NumberField.Cyclotomic.Basic
import Mathlib.NumberTheory.NumberField.Cyclotomic.Embeddings
import Mathlib.NumberTheory.NumberField.Units.Regulator
import Mathlib.RingTheory.RootsOfUnity.CyclotomicUnits

/-!
# Cyclotomic units and their full unit-group index

This file realizes the lattice in `Fermat.Irregular.CircularUnits` as the quotient of the
*full* unit group of a number field by its torsion subgroup.  For any family of units, the
cardinality of the quotient by the span of their classes is proved equal to the multiplicative
index of the subgroup generated by those units and torsion.  Thus a nonsingular residue-symbol
matrix certifies the actual full unit-group index, not merely an abstract lattice index.

For exponent `37` we also:

* define the seventeen normalized cyclotomic units
  `zeta^((1-a)/2) * (1-zeta^a)/(1-zeta)`, for `2 ≤ a ≤ 18`, as units of the ring of
  integers of the full cyclotomic field;
* prove that a `37`th cyclotomic number field has unit rank `17`; and
* specialize the uploaded `17 × 17` certificate to the multiplicative index of this concrete
  family.

Mathlib's regulator theorem then identifies the same index with the regulator ratio.  The final
arithmetic bridge to the real class number is not asserted here: it is Sinnott--Kummer's
cyclotomic-unit index formula (the odd-primary part of this index is the corresponding part of
`h⁺`).  Neither that formula nor an equivalent cyclotomic factorization of the Dedekind zeta
residue is currently present in Mathlib.
-/

open scoped NumberField

namespace Fermat.Irregular.CircularUnitIndex

noncomputable section

open Module NumberField NumberField.InfinitePlace NumberField.Units
open Fermat.Irregular.CircularUnits

variable {K : Type*} [Field K]

/-- The additive integral lattice of units modulo roots of unity. -/
abbrev UnitsModTorsion (K : Type*) [Field K] :=
  Additive ((𝓞 K)ˣ ⧸ NumberField.Units.torsion K)

/- Typeclass search does not unfold the quotient's commutative group structure while looking for
the canonical `ℤ`-module in this particular nested type.  Stating the canonical instance locally
keeps all subsequent objects definitionally on `AddCommGroup.toIntModule`. -/
local instance : Module ℤ (UnitsModTorsion K) :=
  @AddCommGroup.toIntModule (UnitsModTorsion K) (inferInstance)

/-- The class of a unit modulo the torsion subgroup, written additively. -/
def classOfUnit (u : (𝓞 K)ˣ) : UnitsModTorsion K :=
  Additive.ofMul (QuotientGroup.mk u)

/-- The quotient-cardinality used by the lattice certificate is exactly the multiplicative index
of the subgroup generated by the original units together with all roots of unity.

This equality also covers the infinite-index case: both sides use `Nat.card`, hence are zero
there. -/
theorem card_quotient_span_classes_eq_unitIndex {iota : Type*} (u : iota → (𝓞 K)ˣ) :
    Nat.card (UnitsModTorsion K ⧸
      Submodule.span ℤ (Set.range (classOfUnit ∘ u))) =
      (Subgroup.closure (Set.range u) ⊔ NumberField.Units.torsion K).index := by
  change (Submodule.span ℤ (Set.range (classOfUnit ∘ u))).toAddSubgroup.index = _
  have h := Subgroup.index_map (Subgroup.closure (Set.range u))
    (QuotientGroup.mk' (NumberField.Units.torsion K))
  rw [QuotientGroup.ker_mk', QuotientGroup.range_mk', Subgroup.index_top, mul_one] at h
  rw [← h, ← Subgroup.index_toAddSubgroup]
  congr 1
  rw [Submodule.span_int_eq_addSubgroupClosure, MonoidHom.map_closure,
    Subgroup.toAddSubgroup_closure]
  congr 1
  ext x
  simp only [Set.mem_range, Function.comp_apply, classOfUnit, Set.mem_preimage,
    Set.mem_image]
  constructor
  · rintro ⟨i, hi⟩
    exact ⟨u i, ⟨⟨i, rfl⟩, congrArg Additive.toMul hi⟩⟩
  · rintro ⟨a, ⟨⟨i, hai⟩, hax⟩⟩
    subst a
    exact ⟨i, congrArg Additive.ofMul hax⟩

/-- A nonsingular family of additive evaluations on units modulo torsion proves that the
multiplicative unit index is prime to `p`. -/
theorem not_dvd_unitIndex_of_eval_det_ne_zero {p : ℕ} {iota : Type*} [Fintype iota]
    [DecidableEq iota] (b : Basis iota ℤ (UnitsModTorsion K)) (u : iota → (𝓞 K)ˣ)
    (f : iota → UnitsModTorsion K →ₗ[ℤ] ZMod p)
    (h : (evalMatrix (classOfUnit ∘ u) f).det ≠ 0) :
    ¬ p ∣ (Subgroup.closure (Set.range u) ⊔ NumberField.Units.torsion K).index := by
  rw [← card_quotient_span_classes_eq_unitIndex u]
  exact not_dvd_card_quotient_span_of_eval_det_ne_zero b (classOfUnit ∘ u) f h

section NumberField

variable [NumberField K]

/-- When the family has the full unit rank, nonsingularity also proves maximal rank in the
logarithmic embedding. -/
theorem isMaxRank_of_eval_det_ne_zero {p : ℕ}
    (u : Fin (NumberField.Units.rank K) → (𝓞 K)ˣ)
    (f : Fin (NumberField.Units.rank K) → UnitsModTorsion K →ₗ[ℤ] ZMod p)
    (h : (evalMatrix (classOfUnit ∘ u) f).det ≠ 0) :
    NumberField.Units.IsMaxRank u := by
  have hnot := not_dvd_unitIndex_of_eval_det_ne_zero
    (NumberField.Units.basisModTorsion K) u f h
  have hindex :
      (Subgroup.closure (Set.range u) ⊔ NumberField.Units.torsion K).index ≠ 0 := by
    intro hz
    apply hnot
    rw [hz]
    exact dvd_zero p
  apply NumberField.Units.isMaxRank_iff_closure_finiteIndex.mpr
  apply (NumberField.Units.finiteIndex_iff_sup_torsion_finiteIndex (K := K) _).mpr
  rw [Subgroup.finiteIndex_iff]
  exact hindex

/-- The same quotient-cardinality is the regulator of the family divided by the field
regulator.  This is Mathlib's regulator-index theorem expressed in the lattice language used by
the residue-symbol certificate. -/
theorem regOfFamily_div_regulator_eq_card_quotient_span
    (u : Fin (NumberField.Units.rank K) → (𝓞 K)ˣ) :
    NumberField.Units.regOfFamily u / NumberField.Units.regulator K =
      Nat.card (UnitsModTorsion K ⧸
        Submodule.span ℤ (Set.range (classOfUnit ∘ u))) := by
  rw [NumberField.Units.regOfFamily_div_regulator,
    card_quotient_span_classes_eq_unitIndex]

end NumberField

section ThirtySeven

/-- The exponent representing `(1-a)/2` modulo `37` for the column indexed by
`a = i + 2`. -/
def normalizationExponent37 (i : Fin 17) : ℕ :=
  ((38 - (i.val + 2)) * 19) % 37

/-- The standard seventeen normalized cyclotomic units for exponent `37`, realized as units in
the ring of integers of the *full* cyclotomic field. -/
def circularUnit37 {zeta : K} (hzeta : IsPrimitiveRoot zeta 37) (i : Fin 17) : (𝓞 K)ˣ := by
  let a : ℕ := i.val + 2
  have ha : a.Coprime 37 := by
    fin_cases i <;> decide
  let rootUnit : (𝓞 K)ˣ :=
    (hzeta.toInteger_isPrimitiveRoot.isUnit (by norm_num)).unit
  let geomUnit : (𝓞 K)ˣ :=
    (hzeta.toInteger_isPrimitiveRoot.geom_sum_isUnit (by norm_num) ha).unit
  exact rootUnit ^ normalizationExponent37 i * geomUnit

/-- The value of `circularUnit37` in the ring of integers is its normalized geometric sum. -/
theorem circularUnit37_val {zeta : K} (hzeta : IsPrimitiveRoot zeta 37) (i : Fin 17) :
    (circularUnit37 hzeta i : 𝓞 K) =
      hzeta.toInteger ^ normalizationExponent37 i *
        ∑ j ∈ Finset.range (i.val + 2), hzeta.toInteger ^ j := by
  simp [circularUnit37]

/-- In the ambient cyclotomic field, `circularUnit37` is exactly the normalized quotient used by
the uploaded finite-field residue certificate. -/
theorem circularUnit37_coe {zeta : K} (hzeta : IsPrimitiveRoot zeta 37) (i : Fin 17) :
    ((circularUnit37 hzeta i : 𝓞 K) : K) =
      zeta ^ normalizationExponent37 i *
        (1 - zeta ^ (i.val + 2)) / (1 - zeta) := by
  rw [circularUnit37_val]
  simp only [map_mul, map_pow, map_sum, ← RingOfIntegers.coe_eq_algebraMap]
  have hne : 1 - zeta ≠ 0 := sub_ne_zero.mpr (Ne.symm (hzeta.ne_one (by norm_num)))
  apply mul_left_cancel₀ (a := 1 - zeta) hne
  rw [mul_div_cancel₀ _ hne]
  calc
    (1 - zeta) *
        (zeta ^ normalizationExponent37 i *
          ∑ j ∈ Finset.range (i.val + 2), zeta ^ j) =
        zeta ^ normalizationExponent37 i *
          ((1 - zeta) * ∑ j ∈ Finset.range (i.val + 2), zeta ^ j) := by ring
    _ = zeta ^ normalizationExponent37 i * (1 - zeta ^ (i.val + 2)) := by
      rw [show (1 - zeta) * ∑ j ∈ Finset.range (i.val + 2), zeta ^ j =
          1 - zeta ^ (i.val + 2) by
        calc
          (1 - zeta) * ∑ j ∈ Finset.range (i.val + 2), zeta ^ j =
              -((zeta - 1) * ∑ j ∈ Finset.range (i.val + 2), zeta ^ j) := by ring
          _ = -(zeta ^ (i.val + 2) - 1) := by rw [mul_geom_sum]
          _ = 1 - zeta ^ (i.val + 2) := by ring]

variable [NumberField K]

/-- A `37`th cyclotomic number field has unit rank `17`. -/
theorem cyclotomic37_unitRank [IsCyclotomicExtension {37} ℚ K] :
    NumberField.Units.rank K = 17 := by
  rw [NumberField.Units.rank, card_eq_nrRealPlaces_add_nrComplexPlaces,
    IsCyclotomicExtension.Rat.nrRealPlaces_eq_zero K (n := 37) (by norm_num),
    IsCyclotomicExtension.Rat.nrComplexPlaces_eq_totient_div_two (K := K) 37]
  decide

/-- The Dirichlet basis of units modulo torsion, reindexed by the seventeen columns of the
exponent-`37` certificate. -/
def basisModTorsion37 [IsCyclotomicExtension {37} ℚ K] :
    Basis (Fin 17) ℤ (UnitsModTorsion K) :=
  (NumberField.Units.basisModTorsion K).reindex (finCongr (cyclotomic37_unitRank (K := K)))

/-- The uploaded matrix, once realized by actual residue-symbol homomorphisms on the concrete
cyclotomic units, proves that their multiplicative index in the full unit group is prime to
`37`. -/
theorem not_dvd_circularUnit37_index_of_evalMatrix_eq
    [IsCyclotomicExtension {37} ℚ K] {zeta : K} (hzeta : IsPrimitiveRoot zeta 37)
    (f : Fin 17 → UnitsModTorsion K →ₗ[ℤ] ZMod 37)
    (heval : evalMatrix (classOfUnit ∘ circularUnit37 hzeta) f =
      Fermat.ThirtySeven.CircularUnitCertificate.matrix) :
    ¬ 37 ∣ (Subgroup.closure (Set.range (circularUnit37 hzeta)) ⊔
      NumberField.Units.torsion K).index := by
  apply not_dvd_unitIndex_of_eval_det_ne_zero (basisModTorsion37 (K := K))
    (circularUnit37 hzeta) f
  rw [heval]
  exact Fermat.ThirtySeven.CircularUnitCertificate.matrix_det_ne_zero

end ThirtySeven

end

end Fermat.Irregular.CircularUnitIndex
