import Fermat.Irregular.CircularUnitIndex
import Mathlib.NumberTheory.NumberField.Discriminant.Different
import Mathlib.NumberTheory.NumberField.Cyclotomic.Ideal
import FltRegular.NumberTheory.Cyclotomic.MoreLemmas

/-!
# The discriminant of the maximal real 37th cyclotomic field

This file proves the discriminant input needed by the exponent-37
Sinnott--Kummer bridge.  If `K` is a 37th cyclotomic field and `K⁺` is its
maximal real subfield, then

* `ᵊ K = ᵊ K⁺[ζ]`;
* the relative minimal polynomial of `ζ` is
  `X² - (ζ + ζ⁻¹) X + 1`;
* the relative different is generated by `ζ - ζ⁻¹` and has norm `37`; and
* the discriminant tower formula gives `|D(K⁺)| = 37¹⁷`.

The last theorem records the analytic-class-number-formula normalization
`sqrt |D(K⁺)| = sqrt(37)¹⁷`.
-/

open scoped NumberField Classical

namespace Fermat.Irregular.CyclotomicDiscriminant37

noncomputable section

set_option maxHeartbeats 800000

open NumberField Polynomial
open Fermat.Irregular.CircularUnitIndex

variable {K : Type*} [Field K] [NumberField K]
  [IsCyclotomicExtension {37} ℚ K]

local instance : NumberField.IsCMField K := cyclotomic37_isCMField (K := K)
local notation3 "K⁺" => NumberField.maximalRealSubfield K

/-- The primitive root, as a relative algebra generator of the full ring of integers. -/
theorem adjoin_zeta_over_real_eq_top {zeta : K} (hzeta : IsPrimitiveRoot zeta 37) :
    Algebra.adjoin (NumberField.RingOfIntegers K⁺)
      ({hzeta.toInteger} : Set (NumberField.RingOfIntegers K)) = ⊤ := by
  apply top_unique
  intro x hx
  let A := Algebra.adjoin (NumberField.RingOfIntegers K⁺)
    ({hzeta.toInteger} : Set (NumberField.RingOfIntegers K))
  have htop : Algebra.adjoin ℤ
      ({hzeta.toInteger} : Set (NumberField.RingOfIntegers K)) = ⊤ := by
    simpa only [IsPrimitiveRoot.integralPowerBasis_gen] using
      hzeta.integralPowerBasis.adjoin_gen_eq_top
  have hle : Algebra.adjoin ℤ
      ({hzeta.toInteger} : Set (NumberField.RingOfIntegers K)) ≤
        A.restrictScalars ℤ := by
    apply Algebra.adjoin_le
    intro y hy
    exact Algebra.subset_adjoin hy
  have hxall : x ∈ Algebra.adjoin ℤ
      ({hzeta.toInteger} : Set (NumberField.RingOfIntegers K)) := by
    rw [htop]
    trivial
  exact hle hxall

/-- The integral trace `zeta + zeta⁻¹` viewed in the full ring of integers. -/
def zetaRealTraceInteger {zeta : K} (hzeta : IsPrimitiveRoot zeta 37) :
    NumberField.RingOfIntegers K :=
  (hzeta.unit' : NumberField.RingOfIntegers K) +
    (((hzeta.unit')⁻¹ : (NumberField.RingOfIntegers K)ˣ) :
      NumberField.RingOfIntegers K)

theorem complexConj_zetaRealTraceInteger {zeta : K} (hzeta : IsPrimitiveRoot zeta 37) :
    NumberField.IsCMField.complexConj K (zetaRealTraceInteger hzeta : K) =
      (zetaRealTraceInteger hzeta : K) := by
  change NumberField.IsCMField.complexConj K (zeta + zeta⁻¹) = zeta + zeta⁻¹
  rw [map_add, map_inv₀, complexConj_zeta37_inv hzeta, inv_inv]
  ring

/-- The same trace in the maximal real ring of integers. -/
def realTraceInteger {zeta : K} (hzeta : IsPrimitiveRoot zeta 37) :
    NumberField.RingOfIntegers K⁺ :=
  (NumberField.IsCMField.RingOfIntegers.complexConj_eq_self_iff K
    (zetaRealTraceInteger hzeta)).mp (complexConj_zetaRealTraceInteger hzeta) |>.choose

theorem algebraMap_realTraceInteger {zeta : K} (hzeta : IsPrimitiveRoot zeta 37) :
    algebraMap (NumberField.RingOfIntegers K⁺) K (realTraceInteger hzeta) =
      zeta + zeta⁻¹ := by
  calc
    algebraMap (NumberField.RingOfIntegers K⁺) K (realTraceInteger hzeta) =
        (zetaRealTraceInteger hzeta : K) :=
      (NumberField.IsCMField.RingOfIntegers.complexConj_eq_self_iff K
        (zetaRealTraceInteger hzeta)).mp
          (complexConj_zetaRealTraceInteger hzeta) |>.choose_spec
    _ = zeta + zeta⁻¹ := rfl

/-- The full cyclotomic ring is quadratic and monogenic over the maximal-real ring. -/
noncomputable def relativeIntegralPowerBasis37 {zeta : K}
    (hzeta : IsPrimitiveRoot zeta 37) :
    PowerBasis (NumberField.RingOfIntegers K⁺)
      (NumberField.RingOfIntegers K) :=
  PowerBasis.ofAdjoinEqTop'
    (Algebra.IsIntegral.isIntegral hzeta.toInteger)
    (adjoin_zeta_over_real_eq_top hzeta)

@[simp] theorem relativeIntegralPowerBasis37_gen {zeta : K}
    (hzeta : IsPrimitiveRoot zeta 37) :
    (relativeIntegralPowerBasis37 hzeta).gen = hzeta.toInteger := by
  simp [relativeIntegralPowerBasis37]

theorem relativeIntegralPowerBasis37_dim {zeta : K}
    (hzeta : IsPrimitiveRoot zeta 37) :
    (relativeIntegralPowerBasis37 hzeta).dim = 2 := by
  rw [← PowerBasis.finrank]
  rw [← Algebra.IsAlgebraic.finrank_of_isFractionRing
    (NumberField.RingOfIntegers K⁺) K⁺
    (NumberField.RingOfIntegers K) K]
  exact Algebra.IsQuadraticExtension.finrank_eq_two K⁺ K

theorem algebraMap_realTraceInteger_ring {zeta : K}
    (hzeta : IsPrimitiveRoot zeta 37) :
    algebraMap (NumberField.RingOfIntegers K⁺)
        (NumberField.RingOfIntegers K) (realTraceInteger hzeta) =
      zetaRealTraceInteger hzeta := by
  apply NumberField.RingOfIntegers.ext
  exact algebraMap_realTraceInteger hzeta

/-- The relative quadratic polynomial of `zeta` over the real subfield. -/
def relativeCyclotomicPolynomial37 {zeta : K}
    (hzeta : IsPrimitiveRoot zeta 37) :
    Polynomial (NumberField.RingOfIntegers K⁺) :=
  X ^ 2 - C (realTraceInteger hzeta) * X + 1

theorem relativeCyclotomicPolynomial37_monic {zeta : K}
    (hzeta : IsPrimitiveRoot zeta 37) :
    (relativeCyclotomicPolynomial37 hzeta).Monic := by
  rw [relativeCyclotomicPolynomial37]
  monicity <;> norm_num

theorem relativeCyclotomicPolynomial37_natDegree {zeta : K}
    (hzeta : IsPrimitiveRoot zeta 37) :
    (relativeCyclotomicPolynomial37 hzeta).natDegree = 2 := by
  rw [relativeCyclotomicPolynomial37]
  compute_degree <;> norm_num

theorem relativeCyclotomicPolynomial37_aeval {zeta : K}
    (hzeta : IsPrimitiveRoot zeta 37) :
    Polynomial.aeval hzeta.toInteger
      (relativeCyclotomicPolynomial37 hzeta) = 0 := by
  simp only [relativeCyclotomicPolynomial37, map_add, map_sub, map_mul, map_pow,
    aeval_X, aeval_C, aeval_one]
  rw [algebraMap_realTraceInteger_ring]
  apply NumberField.RingOfIntegers.ext
  change zeta ^ 2 - (zeta + zeta⁻¹) * zeta + 1 = 0
  field_simp [hzeta.ne_zero (by norm_num)]
  ring

/-- Exact relative minimal polynomial in the integral extension. -/
theorem minpoly_zetaInteger_over_real {zeta : K}
    (hzeta : IsPrimitiveRoot zeta 37) :
    minpoly (NumberField.RingOfIntegers K⁺) hzeta.toInteger =
      relativeCyclotomicPolynomial37 hzeta := by
  symm
  apply Polynomial.eq_of_monic_of_dvd_of_natDegree_le
    (minpoly.monic (Algebra.IsIntegral.isIntegral hzeta.toInteger))
    (relativeCyclotomicPolynomial37_monic hzeta)
  · exact minpoly.isIntegrallyClosed_dvd
      (Algebra.IsIntegral.isIntegral hzeta.toInteger)
      (relativeCyclotomicPolynomial37_aeval hzeta)
  · rw [relativeCyclotomicPolynomial37_natDegree]
    have h := (relativeIntegralPowerBasis37 hzeta).natDegree_minpoly
    rw [relativeIntegralPowerBasis37_gen,
      relativeIntegralPowerBasis37_dim] at h
    omega

/-- Generator of the relative different, `zeta - zeta⁻¹`. -/
def zetaDifferentGenerator37 {zeta : K} (hzeta : IsPrimitiveRoot zeta 37) :
    NumberField.RingOfIntegers K :=
  (hzeta.unit' : NumberField.RingOfIntegers K) -
    (((hzeta.unit')⁻¹ : (NumberField.RingOfIntegers K)ˣ) :
      NumberField.RingOfIntegers K)

theorem aeval_derivative_minpoly_zetaInteger_over_real {zeta : K}
    (hzeta : IsPrimitiveRoot zeta 37) :
    Polynomial.aeval hzeta.toInteger
        (derivative (minpoly (NumberField.RingOfIntegers K⁺) hzeta.toInteger)) =
      zetaDifferentGenerator37 hzeta := by
  rw [minpoly_zetaInteger_over_real, relativeCyclotomicPolynomial37]
  simp [derivative_mul, algebraMap_realTraceInteger_ring,
    zetaRealTraceInteger, zetaDifferentGenerator37]
  rw [show hzeta.toInteger =
    (hzeta.unit' : NumberField.RingOfIntegers K) from rfl]
  ring

/-- A primitive root generates the full field over its maximal real subfield. -/
theorem adjoin_zeta_over_real_field_eq_top {zeta : K}
    (hzeta : IsPrimitiveRoot zeta 37) :
    Algebra.adjoin K⁺ ({zeta} : Set K) = ⊤ := by
  apply top_unique
  intro x hx
  let A := Algebra.adjoin K⁺ ({zeta} : Set K)
  have htop : Algebra.adjoin ℚ ({zeta} : Set K) = ⊤ :=
    IsCyclotomicExtension.adjoin_primitive_root_eq_top
      (A := ℚ) (B := K) hzeta
  have hle : Algebra.adjoin ℚ ({zeta} : Set K) ≤
      A.restrictScalars ℚ := by
    apply Algebra.adjoin_le
    intro y hy
    exact Algebra.subset_adjoin hy
  apply hle
  rw [htop]
  trivial

/-- The relative different of `K/K⁺` is the principal ideal generated by
`zeta - zeta⁻¹`. -/
theorem differentIdeal_real_eq_span_zetaDifferent {zeta : K}
    (hzeta : IsPrimitiveRoot zeta 37) :
    differentIdeal (NumberField.RingOfIntegers K⁺)
        (NumberField.RingOfIntegers K) =
      Ideal.span {zetaDifferentGenerator37 hzeta} := by
  have hfield : Algebra.adjoin K⁺
      ({algebraMap (NumberField.RingOfIntegers K) K hzeta.toInteger} : Set K) = ⊤ := by
    rw [show algebraMap (NumberField.RingOfIntegers K) K hzeta.toInteger = zeta by
      exact hzeta.coe_toInteger]
    exact adjoin_zeta_over_real_field_eq_top hzeta
  have h := conductor_mul_differentIdeal
    (NumberField.RingOfIntegers K⁺) K⁺ K hzeta.toInteger hfield
  rw [conductor_eq_top_of_adjoin_eq_top (adjoin_zeta_over_real_eq_top hzeta),
    aeval_derivative_minpoly_zetaInteger_over_real] at h
  simpa using h

omit [NumberField K] [IsCyclotomicExtension {37} ℚ K] in
theorem associated_zeta_sub_one_zetaDifferent {zeta : K}
    (hzeta : IsPrimitiveRoot zeta 37) :
    Associated (hzeta.toInteger - 1) (zetaDifferentGenerator37 hzeta) := by
  have hpow : Associated (hzeta.toInteger - 1) (hzeta.toInteger ^ 2 - 1) :=
    hzeta.toInteger_isPrimitiveRoot.associated_sub_one_pow_sub_one_of_coprime
      (by decide : Nat.Coprime 2 37)
  have hdelta : Associated (zetaDifferentGenerator37 hzeta)
      (hzeta.toInteger ^ 2 - 1) := by
    refine ⟨hzeta.unit', ?_⟩
    simp only [zetaDifferentGenerator37]
    rw [show hzeta.toInteger =
      (hzeta.unit' : NumberField.RingOfIntegers K) from rfl]
    rw [sub_mul, Units.inv_mul]
    ring
  exact hpow.trans hdelta.symm

theorem absNorm_span_zetaDifferent {zeta : K}
    (hzeta : IsPrimitiveRoot zeta 37) :
    Ideal.absNorm (Ideal.span {zetaDifferentGenerator37 hzeta}) = 37 := by
  letI : Fact (Nat.Prime 37) := ⟨by decide⟩
  rw [Ideal.span_singleton_eq_span_singleton.mpr
    (associated_zeta_sub_one_zetaDifferent hzeta).symm]
  simpa only [pow_one, zero_add] using
    IsCyclotomicExtension.Rat.absNorm_span_zeta_sub_one 37 0 hzeta

theorem absNorm_differentIdeal_real {zeta : K}
    (hzeta : IsPrimitiveRoot zeta 37) :
    Ideal.absNorm (differentIdeal (NumberField.RingOfIntegers K⁺)
      (NumberField.RingOfIntegers K)) = 37 := by
  rw [differentIdeal_real_eq_span_zetaDifferent hzeta,
    absNorm_span_zetaDifferent hzeta]

theorem natAbs_discr_cyclotomic37 :
    (NumberField.discr K).natAbs = 37 ^ 35 := by
  letI : Fact (Nat.Prime 37) := ⟨by decide⟩
  rw [IsCyclotomicExtension.Rat.discr_prime 37 K]
  norm_num

/-- The maximal real subfield of a 37th cyclotomic field has absolute
discriminant `37^17`. -/
theorem natAbs_discr_maximalRealSubfield37 :
    (NumberField.discr K⁺).natAbs = 37 ^ 17 := by
  let hzeta := IsCyclotomicExtension.zeta_spec 37 ℚ K
  have htower := NumberField.natAbs_discr_eq_absNorm_differentIdeal_mul_natAbs_discr_pow
    K⁺ (NumberField.RingOfIntegers K⁺) K (NumberField.RingOfIntegers K)
  rw [natAbs_discr_cyclotomic37,
    absNorm_differentIdeal_real hzeta,
    Algebra.IsQuadraticExtension.finrank_eq_two] at htower
  have hsquare : 37 ^ 34 = (NumberField.discr K⁺).natAbs ^ 2 := by
    apply Nat.mul_left_cancel (by norm_num : 0 < 37)
    calc
      37 * 37 ^ 34 = 37 ^ 35 := by ring
      _ = 37 * (NumberField.discr K⁺).natAbs ^ 2 := htower
  apply Nat.pow_left_injective (by decide : 2 ≠ 0)
  calc
    (NumberField.discr K⁺).natAbs ^ 2 = 37 ^ 34 := hsquare.symm
    _ = (37 ^ 17) ^ 2 := by ring

theorem abs_realCast_discr_maximalRealSubfield37 :
    |(NumberField.discr K⁺ : ℝ)| = (37 : ℝ) ^ 17 := by
  rw [← Int.cast_abs, ← Int.natCast_natAbs]
  exact_mod_cast natAbs_discr_maximalRealSubfield37 (K := K)

/-- The discriminant normalization used by the analytic class-number formula. -/
theorem sqrt_abs_discr_maximalRealSubfield37 :
    Real.sqrt |(NumberField.discr K⁺ : ℝ)| = (Real.sqrt 37) ^ 17 := by
  rw [abs_realCast_discr_maximalRealSubfield37]
  apply (sq_eq_sq₀ (Real.sqrt_nonneg _)
    (pow_nonneg (Real.sqrt_nonneg _) _)).mp
  rw [Real.sq_sqrt (by positivity)]
  symm
  calc
    ((Real.sqrt 37) ^ 17) ^ 2 = ((Real.sqrt 37) ^ 2) ^ 17 := by ring
    _ = (37 : ℝ) ^ 17 := by rw [Real.sq_sqrt (by norm_num)]

end

end Fermat.Irregular.CyclotomicDiscriminant37
