import Fermat.Irregular.CircularUnitIndex
import Mathlib.NumberTheory.NumberField.Discriminant.Different
import Mathlib.NumberTheory.NumberField.Cyclotomic.Ideal
import FltRegular.NumberTheory.Cyclotomic.MoreLemmas

/-!
# Discriminants of maximal real prime cyclotomic fields

For every odd prime `p`, this file computes the relative different of the
cyclotomic CM extension `K/K⁺` and derives

`|D(K⁺)| = p ^ ((p - 3) / 2)`.

The proof is uniform in `p`.  It constructs the relative integral power
basis generated by a primitive root `ζ`, identifies its quadratic minimal
polynomial, proves that the relative different is generated by `ζ - ζ⁻¹`,
computes the norm of that generator as `p`, and applies the discriminant
tower formula.  The final square-root normalization is directly reusable in
the analytic class-number formula for every prime-exponent campaign.
-/

open scoped NumberField Classical

namespace Fermat.Irregular.CyclotomicDiscriminantPrime

noncomputable section

set_option maxHeartbeats 800000

open NumberField

variable {p : ℕ} [Fact (Nat.Prime p)] [Fact (2 < p)]
variable {K : Type*} [Field K] [NumberField K]
  [IsCyclotomicExtension {p} ℚ K] [NumberField.IsCMField K]

local notation3 "K⁺" => NumberField.maximalRealSubfield K

omit [Fact (2 < p)] [IsCyclotomicExtension {p} ℚ K] in
theorem complexConj_zeta_inv {zeta : K} (hzeta : IsPrimitiveRoot zeta p) :
    NumberField.IsCMField.complexConj K zeta = zeta⁻¹ := by
  let rootUnit : (NumberField.RingOfIntegers K)ˣ :=
    (hzeta.toInteger_isPrimitiveRoot.isUnit
      (Nat.Prime.ne_zero (Fact.out : Nat.Prime p))).unit
  have hpow : rootUnit ^ p = 1 := by
    apply Units.ext
    apply NumberField.RingOfIntegers.ext
    simpa [rootUnit] using hzeta.pow_eq_one
  have ht : rootUnit ∈ NumberField.Units.torsion K := by
    rw [NumberField.Units.torsion, CommGroup.mem_torsion, isOfFinOrder_iff_pow_eq_one]
    exact ⟨p, Nat.Prime.pos (Fact.out : Nat.Prime p), hpow⟩
  have hc := NumberField.IsCMField.unitsComplexConj_torsion K ⟨rootUnit, ht⟩
  have hc' : NumberField.IsCMField.unitsComplexConj K rootUnit = rootUnit⁻¹ := by
    simpa using hc
  have hv := congrArg Units.val hc'
  simpa [rootUnit, NumberField.IsCMField.unitsComplexConj,
    NumberField.IsCMField.ringOfIntegersComplexConj,
    NumberField.RingOfIntegers.ext_iff] using
      congrArg ((↑) : NumberField.RingOfIntegers K → K) hv

omit [Fact (2 < p)] [NumberField.IsCMField K] in
theorem adjoin_zeta_over_real_eq_top {zeta : K}
    (hzeta : IsPrimitiveRoot zeta p) :
    Algebra.adjoin (NumberField.RingOfIntegers K⁺)
      ({hzeta.toInteger} : Set (NumberField.RingOfIntegers K)) = ⊤ := by
  apply top_unique
  intro x hx
  let A := Algebra.adjoin (NumberField.RingOfIntegers K⁺)
    ({hzeta.toInteger} : Set (NumberField.RingOfIntegers K))
  have htop : Algebra.adjoin ℤ
      ({hzeta.toInteger} : Set (NumberField.RingOfIntegers K)) = ⊤ := by
    simpa only [IsPrimitiveRoot.integralPowerBasis_gen] using
      hzeta.integralPowerBasis.adjoin_gen_eq_top
  have hle : Algebra.adjoin ℤ
      ({hzeta.toInteger} : Set (NumberField.RingOfIntegers K)) ≤
        A.restrictScalars ℤ := by
    apply Algebra.adjoin_le
    intro y hy
    exact Algebra.subset_adjoin hy
  apply hle
  rw [htop]
  trivial

def zetaRealTraceInteger {zeta : K} (hzeta : IsPrimitiveRoot zeta p) :
    NumberField.RingOfIntegers K :=
  (hzeta.unit' : NumberField.RingOfIntegers K) +
    (((hzeta.unit')⁻¹ : (NumberField.RingOfIntegers K)ˣ) :
      NumberField.RingOfIntegers K)

omit [Fact (2 < p)] [IsCyclotomicExtension {p} ℚ K] in
theorem complexConj_zetaRealTraceInteger {zeta : K}
    (hzeta : IsPrimitiveRoot zeta p) :
    NumberField.IsCMField.complexConj K (zetaRealTraceInteger hzeta : K) =
      (zetaRealTraceInteger hzeta : K) := by
  change NumberField.IsCMField.complexConj K (zeta + zeta⁻¹) = zeta + zeta⁻¹
  rw [map_add, map_inv₀, complexConj_zeta_inv hzeta, inv_inv]
  ring

def realTraceInteger {zeta : K} (hzeta : IsPrimitiveRoot zeta p) :
    NumberField.RingOfIntegers K⁺ :=
  (NumberField.IsCMField.RingOfIntegers.complexConj_eq_self_iff K
    (zetaRealTraceInteger hzeta)).mp (complexConj_zetaRealTraceInteger hzeta) |>.choose

omit [Fact (2 < p)] [IsCyclotomicExtension {p} ℚ K] in
theorem algebraMap_realTraceInteger {zeta : K} (hzeta : IsPrimitiveRoot zeta p) :
    algebraMap (NumberField.RingOfIntegers K⁺) K (realTraceInteger hzeta) =
      zeta + zeta⁻¹ := by
  calc
    algebraMap (NumberField.RingOfIntegers K⁺) K (realTraceInteger hzeta) =
        (zetaRealTraceInteger hzeta : K) :=
      (NumberField.IsCMField.RingOfIntegers.complexConj_eq_self_iff K
        (zetaRealTraceInteger hzeta)).mp
          (complexConj_zetaRealTraceInteger hzeta) |>.choose_spec
    _ = zeta + zeta⁻¹ := rfl

noncomputable def relativeIntegralPowerBasis {zeta : K}
    (hzeta : IsPrimitiveRoot zeta p) :
    PowerBasis (NumberField.RingOfIntegers K⁺)
      (NumberField.RingOfIntegers K) :=
  PowerBasis.ofAdjoinEqTop'
    (Algebra.IsIntegral.isIntegral hzeta.toInteger)
    (adjoin_zeta_over_real_eq_top hzeta)

omit [Fact (2 < p)] [NumberField.IsCMField K] in
@[simp] theorem relativeIntegralPowerBasis_gen {zeta : K}
    (hzeta : IsPrimitiveRoot zeta p) :
    (relativeIntegralPowerBasis hzeta).gen = hzeta.toInteger := by
  simp [relativeIntegralPowerBasis]

omit [Fact (2 < p)] in
theorem relativeIntegralPowerBasis_dim {zeta : K}
    (hzeta : IsPrimitiveRoot zeta p) :
    (relativeIntegralPowerBasis hzeta).dim = 2 := by
  rw [← PowerBasis.finrank]
  rw [← Algebra.IsAlgebraic.finrank_of_isFractionRing
    (NumberField.RingOfIntegers K⁺) K⁺
    (NumberField.RingOfIntegers K) K]
  exact Algebra.IsQuadraticExtension.finrank_eq_two K⁺ K

omit [Fact (2 < p)] [IsCyclotomicExtension {p} ℚ K] in
theorem algebraMap_realTraceInteger_ring {zeta : K}
    (hzeta : IsPrimitiveRoot zeta p) :
    algebraMap (NumberField.RingOfIntegers K⁺)
        (NumberField.RingOfIntegers K) (realTraceInteger hzeta) =
      zetaRealTraceInteger hzeta := by
  apply NumberField.RingOfIntegers.ext
  exact algebraMap_realTraceInteger hzeta

def relativeCyclotomicPolynomial {zeta : K}
    (hzeta : IsPrimitiveRoot zeta p) :
    Polynomial (NumberField.RingOfIntegers K⁺) :=
  Polynomial.X ^ 2 - Polynomial.C (realTraceInteger hzeta) * Polynomial.X + 1

omit [Fact (2 < p)] [IsCyclotomicExtension {p} ℚ K] in
theorem relativeCyclotomicPolynomial_monic {zeta : K}
    (hzeta : IsPrimitiveRoot zeta p) :
    (relativeCyclotomicPolynomial hzeta).Monic := by
  rw [relativeCyclotomicPolynomial]
  monicity <;> norm_num

omit [Fact (2 < p)] [IsCyclotomicExtension {p} ℚ K] in
theorem relativeCyclotomicPolynomial_natDegree {zeta : K}
    (hzeta : IsPrimitiveRoot zeta p) :
    (relativeCyclotomicPolynomial hzeta).natDegree = 2 := by
  rw [relativeCyclotomicPolynomial]
  compute_degree <;> norm_num

omit [Fact (2 < p)] [IsCyclotomicExtension {p} ℚ K] in
theorem relativeCyclotomicPolynomial_aeval {zeta : K}
    (hzeta : IsPrimitiveRoot zeta p) :
    Polynomial.aeval hzeta.toInteger
      (relativeCyclotomicPolynomial hzeta) = 0 := by
  simp only [relativeCyclotomicPolynomial, map_add, map_sub, map_mul, map_pow,
    Polynomial.aeval_X, Polynomial.aeval_C, Polynomial.aeval_one]
  rw [algebraMap_realTraceInteger_ring]
  apply NumberField.RingOfIntegers.ext
  change zeta ^ 2 - (zeta + zeta⁻¹) * zeta + 1 = 0
  field_simp [hzeta.ne_zero (Nat.Prime.ne_zero (Fact.out : Nat.Prime p))]
  ring

omit [Fact (2 < p)] in
theorem minpoly_zetaInteger_over_real {zeta : K}
    (hzeta : IsPrimitiveRoot zeta p) :
    minpoly (NumberField.RingOfIntegers K⁺) hzeta.toInteger =
      relativeCyclotomicPolynomial hzeta := by
  symm
  apply Polynomial.eq_of_monic_of_dvd_of_natDegree_le
    (minpoly.monic (Algebra.IsIntegral.isIntegral hzeta.toInteger))
    (relativeCyclotomicPolynomial_monic hzeta)
  · exact minpoly.isIntegrallyClosed_dvd
      (Algebra.IsIntegral.isIntegral hzeta.toInteger)
      (relativeCyclotomicPolynomial_aeval hzeta)
  · rw [relativeCyclotomicPolynomial_natDegree]
    have h := (relativeIntegralPowerBasis hzeta).natDegree_minpoly
    rw [relativeIntegralPowerBasis_gen,
      relativeIntegralPowerBasis_dim] at h
    omega

def zetaDifferentGenerator {zeta : K} (hzeta : IsPrimitiveRoot zeta p) :
    NumberField.RingOfIntegers K :=
  (hzeta.unit' : NumberField.RingOfIntegers K) -
    (((hzeta.unit')⁻¹ : (NumberField.RingOfIntegers K)ˣ) :
      NumberField.RingOfIntegers K)

omit [Fact (2 < p)] in
theorem aeval_derivative_minpoly_zetaInteger_over_real {zeta : K}
    (hzeta : IsPrimitiveRoot zeta p) :
    Polynomial.aeval hzeta.toInteger
        (Polynomial.derivative
          (minpoly (NumberField.RingOfIntegers K⁺) hzeta.toInteger)) =
      zetaDifferentGenerator hzeta := by
  rw [minpoly_zetaInteger_over_real, relativeCyclotomicPolynomial]
  simp [Polynomial.derivative_mul, algebraMap_realTraceInteger_ring,
    zetaRealTraceInteger, zetaDifferentGenerator]
  rw [show hzeta.toInteger =
    (hzeta.unit' : NumberField.RingOfIntegers K) from rfl]
  ring

omit [Fact (2 < p)] [NumberField.IsCMField K] in
theorem adjoin_zeta_over_real_field_eq_top {zeta : K}
    (hzeta : IsPrimitiveRoot zeta p) :
    Algebra.adjoin K⁺ ({zeta} : Set K) = ⊤ := by
  apply top_unique
  intro x hx
  let A := Algebra.adjoin K⁺ ({zeta} : Set K)
  have htop : Algebra.adjoin ℚ ({zeta} : Set K) = ⊤ :=
    IsCyclotomicExtension.adjoin_primitive_root_eq_top
      (A := ℚ) (B := K) hzeta
  have hle : Algebra.adjoin ℚ ({zeta} : Set K) ≤
      A.restrictScalars ℚ := by
    apply Algebra.adjoin_le
    intro y hy
    exact Algebra.subset_adjoin hy
  apply hle
  rw [htop]
  trivial

omit [Fact (2 < p)] in
theorem differentIdeal_real_eq_span_zetaDifferent {zeta : K}
    (hzeta : IsPrimitiveRoot zeta p) :
    differentIdeal (NumberField.RingOfIntegers K⁺)
        (NumberField.RingOfIntegers K) =
      Ideal.span {zetaDifferentGenerator hzeta} := by
  have hfield : Algebra.adjoin K⁺
      ({algebraMap (NumberField.RingOfIntegers K) K hzeta.toInteger} : Set K) = ⊤ := by
    simpa only [hzeta.coe_toInteger] using adjoin_zeta_over_real_field_eq_top hzeta
  have h := conductor_mul_differentIdeal
    (NumberField.RingOfIntegers K⁺) K⁺ K hzeta.toInteger hfield
  rw [conductor_eq_top_of_adjoin_eq_top (adjoin_zeta_over_real_eq_top hzeta),
    aeval_derivative_minpoly_zetaInteger_over_real] at h
  simpa using h

omit [NumberField K] [IsCyclotomicExtension {p} ℚ K]
    [NumberField.IsCMField K] in
theorem associated_zeta_sub_one_zetaDifferent {zeta : K}
    (hzeta : IsPrimitiveRoot zeta p) :
    Associated (hzeta.toInteger - 1) (zetaDifferentGenerator hzeta) := by
  have hpodd : Odd p := Nat.Prime.odd_of_ne_two
    (Fact.out : Nat.Prime p) (by have := (Fact.out : 2 < p); omega)
  have hpow : Associated (hzeta.toInteger - 1) (hzeta.toInteger ^ 2 - 1) :=
    hzeta.toInteger_isPrimitiveRoot.associated_sub_one_pow_sub_one_of_coprime
      (Nat.coprime_two_left.mpr hpodd)
  have hdelta : Associated (zetaDifferentGenerator hzeta)
      (hzeta.toInteger ^ 2 - 1) := by
    refine ⟨hzeta.unit', ?_⟩
    simp only [zetaDifferentGenerator]
    rw [show hzeta.toInteger =
      (hzeta.unit' : NumberField.RingOfIntegers K) from rfl]
    rw [sub_mul, Units.inv_mul]
    ring
  exact hpow.trans hdelta.symm

omit [NumberField.IsCMField K] in
theorem absNorm_span_zetaDifferent {zeta : K}
    (hzeta : IsPrimitiveRoot zeta p) :
    Ideal.absNorm (Ideal.span {zetaDifferentGenerator hzeta}) = p := by
  rw [Ideal.span_singleton_eq_span_singleton.mpr
    (associated_zeta_sub_one_zetaDifferent hzeta).symm]
  letI : IsCyclotomicExtension {p ^ (0 + 1)} ℚ K := by
    simpa only [zero_add, pow_one] using
      (inferInstance : IsCyclotomicExtension {p} ℚ K)
  have hzeta' : IsPrimitiveRoot zeta (p ^ (0 + 1)) := by
    simpa only [zero_add, pow_one] using hzeta
  exact IsCyclotomicExtension.Rat.absNorm_span_zeta_sub_one p 0 hzeta'

theorem absNorm_differentIdeal_real {zeta : K}
    (hzeta : IsPrimitiveRoot zeta p) :
    Ideal.absNorm (differentIdeal (NumberField.RingOfIntegers K⁺)
      (NumberField.RingOfIntegers K)) = p := by
  rw [differentIdeal_real_eq_span_zetaDifferent hzeta,
    absNorm_span_zetaDifferent hzeta]

theorem absNorm_differentIdeal_maximalRealSubfield :
    Ideal.absNorm (differentIdeal (NumberField.RingOfIntegers K⁺)
      (NumberField.RingOfIntegers K)) = p :=
  absNorm_differentIdeal_real (IsCyclotomicExtension.zeta_spec p ℚ K)

omit [Fact (2 < p)] [NumberField.IsCMField K] in
theorem natAbs_discr_cyclotomicPrime :
    (NumberField.discr K).natAbs = p ^ (p - 2) := by
  rw [IsCyclotomicExtension.Rat.discr_prime p K]
  rw [Int.natAbs_mul, Int.natAbs_pow]
  simp

theorem odd_prime_exponent_identity :
    p - 2 = ((p - 3) / 2) * 2 + 1 := by
  have hp3 : 2 < p := Fact.out
  have hpodd : Odd p := Nat.Prime.odd_of_ne_two
    (Fact.out : Nat.Prime p) (by omega)
  obtain ⟨k, hk⟩ := hpodd
  omega

theorem natAbs_discr_maximalRealSubfield_of_absNorm_different
    (hdifferent :
      Ideal.absNorm (differentIdeal (NumberField.RingOfIntegers K⁺)
        (NumberField.RingOfIntegers K)) = p) :
    (NumberField.discr K⁺).natAbs = p ^ ((p - 3) / 2) := by
  have htower := NumberField.natAbs_discr_eq_absNorm_differentIdeal_mul_natAbs_discr_pow
    K⁺ (NumberField.RingOfIntegers K⁺) K (NumberField.RingOfIntegers K)
  rw [natAbs_discr_cyclotomicPrime (p := p) (K := K), hdifferent,
    Algebra.IsQuadraticExtension.finrank_eq_two] at htower
  have hsquare : (p ^ ((p - 3) / 2)) ^ 2 =
      (NumberField.discr K⁺).natAbs ^ 2 := by
    apply Nat.mul_left_cancel (Nat.Prime.pos (Fact.out : Nat.Prime p))
    calc
      p * (p ^ ((p - 3) / 2)) ^ 2 = p ^ (p - 2) := by
        rw [odd_prime_exponent_identity (p := p)]
        rw [pow_add, pow_mul, pow_one]
        ring
      _ = p * (NumberField.discr K⁺).natAbs ^ 2 := htower
  apply Nat.pow_left_injective (by decide : 2 ≠ 0)
  exact hsquare.symm

theorem abs_realCast_discr_maximalRealSubfield_of_absNorm_different
    (hdifferent :
      Ideal.absNorm (differentIdeal (NumberField.RingOfIntegers K⁺)
        (NumberField.RingOfIntegers K)) = p) :
    |(NumberField.discr K⁺ : ℝ)| = (p : ℝ) ^ ((p - 3) / 2) := by
  rw [← Int.cast_abs, ← Int.natCast_natAbs]
  exact_mod_cast
    natAbs_discr_maximalRealSubfield_of_absNorm_different
      (p := p) (K := K) hdifferent

theorem sqrt_abs_discr_maximalRealSubfield_of_absNorm_different
    (hdifferent :
      Ideal.absNorm (differentIdeal (NumberField.RingOfIntegers K⁺)
        (NumberField.RingOfIntegers K)) = p) :
    Real.sqrt |(NumberField.discr K⁺ : ℝ)| =
      (Real.sqrt p) ^ ((p - 3) / 2) := by
  rw [abs_realCast_discr_maximalRealSubfield_of_absNorm_different
    (p := p) (K := K) hdifferent]
  apply (sq_eq_sq₀ (Real.sqrt_nonneg _)
    (pow_nonneg (Real.sqrt_nonneg _) _)).mp
  rw [Real.sq_sqrt (by positivity)]
  symm
  calc
    ((Real.sqrt p) ^ ((p - 3) / 2)) ^ 2 =
        (Real.sqrt p) ^ (((p - 3) / 2) * 2) := by rw [pow_mul]
    _ = (Real.sqrt p) ^ (2 * ((p - 3) / 2)) := by rw [mul_comm]
    _ = ((Real.sqrt p) ^ 2) ^ ((p - 3) / 2) := by rw [pow_mul]
    _ = (p : ℝ) ^ ((p - 3) / 2) := by
      rw [Real.sq_sqrt (by positivity)]

theorem natAbs_discr_maximalRealSubfield :
    (NumberField.discr K⁺).natAbs = p ^ ((p - 3) / 2) :=
  natAbs_discr_maximalRealSubfield_of_absNorm_different
    (p := p) (K := K) absNorm_differentIdeal_maximalRealSubfield

theorem abs_realCast_discr_maximalRealSubfield :
    |(NumberField.discr K⁺ : ℝ)| = (p : ℝ) ^ ((p - 3) / 2) :=
  abs_realCast_discr_maximalRealSubfield_of_absNorm_different
    (p := p) (K := K) absNorm_differentIdeal_maximalRealSubfield

theorem sqrt_abs_discr_maximalRealSubfield :
    Real.sqrt |(NumberField.discr K⁺ : ℝ)| =
      (Real.sqrt p) ^ ((p - 3) / 2) :=
  sqrt_abs_discr_maximalRealSubfield_of_absNorm_different
    (p := p) (K := K) absNorm_differentIdeal_maximalRealSubfield

end
end Fermat.Irregular.CyclotomicDiscriminantPrime
