import Fermat.Irregular.KummerConjugationDescent157

set_option maxRecDepth 50000

/-!
# The real fixed field of a degree-157 Kummer extension

Let `L/K` be the degree-`157` Kummer extension attached to an
anti-invariant radicand, and let `τ` be the lift of complex conjugation
constructed in `KummerConjugationDescent157`.  This file defines

`M = L ^ ⟨τ⟩`

over the maximal real subfield `K⁺`.  It proves the field-theoretic
package needed by the reflection argument: `[L : M] = 2` and
`[M : K⁺] = 157`.  The remaining results below identify the deck
transformations inherited from `L/K`.

Ramification is deliberately kept out of this module.
-/

open scoped NumberField

namespace Fermat.Irregular.KummerRealFixedField157

noncomputable section

open Polynomial AdjoinRoot
open Fermat.Irregular.TakagiFurtwangler157
open Fermat.Irregular.KummerConjugationDescent157

variable {K : Type*} [Field K] [NumberField K]
  [IsCyclotomicExtension {157} ℚ K]

local instance : Fact (Nat.Prime 157) := ⟨by norm_num⟩

local instance : NumberField.IsCMField K :=
  IsCyclotomicExtension.IsCMField (p := 157) K (by norm_num)

local notation3 "K⁺" => NumberField.maximalRealSubfield K

variable {a : 𝓞 K}
  [hirr : Fact (Irreducible (X ^ 157 - C (a : K)))]

local notation3 "L" => KummerExtension157 K a

local instance : Field L := AdjoinRoot.instField
local instance : Algebra K L := inferInstance
local instance : Module.Finite K L :=
  (monic_X_pow_sub_C (a : K) (by norm_num : 157 ≠ 0)).finite_adjoinRoot
local instance algebraKummerOverReal157 : Algebra K⁺ L :=
  Algebra.restrictScalars K⁺ K L
local instance scalarTowerKummerOverReal157 : IsScalarTower K⁺ K L :=
  IsScalarTower.of_algebraMap_eq fun _ => rfl
local instance finiteDimensionalKummerOverReal157 : FiniteDimensional K⁺ L :=
  FiniteDimensional.trans K⁺ K L

local instance : IsGalois K L := by
  obtain ⟨ζ, hζ⟩ :=
    IsCyclotomicExtension.exists_isPrimitiveRoot ℚ K
      (show 157 ∈ ({157} : Set ℕ) by simp)
      (by norm_num : 157 ≠ 0)
  exact kummerExtension157_isGalois hζ hirr.out

/-- The order-two subgroup generated by the lifted conjugation. -/
noncomputable def conjugationSubgroup157
    (hanti : ConjugationAntiInvariantWitness157 a) :
    Subgroup (L ≃ₐ[K⁺] L) :=
  Subgroup.zpowers (conjugationLift157 hanti)

/-- The degree-`157` field over `K⁺` fixed by lifted conjugation. -/
noncomputable def realFixedField157
    (hanti : ConjugationAntiInvariantWitness157 a) :
    IntermediateField K⁺ L :=
  IntermediateField.fixedField (conjugationSubgroup157 hanti)

theorem conjugationLift157_ne_one
    (hanti : ConjugationAntiInvariantWitness157 a) :
    conjugationLift157 hanti ≠ (1 : L ≃ₐ[K⁺] L) := by
  intro htau
  apply NumberField.IsCMField.complexConj_ne_one K
  ext x
  apply (algebraMap K L).injective
  have hx := DFunLike.congr_fun htau (algebraMap K L x)
  simpa only [conjugationLift157_algebraMap, one_apply] using hx

theorem orderOf_conjugationLift157
    (hanti : ConjugationAntiInvariantWitness157 a) :
    orderOf (conjugationLift157 hanti) = 2 :=
  orderOf_eq_prime_iff.mpr
    ⟨conjugationLift157_sq (a := a) hanti,
      conjugationLift157_ne_one (a := a) hanti⟩

theorem natCard_conjugationSubgroup157
    (hanti : ConjugationAntiInvariantWitness157 a) :
    Nat.card (conjugationSubgroup157 hanti) = 2 := by
  rw [conjugationSubgroup157, Nat.card_zpowers,
    orderOf_conjugationLift157 (a := a) hanti]

/-- Membership in the fixed field is equivalent to being fixed by its
single generating involution. -/
@[simp]
theorem mem_realFixedField157_iff
    (hanti : ConjugationAntiInvariantWitness157 a) {x : L} :
    x ∈ realFixedField157 hanti ↔ conjugationLift157 hanti x = x := by
  rw [realFixedField157, IntermediateField.mem_fixedField_iff,
    conjugationSubgroup157, Subgroup.forall_mem_zpowers]
  simpa only [AlgEquiv.smul_def, MulAction.mem_fixedBy] using
    (MulAction.mem_fixedBy_zpowers_iff_mem_fixedBy
      (G := L ≃ₐ[K⁺] L) (α := L)
      (g := conjugationLift157 hanti) (a := x))

/-- The Kummer field has degree `314 = 2 * 157` over the maximal real
subfield. -/
theorem finrank_kummerExtension157_over_real :
    Module.finrank K⁺ L = 314 := by
  obtain ⟨ζ, hζ⟩ :=
    IsCyclotomicExtension.exists_isPrimitiveRoot ℚ K
      (show 157 ∈ ({157} : Set ℕ) by simp)
      (by norm_num : 157 ≠ 0)
  calc
    Module.finrank K⁺ L =
        Module.finrank K⁺ K * Module.finrank K L :=
      (Module.finrank_mul_finrank K⁺ K L).symm
    _ = 2 * 157 := by
      rw [Algebra.IsQuadraticExtension.finrank_eq_two K⁺ K,
        kummerExtension157_finrank hζ hirr.out]
    _ = 314 := by norm_num

/-- The extension from the fixed field up to the Kummer field is
quadratic. -/
theorem finrank_over_realFixedField157
    (hanti : ConjugationAntiInvariantWitness157 a) :
    Module.finrank (realFixedField157 hanti) L = 2 := by
  letI : FiniteDimensional K⁺ L :=
    finiteDimensionalKummerOverReal157 (K := K) (a := a)
  change
    Module.finrank
        (IntermediateField.fixedField (conjugationSubgroup157 hanti)) L = 2
  calc
    Module.finrank
        (IntermediateField.fixedField (conjugationSubgroup157 hanti)) L =
        Nat.card (conjugationSubgroup157 hanti) :=
      @IntermediateField.finrank_fixedField_eq_card
        K⁺ _ L _ (algebraKummerOverReal157 (K := K) (a := a))
        (conjugationSubgroup157 hanti)
        (finiteDimensionalKummerOverReal157 (K := K) (a := a))
    _ = 2 := natCard_conjugationSubgroup157 (a := a) hanti

/-- The fixed field has the desired prime degree over the maximal real
subfield. -/
theorem finrank_realFixedField157
    (hanti : ConjugationAntiInvariantWitness157 a) :
    Module.finrank K⁺ (realFixedField157 hanti) = 157 := by
  letI : IsScalarTower K⁺ (realFixedField157 hanti) L :=
    IntermediateField.isScalarTower_mid' (realFixedField157 hanti)
  have htower :=
    Module.finrank_mul_finrank K⁺ (realFixedField157 hanti) L
  rw [finrank_over_realFixedField157 (a := a) hanti,
    finrank_kummerExtension157_over_real (a := a)] at htower
  omega

omit [NumberField K] [IsCyclotomicExtension {157} ℚ K] in
/-- Forgetting from `K`-linearity to `K⁺`-linearity is injective on
automorphisms. -/
theorem restrictKAutToReal157_injective :
    Function.Injective
      (restrictKAutToReal157 :
        (L ≃ₐ[K] L) → (L ≃ₐ[K⁺] L)) := by
  intro σ ρ h
  apply AlgEquiv.ext
  intro x
  exact DFunLike.congr_fun h x

/-- Lifted conjugation is not a `K`-linear deck transformation. -/
theorem conjugationLift157_ne_restrictKAut
    (hanti : ConjugationAntiInvariantWitness157 a)
    (σ : L ≃ₐ[K] L) :
    conjugationLift157 hanti ≠ restrictKAutToReal157 σ := by
  intro h
  apply NumberField.IsCMField.complexConj_ne_one K
  ext x
  apply (algebraMap K L).injective
  calc
    algebraMap K L
        (NumberField.IsCMField.complexConj K x) =
        conjugationLift157 hanti (algebraMap K L x) := by
      rw [conjugationLift157_algebraMap]
    _ = restrictKAutToReal157 σ (algebraMap K L x) := by rw [h]
    _ = algebraMap K L x := σ.commutes x
    _ = algebraMap K L ((1 : K ≃ₐ[K⁺] K) x) := by simp

/-- The two cosets supplied by the deck group and lifted conjugation. -/
noncomputable def realAutCosetMap157
    (hanti : ConjugationAntiInvariantWitness157 a) :
    Bool × (L ≃ₐ[K] L) → (L ≃ₐ[K⁺] L)
  | (false, σ) => restrictKAutToReal157 σ
  | (true, σ) =>
      conjugationLift157 hanti * restrictKAutToReal157 σ

theorem realAutCosetMap157_injective
    (hanti : ConjugationAntiInvariantWitness157 a) :
    Function.Injective (realAutCosetMap157 hanti) := by
  rintro ⟨b, σ⟩ ⟨c, ρ⟩ h
  cases b <;> cases c
  · simp only [realAutCosetMap157] at h
    have hσρ := restrictKAutToReal157_injective (a := a) h
    exact Prod.ext rfl hσρ
  · simp only [realAutCosetMap157] at h
    exfalso
    apply conjugationLift157_ne_restrictKAut (a := a) hanti
      (σ * ρ⁻¹)
    calc
      conjugationLift157 hanti =
          restrictKAutToReal157 σ *
            (restrictKAutToReal157 ρ)⁻¹ := by
        rw [h, mul_assoc, mul_inv_cancel, mul_one]
      _ = restrictKAutToReal157 (σ * ρ⁻¹) := by
        ext x
        rfl
  · simp only [realAutCosetMap157] at h
    exfalso
    apply conjugationLift157_ne_restrictKAut (a := a) hanti
      (ρ * σ⁻¹)
    calc
      conjugationLift157 hanti =
          restrictKAutToReal157 ρ *
            (restrictKAutToReal157 σ)⁻¹ := by
        rw [← h, mul_assoc, mul_inv_cancel, mul_one]
      _ = restrictKAutToReal157 (ρ * σ⁻¹) := by
        ext x
        rfl
  · simp only [realAutCosetMap157] at h
    have hrs :
        restrictKAutToReal157 σ = restrictKAutToReal157 ρ :=
      mul_left_cancel h
    have hσρ := restrictKAutToReal157_injective (a := a) hrs
    exact Prod.ext rfl hσρ

theorem natCard_kummerKAut157 :
    Nat.card (L ≃ₐ[K] L) = 157 := by
  rw [IsGalois.card_aut_eq_finrank]
  obtain ⟨ζ, hζ⟩ :=
    IsCyclotomicExtension.exists_isPrimitiveRoot ℚ K
      (show 157 ∈ ({157} : Set ℕ) by simp)
      (by norm_num : 157 ≠ 0)
  exact kummerExtension157_finrank hζ hirr.out

/-- There are exactly `314` automorphisms over the real subfield.  The
lower bound is provided by the two explicit cosets; the universal
linear-independence bound supplies the upper bound. -/
theorem natCard_kummerRealAut157
    (hanti : ConjugationAntiInvariantWitness157 a) :
    Nat.card (L ≃ₐ[K⁺] L) = 314 := by
  letI : FiniteDimensional K⁺ L :=
    finiteDimensionalKummerOverReal157 (K := K) (a := a)
  letI : Fintype (L ≃ₐ[K⁺] L) :=
    @AlgEquiv.fintype K⁺ L _ _
      (algebraKummerOverReal157 (K := K) (a := a))
      (finiteDimensionalKummerOverReal157 (K := K) (a := a))
  have hlower :
      Nat.card (Bool × (L ≃ₐ[K] L)) ≤
        Nat.card (L ≃ₐ[K⁺] L) :=
    Nat.card_le_card_of_injective
      (realAutCosetMap157 hanti)
      (realAutCosetMap157_injective (a := a) hanti)
  have hlower' : 314 ≤ Nat.card (L ≃ₐ[K⁺] L) := by
    rw [Nat.card_prod, natCard_kummerKAut157 (a := a)] at hlower
    norm_num at hlower ⊢
    exact hlower
  have hupper :
      Nat.card (L ≃ₐ[K⁺] L) ≤ Module.finrank K⁺ L := by
    simpa only [Nat.card_eq_fintype_card] using
      (@AlgEquiv.card_le K⁺ L _ _
        (algebraKummerOverReal157 (K := K) (a := a))
        (finiteDimensionalKummerOverReal157 (K := K) (a := a)))
  rw [finrank_kummerExtension157_over_real (a := a)] at hupper
  omega

/-- The full Kummer field is Galois over the maximal real subfield. -/
theorem isGalois_kummerExtension157_over_real
    (hanti : ConjugationAntiInvariantWitness157 a) :
    IsGalois K⁺ L :=
  @IsGalois.of_card_aut_eq_finrank K⁺ _ L _
    (algebraKummerOverReal157 (K := K) (a := a))
    (finiteDimensionalKummerOverReal157 (K := K) (a := a)) <| by
    exact (natCard_kummerRealAut157 (a := a) hanti).trans
      (finrank_kummerExtension157_over_real (a := a)).symm

theorem realAutCosetMap157_surjective
    (hanti : ConjugationAntiInvariantWitness157 a) :
    Function.Surjective (realAutCosetMap157 hanti) := by
  letI : FiniteDimensional K⁺ L :=
    finiteDimensionalKummerOverReal157 (K := K) (a := a)
  letI : Fintype (L ≃ₐ[K⁺] L) :=
    @AlgEquiv.fintype K⁺ L _ _
      (algebraKummerOverReal157 (K := K) (a := a))
      (finiteDimensionalKummerOverReal157 (K := K) (a := a))
  exact
    ((Nat.bijective_iff_injective_and_card
      (realAutCosetMap157 hanti)).2
      ⟨realAutCosetMap157_injective (a := a) hanti, by
        rw [Nat.card_prod, natCard_kummerKAut157 (a := a),
          natCard_kummerRealAut157 (a := a) hanti]
        norm_num⟩).2

/-- Lifted conjugation is central in the full Galois group over `K⁺`. -/
theorem conjugationLift157_commute_realAut
    (hanti : ConjugationAntiInvariantWitness157 a)
    (σ : L ≃ₐ[K⁺] L) :
    Commute (conjugationLift157 hanti) σ := by
  obtain ⟨⟨b, ρ⟩, rfl⟩ :=
    realAutCosetMap157_surjective (a := a) hanti σ
  cases b
  · exact conjugationLift157_commute_kAut (a := a) hanti ρ
  · exact (Commute.refl (conjugationLift157 hanti)).mul_right
      (conjugationLift157_commute_kAut (a := a) hanti ρ)

/-- The subgroup generated by lifted conjugation is normal. -/
theorem conjugationSubgroup157_normal
    (hanti : ConjugationAntiInvariantWitness157 a) :
    Subgroup.Normal (conjugationSubgroup157 hanti) where
  conj_mem h hh σ := by
    obtain ⟨n, rfl⟩ := Subgroup.mem_zpowers_iff.mp hh
    have hcomm :=
      (conjugationLift157_commute_realAut (a := a) hanti σ).zpow_left n
    rw [← hcomm.eq, mul_assoc, mul_inv_cancel, mul_one]
    exact Subgroup.zpow_mem_zpowers _ _

/-- The degree-`157` real fixed field is Galois over `K⁺`. -/
theorem isGalois_realFixedField157
    (hanti : ConjugationAntiInvariantWitness157 a) :
    IsGalois K⁺ (realFixedField157 hanti) := by
  letI : IsGalois K⁺ L :=
    isGalois_kummerExtension157_over_real (a := a) hanti
  letI : Subgroup.Normal (conjugationSubgroup157 hanti) :=
    conjugationSubgroup157_normal (a := a) hanti
  exact IsGalois.of_fixedField_normal_subgroup
    (conjugationSubgroup157 hanti)

theorem natCard_realFixedFieldAut157
    (hanti : ConjugationAntiInvariantWitness157 a) :
    Nat.card
      ((realFixedField157 hanti) ≃ₐ[K⁺]
        (realFixedField157 hanti)) = 157 := by
  letI : FiniteDimensional K⁺ (realFixedField157 hanti) :=
    FiniteDimensional.of_finrank_pos <| by
      rw [finrank_realFixedField157 (a := a) hanti]
      norm_num
  letI : IsGalois K⁺ (realFixedField157 hanti) :=
    isGalois_realFixedField157 (a := a) hanti
  rw [IsGalois.card_aut_eq_finrank,
    finrank_realFixedField157 (a := a) hanti]

/-- The descended real extension has cyclic Galois group of order `157`. -/
theorem isCyclic_realFixedFieldAut157
    (hanti : ConjugationAntiInvariantWitness157 a) :
    IsCyclic
      ((realFixedField157 hanti) ≃ₐ[K⁺]
        (realFixedField157 hanti)) := by
  exact isCyclic_of_prime_card
    (natCard_realFixedFieldAut157 (a := a) hanti)

end

end Fermat.Irregular.KummerRealFixedField157
