import Fermat.Irregular.KummerConjugationDescentPrime

set_option maxRecDepth 50000

/-!
# The prime-generic real fixed field of a Kummer extension

Let `L/K` be a degree-`p` Kummer extension attached to an
anti-invariant radicand, and let `τ` be the lifted complex conjugation.
This module defines the fixed field

`M = L ^ ⟨τ⟩`

over the maximal real subfield `K⁺`.  It proves `[L : M] = 2`,
`[M : K⁺] = p`, and the Galois/cyclic deck-transformation package used
by Takagi reflection.  Ramification is deliberately kept separate.
-/

open scoped NumberField

namespace Fermat.Irregular.KummerRealFixedFieldPrime

noncomputable section

open Polynomial AdjoinRoot
open Fermat.Irregular.TakagiFurtwanglerPrime
open Fermat.Irregular.KummerConjugationDescentPrime

variable {K : Type*} {p : ℕ} [Fact p.Prime]
  [Field K] [NumberField K] [NumberField.IsCMField K]
  [IsCyclotomicExtension {p} ℚ K]

local notation3 "K⁺" => NumberField.maximalRealSubfield K

variable {a : 𝓞 K}
  [hirr : Fact (Irreducible (X ^ p - C (a : K)))]

local notation3 "L" => KummerExtension (p := p) K a

local instance : Field L := AdjoinRoot.instField
local instance : Algebra K L := inferInstance
local instance : Module.Finite K L :=
  (monic_X_pow_sub_C (a : K)
    (Fact.out : Nat.Prime p).ne_zero).finite_adjoinRoot
local instance algebraKummerOverReal : Algebra K⁺ L :=
  Algebra.restrictScalars K⁺ K L
local instance scalarTowerKummerOverReal : IsScalarTower K⁺ K L :=
  IsScalarTower.of_algebraMap_eq fun _ => rfl
local instance finiteDimensionalKummerOverReal : FiniteDimensional K⁺ L :=
  FiniteDimensional.trans K⁺ K L

local instance : IsGalois K L := by
  obtain ⟨ζ, hζ⟩ :=
    IsCyclotomicExtension.exists_isPrimitiveRoot ℚ K
      (show p ∈ ({p} : Set ℕ) by simp)
      (Fact.out : Nat.Prime p).ne_zero
  exact kummerExtension_isGalois hζ hirr.out

/-- The order-two subgroup generated by the lifted conjugation. -/
noncomputable def conjugationSubgroup
    (hanti : ConjugationAntiInvariantWitness (p := p) a) :
    Subgroup (L ≃ₐ[K⁺] L) :=
  Subgroup.zpowers (conjugationLift hanti)

/-- The degree-`p` field over `K⁺` fixed by lifted conjugation. -/
noncomputable def realFixedField
    (hanti : ConjugationAntiInvariantWitness (p := p) a) :
    IntermediateField K⁺ L :=
  IntermediateField.fixedField (conjugationSubgroup hanti)

theorem conjugationLift_ne_one
    (hanti : ConjugationAntiInvariantWitness (p := p) a) :
    conjugationLift hanti ≠ (1 : L ≃ₐ[K⁺] L) := by
  intro htau
  apply NumberField.IsCMField.complexConj_ne_one K
  ext x
  change NumberField.IsCMField.complexConj K x = x
  apply (algebraMap K L).injective
  have hx := DFunLike.congr_fun htau (algebraMap K L x)
  change
    conjugationLift hanti (algebraMap K L x) =
      algebraMap K L x at hx
  simpa only [conjugationLift_algebraMap] using hx

theorem orderOf_conjugationLift
    (hanti : ConjugationAntiInvariantWitness (p := p) a) :
    orderOf (conjugationLift hanti) = 2 :=
  orderOf_eq_prime_iff.mpr
    ⟨conjugationLift_sq (a := a) hanti,
      conjugationLift_ne_one (a := a) hanti⟩

theorem natCard_conjugationSubgroup
    (hanti : ConjugationAntiInvariantWitness (p := p) a) :
    Nat.card (conjugationSubgroup hanti) = 2 := by
  rw [conjugationSubgroup, Nat.card_zpowers,
    orderOf_conjugationLift (a := a) hanti]

/-- Membership in the fixed field is equivalent to being fixed by its
single generating involution. -/
@[simp]
theorem mem_realFixedField_iff
    (hanti : ConjugationAntiInvariantWitness (p := p) a) {x : L} :
    x ∈ realFixedField hanti ↔ conjugationLift hanti x = x := by
  rw [realFixedField, IntermediateField.mem_fixedField_iff,
    conjugationSubgroup, Subgroup.forall_mem_zpowers]
  simpa only [AlgEquiv.smul_def, MulAction.mem_fixedBy] using
    (MulAction.mem_fixedBy_zpowers_iff_mem_fixedBy
      (G := L ≃ₐ[K⁺] L) (α := L)
      (g := conjugationLift hanti) (a := x))

/-- The Kummer field has degree `2 * p` over the maximal real subfield. -/
theorem finrank_kummerExtension_over_real :
    Module.finrank K⁺ L = 2 * p := by
  obtain ⟨ζ, hζ⟩ :=
    IsCyclotomicExtension.exists_isPrimitiveRoot ℚ K
      (show p ∈ ({p} : Set ℕ) by simp)
      (Fact.out : Nat.Prime p).ne_zero
  calc
    Module.finrank K⁺ L =
        Module.finrank K⁺ K * Module.finrank K L :=
      (Module.finrank_mul_finrank K⁺ K L).symm
    _ = 2 * p := by
      rw [Algebra.IsQuadraticExtension.finrank_eq_two K⁺ K,
        kummerExtension_finrank hζ hirr.out]

/-- The extension from the fixed field up to the Kummer field is
quadratic. -/
theorem finrank_over_realFixedField
    (hanti : ConjugationAntiInvariantWitness (p := p) a) :
    Module.finrank (realFixedField hanti) L = 2 := by
  letI : FiniteDimensional K⁺ L :=
    finiteDimensionalKummerOverReal (K := K) (a := a)
  change
    Module.finrank
        (IntermediateField.fixedField (conjugationSubgroup hanti)) L = 2
  calc
    Module.finrank
        (IntermediateField.fixedField (conjugationSubgroup hanti)) L =
        Nat.card (conjugationSubgroup hanti) :=
      @IntermediateField.finrank_fixedField_eq_card
        K⁺ _ L _ (algebraKummerOverReal (K := K) (a := a))
        (conjugationSubgroup hanti)
        (finiteDimensionalKummerOverReal (K := K) (a := a))
    _ = 2 := natCard_conjugationSubgroup (a := a) hanti

/-- The fixed field has the desired prime degree over the maximal real
subfield. -/
theorem finrank_realFixedField
    (hanti : ConjugationAntiInvariantWitness (p := p) a) :
    Module.finrank K⁺ (realFixedField hanti) = p := by
  letI : IsScalarTower K⁺ (realFixedField hanti) L :=
    IntermediateField.isScalarTower_mid' (realFixedField hanti)
  have htower :=
    Module.finrank_mul_finrank K⁺ (realFixedField hanti) L
  rw [finrank_over_realFixedField (a := a) hanti,
    finrank_kummerExtension_over_real (a := a)] at htower
  omega

omit [NumberField K] [IsCyclotomicExtension {p} ℚ K] in
/-- Forgetting from `K`-linearity to `K⁺`-linearity is injective on
automorphisms. -/
theorem restrictKAutToReal_injective :
    Function.Injective
      (restrictKAutToReal :
        (L ≃ₐ[K] L) → (L ≃ₐ[K⁺] L)) := by
  intro σ ρ h
  apply AlgEquiv.ext
  intro x
  exact DFunLike.congr_fun h x

/-- Lifted conjugation is not a `K`-linear deck transformation. -/
theorem conjugationLift_ne_restrictKAut
    (hanti : ConjugationAntiInvariantWitness (p := p) a)
    (σ : L ≃ₐ[K] L) :
    conjugationLift hanti ≠ restrictKAutToReal σ := by
  intro h
  apply NumberField.IsCMField.complexConj_ne_one K
  ext x
  apply (algebraMap K L).injective
  calc
    algebraMap K L
        (NumberField.IsCMField.complexConj K x) =
        conjugationLift hanti (algebraMap K L x) := by
      rw [conjugationLift_algebraMap]
    _ = restrictKAutToReal σ (algebraMap K L x) := by rw [h]
    _ = algebraMap K L x := σ.commutes x
    _ = algebraMap K L ((1 : K ≃ₐ[K⁺] K) x) := by simp

/-- The two cosets supplied by the deck group and lifted conjugation. -/
noncomputable def realAutCosetMap
    (hanti : ConjugationAntiInvariantWitness (p := p) a) :
    Bool × (L ≃ₐ[K] L) → (L ≃ₐ[K⁺] L)
  | (false, σ) => restrictKAutToReal σ
  | (true, σ) =>
      conjugationLift hanti * restrictKAutToReal σ

theorem realAutCosetMap_injective
    (hanti : ConjugationAntiInvariantWitness (p := p) a) :
    Function.Injective (realAutCosetMap hanti) := by
  rintro ⟨b, σ⟩ ⟨c, ρ⟩ h
  cases b <;> cases c
  · simp only [realAutCosetMap] at h
    have hσρ := restrictKAutToReal_injective (a := a) h
    exact Prod.ext rfl hσρ
  · simp only [realAutCosetMap] at h
    exfalso
    apply conjugationLift_ne_restrictKAut (a := a) hanti
      (σ * ρ⁻¹)
    calc
      conjugationLift hanti =
          restrictKAutToReal σ *
            (restrictKAutToReal ρ)⁻¹ := by
        rw [h, mul_assoc, mul_inv_cancel, mul_one]
      _ = restrictKAutToReal (σ * ρ⁻¹) := by
        ext x
        rfl
  · simp only [realAutCosetMap] at h
    exfalso
    apply conjugationLift_ne_restrictKAut (a := a) hanti
      (ρ * σ⁻¹)
    calc
      conjugationLift hanti =
          restrictKAutToReal ρ *
            (restrictKAutToReal σ)⁻¹ := by
        rw [← h, mul_assoc, mul_inv_cancel, mul_one]
      _ = restrictKAutToReal (ρ * σ⁻¹) := by
        ext x
        rfl
  · simp only [realAutCosetMap] at h
    have hrs :
        restrictKAutToReal σ = restrictKAutToReal ρ :=
      mul_left_cancel h
    have hσρ := restrictKAutToReal_injective (a := a) hrs
    exact Prod.ext rfl hσρ

theorem natCard_kummerKAut :
    Nat.card (L ≃ₐ[K] L) = p := by
  rw [IsGalois.card_aut_eq_finrank]
  obtain ⟨ζ, hζ⟩ :=
    IsCyclotomicExtension.exists_isPrimitiveRoot ℚ K
      (show p ∈ ({p} : Set ℕ) by simp)
      (Fact.out : Nat.Prime p).ne_zero
  exact kummerExtension_finrank hζ hirr.out

/-- There are exactly `2 * p` automorphisms over the real subfield.  The
lower bound is provided by the two explicit cosets; the universal
linear-independence bound supplies the upper bound. -/
theorem natCard_kummerRealAut
    (hanti : ConjugationAntiInvariantWitness (p := p) a) :
    Nat.card (L ≃ₐ[K⁺] L) = 2 * p := by
  letI : FiniteDimensional K⁺ L :=
    finiteDimensionalKummerOverReal (K := K) (a := a)
  letI : Fintype (L ≃ₐ[K⁺] L) :=
    @AlgEquiv.fintype K⁺ L _ _
      (algebraKummerOverReal (K := K) (a := a))
      (finiteDimensionalKummerOverReal (K := K) (a := a))
  have hlower :
      Nat.card (Bool × (L ≃ₐ[K] L)) ≤
        Nat.card (L ≃ₐ[K⁺] L) :=
    Nat.card_le_card_of_injective
      (realAutCosetMap hanti)
      (realAutCosetMap_injective (a := a) hanti)
  have hlower' : 2 * p ≤ Nat.card (L ≃ₐ[K⁺] L) := by
    rw [Nat.card_prod, natCard_kummerKAut (a := a)] at hlower
    norm_num at hlower ⊢
    exact hlower
  have hupper :
      Nat.card (L ≃ₐ[K⁺] L) ≤ Module.finrank K⁺ L := by
    have h :=
      @AlgEquiv.card_le K⁺ L _ _
        (algebraKummerOverReal (K := K) (a := a))
        (finiteDimensionalKummerOverReal (K := K) (a := a))
    rw [← Nat.card_eq_fintype_card] at h
    exact h
  rw [finrank_kummerExtension_over_real (a := a)] at hupper
  omega

/-- The full Kummer field is Galois over the maximal real subfield. -/
theorem isGalois_kummerExtension_over_real
    (hanti : ConjugationAntiInvariantWitness (p := p) a) :
    IsGalois K⁺ L :=
  @IsGalois.of_card_aut_eq_finrank K⁺ _ L _
    (algebraKummerOverReal (K := K) (a := a))
    (finiteDimensionalKummerOverReal (K := K) (a := a)) <| by
    exact (natCard_kummerRealAut (a := a) hanti).trans
      (finrank_kummerExtension_over_real (a := a)).symm

theorem realAutCosetMap_surjective
    (hanti : ConjugationAntiInvariantWitness (p := p) a) :
    Function.Surjective (realAutCosetMap hanti) := by
  letI : FiniteDimensional K⁺ L :=
    finiteDimensionalKummerOverReal (K := K) (a := a)
  letI : Fintype (L ≃ₐ[K⁺] L) :=
    @AlgEquiv.fintype K⁺ L _ _
      (algebraKummerOverReal (K := K) (a := a))
      (finiteDimensionalKummerOverReal (K := K) (a := a))
  exact
    ((Nat.bijective_iff_injective_and_card
      (realAutCosetMap hanti)).2
      ⟨realAutCosetMap_injective (a := a) hanti, by
        rw [Nat.card_prod, natCard_kummerKAut (a := a),
          natCard_kummerRealAut (a := a) hanti]
        norm_num⟩).2

/-- Lifted conjugation is central in the full Galois group over `K⁺`. -/
theorem conjugationLift_commute_realAut
    (hanti : ConjugationAntiInvariantWitness (p := p) a)
    (σ : L ≃ₐ[K⁺] L) :
    Commute (conjugationLift hanti) σ := by
  obtain ⟨⟨b, ρ⟩, rfl⟩ :=
    realAutCosetMap_surjective (a := a) hanti σ
  cases b
  · exact conjugationLift_commute_kAut (a := a) hanti ρ
  · exact (Commute.refl (conjugationLift hanti)).mul_right
      (conjugationLift_commute_kAut (a := a) hanti ρ)

/-- The subgroup generated by lifted conjugation is normal. -/
theorem conjugationSubgroup_normal
    (hanti : ConjugationAntiInvariantWitness (p := p) a) :
    Subgroup.Normal (conjugationSubgroup hanti) where
  conj_mem h hh σ := by
    obtain ⟨n, rfl⟩ := Subgroup.mem_zpowers_iff.mp hh
    have hcomm :=
      (conjugationLift_commute_realAut (a := a) hanti σ).zpow_left n
    rw [← hcomm.eq, mul_assoc, mul_inv_cancel, mul_one]
    exact Subgroup.zpow_mem_zpowers _ _

/-- The degree-`p` real fixed field is Galois over `K⁺`. -/
theorem isGalois_realFixedField
    (hanti : ConjugationAntiInvariantWitness (p := p) a) :
    IsGalois K⁺ (realFixedField hanti) := by
  letI : IsGalois K⁺ L :=
    isGalois_kummerExtension_over_real (a := a) hanti
  letI : Subgroup.Normal (conjugationSubgroup hanti) :=
    conjugationSubgroup_normal (a := a) hanti
  exact IsGalois.of_fixedField_normal_subgroup
    (conjugationSubgroup hanti)

theorem natCard_realFixedFieldAut
    (hanti : ConjugationAntiInvariantWitness (p := p) a) :
    Nat.card
      ((realFixedField hanti) ≃ₐ[K⁺]
        (realFixedField hanti)) = p := by
  letI : FiniteDimensional K⁺ (realFixedField hanti) :=
    FiniteDimensional.of_finrank_pos <| by
      rw [finrank_realFixedField (a := a) hanti]
      exact (Fact.out : Nat.Prime p).pos
  letI : IsGalois K⁺ (realFixedField hanti) :=
    isGalois_realFixedField (a := a) hanti
  rw [IsGalois.card_aut_eq_finrank,
    finrank_realFixedField (a := a) hanti]

/-- The descended real extension has cyclic Galois group of order `p`. -/
theorem isCyclic_realFixedFieldAut
    (hanti : ConjugationAntiInvariantWitness (p := p) a) :
    IsCyclic
      ((realFixedField hanti) ≃ₐ[K⁺]
        (realFixedField hanti)) := by
  exact isCyclic_of_prime_card
    (natCard_realFixedFieldAut (a := a) hanti)

end

end Fermat.Irregular.KummerRealFixedFieldPrime
