import Fermat.Irregular.KummerConjugationDescent59

/-!
# The real fixed field of a degree-59 Kummer extension

Let `L/K` be the degree-`59` Kummer extension attached to an
anti-invariant radicand, and let `τ` be the lift of complex conjugation
constructed in `KummerConjugationDescent59`.  This file defines

`M = L ^ ⟨τ⟩`

over the maximal real subfield `K⁺`.  It proves the field-theoretic
package needed by the reflection argument: `[L : M] = 2` and
`[M : K⁺] = 59`.  The remaining results below identify the deck
transformations inherited from `L/K`.

Ramification is deliberately kept out of this module.
-/

open scoped NumberField

namespace Fermat.Irregular.KummerRealFixedField59

noncomputable section

open Polynomial AdjoinRoot
open Fermat.Irregular.TakagiFurtwangler59
open Fermat.Irregular.KummerConjugationDescent59

variable {K : Type*} [Field K] [NumberField K]
  [IsCyclotomicExtension {59} ℚ K]

local instance : Fact (Nat.Prime 59) := ⟨by norm_num⟩

local instance : NumberField.IsCMField K :=
  IsCyclotomicExtension.IsCMField (p := 59) K (by norm_num)

local notation3 "K⁺" => NumberField.maximalRealSubfield K

variable {a : 𝓞 K}
  [hirr : Fact (Irreducible (X ^ 59 - C (a : K)))]

local notation3 "L" => KummerExtension59 K a

local instance : Field L := AdjoinRoot.instField
local instance : Algebra K L := inferInstance
local instance : Module.Finite K L :=
  (monic_X_pow_sub_C (a : K) (by norm_num : 59 ≠ 0)).finite_adjoinRoot
local instance algebraKummerOverReal59 : Algebra K⁺ L :=
  Algebra.restrictScalars K⁺ K L
local instance scalarTowerKummerOverReal59 : IsScalarTower K⁺ K L :=
  IsScalarTower.of_algebraMap_eq fun _ => rfl
local instance finiteDimensionalKummerOverReal59 : FiniteDimensional K⁺ L :=
  FiniteDimensional.trans K⁺ K L

local instance : IsGalois K L := by
  obtain ⟨ζ, hζ⟩ :=
    IsCyclotomicExtension.exists_isPrimitiveRoot ℚ K
      (show 59 ∈ ({59} : Set ℕ) by simp)
      (by norm_num : 59 ≠ 0)
  exact kummerExtension59_isGalois hζ hirr.out

/-- The order-two subgroup generated by the lifted conjugation. -/
noncomputable def conjugationSubgroup59
    (hanti : ConjugationAntiInvariantWitness59 a) :
    Subgroup (L ≃ₐ[K⁺] L) :=
  Subgroup.zpowers (conjugationLift59 hanti)

/-- The degree-`59` field over `K⁺` fixed by lifted conjugation. -/
noncomputable def realFixedField59
    (hanti : ConjugationAntiInvariantWitness59 a) :
    IntermediateField K⁺ L :=
  IntermediateField.fixedField (conjugationSubgroup59 hanti)

theorem conjugationLift59_ne_one
    (hanti : ConjugationAntiInvariantWitness59 a) :
    conjugationLift59 hanti ≠ (1 : L ≃ₐ[K⁺] L) := by
  intro htau
  apply NumberField.IsCMField.complexConj_ne_one K
  ext x
  change NumberField.IsCMField.complexConj K x = x
  apply (algebraMap K L).injective
  have hx := DFunLike.congr_fun htau (algebraMap K L x)
  change
    conjugationLift59 hanti (algebraMap K L x) =
      algebraMap K L x at hx
  simpa only [conjugationLift59_algebraMap] using hx

theorem orderOf_conjugationLift59
    (hanti : ConjugationAntiInvariantWitness59 a) :
    orderOf (conjugationLift59 hanti) = 2 :=
  orderOf_eq_prime_iff.mpr
    ⟨conjugationLift59_sq (a := a) hanti,
      conjugationLift59_ne_one (a := a) hanti⟩

theorem natCard_conjugationSubgroup59
    (hanti : ConjugationAntiInvariantWitness59 a) :
    Nat.card (conjugationSubgroup59 hanti) = 2 := by
  rw [conjugationSubgroup59, Nat.card_zpowers,
    orderOf_conjugationLift59 (a := a) hanti]

/-- Membership in the fixed field is equivalent to being fixed by its
single generating involution. -/
@[simp]
theorem mem_realFixedField59_iff
    (hanti : ConjugationAntiInvariantWitness59 a) {x : L} :
    x ∈ realFixedField59 hanti ↔ conjugationLift59 hanti x = x := by
  rw [realFixedField59, IntermediateField.mem_fixedField_iff,
    conjugationSubgroup59, Subgroup.forall_mem_zpowers]
  simpa only [AlgEquiv.smul_def, MulAction.mem_fixedBy] using
    (MulAction.mem_fixedBy_zpowers_iff_mem_fixedBy
      (G := L ≃ₐ[K⁺] L) (α := L)
      (g := conjugationLift59 hanti) (a := x))

/-- The Kummer field has degree `118 = 2 * 59` over the maximal real
subfield. -/
theorem finrank_kummerExtension59_over_real :
    Module.finrank K⁺ L = 118 := by
  obtain ⟨ζ, hζ⟩ :=
    IsCyclotomicExtension.exists_isPrimitiveRoot ℚ K
      (show 59 ∈ ({59} : Set ℕ) by simp)
      (by norm_num : 59 ≠ 0)
  calc
    Module.finrank K⁺ L =
        Module.finrank K⁺ K * Module.finrank K L :=
      (Module.finrank_mul_finrank K⁺ K L).symm
    _ = 2 * 59 := by
      rw [Algebra.IsQuadraticExtension.finrank_eq_two K⁺ K,
        kummerExtension59_finrank hζ hirr.out]
    _ = 118 := by norm_num

/-- The extension from the fixed field up to the Kummer field is
quadratic. -/
theorem finrank_over_realFixedField59
    (hanti : ConjugationAntiInvariantWitness59 a) :
    Module.finrank (realFixedField59 hanti) L = 2 := by
  letI : FiniteDimensional K⁺ L :=
    finiteDimensionalKummerOverReal59 (K := K) (a := a)
  change
    Module.finrank
        (IntermediateField.fixedField (conjugationSubgroup59 hanti)) L = 2
  calc
    Module.finrank
        (IntermediateField.fixedField (conjugationSubgroup59 hanti)) L =
        Nat.card (conjugationSubgroup59 hanti) :=
      @IntermediateField.finrank_fixedField_eq_card
        K⁺ _ L _ (algebraKummerOverReal59 (K := K) (a := a))
        (conjugationSubgroup59 hanti)
        (finiteDimensionalKummerOverReal59 (K := K) (a := a))
    _ = 2 := natCard_conjugationSubgroup59 (a := a) hanti

/-- The fixed field has the desired prime degree over the maximal real
subfield. -/
theorem finrank_realFixedField59
    (hanti : ConjugationAntiInvariantWitness59 a) :
    Module.finrank K⁺ (realFixedField59 hanti) = 59 := by
  letI : IsScalarTower K⁺ (realFixedField59 hanti) L :=
    IntermediateField.isScalarTower_mid' (realFixedField59 hanti)
  have htower :=
    Module.finrank_mul_finrank K⁺ (realFixedField59 hanti) L
  rw [finrank_over_realFixedField59 (a := a) hanti,
    finrank_kummerExtension59_over_real (a := a)] at htower
  omega

omit [NumberField K] [IsCyclotomicExtension {59} ℚ K] in
/-- Forgetting from `K`-linearity to `K⁺`-linearity is injective on
automorphisms. -/
theorem restrictKAutToReal59_injective :
    Function.Injective
      (restrictKAutToReal59 :
        (L ≃ₐ[K] L) → (L ≃ₐ[K⁺] L)) := by
  intro σ ρ h
  apply AlgEquiv.ext
  intro x
  exact DFunLike.congr_fun h x

/-- Lifted conjugation is not a `K`-linear deck transformation. -/
theorem conjugationLift59_ne_restrictKAut
    (hanti : ConjugationAntiInvariantWitness59 a)
    (σ : L ≃ₐ[K] L) :
    conjugationLift59 hanti ≠ restrictKAutToReal59 σ := by
  intro h
  apply NumberField.IsCMField.complexConj_ne_one K
  ext x
  apply (algebraMap K L).injective
  calc
    algebraMap K L
        (NumberField.IsCMField.complexConj K x) =
        conjugationLift59 hanti (algebraMap K L x) := by
      rw [conjugationLift59_algebraMap]
    _ = restrictKAutToReal59 σ (algebraMap K L x) := by rw [h]
    _ = algebraMap K L x := σ.commutes x
    _ = algebraMap K L ((1 : K ≃ₐ[K⁺] K) x) := by simp

/-- The two cosets supplied by the deck group and lifted conjugation. -/
noncomputable def realAutCosetMap59
    (hanti : ConjugationAntiInvariantWitness59 a) :
    Bool × (L ≃ₐ[K] L) → (L ≃ₐ[K⁺] L)
  | (false, σ) => restrictKAutToReal59 σ
  | (true, σ) =>
      conjugationLift59 hanti * restrictKAutToReal59 σ

theorem realAutCosetMap59_injective
    (hanti : ConjugationAntiInvariantWitness59 a) :
    Function.Injective (realAutCosetMap59 hanti) := by
  rintro ⟨b, σ⟩ ⟨c, ρ⟩ h
  cases b <;> cases c
  · simp only [realAutCosetMap59] at h
    have hσρ := restrictKAutToReal59_injective (a := a) h
    exact Prod.ext rfl hσρ
  · simp only [realAutCosetMap59] at h
    exfalso
    apply conjugationLift59_ne_restrictKAut (a := a) hanti
      (σ * ρ⁻¹)
    calc
      conjugationLift59 hanti =
          restrictKAutToReal59 σ *
            (restrictKAutToReal59 ρ)⁻¹ := by
        rw [h, mul_assoc, mul_inv_cancel, mul_one]
      _ = restrictKAutToReal59 (σ * ρ⁻¹) := by
        ext x
        rfl
  · simp only [realAutCosetMap59] at h
    exfalso
    apply conjugationLift59_ne_restrictKAut (a := a) hanti
      (ρ * σ⁻¹)
    calc
      conjugationLift59 hanti =
          restrictKAutToReal59 ρ *
            (restrictKAutToReal59 σ)⁻¹ := by
        rw [← h, mul_assoc, mul_inv_cancel, mul_one]
      _ = restrictKAutToReal59 (ρ * σ⁻¹) := by
        ext x
        rfl
  · simp only [realAutCosetMap59] at h
    have hrs :
        restrictKAutToReal59 σ = restrictKAutToReal59 ρ :=
      mul_left_cancel h
    have hσρ := restrictKAutToReal59_injective (a := a) hrs
    exact Prod.ext rfl hσρ

theorem natCard_kummerKAut59 :
    Nat.card (L ≃ₐ[K] L) = 59 := by
  rw [IsGalois.card_aut_eq_finrank]
  obtain ⟨ζ, hζ⟩ :=
    IsCyclotomicExtension.exists_isPrimitiveRoot ℚ K
      (show 59 ∈ ({59} : Set ℕ) by simp)
      (by norm_num : 59 ≠ 0)
  exact kummerExtension59_finrank hζ hirr.out

/-- There are exactly `118` automorphisms over the real subfield.  The
lower bound is provided by the two explicit cosets; the universal
linear-independence bound supplies the upper bound. -/
theorem natCard_kummerRealAut59
    (hanti : ConjugationAntiInvariantWitness59 a) :
    Nat.card (L ≃ₐ[K⁺] L) = 118 := by
  letI : FiniteDimensional K⁺ L :=
    finiteDimensionalKummerOverReal59 (K := K) (a := a)
  letI : Fintype (L ≃ₐ[K⁺] L) :=
    @AlgEquiv.fintype K⁺ L _ _
      (algebraKummerOverReal59 (K := K) (a := a))
      (finiteDimensionalKummerOverReal59 (K := K) (a := a))
  have hlower :
      Nat.card (Bool × (L ≃ₐ[K] L)) ≤
        Nat.card (L ≃ₐ[K⁺] L) :=
    Nat.card_le_card_of_injective
      (realAutCosetMap59 hanti)
      (realAutCosetMap59_injective (a := a) hanti)
  have hlower' : 118 ≤ Nat.card (L ≃ₐ[K⁺] L) := by
    rw [Nat.card_prod, natCard_kummerKAut59 (a := a)] at hlower
    norm_num at hlower ⊢
    exact hlower
  have hupper :
      Nat.card (L ≃ₐ[K⁺] L) ≤ Module.finrank K⁺ L := by
    have h :=
      @AlgEquiv.card_le K⁺ L _ _
        (algebraKummerOverReal59 (K := K) (a := a))
        (finiteDimensionalKummerOverReal59 (K := K) (a := a))
    rw [← Nat.card_eq_fintype_card] at h
    exact h
  rw [finrank_kummerExtension59_over_real (a := a)] at hupper
  omega

/-- The full Kummer field is Galois over the maximal real subfield. -/
theorem isGalois_kummerExtension59_over_real
    (hanti : ConjugationAntiInvariantWitness59 a) :
    IsGalois K⁺ L :=
  @IsGalois.of_card_aut_eq_finrank K⁺ _ L _
    (algebraKummerOverReal59 (K := K) (a := a))
    (finiteDimensionalKummerOverReal59 (K := K) (a := a)) <| by
    exact (natCard_kummerRealAut59 (a := a) hanti).trans
      (finrank_kummerExtension59_over_real (a := a)).symm

theorem realAutCosetMap59_surjective
    (hanti : ConjugationAntiInvariantWitness59 a) :
    Function.Surjective (realAutCosetMap59 hanti) := by
  letI : FiniteDimensional K⁺ L :=
    finiteDimensionalKummerOverReal59 (K := K) (a := a)
  letI : Fintype (L ≃ₐ[K⁺] L) :=
    @AlgEquiv.fintype K⁺ L _ _
      (algebraKummerOverReal59 (K := K) (a := a))
      (finiteDimensionalKummerOverReal59 (K := K) (a := a))
  exact
    ((Nat.bijective_iff_injective_and_card
      (realAutCosetMap59 hanti)).2
      ⟨realAutCosetMap59_injective (a := a) hanti, by
        rw [Nat.card_prod, natCard_kummerKAut59 (a := a),
          natCard_kummerRealAut59 (a := a) hanti]
        norm_num⟩).2

/-- Lifted conjugation is central in the full Galois group over `K⁺`. -/
theorem conjugationLift59_commute_realAut
    (hanti : ConjugationAntiInvariantWitness59 a)
    (σ : L ≃ₐ[K⁺] L) :
    Commute (conjugationLift59 hanti) σ := by
  obtain ⟨⟨b, ρ⟩, rfl⟩ :=
    realAutCosetMap59_surjective (a := a) hanti σ
  cases b
  · exact conjugationLift59_commute_kAut (a := a) hanti ρ
  · exact (Commute.refl (conjugationLift59 hanti)).mul_right
      (conjugationLift59_commute_kAut (a := a) hanti ρ)

/-- The subgroup generated by lifted conjugation is normal. -/
theorem conjugationSubgroup59_normal
    (hanti : ConjugationAntiInvariantWitness59 a) :
    Subgroup.Normal (conjugationSubgroup59 hanti) where
  conj_mem h hh σ := by
    obtain ⟨n, rfl⟩ := Subgroup.mem_zpowers_iff.mp hh
    have hcomm :=
      (conjugationLift59_commute_realAut (a := a) hanti σ).zpow_left n
    rw [← hcomm.eq, mul_assoc, mul_inv_cancel, mul_one]
    exact Subgroup.zpow_mem_zpowers _ _

/-- The degree-`59` real fixed field is Galois over `K⁺`. -/
theorem isGalois_realFixedField59
    (hanti : ConjugationAntiInvariantWitness59 a) :
    IsGalois K⁺ (realFixedField59 hanti) := by
  letI : IsGalois K⁺ L :=
    isGalois_kummerExtension59_over_real (a := a) hanti
  letI : Subgroup.Normal (conjugationSubgroup59 hanti) :=
    conjugationSubgroup59_normal (a := a) hanti
  exact IsGalois.of_fixedField_normal_subgroup
    (conjugationSubgroup59 hanti)

theorem natCard_realFixedFieldAut59
    (hanti : ConjugationAntiInvariantWitness59 a) :
    Nat.card
      ((realFixedField59 hanti) ≃ₐ[K⁺]
        (realFixedField59 hanti)) = 59 := by
  letI : FiniteDimensional K⁺ (realFixedField59 hanti) :=
    FiniteDimensional.of_finrank_pos <| by
      rw [finrank_realFixedField59 (a := a) hanti]
      norm_num
  letI : IsGalois K⁺ (realFixedField59 hanti) :=
    isGalois_realFixedField59 (a := a) hanti
  rw [IsGalois.card_aut_eq_finrank,
    finrank_realFixedField59 (a := a) hanti]

/-- The descended real extension has cyclic Galois group of order `59`. -/
theorem isCyclic_realFixedFieldAut59
    (hanti : ConjugationAntiInvariantWitness59 a) :
    IsCyclic
      ((realFixedField59 hanti) ≃ₐ[K⁺]
        (realFixedField59 hanti)) := by
  exact isCyclic_of_prime_card
    (natCard_realFixedFieldAut59 (a := a) hanti)

end

end Fermat.Irregular.KummerRealFixedField59
