import Fermat.Irregular.KummerConjugationDescent37

/-!
# The real fixed field of a degree-37 Kummer extension

Let `L/K` be the degree-`37` Kummer extension attached to an
anti-invariant radicand, and let `τ` be the lift of complex conjugation
constructed in `KummerConjugationDescent37`.  This file defines

`M = L ^ ⟨τ⟩`

over the maximal real subfield `K⁺`.  It proves the field-theoretic
package needed by the reflection argument: `[L : M] = 2` and
`[M : K⁺] = 37`.  The remaining results below identify the deck
transformations inherited from `L/K`.

Ramification is deliberately kept out of this module.
-/

open scoped NumberField

namespace Fermat.Irregular.KummerRealFixedField37

noncomputable section

open Polynomial AdjoinRoot
open Fermat.Irregular.TakagiFurtwangler37
open Fermat.Irregular.KummerConjugationDescent37

variable {K : Type*} [Field K] [NumberField K]
  [IsCyclotomicExtension {37} ℚ K]

local instance : Fact (Nat.Prime 37) := ⟨by norm_num⟩

local instance : NumberField.IsCMField K :=
  IsCyclotomicExtension.IsCMField (p := 37) K (by norm_num)

local notation3 "K⁺" => NumberField.maximalRealSubfield K

variable {a : 𝓞 K}
  [hirr : Fact (Irreducible (X ^ 37 - C (a : K)))]

local notation3 "L" => KummerExtension37 K a

local instance : Field L := AdjoinRoot.instField
local instance : Algebra K L := inferInstance
local instance : Module.Finite K L :=
  (monic_X_pow_sub_C (a : K) (by norm_num : 37 ≠ 0)).finite_adjoinRoot
local instance algebraKummerOverReal37 : Algebra K⁺ L :=
  Algebra.restrictScalars K⁺ K L
local instance scalarTowerKummerOverReal37 : IsScalarTower K⁺ K L :=
  IsScalarTower.of_algebraMap_eq fun _ => rfl
local instance finiteDimensionalKummerOverReal37 : FiniteDimensional K⁺ L :=
  FiniteDimensional.trans K⁺ K L

local instance : IsGalois K L := by
  obtain ⟨ζ, hζ⟩ :=
    IsCyclotomicExtension.exists_isPrimitiveRoot ℚ K
      (show 37 ∈ ({37} : Set ℕ) by simp)
      (by norm_num : 37 ≠ 0)
  exact kummerExtension37_isGalois hζ hirr.out

/-- The order-two subgroup generated by the lifted conjugation. -/
noncomputable def conjugationSubgroup37
    (hanti : ConjugationAntiInvariantWitness37 a) :
    Subgroup (L ≃ₐ[K⁺] L) :=
  Subgroup.zpowers (conjugationLift37 hanti)

/-- The degree-`37` field over `K⁺` fixed by lifted conjugation. -/
noncomputable def realFixedField37
    (hanti : ConjugationAntiInvariantWitness37 a) :
    IntermediateField K⁺ L :=
  IntermediateField.fixedField (conjugationSubgroup37 hanti)

theorem conjugationLift37_ne_one
    (hanti : ConjugationAntiInvariantWitness37 a) :
    conjugationLift37 hanti ≠ (1 : L ≃ₐ[K⁺] L) := by
  intro htau
  apply NumberField.IsCMField.complexConj_ne_one K
  ext x
  apply (algebraMap K L).injective
  have hx := DFunLike.congr_fun htau (algebraMap K L x)
  simpa only [conjugationLift37_algebraMap, one_apply] using hx

theorem orderOf_conjugationLift37
    (hanti : ConjugationAntiInvariantWitness37 a) :
    orderOf (conjugationLift37 hanti) = 2 :=
  orderOf_eq_prime_iff.mpr
    ⟨conjugationLift37_sq (a := a) hanti,
      conjugationLift37_ne_one (a := a) hanti⟩

theorem natCard_conjugationSubgroup37
    (hanti : ConjugationAntiInvariantWitness37 a) :
    Nat.card (conjugationSubgroup37 hanti) = 2 := by
  rw [conjugationSubgroup37, Nat.card_zpowers,
    orderOf_conjugationLift37 (a := a) hanti]

/-- Membership in the fixed field is equivalent to being fixed by its
single generating involution. -/
@[simp]
theorem mem_realFixedField37_iff
    (hanti : ConjugationAntiInvariantWitness37 a) {x : L} :
    x ∈ realFixedField37 hanti ↔ conjugationLift37 hanti x = x := by
  rw [realFixedField37, IntermediateField.mem_fixedField_iff,
    conjugationSubgroup37, Subgroup.forall_mem_zpowers]
  simpa only [AlgEquiv.smul_def, MulAction.mem_fixedBy] using
    (MulAction.mem_fixedBy_zpowers_iff_mem_fixedBy
      (G := L ≃ₐ[K⁺] L) (α := L)
      (g := conjugationLift37 hanti) (a := x))

/-- The Kummer field has degree `74 = 2 * 37` over the maximal real
subfield. -/
theorem finrank_kummerExtension37_over_real :
    Module.finrank K⁺ L = 74 := by
  obtain ⟨ζ, hζ⟩ :=
    IsCyclotomicExtension.exists_isPrimitiveRoot ℚ K
      (show 37 ∈ ({37} : Set ℕ) by simp)
      (by norm_num : 37 ≠ 0)
  calc
    Module.finrank K⁺ L =
        Module.finrank K⁺ K * Module.finrank K L :=
      (Module.finrank_mul_finrank K⁺ K L).symm
    _ = 2 * 37 := by
      rw [Algebra.IsQuadraticExtension.finrank_eq_two K⁺ K,
        kummerExtension37_finrank hζ hirr.out]
    _ = 74 := by norm_num

/-- The extension from the fixed field up to the Kummer field is
quadratic. -/
theorem finrank_over_realFixedField37
    (hanti : ConjugationAntiInvariantWitness37 a) :
    Module.finrank (realFixedField37 hanti) L = 2 := by
  letI : FiniteDimensional K⁺ L :=
    finiteDimensionalKummerOverReal37 (K := K) (a := a)
  change
    Module.finrank
        (IntermediateField.fixedField (conjugationSubgroup37 hanti)) L = 2
  calc
    Module.finrank
        (IntermediateField.fixedField (conjugationSubgroup37 hanti)) L =
        Nat.card (conjugationSubgroup37 hanti) :=
      @IntermediateField.finrank_fixedField_eq_card
        K⁺ _ L _ (algebraKummerOverReal37 (K := K) (a := a))
        (conjugationSubgroup37 hanti)
        (finiteDimensionalKummerOverReal37 (K := K) (a := a))
    _ = 2 := natCard_conjugationSubgroup37 (a := a) hanti

/-- The fixed field has the desired prime degree over the maximal real
subfield. -/
theorem finrank_realFixedField37
    (hanti : ConjugationAntiInvariantWitness37 a) :
    Module.finrank K⁺ (realFixedField37 hanti) = 37 := by
  letI : IsScalarTower K⁺ (realFixedField37 hanti) L :=
    IntermediateField.isScalarTower_mid' (realFixedField37 hanti)
  have htower :=
    Module.finrank_mul_finrank K⁺ (realFixedField37 hanti) L
  rw [finrank_over_realFixedField37 (a := a) hanti,
    finrank_kummerExtension37_over_real (a := a)] at htower
  omega

omit [NumberField K] [IsCyclotomicExtension {37} ℚ K] in
/-- Forgetting from `K`-linearity to `K⁺`-linearity is injective on
automorphisms. -/
theorem restrictKAutToReal37_injective :
    Function.Injective
      (restrictKAutToReal37 :
        (L ≃ₐ[K] L) → (L ≃ₐ[K⁺] L)) := by
  intro σ ρ h
  apply AlgEquiv.ext
  intro x
  exact DFunLike.congr_fun h x

/-- Lifted conjugation is not a `K`-linear deck transformation. -/
theorem conjugationLift37_ne_restrictKAut
    (hanti : ConjugationAntiInvariantWitness37 a)
    (σ : L ≃ₐ[K] L) :
    conjugationLift37 hanti ≠ restrictKAutToReal37 σ := by
  intro h
  apply NumberField.IsCMField.complexConj_ne_one K
  ext x
  apply (algebraMap K L).injective
  calc
    algebraMap K L
        (NumberField.IsCMField.complexConj K x) =
        conjugationLift37 hanti (algebraMap K L x) := by
      rw [conjugationLift37_algebraMap]
    _ = restrictKAutToReal37 σ (algebraMap K L x) := by rw [h]
    _ = algebraMap K L x := σ.commutes x
    _ = algebraMap K L ((1 : K ≃ₐ[K⁺] K) x) := by simp

/-- The two cosets supplied by the deck group and lifted conjugation. -/
noncomputable def realAutCosetMap37
    (hanti : ConjugationAntiInvariantWitness37 a) :
    Bool × (L ≃ₐ[K] L) → (L ≃ₐ[K⁺] L)
  | (false, σ) => restrictKAutToReal37 σ
  | (true, σ) =>
      conjugationLift37 hanti * restrictKAutToReal37 σ

theorem realAutCosetMap37_injective
    (hanti : ConjugationAntiInvariantWitness37 a) :
    Function.Injective (realAutCosetMap37 hanti) := by
  rintro ⟨b, σ⟩ ⟨c, ρ⟩ h
  cases b <;> cases c
  · simp only [realAutCosetMap37] at h
    have hσρ := restrictKAutToReal37_injective (a := a) h
    exact Prod.ext rfl hσρ
  · simp only [realAutCosetMap37] at h
    exfalso
    apply conjugationLift37_ne_restrictKAut (a := a) hanti
      (σ * ρ⁻¹)
    calc
      conjugationLift37 hanti =
          restrictKAutToReal37 σ *
            (restrictKAutToReal37 ρ)⁻¹ := by
        rw [h, mul_assoc, mul_inv_cancel, mul_one]
      _ = restrictKAutToReal37 (σ * ρ⁻¹) := by
        ext x
        rfl
  · simp only [realAutCosetMap37] at h
    exfalso
    apply conjugationLift37_ne_restrictKAut (a := a) hanti
      (ρ * σ⁻¹)
    calc
      conjugationLift37 hanti =
          restrictKAutToReal37 ρ *
            (restrictKAutToReal37 σ)⁻¹ := by
        rw [← h, mul_assoc, mul_inv_cancel, mul_one]
      _ = restrictKAutToReal37 (ρ * σ⁻¹) := by
        ext x
        rfl
  · simp only [realAutCosetMap37] at h
    have hrs :
        restrictKAutToReal37 σ = restrictKAutToReal37 ρ :=
      mul_left_cancel h
    have hσρ := restrictKAutToReal37_injective (a := a) hrs
    exact Prod.ext rfl hσρ

theorem natCard_kummerKAut37 :
    Nat.card (L ≃ₐ[K] L) = 37 := by
  rw [IsGalois.card_aut_eq_finrank]
  obtain ⟨ζ, hζ⟩ :=
    IsCyclotomicExtension.exists_isPrimitiveRoot ℚ K
      (show 37 ∈ ({37} : Set ℕ) by simp)
      (by norm_num : 37 ≠ 0)
  exact kummerExtension37_finrank hζ hirr.out

/-- There are exactly `74` automorphisms over the real subfield.  The
lower bound is provided by the two explicit cosets; the universal
linear-independence bound supplies the upper bound. -/
theorem natCard_kummerRealAut37
    (hanti : ConjugationAntiInvariantWitness37 a) :
    Nat.card (L ≃ₐ[K⁺] L) = 74 := by
  letI : FiniteDimensional K⁺ L :=
    finiteDimensionalKummerOverReal37 (K := K) (a := a)
  letI : Fintype (L ≃ₐ[K⁺] L) :=
    @AlgEquiv.fintype K⁺ L _ _
      (algebraKummerOverReal37 (K := K) (a := a))
      (finiteDimensionalKummerOverReal37 (K := K) (a := a))
  have hlower :
      Nat.card (Bool × (L ≃ₐ[K] L)) ≤
        Nat.card (L ≃ₐ[K⁺] L) :=
    Nat.card_le_card_of_injective
      (realAutCosetMap37 hanti)
      (realAutCosetMap37_injective (a := a) hanti)
  have hlower' : 74 ≤ Nat.card (L ≃ₐ[K⁺] L) := by
    rw [Nat.card_prod, natCard_kummerKAut37 (a := a)] at hlower
    norm_num at hlower ⊢
    exact hlower
  have hupper :
      Nat.card (L ≃ₐ[K⁺] L) ≤ Module.finrank K⁺ L := by
    simpa only [Nat.card_eq_fintype_card] using
      (@AlgEquiv.card_le K⁺ L _ _
        (algebraKummerOverReal37 (K := K) (a := a))
        (finiteDimensionalKummerOverReal37 (K := K) (a := a)))
  rw [finrank_kummerExtension37_over_real (a := a)] at hupper
  omega

/-- The full Kummer field is Galois over the maximal real subfield. -/
theorem isGalois_kummerExtension37_over_real
    (hanti : ConjugationAntiInvariantWitness37 a) :
    IsGalois K⁺ L :=
  @IsGalois.of_card_aut_eq_finrank K⁺ _ L _
    (algebraKummerOverReal37 (K := K) (a := a))
    (finiteDimensionalKummerOverReal37 (K := K) (a := a)) <| by
    exact (natCard_kummerRealAut37 (a := a) hanti).trans
      (finrank_kummerExtension37_over_real (a := a)).symm

theorem realAutCosetMap37_surjective
    (hanti : ConjugationAntiInvariantWitness37 a) :
    Function.Surjective (realAutCosetMap37 hanti) := by
  letI : FiniteDimensional K⁺ L :=
    finiteDimensionalKummerOverReal37 (K := K) (a := a)
  letI : Fintype (L ≃ₐ[K⁺] L) :=
    @AlgEquiv.fintype K⁺ L _ _
      (algebraKummerOverReal37 (K := K) (a := a))
      (finiteDimensionalKummerOverReal37 (K := K) (a := a))
  exact
    ((Nat.bijective_iff_injective_and_card
      (realAutCosetMap37 hanti)).2
      ⟨realAutCosetMap37_injective (a := a) hanti, by
        rw [Nat.card_prod, natCard_kummerKAut37 (a := a),
          natCard_kummerRealAut37 (a := a) hanti]
        norm_num⟩).2

/-- Lifted conjugation is central in the full Galois group over `K⁺`. -/
theorem conjugationLift37_commute_realAut
    (hanti : ConjugationAntiInvariantWitness37 a)
    (σ : L ≃ₐ[K⁺] L) :
    Commute (conjugationLift37 hanti) σ := by
  obtain ⟨⟨b, ρ⟩, rfl⟩ :=
    realAutCosetMap37_surjective (a := a) hanti σ
  cases b
  · exact conjugationLift37_commute_kAut (a := a) hanti ρ
  · exact (Commute.refl (conjugationLift37 hanti)).mul_right
      (conjugationLift37_commute_kAut (a := a) hanti ρ)

/-- The subgroup generated by lifted conjugation is normal. -/
theorem conjugationSubgroup37_normal
    (hanti : ConjugationAntiInvariantWitness37 a) :
    Subgroup.Normal (conjugationSubgroup37 hanti) where
  conj_mem h hh σ := by
    obtain ⟨n, rfl⟩ := Subgroup.mem_zpowers_iff.mp hh
    have hcomm :=
      (conjugationLift37_commute_realAut (a := a) hanti σ).zpow_left n
    rw [← hcomm.eq, mul_assoc, mul_inv_cancel, mul_one]
    exact Subgroup.zpow_mem_zpowers _ _

/-- The degree-`37` real fixed field is Galois over `K⁺`. -/
theorem isGalois_realFixedField37
    (hanti : ConjugationAntiInvariantWitness37 a) :
    IsGalois K⁺ (realFixedField37 hanti) := by
  letI : IsGalois K⁺ L :=
    isGalois_kummerExtension37_over_real (a := a) hanti
  letI : Subgroup.Normal (conjugationSubgroup37 hanti) :=
    conjugationSubgroup37_normal (a := a) hanti
  exact IsGalois.of_fixedField_normal_subgroup
    (conjugationSubgroup37 hanti)

theorem natCard_realFixedFieldAut37
    (hanti : ConjugationAntiInvariantWitness37 a) :
    Nat.card
      ((realFixedField37 hanti) ≃ₐ[K⁺]
        (realFixedField37 hanti)) = 37 := by
  letI : FiniteDimensional K⁺ (realFixedField37 hanti) :=
    FiniteDimensional.of_finrank_pos <| by
      rw [finrank_realFixedField37 (a := a) hanti]
      norm_num
  letI : IsGalois K⁺ (realFixedField37 hanti) :=
    isGalois_realFixedField37 (a := a) hanti
  rw [IsGalois.card_aut_eq_finrank,
    finrank_realFixedField37 (a := a) hanti]

/-- The descended real extension has cyclic Galois group of order `37`. -/
theorem isCyclic_realFixedFieldAut37
    (hanti : ConjugationAntiInvariantWitness37 a) :
    IsCyclic
      ((realFixedField37 hanti) ≃ₐ[K⁺]
        (realFixedField37 hanti)) := by
  exact isCyclic_of_prime_card
    (natCard_realFixedFieldAut37 (a := a) hanti)

end

end Fermat.Irregular.KummerRealFixedField37
