import Fermat.Irregular.KummerConjugationDescent587

set_option maxRecDepth 50000

/-!
# The real fixed field of a degree-587 Kummer extension

Let `L/K` be the degree-`587` Kummer extension attached to an
anti-invariant radicand, and let `τ` be the lift of complex conjugation
constructed in `KummerConjugationDescent587`.  This file defines

`M = L ^ ⟨τ⟩`

over the maximal real subfield `K⁺`.  It proves the field-theoretic
package needed by the reflection argument: `[L : M] = 2` and
`[M : K⁺] = 587`.  The remaining results below identify the deck
transformations inherited from `L/K`.

Ramification is deliberately kept out of this module.
-/

open scoped NumberField

namespace Fermat.Irregular.KummerRealFixedField587

noncomputable section

open Polynomial AdjoinRoot
open Fermat.Irregular.TakagiFurtwangler587
open Fermat.Irregular.KummerConjugationDescent587

variable {K : Type*} [Field K] [NumberField K]
  [IsCyclotomicExtension {587} ℚ K]

local instance : Fact (Nat.Prime 587) := ⟨by norm_num⟩

local instance : NumberField.IsCMField K :=
  IsCyclotomicExtension.IsCMField (p := 587) K (by norm_num)

local notation3 "K⁺" => NumberField.maximalRealSubfield K

variable {a : 𝓞 K}
  [hirr : Fact (Irreducible (X ^ 587 - C (a : K)))]

local notation3 "L" => KummerExtension587 K a

local instance : Field L := AdjoinRoot.instField
local instance : Algebra K L := inferInstance
local instance : Module.Finite K L :=
  (monic_X_pow_sub_C (a : K) (by norm_num : 587 ≠ 0)).finite_adjoinRoot
local instance algebraKummerOverReal587 : Algebra K⁺ L :=
  Algebra.restrictScalars K⁺ K L
local instance scalarTowerKummerOverReal587 : IsScalarTower K⁺ K L :=
  IsScalarTower.of_algebraMap_eq fun _ => rfl
local instance finiteDimensionalKummerOverReal587 : FiniteDimensional K⁺ L :=
  FiniteDimensional.trans K⁺ K L

local instance : IsGalois K L := by
  obtain ⟨ζ, hζ⟩ :=
    IsCyclotomicExtension.exists_isPrimitiveRoot ℚ K
      (show 587 ∈ ({587} : Set ℕ) by simp)
      (by norm_num : 587 ≠ 0)
  exact kummerExtension587_isGalois hζ hirr.out

/-- The order-two subgroup generated by the lifted conjugation. -/
noncomputable def conjugationSubgroup587
    (hanti : ConjugationAntiInvariantWitness587 a) :
    Subgroup (L ≃ₐ[K⁺] L) :=
  Subgroup.zpowers (conjugationLift587 hanti)

/-- The degree-`587` field over `K⁺` fixed by lifted conjugation. -/
noncomputable def realFixedField587
    (hanti : ConjugationAntiInvariantWitness587 a) :
    IntermediateField K⁺ L :=
  IntermediateField.fixedField (conjugationSubgroup587 hanti)

theorem conjugationLift587_ne_one
    (hanti : ConjugationAntiInvariantWitness587 a) :
    conjugationLift587 hanti ≠ (1 : L ≃ₐ[K⁺] L) := by
  intro htau
  apply NumberField.IsCMField.complexConj_ne_one K
  ext x
  change NumberField.IsCMField.complexConj K x = x
  apply (algebraMap K L).injective
  have hx := DFunLike.congr_fun htau (algebraMap K L x)
  change
    conjugationLift587 hanti (algebraMap K L x) =
      algebraMap K L x at hx
  simpa only [conjugationLift587_algebraMap] using hx

theorem orderOf_conjugationLift587
    (hanti : ConjugationAntiInvariantWitness587 a) :
    orderOf (conjugationLift587 hanti) = 2 :=
  orderOf_eq_prime_iff.mpr
    ⟨conjugationLift587_sq (a := a) hanti,
      conjugationLift587_ne_one (a := a) hanti⟩

theorem natCard_conjugationSubgroup587
    (hanti : ConjugationAntiInvariantWitness587 a) :
    Nat.card (conjugationSubgroup587 hanti) = 2 := by
  rw [conjugationSubgroup587, Nat.card_zpowers,
    orderOf_conjugationLift587 (a := a) hanti]

/-- Membership in the fixed field is equivalent to being fixed by its
single generating involution. -/
@[simp]
theorem mem_realFixedField587_iff
    (hanti : ConjugationAntiInvariantWitness587 a) {x : L} :
    x ∈ realFixedField587 hanti ↔ conjugationLift587 hanti x = x := by
  rw [realFixedField587, IntermediateField.mem_fixedField_iff,
    conjugationSubgroup587, Subgroup.forall_mem_zpowers]
  simpa only [AlgEquiv.smul_def, MulAction.mem_fixedBy] using
    (MulAction.mem_fixedBy_zpowers_iff_mem_fixedBy
      (G := L ≃ₐ[K⁺] L) (α := L)
      (g := conjugationLift587 hanti) (a := x))

/-- The Kummer field has degree `1174 = 2 * 587` over the maximal real
subfield. -/
theorem finrank_kummerExtension587_over_real :
    Module.finrank K⁺ L = 1174 := by
  obtain ⟨ζ, hζ⟩ :=
    IsCyclotomicExtension.exists_isPrimitiveRoot ℚ K
      (show 587 ∈ ({587} : Set ℕ) by simp)
      (by norm_num : 587 ≠ 0)
  calc
    Module.finrank K⁺ L =
        Module.finrank K⁺ K * Module.finrank K L :=
      (Module.finrank_mul_finrank K⁺ K L).symm
    _ = 2 * 587 := by
      rw [Algebra.IsQuadraticExtension.finrank_eq_two K⁺ K,
        kummerExtension587_finrank hζ hirr.out]
    _ = 1174 := by norm_num

/-- The extension from the fixed field up to the Kummer field is
quadratic. -/
theorem finrank_over_realFixedField587
    (hanti : ConjugationAntiInvariantWitness587 a) :
    Module.finrank (realFixedField587 hanti) L = 2 := by
  letI : FiniteDimensional K⁺ L :=
    finiteDimensionalKummerOverReal587 (K := K) (a := a)
  change
    Module.finrank
        (IntermediateField.fixedField (conjugationSubgroup587 hanti)) L = 2
  calc
    Module.finrank
        (IntermediateField.fixedField (conjugationSubgroup587 hanti)) L =
        Nat.card (conjugationSubgroup587 hanti) :=
      @IntermediateField.finrank_fixedField_eq_card
        K⁺ _ L _ (algebraKummerOverReal587 (K := K) (a := a))
        (conjugationSubgroup587 hanti)
        (finiteDimensionalKummerOverReal587 (K := K) (a := a))
    _ = 2 := natCard_conjugationSubgroup587 (a := a) hanti

/-- The fixed field has the desired prime degree over the maximal real
subfield. -/
theorem finrank_realFixedField587
    (hanti : ConjugationAntiInvariantWitness587 a) :
    Module.finrank K⁺ (realFixedField587 hanti) = 587 := by
  letI : IsScalarTower K⁺ (realFixedField587 hanti) L :=
    IntermediateField.isScalarTower_mid' (realFixedField587 hanti)
  have htower :=
    Module.finrank_mul_finrank K⁺ (realFixedField587 hanti) L
  rw [finrank_over_realFixedField587 (a := a) hanti,
    finrank_kummerExtension587_over_real (a := a)] at htower
  omega

omit [NumberField K] [IsCyclotomicExtension {587} ℚ K] in
/-- Forgetting from `K`-linearity to `K⁺`-linearity is injective on
automorphisms. -/
theorem restrictKAutToReal587_injective :
    Function.Injective
      (restrictKAutToReal587 :
        (L ≃ₐ[K] L) → (L ≃ₐ[K⁺] L)) := by
  intro σ ρ h
  apply AlgEquiv.ext
  intro x
  exact DFunLike.congr_fun h x

/-- Lifted conjugation is not a `K`-linear deck transformation. -/
theorem conjugationLift587_ne_restrictKAut
    (hanti : ConjugationAntiInvariantWitness587 a)
    (σ : L ≃ₐ[K] L) :
    conjugationLift587 hanti ≠ restrictKAutToReal587 σ := by
  intro h
  apply NumberField.IsCMField.complexConj_ne_one K
  ext x
  apply (algebraMap K L).injective
  calc
    algebraMap K L
        (NumberField.IsCMField.complexConj K x) =
        conjugationLift587 hanti (algebraMap K L x) := by
      rw [conjugationLift587_algebraMap]
    _ = restrictKAutToReal587 σ (algebraMap K L x) := by rw [h]
    _ = algebraMap K L x := σ.commutes x
    _ = algebraMap K L ((1 : K ≃ₐ[K⁺] K) x) := by simp

/-- The two cosets supplied by the deck group and lifted conjugation. -/
noncomputable def realAutCosetMap587
    (hanti : ConjugationAntiInvariantWitness587 a) :
    Bool × (L ≃ₐ[K] L) → (L ≃ₐ[K⁺] L)
  | (false, σ) => restrictKAutToReal587 σ
  | (true, σ) =>
      conjugationLift587 hanti * restrictKAutToReal587 σ

theorem realAutCosetMap587_injective
    (hanti : ConjugationAntiInvariantWitness587 a) :
    Function.Injective (realAutCosetMap587 hanti) := by
  rintro ⟨b, σ⟩ ⟨c, ρ⟩ h
  cases b <;> cases c
  · simp only [realAutCosetMap587] at h
    have hσρ := restrictKAutToReal587_injective (a := a) h
    exact Prod.ext rfl hσρ
  · simp only [realAutCosetMap587] at h
    exfalso
    apply conjugationLift587_ne_restrictKAut (a := a) hanti
      (σ * ρ⁻¹)
    calc
      conjugationLift587 hanti =
          restrictKAutToReal587 σ *
            (restrictKAutToReal587 ρ)⁻¹ := by
        rw [h, mul_assoc, mul_inv_cancel, mul_one]
      _ = restrictKAutToReal587 (σ * ρ⁻¹) := by
        ext x
        rfl
  · simp only [realAutCosetMap587] at h
    exfalso
    apply conjugationLift587_ne_restrictKAut (a := a) hanti
      (ρ * σ⁻¹)
    calc
      conjugationLift587 hanti =
          restrictKAutToReal587 ρ *
            (restrictKAutToReal587 σ)⁻¹ := by
        rw [← h, mul_assoc, mul_inv_cancel, mul_one]
      _ = restrictKAutToReal587 (ρ * σ⁻¹) := by
        ext x
        rfl
  · simp only [realAutCosetMap587] at h
    have hrs :
        restrictKAutToReal587 σ = restrictKAutToReal587 ρ :=
      mul_left_cancel h
    have hσρ := restrictKAutToReal587_injective (a := a) hrs
    exact Prod.ext rfl hσρ

theorem natCard_kummerKAut587 :
    Nat.card (L ≃ₐ[K] L) = 587 := by
  rw [IsGalois.card_aut_eq_finrank]
  obtain ⟨ζ, hζ⟩ :=
    IsCyclotomicExtension.exists_isPrimitiveRoot ℚ K
      (show 587 ∈ ({587} : Set ℕ) by simp)
      (by norm_num : 587 ≠ 0)
  exact kummerExtension587_finrank hζ hirr.out

/-- There are exactly `1174` automorphisms over the real subfield.  The
lower bound is provided by the two explicit cosets; the universal
linear-independence bound supplies the upper bound. -/
theorem natCard_kummerRealAut587
    (hanti : ConjugationAntiInvariantWitness587 a) :
    Nat.card (L ≃ₐ[K⁺] L) = 1174 := by
  letI : FiniteDimensional K⁺ L :=
    finiteDimensionalKummerOverReal587 (K := K) (a := a)
  letI : Fintype (L ≃ₐ[K⁺] L) :=
    @AlgEquiv.fintype K⁺ L _ _
      (algebraKummerOverReal587 (K := K) (a := a))
      (finiteDimensionalKummerOverReal587 (K := K) (a := a))
  have hlower :
      Nat.card (Bool × (L ≃ₐ[K] L)) ≤
        Nat.card (L ≃ₐ[K⁺] L) :=
    Nat.card_le_card_of_injective
      (realAutCosetMap587 hanti)
      (realAutCosetMap587_injective (a := a) hanti)
  have hlower' : 1174 ≤ Nat.card (L ≃ₐ[K⁺] L) := by
    rw [Nat.card_prod, natCard_kummerKAut587 (a := a)] at hlower
    norm_num at hlower ⊢
    exact hlower
  have hupper :
      Nat.card (L ≃ₐ[K⁺] L) ≤ Module.finrank K⁺ L := by
    have h :=
      @AlgEquiv.card_le K⁺ L _ _
        (algebraKummerOverReal587 (K := K) (a := a))
        (finiteDimensionalKummerOverReal587 (K := K) (a := a))
    rw [← Nat.card_eq_fintype_card] at h
    exact h
  rw [finrank_kummerExtension587_over_real (a := a)] at hupper
  omega

/-- The full Kummer field is Galois over the maximal real subfield. -/
theorem isGalois_kummerExtension587_over_real
    (hanti : ConjugationAntiInvariantWitness587 a) :
    IsGalois K⁺ L :=
  @IsGalois.of_card_aut_eq_finrank K⁺ _ L _
    (algebraKummerOverReal587 (K := K) (a := a))
    (finiteDimensionalKummerOverReal587 (K := K) (a := a)) <| by
    exact (natCard_kummerRealAut587 (a := a) hanti).trans
      (finrank_kummerExtension587_over_real (a := a)).symm

theorem realAutCosetMap587_surjective
    (hanti : ConjugationAntiInvariantWitness587 a) :
    Function.Surjective (realAutCosetMap587 hanti) := by
  letI : FiniteDimensional K⁺ L :=
    finiteDimensionalKummerOverReal587 (K := K) (a := a)
  letI : Fintype (L ≃ₐ[K⁺] L) :=
    @AlgEquiv.fintype K⁺ L _ _
      (algebraKummerOverReal587 (K := K) (a := a))
      (finiteDimensionalKummerOverReal587 (K := K) (a := a))
  exact
    ((Nat.bijective_iff_injective_and_card
      (realAutCosetMap587 hanti)).2
      ⟨realAutCosetMap587_injective (a := a) hanti, by
        rw [Nat.card_prod, natCard_kummerKAut587 (a := a),
          natCard_kummerRealAut587 (a := a) hanti]
        norm_num⟩).2

/-- Lifted conjugation is central in the full Galois group over `K⁺`. -/
theorem conjugationLift587_commute_realAut
    (hanti : ConjugationAntiInvariantWitness587 a)
    (σ : L ≃ₐ[K⁺] L) :
    Commute (conjugationLift587 hanti) σ := by
  obtain ⟨⟨b, ρ⟩, rfl⟩ :=
    realAutCosetMap587_surjective (a := a) hanti σ
  cases b
  · exact conjugationLift587_commute_kAut (a := a) hanti ρ
  · exact (Commute.refl (conjugationLift587 hanti)).mul_right
      (conjugationLift587_commute_kAut (a := a) hanti ρ)

/-- The subgroup generated by lifted conjugation is normal. -/
theorem conjugationSubgroup587_normal
    (hanti : ConjugationAntiInvariantWitness587 a) :
    Subgroup.Normal (conjugationSubgroup587 hanti) where
  conj_mem h hh σ := by
    obtain ⟨n, rfl⟩ := Subgroup.mem_zpowers_iff.mp hh
    have hcomm :=
      (conjugationLift587_commute_realAut (a := a) hanti σ).zpow_left n
    rw [← hcomm.eq, mul_assoc, mul_inv_cancel, mul_one]
    exact Subgroup.zpow_mem_zpowers _ _

/-- The degree-`587` real fixed field is Galois over `K⁺`. -/
theorem isGalois_realFixedField587
    (hanti : ConjugationAntiInvariantWitness587 a) :
    IsGalois K⁺ (realFixedField587 hanti) := by
  letI : IsGalois K⁺ L :=
    isGalois_kummerExtension587_over_real (a := a) hanti
  letI : Subgroup.Normal (conjugationSubgroup587 hanti) :=
    conjugationSubgroup587_normal (a := a) hanti
  exact IsGalois.of_fixedField_normal_subgroup
    (conjugationSubgroup587 hanti)

theorem natCard_realFixedFieldAut587
    (hanti : ConjugationAntiInvariantWitness587 a) :
    Nat.card
      ((realFixedField587 hanti) ≃ₐ[K⁺]
        (realFixedField587 hanti)) = 587 := by
  letI : FiniteDimensional K⁺ (realFixedField587 hanti) :=
    FiniteDimensional.of_finrank_pos <| by
      rw [finrank_realFixedField587 (a := a) hanti]
      norm_num
  letI : IsGalois K⁺ (realFixedField587 hanti) :=
    isGalois_realFixedField587 (a := a) hanti
  rw [IsGalois.card_aut_eq_finrank,
    finrank_realFixedField587 (a := a) hanti]

/-- The descended real extension has cyclic Galois group of order `587`. -/
theorem isCyclic_realFixedFieldAut587
    (hanti : ConjugationAntiInvariantWitness587 a) :
    IsCyclic
      ((realFixedField587 hanti) ≃ₐ[K⁺]
        (realFixedField587 hanti)) := by
  exact isCyclic_of_prime_card
    (natCard_realFixedFieldAut587 (a := a) hanti)

end

end Fermat.Irregular.KummerRealFixedField587
