import Fermat.Irregular.KummerConjugationDescent67

/-!
# The real fixed field of a degree-67 Kummer extension

Let `L/K` be the degree-`67` Kummer extension attached to an
anti-invariant radicand, and let `τ` be the lift of complex conjugation
constructed in `KummerConjugationDescent67`.  This file defines

`M = L ^ ⟨τ⟩`

over the maximal real subfield `K⁺`.  It proves the field-theoretic
package needed by the reflection argument: `[L : M] = 2` and
`[M : K⁺] = 67`.  The remaining results below identify the deck
transformations inherited from `L/K`.

Ramification is deliberately kept out of this module.
-/

open scoped NumberField

namespace Fermat.Irregular.KummerRealFixedField67

noncomputable section

open Polynomial AdjoinRoot
open Fermat.Irregular.TakagiFurtwangler67
open Fermat.Irregular.KummerConjugationDescent67

variable {K : Type*} [Field K] [NumberField K]
  [IsCyclotomicExtension {67} ℚ K]

local instance : Fact (Nat.Prime 67) := ⟨by norm_num⟩

local instance : NumberField.IsCMField K :=
  IsCyclotomicExtension.IsCMField (p := 67) K (by norm_num)

local notation3 "K⁺" => NumberField.maximalRealSubfield K

variable {a : 𝓞 K}
  [hirr : Fact (Irreducible (X ^ 67 - C (a : K)))]

local notation3 "L" => KummerExtension67 K a

local instance : Field L := AdjoinRoot.instField
local instance : Algebra K L := inferInstance
local instance : Module.Finite K L :=
  (monic_X_pow_sub_C (a : K) (by norm_num : 67 ≠ 0)).finite_adjoinRoot
local instance algebraKummerOverReal67 : Algebra K⁺ L :=
  Algebra.restrictScalars K⁺ K L
local instance scalarTowerKummerOverReal67 : IsScalarTower K⁺ K L :=
  IsScalarTower.of_algebraMap_eq fun _ => rfl
local instance finiteDimensionalKummerOverReal67 : FiniteDimensional K⁺ L :=
  FiniteDimensional.trans K⁺ K L

local instance : IsGalois K L := by
  obtain ⟨ζ, hζ⟩ :=
    IsCyclotomicExtension.exists_isPrimitiveRoot ℚ K
      (show 67 ∈ ({67} : Set ℕ) by simp)
      (by norm_num : 67 ≠ 0)
  exact kummerExtension67_isGalois hζ hirr.out

/-- The order-two subgroup generated by the lifted conjugation. -/
noncomputable def conjugationSubgroup67
    (hanti : ConjugationAntiInvariantWitness67 a) :
    Subgroup (L ≃ₐ[K⁺] L) :=
  Subgroup.zpowers (conjugationLift67 hanti)

/-- The degree-`67` field over `K⁺` fixed by lifted conjugation. -/
noncomputable def realFixedField67
    (hanti : ConjugationAntiInvariantWitness67 a) :
    IntermediateField K⁺ L :=
  IntermediateField.fixedField (conjugationSubgroup67 hanti)

theorem conjugationLift67_ne_one
    (hanti : ConjugationAntiInvariantWitness67 a) :
    conjugationLift67 hanti ≠ (1 : L ≃ₐ[K⁺] L) := by
  intro htau
  apply NumberField.IsCMField.complexConj_ne_one K
  ext x
  apply (algebraMap K L).injective
  have hx := DFunLike.congr_fun htau (algebraMap K L x)
  simpa only [conjugationLift67_algebraMap, one_apply] using hx

theorem orderOf_conjugationLift67
    (hanti : ConjugationAntiInvariantWitness67 a) :
    orderOf (conjugationLift67 hanti) = 2 :=
  orderOf_eq_prime_iff.mpr
    ⟨conjugationLift67_sq (a := a) hanti,
      conjugationLift67_ne_one (a := a) hanti⟩

theorem natCard_conjugationSubgroup67
    (hanti : ConjugationAntiInvariantWitness67 a) :
    Nat.card (conjugationSubgroup67 hanti) = 2 := by
  rw [conjugationSubgroup67, Nat.card_zpowers,
    orderOf_conjugationLift67 (a := a) hanti]

/-- Membership in the fixed field is equivalent to being fixed by its
single generating involution. -/
@[simp]
theorem mem_realFixedField67_iff
    (hanti : ConjugationAntiInvariantWitness67 a) {x : L} :
    x ∈ realFixedField67 hanti ↔ conjugationLift67 hanti x = x := by
  rw [realFixedField67, IntermediateField.mem_fixedField_iff,
    conjugationSubgroup67, Subgroup.forall_mem_zpowers]
  simpa only [AlgEquiv.smul_def, MulAction.mem_fixedBy] using
    (MulAction.mem_fixedBy_zpowers_iff_mem_fixedBy
      (G := L ≃ₐ[K⁺] L) (α := L)
      (g := conjugationLift67 hanti) (a := x))

/-- The Kummer field has degree `134 = 2 * 67` over the maximal real
subfield. -/
theorem finrank_kummerExtension67_over_real :
    Module.finrank K⁺ L = 134 := by
  obtain ⟨ζ, hζ⟩ :=
    IsCyclotomicExtension.exists_isPrimitiveRoot ℚ K
      (show 67 ∈ ({67} : Set ℕ) by simp)
      (by norm_num : 67 ≠ 0)
  calc
    Module.finrank K⁺ L =
        Module.finrank K⁺ K * Module.finrank K L :=
      (Module.finrank_mul_finrank K⁺ K L).symm
    _ = 2 * 67 := by
      rw [Algebra.IsQuadraticExtension.finrank_eq_two K⁺ K,
        kummerExtension67_finrank hζ hirr.out]
    _ = 134 := by norm_num

/-- The extension from the fixed field up to the Kummer field is
quadratic. -/
theorem finrank_over_realFixedField67
    (hanti : ConjugationAntiInvariantWitness67 a) :
    Module.finrank (realFixedField67 hanti) L = 2 := by
  letI : FiniteDimensional K⁺ L :=
    finiteDimensionalKummerOverReal67 (K := K) (a := a)
  change
    Module.finrank
        (IntermediateField.fixedField (conjugationSubgroup67 hanti)) L = 2
  calc
    Module.finrank
        (IntermediateField.fixedField (conjugationSubgroup67 hanti)) L =
        Nat.card (conjugationSubgroup67 hanti) :=
      @IntermediateField.finrank_fixedField_eq_card
        K⁺ _ L _ (algebraKummerOverReal67 (K := K) (a := a))
        (conjugationSubgroup67 hanti)
        (finiteDimensionalKummerOverReal67 (K := K) (a := a))
    _ = 2 := natCard_conjugationSubgroup67 (a := a) hanti

/-- The fixed field has the desired prime degree over the maximal real
subfield. -/
theorem finrank_realFixedField67
    (hanti : ConjugationAntiInvariantWitness67 a) :
    Module.finrank K⁺ (realFixedField67 hanti) = 67 := by
  letI : IsScalarTower K⁺ (realFixedField67 hanti) L :=
    IntermediateField.isScalarTower_mid' (realFixedField67 hanti)
  have htower :=
    Module.finrank_mul_finrank K⁺ (realFixedField67 hanti) L
  rw [finrank_over_realFixedField67 (a := a) hanti,
    finrank_kummerExtension67_over_real (a := a)] at htower
  omega

omit [NumberField K] [IsCyclotomicExtension {67} ℚ K] in
/-- Forgetting from `K`-linearity to `K⁺`-linearity is injective on
automorphisms. -/
theorem restrictKAutToReal67_injective :
    Function.Injective
      (restrictKAutToReal67 :
        (L ≃ₐ[K] L) → (L ≃ₐ[K⁺] L)) := by
  intro σ ρ h
  apply AlgEquiv.ext
  intro x
  exact DFunLike.congr_fun h x

/-- Lifted conjugation is not a `K`-linear deck transformation. -/
theorem conjugationLift67_ne_restrictKAut
    (hanti : ConjugationAntiInvariantWitness67 a)
    (σ : L ≃ₐ[K] L) :
    conjugationLift67 hanti ≠ restrictKAutToReal67 σ := by
  intro h
  apply NumberField.IsCMField.complexConj_ne_one K
  ext x
  apply (algebraMap K L).injective
  calc
    algebraMap K L
        (NumberField.IsCMField.complexConj K x) =
        conjugationLift67 hanti (algebraMap K L x) := by
      rw [conjugationLift67_algebraMap]
    _ = restrictKAutToReal67 σ (algebraMap K L x) := by rw [h]
    _ = algebraMap K L x := σ.commutes x
    _ = algebraMap K L ((1 : K ≃ₐ[K⁺] K) x) := by simp

/-- The two cosets supplied by the deck group and lifted conjugation. -/
noncomputable def realAutCosetMap67
    (hanti : ConjugationAntiInvariantWitness67 a) :
    Bool × (L ≃ₐ[K] L) → (L ≃ₐ[K⁺] L)
  | (false, σ) => restrictKAutToReal67 σ
  | (true, σ) =>
      conjugationLift67 hanti * restrictKAutToReal67 σ

theorem realAutCosetMap67_injective
    (hanti : ConjugationAntiInvariantWitness67 a) :
    Function.Injective (realAutCosetMap67 hanti) := by
  rintro ⟨b, σ⟩ ⟨c, ρ⟩ h
  cases b <;> cases c
  · simp only [realAutCosetMap67] at h
    have hσρ := restrictKAutToReal67_injective (a := a) h
    exact Prod.ext rfl hσρ
  · simp only [realAutCosetMap67] at h
    exfalso
    apply conjugationLift67_ne_restrictKAut (a := a) hanti
      (σ * ρ⁻¹)
    calc
      conjugationLift67 hanti =
          restrictKAutToReal67 σ *
            (restrictKAutToReal67 ρ)⁻¹ := by
        rw [h, mul_assoc, mul_inv_cancel, mul_one]
      _ = restrictKAutToReal67 (σ * ρ⁻¹) := by
        ext x
        rfl
  · simp only [realAutCosetMap67] at h
    exfalso
    apply conjugationLift67_ne_restrictKAut (a := a) hanti
      (ρ * σ⁻¹)
    calc
      conjugationLift67 hanti =
          restrictKAutToReal67 ρ *
            (restrictKAutToReal67 σ)⁻¹ := by
        rw [← h, mul_assoc, mul_inv_cancel, mul_one]
      _ = restrictKAutToReal67 (ρ * σ⁻¹) := by
        ext x
        rfl
  · simp only [realAutCosetMap67] at h
    have hrs :
        restrictKAutToReal67 σ = restrictKAutToReal67 ρ :=
      mul_left_cancel h
    have hσρ := restrictKAutToReal67_injective (a := a) hrs
    exact Prod.ext rfl hσρ

theorem natCard_kummerKAut67 :
    Nat.card (L ≃ₐ[K] L) = 67 := by
  rw [IsGalois.card_aut_eq_finrank]
  obtain ⟨ζ, hζ⟩ :=
    IsCyclotomicExtension.exists_isPrimitiveRoot ℚ K
      (show 67 ∈ ({67} : Set ℕ) by simp)
      (by norm_num : 67 ≠ 0)
  exact kummerExtension67_finrank hζ hirr.out

/-- There are exactly `134` automorphisms over the real subfield.  The
lower bound is provided by the two explicit cosets; the universal
linear-independence bound supplies the upper bound. -/
theorem natCard_kummerRealAut67
    (hanti : ConjugationAntiInvariantWitness67 a) :
    Nat.card (L ≃ₐ[K⁺] L) = 134 := by
  letI : FiniteDimensional K⁺ L :=
    finiteDimensionalKummerOverReal67 (K := K) (a := a)
  letI : Fintype (L ≃ₐ[K⁺] L) :=
    @AlgEquiv.fintype K⁺ L _ _
      (algebraKummerOverReal67 (K := K) (a := a))
      (finiteDimensionalKummerOverReal67 (K := K) (a := a))
  have hlower :
      Nat.card (Bool × (L ≃ₐ[K] L)) ≤
        Nat.card (L ≃ₐ[K⁺] L) :=
    Nat.card_le_card_of_injective
      (realAutCosetMap67 hanti)
      (realAutCosetMap67_injective (a := a) hanti)
  have hlower' : 134 ≤ Nat.card (L ≃ₐ[K⁺] L) := by
    rw [Nat.card_prod, natCard_kummerKAut67 (a := a)] at hlower
    norm_num at hlower ⊢
    exact hlower
  have hupper :
      Nat.card (L ≃ₐ[K⁺] L) ≤ Module.finrank K⁺ L := by
    simpa only [Nat.card_eq_fintype_card] using
      (@AlgEquiv.card_le K⁺ L _ _
        (algebraKummerOverReal67 (K := K) (a := a))
        (finiteDimensionalKummerOverReal67 (K := K) (a := a)))
  rw [finrank_kummerExtension67_over_real (a := a)] at hupper
  omega

/-- The full Kummer field is Galois over the maximal real subfield. -/
theorem isGalois_kummerExtension67_over_real
    (hanti : ConjugationAntiInvariantWitness67 a) :
    IsGalois K⁺ L :=
  @IsGalois.of_card_aut_eq_finrank K⁺ _ L _
    (algebraKummerOverReal67 (K := K) (a := a))
    (finiteDimensionalKummerOverReal67 (K := K) (a := a)) <| by
    exact (natCard_kummerRealAut67 (a := a) hanti).trans
      (finrank_kummerExtension67_over_real (a := a)).symm

theorem realAutCosetMap67_surjective
    (hanti : ConjugationAntiInvariantWitness67 a) :
    Function.Surjective (realAutCosetMap67 hanti) := by
  letI : FiniteDimensional K⁺ L :=
    finiteDimensionalKummerOverReal67 (K := K) (a := a)
  letI : Fintype (L ≃ₐ[K⁺] L) :=
    @AlgEquiv.fintype K⁺ L _ _
      (algebraKummerOverReal67 (K := K) (a := a))
      (finiteDimensionalKummerOverReal67 (K := K) (a := a))
  exact
    ((Nat.bijective_iff_injective_and_card
      (realAutCosetMap67 hanti)).2
      ⟨realAutCosetMap67_injective (a := a) hanti, by
        rw [Nat.card_prod, natCard_kummerKAut67 (a := a),
          natCard_kummerRealAut67 (a := a) hanti]
        norm_num⟩).2

/-- Lifted conjugation is central in the full Galois group over `K⁺`. -/
theorem conjugationLift67_commute_realAut
    (hanti : ConjugationAntiInvariantWitness67 a)
    (σ : L ≃ₐ[K⁺] L) :
    Commute (conjugationLift67 hanti) σ := by
  obtain ⟨⟨b, ρ⟩, rfl⟩ :=
    realAutCosetMap67_surjective (a := a) hanti σ
  cases b
  · exact conjugationLift67_commute_kAut (a := a) hanti ρ
  · exact (Commute.refl (conjugationLift67 hanti)).mul_right
      (conjugationLift67_commute_kAut (a := a) hanti ρ)

/-- The subgroup generated by lifted conjugation is normal. -/
theorem conjugationSubgroup67_normal
    (hanti : ConjugationAntiInvariantWitness67 a) :
    Subgroup.Normal (conjugationSubgroup67 hanti) where
  conj_mem h hh σ := by
    obtain ⟨n, rfl⟩ := Subgroup.mem_zpowers_iff.mp hh
    have hcomm :=
      (conjugationLift67_commute_realAut (a := a) hanti σ).zpow_left n
    rw [← hcomm.eq, mul_assoc, mul_inv_cancel, mul_one]
    exact Subgroup.zpow_mem_zpowers _ _

/-- The degree-`67` real fixed field is Galois over `K⁺`. -/
theorem isGalois_realFixedField67
    (hanti : ConjugationAntiInvariantWitness67 a) :
    IsGalois K⁺ (realFixedField67 hanti) := by
  letI : IsGalois K⁺ L :=
    isGalois_kummerExtension67_over_real (a := a) hanti
  letI : Subgroup.Normal (conjugationSubgroup67 hanti) :=
    conjugationSubgroup67_normal (a := a) hanti
  exact IsGalois.of_fixedField_normal_subgroup
    (conjugationSubgroup67 hanti)

theorem natCard_realFixedFieldAut67
    (hanti : ConjugationAntiInvariantWitness67 a) :
    Nat.card
      ((realFixedField67 hanti) ≃ₐ[K⁺]
        (realFixedField67 hanti)) = 67 := by
  letI : FiniteDimensional K⁺ (realFixedField67 hanti) :=
    FiniteDimensional.of_finrank_pos <| by
      rw [finrank_realFixedField67 (a := a) hanti]
      norm_num
  letI : IsGalois K⁺ (realFixedField67 hanti) :=
    isGalois_realFixedField67 (a := a) hanti
  rw [IsGalois.card_aut_eq_finrank,
    finrank_realFixedField67 (a := a) hanti]

/-- The descended real extension has cyclic Galois group of order `67`. -/
theorem isCyclic_realFixedFieldAut67
    (hanti : ConjugationAntiInvariantWitness67 a) :
    IsCyclic
      ((realFixedField67 hanti) ≃ₐ[K⁺]
        (realFixedField67 hanti)) := by
  exact isCyclic_of_prime_card
    (natCard_realFixedFieldAut67 (a := a) hanti)

end

end Fermat.Irregular.KummerRealFixedField67
