import Fermat.Irregular.KummerConjugationDescent491

set_option maxRecDepth 50000

/-!
# The real fixed field of a degree-491 Kummer extension

Let `L/K` be the degree-`491` Kummer extension attached to an
anti-invariant radicand, and let `τ` be the lift of complex conjugation
constructed in `KummerConjugationDescent491`.  This file defines

`M = L ^ ⟨τ⟩`

over the maximal real subfield `K⁺`.  It proves the field-theoretic
package needed by the reflection argument: `[L : M] = 2` and
`[M : K⁺] = 491`.  The remaining results below identify the deck
transformations inherited from `L/K`.

Ramification is deliberately kept out of this module.
-/

open scoped NumberField

namespace Fermat.Irregular.KummerRealFixedField491

noncomputable section

open Polynomial AdjoinRoot
open Fermat.Irregular.TakagiFurtwangler491
open Fermat.Irregular.KummerConjugationDescent491

variable {K : Type*} [Field K] [NumberField K]
  [IsCyclotomicExtension {491} ℚ K]

local instance : Fact (Nat.Prime 491) := ⟨by norm_num⟩

local instance : NumberField.IsCMField K :=
  IsCyclotomicExtension.IsCMField (p := 491) K (by norm_num)

local notation3 "K⁺" => NumberField.maximalRealSubfield K

variable {a : 𝓞 K}
  [hirr : Fact (Irreducible (X ^ 491 - C (a : K)))]

local notation3 "L" => KummerExtension491 K a

local instance : Field L := AdjoinRoot.instField
local instance : Algebra K L := inferInstance
local instance : Module.Finite K L :=
  (monic_X_pow_sub_C (a : K) (by norm_num : 491 ≠ 0)).finite_adjoinRoot
local instance algebraKummerOverReal491 : Algebra K⁺ L :=
  Algebra.restrictScalars K⁺ K L
local instance scalarTowerKummerOverReal491 : IsScalarTower K⁺ K L :=
  IsScalarTower.of_algebraMap_eq fun _ => rfl
local instance finiteDimensionalKummerOverReal491 : FiniteDimensional K⁺ L :=
  FiniteDimensional.trans K⁺ K L

local instance : IsGalois K L := by
  obtain ⟨ζ, hζ⟩ :=
    IsCyclotomicExtension.exists_isPrimitiveRoot ℚ K
      (show 491 ∈ ({491} : Set ℕ) by simp)
      (by norm_num : 491 ≠ 0)
  exact kummerExtension491_isGalois hζ hirr.out

/-- The order-two subgroup generated by the lifted conjugation. -/
noncomputable def conjugationSubgroup491
    (hanti : ConjugationAntiInvariantWitness491 a) :
    Subgroup (L ≃ₐ[K⁺] L) :=
  Subgroup.zpowers (conjugationLift491 hanti)

/-- The degree-`491` field over `K⁺` fixed by lifted conjugation. -/
noncomputable def realFixedField491
    (hanti : ConjugationAntiInvariantWitness491 a) :
    IntermediateField K⁺ L :=
  IntermediateField.fixedField (conjugationSubgroup491 hanti)

theorem conjugationLift491_ne_one
    (hanti : ConjugationAntiInvariantWitness491 a) :
    conjugationLift491 hanti ≠ (1 : L ≃ₐ[K⁺] L) := by
  intro htau
  apply NumberField.IsCMField.complexConj_ne_one K
  ext x
  change NumberField.IsCMField.complexConj K x = x
  apply (algebraMap K L).injective
  have hx := DFunLike.congr_fun htau (algebraMap K L x)
  change
    conjugationLift491 hanti (algebraMap K L x) =
      algebraMap K L x at hx
  simpa only [conjugationLift491_algebraMap] using hx

theorem orderOf_conjugationLift491
    (hanti : ConjugationAntiInvariantWitness491 a) :
    orderOf (conjugationLift491 hanti) = 2 :=
  orderOf_eq_prime_iff.mpr
    ⟨conjugationLift491_sq (a := a) hanti,
      conjugationLift491_ne_one (a := a) hanti⟩

theorem natCard_conjugationSubgroup491
    (hanti : ConjugationAntiInvariantWitness491 a) :
    Nat.card (conjugationSubgroup491 hanti) = 2 := by
  rw [conjugationSubgroup491, Nat.card_zpowers,
    orderOf_conjugationLift491 (a := a) hanti]

/-- Membership in the fixed field is equivalent to being fixed by its
single generating involution. -/
@[simp]
theorem mem_realFixedField491_iff
    (hanti : ConjugationAntiInvariantWitness491 a) {x : L} :
    x ∈ realFixedField491 hanti ↔ conjugationLift491 hanti x = x := by
  rw [realFixedField491, IntermediateField.mem_fixedField_iff,
    conjugationSubgroup491, Subgroup.forall_mem_zpowers]
  simpa only [AlgEquiv.smul_def, MulAction.mem_fixedBy] using
    (MulAction.mem_fixedBy_zpowers_iff_mem_fixedBy
      (G := L ≃ₐ[K⁺] L) (α := L)
      (g := conjugationLift491 hanti) (a := x))

/-- The Kummer field has degree `982 = 2 * 491` over the maximal real
subfield. -/
theorem finrank_kummerExtension491_over_real :
    Module.finrank K⁺ L = 982 := by
  obtain ⟨ζ, hζ⟩ :=
    IsCyclotomicExtension.exists_isPrimitiveRoot ℚ K
      (show 491 ∈ ({491} : Set ℕ) by simp)
      (by norm_num : 491 ≠ 0)
  calc
    Module.finrank K⁺ L =
        Module.finrank K⁺ K * Module.finrank K L :=
      (Module.finrank_mul_finrank K⁺ K L).symm
    _ = 2 * 491 := by
      rw [Algebra.IsQuadraticExtension.finrank_eq_two K⁺ K,
        kummerExtension491_finrank hζ hirr.out]
    _ = 982 := by norm_num

/-- The extension from the fixed field up to the Kummer field is
quadratic. -/
theorem finrank_over_realFixedField491
    (hanti : ConjugationAntiInvariantWitness491 a) :
    Module.finrank (realFixedField491 hanti) L = 2 := by
  letI : FiniteDimensional K⁺ L :=
    finiteDimensionalKummerOverReal491 (K := K) (a := a)
  change
    Module.finrank
        (IntermediateField.fixedField (conjugationSubgroup491 hanti)) L = 2
  calc
    Module.finrank
        (IntermediateField.fixedField (conjugationSubgroup491 hanti)) L =
        Nat.card (conjugationSubgroup491 hanti) :=
      @IntermediateField.finrank_fixedField_eq_card
        K⁺ _ L _ (algebraKummerOverReal491 (K := K) (a := a))
        (conjugationSubgroup491 hanti)
        (finiteDimensionalKummerOverReal491 (K := K) (a := a))
    _ = 2 := natCard_conjugationSubgroup491 (a := a) hanti

/-- The fixed field has the desired prime degree over the maximal real
subfield. -/
theorem finrank_realFixedField491
    (hanti : ConjugationAntiInvariantWitness491 a) :
    Module.finrank K⁺ (realFixedField491 hanti) = 491 := by
  letI : IsScalarTower K⁺ (realFixedField491 hanti) L :=
    IntermediateField.isScalarTower_mid' (realFixedField491 hanti)
  have htower :=
    Module.finrank_mul_finrank K⁺ (realFixedField491 hanti) L
  rw [finrank_over_realFixedField491 (a := a) hanti,
    finrank_kummerExtension491_over_real (a := a)] at htower
  omega

omit [NumberField K] [IsCyclotomicExtension {491} ℚ K] in
/-- Forgetting from `K`-linearity to `K⁺`-linearity is injective on
automorphisms. -/
theorem restrictKAutToReal491_injective :
    Function.Injective
      (restrictKAutToReal491 :
        (L ≃ₐ[K] L) → (L ≃ₐ[K⁺] L)) := by
  intro σ ρ h
  apply AlgEquiv.ext
  intro x
  exact DFunLike.congr_fun h x

/-- Lifted conjugation is not a `K`-linear deck transformation. -/
theorem conjugationLift491_ne_restrictKAut
    (hanti : ConjugationAntiInvariantWitness491 a)
    (σ : L ≃ₐ[K] L) :
    conjugationLift491 hanti ≠ restrictKAutToReal491 σ := by
  intro h
  apply NumberField.IsCMField.complexConj_ne_one K
  ext x
  apply (algebraMap K L).injective
  calc
    algebraMap K L
        (NumberField.IsCMField.complexConj K x) =
        conjugationLift491 hanti (algebraMap K L x) := by
      rw [conjugationLift491_algebraMap]
    _ = restrictKAutToReal491 σ (algebraMap K L x) := by rw [h]
    _ = algebraMap K L x := σ.commutes x
    _ = algebraMap K L ((1 : K ≃ₐ[K⁺] K) x) := by simp

/-- The two cosets supplied by the deck group and lifted conjugation. -/
noncomputable def realAutCosetMap491
    (hanti : ConjugationAntiInvariantWitness491 a) :
    Bool × (L ≃ₐ[K] L) → (L ≃ₐ[K⁺] L)
  | (false, σ) => restrictKAutToReal491 σ
  | (true, σ) =>
      conjugationLift491 hanti * restrictKAutToReal491 σ

theorem realAutCosetMap491_injective
    (hanti : ConjugationAntiInvariantWitness491 a) :
    Function.Injective (realAutCosetMap491 hanti) := by
  rintro ⟨b, σ⟩ ⟨c, ρ⟩ h
  cases b <;> cases c
  · simp only [realAutCosetMap491] at h
    have hσρ := restrictKAutToReal491_injective (a := a) h
    exact Prod.ext rfl hσρ
  · simp only [realAutCosetMap491] at h
    exfalso
    apply conjugationLift491_ne_restrictKAut (a := a) hanti
      (σ * ρ⁻¹)
    calc
      conjugationLift491 hanti =
          restrictKAutToReal491 σ *
            (restrictKAutToReal491 ρ)⁻¹ := by
        rw [h, mul_assoc, mul_inv_cancel, mul_one]
      _ = restrictKAutToReal491 (σ * ρ⁻¹) := by
        ext x
        rfl
  · simp only [realAutCosetMap491] at h
    exfalso
    apply conjugationLift491_ne_restrictKAut (a := a) hanti
      (ρ * σ⁻¹)
    calc
      conjugationLift491 hanti =
          restrictKAutToReal491 ρ *
            (restrictKAutToReal491 σ)⁻¹ := by
        rw [← h, mul_assoc, mul_inv_cancel, mul_one]
      _ = restrictKAutToReal491 (ρ * σ⁻¹) := by
        ext x
        rfl
  · simp only [realAutCosetMap491] at h
    have hrs :
        restrictKAutToReal491 σ = restrictKAutToReal491 ρ :=
      mul_left_cancel h
    have hσρ := restrictKAutToReal491_injective (a := a) hrs
    exact Prod.ext rfl hσρ

theorem natCard_kummerKAut491 :
    Nat.card (L ≃ₐ[K] L) = 491 := by
  rw [IsGalois.card_aut_eq_finrank]
  obtain ⟨ζ, hζ⟩ :=
    IsCyclotomicExtension.exists_isPrimitiveRoot ℚ K
      (show 491 ∈ ({491} : Set ℕ) by simp)
      (by norm_num : 491 ≠ 0)
  exact kummerExtension491_finrank hζ hirr.out

/-- There are exactly `982` automorphisms over the real subfield.  The
lower bound is provided by the two explicit cosets; the universal
linear-independence bound supplies the upper bound. -/
theorem natCard_kummerRealAut491
    (hanti : ConjugationAntiInvariantWitness491 a) :
    Nat.card (L ≃ₐ[K⁺] L) = 982 := by
  letI : FiniteDimensional K⁺ L :=
    finiteDimensionalKummerOverReal491 (K := K) (a := a)
  letI : Fintype (L ≃ₐ[K⁺] L) :=
    @AlgEquiv.fintype K⁺ L _ _
      (algebraKummerOverReal491 (K := K) (a := a))
      (finiteDimensionalKummerOverReal491 (K := K) (a := a))
  have hlower :
      Nat.card (Bool × (L ≃ₐ[K] L)) ≤
        Nat.card (L ≃ₐ[K⁺] L) :=
    Nat.card_le_card_of_injective
      (realAutCosetMap491 hanti)
      (realAutCosetMap491_injective (a := a) hanti)
  have hlower' : 982 ≤ Nat.card (L ≃ₐ[K⁺] L) := by
    rw [Nat.card_prod, natCard_kummerKAut491 (a := a)] at hlower
    norm_num at hlower ⊢
    exact hlower
  have hupper :
      Nat.card (L ≃ₐ[K⁺] L) ≤ Module.finrank K⁺ L := by
    have h :=
      @AlgEquiv.card_le K⁺ L _ _
        (algebraKummerOverReal491 (K := K) (a := a))
        (finiteDimensionalKummerOverReal491 (K := K) (a := a))
    rw [← Nat.card_eq_fintype_card] at h
    exact h
  rw [finrank_kummerExtension491_over_real (a := a)] at hupper
  omega

/-- The full Kummer field is Galois over the maximal real subfield. -/
theorem isGalois_kummerExtension491_over_real
    (hanti : ConjugationAntiInvariantWitness491 a) :
    IsGalois K⁺ L :=
  @IsGalois.of_card_aut_eq_finrank K⁺ _ L _
    (algebraKummerOverReal491 (K := K) (a := a))
    (finiteDimensionalKummerOverReal491 (K := K) (a := a)) <| by
    exact (natCard_kummerRealAut491 (a := a) hanti).trans
      (finrank_kummerExtension491_over_real (a := a)).symm

theorem realAutCosetMap491_surjective
    (hanti : ConjugationAntiInvariantWitness491 a) :
    Function.Surjective (realAutCosetMap491 hanti) := by
  letI : FiniteDimensional K⁺ L :=
    finiteDimensionalKummerOverReal491 (K := K) (a := a)
  letI : Fintype (L ≃ₐ[K⁺] L) :=
    @AlgEquiv.fintype K⁺ L _ _
      (algebraKummerOverReal491 (K := K) (a := a))
      (finiteDimensionalKummerOverReal491 (K := K) (a := a))
  exact
    ((Nat.bijective_iff_injective_and_card
      (realAutCosetMap491 hanti)).2
      ⟨realAutCosetMap491_injective (a := a) hanti, by
        rw [Nat.card_prod, natCard_kummerKAut491 (a := a),
          natCard_kummerRealAut491 (a := a) hanti]
        norm_num⟩).2

/-- Lifted conjugation is central in the full Galois group over `K⁺`. -/
theorem conjugationLift491_commute_realAut
    (hanti : ConjugationAntiInvariantWitness491 a)
    (σ : L ≃ₐ[K⁺] L) :
    Commute (conjugationLift491 hanti) σ := by
  obtain ⟨⟨b, ρ⟩, rfl⟩ :=
    realAutCosetMap491_surjective (a := a) hanti σ
  cases b
  · exact conjugationLift491_commute_kAut (a := a) hanti ρ
  · exact (Commute.refl (conjugationLift491 hanti)).mul_right
      (conjugationLift491_commute_kAut (a := a) hanti ρ)

/-- The subgroup generated by lifted conjugation is normal. -/
theorem conjugationSubgroup491_normal
    (hanti : ConjugationAntiInvariantWitness491 a) :
    Subgroup.Normal (conjugationSubgroup491 hanti) where
  conj_mem h hh σ := by
    obtain ⟨n, rfl⟩ := Subgroup.mem_zpowers_iff.mp hh
    have hcomm :=
      (conjugationLift491_commute_realAut (a := a) hanti σ).zpow_left n
    rw [← hcomm.eq, mul_assoc, mul_inv_cancel, mul_one]
    exact Subgroup.zpow_mem_zpowers _ _

/-- The degree-`491` real fixed field is Galois over `K⁺`. -/
theorem isGalois_realFixedField491
    (hanti : ConjugationAntiInvariantWitness491 a) :
    IsGalois K⁺ (realFixedField491 hanti) := by
  letI : IsGalois K⁺ L :=
    isGalois_kummerExtension491_over_real (a := a) hanti
  letI : Subgroup.Normal (conjugationSubgroup491 hanti) :=
    conjugationSubgroup491_normal (a := a) hanti
  exact IsGalois.of_fixedField_normal_subgroup
    (conjugationSubgroup491 hanti)

theorem natCard_realFixedFieldAut491
    (hanti : ConjugationAntiInvariantWitness491 a) :
    Nat.card
      ((realFixedField491 hanti) ≃ₐ[K⁺]
        (realFixedField491 hanti)) = 491 := by
  letI : FiniteDimensional K⁺ (realFixedField491 hanti) :=
    FiniteDimensional.of_finrank_pos <| by
      rw [finrank_realFixedField491 (a := a) hanti]
      norm_num
  letI : IsGalois K⁺ (realFixedField491 hanti) :=
    isGalois_realFixedField491 (a := a) hanti
  rw [IsGalois.card_aut_eq_finrank,
    finrank_realFixedField491 (a := a) hanti]

/-- The descended real extension has cyclic Galois group of order `491`. -/
theorem isCyclic_realFixedFieldAut491
    (hanti : ConjugationAntiInvariantWitness491 a) :
    IsCyclic
      ((realFixedField491 hanti) ≃ₐ[K⁺]
        (realFixedField491 hanti)) := by
  exact isCyclic_of_prime_card
    (natCard_realFixedFieldAut491 (a := a) hanti)

end

end Fermat.Irregular.KummerRealFixedField491
