import Fermat.Irregular.IdealCount
import Mathlib.Data.Sym.Card

/-!
# Ideal counts from uniform splitting data

If every prime ideal above a rational prime `q` has norm `q ^ f`, unique ideal
factorization identifies ideals of norm `q ^ (f * d)` with multisets of `d`
primes above `q`.  Stars and bars then gives the corresponding prime-power
ideal count as a multichoose coefficient.  If `f` does not divide the exponent,
the norm fiber is empty.
-/

open scoped Classical

namespace Fermat.Irregular.PrimePowerIdealCount

noncomputable section

open Fermat.Irregular.IdealCount

variable {S : Type*} [CommRing S] [Nontrivial S] [IsDedekindDomain S]
  [Module.Free ℤ S] [Module.Finite ℤ S] [CharZero S]

/-- The ideal of `ℤ` generated by the natural number `q`. -/
abbrev rationalPrimeIdeal (q : ℕ) : Ideal ℤ := Ideal.span {(q : ℤ)}

omit [Module.Finite ℤ S] [CharZero S] in
/-- Every normalized prime factor of an ideal of prime-power norm lies above
that rational prime. -/
theorem normalizedFactor_mem_primesOver_of_absNorm_eq_prime_pow
    {q k : ℕ} (hq : q.Prime) {I P : Ideal S}
    (hI : Ideal.absNorm I = q ^ k)
    (hP : P ∈ UniqueFactorizationMonoid.normalizedFactors I) :
    P ∈ (rationalPrimeIdeal q).primesOver S := by
  have hIne : I ≠ ⊥ := by
    intro hzero
    have : q ^ k = 0 := by simpa [hzero] using hI.symm
    exact (pow_ne_zero k hq.ne_zero) this
  have hPprime : P.IsPrime :=
    UniqueFactorizationMonoid.prime_of_normalized_factor P hP |>
      Ideal.isPrime_of_prime
  have hIP : I ≤ P := (Ideal.mem_normalizedFactors_iff hIne).mp hP |>.2
  have hpow : ((q : S) ^ k) ∈ P := by
    apply hIP
    simpa [hI] using Ideal.absNorm_mem I
  have hqmem : algebraMap ℤ S (q : ℤ) ∈ P := by
    simpa using hPprime.mem_of_pow_mem k hpow
  refine ⟨hPprime, ?_⟩
  exact (Ideal.liesOver_span_iff hPprime.ne_top
    (Nat.prime_iff_prime_int.mp hq)).2 hqmem

/-- Send an ideal of norm `q ^ (f * d)` to its multiset of `d` prime factors
above `q`. -/
def normFiberToPrimeSym
    (q f d : ℕ) (hq : q.Prime) (hf : 0 < f)
    (hnorm : ∀ P ∈ (rationalPrimeIdeal q).primesOver S,
      Ideal.absNorm P = q ^ f) :
    NormFiber S (q ^ (f * d)) → Sym ((rationalPrimeIdeal q).primesOver S) d := by
  intro I
  let s := UniqueFactorizationMonoid.normalizedFactors I.1
  have habove : ∀ P ∈ s, P ∈ (rationalPrimeIdeal q).primesOver S := by
    intro P hP
    exact normalizedFactor_mem_primesOver_of_absNorm_eq_prime_pow hq I.2 hP
  let t : Multiset ((rationalPrimeIdeal q).primesOver S) :=
    s.attach.map fun P ↦ ⟨P.1, habove P.1 P.2⟩
  refine ⟨t, ?_⟩
  have hnormFactors : ∀ P ∈ s, Ideal.absNorm P = q ^ f := by
    intro P hP
    exact hnorm P (habove P hP)
  have hIne : I.1 ≠ ⊥ := by
    intro hzero
    have : q ^ (f * d) = 0 := by simpa [hzero] using I.2.symm
    exact (pow_ne_zero (f * d) hq.ne_zero) this
  have hprod : Ideal.absNorm s.prod = q ^ (f * s.card) :=
    absNorm_multiset_prod_of_forall_eq_pow s q f hnormFactors
  rw [Ideal.prod_normalizedFactors_eq_self hIne, I.2] at hprod
  have hexp : f * d = f * s.card :=
    Nat.pow_right_injective hq.two_le hprod
  have hcard : s.card = d :=
    (Nat.eq_of_mul_eq_mul_left hf hexp).symm
  simp [t, hcard]

/-- Multiply a multiset of `d` primes above `q` into an ideal of norm
`q ^ (f * d)`. -/
def primeSymToNormFiber
    (q f d : ℕ)
    (hnorm : ∀ P ∈ (rationalPrimeIdeal q).primesOver S,
      Ideal.absNorm P = q ^ f) :
    Sym ((rationalPrimeIdeal q).primesOver S) d →
      NormFiber S (q ^ (f * d)) := by
  intro t
  let s : Multiset (Ideal S) := t.1.map Subtype.val
  refine ⟨s.prod, ?_⟩
  have hs : ∀ P ∈ s, Ideal.absNorm P = q ^ f := by
    intro P hP
    rw [Multiset.mem_map] at hP
    obtain ⟨Q, hQt, rfl⟩ := hP
    exact hnorm Q.1 Q.2
  have h := absNorm_multiset_prod_of_forall_eq_pow s q f hs
  simpa [s, t.2] using h

/-- Ideals of norm `q ^ (f * d)` are equivalent to multisets of cardinality
`d` drawn from the primes above `q`. -/
def normFiberPrimeSymEquiv
    (q f d : ℕ) (hq : q.Prime) (hf : 0 < f)
    (hnorm : ∀ P ∈ (rationalPrimeIdeal q).primesOver S,
      Ideal.absNorm P = q ^ f) :
    NormFiber S (q ^ (f * d)) ≃ Sym ((rationalPrimeIdeal q).primesOver S) d where
  toFun := normFiberToPrimeSym q f d hq hf hnorm
  invFun := primeSymToNormFiber q f d hnorm
  left_inv I := by
    apply Subtype.ext
    simp only [normFiberToPrimeSym, primeSymToNormFiber]
    rw [Multiset.map_map]
    simp only [Function.comp_apply]
    rw [Multiset.attach_map_val,
      Ideal.prod_normalizedFactors_eq_self]
    intro hzero
    have : q ^ (f * d) = 0 := by simpa [hzero] using I.2.symm
    exact (pow_ne_zero (f * d) hq.ne_zero) this
  right_inv t := by
    apply Subtype.ext
    simp only [normFiberToPrimeSym, primeSymToNormFiber]
    have hprime : ∀ P ∈ (t.1.map fun P ↦ (P.1 : Ideal S)), Prime P := by
      intro P hP
      rw [Multiset.mem_map] at hP
      obtain ⟨Q, hQt, rfl⟩ := hP
      exact Ideal.prime_of_mem_primesOver
        (by simpa [rationalPrimeIdeal] using hq.ne_zero) Q.2
    have hnf := UniqueFactorizationMonoid.normalizedFactors_prod_of_prime hprime
    apply Multiset.map_injective Subtype.val_injective
    simp only [Multiset.map_map, Function.comp_apply, Multiset.attach_map_val]
    exact hnf

/-- The count at exponent `f * d` is the stars-and-bars binomial
coefficient. -/
theorem natCard_normFiber_prime_pow_mul
    (q f d : ℕ) (hq : q.Prime) (hf : 0 < f)
    (hnorm : ∀ P ∈ (rationalPrimeIdeal q).primesOver S,
      Ideal.absNorm P = q ^ f) :
    Nat.card (NormFiber S (q ^ (f * d))) =
      (((rationalPrimeIdeal q).primesOver S).ncard + d - 1).choose d := by
  have hfinite : ((rationalPrimeIdeal q).primesOver S).Finite := by
    refine (Ideal.finite_setOf_absNorm_eq (q ^ f)).subset ?_
    intro P hP
    exact hnorm P hP
  letI : Fintype ((rationalPrimeIdeal q).primesOver S) := hfinite.fintype
  letI : Fintype (Sym ((rationalPrimeIdeal q).primesOver S) d) := Fintype.ofFinite _
  calc
    Nat.card (NormFiber S (q ^ (f * d))) =
        Nat.card (Sym ((rationalPrimeIdeal q).primesOver S) d) :=
      Nat.card_congr (normFiberPrimeSymEquiv q f d hq hf hnorm)
    _ = Fintype.card (Sym ((rationalPrimeIdeal q).primesOver S) d) :=
      Nat.card_eq_fintype_card
    _ = (Fintype.card ((rationalPrimeIdeal q).primesOver S) + d - 1).choose d :=
      Sym.card_sym_eq_choose d
    _ = (((rationalPrimeIdeal q).primesOver S).ncard + d - 1).choose d := by
      rw [Set.fintypeCard_eq_ncard]

omit [Module.Finite ℤ S] [CharZero S] in
/-- If the residue degree does not divide `k`, no ideal has norm `q ^ k`. -/
theorem normFiber_isEmpty_of_not_dvd_inertiaDeg
    (q f k : ℕ) (hq : q.Prime) (hfd : ¬ f ∣ k)
    (hnorm : ∀ P ∈ (rationalPrimeIdeal q).primesOver S,
      Ideal.absNorm P = q ^ f) :
    IsEmpty (NormFiber S (q ^ k)) := by
  constructor
  intro I
  let s := UniqueFactorizationMonoid.normalizedFactors I.1
  have hIne : I.1 ≠ ⊥ := by
    intro hzero
    have : q ^ k = 0 := by simpa [hzero] using I.2.symm
    exact (pow_ne_zero k hq.ne_zero) this
  have habove : ∀ P ∈ s, P ∈ (rationalPrimeIdeal q).primesOver S := by
    intro P hP
    exact normalizedFactor_mem_primesOver_of_absNorm_eq_prime_pow hq I.2 hP
  have hnormFactors : ∀ P ∈ s, Ideal.absNorm P = q ^ f := by
    intro P hP
    exact hnorm P (habove P hP)
  have hprod : Ideal.absNorm s.prod = q ^ (f * s.card) :=
    absNorm_multiset_prod_of_forall_eq_pow s q f hnormFactors
  rw [Ideal.prod_normalizedFactors_eq_self hIne, I.2] at hprod
  have hexp : k = f * s.card := Nat.pow_right_injective hq.two_le hprod
  exact hfd ⟨s.card, hexp⟩

/-- Uniform residue degree gives the complete prime-power norm-fiber count. -/
theorem natCard_normFiber_prime_pow
    (q f k : ℕ) (hq : q.Prime) (hf : 0 < f)
    (hnorm : ∀ P ∈ (rationalPrimeIdeal q).primesOver S,
      Ideal.absNorm P = q ^ f) :
    Nat.card (NormFiber S (q ^ k)) =
      if f ∣ k then
        (((rationalPrimeIdeal q).primesOver S).ncard + k / f - 1).choose (k / f)
      else 0 := by
  by_cases hfd : f ∣ k
  · obtain ⟨d, rfl⟩ := hfd
    rw [if_pos (dvd_mul_right f d)]
    simpa [Nat.mul_div_cancel_left d hf] using
      natCard_normFiber_prime_pow_mul (S := S) q f d hq hf hnorm
  · rw [if_neg hfd]
    letI : Fintype (NormFiber S (q ^ k)) :=
      (Ideal.finite_setOf_absNorm_eq (q ^ k)).fintype
    rw [Nat.card_eq_fintype_card, Fintype.card_eq_zero_iff]
    exact normFiber_isEmpty_of_not_dvd_inertiaDeg q f k hq hfd hnorm

/-- The same norm-fiber count in its natural multichoose form. -/
theorem natCard_normFiber_prime_pow_eq_multichoose
    (q f k : ℕ) (hq : q.Prime) (hf : 0 < f)
    (hnorm : ∀ P ∈ (rationalPrimeIdeal q).primesOver S,
      Ideal.absNorm P = q ^ f) :
    Nat.card (NormFiber S (q ^ k)) =
      if f ∣ k then
        Nat.multichoose ((rationalPrimeIdeal q).primesOver S).ncard (k / f)
      else 0 := by
  rw [natCard_normFiber_prime_pow q f k hq hf hnorm]
  split <;> simp [Nat.multichoose_eq]

/-- The prime-power coefficient of the ideal-counting arithmetic function in
multichoose form. -/
theorem idealCountArithmetic_prime_pow_eq_multichoose
    (q f k : ℕ) (hq : q.Prime) (hf : 0 < f)
    (hnorm : ∀ P ∈ (rationalPrimeIdeal q).primesOver S,
      Ideal.absNorm P = q ^ f) :
    idealCountArithmetic (S := S) (q ^ k) =
      if f ∣ k then
        (Nat.multichoose ((rationalPrimeIdeal q).primesOver S).ncard (k / f) : ℂ)
      else 0 := by
  change (if q ^ k = 0 then 0 else (Nat.card (NormFiber S (q ^ k)) : ℂ)) = _
  rw [if_neg (pow_ne_zero k hq.ne_zero),
    natCard_normFiber_prime_pow_eq_multichoose q f k hq hf hnorm]
  split <;> norm_num

end

end Fermat.Irregular.PrimePowerIdealCount
