import Fermat.Irregular.CyclotomicZetaCoefficientsPrime
import Fermat.Irregular.CircularUnitFamily
import Fermat.Irregular.PrimePowerIdealCount
import Mathlib.NumberTheory.NumberField.Cyclotomic.Ideal
import Mathlib.NumberTheory.NumberField.Cyclotomic.Galois

/-!
# The ramified local factor for prime cyclotomic fields

For every odd prime p, the unique prime above p in the full cyclotomic
field descends to a unique prime of residue degree one in the maximal real
subfield.  Consequently the actual ideal-count coefficient at p^k is one.
All nontrivial even character coefficients vanish at positive powers of p,
so the predicted coefficient is one as well.
-/

open scoped NumberField Classical BigOperators

namespace Fermat.Irregular.RamifiedLocalFactorPrime

noncomputable section

open Fermat.Irregular.CyclotomicCharactersPrime
open Fermat.Irregular.CyclotomicZetaCoefficientsPrime
open Fermat.Irregular.PrimePowerIdealCount

variable {p : ℕ} [Fact (Nat.Prime p)] [Fact (2 < p)]
variable {K : Type*} [Field K] [NumberField K]
  [IsCyclotomicExtension {p} ℚ K]
  [NumberField.IsCMField K] [IsAbelianGalois ℚ K]

local notation3 "K⁺" => NumberField.maximalRealSubfield K

local instance : IsAbelianGalois ℚ K⁺ :=
  IsAbelianGalois.tower_bot ℚ K⁺ K
local instance : IsAbelianGalois K⁺ K :=
  IsAbelianGalois.tower_top ℚ K⁺ K
local instance : Fintype (RealResidueGroup p →* ℂˣ) :=
  Fintype.ofFinite _

/-- The rational prime ideal generated by p. -/
abbrev pIdeal : Ideal ℤ := Ideal.span {(p : ℤ)}

/-- There is exactly one prime of the maximal real field above p. -/
theorem ncard_primesOver_p_real :
    ((pIdeal (p := p)).primesOver
      (NumberField.RingOfIntegers K⁺)).ncard = 1 := by
  have hpprime : (pIdeal (p := p)).IsPrime := by
    exact (Ideal.span_singleton_prime (by
      exact_mod_cast (Fact.out : Nat.Prime p).ne_zero)).2
        (Nat.prime_iff_prime_int.mp (Fact.out : Nat.Prime p))
  letI : (pIdeal (p := p)).IsMaximal :=
    hpprime.isMaximal (by
      simpa [pIdeal] using (Fact.out : Nat.Prime p).ne_zero)
  obtain ⟨⟨P, hPprime, hPlies⟩⟩ :=
    (pIdeal (p := p)).nonempty_primesOver
      (S := NumberField.RingOfIntegers K⁺)
  letI : P.IsPrime := hPprime
  letI : P.LiesOver (pIdeal (p := p)) := hPlies
  have hPne : P ≠ ⊥ :=
    Ideal.ne_bot_of_mem_primesOver
      (by simpa [pIdeal] using (Fact.out : Nat.Prime p).ne_zero)
      ⟨hPprime, hPlies⟩
  letI : P.IsMaximal := hPprime.isMaximal hPne
  have h := Ideal.ncard_primesOver_mul_ncard_primesOver
    (p := pIdeal (p := p)) P Gal(K⁺/ℚ)
      (NumberField.RingOfIntegers K) Gal(K/ℚ) Gal(K/K⁺)
      (by simpa [pIdeal] using (Fact.out : Nat.Prime p).ne_zero)
  have hfull :
      ((pIdeal (p := p)).primesOver
        (NumberField.RingOfIntegers K)).ncard = 1 := by
    simpa [pIdeal] using
      IsCyclotomicExtension.Rat.ncard_primesOver_of_prime p K
  rw [hfull] at h
  exact (mul_eq_one.mp h).1

/-- The residue degree of p in the maximal real field is one. -/
theorem inertiaDegIn_p_real :
    (pIdeal (p := p)).inertiaDegIn
      (NumberField.RingOfIntegers K⁺) = 1 := by
  have hpprime : (pIdeal (p := p)).IsPrime := by
    exact (Ideal.span_singleton_prime (by
      exact_mod_cast (Fact.out : Nat.Prime p).ne_zero)).2
        (Nat.prime_iff_prime_int.mp (Fact.out : Nat.Prime p))
  letI : (pIdeal (p := p)).IsMaximal :=
    hpprime.isMaximal (by
      simpa [pIdeal] using (Fact.out : Nat.Prime p).ne_zero)
  obtain ⟨⟨P, hPprime, hPlies⟩⟩ :=
    (pIdeal (p := p)).nonempty_primesOver
      (S := NumberField.RingOfIntegers K⁺)
  letI : P.IsPrime := hPprime
  letI : P.LiesOver (pIdeal (p := p)) := hPlies
  have hPne : P ≠ ⊥ :=
    Ideal.ne_bot_of_mem_primesOver
      (by simpa [pIdeal] using (Fact.out : Nat.Prime p).ne_zero)
      ⟨hPprime, hPlies⟩
  letI : P.IsMaximal := hPprime.isMaximal hPne
  have h := Ideal.inertiaDegIn_mul_inertiaDegIn
    (pIdeal (p := p)) P Gal(K⁺/ℚ)
      (NumberField.RingOfIntegers K) Gal(K/ℚ) Gal(K/K⁺)
  have hfull :
      (pIdeal (p := p)).inertiaDegIn
        (NumberField.RingOfIntegers K) = 1 := by
    simpa [pIdeal] using
      IsCyclotomicExtension.Rat.inertiaDegIn_eq_of_prime p K
  rw [hfull] at h
  exact (mul_eq_one.mp h).1

/-- Every prime above p in the maximal real field has norm p. -/
theorem absNorm_eq_p_of_mem_primesOver
    {P : Ideal (NumberField.RingOfIntegers K⁺)}
    (hP : P ∈ (pIdeal (p := p)).primesOver
      (NumberField.RingOfIntegers K⁺)) :
    Ideal.absNorm P = p := by
  letI : P.IsPrime := hP.1
  letI : P.LiesOver (pIdeal (p := p)) := hP.2
  have hdeg : (pIdeal (p := p)).inertiaDeg P = 1 := by
    rw [← Ideal.inertiaDegIn_eq_inertiaDeg
      (pIdeal (p := p)) P Gal(K⁺/ℚ)]
    exact inertiaDegIn_p_real (p := p) (K := K)
  calc
    Ideal.absNorm P =
        p ^ (pIdeal (p := p)).inertiaDeg P := by
      simpa [pIdeal] using
        Ideal.absNorm_eq_pow_inertiaDeg' P
          (Fact.out : Nat.Prime p)
    _ = p := by rw [hdeg]; simp

/-- The actual ideal-count coefficient at every power of p is one. -/
theorem idealCount_p_pow (k : ℕ) :
    idealCount K⁺ (p ^ k) = 1 := by
  change Fermat.Irregular.IdealCount.idealCountArithmetic
    (S := NumberField.RingOfIntegers K⁺) (p ^ k) = 1
  rw [idealCountArithmetic_prime_pow_eq_multichoose
    p 1 k (Fact.out : Nat.Prime p) (by norm_num)]
  · rw [ncard_primesOver_p_real (p := p) (K := K)]
    simp
  · intro P hP
    rw [absNorm_eq_p_of_mem_primesOver (p := p) (K := K) hP,
      pow_one]

/-- A nontrivial character coefficient is one at p^0 and vanishes at every
positive power of p. -/
theorem characterCoefficient_p_pow
    (χ : {χ : RealResidueGroup p →* ℂˣ // χ ≠ 1}) (k : ℕ) :
    characterCoefficient χ (p ^ k) = if k = 0 then 1 else 0 := by
  rcases k with _ | k
  · simp [characterCoefficient, toArithmeticFunction]
  · simp [characterCoefficient, toArithmeticFunction,
      (Fact.out : Nat.Prime p).ne_zero]
    apply MulChar.map_nonunit
    simpa only [isUnit_iff_ne_zero, not_not] using
      ZMod.natCast_self p

/-- Convolution by a function supported only at q^0 does not change a
second function on powers of the prime q. -/
theorem mul_apply_prime_pow_of_left_delta
    (q : ℕ) (hq : q.Prime)
    (f g : ArithmeticFunction ℂ)
    (hf : ∀ i : ℕ, f (q ^ i) = if i = 0 then 1 else 0)
    (k : ℕ) :
    (f * g) (q ^ k) = g (q ^ k) := by
  rw [ArithmeticFunction.mul_apply,
    Nat.sum_divisorsAntidiagonal (fun x y ↦ f x * g y),
    Nat.sum_divisors_prime_pow hq]
  rw [Finset.sum_eq_single 0]
  · have hfone : f 1 = 1 := by simpa using hf 0
    simp only [pow_zero, Nat.div_one, hfone, one_mul]
  · intro i hi hi0
    rw [hf i, if_neg hi0, zero_mul]
  · simp

/-- Any finite product of the nontrivial character coefficients is
supported only at p^0 along powers of p. -/
theorem finset_prod_characterCoefficient_p_pow
    (S : Finset {χ : RealResidueGroup p →* ℂˣ // χ ≠ 1})
    (k : ℕ) :
    (∏ χ ∈ S, characterCoefficient χ : ArithmeticFunction ℂ)
        (p ^ k) =
      if k = 0 then 1 else 0 := by
  induction S using Finset.induction_on with
  | empty =>
      rcases k with _ | k
      · simp
      · simp only [Finset.prod_empty, if_neg (Nat.succ_ne_zero k)]
        rw [ArithmeticFunction.one_apply_ne]
        exact ne_of_gt (one_lt_pow₀
          (Fact.out : Nat.Prime p).one_lt (Nat.succ_ne_zero k))
  | @insert χ S hχ ih =>
      rw [Finset.prod_insert hχ]
      rw [mul_apply_prime_pow_of_left_delta p
        (Fact.out : Nat.Prime p) _ _
        (characterCoefficient_p_pow χ) k]
      exact ih

/-- The character-predicted coefficient at every power of p is one. -/
theorem expectedIdealCount_p_pow (k : ℕ) :
    expectedIdealCount (p := p) (p ^ k) = 1 := by
  rw [expectedIdealCount, mul_comm]
  calc
    ((∏ χ : {χ : RealResidueGroup p →* ℂˣ // χ ≠ 1},
        characterCoefficient χ) *
        (ArithmeticFunction.zeta : ArithmeticFunction ℂ)) (p ^ k) =
        (ArithmeticFunction.zeta : ArithmeticFunction ℂ) (p ^ k) := by
      apply mul_apply_prime_pow_of_left_delta p
        (Fact.out : Nat.Prime p)
      intro i
      simpa using finset_prod_characterCoefficient_p_pow
        (Finset.univ :
          Finset {χ : RealResidueGroup p →* ℂˣ // χ ≠ 1}) i
    _ = 1 := by simp [(Fact.out : Nat.Prime p).ne_zero]

/-- The actual and predicted prime-power coefficients agree at the
ramified prime p. -/
theorem idealCount_eq_expected_p_pow (k : ℕ) :
    idealCount K⁺ (p ^ k) =
      expectedIdealCount (p := p) (p ^ k) := by
  rw [idealCount_p_pow, expectedIdealCount_p_pow]

end

end Fermat.Irregular.RamifiedLocalFactorPrime
