import Fermat.Irregular.CyclotomicZetaCoefficients37
import Mathlib.NumberTheory.NumberField.Cyclotomic.Ideal
import Mathlib.NumberTheory.NumberField.Cyclotomic.Galois

/-!
# The ramified local factor at 37

This file closes the ramified prime-power case in the coefficientwise Artin
factorization for the maximal real subfield of a 37th cyclotomic field.  The
unique prime above `37` has residue degree one, so every ideal of norm `37 ^ k`
is its `k`th power.  On the character side all nontrivial Dirichlet-character
coefficients vanish at positive powers of `37`, leaving the zeta coefficient.
-/

open scoped NumberField Classical

namespace Fermat.Irregular.RamifiedLocalFactor37

noncomputable section

open Fermat.Irregular.CircularUnitIndex
open Fermat.Irregular.IdealCount
open Fermat.Irregular.CyclotomicZetaCoefficients37
open Fermat.Irregular.CyclotomicDirichlet37
open Fermat.Irregular.CyclotomicLogDet

local instance : Fact (Nat.Prime 37) := ⟨by decide⟩
local instance : Fintype (RealResidueGroup37 →* ℂˣ) := Fintype.ofFinite _

variable {K : Type*} [Field K] [NumberField K]
  [IsCyclotomicExtension {37} ℚ K]

local instance : NumberField.IsCMField K := cyclotomic37_isCMField (K := K)
local notation3 "K⁺" => NumberField.maximalRealSubfield K

local instance : IsAbelianGalois ℚ K :=
  IsCyclotomicExtension.isAbelianGalois {37} ℚ K
local instance : IsAbelianGalois ℚ K⁺ :=
  IsAbelianGalois.tower_bot ℚ K⁺ K
local instance : IsAbelianGalois K⁺ K :=
  IsAbelianGalois.tower_top ℚ K⁺ K

/-- The rational prime ideal generated by `37`. -/
abbrev p37 : Ideal ℤ := Ideal.span {(37 : ℤ)}

/-- There is exactly one prime of the maximal real field above `37`. -/
theorem ncard_primesOver_37_real :
    (p37.primesOver (NumberField.RingOfIntegers K⁺)).ncard = 1 := by
  have hpprime : p37.IsPrime := by
    exact (Ideal.span_singleton_prime (by norm_num : (37 : ℤ) ≠ 0)).2
      (Nat.prime_iff_prime_int.mp (by decide))
  letI : p37.IsMaximal := hpprime.isMaximal (by norm_num [p37])
  obtain ⟨⟨P, hPprime, hPlies⟩⟩ :=
    p37.nonempty_primesOver (S := NumberField.RingOfIntegers K⁺)
  letI : P.IsPrime := hPprime
  letI : P.LiesOver p37 := hPlies
  have hPne : P ≠ ⊥ :=
    Ideal.ne_bot_of_mem_primesOver (by norm_num [p37]) ⟨hPprime, hPlies⟩
  letI : P.IsMaximal := hPprime.isMaximal hPne
  have h := Ideal.ncard_primesOver_mul_ncard_primesOver (p := p37) P Gal(K⁺/ℚ)
    (NumberField.RingOfIntegers K) Gal(K/ℚ) Gal(K/K⁺) (by norm_num [p37])
  have hfull : (p37.primesOver (NumberField.RingOfIntegers K)).ncard = 1 := by
    simpa [p37] using IsCyclotomicExtension.Rat.ncard_primesOver_of_prime 37 K
  rw [hfull] at h
  exact (mul_eq_one.mp h).1

/-- The residue degree of `37` in the maximal real field is one. -/
theorem inertiaDegIn_37_real :
    p37.inertiaDegIn (NumberField.RingOfIntegers K⁺) = 1 := by
  have hpprime : p37.IsPrime := by
    exact (Ideal.span_singleton_prime (by norm_num : (37 : ℤ) ≠ 0)).2
      (Nat.prime_iff_prime_int.mp (by decide))
  letI : p37.IsMaximal := hpprime.isMaximal (by norm_num [p37])
  obtain ⟨⟨P, hPprime, hPlies⟩⟩ :=
    p37.nonempty_primesOver (S := NumberField.RingOfIntegers K⁺)
  letI : P.IsPrime := hPprime
  letI : P.LiesOver p37 := hPlies
  have hPne : P ≠ ⊥ :=
    Ideal.ne_bot_of_mem_primesOver (by norm_num [p37]) ⟨hPprime, hPlies⟩
  letI : P.IsMaximal := hPprime.isMaximal hPne
  have h := Ideal.inertiaDegIn_mul_inertiaDegIn p37 P Gal(K⁺/ℚ)
    (NumberField.RingOfIntegers K) Gal(K/ℚ) Gal(K/K⁺)
  have hfull : p37.inertiaDegIn (NumberField.RingOfIntegers K) = 1 := by
    simpa [p37] using IsCyclotomicExtension.Rat.inertiaDegIn_eq_of_prime 37 K
  rw [hfull] at h
  exact (mul_eq_one.mp h).1

/-- Every prime above `37` in the maximal real field has absolute norm `37`. -/
theorem absNorm_eq_37_of_mem_primesOver
    {P : Ideal (NumberField.RingOfIntegers K⁺)}
    (hP : P ∈ p37.primesOver (NumberField.RingOfIntegers K⁺)) :
    Ideal.absNorm P = 37 := by
  letI : P.IsPrime := hP.1
  letI : P.LiesOver p37 := hP.2
  have hdeg : p37.inertiaDeg P = 1 := by
    rw [← Ideal.inertiaDegIn_eq_inertiaDeg p37 P Gal(K⁺/ℚ)]
    exact inertiaDegIn_37_real (K := K)
  calc
    Ideal.absNorm P = 37 ^ p37.inertiaDeg P := by
      simpa [p37] using Ideal.absNorm_eq_pow_inertiaDeg' P (by decide : Nat.Prime 37)
    _ = 37 := by rw [hdeg]; simp

/-- Any two primes of the maximal real field above `37` coincide. -/
theorem eq_of_mem_primesOver_37
    {P Q : Ideal (NumberField.RingOfIntegers K⁺)}
    (hP : P ∈ p37.primesOver (NumberField.RingOfIntegers K⁺))
    (hQ : Q ∈ p37.primesOver (NumberField.RingOfIntegers K⁺)) :
    P = Q := by
  obtain ⟨R, hR⟩ := Set.ncard_eq_one.mp (ncard_primesOver_37_real (K := K))
  have hPR : P = R := by
    have : P ∈ ({R} : Set (Ideal (NumberField.RingOfIntegers K⁺))) := hR ▸ hP
    simpa using this
  have hQR : Q = R := by
    have : Q ∈ ({R} : Set (Ideal (NumberField.RingOfIntegers K⁺))) := hR ▸ hQ
    simpa using this
  exact hPR.trans hQR.symm

/-- An ideal of norm `37 ^ k` has exactly `k` copies of the unique prime above
`37` in its normalized factorization. -/
theorem normalizedFactors_eq_replicate_of_absNorm_eq_37_pow
    (P : Ideal (NumberField.RingOfIntegers K⁺))
    (hP : P ∈ p37.primesOver (NumberField.RingOfIntegers K⁺))
    (I : Ideal (NumberField.RingOfIntegers K⁺)) (k : ℕ)
    (hI : Ideal.absNorm I = 37 ^ k) :
    UniqueFactorizationMonoid.normalizedFactors I = Multiset.replicate k P := by
  have hIne : I ≠ ⊥ := by
    intro hzero
    have : (37 : ℕ) ^ k = 0 := by simpa [hzero] using hI.symm
    exact (pow_ne_zero k (by norm_num : (37 : ℕ) ≠ 0)) this
  let s := UniqueFactorizationMonoid.normalizedFactors I
  have hfactorAbove : ∀ Q ∈ s,
      Q ∈ p37.primesOver (NumberField.RingOfIntegers K⁺) := by
    intro Q hQ
    have hQprime : Q.IsPrime :=
      UniqueFactorizationMonoid.prime_of_normalized_factor Q hQ |>
        Ideal.isPrime_of_prime
    have hIQ : I ≤ Q :=
      (Ideal.mem_normalizedFactors_iff hIne).mp hQ |>.2
    have hpow : ((37 : NumberField.RingOfIntegers K⁺) ^ k) ∈ Q := by
      apply hIQ
      simpa [hI] using Ideal.absNorm_mem I
    have h37mem : algebraMap ℤ (NumberField.RingOfIntegers K⁺) (37 : ℤ) ∈ Q := by
      simpa using hQprime.mem_of_pow_mem k hpow
    refine ⟨hQprime, ?_⟩
    exact (Ideal.liesOver_span_iff hQprime.ne_top
      (Nat.prime_iff_prime_int.mp (by decide : Nat.Prime 37))).2 h37mem
  have hall : ∀ Q ∈ s, Q = P := by
    intro Q hQ
    exact eq_of_mem_primesOver_37 (K := K) (hfactorAbove Q hQ) hP
  have hnormFactors : ∀ Q ∈ s, Ideal.absNorm Q = 37 ^ 1 := by
    intro Q hQ
    rw [hall Q hQ, absNorm_eq_37_of_mem_primesOver (K := K) hP, pow_one]
  have hcard : s.card = k := by
    have hprod : Ideal.absNorm s.prod = 37 ^ (1 * s.card) :=
      absNorm_multiset_prod_of_forall_eq_pow s 37 1 hnormFactors
    rw [Ideal.prod_normalizedFactors_eq_self hIne, hI, one_mul] at hprod
    exact (Nat.pow_right_injective (by norm_num : 1 < 37)) hprod.symm
  calc
    UniqueFactorizationMonoid.normalizedFactors I = Multiset.replicate s.card P :=
      Multiset.eq_replicate_card.2 hall
    _ = Multiset.replicate k P := by rw [hcard]

/-- Every ideal of norm `37 ^ k` is the `k`th power of the unique prime above
`37`. -/
theorem eq_pow_of_absNorm_eq_37_pow
    (P : Ideal (NumberField.RingOfIntegers K⁺))
    (hP : P ∈ p37.primesOver (NumberField.RingOfIntegers K⁺))
    (I : Ideal (NumberField.RingOfIntegers K⁺)) (k : ℕ)
    (hI : Ideal.absNorm I = 37 ^ k) :
    I = P ^ k := by
  have hIne : I ≠ ⊥ := by
    intro hzero
    have : (37 : ℕ) ^ k = 0 := by simpa [hzero] using hI.symm
    exact (pow_ne_zero k (by norm_num : (37 : ℕ) ≠ 0)) this
  calc
    I = (UniqueFactorizationMonoid.normalizedFactors I).prod :=
      (Ideal.prod_normalizedFactors_eq_self hIne).symm
    _ = (Multiset.replicate k P).prod := by
      rw [normalizedFactors_eq_replicate_of_absNorm_eq_37_pow (K := K) P hP I k hI]
    _ = P ^ k := by simp

/-- There is exactly one ideal of norm `37 ^ k`. -/
theorem natCard_normFiber_37_pow (k : ℕ) :
    Nat.card (NormFiber (NumberField.RingOfIntegers K⁺) (37 ^ k)) = 1 := by
  letI : Fintype (NormFiber (NumberField.RingOfIntegers K⁺) (37 ^ k)) :=
    (Ideal.finite_setOf_absNorm_eq (37 ^ k)).fintype
  letI : p37.IsPrime := by
    exact (Ideal.span_singleton_prime (by norm_num : (37 : ℤ) ≠ 0)).2
      (Nat.prime_iff_prime_int.mp (by decide))
  obtain ⟨⟨P, hP⟩⟩ :=
    p37.nonempty_primesOver (S := NumberField.RingOfIntegers K⁺)
  refine Nat.card_eq_one_iff_unique.mpr ⟨⟨?_⟩, ?_⟩
  · intro I J
    apply Subtype.ext
    exact (eq_pow_of_absNorm_eq_37_pow (K := K) P hP I.1 k I.2).trans
      (eq_pow_of_absNorm_eq_37_pow (K := K) P hP J.1 k J.2).symm
  · refine ⟨⟨P ^ k, ?_⟩⟩
    rw [map_pow, absNorm_eq_37_of_mem_primesOver (K := K) hP]

/-- The actual ideal-count coefficient at every power of the ramified prime is
one. -/
theorem idealCount_37_pow (k : ℕ) :
    idealCount K⁺ (37 ^ k) = 1 := by
  change (if 37 ^ k = 0 then 0 else
    (Nat.card (NormFiber (NumberField.RingOfIntegers K⁺) (37 ^ k)) : ℂ)) = 1
  rw [if_neg (pow_ne_zero k (by norm_num : (37 : ℕ) ≠ 0)), natCard_normFiber_37_pow]
  norm_num

/-- A nontrivial character coefficient is one at `37 ^ 0` and vanishes at
every positive power of `37`. -/
theorem characterCoefficient_37_pow
    (chi : {chi : RealResidueGroup37 →* ℂˣ // chi ≠ 1}) (k : ℕ) :
    characterCoefficient chi (37 ^ k) = if k = 0 then 1 else 0 := by
  rcases k with _ | k
  · simp [characterCoefficient, toArithmeticFunction]
  · simp [characterCoefficient, toArithmeticFunction]
    apply MulChar.map_nonunit
    simpa only [isUnit_iff_ne_zero, not_not] using ZMod.natCast_self 37

/-- Convolution by a function supported only at `37 ^ 0` does not change a
second function on powers of `37`. -/
theorem mul_apply_37_pow_of_left_delta
    (f g : ArithmeticFunction ℂ)
    (hf : ∀ i : ℕ, f (37 ^ i) = if i = 0 then 1 else 0)
    (k : ℕ) :
    (f * g) (37 ^ k) = g (37 ^ k) := by
  rw [ArithmeticFunction.mul_apply,
    Nat.sum_divisorsAntidiagonal (fun x y ↦ f x * g y),
    Nat.sum_divisors_prime_pow (by decide : Nat.Prime 37)]
  rw [Finset.sum_eq_single 0]
  · have hfone : f 1 = 1 := by simpa using hf 0
    simp only [pow_zero, Nat.div_one, hfone, one_mul]
  · intro i hi hi0
    rw [hf i, if_neg hi0, zero_mul]
  · simp

/-- The product of all nontrivial character coefficients is supported only at
`37 ^ 0` along the powers of `37`. -/
theorem finset_prod_characterCoefficient_37_pow
    (S : Finset {chi : RealResidueGroup37 →* ℂˣ // chi ≠ 1}) (k : ℕ) :
    (∏ chi ∈ S, characterCoefficient chi : ArithmeticFunction ℂ) (37 ^ k) =
      if k = 0 then 1 else 0 := by
  induction S using Finset.induction_on with
  | empty =>
      rcases k with _ | k
      · simp
      · simp
  | @insert chi S hchi ih =>
      rw [Finset.prod_insert hchi]
      rw [mul_apply_37_pow_of_left_delta _ _ (characterCoefficient_37_pow chi) k]
      exact ih

/-- The character-predicted ideal coefficient at every power of the ramified
prime is one. -/
theorem expectedIdealCount_37_pow (k : ℕ) :
    expectedIdealCount (37 ^ k) = 1 := by
  rw [expectedIdealCount, mul_comm]
  calc
    ((∏ chi : {chi : RealResidueGroup37 →* ℂˣ // chi ≠ 1}, characterCoefficient chi) *
        (ArithmeticFunction.zeta : ArithmeticFunction ℂ)) (37 ^ k) =
        (ArithmeticFunction.zeta : ArithmeticFunction ℂ) (37 ^ k) := by
      apply mul_apply_37_pow_of_left_delta
      intro i
      simpa using finset_prod_characterCoefficient_37_pow
        (Finset.univ : Finset {chi : RealResidueGroup37 →* ℂˣ // chi ≠ 1}) i
    _ = 1 := by simp

/-- The actual and predicted prime-power coefficients agree at the ramified
prime `37`. -/
theorem idealCount_eq_expected_37_pow (k : ℕ) :
    idealCount K⁺ (37 ^ k) = expectedIdealCount (37 ^ k) := by
  rw [idealCount_37_pow, expectedIdealCount_37_pow]

end

end Fermat.Irregular.RamifiedLocalFactor37
