import Fermat.Irregular.VandiverHistoricalStartPrime
import Fermat.Irregular.VandiverHistoricalStatePrime

/-!
# Prime-generic distinguished equation-(8a) ideal

For an odd prime `p = 2*r + 1`, this module constructs the distinguished
residual ideal `J` and the literal real quotient `q` in Vandiver's
equation (8a), and proves

`J^p = (q)`.

Everything here is local factor allocation and ramified-power
bookkeeping.  In particular, no plus-class hypothesis occurs in this
module.  `PlusClassNondivisibility K p` first enters only after the final
theorem below, when one principalizes `J` from `J^p = (q)` and chooses a
generator `ρ` with `q = η * ρ^p`.
-/

namespace Fermat.Irregular.VandiverHistoricalEquationEightAPrime

open scoped NumberField nonZeroDivisors

open Fermat.Irregular.VandiverCriterion
open Fermat.Irregular.VandiverLemmaOne
open Fermat.Irregular.VandiverHistoricalDescent
open Fermat.Irregular.VandiverHistoricalPrime
open Fermat.Irregular.VandiverHistoricalStatePrime

noncomputable section

variable {K : Type} {p r : ℕ} [Fact p.Prime]
  [Field K] [NumberField K] [NumberField.IsCMField K]
  [IsCyclotomicExtension {p} ℚ K]

/-- The fixed-denominator factor at the root `1`; it is
`(ω + θ) / (ζ - 1)`. -/
noncomputable def historicalOneFactor
    (hp2 : p ≠ 2)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ) : 𝓞 K :=
  div_zeta_sub_one hp2 hζ
    (historicalState_regularEquation hζ s)
    (oneNthRoot (K := K) (p := p))

/-- The allocated ideal root of the distinguished factor at `1`. -/
noncomputable def historicalOneFactorIdeal
    (hp2 : p ≠ 2)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ) : Ideal (𝓞 K) :=
  root_div_zeta_sub_one_dvd_gcd hp2 hζ
    (historicalState_regularEquation hζ s)
    (historicalState_theta_not_dvd hζ s)
    (oneNthRoot (K := K) (p := p))

/-- After removing the forced `(ζ - 1)^(2*m - 1)` from the allocated
root at `1`, this is the residual ideal whose generator occurs in
equation (8a). -/
noncomputable def historicalEquationEightAIdeal
    (hp2 : p ≠ 2)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ) : Ideal (𝓞 K) :=
  a_eta_zero_dvd_p_pow hp2 hζ
    (historicalState_regularEquation hζ s)
    (historicalState_theta_not_dvd hζ s)

/-- Multiplying the fixed-denominator factor at `1` back by `ζ - 1`
recovers `ω + θ`. -/
lemma historicalOneFactor_mul_zeta_sub_one
    (hp2 : p ≠ 2)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ) :
    historicalOneFactor hp2 hζ s *
        ((hζ.unit' : 𝓞 K) - 1) =
      s.omega + s.theta := by
  simpa only [historicalOneFactor, oneNthRoot, mul_one] using
    (div_zeta_sub_one_mul_zeta_sub_one hp2 hζ
      (historicalState_regularEquation hζ s)
      (oneNthRoot (K := K) (p := p)))

set_option maxRecDepth 50000 in
/-- The allocated ideal at the root `1` has `p`-th power generated by its
literal fixed-denominator factor. -/
lemma historicalOneFactorIdeal_pow
    (hp2 : p ≠ 2)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ) :
    historicalOneFactorIdeal hp2 hζ s ^ p =
      Ideal.span {historicalOneFactor hp2 hζ s} := by
  exact (linearFactorQuotient_span_eq_factorRoot_pow
    hp2 hζ
    (historicalState_regularEquation hζ s)
    (historicalState_theta_not_dvd hζ s)
    s.coprime_omega_theta
    (oneNthRoot (K := K) (p := p))).symm

/-- The forced ramified part times the residual equation-(8a) ideal is
the allocated ideal at the root `1`. -/
lemma historicalEquationEightAIdeal_spec
    (hp2 : p ≠ 2)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ)
    (hs : RealSourceAdmissible hζ s) :
    Ideal.span ({(hζ.unit' : 𝓞 K) - 1} : Set (𝓞 K)) ^
          (2 * s.m - 1) *
        historicalEquationEightAIdeal hp2 hζ s =
      historicalOneFactorIdeal hp2 hζ s := by
  have hspec := a_eta_zero_dvd_p_pow_spec hp2 hζ
    (historicalState_regularEquation hζ s)
    (historicalState_theta_not_dvd hζ s)
  rw [distinguishedRoot_eq_one_of_real hp2 hζ
    (historicalState_regularEquation hζ s)
    (historicalState_theta_not_dvd hζ s) hs.1 hs.2.1] at hspec
  simpa only [historicalEquationEightAIdeal,
    historicalOneFactorIdeal] using hspec

/-- The real factor `ω + θ` is nonzero in every historical state at an
odd prime. -/
lemma historicalState_omega_add_theta_ne_zero
    (hp2 : p ≠ 2)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ) :
    s.omega + s.theta ≠ 0 := by
  intro hsum
  have htheta : s.theta = -s.omega := by
    linear_combination hsum
  have hkappa0 : kappa hζ ≠ 0 := by
    rw [kappa_eq_kappaUnit_mul_sq]
    exact mul_ne_zero (kappaUnit hζ).isUnit.ne_zero
      (pow_ne_zero 2 (sub_ne_zero.mpr
        (hζ.unit'_coe.ne_one (Fact.out : Nat.Prime p).one_lt)))
  have hrhs :
      (s.eta : 𝓞 K) * (kappa hζ ^ s.m * s.xi) ^ p ≠ 0 :=
    mul_ne_zero s.eta.isUnit.ne_zero
      (pow_ne_zero p
        (mul_ne_zero (pow_ne_zero s.m hkappa0) s.xi_ne_zero))
  apply hrhs
  rw [← s.equation, htheta]
  simp only [Odd.neg_pow
    ((Fact.out : Nat.Prime p).odd_of_ne_two hp2), add_neg_cancel]

/-- If `p = 2*r+1`, the exact `κ`-power displayed in equation (8a)
divides `ω + θ`:

`κ^(p*m-r) ∣ ω+θ`.

The exponent identity is
`2*(p*m-r) = (2*m-1)*p+1`. -/
lemma historicalState_kappaPower_dvd_omega_add_theta
    (hp2 : p ≠ 2) (hr : p = 2 * r + 1)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ)
    (hs : RealSourceAdmissible hζ s) :
    kappa hζ ^ (p * s.m - r) ∣ s.omega + s.theta := by
  let E : ℕ := p * s.m - r
  let N : ℕ := (2 * s.m - 1) * p + 1
  have hexp : 2 * E = N := by
    dsimp [E, N]
    rw [Nat.mul_sub_left_distrib, Nat.mul_sub_right_distrib]
    simp only [one_mul]
    rw [show 2 * (p * s.m) = 2 * s.m * p by ring]
    have hm := s.one_lt_m
    have hlarge : p ≤ 2 * s.m * p := by
      simpa only [one_mul] using
        Nat.mul_le_mul_right p (show 1 ≤ 2 * s.m by omega)
    omega
  have hhigh :=
    historicalState_omega_add_theta_fullHighDivisibility
      hp2 hζ s hs
  obtain ⟨c, hc⟩ := hhigh
  have hcN :
      s.omega + s.theta =
        ((hζ.unit' : 𝓞 K) - 1) ^ N * c := by
    simpa only [N] using hc
  let u : (𝓞 K)ˣ := kappaUnit hζ ^ E
  refine ⟨(u⁻¹ : (𝓞 K)ˣ) * c, ?_⟩
  rw [kappa_pow_eq_kappaUnit_pow_mul, hexp]
  change s.omega + s.theta =
    ((u : 𝓞 K) * ((hζ.unit' : 𝓞 K) - 1) ^ N) *
      ((u⁻¹ : (𝓞 K)ˣ) * c)
  rw [hcN]
  calc
    ((hζ.unit' : 𝓞 K) - 1) ^ N * c =
        (((u : 𝓞 K) * (u⁻¹ : (𝓞 K)ˣ)) *
          ((hζ.unit' : 𝓞 K) - 1) ^ N) * c := by
      rw [← Units.val_mul]
      simp
    _ = ((u : 𝓞 K) * ((hζ.unit' : 𝓞 K) - 1) ^ N) *
        ((u⁻¹ : (𝓞 K)ˣ) * c) := by ring

/-- The literal integral quotient in equation (8a). -/
noncomputable def historicalEquationEightAQuotient
    (hp2 : p ≠ 2) (hr : p = 2 * r + 1)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ)
    (hs : RealSourceAdmissible hζ s) : 𝓞 K :=
  (historicalState_kappaPower_dvd_omega_add_theta
    hp2 hr hζ s hs).choose

/-- Definition equation for the integral quotient in (8a). -/
lemma historicalEquationEightAQuotient_spec
    (hp2 : p ≠ 2) (hr : p = 2 * r + 1)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ)
    (hs : RealSourceAdmissible hζ s) :
    s.omega + s.theta =
      kappa hζ ^ (p * s.m - r) *
        historicalEquationEightAQuotient hp2 hr hζ s hs :=
  (historicalState_kappaPower_dvd_omega_add_theta
    hp2 hr hζ s hs).choose_spec

/-- The quotient occurring in equation (8a) is real. -/
lemma historicalEquationEightAQuotient_real
    (hp2 : p ≠ 2) (hr : p = 2 * r + 1)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ)
    (hs : RealSourceAdmissible hζ s) :
    NumberField.IsCMField.ringOfIntegersComplexConj K
        (historicalEquationEightAQuotient hp2 hr hζ s hs) =
      historicalEquationEightAQuotient hp2 hr hζ s hs := by
  let E : ℕ := p * s.m - r
  let q : 𝓞 K :=
    historicalEquationEightAQuotient hp2 hr hζ s hs
  have hkappa0 : kappa hζ ^ E ≠ 0 := by
    rw [kappa_pow_eq_kappaUnit_pow_mul]
    exact mul_ne_zero (kappaUnit hζ ^ E).isUnit.ne_zero
      (pow_ne_zero (2 * E) (sub_ne_zero.mpr
        (hζ.unit'_coe.ne_one (Fact.out : Nat.Prime p).one_lt)))
  have hq :=
    historicalEquationEightAQuotient_spec hp2 hr hζ s hs
  change s.omega + s.theta = kappa hζ ^ E * q at hq
  apply mul_left_cancel₀ hkappa0
  calc
    kappa hζ ^ E *
        NumberField.IsCMField.ringOfIntegersComplexConj K q =
      NumberField.IsCMField.ringOfIntegersComplexConj K
        (kappa hζ ^ E * q) := by
          rw [map_mul, map_pow,
            Fermat.Irregular.VandiverHistoricalStartPrime.ringOfIntegersComplexConj_kappa
              hζ]
    _ = NumberField.IsCMField.ringOfIntegersComplexConj K
        (s.omega + s.theta) := by rw [← hq]
    _ = s.omega + s.theta := by rw [map_add, hs.1, hs.2.1]
    _ = kappa hζ ^ E * q := hq

/-- The quotient in equation (8a) is nonzero. -/
lemma historicalEquationEightAQuotient_ne_zero
    (hp2 : p ≠ 2) (hr : p = 2 * r + 1)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ)
    (hs : RealSourceAdmissible hζ s) :
    historicalEquationEightAQuotient hp2 hr hζ s hs ≠ 0 := by
  intro hq
  apply historicalState_omega_add_theta_ne_zero hp2 hζ s
  rw [historicalEquationEightAQuotient_spec hp2 hr hζ s hs,
    hq, mul_zero]

/-- Principal-ideal form of the exact ramified exponent in equation
(8a). -/
lemma historical_span_kappaPower
    (hr : p = 2 * r + 1)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ) :
    Ideal.span ({kappa hζ ^ (p * s.m - r)} : Set (𝓞 K)) =
      Ideal.span ({(hζ.unit' : 𝓞 K) - 1} : Set (𝓞 K)) ^
        ((2 * s.m - 1) * p + 1) := by
  let E : ℕ := p * s.m - r
  let N : ℕ := (2 * s.m - 1) * p + 1
  have hexp : 2 * E = N := by
    dsimp [E, N]
    rw [Nat.mul_sub_left_distrib, Nat.mul_sub_right_distrib]
    simp only [one_mul]
    rw [show 2 * (p * s.m) = 2 * s.m * p by ring]
    have hm := s.one_lt_m
    have hlarge : p ≤ 2 * s.m * p := by
      simpa only [one_mul] using
        Nat.mul_le_mul_right p (show 1 ≤ 2 * s.m by omega)
    omega
  rw [show p * s.m - r = E by rfl,
    kappa_pow_eq_kappaUnit_pow_mul, hexp]
  change Ideal.span
      ({((kappaUnit hζ ^ E : (𝓞 K)ˣ) : 𝓞 K) *
        ((hζ.unit' : 𝓞 K) - 1) ^ N} : Set (𝓞 K)) =
    Ideal.span ({(hζ.unit' : 𝓞 K) - 1} : Set (𝓞 K)) ^ N
  rw [← Ideal.span_singleton_mul_span_singleton]
  rw [Ideal.span_singleton_eq_top.mpr
    (kappaUnit hζ ^ E).isUnit, ← Ideal.one_eq_top, one_mul]
  exact
    (Ideal.span_singleton_pow ((hζ.unit' : 𝓞 K) - 1) N).symm

set_option maxRecDepth 50000 in
/-- The residual equation-(8a) ideal has `p`-th power generated by the
literal real quotient `(ω + θ) / κ^(p*m-r)`.

This is the last theorem before plus-class nondivisibility is needed. -/
theorem historicalEquationEightAIdeal_pow
    (hp2 : p ≠ 2) (hr : p = 2 * r + 1)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ)
    (hs : RealSourceAdmissible hζ s) :
    historicalEquationEightAIdeal hp2 hζ s ^ p =
      Ideal.span
        {historicalEquationEightAQuotient hp2 hr hζ s hs} := by
  let P : Ideal (𝓞 K) :=
    Ideal.span ({(hζ.unit' : 𝓞 K) - 1} : Set (𝓞 K))
  let A : Ideal (𝓞 K) := historicalOneFactorIdeal hp2 hζ s
  let J : Ideal (𝓞 K) := historicalEquationEightAIdeal hp2 hζ s
  let qone : 𝓞 K := historicalOneFactor hp2 hζ s
  let qzero : 𝓞 K :=
    historicalEquationEightAQuotient hp2 hr hζ s hs
  let E : ℕ := p * s.m - r
  let d : ℕ := 2 * s.m - 1
  let N : ℕ := d * p + 1
  have hPJ : P ^ d * J = A := by
    simpa only [P, d, J, A] using
      historicalEquationEightAIdeal_spec hp2 hζ s hs
  have hAp : A ^ p = Ideal.span {qone} := by
    simpa only [A, qone] using
      historicalOneFactorIdeal_pow hp2 hζ s
  have hqone :
      qone * ((hζ.unit' : 𝓞 K) - 1) =
        s.omega + s.theta := by
    simpa only [qone] using
      historicalOneFactor_mul_zeta_sub_one hp2 hζ s
  have hqzero :
      s.omega + s.theta = kappa hζ ^ E * qzero := by
    simpa only [E, qzero] using
      historicalEquationEightAQuotient_spec hp2 hr hζ s hs
  have hspanK : Ideal.span {kappa hζ ^ E} = P ^ N := by
    simpa only [E, P, N, d] using
      historical_span_kappaPower hr hζ s
  have hramified :
      P ^ N * J ^ p =
        Ideal.span {s.omega + s.theta} := by
    calc
      P ^ N * J ^ p = P * (P ^ d * J) ^ p := by
        dsimp only [N]
        rw [mul_pow, ← pow_mul]
        rw [pow_succ']
        ring
      _ = P * A ^ p := by rw [hPJ]
      _ = P * Ideal.span {qone} := by rw [hAp]
      _ = Ideal.span
          {((hζ.unit' : 𝓞 K) - 1) * qone} := by
        dsimp only [P]
        rw [Ideal.span_singleton_mul_span_singleton]
      _ = Ideal.span {s.omega + s.theta} := by
        congr 2
        rw [mul_comm, hqone]
  have hspanEq :
      Ideal.span {kappa hζ ^ E} * J ^ p =
        Ideal.span {kappa hζ ^ E} *
          Ideal.span {qzero} := by
    calc
      Ideal.span {kappa hζ ^ E} * J ^ p =
          P ^ N * J ^ p := by rw [hspanK]
      _ = Ideal.span {s.omega + s.theta} := hramified
      _ = Ideal.span {kappa hζ ^ E * qzero} := by rw [hqzero]
      _ = Ideal.span {kappa hζ ^ E} *
          Ideal.span {qzero} :=
        (Ideal.span_singleton_mul_span_singleton _ _).symm
  have hkappa0 : kappa hζ ^ E ≠ 0 := by
    rw [kappa_pow_eq_kappaUnit_pow_mul]
    exact mul_ne_zero (kappaUnit hζ ^ E).isUnit.ne_zero
      (pow_ne_zero (2 * E) (sub_ne_zero.mpr
        (hζ.unit'_coe.ne_one (Fact.out : Nat.Prime p).one_lt)))
  have hspan0 : Ideal.span {kappa hζ ^ E} ≠ 0 := by
    simpa only [ne_eq, Ideal.zero_eq_bot,
      Ideal.span_singleton_eq_bot] using hkappa0
  exact mul_left_cancel₀ hspan0 hspanEq

end

end Fermat.Irregular.VandiverHistoricalEquationEightAPrime
