import Fermat.Irregular.VandiverHistoricalEquationEightAPrime
import Fermat.Irregular.VandiverHistoricalSupportPrime
import Fermat.Irregular.VandiverGeneratorSupportPrime

/-!
# Prime-generic factorization of Vandiver's equation (8a)

This module extracts the factor-allocation and strict-support argument
used in the exponent-specific historical proofs.  For every prime
`p ≠ 2`, the allocated linear factors split `(ξ)` as the distinguished
equation-(8a) ideal times a coprime complement.

For `p ≥ 5`, the complement cannot be the unit ideal.  The proof is
Vandiver's exceptional-case argument: if the factor at `ζ` were a unit,
conjugation would force the rational prime `p` to divide a product
associated to only `(ζ - 1)²`, whereas ramification identifies `(p)`
with `(ζ - 1)^(p-1)`.
-/

namespace Fermat.Irregular.VandiverEquationEightAFactorizationPrime

open scoped NumberField nonZeroDivisors BigOperators
open Polynomial

open Fermat.Irregular.VandiverCriterion
open Fermat.Irregular.VandiverLemmaOne
open Fermat.Irregular.VandiverHistoricalDescent
open Fermat.Irregular.VandiverHistoricalPrime
open Fermat.Irregular.VandiverHistoricalStatePrime
open Fermat.Irregular.VandiverHistoricalEquationEightAPrime
open Fermat.Irregular.VandiverHistoricalSupportPrime
open Fermat.Irregular.VandiverGeneratorSupportPrime
open Fermat.Irregular.VandiverRealNormalizationPrime

noncomputable section

variable {K : Type} {p : ℕ} [Fact p.Prime]
  [Field K] [NumberField K] [NumberField.IsCMField K]
  [IsCyclotomicExtension {p} ℚ K]

/-- The fixed-denominator historical linear factor at `ζ`. -/
noncomputable def historicalZetaFactor
    (hp2 : p ≠ 2)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ) : 𝓞 K :=
  div_zeta_sub_one hp2 hζ
    (historicalState_regularEquation hζ s)
    (zetaNthRoot (K := K) (p := p) hζ)

/-- The allocated ideal root of the historical linear factor at `ζ`. -/
noncomputable def historicalZetaFactorIdeal
    (hp2 : p ≠ 2)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ) : Ideal (𝓞 K) :=
  root_div_zeta_sub_one_dvd_gcd hp2 hζ
    (historicalState_regularEquation hζ s)
    (historicalState_theta_not_dvd hζ s)
    (zetaNthRoot (K := K) (p := p) hζ)

set_option maxRecDepth 50000 in
/-- The allocated ideal at `ζ` has `p`-th power generated by its literal
fixed-denominator factor. -/
lemma historicalZetaFactorIdeal_pow
    (hp2 : p ≠ 2)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ) :
    historicalZetaFactorIdeal hp2 hζ s ^ p =
      Ideal.span {historicalZetaFactor hp2 hζ s} := by
  exact (linearFactorQuotient_span_eq_factorRoot_pow
    hp2 hζ
    (historicalState_regularEquation hζ s)
    (historicalState_theta_not_dvd hζ s)
    s.coprime_omega_theta
    (zetaNthRoot (K := K) (p := p) hζ)).symm

/-- The product of all allocated linear-factor roots other than the
distinguished real root. -/
noncomputable def historicalEquationEightAComplement
    (hp2 : p ≠ 2)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ) : Ideal (𝓞 K) :=
  by
    classical
    let e := historicalState_regularEquation hζ s
    let hy := historicalState_theta_not_dvd hζ s
    let root := fun η : nthRootsFinset p (1 : 𝓞 K) ↦
      root_div_zeta_sub_one_dvd_gcd
        (K := K) (p := p) (x := s.omega) (y := s.theta)
        (z := s.xi) (ε := historicalRegularUnit hζ s)
        (m := 2 * s.m - 1) hp2 hζ e hy η
    let η₀ := zeta_sub_one_dvd_root
      (K := K) (p := p) (x := s.omega) (y := s.theta)
      (z := s.xi) (ε := historicalRegularUnit hζ s)
      (m := 2 * s.m - 1) hp2 hζ e hy
    exact
      ∏ η ∈ Finset.attach (nthRootsFinset p (1 : 𝓞 K)) \ {η₀}, root η

set_option maxRecDepth 50000 in
/-- The allocated roots factor `(ξ)` into the distinguished equation-(8a)
ideal and a coprime complement. -/
theorem historicalEquationEightA_factorization_and_coprime
    (hp2 : p ≠ 2)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ) (hs : RealSourceAdmissible hζ s) :
    Ideal.span {s.xi} =
        historicalEquationEightAIdeal hp2 hζ s *
          historicalEquationEightAComplement hp2 hζ s ∧
      IsCoprime (historicalEquationEightAIdeal hp2 hζ s)
        (historicalEquationEightAComplement hp2 hζ s) := by
  classical
  let e := historicalState_regularEquation hζ s
  let hy := historicalState_theta_not_dvd hζ s
  let π : 𝓞 K := (hζ.unit' : 𝓞 K) - 1
  let P : Ideal (𝓞 K) := Ideal.span {π}
  let M : Ideal (𝓞 K) :=
    gcd (Ideal.span {s.omega}) (Ideal.span {s.theta})
  let Z : Ideal (𝓞 K) :=
    z_div_m (K := K) (p := p)
      (x := s.omega) (y := s.theta) (z := s.xi)
      (ε := historicalRegularUnit hζ s) (m := 2 * s.m - 1)
      hζ e hy
  let root := fun η : nthRootsFinset p (1 : 𝓞 K) ↦
    root_div_zeta_sub_one_dvd_gcd
      (K := K) (p := p) (x := s.omega) (y := s.theta)
      (z := s.xi) (ε := historicalRegularUnit hζ s)
      (m := 2 * s.m - 1) hp2 hζ e hy η
  let c := fun η : nthRootsFinset p (1 : 𝓞 K) ↦
    div_zeta_sub_one_dvd_gcd
      (K := K) (p := p) (x := s.omega) (y := s.theta)
      (z := s.xi) (ε := historicalRegularUnit hζ s)
      (m := 2 * s.m - 1) hp2 hζ e hy η
  let η₀ := zeta_sub_one_dvd_root
    (K := K) (p := p) (x := s.omega) (y := s.theta)
    (z := s.xi) (ε := historicalRegularUnit hζ s)
    (m := 2 * s.m - 1) hp2 hζ e hy
  let Q : Ideal (𝓞 K) :=
    ∏ η ∈ Finset.attach (nthRootsFinset p (1 : 𝓞 K)) \ {η₀}, root η
  have hM : M = 1 := by
    have hcop :
        IsCoprime (Ideal.span {s.omega}) (Ideal.span {s.theta}) :=
      (Ideal.isCoprime_span_singleton_iff _ _).mpr
        s.coprime_omega_theta
    simpa only [M] using (Ideal.isCoprime_iff_gcd.mp hcop)
  have hZ : Z = Ideal.span {s.xi} := by
    have hzspec :
        Ideal.span {s.xi} = M * Z := by
      simpa only [M, Z] using
        (z_div_m_spec (K := K) (p := p)
          (x := s.omega) (y := s.theta) (z := s.xi)
          (ε := historicalRegularUnit hζ s)
          (m := 2 * s.m - 1) hζ e hy)
    rw [hM, one_mul] at hzspec
    exact hzspec.symm
  have hrootpow (η : nthRootsFinset p (1 : 𝓞 K)) :
      root η ^ p = c η := by
    simpa only [root, c] using
      (root_div_zeta_sub_one_dvd_gcd_spec
        (K := K) (p := p) (x := s.omega) (y := s.theta)
        (z := s.xi) (ε := historicalRegularUnit hζ s)
        (m := 2 * s.m - 1) hp2 hζ e hy η)
  have hprodC :
      ∏ η ∈ Finset.attach (nthRootsFinset p (1 : 𝓞 K)), c η =
        (Z * P ^ (2 * s.m - 1)) ^ p := by
    simpa only [c, Z, P, π] using
      (prod_c (K := K) (p := p)
        (x := s.omega) (y := s.theta) (z := s.xi)
        (ε := historicalRegularUnit hζ s)
        (m := 2 * s.m - 1) hp2 hζ e hy)
  have hprodRootPow :
      (∏ η ∈ Finset.attach (nthRootsFinset p (1 : 𝓞 K)),
          root η) ^ p =
        (Z * P ^ (2 * s.m - 1)) ^ p := by
    rw [← Finset.prod_pow]
    simpa only [hrootpow] using hprodC
  have hprodRoot :
      ∏ η ∈ Finset.attach (nthRootsFinset p (1 : 𝓞 K)), root η =
        Z * P ^ (2 * s.m - 1) :=
    pow_left_injective (M := Ideal (𝓞 K))
      (Fact.out : Nat.Prime p).ne_zero hprodRootPow
  have hη₀one :
      η₀ = oneNthRoot (K := K) (p := p) := by
    simpa only [η₀, e, hy] using
      distinguishedRoot_eq_one_of_real hp2 hζ e hy hs.1 hs.2.1
  have hrootη₀ :
      root η₀ = historicalOneFactorIdeal hp2 hζ s := by
    rw [hη₀one]
    rfl
  have hsplit :
      root η₀ * Q = Z * P ^ (2 * s.m - 1) := by
    rw [← hprodRoot]
    dsimp only [Q]
    exact (Finset.prod_eq_mul_prod_diff_singleton_of_mem
      (Finset.mem_attach _ η₀) root).symm
  have hspec :
      P ^ (2 * s.m - 1) *
          historicalEquationEightAIdeal hp2 hζ s =
        root η₀ := by
    rw [hrootη₀]
    simpa only [P, π] using
      historicalEquationEightAIdeal_spec hp2 hζ s hs
  have hP0 : P ^ (2 * s.m - 1) ≠ 0 := by
    apply pow_ne_zero
    dsimp [P, π]
    simpa only [Ideal.zero_eq_bot, ne_eq,
      Ideal.span_singleton_eq_bot] using
      hζ.unit'_coe.sub_one_ne_zero (Fact.out : Nat.Prime p).one_lt
  have hfactor :
      Ideal.span {s.xi} =
        historicalEquationEightAIdeal hp2 hζ s * Q := by
    apply mul_left_cancel₀ hP0
    symm
    calc
      P ^ (2 * s.m - 1) *
          (historicalEquationEightAIdeal hp2 hζ s * Q) =
          (P ^ (2 * s.m - 1) *
            historicalEquationEightAIdeal hp2 hζ s) * Q := by
              rw [mul_assoc]
      _ = root η₀ * Q := by rw [hspec]
      _ = Z * P ^ (2 * s.m - 1) := hsplit
      _ = P ^ (2 * s.m - 1) * Ideal.span {s.xi} := by
        rw [hZ]
        ac_rfl
  have hcop :
      IsCoprime (historicalEquationEightAIdeal hp2 hζ s) Q := by
    apply IsCoprime.prod_right
    intro η hη
    simp only [Finset.mem_sdiff, Finset.mem_singleton] at hη
    have hc :
        IsCoprime (c η₀) (c η) := by
      exact coprime_c (K := K) (p := p)
        (x := s.omega) (y := s.theta) (z := s.xi)
        (ε := historicalRegularUnit hζ s)
        (m := 2 * s.m - 1) hp2 hζ e hy
        η₀ η (Ne.symm hη.2)
    rw [← hrootpow η₀, ← hrootpow η] at hc
    have hroots : IsCoprime (root η₀) (root η) :=
      (IsCoprime.pow_left_iff (Fact.out : Nat.Prime p).pos).mp
        ((IsCoprime.pow_right_iff
          (Fact.out : Nat.Prime p).pos).mp hc)
    rw [← hspec] at hroots
    exact hroots.of_mul_left_right
  simpa only [historicalEquationEightAComplement, e, hy, root, η₀, Q] using
    And.intro hfactor hcop

set_option maxRecDepth 50000 in
/-- For every prime `p ≥ 5`, the complement in the equation-(8a)
factorization is nontrivial.

The only numerical input is the inequality `p - 1 > 2`.  All divisibility
depth is supplied by the prime-generic historical state. -/
theorem historicalEquationEightAComplement_ne_top
    (hp5 : 5 ≤ p)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ) (hs : RealSourceAdmissible hζ s) :
    historicalEquationEightAComplement (by omega : p ≠ 2) hζ s ≠ ⊤ := by
  classical
  have hp2 : p ≠ 2 := by omega
  have hcop2 : Nat.Coprime 2 p := by
    exact
      ((Fact.out : Nat.Prime p).coprime_iff_not_dvd.mpr (by
        intro hdvd
        have hle : p ≤ 2 := Nat.le_of_dvd (by norm_num) hdvd
        omega)).symm
  intro hQtop
  let e := historicalState_regularEquation hζ s
  let hy := historicalState_theta_not_dvd hζ s
  let π : 𝓞 K := (hζ.unit' : 𝓞 K) - 1
  let root := fun η : nthRootsFinset p (1 : 𝓞 K) ↦
    root_div_zeta_sub_one_dvd_gcd
      (K := K) (p := p) (x := s.omega) (y := s.theta)
      (z := s.xi) (ε := historicalRegularUnit hζ s)
      (m := 2 * s.m - 1) hp2 hζ e hy η
  let η₀ := zeta_sub_one_dvd_root
    (K := K) (p := p) (x := s.omega) (y := s.theta)
    (z := s.xi) (ε := historicalRegularUnit hζ s)
    (m := 2 * s.m - 1) hp2 hζ e hy
  let ηζ : nthRootsFinset p (1 : 𝓞 K) :=
    zetaNthRoot (K := K) (p := p) hζ
  have hη₀one :
      η₀ = oneNthRoot (K := K) (p := p) := by
    simpa only [η₀, e, hy] using
      distinguishedRoot_eq_one_of_real hp2 hζ e hy hs.1 hs.2.1
  have hηζ_ne : ηζ ≠ η₀ := by
    rw [hη₀one]
    intro h
    have hv := congrArg
      (fun x : nthRootsFinset p (1 : 𝓞 K) ↦ (x : 𝓞 K)) h
    exact hζ.unit'_coe.ne_one (Fact.out : Nat.Prime p).one_lt hv
  have hηζmem :
      ηζ ∈
        Finset.attach (nthRootsFinset p (1 : 𝓞 K)) \ {η₀} := by
    simp only [Finset.mem_sdiff, Finset.mem_attach,
      Finset.mem_singleton, true_and]
    exact hηζ_ne
  have hrootDvd :
      root ηζ ∣ historicalEquationEightAComplement hp2 hζ s := by
    simpa only [historicalEquationEightAComplement, e, hy, root, η₀] using
      (Finset.dvd_prod_of_mem root hηζmem)
  have hrootUnit : IsUnit (root ηζ) := by
    apply isUnit_of_dvd_one
    simpa only [hQtop, Ideal.one_eq_top] using hrootDvd
  have hrootTop : root ηζ = ⊤ := by
    simpa only [Ideal.isUnit_iff] using hrootUnit
  have hfactorIdealTop :
      historicalZetaFactorIdeal hp2 hζ s = ⊤ := by
    simpa only [root, ηζ, historicalZetaFactorIdeal] using hrootTop
  have hqspan :
      Ideal.span {historicalZetaFactor hp2 hζ s} = ⊤ := by
    rw [← historicalZetaFactorIdeal_pow hp2 hζ s, hfactorIdealTop]
    simp
  have hqunit :
      IsUnit (historicalZetaFactor hp2 hζ s) :=
    Ideal.span_singleton_eq_top.mp hqspan
  let qUnit : (𝓞 K)ˣ := hqunit.unit
  let A : (𝓞 K)ˣ := -qUnit
  let B : (𝓞 K)ˣ := NumberField.IsCMField.unitsComplexConj K A
  have hqUnitVal :
      (qUnit : 𝓞 K) = historicalZetaFactor hp2 hζ s :=
    hqunit.unit_spec
  have hAval :
      (A : 𝓞 K) = -historicalZetaFactor hp2 hζ s := by
    dsimp [A]
    exact congrArg Neg.neg hqUnitVal
  have hone :
      s.omega + (hζ.unit' : 𝓞 K) * s.theta =
        (1 - (hζ.unit' : 𝓞 K)) * (A : 𝓞 K) := by
    have hqmul :
        historicalZetaFactor hp2 hζ s * π =
          s.omega + s.theta * (hζ.unit' : 𝓞 K) :=
      div_zeta_sub_one_mul_zeta_sub_one hp2 hζ
        (historicalState_regularEquation hζ s)
        (zetaNthRoot (K := K) (p := p) hζ)
    dsimp [π] at hqmul
    calc
      s.omega + (hζ.unit' : 𝓞 K) * s.theta =
          s.omega + s.theta * (hζ.unit' : 𝓞 K) := by ring
      _ = historicalZetaFactor hp2 hζ s *
          ((hζ.unit' : 𝓞 K) - 1) := hqmul.symm
      _ = (1 - (hζ.unit' : 𝓞 K)) * (A : 𝓞 K) := by
        rw [hAval]
        ring
  have hconjζ :
      NumberField.IsCMField.ringOfIntegersComplexConj K
          (hζ.unit' : 𝓞 K) =
        (hζ.unit'⁻¹ : (𝓞 K)ˣ) :=
    congrArg ((↑) : (𝓞 K)ˣ → 𝓞 K)
      (unitsComplexConj_zeta hζ)
  have hBval :
      (B : 𝓞 K) =
        NumberField.IsCMField.ringOfIntegersComplexConj K (A : 𝓞 K) :=
    rfl
  have hminus :
      s.omega + (hζ.unit'⁻¹ : (𝓞 K)ˣ) * s.theta =
        (1 - (hζ.unit'⁻¹ : (𝓞 K)ˣ)) * (B : 𝓞 K) := by
    have hc := congrArg
      (NumberField.IsCMField.ringOfIntegersComplexConj K) hone
    simpa only [map_add, map_mul, map_sub, map_one,
      hs.1, hs.2.1, hconjζ, hBval] using hc
  obtain ⟨j, hj⟩ :=
    unit_inv_conj_is_root_of_unity hζ A (by omega)
  let r : (𝓞 K)ˣ := (hζ.unit' ^ j) ^ 2
  have hAB : A = r * B := by
    calc
      A = (A * B⁻¹) * B := by simp
      _ = r * B := by simpa only [B, r] using congrArg (· * B) hj
  have hABval : (A : 𝓞 K) = (r : 𝓞 K) * (B : 𝓞 K) :=
    congrArg ((↑) : (𝓞 K)ˣ → 𝓞 K) hAB
  have hzinv :
      (hζ.unit' : 𝓞 K) *
          (hζ.unit'⁻¹ : (𝓞 K)ˣ) = 1 := by
    rw [← Units.val_mul]
    simp
  have hminusZ :
      (hζ.unit' : 𝓞 K) * s.omega + s.theta =
        -(1 - (hζ.unit' : 𝓞 K)) * (B : 𝓞 K) := by
    calc
      (hζ.unit' : 𝓞 K) * s.omega + s.theta =
          (hζ.unit' : 𝓞 K) *
            (s.omega +
              (hζ.unit'⁻¹ : (𝓞 K)ˣ) * s.theta) := by
        rw [mul_add, ← mul_assoc, hzinv, one_mul]
      _ = (hζ.unit' : 𝓞 K) *
          ((1 - (hζ.unit'⁻¹ : (𝓞 K)ˣ)) * (B : 𝓞 K)) := by
            rw [hminus]
      _ = -(1 - (hζ.unit' : 𝓞 K)) * (B : 𝓞 K) := by
        calc
          _ = ((hζ.unit' : 𝓞 K) -
              (hζ.unit' : 𝓞 K) *
                (hζ.unit'⁻¹ : (𝓞 K)ˣ)) * (B : 𝓞 K) := by ring
          _ = ((hζ.unit' : 𝓞 K) - 1) * (B : 𝓞 K) := by
            rw [hzinv]
          _ = _ := by ring
  have honeR :
      s.omega + (hζ.unit' : 𝓞 K) * s.theta =
        (1 - (hζ.unit' : 𝓞 K)) *
          ((r : 𝓞 K) * (B : 𝓞 K)) := by
    rw [← hABval]
    exact hone
  have hsum :
      (1 + (hζ.unit' : 𝓞 K)) * (s.omega + s.theta) =
        (1 - (hζ.unit' : 𝓞 K)) *
          ((r : 𝓞 K) - 1) * (B : 𝓞 K) := by
    linear_combination honeR + hminusZ
  have hidentity :
      (1 - (r : 𝓞 K)) *
          (1 - (hζ.unit' : 𝓞 K)) * (B : 𝓞 K) =
        -(1 + (hζ.unit' : 𝓞 K)) * (s.omega + s.theta) := by
    calc
      _ = -((1 - (hζ.unit' : 𝓞 K)) *
          ((r : 𝓞 K) - 1) * (B : 𝓞 K)) := by ring
      _ = -((1 + (hζ.unit' : 𝓞 K)) *
          (s.omega + s.theta)) :=
        congrArg Neg.neg hsum.symm
      _ = -(1 + (hζ.unit' : 𝓞 K)) *
          (s.omega + s.theta) := by rw [neg_mul]
  have hr_ne : (r : 𝓞 K) ≠ 1 := by
    intro hr
    have hzero :
        (1 + (hζ.unit' : 𝓞 K)) *
          (s.omega + s.theta) = 0 := by
      have h := hidentity
      rw [hr] at h
      linear_combination h
    have hplusUnit :
        IsUnit ((1 : 𝓞 K) + hζ.unit') := by
      simpa [add_comm] using
        hζ.unit'_coe.geom_sum_isUnit (by omega) hcop2
    exact historicalState_omega_add_theta_ne_zero hp2 hζ s
      ((mul_eq_zero.mp hzero).resolve_left hplusUnit.ne_zero)
  have hpsum : (p : 𝓞 K) ∣ s.omega + s.theta := by
    have hfull :=
      historicalState_omega_add_theta_fullHighDivisibility
        hp2 hζ s hs
    have hexp :
        p - 1 ≤ (2 * s.m - 1) * p + 1 := by
      have hm := s.one_lt_m
      have hcoef : 1 ≤ 2 * s.m - 1 := by omega
      have hpmul : p ≤ (2 * s.m - 1) * p := by
        simpa only [one_mul] using Nat.mul_le_mul_right p hcoef
      omega
    have hpm1 :
        π ^ (p - 1) ∣ s.omega + s.theta :=
      (pow_dvd_pow π hexp).trans
        (by simpa only [π] using hfull)
    exact ((associated_zeta_sub_one_pow_prime hζ).dvd_iff_dvd_left).mp
      (by simpa only [π] using hpm1)
  have hpprod :
      (p : 𝓞 K) ∣
        (1 - (r : 𝓞 K)) *
          (1 - (hζ.unit' : 𝓞 K)) := by
    have hwithB :
        (p : 𝓞 K) ∣
          ((1 - (r : 𝓞 K)) *
            (1 - (hζ.unit' : 𝓞 K))) * (B : 𝓞 K) := by
      rw [hidentity]
      exact dvd_mul_of_dvd_right hpsum _
    exact (B.isUnit.dvd_mul_right).mp hwithB
  have hrpow : (r : 𝓞 K) ^ p = 1 := by
    change ((((hζ.unit' : 𝓞 K) ^ j) ^ 2) ^ p) = 1
    rw [← pow_mul, ← pow_mul]
    rw [show j * (2 * p) = p * (j * 2) by ring, pow_mul,
      hζ.unit'_coe.pow_eq_one, one_pow]
  let ηr : nthRootsFinset p (1 : 𝓞 K) :=
    ⟨(r : 𝓞 K), by
      rw [Polynomial.mem_nthRootsFinset
        (Fact.out : Nat.Prime p).pos]
      exact hrpow⟩
  let ηone : nthRootsFinset p (1 : 𝓞 K) :=
    oneNthRoot (K := K) (p := p)
  have hηr_ne : (ηr : 𝓞 K) ≠ (ηone : 𝓞 K) := by
    simpa only [ηr, ηone, oneNthRoot] using hr_ne
  have hrAssocSub :
      Associated ((r : 𝓞 K) - 1) π := by
    simpa only [ηr, ηone, oneNthRoot, π] using
      (hζ.unit'_coe.ntRootsFinset_pairwise_associated_sub_one_sub_of_prime
        (Fact.out : Nat.Prime p) ηr.prop ηone.prop hηr_ne).symm
  have hrAssoc :
      Associated (1 - (r : 𝓞 K)) π := by
    have hneg :
        Associated (-((r : 𝓞 K) - 1)) ((r : 𝓞 K) - 1) := by
      simpa only [Units.val_neg, Units.val_one, neg_mul, one_mul] using
        associated_unit_mul_left
          ((r : 𝓞 K) - 1)
          ((-1 : (𝓞 K)ˣ) : 𝓞 K) (-1 : (𝓞 K)ˣ).isUnit
    simpa only [neg_sub] using hneg.trans hrAssocSub
  have hzAssoc :
      Associated (1 - (hζ.unit' : 𝓞 K)) π := by
    simpa only [π, pow_one, Units.val_one, mul_one] using
      associated_one_sub_zetaPow_mul_unit hζ 1
        (by norm_num) (by omega) (1 : (𝓞 K)ˣ)
  have hprodAssoc :
      Associated
        ((1 - (r : 𝓞 K)) * (1 - (hζ.unit' : 𝓞 K)))
        (π ^ 2) := by
    simpa only [pow_two] using hrAssoc.mul_mul hzAssoc
  have hπpm1prod :
      π ^ (p - 1) ∣
        (1 - (r : 𝓞 K)) * (1 - (hζ.unit' : 𝓞 K)) := by
    exact ((associated_zeta_sub_one_pow_prime hζ).dvd_iff_dvd_left).mpr
      (by simpa only [π] using hpprod)
  have hbad : π ^ (p - 1) ∣ π ^ 2 :=
    (hprodAssoc.dvd_iff_dvd_right).mp hπpm1prod
  have hle :
      p - 1 ≤ 2 :=
    (pow_dvd_pow_iff
      (hζ.unit'_coe.sub_one_ne_zero
        (Fact.out : Nat.Prime p).one_lt)
      hζ.zeta_sub_one_prime'.not_unit).mp
        (by simpa only [π] using hbad)
  omega

/-- The historical allocation supplies the strict support drop for the
square of any chosen generator of equation (8a). -/
theorem historicalEquationEightA_square_support_strict_unconditional
    (hp5 : 5 ≤ p)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (s : HistoricalState hζ) (hs : RealSourceAdmissible hζ s)
    (ρzero : 𝓞 K)
    (hgenerator :
      historicalEquationEightAIdeal (by omega : p ≠ 2) hζ s =
        Ideal.span {ρzero}) :
    primeIdealFactorSupport (ρzero ^ 2) ⊂
      primeIdealFactorSupport s.xi := by
  have hp2 : p ≠ 2 := by omega
  obtain ⟨hfactor, hcop⟩ :=
    historicalEquationEightA_factorization_and_coprime
      hp2 hζ s hs
  exact square_support_strict_of_generator
    s.xi_ne_zero hgenerator hfactor
    (historicalEquationEightAComplement_ne_top hp5 hζ s hs) hcop

end

end Fermat.Irregular.VandiverEquationEightAFactorizationPrime
