import Fermat.Irregular.VandiverEquationNinePrime
import Fermat.Irregular.VandiverTakagiPairPrime
import Fermat.Irregular.VandiverRealEquationNineGeneratorPrime

/-!
# Prime-generic algebra after Vandiver's equation (9a)

This module packages the normalized difference equation, its literal
fixed-denominator quotient, and the local congruences used to absorb a real
principal generator into both members of a conjugate pair.

The global generator input is isolated as
`RealEquationNineGeneratorExtraction`: the exact statement that the
nonramified real quotient ideal has a real generator.  It can either be
supplied explicitly or constructed below from plus-class
nondivisibility.  The quotient construction and all congruence algebra
below do not assume an unconditional Takagi theorem.
-/

namespace Fermat.Irregular.VandiverPostEquationNinePrime

open scoped NumberField nonZeroDivisors

open Fermat.Irregular.VandiverCriterion
open Fermat.Irregular.VandiverLemmaOne
open Fermat.Irregular.VandiverHistoricalPrime
open Fermat.Irregular.VandiverRealNormalizationPrime
open Fermat.Irregular.VandiverRealEquationNineGeneratorPrime

noncomputable section

variable {K : Type} {p : ℕ} [Fact p.Prime]
  [Field K] [NumberField K] [NumberField.IsCMField K]
  [IsCyclotomicExtension {p} ℚ K]

/-- The exact global generator input used after equation (9a). -/
def RealEquationNineGeneratorExtraction
    {ζ : K} (hζ : IsPrimitiveRoot ζ p) : Prop :=
  ∀ (J : Ideal (𝓞 K)) (q : 𝓞 K),
    (¬ Ideal.span
        ({(hζ.unit' : 𝓞 K) - 1} : Set (𝓞 K)) ∣ J) →
    NumberField.IsCMField.ringOfIntegersComplexConj K q = q →
    J ^ p = Ideal.span {q} →
    ∃ (mu : 𝓞 K) (eta : (𝓞 K)ˣ),
      J = Ideal.span {mu} ∧
      NumberField.IsCMField.ringOfIntegersComplexConj K mu = mu ∧
      q = eta * mu ^ p

/-- Plus-class nondivisibility discharges the real-generator interface.
This is the reusable prime-generic form of the theorem formerly repeated
for exponents `587` and `691`. -/
theorem realEquationNineGeneratorExtraction
    (hplus : PlusClassNondivisibility K p)
    (hp2 : 2 < p) (hcop2 : Nat.Coprime 2 p)
    {r : ℕ} (hr : p = 2 * r + 1)
    {ζ : K} (hζ : IsPrimitiveRoot ζ p) :
    RealEquationNineGeneratorExtraction hζ := by
  intro J q hprime hqreal hpow
  exact
    exists_realEquationNineGenerator
      hplus hp2 hcop2 hr hζ J q hprime hqreal hpow

/-- A normalized pair immediately after equation (9a), together with the
source equation needed to allocate its fixed-denominator factor. -/
structure PostEquationNineNormalizedData
    {ζ : K} (hζ : IsPrimitiveRoot ζ p) where
  m : ℕ
  one_lt_m : 1 < m
  rplus : 𝓞 K
  rminus : 𝓞 K
  rzero : 𝓞 K
  epsilon : (𝓞 K)ˣ
  equation :
    rplus ^ p - rminus ^ p =
      epsilon *
        (((hζ.unit' : 𝓞 K) - 1) ^ (2 * m - 1) * rzero) ^ p
  conjugate :
    NumberField.IsCMField.ringOfIntegersComplexConj K rplus = rminus
  coprime : IsCoprime rplus rminus
  rminus_not_ramified :
    ¬ (hζ.unit' : 𝓞 K) - 1 ∣ rminus
  depth : ℕ
  two_le_depth : 2 ≤ depth
  close :
    ((hζ.unit' : 𝓞 K) - 1) ^ depth ∣ rplus - rminus

namespace PostEquationNineNormalizedData

variable {ζ : K} (hζ : IsPrimitiveRoot ζ p)
  (d : PostEquationNineNormalizedData hζ)

lemma regularEquation
    (hp2 : p ≠ 2) :
    d.rplus ^ p + (-d.rminus) ^ p =
      d.epsilon *
        (((hζ.unit' : 𝓞 K) - 1) ^ ((2 * d.m - 2) + 1) *
          d.rzero) ^ p := by
  have hexp : 2 * d.m - 1 = (2 * d.m - 2) + 1 := by
    have hm := d.one_lt_m
    omega
  rw [← hexp]
  simpa only [Odd.neg_pow
    ((Fact.out : Nat.Prime p).odd_of_ne_two hp2),
    sub_eq_add_neg] using d.equation

lemma neg_rminus_not_ramified :
    ¬ (hζ.unit' : 𝓞 K) - 1 ∣ -d.rminus := by
  simpa using d.rminus_not_ramified

/-- Vandiver's literal quotient
`(rplus - ζ*rminus)/(1-ζ)`. -/
noncomputable def quotient
    (hp2 : p ≠ 2) : 𝓞 K :=
  -div_zeta_sub_one hp2 hζ
    (d.regularEquation hζ hp2)
    (zetaNthRoot (K := K) (p := p) hζ)

/-- The allocated ideal whose `p`-th power is generated by `quotient`. -/
noncomputable def quotientIdeal
    (hp2 : p ≠ 2) : Ideal (𝓞 K) :=
  root_div_zeta_sub_one_dvd_gcd hp2 hζ
    (d.regularEquation hζ hp2)
    (d.neg_rminus_not_ramified hζ)
    (zetaNthRoot (K := K) (p := p) hζ)

lemma quotient_mul_one_sub_zeta
    (hp2 : p ≠ 2) :
    quotient hζ d hp2 * (1 - (hζ.unit' : 𝓞 K)) =
      d.rplus - (hζ.unit' : 𝓞 K) * d.rminus := by
  have hmul := div_zeta_sub_one_mul_zeta_sub_one
    hp2 hζ (d.regularEquation hζ hp2)
    (zetaNthRoot (K := K) (p := p) hζ)
  calc
    quotient hζ d hp2 * (1 - (hζ.unit' : 𝓞 K)) =
        div_zeta_sub_one hp2 hζ
          (d.regularEquation hζ hp2)
          (zetaNthRoot (K := K) (p := p) hζ) *
            ((hζ.unit' : 𝓞 K) - 1) := by
      dsimp [quotient]
      ring
    _ = d.rplus +
        (-d.rminus) *
          (zetaNthRoot (K := K) (p := p) hζ : 𝓞 K) := hmul
    _ = d.rplus - (hζ.unit' : 𝓞 K) * d.rminus := by
      dsimp [zetaNthRoot]
      ring

lemma quotientIdeal_pow
    (hp2 : p ≠ 2) :
    quotientIdeal hζ d hp2 ^ p =
      Ideal.span {quotient hζ d hp2} := by
  have hpow := linearFactorQuotient_span_eq_factorRoot_pow
    hp2 hζ (d.regularEquation hζ hp2)
    (d.neg_rminus_not_ramified hζ)
    d.coprime.neg_right
    (zetaNthRoot (K := K) (p := p) hζ)
  calc
    quotientIdeal hζ d hp2 ^ p =
        Ideal.span
          {div_zeta_sub_one hp2 hζ
            (d.regularEquation hζ hp2)
            (zetaNthRoot (K := K) (p := p) hζ)} := hpow.symm
    _ = Ideal.span {quotient hζ d hp2} := by
      apply Ideal.span_singleton_eq_span_singleton.mpr
      refine ⟨-1, ?_⟩
      simp [quotient]

lemma quotient_real
    (hp2 : p ≠ 2) :
    NumberField.IsCMField.ringOfIntegersComplexConj K
        (quotient hζ d hp2) =
      quotient hζ d hp2 := by
  let q : 𝓞 K := quotient hζ d hp2
  let t : 𝓞 K := (hζ.unit' : 𝓞 K)
  have htinv : t * (hζ.unit'⁻¹ : (𝓞 K)ˣ) = 1 := by
    dsimp [t]
    rw [← Units.val_mul]
    simp
  have ht0 : 1 - t ≠ 0 := by
    dsimp [t]
    exact sub_ne_zero.mpr
      (hζ.unit'_coe.ne_one (Fact.out : Nat.Prime p).one_lt).symm
  have hconjt :
      NumberField.IsCMField.ringOfIntegersComplexConj K t =
        (hζ.unit'⁻¹ : (𝓞 K)ˣ) := by
    exact congrArg ((↑) : (𝓞 K)ˣ → 𝓞 K)
      (unitsComplexConj_zeta hζ)
  have hconjminus :
      NumberField.IsCMField.ringOfIntegersComplexConj K d.rminus =
        d.rplus := by
    have hcc :
        NumberField.IsCMField.ringOfIntegersComplexConj K
          (NumberField.IsCMField.ringOfIntegersComplexConj K
            d.rplus) =
          d.rplus := by
      ext
      exact NumberField.IsCMField.complexConj_apply_apply K d.rplus
    rw [d.conjugate] at hcc
    exact hcc
  have hq :
      q * (1 - t) =
        d.rplus - t * d.rminus := by
    simpa only [q, t] using d.quotient_mul_one_sub_zeta hζ hp2
  have hc := congrArg
    (NumberField.IsCMField.ringOfIntegersComplexConj K) hq
  have hc' :
      NumberField.IsCMField.ringOfIntegersComplexConj K q *
          (1 - (hζ.unit'⁻¹ : (𝓞 K)ˣ)) =
        d.rminus -
          (hζ.unit'⁻¹ : (𝓞 K)ˣ) * d.rplus := by
    simpa only [map_mul, map_sub, map_one, hconjt, d.conjugate,
      hconjminus] using hc
  have hden :
      1 - t =
        (-t) * (1 - (hζ.unit'⁻¹ : (𝓞 K)ˣ)) := by
    calc
      1 - t = -t + 1 := by ring
      _ = -t + t * (hζ.unit'⁻¹ : (𝓞 K)ˣ) := by rw [htinv]
      _ = (-t) * (1 - (hζ.unit'⁻¹ : (𝓞 K)ˣ)) := by ring
  apply mul_right_cancel₀ ht0
  calc
    NumberField.IsCMField.ringOfIntegersComplexConj K q *
          (1 - t) =
        NumberField.IsCMField.ringOfIntegersComplexConj K q *
          ((-t) * (1 - (hζ.unit'⁻¹ : (𝓞 K)ˣ))) := by
      rw [hden]
    _ = (-t) *
          (NumberField.IsCMField.ringOfIntegersComplexConj K q *
            (1 - (hζ.unit'⁻¹ : (𝓞 K)ˣ))) := by ring
    _ = (-t) *
        (d.rminus -
          (hζ.unit'⁻¹ : (𝓞 K)ˣ) * d.rplus) := by
      rw [hc']
    _ = d.rplus - t * d.rminus := by
      rw [mul_sub, neg_mul, neg_mul, ← mul_assoc, htinv, one_mul]
      ring
    _ = q * (1 - t) := hq.symm

/-- The quotient differs from the normalized inverse root by one fewer
power of the uniformizer. -/
lemma pow_pred_dvd_rminus_sub_quotient
    (hp2 : p ≠ 2) :
    ((hζ.unit' : 𝓞 K) - 1) ^ (d.depth - 1) ∣
      d.rminus - quotient hζ d hp2 := by
  let pi : 𝓞 K := (hζ.unit' : 𝓞 K) - 1
  let q : 𝓞 K := quotient hζ d hp2
  have hpi0 : pi ≠ 0 :=
    hζ.unit'_coe.sub_one_ne_zero
      (Fact.out : Nat.Prime p).one_lt
  have hq :
      q * (1 - (hζ.unit' : 𝓞 K)) =
        d.rplus - (hζ.unit' : 𝓞 K) * d.rminus := by
    simpa only [q] using d.quotient_mul_one_sub_zeta hζ hp2
  have hqpi :
      q * pi =
        -(d.rplus - (hζ.unit' : 𝓞 K) * d.rminus) := by
    calc
      q * pi = -(q * (1 - (hζ.unit' : 𝓞 K))) := by
        dsimp [pi]
        ring
      _ = -(d.rplus -
          (hζ.unit' : 𝓞 K) * d.rminus) := by rw [hq]
  have hmul :
      (d.rminus - q) * pi = d.rplus - d.rminus := by
    rw [sub_mul, hqpi]
    dsimp [pi]
    ring
  obtain ⟨c, hc⟩ := d.close
  refine ⟨c, ?_⟩
  apply mul_right_cancel₀ hpi0
  calc
    (d.rminus - q) * pi = d.rplus - d.rminus := hmul
    _ = pi ^ d.depth * c := by simpa only [pi] using hc
    _ = (pi ^ (d.depth - 1) * c) * pi := by
      have hdepth : d.depth = (d.depth - 1) + 1 := by
        have hd := d.two_le_depth
        omega
      have hpow :
          pi ^ d.depth = pi ^ (d.depth - 1) * pi := by
        have hpow' :
            pi ^ d.depth =
              pi ^ ((d.depth - 1) + 1) :=
          congrArg (fun n : ℕ ↦ pi ^ n) hdepth
        calc
          pi ^ d.depth =
              pi ^ ((d.depth - 1) + 1) := hpow'
          _ = pi ^ (d.depth - 1) * pi := pow_succ _ _
      rw [hpow]
      ring

lemma quotient_not_ramified
    (hp2 : p ≠ 2) :
    ¬ (hζ.unit' : 𝓞 K) - 1 ∣ quotient hζ d hp2 := by
  intro hq
  apply d.rminus_not_ramified
  have hpredPos : d.depth - 1 ≠ 0 := by
    have hd := d.two_le_depth
    omega
  have hdiff :
      (hζ.unit' : 𝓞 K) - 1 ∣
        d.rminus - quotient hζ d hp2 :=
    (dvd_pow_self ((hζ.unit' : 𝓞 K) - 1) hpredPos).trans
      (d.pow_pred_dvd_rminus_sub_quotient hζ hp2)
  have hadd := dvd_add hdiff hq
  convert hadd using 1
  ring

lemma quotientIdeal_not_ramified
    (hp2 : p ≠ 2) :
    ¬ Ideal.span
        ({(hζ.unit' : 𝓞 K) - 1} : Set (𝓞 K)) ∣
      quotientIdeal hζ d hp2 := by
  intro hJ
  apply d.quotient_not_ramified hζ hp2
  rw [← Ideal.mem_span_singleton, ← Ideal.dvd_span_singleton,
    ← d.quotientIdeal_pow hζ hp2]
  exact dvd_pow (n := p) hJ (Fact.out : Nat.Prime p).ne_zero

/-- The complete post-(9) generator extraction, parameterized only by the
explicit global generator interface. -/
theorem exists_real_generator
    (hp2 : p ≠ 2)
    (hextract : RealEquationNineGeneratorExtraction hζ) :
    ∃ (mu : 𝓞 K) (eta : (𝓞 K)ˣ),
      quotientIdeal hζ d hp2 = Ideal.span {mu} ∧
      NumberField.IsCMField.ringOfIntegersComplexConj K mu = mu ∧
      quotient hζ d hp2 = eta * mu ^ p ∧
      ¬ (hζ.unit' : 𝓞 K) - 1 ∣ mu ∧
      ((hζ.unit' : 𝓞 K) - 1) ^ (d.depth - 1) ∣
        d.rminus - quotient hζ d hp2 ∧
      ((hζ.unit' : 𝓞 K) - 1) ^ (d.depth - 1) ∣
        d.rplus - eta * mu ^ p := by
  obtain ⟨mu, eta, hJ, hmureal, hq⟩ :=
    hextract
      (quotientIdeal hζ d hp2) (quotient hζ d hp2)
      (d.quotientIdeal_not_ramified hζ hp2)
      (d.quotient_real hζ hp2)
      (d.quotientIdeal_pow hζ hp2)
  have hmunot :
      ¬ (hζ.unit' : 𝓞 K) - 1 ∣ mu := by
    intro hmu
    apply d.quotient_not_ramified hζ hp2
    rw [hq]
    exact dvd_mul_of_dvd_right
      (dvd_pow (n := p) hmu (Fact.out : Nat.Prime p).ne_zero) _
  have hminus :=
    d.pow_pred_dvd_rminus_sub_quotient hζ hp2
  have hplusMinus :
      ((hζ.unit' : 𝓞 K) - 1) ^ (d.depth - 1) ∣
        d.rplus - d.rminus := by
    exact
      (pow_dvd_pow_of_dvd_of_le dvd_rfl
        (Nat.sub_le d.depth 1)).trans d.close
  have hplusQ :
      ((hζ.unit' : 𝓞 K) - 1) ^ (d.depth - 1) ∣
        d.rplus - quotient hζ d hp2 := by
    have hadd := dvd_add hplusMinus hminus
    convert hadd using 1
    ring
  refine ⟨mu, eta, hJ, hmureal, hq, hmunot, hminus, ?_⟩
  simpa only [hq] using hplusQ

/-- Since both the quotient and its chosen generator are real, the
residual unit is real as well. -/
lemma generator_unit_real
    (hp2 : p ≠ 2)
    (mu : 𝓞 K) (eta : (𝓞 K)ˣ)
    (hmureal :
      NumberField.IsCMField.ringOfIntegersComplexConj K mu = mu)
    (hmunot : ¬ (hζ.unit' : 𝓞 K) - 1 ∣ mu)
    (hq : quotient hζ d hp2 = eta * mu ^ p) :
    NumberField.IsCMField.unitsComplexConj K eta = eta := by
  have hmu0 : mu ≠ 0 := by
    intro hmu
    subst mu
    exact hmunot (dvd_zero _)
  apply Units.ext
  change
    NumberField.IsCMField.ringOfIntegersComplexConj K (eta : 𝓞 K) =
      (eta : 𝓞 K)
  apply mul_right_cancel₀
    (pow_ne_zero p hmu0)
  have hqreal := d.quotient_real hζ hp2
  calc
    (NumberField.IsCMField.unitsComplexConj K eta : 𝓞 K) *
          mu ^ p =
        NumberField.IsCMField.ringOfIntegersComplexConj K
          ((eta : 𝓞 K) * mu ^ p) := by
      rw [map_mul, map_pow, hmureal]
      change
        NumberField.IsCMField.ringOfIntegersComplexConj K
              (eta : 𝓞 K) * mu ^ p =
          NumberField.IsCMField.ringOfIntegersComplexConj K
              (eta : 𝓞 K) * mu ^ p
      rfl
    _ = NumberField.IsCMField.ringOfIntegersComplexConj K
          (quotient hζ d hp2) := by rw [hq]
    _ = quotient hζ d hp2 := hqreal
    _ = (eta : 𝓞 K) * mu ^ p := hq

/-- After absorbing the quotient unit, the inverse root is close to a
literal `p`-th power. -/
lemma pow_pred_dvd_inv_unit_mul_rminus_sub_pow
    (hp2 : p ≠ 2)
    (mu : 𝓞 K) (eta : (𝓞 K)ˣ)
    (hq : quotient hζ d hp2 = eta * mu ^ p) :
    ((hζ.unit' : 𝓞 K) - 1) ^ (d.depth - 1) ∣
      (eta⁻¹ : (𝓞 K)ˣ) * d.rminus - mu ^ p := by
  have h := dvd_mul_of_dvd_right
    (d.pow_pred_dvd_rminus_sub_quotient hζ hp2)
    (eta⁻¹ : (𝓞 K)ˣ)
  convert h using 1
  rw [hq]
  have hinv :
      (eta⁻¹ : (𝓞 K)ˣ) * (eta : 𝓞 K) = 1 := by
    rw [← Units.val_mul]
    simp
  rw [mul_sub, ← mul_assoc, hinv, one_mul]

/-- The same absorption makes the positive root close to the identical
real `p`-th power. -/
lemma pow_pred_dvd_inv_unit_mul_rplus_sub_pow
    (mu : 𝓞 K) (eta : (𝓞 K)ˣ)
    (hplus :
      ((hζ.unit' : 𝓞 K) - 1) ^ (d.depth - 1) ∣
        d.rplus - eta * mu ^ p) :
    ((hζ.unit' : 𝓞 K) - 1) ^ (d.depth - 1) ∣
      (eta⁻¹ : (𝓞 K)ˣ) * d.rplus - mu ^ p := by
  have h := dvd_mul_of_dvd_right hplus (eta⁻¹ : (𝓞 K)ˣ)
  convert h using 1
  have hinv :
      (eta⁻¹ : (𝓞 K)ˣ) * (eta : 𝓞 K) = 1 := by
    rw [← Units.val_mul]
    simp
  rw [mul_sub, ← mul_assoc, hinv, one_mul]

end PostEquationNineNormalizedData

end

end Fermat.Irregular.VandiverPostEquationNinePrime
