import Fermat.SixHundredNinetyOne.CircularUnitResidues
import Fermat.SixHundredNinetyOne.VandiverDiagonalArithmetic691
import Mathlib.LinearAlgebra.Vandermonde

/-!
# Residue and Fourier certificates for Vandiver's diagonal units at 691

This module derives the residue matrix of Vandiver's 344 diagonal units
from the already certified circular-unit matrix at `q = 11057`.

The 345 basic factors form the edges of the cyclic ordering generated by
`118` modulo sign.  Their positive integral weights are the nontrivial even
characters of that cycle.  Consequently the change of basis is a scaled
transpose Vandermonde matrix.  This avoids both a `344 × 345` Cartesian
certificate and a second explicit dense inverse.
-/

namespace Fermat.SixHundredNinetyOne.VandiverDiagonalUnitResidues

open Fermat.SixHundredNinetyOne.VandiverDiagonalArithmetic
open Fermat.SixHundredNinetyOne.CircularUnitCyclic
open Fermat.SixHundredNinetyOne.CircularUnitEntryCertificate
open Fermat.SixHundredNinetyOne.CircularUnitMatrix
open Fermat.Irregular.CircularUnitFamily
open Fermat.Irregular.CircularUnitResidues
open Fermat.Irregular.CircularUnitResidues.Certificate

local instance : Fact (Nat.Prime 691) := ⟨by norm_num⟩
local instance : Fact (Nat.Prime 11057) := ⟨by norm_num⟩

set_option maxHeartbeats 3000000
set_option maxRecDepth 1000000

/-- The canonical circular-unit column corresponding to the real class
of `118^(j+1)`. -/
def cycleColumn691 (j : Fin 344) : Fin 344 :=
  let s := ((teichmullerRoot691 : ZMod 691) ^ (j.val + 1)).val
  let a := min s (691 - s)
  ⟨(a - 2) % 344, Nat.mod_lt _ (by norm_num)⟩

/-- The powers of `118` visit every nontrivial real class exactly once. -/
theorem cycleColumn691_bijective :
    Function.Bijective cycleColumn691 := by decide

noncomputable def cycleColumnEquiv691 : Fin 344 ≃ Fin 344 :=
  Equiv.ofBijective cycleColumn691 cycleColumn691_bijective

/-- The nontrivial even Fourier nodes `118^(-2n)`, `1 ≤ n ≤ 344`. -/
def vandermondeNode691 (i : Fin 344) : ZMod 691 :=
  (teichmullerRoot691 : ZMod 691) ^ (688 - 2 * i.val)

theorem vandermondeNode691_injective :
    Function.Injective vandermondeNode691 := by decide

/-- Column scale converting powers `0, ..., 343` to Vandiver's edge
coefficients. -/
def fourierScale691 (i : Fin 344) : ZMod 691 :=
  ((teichmullerRoot691 : ZMod 691) ^ (2 * (i.val + 1)) - 1) *
    (teichmullerRoot691 : ZMod 691) * vandermondeNode691 i

theorem fourierScale691_ne_zero (i : Fin 344) :
    fourierScale691 i ≠ 0 := by
  fin_cases i <;> decide

/-- The edge-to-diagonal change of basis. -/
def fourierChange691 : Matrix (Fin 344) (Fin 344) (ZMod 691) :=
  (Matrix.vandermonde vandermondeNode691).transpose *
    Matrix.diagonal fourierScale691

theorem fourierChange691_apply (row i : Fin 344) :
    fourierChange691 row i =
      vandermondeNode691 i ^ row.val * fourierScale691 i := by
  rw [fourierChange691, Matrix.mul_diagonal]
  rfl

/-- The scaled Fourier matrix is nonsingular. -/
theorem fourierChange691_det_ne_zero :
    fourierChange691.det ≠ 0 := by
  rw [fourierChange691, Matrix.det_mul, Matrix.det_transpose,
    Matrix.det_diagonal]
  exact mul_ne_zero
    (Matrix.det_vandermonde_ne_zero_iff.mpr
      vandermondeNode691_injective)
    (Finset.prod_ne_zero_iff.mpr
      (fun i _ ↦ fourierScale691_ne_zero i))

abbrev certificate691 : Certificate 691 11057 :=
  Fermat.SixHundredNinetyOne.CircularUnitResidues.certificate

/-- Extend the circular-unit cycle by the trivial class at positions zero
and 345. -/
def cycleClassSymbol691 (row : Fin 344) (ell : ℕ) : ZMod 691 :=
  if h : 1 ≤ ell ∧ ell ≤ 344 then
    Fermat.SixHundredNinetyOne.CircularUnitMatrix.matrix row
      (cycleColumn691 ⟨ell - 1, by omega⟩)
  else 0

/-- The symbol of the `j`th basic factor is the difference of adjacent
circular-unit symbols. -/
def basicEdgeSymbol691 (row : Fin 344) (j : Fin 345) : ZMod 691 :=
  cycleClassSymbol691 row (j.val + 1) -
    cycleClassSymbol691 row j.val

/-- Literal source exponent `4955^j`. -/
def conjugateExponent691 (j : Fin 345) : ℕ :=
  teichmullerRoot691 ^ j.val

/-- Its small reduction modulo `691`. -/
def reducedConjugateExponent691 (j : Fin 345) : ℕ :=
  ((teichmullerRoot691 : ZMod 691) ^ j.val).val

theorem conjugateExponent691_modEq_reduced (j : Fin 345) :
    conjugateExponent691 j ≡ reducedConjugateExponent691 j [MOD 691] := by
  rw [← ZMod.natCast_eq_natCast_iff]
  simp [conjugateExponent691, reducedConjugateExponent691]

theorem pow_conjugateExponent691_eq_reduced {G : Type*} [Monoid G]
    (x : G) (hx : x ^ 691 = 1) (j : Fin 345) :
    x ^ conjugateExponent691 j = x ^ reducedConjugateExponent691 j :=
  pow_eq_pow_of_modEq (conjugateExponent691_modEq_reduced j) hx

/-- The literal 4955-term geometric sum in the finite-field reduction. -/
def basicResidueGeomSum691 (row : Fin 344) (j : Fin 345) : ZMod 11057 :=
  let w := embeddingRoot (p := 691) certificate691.root row ^
    conjugateExponent691 j
  ∑ k ∈ Finset.range 4955, w ^ k

/-- Reduction of the normalized basic factor. -/
def basicResidueValue691 (row : Fin 344) (j : Fin 345) : ZMod 11057 :=
  let w := embeddingRoot (p := 691) certificate691.root row ^
    conjugateExponent691 j
  w ^ 287 * basicResidueGeomSum691 row j

/-- Since `4955 = 7 * 691 + 118`, the literal source sum reduces to
length 118 at a 691st root. -/
theorem basicResidueGeomSum691_eq (row : Fin 344) (j : Fin 345) :
    basicResidueGeomSum691 row j =
      ∑ k ∈ Finset.range 118,
        (embeddingRoot (p := 691) certificate691.root row ^
          conjugateExponent691 j) ^ k := by
  let w : ZMod 11057 :=
    embeddingRoot (p := 691) certificate691.root row ^
      conjugateExponent691 j
  have hwroot : IsPrimitiveRoot w 691 := by
    apply (embeddingRoot_isPrimitive certificate691.hp2
      certificate691.root_isPrimitive row).pow_of_coprime
    exact (by norm_num : Nat.Coprime 4955 691).pow_left j.val
  have hwne : w - 1 ≠ 0 :=
    sub_ne_zero.mpr (hwroot.ne_one (by norm_num))
  apply mul_left_cancel₀ (a := w - 1) hwne
  rw [show (w - 1) * basicResidueGeomSum691 row j = w ^ 4955 - 1 by
    simpa [basicResidueGeomSum691, w] using (mul_geom_sum w 4955)]
  rw [show (w - 1) *
      (∑ k ∈ Finset.range 118,
        (embeddingRoot (p := 691) certificate691.root row ^
          conjugateExponent691 j) ^ k) = w ^ 118 - 1 by
    simpa [w] using (mul_geom_sum w 118)]
  rw [show 4955 = 691 * 7 + 118 by norm_num, pow_add, pow_mul,
    hwroot.pow_eq_one, one_pow, one_mul]

/-! ## Compact cyclic provenance

The real residue group is cyclic of order 345.  Thus the edge-symbol and
normalized-value identities factor through two one-variable certificates
and an algebraic phase argument. -/

/-- In the real cyclic quotient generated by `3`, multiplication by `118`
is translation by `67`; equivalently, `3^67 = 118 (mod 691)`. -/
theorem cycleColumn691_coord (ell : Fin 344) :
    coord (columnPermutation (cycleColumn691 ell)) =
      ((67 * (ell.val + 1) : ℕ) : Cyc) := by
  decide +revert

/-- The stored column is the canonical representative of
`118^(ell+1)` up to the harmless real-class sign. -/
theorem cycleColumn691_realRepresentative (ell : Fin 344) :
    let a := ((cycleColumn691 ell).val + 2 : ZMod 691)
    let d := (teichmullerRoot691 : ZMod 691) ^ (ell.val + 1)
    a = d ∨ a = -d := by
  decide +revert

/-- Cyclic coordinate of an original embedding row. -/
def rowCycleCoord691 (row : Fin 344) : Cyc :=
  coord (rowPermutation row)

/-- Extend the literal conjugate powers through the wrap at exponent
`345`. -/
def extendedConjugateExponent691 (ell : Fin 346) : ℕ :=
  teichmullerRoot691 ^ ell.val

/-- Its cyclic real-residue coordinate. -/
def extendedCycleCoord691 (ell : Fin 346) : Cyc :=
  ((67 * ell.val : ℕ) : Cyc)

private theorem weight_eq_of_eq_or_inv {x y : ZMod 11057}
    (hy : y ≠ 0) (h : x = y ∨ x = y⁻¹) :
    weight x = weight y := by
  rcases h with h | h
  · rw [h]
  · rw [h, weight_inv y hy]

private theorem pow_eq_inv_pow_of_cast_eq_neg
    {x : ZMod 11057} (hx : IsPrimitiveRoot x 691)
    {a b : ℕ}
    (h : (a : ZMod 691) = -(b : ZMod 691)) :
    x ^ a = (x ^ b)⁻¹ := by
  have hab : a + b ≡ 0 [MOD 691] := by
    rw [← ZMod.natCast_eq_natCast_iff]
    simpa only [Nat.cast_add, Nat.cast_zero, add_eq_zero_iff_eq_neg] using h
  have hp : x ^ (a + b) = 1 := by
    simpa using pow_eq_pow_of_modEq hab hx.pow_eq_one
  apply (mul_eq_one_iff_eq_inv₀
    (pow_ne_zero b (hx.ne_zero (by norm_num)))).mp
  rw [← pow_add]
  exact hp

private theorem pow_eq_or_inv_pow_of_cast_eq_or_neg
    {x : ZMod 11057} (hx : IsPrimitiveRoot x 691)
    {a b : ℕ}
    (h : (a : ZMod 691) = b ∨ (a : ZMod 691) = -(b : ZMod 691)) :
    x ^ a = x ^ b ∨ x ^ a = (x ^ b)⁻¹ := by
  rcases h with h | h
  · left
    apply pow_eq_pow_of_modEq _ hx.pow_eq_one
    rw [← ZMod.natCast_eq_natCast_iff]
    exact h
  · exact Or.inr (pow_eq_inv_pow_of_cast_eq_neg hx h)

/-- The weight of every conjugated root is its cyclic phase weight.  This
is parametric in the row; only the two column-orientation facts above are
checked finitely. -/
theorem extendedConjugateWeight691 (row : Fin 344) (ell : Fin 346) :
    let x := embeddingRoot (p := 691) (1820 : ZMod 11057) row
    weight (x ^ extendedConjugateExponent691 ell) =
      weight (classRoot (rowCycleCoord691 row + extendedCycleCoord691 ell)) := by
  let x := embeddingRoot (p := 691) (1820 : ZMod 11057) row
  change
    weight (x ^ extendedConjugateExponent691 ell) =
      weight (classRoot (rowCycleCoord691 row + extendedCycleCoord691 ell))
  have hxprim : IsPrimitiveRoot x 691 :=
    embeddingRoot_isPrimitive (p := 691) (q := 11057) (by norm_num)
      root_isPrimitive row
  have hx0 : x ≠ 0 := hxprim.ne_zero (by norm_num)
  by_cases hzero : ell.val = 0
  · have hell : ell = ⟨0, by norm_num⟩ := Fin.ext hzero
    subst ell
    have hrow :
        classRoot (rowCycleCoord691 row) = x ∨
          classRoot (rowCycleCoord691 row) = x⁻¹ := by
      simpa [x, rowCycleCoord691] using row_root_relation row
    have hw := weight_eq_of_eq_or_inv hx0 hrow
    simpa [x, rowCycleCoord691, extendedConjugateExponent691,
      extendedCycleCoord691] using hw.symm
  by_cases hlast : ell.val = 345
  · have hell : ell = ⟨345, by norm_num⟩ := Fin.ext hlast
    subst ell
    have hpowLast :
        x ^ extendedConjugateExponent691 ⟨345, by norm_num⟩ = x⁻¹ := by
      have hcast :
          (extendedConjugateExponent691 ⟨345, by norm_num⟩ : ZMod 691) =
            -(1 : ZMod 691) := by
        decide +kernel
      simpa only [pow_one] using
        pow_eq_inv_pow_of_cast_eq_neg hxprim hcast
    have hrow :
        classRoot (rowCycleCoord691 row) = x ∨
          classRoot (rowCycleCoord691 row) = x⁻¹ := by
      simpa [x, rowCycleCoord691] using row_root_relation row
    have hw := weight_eq_of_eq_or_inv hx0 hrow
    have hcoordlast :
        extendedCycleCoord691 ⟨345, by norm_num⟩ = 0 := by
      decide
    calc
      weight
          (x ^ extendedConjugateExponent691 ⟨345, by norm_num⟩) =
          weight x⁻¹ := congrArg weight hpowLast
      _ = weight x := weight_inv x hx0
      _ = weight
          (classRoot
            (rowCycleCoord691 row +
              extendedCycleCoord691 ⟨345, by norm_num⟩)) := by
        rw [hcoordlast, add_zero]
        exact hw.symm
  · have hpos : 1 ≤ ell.val := by omega
    have hle : ell.val ≤ 344 := by omega
    let k : Fin 344 := ⟨ell.val - 1, by omega⟩
    have hk : k.val + 1 = ell.val := by simp [k]; omega
    let a := (cycleColumn691 k).val + 2
    have hrep := cycleColumn691_realRepresentative k
    have hcast :
        (a : ZMod 691) =
            (extendedConjugateExponent691 ell : ZMod 691) ∨
          (a : ZMod 691) =
            -(extendedConjugateExponent691 ell : ZMod 691) := by
      simpa [a, extendedConjugateExponent691, hk] using hrep
    have hpow := pow_eq_or_inv_pow_of_cast_eq_or_neg hxprim hcast
    have hpowWeight :
      weight (x ^ a) =
          weight (x ^ extendedConjugateExponent691 ell) :=
      weight_eq_of_eq_or_inv
        (pow_ne_zero (extendedConjugateExponent691 ell) hx0) hpow
    have hprod :
        classRoot
            (rowCycleCoord691 row +
              coord (columnPermutation (cycleColumn691 k))) =
            x ^ a ∨
          classRoot
            (rowCycleCoord691 row +
              coord (columnPermutation (cycleColumn691 k))) =
            (x ^ a)⁻¹ := by
      simpa [x, a, rowCycleCoord691] using
        product_root_relation row (cycleColumn691 k)
    have hprodWeight :
        weight
            (classRoot
              (rowCycleCoord691 row +
                coord (columnPermutation (cycleColumn691 k)))) =
          weight (x ^ a) := by
      exact weight_eq_of_eq_or_inv (pow_ne_zero a hx0) hprod
    rw [cycleColumn691_coord k] at hprodWeight
    have hcoord :
        ((67 * (k.val + 1) : ℕ) : Cyc) = extendedCycleCoord691 ell := by
      simp only [extendedCycleCoord691, hk]
    rw [hcoord] at hprodWeight
    exact (hprodWeight.trans hpowWeight).symm

private theorem normalizedGeom_pow_eq_weight_ratio
    (w : ZMod 11057) (hw : IsPrimitiveRoot w 691) (a e : ℕ)
    (hexp : 2 * e + a ≡ 1 [MOD 691]) :
    (w ^ e * ∑ k ∈ Finset.range a, w ^ k) ^ 16 =
      weight (w ^ a) / weight w := by
  have hw0 : w ≠ 0 := hw.ne_zero (by norm_num)
  have hw1 : 1 - w ≠ 0 :=
    sub_ne_zero.mpr (Ne.symm (hw.ne_one (by norm_num)))
  have hgeom :
      ∑ k ∈ Finset.range a, w ^ k = (1 - w ^ a) / (1 - w) := by
    apply (eq_div_iff hw1).2
    calc
      (∑ k ∈ Finset.range a, w ^ k) * (1 - w) =
          -((w - 1) * ∑ k ∈ Finset.range a, w ^ k) := by ring
      _ = -(w ^ a - 1) := by rw [mul_geom_sum]
      _ = 1 - w ^ a := by ring
  rw [hgeom, ← mul_div_assoc]
  change (w ^ e * (1 - w ^ a) / (1 - w)) ^ 16 =
    weight (w ^ a) / weight w
  have hnorm8 : 8 * (2 * e + a) ≡ 8 * 1 [MOD 691] :=
    hexp.mul_left 8
  have hexp16 : 16 * e + 8 * a ≡ 8 [MOD 691] := by
    convert hnorm8 using 1
    all_goals omega
  have hpow : w ^ (16 * e + 8 * a) = w ^ 8 :=
    pow_eq_pow_of_modEq hexp16 hw.pow_eq_one
  simp only [weight, mul_pow, div_pow]
  field_simp [hw0, hw1]
  have hpow' : w ^ (e * 16) * w ^ (a * 8) = w ^ 8 := by
    rw [← pow_add]
    simpa [Nat.mul_comm] using hpow
  calc
    _ = (w ^ (e * 16) * w ^ (a * 8)) *
        (1 - w ^ a) ^ 16 := by ring
    _ = w ^ 8 * (1 - w ^ a) ^ 16 := by rw [hpow']
    _ = _ := by ring

theorem normalizedLength118_pow_eq_weight_ratio
    (w : ZMod 11057) (hw : IsPrimitiveRoot w 691) :
    (w ^ 287 * ∑ k ∈ Finset.range 118, w ^ k) ^ 16 =
      weight (w ^ 118) / weight w :=
  normalizedGeom_pow_eq_weight_ratio w hw 118 287 (by norm_num)

/-- The extended cycle symbols are ordinary differences of the compressed
phase vector. -/
theorem cycleClassSymbol691_succ_phase (row ell : Fin 344) :
    cycleClassSymbol691 row (ell.val + 1) =
      symbolPhase
          (rowCycleCoord691 row +
            ((67 * (ell.val + 1) : ℕ) : Cyc)) -
        symbolPhase (rowCycleCoord691 row) := by
  rw [cycleClassSymbol691, dif_pos]
  · change
      symbolPhase
            (coord (rowPermutation row) +
              coord (columnPermutation (cycleColumn691 ell))) -
          symbolPhase (coord (rowPermutation row)) =
        _
    rw [cycleColumn691_coord]
    rfl
  · omega

theorem cycleClassSymbol691_phase (row : Fin 344) (ell : ℕ)
    (hell : ell ≤ 345) :
    cycleClassSymbol691 row ell =
      symbolPhase
          (rowCycleCoord691 row + ((67 * ell : ℕ) : Cyc)) -
        symbolPhase (rowCycleCoord691 row) := by
  by_cases hzero : ell = 0
  · subst ell
    simp [cycleClassSymbol691]
  by_cases hlast : ell = 345
  · subst ell
    have hcoord : (((67 * 345 : ℕ) : Cyc)) = 0 := by decide
    rw [cycleClassSymbol691, dif_neg (by omega), hcoord, add_zero, sub_self]
  · have hpos : 1 ≤ ell := by omega
    have hle : ell ≤ 344 := by omega
    let k : Fin 344 := ⟨ell - 1, by omega⟩
    have hk : k.val + 1 = ell := by simp [k]; omega
    simpa only [hk] using cycleClassSymbol691_succ_phase row k

theorem basicEdgeSymbol691_phase (row : Fin 344) (j : Fin 345) :
    basicEdgeSymbol691 row j =
      symbolPhase
          ((rowCycleCoord691 row +
              extendedCycleCoord691 j.castSucc) + 67) -
        symbolPhase
          (rowCycleCoord691 row +
            extendedCycleCoord691 j.castSucc) := by
  rw [basicEdgeSymbol691,
    cycleClassSymbol691_phase row (j.val + 1) (by omega),
    cycleClassSymbol691_phase row j.val (by omega)]
  simp only [extendedCycleCoord691, Fin.val_castSucc]
  have hstep :
      rowCycleCoord691 row + ((67 * (j.val + 1) : ℕ) : Cyc) =
        (rowCycleCoord691 row + ((67 * j.val : ℕ) : Cyc)) + 67 := by
    push_cast
    ring
  rw [hstep]
  ring

theorem extendedConjugateStep691
    (x : ZMod 11057) (hx : IsPrimitiveRoot x 691) (j : Fin 345) :
    (x ^ extendedConjugateExponent691 j.castSucc) ^ 118 =
      x ^ extendedConjugateExponent691 j.succ := by
  rw [← pow_mul]
  apply pow_eq_pow_of_modEq _ hx.pow_eq_one
  change
    teichmullerRoot691 ^ j.val * 118 ≡
      teichmullerRoot691 ^ (j.val + 1) [MOD 691]
  rw [pow_succ]
  exact (by norm_num [teichmullerRoot691] :
    118 ≡ teichmullerRoot691 [MOD 691]).mul_left _

private def reducedBasicResidueValue691
    (row : Fin 344) (j : Fin 345) : ZMod 11057 :=
  let x := embeddingRoot (p := 691) (1820 : ZMod 11057) row
  let w := x ^ extendedConjugateExponent691 j.castSucc
  w ^ 287 * ∑ k ∈ Finset.range 118, w ^ k

private theorem reducedBasicResidueValue691_symbol
    (row : Fin 344) (j : Fin 345) :
    reducedBasicResidueValue691 row j ^ 16 =
      (1820 : ZMod 11057) ^ (basicEdgeSymbol691 row j).val := by
  let x := embeddingRoot (p := 691) (1820 : ZMod 11057) row
  let w := x ^ extendedConjugateExponent691 j.castSucc
  have hxprim : IsPrimitiveRoot x 691 :=
    embeddingRoot_isPrimitive (p := 691) (q := 11057) (by norm_num)
      root_isPrimitive row
  have hwprim : IsPrimitiveRoot w 691 := by
    apply hxprim.pow_of_coprime
    exact (by norm_num : Nat.Coprime 4955 691).pow_left j.val
  change (w ^ 287 * ∑ k ∈ Finset.range 118, w ^ k) ^ 16 = _
  rw [normalizedLength118_pow_eq_weight_ratio w hwprim]
  have hcur :
      weight w =
        weight
          (classRoot
            (rowCycleCoord691 row +
              extendedCycleCoord691 j.castSucc)) := by
    simpa [x, w] using extendedConjugateWeight691 row j.castSucc
  have hnext :
      weight (x ^ extendedConjugateExponent691 j.succ) =
        weight
          (classRoot
            (rowCycleCoord691 row +
              extendedCycleCoord691 j.succ)) := by
    simpa [x] using extendedConjugateWeight691 row j.succ
  have hstep := extendedConjugateStep691 x hxprim j
  rw [hstep, hnext, hcur]
  have hcoord :
      rowCycleCoord691 row + extendedCycleCoord691 j.succ =
        (rowCycleCoord691 row +
          extendedCycleCoord691 j.castSucc) + 67 := by
    simp only [extendedCycleCoord691, Fin.val_succ, Fin.val_castSucc]
    push_cast
    ring
  rw [hcoord, weight_ratio_eq_phase_ratio,
    phase_value_certificate, phase_value_certificate,
    ← root_pow_sub_val]
  rw [basicEdgeSymbol691_phase]

/-- Complete provenance of every basic-factor residue symbol, derived from
the one-variable cyclic certificates rather than a Cartesian case split. -/
theorem basicResidueValue691_symbol (row : Fin 344) (j : Fin 345) :
    basicResidueValue691 row j ^ 16 =
      certificate691.root ^ (basicEdgeSymbol691 row j).val := by
  rw [basicResidueValue691, basicResidueGeomSum691_eq]
  simpa [reducedBasicResidueValue691, extendedConjugateExponent691,
    conjugateExponent691, certificate691,
    Fermat.SixHundredNinetyOne.CircularUnitResidues.certificate] using
    reducedBasicResidueValue691_symbol row j

end Fermat.SixHundredNinetyOne.VandiverDiagonalUnitResidues
