import Fermat.Quadratic.Golden

/-!
# Units of the golden quadratic order

The unit group of `ℤ[(1 + √5) / 2]` is generated by the golden unit `φ`
and `-1`.  The proof passes through Pell's equation: the sixth power of every
unit lies in `ℤ[√5]`, where it is a norm-one Pell solution, and the
fundamental positive solution is `9 + 4√5 = φ⁶`.
-/

namespace Fermat.Quadratic.Golden

namespace MaximalOrder

/-- The golden ratio as a unit of the maximal order.  Its inverse is `φ - 1`. -/
def phiUnit : MaximalOrderˣ where
  val := phi
  inv := phi - 1
  val_inv := by ext <;> norm_num [phi]
  inv_val := by ext <;> norm_num [phi]

@[simp] theorem coe_phiUnit : (phiUnit : MaximalOrder) = phi := rfl
@[simp] theorem phiUnit_val_re : (phiUnit : MaximalOrder).re = 0 := rfl
@[simp] theorem phiUnit_val_im : (phiUnit : MaximalOrder).im = 1 := rfl
@[simp] theorem coe_phiUnit_inv : ((phiUnit⁻¹ : MaximalOrderˣ) : MaximalOrder) = phi - 1 := rfl

/-! ## A real embedding -/

/-- The real embedding sending the integral generator to the positive golden ratio. -/
noncomputable def toReal : MaximalOrder →+* ℝ where
  toFun z := z.re + z.im * Real.goldenRatio
  map_zero' := by simp
  map_one' := by simp
  map_add' z w := by
    simp only [re_add, im_add, Int.cast_add]
    ring
  map_mul' z w := by
    simp only [re_mul, im_mul, Int.cast_add, Int.cast_mul]
    generalize hrdef : Real.goldenRatio = r
    have hr : r ^ 2 = r + 1 := by
      rw [← hrdef]
      exact Real.goldenRatio_sq
    ring_nf
    rw [hr]
    ring

@[simp] theorem toReal_apply (z : MaximalOrder) :
    toReal z = z.re + z.im * Real.goldenRatio := rfl

@[simp] theorem toReal_phi : toReal phi = Real.goldenRatio := by simp [toReal]

theorem toReal_eq_zero_iff {z : MaximalOrder} : toReal z = 0 ↔ z = 0 := by
  constructor
  · intro hz
    have him : z.im = 0 := by
      by_contra him
      apply Real.goldenRatio_irrational.ne_rational (-z.re) z.im
      have himR : (z.im : ℝ) ≠ 0 := by exact_mod_cast him
      rw [eq_div_iff himR]
      have := hz
      simp only [toReal_apply] at this
      calc
        Real.goldenRatio * (z.im : ℝ) = (z.im : ℝ) * Real.goldenRatio := by ring
        _ = -(z.re : ℝ) := by linarith
        _ = ((-z.re : ℤ) : ℝ) := by push_cast; rfl
    have hre : z.re = 0 := by
      simpa [him] using hz
    ext <;> simp [hre, him]
  · rintro rfl
    simp

theorem toReal_injective : Function.Injective toReal := by
  intro z w h
  rw [← sub_eq_zero, ← toReal_eq_zero_iff, map_sub, h, sub_self]

/-- A sixth root of unity in the golden order is `1` or `-1`. -/
theorem eq_one_or_neg_one_of_pow_six_eq_one (u : MaximalOrderˣ) (hu : u ^ 6 = 1) :
    u = 1 ∨ u = -1 := by
  have hreal : toReal (u : MaximalOrder) ^ 6 = 1 := by
    have huval : (u : MaximalOrder) ^ 6 = 1 := by
      simpa only [Units.val_pow_eq_pow_val, Units.val_one] using congrArg Units.val hu
    rw [← map_pow, huval, map_one]
  rcases (pow_eq_one_iff_of_ne_zero (a := toReal (u : MaximalOrder)) (by norm_num : 6 ≠ 0)).mp
      hreal with hpos | ⟨hneg, -⟩
  · left
    apply Units.ext
    exact toReal_injective (by simpa using hpos)
  · right
    apply Units.ext
    exact toReal_injective (by simpa using hneg)

/-! ## Sixth powers and Pell solutions -/

private theorem im_pow_six_formula (z : MaximalOrder) :
    (z ^ 6).im =
      6 * z.re ^ 5 * z.im + 15 * z.re ^ 4 * z.im ^ 2 +
      40 * z.re ^ 3 * z.im ^ 3 + 45 * z.re ^ 2 * z.im ^ 4 +
      30 * z.re * z.im ^ 5 + 8 * z.im ^ 6 := by
  simp only [show 6 = 5 + 1 by omega, pow_succ, im_mul, re_mul]
  norm_num
  ring

/-- The `φ`-coordinate of every sixth power is even. -/
theorem even_im_pow_six (z : MaximalOrder) : Even (z ^ 6).im := by
  rw [im_pow_six_formula]
  rcases z.re.even_or_odd with hre | hre <;>
    rcases z.im.even_or_odd with him | him <;>
    norm_num [parity_simps, hre, him]

/-- The canonical element of `ℤ[√5]` whose image is `z⁶`. -/
def sixthPreimage (z : MaximalOrder) : Zsqrtd 5 :=
  ⟨(z ^ 6).re + (z ^ 6).im / 2, (z ^ 6).im / 2⟩

@[simp] theorem embed_sixthPreimage (z : MaximalOrder) : embed (sixthPreimage z) = z ^ 6 := by
  apply MaximalOrder.ext
  · simp [sixthPreimage]
  · change 2 * ((z ^ 6).im / 2) = (z ^ 6).im
    exact Int.two_mul_ediv_two_of_even (even_im_pow_six z)

@[simp] theorem norm_pow (z : MaximalOrder) (n : ℕ) : norm (z ^ n) = norm z ^ n :=
  map_pow normMonoidHom z n

private theorem norm_unit_pow_six (u : MaximalOrderˣ) : norm ((u : MaximalOrder) ^ 6) = 1 := by
  have hu : IsUnit (norm (u : MaximalOrder)) := u.isUnit.map normMonoidHom
  rcases Int.isUnit_eq_one_or hu with hu | hu <;> simp [hu]

/-- The norm-one Pell solution represented by the sixth power of a golden-order unit. -/
noncomputable def pellOfUnitSixth (u : MaximalOrderˣ) : Pell.Solution₁ 5 :=
  Pell.Solution₁.mk (sixthPreimage (u : MaximalOrder)).re
    (sixthPreimage (u : MaximalOrder)).im (by
      have hnorm : Zsqrtd.norm (sixthPreimage (u : MaximalOrder)) = 1 := by
        calc
          Zsqrtd.norm (sixthPreimage (u : MaximalOrder)) =
              norm (embed (sixthPreimage (u : MaximalOrder))) := by
                rw [norm_embed]
                simp only [Zsqrtd.norm]
                ring
          _ = norm ((u : MaximalOrder) ^ 6) := by rw [embed_sixthPreimage]
          _ = 1 := norm_unit_pow_six u
      simpa [Zsqrtd.norm, pow_two, mul_assoc] using hnorm)

/-! ## The fundamental Pell solution -/

/-- The Pell solution `9 + 4√5`, equal to `φ⁶`. -/
def pellFundamental : Pell.Solution₁ 5 :=
  Pell.Solution₁.mk 9 4 (by norm_num)

@[simp] theorem pellFundamental_x : pellFundamental.x = 9 := rfl
@[simp] theorem pellFundamental_y : pellFundamental.y = 4 := rfl

private theorem no_small_pell_mod_twenty :
    ∀ x y : ZMod 20,
      (x = 2 ∨ x = 3 ∨ x = 4 ∨ x = 5 ∨ x = 6 ∨ x = 7 ∨ x = 8) →
      x ^ 2 - 5 * y ^ 2 ≠ 1 := by
  decide

/-- `9 + 4√5` is the fundamental positive solution of `x² - 5y² = 1`. -/
theorem pellFundamental_isFundamental : Pell.IsFundamental pellFundamental := by
  refine ⟨by norm_num, by norm_num, ?_⟩
  intro b hb
  by_contra h9
  have hblt : b.x < 9 := lt_of_not_ge h9
  have hcases :
      b.x = 2 ∨ b.x = 3 ∨ b.x = 4 ∨ b.x = 5 ∨ b.x = 6 ∨ b.x = 7 ∨ b.x = 8 := by
    omega
  have hcases' :
      (b.x : ZMod 20) = 2 ∨ (b.x : ZMod 20) = 3 ∨ (b.x : ZMod 20) = 4 ∨
      (b.x : ZMod 20) = 5 ∨ (b.x : ZMod 20) = 6 ∨ (b.x : ZMod 20) = 7 ∨
      (b.x : ZMod 20) = 8 := by
    rcases hcases with h | h | h | h | h | h | h <;> simp [h]
  have hprop : (b.x : ZMod 20) ^ 2 - 5 * (b.y : ZMod 20) ^ 2 = 1 := by
    simpa using congrArg (fun n : ℤ ↦ (n : ZMod 20)) b.prop
  exact no_small_pell_mod_twenty (b.x : ZMod 20) (b.y : ZMod 20) hcases' hprop

/-! ## Transporting the Pell group into the unit group -/

private theorem pell_norm_one (s : Pell.Solution₁ 5) :
    Zsqrtd.norm (s : Zsqrtd 5) = 1 := by
  simpa [Zsqrtd.norm, pow_two, mul_assoc] using s.prop

/-- A norm-one Pell solution, embedded as a unit of the maximal order. -/
def pellUnit (s : Pell.Solution₁ 5) : MaximalOrderˣ where
  val := embed (s : Zsqrtd 5)
  inv := embed (star (s : Zsqrtd 5))
  val_inv := by
    rw [← map_mul, ← Zsqrtd.norm_eq_mul_conj, pell_norm_one]
    simp
  inv_val := by
    rw [mul_comm, ← map_mul, ← Zsqrtd.norm_eq_mul_conj, pell_norm_one]
    simp

/-- The embedding of the Pell solution group into the golden-order unit group. -/
def pellUnitHom : Pell.Solution₁ 5 →* MaximalOrderˣ where
  toFun := pellUnit
  map_one' := by
    apply Units.ext
    change embed (1 : Zsqrtd 5) = 1
    simp
  map_mul' s t := by
    apply Units.ext
    change embed ((s : Zsqrtd 5) * (t : Zsqrtd 5)) =
      embed (s : Zsqrtd 5) * embed (t : Zsqrtd 5)
    exact map_mul embed _ _

@[simp] theorem pellUnitHom_apply (s : Pell.Solution₁ 5) :
    (pellUnitHom s : MaximalOrder) = embed (s : Zsqrtd 5) := rfl

@[simp] theorem pellUnitHom_neg (s : Pell.Solution₁ 5) :
    pellUnitHom (-s) = -pellUnitHom s := by
  apply Units.ext
  change embed (-(s : Zsqrtd 5)) = -embed (s : Zsqrtd 5)
  exact map_neg embed _

@[simp] theorem pellUnitHom_fundamental :
    pellUnitHom pellFundamental = phiUnit ^ 6 := by
  apply Units.ext
  ext <;> norm_num [pellUnitHom, pellUnit, pellFundamental, phiUnit, phi, pow_succ]

@[simp] theorem pellUnitHom_pellOfUnitSixth (u : MaximalOrderˣ) :
    pellUnitHom (pellOfUnitSixth u) = u ^ 6 := by
  apply Units.ext
  change embed (sixthPreimage (u : MaximalOrder)) = (u : MaximalOrder) ^ 6
  exact embed_sixthPreimage (u : MaximalOrder)

private theorem pow_six_ne_neg_pow_six (u v : MaximalOrderˣ) : u ^ 6 ≠ -(v ^ 6) := by
  intro h
  have hu0 : toReal (u : MaximalOrder) ≠ 0 := by
    intro hu
    exact u.ne_zero (toReal_eq_zero_iff.mp hu)
  have hv0 : toReal (v : MaximalOrder) ≠ 0 := by
    intro hv
    exact v.ne_zero (toReal_eq_zero_iff.mp hv)
  have hr : toReal (u : MaximalOrder) ^ 6 = -(toReal (v : MaximalOrder) ^ 6) := by
    have := congrArg (fun w : MaximalOrderˣ ↦ toReal (w : MaximalOrder)) h
    simpa only [Units.val_pow_eq_pow_val, Units.val_neg, map_pow, map_neg] using this
  have hup : 0 < toReal (u : MaximalOrder) ^ 6 := by positivity
  have hvp : 0 < toReal (v : MaximalOrder) ^ 6 := by positivity
  linarith

private theorem eq_or_eq_neg_of_pow_six_eq (u v : MaximalOrderˣ) (h : u ^ 6 = v ^ 6) :
    u = v ∨ u = -v := by
  have hw : (u * v⁻¹) ^ 6 = 1 := by
    rw [mul_pow, h]
    group
  rcases eq_one_or_neg_one_of_pow_six_eq_one (u * v⁻¹) hw with hw | hw
  · left
    calc
      u = (u * v⁻¹) * v := by group
      _ = 1 * v := by rw [hw]
      _ = v := one_mul v
  · right
    calc
      u = (u * v⁻¹) * v := by group
      _ = (-1) * v := by rw [hw]
      _ = -v := neg_one_mul v

/-! ## Classification -/

/-- Every unit of the golden order is, up to sign, an integral power of `φ`. -/
theorem unit_eq_sign_mul_phiUnit_zpow (u : MaximalOrderˣ) :
    ∃ n : ℤ, u = phiUnit ^ n ∨ u = -phiUnit ^ n := by
  obtain ⟨n, hn⟩ :=
    pellFundamental_isFundamental.eq_zpow_or_neg_zpow (pellOfUnitSixth u)
  refine ⟨n, ?_⟩
  rcases hn with hn | hn
  · have h6 : u ^ 6 = (phiUnit ^ n) ^ 6 := by
      calc
        u ^ 6 = pellUnitHom (pellOfUnitSixth u) :=
          (pellUnitHom_pellOfUnitSixth u).symm
        _ = pellUnitHom (pellFundamental ^ n) := congrArg pellUnitHom hn
        _ = pellUnitHom pellFundamental ^ n := map_zpow pellUnitHom pellFundamental n
        _ = (phiUnit ^ 6) ^ n := by rw [pellUnitHom_fundamental]
        _ = (phiUnit ^ n) ^ 6 := by group
    exact eq_or_eq_neg_of_pow_six_eq u (phiUnit ^ n) h6
  · have h6 : u ^ 6 = -((phiUnit ^ n) ^ 6) := by
      calc
        u ^ 6 = pellUnitHom (pellOfUnitSixth u) :=
          (pellUnitHom_pellOfUnitSixth u).symm
        _ = pellUnitHom (-(pellFundamental ^ n)) := congrArg pellUnitHom hn
        _ = -(pellUnitHom (pellFundamental ^ n)) := pellUnitHom_neg _
        _ = -(pellUnitHom pellFundamental ^ n) := by rw [map_zpow]
        _ = -((phiUnit ^ 6) ^ n) := by rw [pellUnitHom_fundamental]
        _ = -((phiUnit ^ n) ^ 6) := by congr 1; group
    exact (pow_six_ne_neg_pow_six u (phiUnit ^ n) h6).elim

/-- Split a unit into a fifth power and one of the five residue powers of `φ`.
The possible sign is absorbed into the fifth power because the exponent is odd. -/
theorem unit_eq_fifth_mul_phiUnit_pow_mod_five (u : MaximalOrderˣ) :
    ∃ v : MaximalOrderˣ, ∃ r : ℕ, r < 5 ∧ u = v ^ 5 * phiUnit ^ r := by
  obtain ⟨n, hn | hn⟩ := unit_eq_sign_mul_phiUnit_zpow u
  all_goals
    let r : ℕ := n.natMod 5
    let q : ℤ := n / 5
    have hr : r < 5 := Int.natMod_lt (by norm_num)
    have hrem : (r : ℤ) = n % 5 := by
      dsimp [r, Int.natMod]
      rw [Int.toNat_of_nonneg (Int.emod_nonneg n (by norm_num))]
    have hdecomp : n = (r : ℤ) + 5 * q := by
      dsimp [q]
      rw [hrem]
      exact (Int.emod_add_mul_ediv n 5).symm
  · refine ⟨phiUnit ^ q, r, hr, ?_⟩
    calc
      u = phiUnit ^ n := hn
      _ = (phiUnit ^ q) ^ 5 * phiUnit ^ r := by
        rw [hdecomp]
        group
  · refine ⟨-(phiUnit ^ q), r, hr, ?_⟩
    calc
      u = -phiUnit ^ n := hn
      _ = (-(phiUnit ^ q)) ^ 5 * phiUnit ^ r := by
        rw [hdecomp]
        rw [(show Odd 5 by decide).neg_pow]
        rw [neg_mul]
        congr 1
        group

end MaximalOrder

end Fermat.Quadratic.Golden
