/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, Fable

# The conductor-59 Artin--Hasse generator inventory

This file records the Stage-3 formula-budget decision.  It contains no wild
symbol and asserts no Artin--Hasse special value.  It also names the exact
decomposition interface which would be sufficient to revisit that decision.

Three generator kinds have explicit cyclotomic provenance in the selected
cone:

* `StateFactorPair.zetaUnit` is the chosen root of unity;
* `StateFactorPair.fixedDenominator` is `zeta - 1`, hence an associate of
  `1 - zeta`; and
* `Credit.generatedUnit` is generated from geometric cyclotomic units.

The two values actually supplied to the wild pairing do not presently carry
such a decomposition.  The statewise value is obtained through
`CommonActionStage.allocatedSelmerObstruction`, whose underlying
`ExactFilteredPair.liftClassPair` is a chosen preimage of the class
projection.  The detector value is the unrestricted
`TateBridge.TransverseDetector.detector`.  In the seated realization both
are Kummer classes; `SelmerEigenspace.quotientRepresentative` chooses a
representative and proves only the Selmer valuation receipt, not membership
in the cyclotomic-unit subgroup.

Accordingly, `needsVostokov` below means that the currently available
decomposition evidence does not reduce every actual input to the two special
Artin--Hasse families.  It is deliberately not a theorem that a future
explicit representative cannot lie in that subgroup: supplying the two
missing decompositions would justify revisiting the budget.
-/
import Fermat.Conservation.TameSymbol
import Fermat.FiftyNine.Conservation.Credit
import Fermat.FiftyNine.Conservation.StateFactorPair
import Mathlib.Tactic

open scoped BigOperators NumberField

namespace Fermat.FiftyNine.Conservation.ArtinHasseInventory

open Fermat.Conservation
open Fermat.FiftyNine.Conservation
open Fermat.FiftyNine.Conservation.FermatState

noncomputable section

local instance : Fact (Nat.Prime 59) := ⟨by norm_num⟩

/-! ## The exact decomposition interface -/

variable {K : Type*} [Field K] [NumberField K]
  [IsCyclotomicExtension {59} ℚ K]
  {ζ : K}

local instance : NumberField.IsCMField K :=
  IsCyclotomicExtension.Rat.isCMField
    (S := {59}) K ⟨59, rfl, by norm_num⟩

/-- The Kummer class of a nonzero field element. -/
def fieldKummerClass (a : Kˣ) : TameSymbol.KummerClass 59 K :=
  Additive.ofMul
    (QuotientGroup.mk' (powMonoidHom 59 : Kˣ →* Kˣ).range a)

/-- The Kummer class of an integral unit after embedding it in the field. -/
def integralUnitKummerClass (u : (𝓞 K)ˣ) :
    TameSymbol.KummerClass 59 K :=
  fieldKummerClass (Units.map (algebraMap (𝓞 K) K) u)

/-- The Kummer class of a nonzero algebraic integer after embedding it in
the field.  This is needed for `ζ - 1` and for the two normalized factors,
which are not asserted to be global units. -/
def integralNonzeroKummerClass (a : 𝓞 K) (ha : a ≠ 0) :
    TameSymbol.KummerClass 59 K :=
  fieldKummerClass
    (Units.mk0 (algebraMap (𝓞 K) K a)
      ((FaithfulSMul.algebraMap_injective (𝓞 K) K).ne ha))

/-- The root-of-unity generator in the Artin--Hasse Kummer subgroup. -/
def zetaKummerClass (hζ : IsPrimitiveRoot ζ 59) :
    TameSymbol.KummerClass 59 K :=
  integralUnitKummerClass (StateFactorPair.zetaUnit hζ)

/-- The `ζ - 1` generator in the Artin--Hasse Kummer subgroup. -/
def fixedDenominatorKummerClass (hζ : IsPrimitiveRoot ζ 59) :
    TameSymbol.KummerClass 59 K :=
  integralNonzeroKummerClass (StateFactorPair.fixedDenominator hζ)
    (StateFactorPair.fixedDenominator_ne_zero hζ)

/-- One of the 28 generated real cyclotomic-unit Kummer classes. -/
def generatedUnitKummerClass (hζ : IsPrimitiveRoot ζ 59)
    (i : Credit.LedgerNode) : TameSymbol.KummerClass 59 K :=
  integralUnitKummerClass (Credit.generatedUnit hζ i : (𝓞 K)ˣ)

/-- The additive subgroup generated by the three advertised Artin--Hasse
families: the selected root of unity, `ζ - 1`, and the 28 generated real
cyclotomic units. -/
def artinHasseKummerSubgroup (hζ : IsPrimitiveRoot ζ 59) :
    AddSubgroup (TameSymbol.KummerClass 59 K) :=
  AddSubgroup.closure
    ({zetaKummerClass hζ, fixedDenominatorKummerClass hζ} ∪
      Set.range (generatedUnitKummerClass hζ))

/-- The Kummer class of the normalized factor at `ζ`. -/
def normalizedPlusKummerClass
    (hζ : IsPrimitiveRoot ζ 59)
    (S : PrimitiveSecondCaseSolution) (hz : (59 : ℤ) ∣ S.z) :
    TameSymbol.KummerClass 59 K :=
  integralNonzeroKummerClass (StateFactorPair.normalizedPlusFactor hζ S hz)
    (StateFactorPair.normalizedPlusFactor_ne_zero hζ S hz)

/-- The Kummer class of the normalized factor at `ζ⁻¹`. -/
def normalizedMinusKummerClass
    (hζ : IsPrimitiveRoot ζ 59)
    (S : PrimitiveSecondCaseSolution) (hz : (59 : ℤ) ∣ S.z) :
    TameSymbol.KummerClass 59 K :=
  integralNonzeroKummerClass (StateFactorPair.normalizedMinusFactor hζ S hz)
    (StateFactorPair.normalizedMinusFactor_ne_zero hζ S hz)

/-- Explicit integer coefficients for an element of the advertised
Artin--Hasse Kummer subgroup.  The equality, rather than mere subgroup
membership, is the data needed to reduce a wild-symbol computation to the
three known generator families. -/
structure ArtinHasseKummerDecomposition
    (hζ : IsPrimitiveRoot ζ 59)
    (x : TameSymbol.KummerClass 59 K) where
  zetaCoefficient : ℤ
  denominatorCoefficient : ℤ
  generatedCoefficient : Credit.LedgerNode → ℤ
  decomposition :
    x = zetaCoefficient • zetaKummerClass hζ +
      denominatorCoefficient • fixedDenominatorKummerClass hζ +
      ∑ i, generatedCoefficient i • generatedUnitKummerClass hζ i

theorem ArtinHasseKummerDecomposition.mem
    {hζ : IsPrimitiveRoot ζ 59}
    {x : TameSymbol.KummerClass 59 K}
    (d : ArtinHasseKummerDecomposition hζ x) :
    x ∈ artinHasseKummerSubgroup hζ := by
  let H := artinHasseKummerSubgroup hζ
  have hzeta : zetaKummerClass hζ ∈ H := by
    apply AddSubgroup.subset_closure
    simp
  have hdenominator : fixedDenominatorKummerClass hζ ∈ H := by
    apply AddSubgroup.subset_closure
    simp
  have hgenerated : ∀ i, generatedUnitKummerClass hζ i ∈ H := by
    intro i
    apply AddSubgroup.subset_closure
    simp
  have hsum :
      (∑ i, d.generatedCoefficient i • generatedUnitKummerClass hζ i) ∈ H := by
    apply sum_mem
    intro i _
    exact H.zsmul_mem (hgenerated i) (d.generatedCoefficient i)
  rw [d.decomposition]
  exact H.add_mem
    (H.add_mem
      (H.zsmul_mem hzeta d.zetaCoefficient)
      (H.zsmul_mem hdenominator d.denominatorCoefficient))
    hsum

/-- **Named `NEEDS-VOSTOKOV` discharge interface.**  Supplying explicit
Artin--Hasse expansions for both normalized state factors is sufficient to
replace a general Vostokov formula for those two factor classes.  It does
not identify either factor with the separately chosen statewise Selmer lift
or transverse detector, and it contains no wild-symbol evaluation. -/
structure NormalizedStateFactorArtinHasseDecomposition
    (hζ : IsPrimitiveRoot ζ 59)
    (S : PrimitiveSecondCaseSolution) (hz : (59 : ℤ) ∣ S.z) where
  plus : ArtinHasseKummerDecomposition hζ
    (normalizedPlusKummerClass hζ S hz)
  minus : ArtinHasseKummerDecomposition hζ
    (normalizedMinusKummerClass hζ S hz)

theorem NormalizedStateFactorArtinHasseDecomposition.plus_mem
    {hζ : IsPrimitiveRoot ζ 59}
    {S : PrimitiveSecondCaseSolution} {hz : (59 : ℤ) ∣ S.z}
    (d : NormalizedStateFactorArtinHasseDecomposition hζ S hz) :
    normalizedPlusKummerClass hζ S hz ∈ artinHasseKummerSubgroup hζ :=
  d.plus.mem

theorem NormalizedStateFactorArtinHasseDecomposition.minus_mem
    {hζ : IsPrimitiveRoot ζ 59}
    {S : PrimitiveSecondCaseSolution} {hz : (59 : ℤ) ∣ S.z}
    (d : NormalizedStateFactorArtinHasseDecomposition hζ S hz) :
    normalizedMinusKummerClass hζ S hz ∈ artinHasseKummerSubgroup hζ :=
  d.minus.mem

/-- Provenance classes relevant to the conductor-59 wild-symbol budget. -/
inductive WildClassKind
  | rootOfUnity
  | oneSubRoot
  | cyclotomicUnit
  | statewiseSelmerLift
  | transverseDetectorComponent
  deriving DecidableEq, Repr

/-- Whether the selected cone currently exposes the advertised
Artin--Hasse-generator decomposition for this kind of input. -/
def hasArtinHasseDecomposition : WildClassKind → Bool
  | .rootOfUnity => true
  | .oneSubRoot => true
  | .cyclotomicUnit => true
  | .statewiseSelmerLift => false
  | .transverseDetectorComponent => false

/-- The two possible budgets named by the Stage-3 fork check. -/
inductive WildFormulaBudget
  | ahSuffices
  | needsVostokov
  deriving DecidableEq, Repr

/-- Special formulas suffice exactly when every inventoried input comes with
the corresponding generator decomposition in the current cone. -/
def formulaBudget (inventory : List WildClassKind) : WildFormulaBudget :=
  if inventory.all hasArtinHasseDecomposition then
    .ahSuffices
  else
    .needsVostokov

/-- The complete selected inventory: the three advertised generators and
the two opaque values actually entering the wild pairing. -/
def campaignInventory : List WildClassKind :=
  [.rootOfUnity, .oneSubRoot, .cyclotomicUnit,
    .statewiseSelmerLift, .transverseDetectorComponent]

/-- **Stage-3 fork verdict: `NEEDS-VOSTOKOV`.**  The verdict is a coverage
audit of available decompositions, not an invented non-membership theorem. -/
theorem campaign_formulaBudget_eq_needsVostokov :
    formulaBudget campaignInventory = .needsVostokov := by
  rfl

end

end Fermat.FiftyNine.Conservation.ArtinHasseInventory
