/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, Fable

# The generated capacity certificate at conductor 59

This is the residue-functional realization of the generated credit edges.
The auxiliary prime, root, orbit, and all matrix entries are computed from
the `7 → 29 → 59` tower in `Credit`; the inverse below is only a proof
certificate for the resulting generated matrix.
-/
import Fermat.FiftyNine.Conservation.Credit
import Mathlib.LinearAlgebra.FreeModule.Finite.CardQuotient

open scoped BigOperators NumberField

namespace Fermat.FiftyNine.Conservation.CapacityCertificate

open Fermat.FiftyNine.Conservation.Credit
open Polynomial Module NumberField NumberField.InfinitePlace

noncomputable section

/-! ## The generated finite-field unfolding -/

local instance : Fact (Nat.Prime 59) := ⟨by norm_num⟩
local instance : Fact (Nat.Prime attestationPrime) :=
  ⟨attestationPrime_isPrime⟩

/-- The row root is generated by advancing through the nontrivial first
half of the order-59 root cycle. -/
def rowRoot (j : LedgerNode) : ZMod attestationPrime :=
  attestationRoot ^ (j.val + 1)

/-- The exponent at the `n`th node of the one order-29 recursion. -/
def nodeExponent (n : ℕ) : ℕ :=
  ZMod.val ((exponentGenerator ^ n : (ZMod 59)ˣ) : ZMod 59)

/-- Evaluation of the geometric unit at a generated row root. -/
def geometricResidue (j : LedgerNode) (n : ℕ) :
    ZMod attestationPrime :=
  ∑ k ∈ Finset.range (nodeExponent n), rowRoot j ^ k

/-- The residue of the real projection is the product of the two conjugate
geometric evaluations. -/
def realNodeResidue (j : LedgerNode) (n : ℕ) :
    ZMod attestationPrime :=
  geometricResidue j n *
    ∑ k ∈ Finset.range (nodeExponent n), (rowRoot j)⁻¹ ^ k

/-- Residue of the generated edge from node `i` to node `i+1`. -/
def edgeResidue (j i : LedgerNode) : ZMod attestationPrime :=
  realNodeResidue j (i.val + 1) / realNodeResidue j i.val

/-- A computable discrete logarithm on the particular fourteenth powers
that occur in the generated edge matrix.  Uniqueness is supplied later by
the exact order of `attestationRoot`; for computation it is useful to keep
the finite search visible. -/
def generatedMatrix : Matrix LedgerNode LedgerNode (ZMod 59) :=
  fun j i ↦
    ∑ k : Fin 59,
      if edgeResidue j i ^ (2 * 7) = attestationRoot ^ k.val
      then (k.val : ZMod 59)
      else 0

/-- An independently computed inverse of the matrix generated above. -/
def generatedMatrixInverse : Matrix LedgerNode LedgerNode (ZMod 59) := ![
  ![34, 29, 44, 1, 40, 12, 37, 56, 54, 48, 1, 42, 34, 6, 15, 17, 45, 57, 53, 9, 22, 38, 15, 38, 38, 26, 13, 35],
  ![6, 56, 57, 48, 20, 21, 43, 40, 40, 13, 46, 14, 42, 21, 20, 28, 11, 3, 10, 2, 31, 9, 12, 47, 7, 3, 32, 18],
  ![26, 13, 2, 32, 45, 3, 58, 32, 10, 2, 24, 32, 21, 7, 24, 40, 29, 43, 8, 43, 32, 41, 21, 50, 44, 50, 29, 0],
  ![53, 48, 4, 28, 11, 49, 24, 13, 3, 43, 12, 53, 20, 54, 28, 49, 42, 6, 10, 28, 53, 25, 52, 7, 9, 20, 2, 25],
  ![14, 53, 49, 2, 20, 30, 14, 10, 58, 10, 40, 6, 10, 21, 20, 39, 0, 29, 47, 14, 42, 49, 46, 15, 55, 32, 8, 36],
  ![42, 45, 56, 46, 1, 33, 20, 11, 47, 42, 27, 29, 54, 2, 35, 43, 50, 14, 0, 57, 24, 44, 53, 34, 14, 53, 29, 12],
  ![35, 54, 28, 58, 52, 1, 4, 40, 3, 3, 50, 24, 9, 17, 12, 32, 47, 7, 58, 47, 50, 52, 23, 37, 7, 42, 10, 23],
  ![38, 15, 14, 38, 33, 54, 6, 12, 23, 52, 18, 38, 43, 39, 55, 15, 53, 12, 46, 5, 34, 43, 3, 36, 50, 48, 21, 41],
  ![57, 26, 8, 1, 30, 33, 4, 3, 42, 20, 41, 45, 25, 5, 38, 35, 53, 26, 32, 28, 57, 23, 48, 7, 35, 50, 50, 15],
  ![9, 6, 4, 10, 42, 52, 26, 21, 17, 54, 13, 57, 12, 47, 46, 21, 2, 56, 21, 40, 31, 12, 39, 35, 38, 5, 7, 42],
  ![38, 44, 36, 16, 15, 41, 14, 57, 28, 4, 41, 49, 54, 4, 18, 53, 56, 4, 49, 34, 54, 32, 14, 44, 29, 8, 2, 22],
  ![6, 42, 49, 10, 30, 12, 15, 14, 24, 53, 34, 39, 4, 57, 9, 47, 29, 8, 6, 19, 7, 53, 38, 26, 57, 45, 32, 32],
  ![2, 1, 41, 6, 17, 55, 27, 46, 50, 12, 27, 34, 7, 13, 38, 5, 27, 19, 40, 33, 37, 55, 18, 49, 4, 41, 24, 5],
  ![39, 15, 18, 5, 13, 1, 41, 20, 12, 28, 38, 9, 1, 46, 16, 33, 35, 4, 20, 45, 25, 37, 55, 33, 56, 38, 24, 30],
  ![24, 34, 38, 19, 11, 30, 52, 6, 35, 53, 2, 6, 1, 9, 39, 15, 42, 43, 14, 19, 4, 23, 38, 1, 27, 57, 26, 21],
  ![19, 1, 16, 41, 25, 38, 24, 48, 58, 28, 6, 10, 52, 10, 5, 53, 46, 24, 2, 38, 15, 4, 38, 27, 47, 1, 32, 31],
  ![15, 17, 53, 53, 18, 38, 8, 28, 32, 49, 5, 47, 57, 21, 33, 41, 43, 49, 39, 23, 9, 37, 15, 41, 2, 35, 40, 13],
  ![11, 40, 15, 25, 46, 36, 33, 20, 52, 11, 17, 30, 25, 42, 13, 18, 1, 38, 20, 1, 7, 21, 33, 58, 11, 30, 45, 56],
  ![19, 9, 34, 38, 1, 30, 53, 2, 47, 28, 33, 19, 27, 40, 45, 23, 57, 42, 14, 35, 52, 57, 5, 19, 36, 28, 43, 31],
  ![4, 22, 54, 15, 7, 22, 0, 31, 50, 53, 37, 7, 19, 31, 25, 9, 24, 16, 42, 52, 49, 29, 34, 27, 12, 57, 32, 56],
  ![27, 38, 29, 47, 11, 17, 12, 7, 7, 9, 4, 57, 12, 38, 56, 2, 14, 54, 55, 36, 12, 16, 50, 45, 32, 35, 44, 35],
  ![43, 57, 4, 24, 38, 19, 34, 3, 7, 6, 19, 8, 8, 56, 4, 49, 14, 31, 29, 42, 16, 0, 12, 16, 54, 26, 43, 14],
  ![1, 34, 54, 52, 25, 30, 53, 42, 9, 20, 7, 4, 11, 12, 1, 57, 54, 8, 10, 27, 19, 40, 43, 40, 12, 25, 21, 56],
  ![52, 37, 14, 24, 33, 18, 0, 43, 4, 24, 27, 15, 53, 26, 41, 8, 20, 34, 14, 53, 0, 4, 6, 44, 12, 4, 58, 31],
  ![21, 35, 22, 31, 56, 19, 31, 18, 23, 25, 5, 32, 56, 42, 30, 13, 12, 14, 36, 31, 56, 1, 41, 5, 35, 15, 0, 16],
  ![30, 12, 41, 38, 36, 41, 18, 21, 1, 49, 55, 12, 30, 52, 1, 38, 33, 19, 30, 30, 22, 3, 54, 4, 17, 33, 3, 19],
  ![1, 38, 44, 27, 58, 4, 44, 47, 37, 7, 49, 26, 40, 35, 33, 41, 34, 16, 15, 19, 27, 26, 36, 29, 45, 7, 50, 5],
  ![23, 38, 32, 4, 21, 3, 4, 9, 52, 25, 55, 53, 40, 12, 37, 37, 44, 0, 49, 57, 29, 0, 43, 26, 16, 23, 41, 1]
]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every generated matrix entry records the actual fourteenth-power
symbol of its generated edge. -/
private theorem generatedMatrix_entry_certificate :
    ∀ j i,
      edgeResidue j i ^ (2 * 7) =
        attestationRoot ^ (generatedMatrix j i).val := by
  decide +kernel +revert

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Kernel-checked nonsingularity certificate for the generated matrix. -/
private theorem generatedMatrix_mul_inverse :
    generatedMatrix * generatedMatrixInverse = 1 := by
  decide +kernel +revert

/-- The generated residue matrix is nonsingular over `ZMod 59`. -/
private theorem generatedMatrix_det_ne_zero :
    generatedMatrix.det ≠ 0 := by
  intro h
  have hdet := congrArg Matrix.det generatedMatrix_mul_inverse
  rw [Matrix.det_mul, h, zero_mul, Matrix.det_one] at hdet
  exact (by decide : (0 : ZMod 59) ≠ 1) hdet

/-! ## Actual residue characters on cyclotomic units -/

private theorem rowRoot_isPrimitive (j : LedgerNode) :
    IsPrimitiveRoot (rowRoot j) 59 := by
  apply (IsPrimitiveRoot.iff_orderOf.mpr attestationRoot_order).pow_of_coprime
  have hj : j.val < 28 := by
    simpa only [LedgerNode, exponentCycle_rank] using j.isLt
  exact Nat.Coprime.symm <| Nat.coprime_of_lt_prime
    (by omega) (by omega) (by norm_num)

/-- The generated root bundled as a unit of the attestation field. -/
def attestationRootUnit : (ZMod attestationPrime)ˣ :=
  Units.mk0 attestationRoot
    ((IsPrimitiveRoot.iff_orderOf.mpr attestationRoot_order).ne_zero
      (by norm_num))

private theorem attestationRootUnit_isPrimitive :
    IsPrimitiveRoot attestationRootUnit 59 := by
  apply IsPrimitiveRoot.coe_units_iff.mp
  simpa [attestationRootUnit] using
    (IsPrimitiveRoot.iff_orderOf.mpr attestationRoot_order :
      IsPrimitiveRoot attestationRoot 59)

/-- Raising a nonzero attestation residue to the generated exponent
`2 * 7` lands in the powers of the order-59 root. -/
noncomputable def symbolPower :
    (ZMod attestationPrime)ˣ →* Subgroup.zpowers attestationRootUnit where
  toFun u := ⟨u ^ (2 * 7), by
    rw [attestationRootUnit_isPrimitive.zpowers_eq, mem_rootsOfUnity]
    calc
      (u ^ (2 * 7)) ^ 59 = u ^ (attestationPrime - 1) := by
        rw [← pow_mul]
        norm_num [attestationPrime]
      _ = 1 :=
        ZMod.units_pow_card_sub_one_eq_one attestationPrime u⟩
  map_one' := by ext; simp
  map_mul' u v := by ext; simp [mul_pow]

/-- The order-59 logarithm of the fourteenth-power residue symbol. -/
noncomputable def residueLog :
    Additive (ZMod attestationPrime)ˣ →+ ZMod 59 :=
  attestationRootUnit_isPrimitive.zmodEquivZPowers.symm.toAddMonoidHom.comp
    symbolPower.toAdditive

private theorem residueLog_eq_of_symbol (u : (ZMod attestationPrime)ˣ) (m : ℕ)
    (h : ((u : ZMod attestationPrime) ^ (2 * 7)) =
      attestationRoot ^ m) :
    residueLog (Additive.ofMul u) = (m : ZMod 59) := by
  have hpower : symbolPower u =
      (⟨attestationRootUnit ^ m, m, rfl⟩ :
        Subgroup.zpowers attestationRootUnit) := by
    apply Subtype.ext
    change u ^ (2 * 7) = attestationRootUnit ^ m
    apply Units.ext
    simpa [attestationRootUnit] using h
  change attestationRootUnit_isPrimitive.zmodEquivZPowers.symm
    (Additive.ofMul (symbolPower u)) = (m : ZMod 59)
  rw [hpower,
    attestationRootUnit_isPrimitive.zmodEquivZPowers_symm_apply_pow]

variable {K : Type*} [Field K] [NumberField K]
  [IsCyclotomicExtension {59} ℚ K]
variable {ζ : K} (hζ : IsPrimitiveRoot ζ 59)

local instance : NumberField.IsCMField K :=
  IsCyclotomicExtension.Rat.isCMField
    (S := {59}) K ⟨59, rfl, by norm_num⟩

omit [IsCyclotomicExtension {59} ℚ K] in
private theorem minpoly_toInteger_eq_cyclotomic :
    minpoly ℤ hζ.toInteger = Polynomial.cyclotomic 59 ℤ := by
  apply Polynomial.map_injective (algebraMap ℤ ℚ)
    (RingHom.injective_int (algebraMap ℤ ℚ))
  rw [← minpoly.isIntegrallyClosed_eq_field_fractions ℚ K,
    show algebraMap (𝓞 K) K hζ.toInteger = ζ from rfl,
    ← Polynomial.cyclotomic_eq_minpoly_rat hζ (by norm_num),
    Polynomial.map_cyclotomic]
  exact IsIntegralClosure.isIntegral _ K _

/-- Evaluation of cyclotomic integers at the generated row root modulo the
generated prime 827. -/
noncomputable def reductionHom (j : LedgerNode) :
    𝓞 K →+* ZMod attestationPrime :=
  (hζ.integralPowerBasis.lift (rowRoot j) (by
    rw [hζ.integralPowerBasis_gen, minpoly_toInteger_eq_cyclotomic hζ]
    simpa [Polynomial.aeval_def, Polynomial.eval₂_eq_eval_map,
      Polynomial.map_cyclotomic, IsRoot.def] using
      (rowRoot_isPrimitive j).isRoot_cyclotomic (by norm_num))).toRingHom

@[simp]
private theorem reductionHom_zeta (j : LedgerNode) :
    reductionHom hζ j hζ.toInteger = rowRoot j := by
  rw [reductionHom, ← hζ.integralPowerBasis_gen]
  exact PowerBasis.lift_gen _ _ _

/-- The integral primitive root bundled as a unit. -/
def integralRootUnit : (𝓞 K)ˣ :=
  (hζ.toInteger_isPrimitiveRoot.isUnit (by norm_num)).unit

@[simp]
private theorem integralRootUnit_val :
    (integralRootUnit hζ : 𝓞 K) = hζ.toInteger := by
  rfl

/-- The geometric orbit unit specializes to its generated geometric
residue. -/
private theorem reductionHom_orbitNodeUnit (j : LedgerNode) (a : (ZMod 59)ˣ) :
    reductionHom hζ j (orbitNodeUnit hζ a : 𝓞 K) =
      ∑ k ∈ Finset.range (ZMod.val (a : ZMod 59)), rowRoot j ^ k := by
  simp [orbitNodeUnit, reductionHom_zeta]

/-- Complex conjugation inverts the chosen primitive root. -/
private theorem complexConj_zeta (hζ : IsPrimitiveRoot ζ 59) :
    NumberField.IsCMField.complexConj K ζ = ζ⁻¹ := by
  let u : (𝓞 K)ˣ := integralRootUnit hζ
  have hupow : u ^ 59 = 1 := by
    apply Units.ext
    apply NumberField.RingOfIntegers.ext
    simpa [u] using hζ.pow_eq_one
  have hutorsion : u ∈ NumberField.Units.torsion K := by
    rw [NumberField.Units.torsion, CommGroup.mem_torsion,
      isOfFinOrder_iff_pow_eq_one]
    exact ⟨59, by norm_num, hupow⟩
  have hconj :
      NumberField.IsCMField.unitsComplexConj K u = u⁻¹ := by
    simpa using NumberField.IsCMField.unitsComplexConj_torsion
      (K := K) (⟨u, hutorsion⟩ : NumberField.Units.torsion K)
  have hval := congrArg Units.val hconj
  simpa [u, integralRootUnit,
    NumberField.IsCMField.unitsComplexConj,
    NumberField.IsCMField.ringOfIntegersComplexConj,
    NumberField.RingOfIntegers.ext_iff] using
      congrArg ((↑) : 𝓞 K → K) hval

/-- Conjugating a geometric orbit unit replaces the primitive root by its
inverse, before any finite-field reduction is taken. -/
private theorem unitsComplexConj_orbitNodeUnit_val (a : (ZMod 59)ˣ) :
    (NumberField.IsCMField.unitsComplexConj K
        (orbitNodeUnit hζ a) : 𝓞 K) =
      ∑ k ∈ Finset.range (ZMod.val (a : ZMod 59)),
        ((((integralRootUnit hζ)⁻¹ : (𝓞 K)ˣ) ^ k :
          (𝓞 K)ˣ) : 𝓞 K) := by
  apply NumberField.RingOfIntegers.ext
  change NumberField.IsCMField.complexConj K
      (((orbitNodeUnit hζ a : (𝓞 K)ˣ) : 𝓞 K) : K) = _
  simp only [orbitNodeUnit, Units.val_pow_eq_pow_val,
    map_sum, map_pow, ← NumberField.RingOfIntegers.coe_eq_algebraMap]
  simp [complexConj_zeta hζ, integralRootUnit]

/-- The reduction of a conjugated orbit node is evaluation at the inverse
row root. -/
private theorem reductionHom_conjugate_orbitNodeUnit
    (j : LedgerNode) (a : (ZMod 59)ˣ) :
    reductionHom hζ j
        (NumberField.IsCMField.unitsComplexConj K
          (orbitNodeUnit hζ a) : 𝓞 K) =
      ∑ k ∈ Finset.range (ZMod.val (a : ZMod 59)),
        (rowRoot j)⁻¹ ^ k := by
  rw [unitsComplexConj_orbitNodeUnit_val hζ]
  simp [integralRootUnit, reductionHom_zeta]

/-- Each generated real node has exactly the finite-field value used to
generate the matrix. -/
private theorem reductionHom_realOrbitNode (j : LedgerNode) (a : (ZMod 59)ˣ) :
    reductionHom hζ j (realOrbitNode hζ a : (𝓞 K)ˣ) =
      (∑ k ∈ Finset.range (ZMod.val (a : ZMod 59)), rowRoot j ^ k) *
      ∑ k ∈ Finset.range (ZMod.val (a : ZMod 59)),
        (rowRoot j)⁻¹ ^ k := by
  rw [realOrbitNode,
    Fermat.Conservation.Credit.Flow.realCyclotomicOrbitNode_val]
  simp only [Units.val_mul, map_mul]
  change
    reductionHom hζ j (orbitNodeUnit hζ a : 𝓞 K) *
        reductionHom hζ j
          (NumberField.IsCMField.unitsComplexConj K
            (orbitNodeUnit hζ a) : 𝓞 K) =
      (∑ k ∈ Finset.range (ZMod.val (a : ZMod 59)), rowRoot j ^ k) *
        ∑ k ∈ Finset.range (ZMod.val (a : ZMod 59)),
          (rowRoot j)⁻¹ ^ k
  rw [reductionHom_orbitNodeUnit hζ,
    reductionHom_conjugate_orbitNodeUnit hζ]

/-- The actual generated edge specializes to the generated edge residue. -/
private theorem reductionHom_generatedUnit (j i : LedgerNode) :
    reductionHom hζ j (generatedUnit hζ i : (𝓞 K)ˣ) =
      edgeResidue j i := by
  rw [generatedUnit_eq_orbit_ratio]
  change reductionHom hζ j
      ((((realOrbitNode hζ
            (exponentCycle.point (i.val + 1))).1 *
          (realOrbitNode hζ
            (exponentCycle.point i.val)).1⁻¹ : (𝓞 K)ˣ) : 𝓞 K)) =
    edgeResidue j i
  change ((Units.map (reductionHom hζ j)
      ((realOrbitNode hζ
          (exponentCycle.point (i.val + 1))).1 *
        (realOrbitNode hζ
          (exponentCycle.point i.val)).1⁻¹) :
      (ZMod attestationPrime)ˣ) : ZMod attestationPrime) =
    edgeResidue j i
  rw [map_mul, map_inv]
  rw [Units.val_mul, Units.val_inv_eq_inv_val,
    Units.coe_map, Units.coe_map]
  change reductionHom hζ j
      (realOrbitNode hζ
        (exponentCycle.point (i.val + 1)) : (𝓞 K)ˣ) *
      (reductionHom hζ j
        (realOrbitNode hζ
          (exponentCycle.point i.val) : (𝓞 K)ˣ))⁻¹ =
    edgeResidue j i
  rw [reductionHom_realOrbitNode hζ, reductionHom_realOrbitNode hζ,
    exponentCycle_point, exponentCycle_point]
  rfl

/-- The CM norm kills full-field torsion and squares every real unit. -/
noncomputable def realNorm : (𝓞 K)ˣ →* (𝓞 K)ˣ where
  toFun u := u * NumberField.IsCMField.unitsComplexConj K u
  map_one' := by simp
  map_mul' u v := by
    simp only [map_mul]
    ac_rfl

private theorem realNorm_eq_one_of_torsion (u : (𝓞 K)ˣ)
    (hu : u ∈ NumberField.Units.torsion K) :
    realNorm u = 1 := by
  have hc : NumberField.IsCMField.unitsComplexConj K u = u⁻¹ := by
    simpa using NumberField.IsCMField.unitsComplexConj_torsion
      (K := K) (⟨u, hu⟩ : NumberField.Units.torsion K)
  change u * NumberField.IsCMField.unitsComplexConj K u = 1
  rw [hc, mul_inv_cancel]

@[simp]
private theorem realNorm_generatedUnit (i : LedgerNode) :
    realNorm (generatedUnit hζ i : (𝓞 K)ˣ) =
      (generatedUnit hζ i : (𝓞 K)ˣ) ^ 2 := by
  change (generatedUnit hζ i : (𝓞 K)ˣ) *
      NumberField.IsCMField.unitsComplexConj K
        (generatedUnit hζ i : (𝓞 K)ˣ) = _
  rw [(NumberField.IsCMField.unitsComplexConj_eq_self_iff K _).mpr
    (generatedUnit hζ i).2]
  exact (pow_two _).symm

/-- Division by two in the additive residue target. -/
def halfScale : ZMod 59 →+ ZMod 59 where
  toFun x := (2 : ZMod 59)⁻¹ * x
  map_zero' := by simp
  map_add' x y := by ring

/-- The corrected character on the full unit group.  The CM norm removes
all roots of unity, and the half-scale restores the original symbol on
real units. -/
noncomputable def correctedCharacter (j : LedgerNode) :
    Additive (𝓞 K)ˣ →+ ZMod 59 :=
  halfScale.comp <| residueLog.comp <|
    ((Units.map (reductionHom hζ j)).comp (realNorm (K := K))).toAdditive

private theorem correctedCharacter_eq_zero_of_torsion
    (j : LedgerNode) (u : (𝓞 K)ˣ)
    (hu : u ∈ NumberField.Units.torsion K) :
    correctedCharacter hζ j (Additive.ofMul u) = 0 := by
  rw [correctedCharacter]
  simp [realNorm_eq_one_of_torsion (K := K) u hu]

/-- The corrected character evaluates every actual generated edge to the
corresponding entry of the generated matrix. -/
private theorem correctedCharacter_generatedUnit (j i : LedgerNode) :
    correctedCharacter hζ j
        (Additive.ofMul (generatedUnit hζ i : (𝓞 K)ˣ)) =
      generatedMatrix j i := by
  let u : (ZMod attestationPrime)ˣ :=
    Units.map (reductionHom hζ j)
      (realNorm (generatedUnit hζ i : (𝓞 K)ˣ))
  have huval :
      (u : ZMod attestationPrime) = edgeResidue j i ^ 2 := by
    dsimp [u]
    rw [realNorm_generatedUnit hζ i, Units.val_pow_eq_pow_val,
      map_pow, reductionHom_generatedUnit hζ]
  have hsymbol :
      (u : ZMod attestationPrime) ^ (2 * 7) =
        attestationRoot ^ ((generatedMatrix j i).val * 2) := by
    calc
      (u : ZMod attestationPrime) ^ (2 * 7) =
          (edgeResidue j i ^ 2) ^ (2 * 7) := by rw [huval]
      _ = (edgeResidue j i ^ (2 * 7)) ^ 2 := by
        simp only [← pow_mul]
      _ = (attestationRoot ^ (generatedMatrix j i).val) ^ 2 := by
        rw [generatedMatrix_entry_certificate]
      _ = attestationRoot ^ ((generatedMatrix j i).val * 2) := by
        rw [pow_mul]
  change (2 : ZMod 59)⁻¹ * residueLog (Additive.ofMul u) =
    generatedMatrix j i
  rw [residueLog_eq_of_symbol u _ hsymbol, Nat.cast_mul,
    ZMod.natCast_zmod_val]
  have htwo : (2 : ZMod 59) ≠ 0 := by decide
  calc
    (2 : ZMod 59)⁻¹ * (generatedMatrix j i * 2) =
        (2⁻¹ * 2) * generatedMatrix j i := by ring
    _ = generatedMatrix j i := by
      rw [inv_mul_cancel₀ htwo, one_mul]

/-! ## Descent to the Dirichlet lattice -/

/-- The additive lattice of full units modulo roots of unity. -/
abbrev UnitLattice (K : Type*) [Field K] :=
  Additive ((𝓞 K)ˣ ⧸ NumberField.Units.torsion K)

local instance : Module ℤ (UnitLattice K) :=
  @AddCommGroup.toIntModule (UnitLattice K) (inferInstance)

/-- Class of a unit in the Dirichlet lattice. -/
def unitClass (u : (𝓞 K)ˣ) : UnitLattice K :=
  Additive.ofMul (QuotientGroup.mk u)

noncomputable def correctedCharacterMul (j : LedgerNode) :
    (𝓞 K)ˣ →* Multiplicative (ZMod 59) where
  toFun u := Multiplicative.ofAdd <|
    correctedCharacter hζ j (Additive.ofMul u)
  map_one' := by
    apply Multiplicative.toAdd.injective
    simp
  map_mul' u v := by
    apply Multiplicative.toAdd.injective
    exact map_add (correctedCharacter hζ j)
      (Additive.ofMul u) (Additive.ofMul v)

private theorem torsion_le_correctedCharacterMul_ker (j : LedgerNode) :
    NumberField.Units.torsion K ≤
      (correctedCharacterMul hζ j).ker := by
  intro u hu
  rw [MonoidHom.mem_ker]
  apply Multiplicative.toAdd.injective
  exact correctedCharacter_eq_zero_of_torsion hζ j u hu

noncomputable def quotientCharacterMul (j : LedgerNode) :
    ((𝓞 K)ˣ ⧸ NumberField.Units.torsion K) →*
      Multiplicative (ZMod 59) :=
  QuotientGroup.lift (NumberField.Units.torsion K)
    (correctedCharacterMul hζ j)
    (torsion_le_correctedCharacterMul_ker hζ j)

noncomputable def quotientCharacter (j : LedgerNode) :
    UnitLattice K →+ ZMod 59 where
  toFun x :=
    Multiplicative.toAdd (quotientCharacterMul hζ j x.toMul)
  map_zero' := by simp [quotientCharacterMul]
  map_add' x y := by
    change Multiplicative.toAdd
      (quotientCharacterMul hζ j (x.toMul * y.toMul)) = _
    rw [map_mul]
    rfl

/-- The residue character as a `ℤ`-linear functional on the unit lattice. -/
noncomputable def residueFunctional (j : LedgerNode) :
    UnitLattice K →ₗ[ℤ] ZMod 59 :=
  { quotientCharacter hζ j with
    map_smul' := fun n x ↦ (quotientCharacter hζ j).map_zsmul n x }

@[simp]
private theorem residueFunctional_generatedUnit (j i : LedgerNode) :
    residueFunctional hζ j
        (unitClass (generatedUnit hζ i : (𝓞 K)ˣ)) =
      generatedMatrix j i := by
  change quotientCharacter hζ j
    (unitClass (generatedUnit hζ i : (𝓞 K)ˣ)) = _
  change correctedCharacter hζ j
    (Additive.ofMul (generatedUnit hζ i : (𝓞 K)ˣ)) = _
  exact correctedCharacter_generatedUnit hζ j i

/-- Evaluation of lattice vectors by residue functionals. -/
def evaluationMatrix (u : LedgerNode → UnitLattice K)
    (f : LedgerNode → UnitLattice K →ₗ[ℤ] ZMod 59) :
    Matrix LedgerNode LedgerNode (ZMod 59) :=
  fun j i ↦ f j (u i)

/-- The actual residue functionals realize the generated matrix. -/
private theorem evaluationMatrix_generatedUnit :
    evaluationMatrix
      (unitClass ∘ fun i ↦ (generatedUnit hζ i : (𝓞 K)ˣ))
      (residueFunctional hζ) = generatedMatrix := by
  ext j i
  exact residueFunctional_generatedUnit hζ j i

/-- A 59th cyclotomic field has Dirichlet unit rank 28. -/
private theorem unitRank_eq_twentyEight :
    NumberField.Units.rank K = 28 := by
  rw [NumberField.Units.rank, card_eq_nrRealPlaces_add_nrComplexPlaces,
    IsCyclotomicExtension.Rat.nrRealPlaces_eq_zero K (n := 59)
      (by norm_num),
    IsCyclotomicExtension.Rat.nrComplexPlaces_eq_totient_div_two
      (K := K) 59]
  decide

/-- Dirichlet's basis, reindexed by the generated stock rank. -/
def unitLatticeBasis : Basis LedgerNode ℤ (UnitLattice K) :=
  (NumberField.Units.basisModTorsion K).reindex
    (finCongr ((unitRank_eq_twentyEight (K := K)).trans
      exponentCycle_rank.symm))

/-- Coordinates of a lattice family reduced modulo 59. -/
def coordinateMatrix (b : Basis LedgerNode ℤ (UnitLattice K))
    (u : LedgerNode → UnitLattice K) :
    Matrix LedgerNode LedgerNode (ZMod 59) :=
  fun k i ↦ (b.repr (u i) k : ZMod 59)

/-- Values of a functional family on the chosen Dirichlet basis. -/
def functionalMatrix (b : Basis LedgerNode ℤ (UnitLattice K))
    (f : LedgerNode → UnitLattice K →ₗ[ℤ] ZMod 59) :
    Matrix LedgerNode LedgerNode (ZMod 59) :=
  fun j k ↦ f j (b k)

private theorem evaluationMatrix_factor
    (b : Basis LedgerNode ℤ (UnitLattice K))
    (u : LedgerNode → UnitLattice K)
    (f : LedgerNode → UnitLattice K →ₗ[ℤ] ZMod 59) :
    evaluationMatrix u f = functionalMatrix b f * coordinateMatrix b u := by
  ext j i
  simp only [evaluationMatrix, functionalMatrix, coordinateMatrix,
    Matrix.mul_apply]
  calc
    f j (u i) = f j (∑ k, (b.repr (u i) k) • b k) := by
      congr 1
      exact (b.sum_repr (u i)).symm
    _ = ∑ k, f j ((b.repr (u i) k) • b k) := by
      rw [map_sum]
    _ = ∑ k, f j (b k) * (b.repr (u i) k : ZMod 59) := by
      apply Finset.sum_congr rfl
      intro k _
      rw [LinearMap.map_smul]
      simp [mul_comm]

private theorem coordinateMatrix_det
    (b : Basis LedgerNode ℤ (UnitLattice K))
    (u : LedgerNode → UnitLattice K) :
    (coordinateMatrix b u).det = (b.det u : ZMod 59) := by
  rw [b.det_apply]
  symm
  calc
    ((b.toMatrix u).det : ZMod 59) =
        ((Int.castRingHom (ZMod 59)).mapMatrix (b.toMatrix u)).det :=
      RingHom.map_det (Int.castRingHom (ZMod 59)) (b.toMatrix u)
    _ = (coordinateMatrix b u).det := by
      congr

/-- Nonsingular residue evaluation keeps the integral coordinate
determinant nonzero modulo 59. -/
private theorem coordinateDet_mod_ne_zero
    (b : Basis LedgerNode ℤ (UnitLattice K))
    (u : LedgerNode → UnitLattice K)
    (f : LedgerNode → UnitLattice K →ₗ[ℤ] ZMod 59)
    (h : (evaluationMatrix u f).det ≠ 0) :
    (b.det u : ZMod 59) ≠ 0 := by
  intro hzero
  apply h
  rw [evaluationMatrix_factor b u f, Matrix.det_mul,
    coordinateMatrix_det, hzero, mul_zero]

/-- The tested lattice vectors are integrally independent. -/
private theorem latticeIndependent_of_evaluation
    (b : Basis LedgerNode ℤ (UnitLattice K))
    (u : LedgerNode → UnitLattice K)
    (f : LedgerNode → UnitLattice K →ₗ[ℤ] ZMod 59)
    (h : (evaluationMatrix u f).det ≠ 0) :
    LinearIndependent ℤ u := by
  have hmod := coordinateDet_mod_ne_zero b u f h
  have hinter : b.det u ≠ 0 := by
    intro hz
    apply hmod
    simp [hz]
  letI : Module.Free ℤ (UnitLattice K) := Module.Free.of_basis b
  letI : Module.Finite ℤ (UnitLattice K) := Module.Finite.of_basis b
  let g : UnitLattice K →ₗ[ℤ] UnitLattice K := b.constr ℕ u
  have hgdet : LinearMap.det g = b.det u := by
    calc
      LinearMap.det g = ((LinearMap.toMatrix b b) g).det :=
        (LinearMap.det_toMatrix b g).symm
      _ = (b.toMatrix u).det :=
        congrArg Matrix.det (b.toMatrix_eq_toMatrix_constr u).symm
      _ = b.det u := (b.det_apply u).symm
  have hgker : LinearMap.ker g = ⊥ := by
    by_contra hk
    exact hinter (hgdet ▸ LinearMap.det_eq_zero_iff_ker_ne_bot.mpr hk)
  have hmapped := b.linearIndependent.map' g hgker
  have hfamily : g ∘ b = u := by
    funext i
    exact b.constr_basis ℕ u i
  rwa [hfamily] at hmapped

/-- The generated vectors have lattice quotient cardinal prime to 59. -/
private theorem not_dvd_latticeQuotient_of_evaluation
    (b : Basis LedgerNode ℤ (UnitLattice K))
    (u : LedgerNode → UnitLattice K)
    (f : LedgerNode → UnitLattice K →ₗ[ℤ] ZMod 59)
    (h : (evaluationMatrix u f).det ≠ 0) :
    ¬59 ∣ Nat.card
      (UnitLattice K ⧸ Submodule.span ℤ (Set.range u)) := by
  let independent := latticeIndependent_of_evaluation b u f h
  let spanBasis : Basis LedgerNode ℤ
      (Submodule.span ℤ (Set.range u)) := Basis.span independent
  letI : Module.Free ℤ (UnitLattice K) := Module.Free.of_basis b
  letI : Module.Finite ℤ (UnitLattice K) := Module.Finite.of_basis b
  have hcard := Submodule.natAbs_det_basis_change b
    (Submodule.span ℤ (Set.range u)) spanBasis
  have hspanFamily : ((↑) ∘ spanBasis : LedgerNode → UnitLattice K) = u := by
    funext i
    simp [spanBasis]
  rw [hspanFamily] at hcard
  rw [← hcard, ← Int.natCast_dvd]
  intro hdiv
  exact coordinateDet_mod_ne_zero b u f h <|
    (ZMod.intCast_zmod_eq_zero_iff_dvd (b.det u) 59).mpr hdiv

/-- The generated residue matrix proves the exact lattice quotient needed
for the edge family is prime to 59. -/
private theorem not_dvd_generatedUnit_latticeQuotient :
    ¬59 ∣ Nat.card
      (UnitLattice K ⧸ Submodule.span ℤ
        (Set.range
          (unitClass ∘ fun i ↦ (generatedUnit hζ i : (𝓞 K)ˣ)))) := by
  apply not_dvd_latticeQuotient_of_evaluation
    (unitLatticeBasis (K := K))
    (unitClass ∘ fun i ↦ (generatedUnit hζ i : (𝓞 K)ˣ))
    (residueFunctional hζ)
  rw [evaluationMatrix_generatedUnit hζ]
  exact generatedMatrix_det_ne_zero

/-! ## From the full-unit lattice to the real generated subgroup -/

/-- The quotient lattice cardinal is the index of the underlying unit
subgroup after adjoining the full cyclotomic torsion. -/
private theorem latticeQuotient_card_eq_augmentedIndex
    (u : LedgerNode → (𝓞 K)ˣ) :
    Nat.card
      (UnitLattice K ⧸
        Submodule.span ℤ (Set.range (unitClass ∘ u))) =
      (Subgroup.closure (Set.range u) ⊔
        NumberField.Units.torsion K).index := by
  let T := NumberField.Units.torsion K
  let q : (𝓞 K)ˣ →* ((𝓞 K)ˣ ⧸ T) := QuotientGroup.mk' T
  let H := Subgroup.closure (Set.range u)
  have hmapIndex :
      (H.map q).index = (H ⊔ T).index := by
    have h := Subgroup.index_map H q
    rw [show q.ker = T by
      exact QuotientGroup.ker_mk' T,
      show q.range = ⊤ by
        exact QuotientGroup.range_mk' T,
      Subgroup.index_top, mul_one] at h
    exact h
  have hspan :
      (Submodule.span ℤ
        (Set.range (unitClass ∘ u))).toAddSubgroup =
      (H.map q).toAddSubgroup := by
    rw [Submodule.span_int_eq_addSubgroupClosure,
      MonoidHom.map_closure, Subgroup.toAddSubgroup_closure]
    congr 1
    ext x
    simp only [Set.mem_range, Function.comp_apply, unitClass,
      Set.mem_preimage, Set.mem_image]
    constructor
    · rintro ⟨i, rfl⟩
      exact ⟨u i, ⟨⟨i, rfl⟩, rfl⟩⟩
    · rintro ⟨a, ⟨⟨i, rfl⟩, hax⟩⟩
      exact ⟨i, congrArg Additive.ofMul hax⟩
  change (Submodule.span ℤ
    (Set.range (unitClass ∘ u))).toAddSubgroup.index = _
  rw [hspan, ← Subgroup.index_toAddSubgroup]
  exact hmapIndex

/-- The generated matrix controls the full-unit subgroup with torsion
adjoined. -/
private theorem not_dvd_augmentedGenerated_index :
    ¬59 ∣
      (Subgroup.closure
        (Set.range fun i ↦ (generatedUnit hζ i : (𝓞 K)ˣ)) ⊔
        NumberField.Units.torsion K).index := by
  rw [← latticeQuotient_card_eq_augmentedIndex
    (fun i ↦ (generatedUnit hζ i : (𝓞 K)ˣ))]
  exact not_dvd_generatedUnit_latticeQuotient hζ

/-- The generated real subgroup, regarded in the full unit group, is
exactly the closure of the underlying generated units. -/
private theorem generatedSubledger_map_realUnitsSubtype :
    (generatedSubledger hζ).map
        (NumberField.IsCMField.realUnits K).subtype =
      Subgroup.closure
        (Set.range fun i ↦ (generatedUnit hζ i : (𝓞 K)ˣ)) := by
  rw [generatedSubledger, Fermat.Conservation.Credit.Cycle.generatedSubledger,
    MonoidHom.map_closure]
  congr 1
  ext u
  simp only [Set.mem_image, Set.mem_range]
  constructor
  · rintro ⟨x, ⟨i, rfl⟩, rfl⟩
    exact ⟨i, rfl⟩
  · rintro ⟨i, rfl⟩
    exact ⟨generatedUnit hζ i, ⟨i, rfl⟩, rfl⟩

/-- The matrix-controlled index remains prime to 59 after restricting the
ambient full unit group to real units with full torsion adjoined. -/
private theorem not_dvd_augmentedGenerated_realRelativeIndex :
    ¬59 ∣
      (Subgroup.closure
          (Set.range fun i ↦ (generatedUnit hζ i : (𝓞 K)ˣ)) ⊔
        NumberField.Units.torsion K).relIndex
        (NumberField.IsCMField.realUnits K ⊔
          NumberField.Units.torsion K) := by
  let H := Subgroup.closure
    (Set.range fun i ↦ (generatedUnit hζ i : (𝓞 K)ˣ))
  let T := NumberField.Units.torsion K
  let R := NumberField.IsCMField.realUnits K
  have hle : H ⊔ T ≤ R ⊔ T := by
    apply sup_le
    · apply (Subgroup.closure_le _).mpr
      rintro _ ⟨i, rfl⟩
      exact (show R ≤ R ⊔ T from le_sup_left) (generatedUnit hζ i).2
    · exact le_sup_right
  intro hdiv
  apply not_dvd_augmentedGenerated_index hζ
  rw [← Subgroup.relIndex_mul_index hle]
  exact dvd_mul_of_dvd_left hdiv _

/-- Real units that are also full-field torsion.  This is the kernel that
must be kept separate from the full cyclotomic torsion, which itself
contains 59-torsion. -/
def realTorsion :
    Subgroup (NumberField.IsCMField.realUnits K) :=
  (NumberField.Units.torsion K).comap
    (NumberField.IsCMField.realUnits K).subtype

/-- Quotient a real unit by the full cyclotomic torsion subgroup. -/
noncomputable def realToUnitLattice :
    NumberField.IsCMField.realUnits K →*
      ((𝓞 K)ˣ ⧸ NumberField.Units.torsion K) :=
  (QuotientGroup.mk' (NumberField.Units.torsion K)).comp
    (NumberField.IsCMField.realUnits K).subtype

private theorem realToUnitLattice_ker :
    (realToUnitLattice (K := K)).ker = realTorsion (K := K) := by
  ext u
  change
    QuotientGroup.mk' (NumberField.Units.torsion K)
      ((NumberField.IsCMField.realUnits K).subtype u) = 1 ↔
      (NumberField.IsCMField.realUnits K).subtype u ∈
        NumberField.Units.torsion K
  rw [← MonoidHom.mem_ker, QuotientGroup.ker_mk']

/-- Minus one as a real unit. -/
def negativeOneRealUnit :
    NumberField.IsCMField.realUnits K :=
  ⟨-1, by
    rw [← NumberField.IsCMField.unitsComplexConj_eq_self_iff]
    apply Units.ext
    simp [NumberField.IsCMField.unitsComplexConj,
      NumberField.IsCMField.ringOfIntegersComplexConj]⟩

/-- Minus one belongs to the real torsion kernel. -/
def negativeOneRealTorsion : realTorsion (K := K) :=
  ⟨negativeOneRealUnit (K := K), by
    exact neg_one_mem_torsion⟩

/-- A unit that is simultaneously real and torsion is `1` or `-1`.
This is the explicit two-primary kernel calculation. -/
private theorem real_torsion_unit_eq_one_or_neg_one
    (u : (𝓞 K)ˣ)
    (hreal : u ∈ NumberField.IsCMField.realUnits K)
    (htorsion : u ∈ NumberField.Units.torsion K) :
    u = 1 ∨ u = -1 := by
  have hself :
      NumberField.IsCMField.unitsComplexConj K u = u :=
    (NumberField.IsCMField.unitsComplexConj_eq_self_iff K u).mpr hreal
  have hinverse :
      NumberField.IsCMField.unitsComplexConj K u = u⁻¹ := by
    simpa using NumberField.IsCMField.unitsComplexConj_torsion
      (K := K) (⟨u, htorsion⟩ : NumberField.Units.torsion K)
  have huinv : u = u⁻¹ := hself.symm.trans hinverse
  have husq : u ^ 2 = 1 := by
    calc
      u ^ 2 = u * u := pow_two u
      _ = u⁻¹ * u := congrArg (fun v ↦ v * u) huinv
      _ = 1 := inv_mul_cancel u
  have hvalsq : (u : 𝓞 K) ^ 2 = 1 := by
    simpa using congrArg Units.val husq
  rcases (sq_eq_one_iff.mp hvalsq) with hone | hneg
  · exact Or.inl (Units.ext hone)
  · exact Or.inr (Units.ext hneg)

private theorem realTorsion_eq_one_or_negativeOne
    (u : realTorsion (K := K)) :
    u = 1 ∨ u = negativeOneRealTorsion (K := K) := by
  have htorsion :
      (u.1.1 : (𝓞 K)ˣ) ∈ NumberField.Units.torsion K := by
    exact u.2
  rcases real_torsion_unit_eq_one_or_neg_one
      (u.1.1 : (𝓞 K)ˣ)
      u.1.2 htorsion with hu | hu
  · left
    apply Subtype.ext
    apply Subtype.ext
    exact hu
  · right
    apply Subtype.ext
    apply Subtype.ext
    exact hu

private theorem negativeOneRealTorsion_ne_one :
    negativeOneRealTorsion (K := K) ≠ 1 := by
  intro h
  have hval := congrArg
    (fun u : realTorsion (K := K) ↦
      (((u.1.1 : (𝓞 K)ˣ) : 𝓞 K))) h
  exact (Ring.neg_one_ne_one_of_char_ne_two (R := 𝓞 K) (by norm_num))
    (by simpa [negativeOneRealTorsion, negativeOneRealUnit] using hval)

/-- The real torsion kernel has exactly two elements. -/
private theorem realTorsion_card :
    Nat.card (realTorsion (K := K)) = 2 := by
  let cover : Bool → realTorsion (K := K) :=
    fun b ↦ if b then negativeOneRealTorsion (K := K) else 1
  have hsurj : Function.Surjective cover := by
    intro u
    rcases realTorsion_eq_one_or_negativeOne u with hu | hu
    · exact ⟨false, by simpa [cover] using hu.symm⟩
    · exact ⟨true, by simpa [cover] using hu.symm⟩
  have hinj : Function.Injective cover := by
    intro a b hab
    cases a <;> cases b
    · rfl
    · exfalso
      exact negativeOneRealTorsion_ne_one (K := K) (by
        simpa [cover] using hab.symm)
    · exfalso
      exact negativeOneRealTorsion_ne_one (K := K) (by
        simpa [cover] using hab)
    · rfl
  calc
    Nat.card (realTorsion (K := K)) = Nat.card Bool :=
      (Nat.card_congr (Equiv.ofBijective cover ⟨hinj, hsurj⟩)).symm
    _ = 2 := by
      rw [Nat.card_eq_fintype_card]
      exact Fintype.card_bool

/-- Adjoining the real torsion kernel changes an index only by a divisor
of two. -/
private theorem realTorsion_indexFactor_dvd_two
    (H : Subgroup (NumberField.IsCMField.realUnits K)) :
    H.relIndex (H ⊔ realTorsion (K := K)) ∣ 2 := by
  have hcard :
      H.relIndex (H ⊔ realTorsion (K := K)) ∣
        Nat.card (realTorsion (K := K)) := by
    rw [sup_comm,
      Subgroup.relIndex_sup_right (realTorsion (K := K)) H]
    exact Subgroup.relIndex_dvd_card
      (G := NumberField.IsCMField.realUnits K)
      (H := H) (K := realTorsion (K := K))
  rwa [realTorsion_card (K := K)] at hcard

/-- Quotienting real units by real torsion identifies the matrix-controlled
relative index.  This is the exact subquotient step between the full-unit
lattice certificate and the requested real-unit index. -/
private theorem generated_with_realTorsion_index_eq_augmentedRelative :
    (generatedSubledger hζ ⊔ realTorsion (K := K)).index =
      (Subgroup.closure
          (Set.range fun i ↦ (generatedUnit hζ i : (𝓞 K)ˣ)) ⊔
        NumberField.Units.torsion K).relIndex
        (NumberField.IsCMField.realUnits K ⊔
          NumberField.Units.torsion K) := by
  let R := NumberField.IsCMField.realUnits K
  let T := NumberField.Units.torsion K
  let H : Subgroup R := generatedSubledger hζ
  let HU : Subgroup (𝓞 K)ˣ :=
    Subgroup.closure
      (Set.range fun i ↦ (generatedUnit hζ i : (𝓞 K)ˣ))
  let q : (𝓞 K)ˣ →* ((𝓞 K)ˣ ⧸ T) := QuotientGroup.mk' T
  let f : R →* ((𝓞 K)ˣ ⧸ T) := q.comp R.subtype
  have hfker : f.ker = realTorsion (K := K) := by
    exact realToUnitLattice_ker (K := K)
  have hHmap : H.map f = HU.map q := by
    change H.map (q.comp R.subtype) = HU.map q
    rw [← Subgroup.map_map]
    have hmap :
        H.map R.subtype = HU := by
      exact generatedSubledger_map_realUnitsSubtype hζ
    rw [hmap]
  have htopmap : (⊤ : Subgroup R).map f = R.map q := by
    change (⊤ : Subgroup R).map (q.comp R.subtype) = R.map q
    rw [← Subgroup.map_map]
    have htop : (⊤ : Subgroup R).map R.subtype = R := by
      ext u
      simp
    rw [htop]
  have hrealQuotient :
      (H.map f).relIndex ((⊤ : Subgroup R).map f) =
        (H ⊔ realTorsion (K := K)).index := by
    rw [Subgroup.relIndex_map_map, hfker]
    simp
  have hfullQuotient :
      (HU.map q).relIndex (R.map q) =
        (HU ⊔ T).relIndex (R ⊔ T) := by
    have hq := Subgroup.relIndex_map_map q HU R
    rw [show q.ker = T by exact QuotientGroup.ker_mk' T] at hq
    exact hq
  calc
    (generatedSubledger hζ ⊔ realTorsion (K := K)).index =
        (H.map f).relIndex ((⊤ : Subgroup R).map f) :=
      hrealQuotient.symm
    _ = (HU.map q).relIndex (R.map q) := by
      rw [hHmap, htopmap]
    _ = (HU ⊔ T).relIndex (R ⊔ T) := hfullQuotient

/-- The actual generated real-unit subgroup has index prime to 59.  The
proof factors its index into the matrix-controlled quotient and the
explicit two-primary real-torsion kernel. -/
private theorem not_dvd_generatedSubledger_index :
    ¬59 ∣ (generatedSubledger hζ).index := by
  let H := generatedSubledger hζ
  let RT := realTorsion (K := K)
  have hquotient : ¬59 ∣ (H ⊔ RT).index := by
    rw [generated_with_realTorsion_index_eq_augmentedRelative hζ]
    exact not_dvd_augmentedGenerated_realRelativeIndex hζ
  have hkernel : H.relIndex (H ⊔ RT) ∣ 2 :=
    realTorsion_indexFactor_dvd_two H
  intro hdiv
  have hproduct :
      59 ∣ H.relIndex (H ⊔ RT) * (H ⊔ RT).index := by
    rw [Subgroup.relIndex_mul_index le_sup_left]
    exact hdiv
  rcases (Nat.Prime.dvd_mul (by norm_num : Nat.Prime 59)).mp hproduct with
    hleft | hright
  · exact (by norm_num : ¬59 ∣ 2) (dvd_trans hleft hkernel)
  · exact hquotient hright

/-- **C2 at conductor 59.** The generated edge sub-ledger has finite index
in the full real-unit ledger, and its capacity is prime to 59. -/
theorem capacityCertificate (hζ : IsPrimitiveRoot ζ 59) :
    CapacityCertificateGoal hζ := by
  have hnot : ¬59 ∣ (generatedSubledger hζ).index :=
    not_dvd_generatedSubledger_index hζ
  have hfinite : (generatedSubledger hζ).FiniteIndex := by
    rw [Subgroup.finiteIndex_iff]
    intro hzero
    apply hnot
    rw [hzero]
    exact dvd_zero 59
  refine ⟨hfinite, ?_⟩
  rw [capacityIndex_eq_relIndex]
  exact hnot

end

end Fermat.FiftyNine.Conservation.CapacityCertificate
