/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, Codex

# Historical equation-(8) route verification at exponent 59

This executable audit leaf verifies the route from the allocated Fermat
state through Takagi--Furtwängler relation (7a), literal equation (8), the
genuine unit and ideal-class character actions, and Vandiver's historical
support descent.  It is deliberately a sibling of `Verification.lean`:
the historical endpoint intentionally imports Case I and the older
Vandiver continuation, whereas the structural conservation audit has a
broader import-refusal cone.

Besides checking the complete public surface of the nine new modules, the
leaf audits axioms and unsplit public types namespace-wide.  Positive proof
dependency guards record the intended composition spine.  Negative guards
make the crucial distinction between reusing the uniform historical
continuation and bypassing the newly constructed equation-(8) prefix with
an older monolithic endpoint.
-/
import Fermat.Conservation.GuardDependsOn
import Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59
import Fermat.FiftyNine.Conservation.FermatStateEquationEight59
import Fermat.FiftyNine.Conservation.FermatStateSelmerUnitLifts59
import Fermat.FiftyNine.Conservation.FermatStatePrimalUnitProjection59
import Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59
import Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59
import Fermat.FiftyNine.Conservation.FermatFactorClassProjection59
import Fermat.FiftyNine.Conservation.FermatStateUnitClassKernel59
import Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59

open Lean Elab Command

/-- Audit every declaration under a selected implementation namespace
against Lean's standard extensionality, choice, and quotient boundary. -/
elab "#guard_standard_axioms_prefix " p:ident : command => do
  let env ← getEnv
  let auditedPrefix := p.getId
  let allowed : Array Name :=
    #[``propext, ``Classical.choice, ``Quot.sound]
  let declarations :=
    env.constants.toList
      |>.map Prod.fst
      |>.filter auditedPrefix.isPrefixOf
  for declaration in declarations do
    let axioms ← Lean.collectAxioms declaration
    let unexpected := axioms.filter fun ax => !allowed.contains ax
    unless unexpected.isEmpty do
      throwError
        "{declaration} depends on nonstandard axioms: {unexpected}"

/-! ## Complete public inventory -/

#check Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59.normalizedPlus_conjugatePair_isKummerPrimary59
#check Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59.exists_takagiSevenAGenerator
#check Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59.vandiverSevenA_takagi
#check Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59.rootClasses_eq_zero_takagi
#check Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59.factorPrincipalizationPermit_takagi

#check Fermat.FiftyNine.Conservation.FermatStateEquationEight59.exists_normalizedPlusFactor_equationEight59
#check Fermat.FiftyNine.Conservation.FermatStateEquationEight59.exists_normalizedMinusFactor_equationEight59
#check Fermat.FiftyNine.Conservation.FermatStateEquationEight59.exists_normalizedFactor_equationEightPair59

#check Fermat.FiftyNine.Conservation.FermatStateSelmerUnitLifts59.fermatPlusStrictSelmer59_mem_unitRange_takagi
#check Fermat.FiftyNine.Conservation.FermatStateSelmerUnitLifts59.fermatMinusStrictSelmer59_mem_unitRange_takagi
#check Fermat.FiftyNine.Conservation.FermatStateSelmerUnitLifts59.fermatFactorSelmerDifference59_mem_unitRange_takagi
#check Fermat.FiftyNine.Conservation.FermatStateSelmerUnitLifts59.exists_unitLift_fermatPlusStrictSelmer59
#check Fermat.FiftyNine.Conservation.FermatStateSelmerUnitLifts59.exists_unitLift_fermatMinusStrictSelmer59
#check Fermat.FiftyNine.Conservation.FermatStateSelmerUnitLifts59.exists_explicitUnitLift_fermatPlusStrictSelmer59
#check Fermat.FiftyNine.Conservation.FermatStateSelmerUnitLifts59.exists_explicitUnitLift_fermatMinusStrictSelmer59
#check Fermat.FiftyNine.Conservation.FermatStateSelmerUnitLifts59.exists_explicitUnitLift_fermatFactorPair59

#check Fermat.FiftyNine.Conservation.FermatStatePrimalUnitProjection59.exists_explicitUnitProjection_fermatPlusPrimalMode59
#check Fermat.FiftyNine.Conservation.FermatStatePrimalUnitProjection59.exists_explicitUnitProjection_fermatMinusPrimalMode59
#check Fermat.FiftyNine.Conservation.FermatStatePrimalUnitProjection59.exists_explicitUnitProjection_fermatFactorPair59

#check Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.cyclotomicRingUnitMulEquiv59
#check Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.cyclotomicRingUnitMulEquiv59_powRange
#check Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.cyclotomicUnitModPMulEquiv59
#check Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.cyclotomicUnitModPMulEquiv59_mk
#check Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.cyclotomicUnitModPAddEquiv59
#check Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.cyclotomicUnitModPAddEquiv59_one_apply
#check Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.cyclotomicUnitModPAddEquiv59_mul_apply
#check Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.unitModP59_nsmul_eq_zero
#check Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.cyclotomicUnitModPAddHom59
#check Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.cyclotomicUnitModPLinearMap59
#check Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.cyclotomicUnitModPRepresentation59
#check Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.cyclotomicRingUnitMulEquiv59_map_algebraMap
#check Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.unitInclusion_cyclotomicUnitModPAddEquiv59
#check Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.unitInclusionLinearMap59
#check Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.unitInclusionIntertwiner59
#check Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.cyclotomicUnitProjector59
#check Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.unitInclusionLinearMap59_characterProjector
#check Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.exists_cyclotomicTransport_explicitUnitLift_fermatPlusStrictSelmer59
#check Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.exists_cyclotomicTransport_explicitUnitLift_fermatMinusStrictSelmer59
#check Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.exists_explicitUnitProjector_fermatPlusPrimalMode59
#check Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.exists_explicitUnitProjector_fermatMinusPrimalMode59

#check Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.cyclotomicFractionalIdealEquiv59
#check Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.cyclotomicFractionalIdealUnitMulEquiv59
#check Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.cyclotomicClassGroupMulEquiv59
#check Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.cyclotomicClassGroupMulEquiv59_mk
#check Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.cyclotomicClassGroupMulEquiv59_one_apply
#check Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.cyclotomicClassGroupMulEquiv59_mul_apply
#check Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.cyclotomicAdditiveClassGroupRepresentation59
#check Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.cyclotomicFractionEquiv59_eq
#check Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.cyclotomicFractionalIdealEquiv59_toPrincipalIdeal
#check Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.strictSelmerIdealClass59_cyclotomic
#check Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.ClassTorsion59
#check Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.cyclotomicClassTorsionAddHom59
#check Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.cyclotomicClassTorsionLinearMap59
#check Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.cyclotomicClassTorsionRepresentation59
#check Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.strictSelmerClassLinearMap59
#check Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.strictSelmerClassLinearMap59_value
#check Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.strictSelmerClassIntertwiner59
#check Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.cyclotomicClassProjector59
#check Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.strictSelmerClassLinearMap59_characterProjector
#check Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.fermatPlusPrimalMode59_classProjection
#check Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.fermatMinusPrimalMode59_classProjection

#check Fermat.FiftyNine.Conservation.FermatFactorClassProjection59.allocatedRootClassPTorsion_one_projection_eq_neg_zero
#check Fermat.FiftyNine.Conservation.FermatFactorClassProjection59.allocatedRootClassPTorsion_difference_projection
#check Fermat.FiftyNine.Conservation.FermatFactorClassProjection59.fermatFactorSelmerDifference59_projected_class
#check Fermat.FiftyNine.Conservation.FermatFactorClassProjection59.fermatFactorSelmerDifference59_projected_class_eq_two_smul
#check Fermat.FiftyNine.Conservation.FermatFactorClassProjection59.allocatedRootClassPTorsion_zero_eq_zero_takagi
#check Fermat.FiftyNine.Conservation.FermatFactorClassProjection59.allocatedRootClassPTorsion_one_eq_zero_takagi
#check Fermat.FiftyNine.Conservation.FermatFactorClassProjection59.fermatPlusPrimalMode59_classProjection_eq_zero_takagi
#check Fermat.FiftyNine.Conservation.FermatFactorClassProjection59.fermatMinusPrimalMode59_classProjection_eq_zero_takagi
#check Fermat.FiftyNine.Conservation.FermatFactorClassProjection59.fermatFactorSelmerDifference59_projected_class_eq_zero_takagi

#check Fermat.FiftyNine.Conservation.FermatStateUnitClassKernel59.exists_explicitProjectedUnitLift_classSilent_fermatPlus59
#check Fermat.FiftyNine.Conservation.FermatStateUnitClassKernel59.exists_explicitProjectedUnitLift_classSilent_fermatMinus59
#check Fermat.FiftyNine.Conservation.FermatStateUnitClassKernel59.exists_explicitProjectedUnitDifference_classSilent59

#check Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.historicalZetaFactor_eq_normalizedPlusFactor59
#check Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_historicalEquationEightPair_of_state59
#check Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_preparedEquationEightPair_one_of_state59
#check Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_preparedEquationEightPair_one_of_state_unconditional59
#check Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_initialHistoricalPreparedEquationEightPair_one59
#check Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_preparedEquationEightPair_two_of_state_unconditional59
#check Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_conjugationPowerReductionData_of_preparedPairs59
#check Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_initialHistoricalPreparedEquationEightPairs59
#check Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_initialHistoricalReductionData59
#check Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_initialHistoricalStrictSuccessor59
#check Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.false_of_stateLinkedIdealPair_historicalDescent59
#check Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.not_exists_orientedPrimitiveSecondCaseSolution59
#check Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.no_primitiveSecondCaseSolution59
#check Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.secondCaseExcluded_fiftyNine_via_stateEquationEight
#check Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.holdsAt_fiftyNine_via_stateEquationEight

/-! ## Representative kernel-axiom readout -/

#print axioms Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59.normalizedPlus_conjugatePair_isKummerPrimary59
#print axioms Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59.rootClasses_eq_zero_takagi
#print axioms Fermat.FiftyNine.Conservation.FermatStateEquationEight59.exists_normalizedFactor_equationEightPair59
#print axioms Fermat.FiftyNine.Conservation.FermatStateSelmerUnitLifts59.exists_explicitUnitLift_fermatFactorPair59
#print axioms Fermat.FiftyNine.Conservation.FermatStatePrimalUnitProjection59.exists_explicitUnitProjection_fermatFactorPair59
#print axioms Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.unitInclusionLinearMap59_characterProjector
#print axioms Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.cyclotomicClassGroupMulEquiv59_mk
#print axioms Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.strictSelmerIdealClass59_cyclotomic
#print axioms Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.strictSelmerClassLinearMap59_characterProjector
#print axioms Fermat.FiftyNine.Conservation.FermatFactorClassProjection59.fermatFactorSelmerDifference59_projected_class_eq_zero_takagi
#print axioms Fermat.FiftyNine.Conservation.FermatStateUnitClassKernel59.exists_explicitProjectedUnitLift_classSilent_fermatPlus59
#print axioms Fermat.FiftyNine.Conservation.FermatStateUnitClassKernel59.exists_explicitProjectedUnitLift_classSilent_fermatMinus59
#print axioms Fermat.FiftyNine.Conservation.FermatStateUnitClassKernel59.exists_explicitProjectedUnitDifference_classSilent59
#print axioms Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_historicalEquationEightPair_of_state59
#print axioms Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_initialHistoricalReductionData59
#print axioms Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_initialHistoricalStrictSuccessor59
#print axioms Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.false_of_stateLinkedIdealPair_historicalDescent59
#print axioms Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.secondCaseExcluded_fiftyNine_via_stateEquationEight
#print axioms Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.holdsAt_fiftyNine_via_stateEquationEight

/-! ## Exhaustive namespace invariants -/

#guard_standard_axioms_prefix Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59
#guard_standard_axioms_prefix Fermat.FiftyNine.Conservation.FermatStateEquationEight59
#guard_standard_axioms_prefix Fermat.FiftyNine.Conservation.FermatStateSelmerUnitLifts59
#guard_standard_axioms_prefix Fermat.FiftyNine.Conservation.FermatStatePrimalUnitProjection59
#guard_standard_axioms_prefix Fermat.Conservation.PrimeCyclotomicUnitSelmerNaturality
#guard_standard_axioms_prefix Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59
#guard_standard_axioms_prefix Fermat.Conservation.PrimeCyclotomicSelmerClassNaturality
#guard_standard_axioms_prefix Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59
#guard_standard_axioms_prefix Fermat.FiftyNine.Conservation.FermatFactorClassProjection59
#guard_standard_axioms_prefix Fermat.FiftyNine.Conservation.FermatStateUnitClassKernel59
#guard_standard_axioms_prefix Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59

#audit_no_product_equiv_types_prefix Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59
#audit_no_product_equiv_types_prefix Fermat.FiftyNine.Conservation.FermatStateEquationEight59
#audit_no_product_equiv_types_prefix Fermat.FiftyNine.Conservation.FermatStateSelmerUnitLifts59
#audit_no_product_equiv_types_prefix Fermat.FiftyNine.Conservation.FermatStatePrimalUnitProjection59
#audit_no_product_equiv_types_prefix Fermat.Conservation.PrimeCyclotomicUnitSelmerNaturality
#audit_no_product_equiv_types_prefix Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59
#audit_no_product_equiv_types_prefix Fermat.Conservation.PrimeCyclotomicSelmerClassNaturality
#audit_no_product_equiv_types_prefix Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59
#audit_no_product_equiv_types_prefix Fermat.FiftyNine.Conservation.FermatFactorClassProjection59
#audit_no_product_equiv_types_prefix Fermat.FiftyNine.Conservation.FermatStateUnitClassKernel59
#audit_no_product_equiv_types_prefix Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59

/-! ## Intended positive composition spine -/

#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59.exists_takagiSevenAGenerator,
  Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59.normalizedPlus_conjugatePair_isKummerPrimary59
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59.vandiverSevenA_takagi,
  Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59.exists_takagiSevenAGenerator
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59.rootClasses_eq_zero_takagi,
  Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59.vandiverSevenA_takagi
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59.rootClasses_eq_zero_takagi,
  Fermat.FiftyNine.Conservation.StateFactorConjugation.StateLinkedIdealPair.vandiverSevenD
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59.factorPrincipalizationPermit_takagi,
  Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59.vandiverSevenA_takagi

#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateEquationEight59.exists_normalizedPlusFactor_equationEight59,
  Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59.rootClasses_eq_zero_takagi
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateEquationEight59.exists_normalizedMinusFactor_equationEight59,
  Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59.rootClasses_eq_zero_takagi
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateEquationEight59.exists_normalizedFactor_equationEightPair59,
  Fermat.FiftyNine.Conservation.FermatStateEquationEight59.exists_normalizedPlusFactor_equationEight59
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateEquationEight59.exists_normalizedFactor_equationEightPair59,
  Fermat.FiftyNine.Conservation.FermatStateEquationEight59.exists_normalizedMinusFactor_equationEight59

#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateSelmerUnitLifts59.fermatPlusStrictSelmer59_mem_unitRange_takagi,
  Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59.rootClasses_eq_zero_takagi
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateSelmerUnitLifts59.fermatMinusStrictSelmer59_mem_unitRange_takagi,
  Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59.rootClasses_eq_zero_takagi
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateSelmerUnitLifts59.fermatFactorSelmerDifference59_mem_unitRange_takagi,
  Fermat.FiftyNine.Conservation.FermatStateTakagiSevenA59.vandiverSevenA_takagi
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateSelmerUnitLifts59.exists_explicitUnitLift_fermatPlusStrictSelmer59,
  Fermat.FiftyNine.Conservation.FermatStateEquationEight59.exists_normalizedPlusFactor_equationEight59
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateSelmerUnitLifts59.exists_explicitUnitLift_fermatMinusStrictSelmer59,
  Fermat.FiftyNine.Conservation.FermatStateEquationEight59.exists_normalizedMinusFactor_equationEight59
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStatePrimalUnitProjection59.exists_explicitUnitProjection_fermatPlusPrimalMode59,
  Fermat.FiftyNine.Conservation.FermatStateSelmerUnitLifts59.exists_explicitUnitLift_fermatPlusStrictSelmer59
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStatePrimalUnitProjection59.exists_explicitUnitProjection_fermatMinusPrimalMode59,
  Fermat.FiftyNine.Conservation.FermatStateSelmerUnitLifts59.exists_explicitUnitLift_fermatMinusStrictSelmer59

#guard_depends_on
  Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.unitInclusion_cyclotomicUnitModPAddEquiv59,
  Fermat.Conservation.PrimeCyclotomicUnitSelmerNaturality.unitInclusion_cyclotomicUnitModPAddEquiv
#guard_depends_on
  Fermat.Conservation.PrimeCyclotomicUnitSelmerNaturality.unitInclusion_cyclotomicUnitModPAddEquiv,
  Fermat.Conservation.PrimeCyclotomicUnitSelmerNaturality.cyclotomicRingUnitMulEquiv_map_algebraMap
#guard_depends_on
  Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.unitInclusionIntertwiner59,
  Fermat.Conservation.PrimeCyclotomicUnitSelmerNaturality.unitInclusionIntertwiner
#guard_depends_on
  Fermat.Conservation.PrimeCyclotomicUnitSelmerNaturality.unitInclusionIntertwiner,
  Fermat.Conservation.PrimeCyclotomicUnitSelmerNaturality.unitInclusion_cyclotomicUnitModPAddEquiv
#guard_depends_on
  Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.unitInclusionLinearMap59_characterProjector,
  Fermat.Conservation.PrimeCyclotomicUnitSelmerNaturality.unitInclusionLinearMap_characterProjector
#guard_depends_on
  Fermat.Conservation.PrimeCyclotomicUnitSelmerNaturality.unitInclusionLinearMap_characterProjector,
  Fermat.Conservation.PrimeCyclotomicUnitSelmerNaturality.unitInclusionIntertwiner
#guard_depends_on
  Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.exists_explicitUnitProjector_fermatPlusPrimalMode59,
  Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.unitInclusionLinearMap59_characterProjector
#guard_depends_on
  Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.exists_explicitUnitProjector_fermatMinusPrimalMode59,
  Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.unitInclusionLinearMap59_characterProjector

#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatFactorSelmerSource59.strictSelmerIdealClass59,
  Fermat.Conservation.PrimeCyclotomicSelmerClassNaturality.strictSelmerIdealClass
#guard_depends_on
  Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.cyclotomicClassGroupMulEquiv59_mk,
  Fermat.Conservation.PrimeCyclotomicSelmerClassNaturality.cyclotomicClassGroupMulEquiv_mk
#guard_depends_on
  Fermat.Conservation.PrimeCyclotomicSelmerClassNaturality.cyclotomicClassGroupMulEquiv_mk,
  ClassGroup.mk_canonicalEquiv
#guard_depends_on
  Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.cyclotomicFractionalIdealEquiv59_toPrincipalIdeal,
  Fermat.Conservation.PrimeCyclotomicSelmerClassNaturality.cyclotomicFractionalIdealEquiv_toPrincipalIdeal
#guard_depends_on
  Fermat.Conservation.PrimeCyclotomicSelmerClassNaturality.cyclotomicFractionalIdealEquiv_toPrincipalIdeal,
  Fermat.Conservation.PrimeCyclotomicSelmerClassNaturality.cyclotomicFractionEquiv_eq
#guard_depends_on
  Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.strictSelmerIdealClass59_cyclotomic,
  Fermat.Conservation.PrimeCyclotomicSelmerClassNaturality.strictSelmerIdealClass_cyclotomic
#guard_depends_on
  Fermat.Conservation.PrimeCyclotomicSelmerClassNaturality.strictSelmerIdealClass_cyclotomic,
  Fermat.Conservation.PrimeCyclotomicSelmerClassNaturality.cyclotomicClassGroupMulEquiv_mk
#guard_depends_on
  Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.strictSelmerClassIntertwiner59,
  Fermat.Conservation.PrimeCyclotomicSelmerClassNaturality.strictSelmerClassIntertwiner
#guard_depends_on
  Fermat.Conservation.PrimeCyclotomicSelmerClassNaturality.strictSelmerClassIntertwiner,
  Fermat.Conservation.PrimeCyclotomicSelmerClassNaturality.strictSelmerIdealClass_cyclotomic
#guard_depends_on
  Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.strictSelmerClassLinearMap59_characterProjector,
  Fermat.Conservation.PrimeCyclotomicSelmerClassNaturality.strictSelmerClassLinearMap_characterProjector
#guard_depends_on
  Fermat.Conservation.PrimeCyclotomicSelmerClassNaturality.strictSelmerClassLinearMap_characterProjector,
  Fermat.Conservation.PrimeCyclotomicSelmerClassNaturality.strictSelmerClassIntertwiner
#guard_depends_on
  Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.fermatPlusPrimalMode59_classProjection,
  Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.strictSelmerClassLinearMap59_characterProjector
#guard_depends_on
  Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.fermatMinusPrimalMode59_classProjection,
  Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.strictSelmerClassLinearMap59_characterProjector

#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatFactorClassProjection59.allocatedRootClassPTorsion_one_projection_eq_neg_zero,
  Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.fermatMinusPrimalMode59_classProjection
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatFactorClassProjection59.allocatedRootClassPTorsion_difference_projection,
  Fermat.FiftyNine.Conservation.FermatFactorClassProjection59.allocatedRootClassPTorsion_one_projection_eq_neg_zero
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatFactorClassProjection59.fermatFactorSelmerDifference59_projected_class,
  Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.strictSelmerClassLinearMap59_characterProjector
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatFactorClassProjection59.fermatFactorSelmerDifference59_projected_class_eq_zero_takagi,
  Fermat.FiftyNine.Conservation.FermatFactorClassProjection59.fermatFactorSelmerDifference59_projected_class_eq_two_smul
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatFactorClassProjection59.fermatFactorSelmerDifference59_projected_class_eq_zero_takagi,
  Fermat.FiftyNine.Conservation.FermatFactorClassProjection59.allocatedRootClassPTorsion_zero_eq_zero_takagi

#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateUnitClassKernel59.exists_explicitProjectedUnitLift_classSilent_fermatPlus59,
  Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.exists_explicitUnitProjector_fermatPlusPrimalMode59
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateUnitClassKernel59.exists_explicitProjectedUnitLift_classSilent_fermatPlus59,
  Fermat.FiftyNine.Conservation.FermatFactorClassProjection59.fermatPlusPrimalMode59_classProjection_eq_zero_takagi
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateUnitClassKernel59.exists_explicitProjectedUnitLift_classSilent_fermatMinus59,
  Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.exists_explicitUnitProjector_fermatMinusPrimalMode59
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateUnitClassKernel59.exists_explicitProjectedUnitLift_classSilent_fermatMinus59,
  Fermat.FiftyNine.Conservation.FermatFactorClassProjection59.fermatMinusPrimalMode59_classProjection_eq_zero_takagi
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateUnitClassKernel59.exists_explicitProjectedUnitDifference_classSilent59,
  Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.exists_explicitUnitProjector_fermatPlusPrimalMode59
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateUnitClassKernel59.exists_explicitProjectedUnitDifference_classSilent59,
  Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.exists_explicitUnitProjector_fermatMinusPrimalMode59
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateUnitClassKernel59.exists_explicitProjectedUnitDifference_classSilent59,
  Fermat.FiftyNine.Conservation.NormalizationCorrectionProjection59.fermatMinusPrimalMode59_eq_neg_plus
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateUnitClassKernel59.exists_explicitProjectedUnitDifference_classSilent59,
  Fermat.FiftyNine.Conservation.FermatFactorClassProjection59.fermatFactorSelmerDifference59_projected_class_eq_zero_takagi

#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_historicalEquationEightPair_of_state59,
  Fermat.FiftyNine.Conservation.FermatStateEquationEight59.exists_normalizedPlusFactor_equationEight59
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_preparedEquationEightPair_one_of_state59,
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_historicalEquationEightPair_of_state59
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_preparedEquationEightPair_one_of_state_unconditional59,
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_preparedEquationEightPair_one_of_state59
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_initialHistoricalPreparedEquationEightPair_one59,
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_preparedEquationEightPair_one_of_state_unconditional59
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_preparedEquationEightPair_two_of_state_unconditional59,
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_preparedEquationEightPair_one_of_state_unconditional59
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_initialHistoricalPreparedEquationEightPairs59,
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_preparedEquationEightPair_two_of_state_unconditional59
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_initialHistoricalReductionData59,
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_conjugationPowerReductionData_of_preparedPairs59
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_initialHistoricalStrictSuccessor59,
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_initialHistoricalReductionData59
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_initialHistoricalStrictSuccessor59,
  Fermat.FiftyNine.VandiverLemmaTwo.vandiverLemmaTwo_fiftyNine
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.false_of_stateLinkedIdealPair_historicalDescent59,
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_initialHistoricalStrictSuccessor59
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.false_of_stateLinkedIdealPair_historicalDescent59,
  Fermat.FiftyNine.VandiverHistorical.realPrincipalGeneratorElimination59
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.false_of_stateLinkedIdealPair_historicalDescent59,
  Fermat.Irregular.VandiverHistoricalDescent.no_historicalState
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.not_exists_orientedPrimitiveSecondCaseSolution59,
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.false_of_stateLinkedIdealPair_historicalDescent59
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.no_primitiveSecondCaseSolution59,
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.not_exists_orientedPrimitiveSecondCaseSolution59
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.secondCaseExcluded_fiftyNine_via_stateEquationEight,
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.no_primitiveSecondCaseSolution59
#guard_depends_on
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.holdsAt_fiftyNine_via_stateEquationEight,
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.secondCaseExcluded_fiftyNine_via_stateEquationEight

/-! ## Route-separation guards -/

#guard_not_depends_on
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_historicalEquationEightPair_of_state59,
  Fermat.FiftyNine.VandiverHistorical.exists_historicalEquationEight59
#guard_not_depends_on
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_preparedEquationEightPair_one_of_state_unconditional59,
  Fermat.FiftyNine.VandiverHistorical.exists_preparedEquationEightPair_one59
#guard_not_depends_on
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_preparedEquationEightPair_two_of_state_unconditional59,
  Fermat.FiftyNine.VandiverHistorical.exists_preparedEquationEightPair_two59
#guard_not_depends_on
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.exists_initialHistoricalReductionData59,
  Fermat.FiftyNine.VandiverHistorical.realPrincipalGeneratorElimination59
#guard_not_depends_on
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.secondCaseExcluded_fiftyNine_via_stateEquationEight,
  Fermat.FiftyNine.secondCaseExcluded_fiftyNine
#guard_not_depends_on
  Fermat.FiftyNine.Conservation.FermatStateHistoricalDescent59.holdsAt_fiftyNine_via_stateEquationEight,
  Fermat.FiftyNine.holdsAt_fiftyNine

#guard_not_depends_on
  Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.unitInclusion_cyclotomicUnitModPAddEquiv59,
  Fermat.FiftyNine.Conservation.FermatStatePrimalUnitProjection59.exists_explicitUnitProjection_fermatPlusPrimalMode59
#guard_not_depends_on
  Fermat.FiftyNine.Conservation.CyclotomicUnitSelmerNaturality59.unitInclusionLinearMap59_characterProjector,
  Fermat.FiftyNine.Conservation.FermatStatePrimalUnitProjection59.exists_explicitUnitProjection_fermatMinusPrimalMode59
#guard_not_depends_on
  Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.strictSelmerIdealClass59_cyclotomic,
  Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.fermatPlusPrimalMode59_classProjection
#guard_not_depends_on
  Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.strictSelmerClassLinearMap59_characterProjector,
  Fermat.FiftyNine.Conservation.CyclotomicSelmerClassNaturality59.fermatMinusPrimalMode59_classProjection
