/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, Codex

# The split-prime Fourier fiber at 827

Provenance: Fabian observed that the old Boolean steering branch is the
lossy shadow of a relative orientation.  At the auxiliary prime 827 the
position coordinates are the 58 places in one regular Galois orbit, while
the character coordinates are their Fourier modes.

This file proves the cyclotomic splitting count and specializes the
prime-generic residue-field Fourier dictionary at `p = 59`.  A positional
delta has a nonzero coefficient in every frequency, while a nonzero
pure-character vector is nonzero at every position.  Consequently a
pure-character localization vector cannot be silent at 57 places and
nonzero at the selected place.

The current q-relaxed representation is supplied abstractly and has no
compiled compatibility with the arithmetic permutation of places.
`QLocalizationEquivariance827` names exactly that missing contragredient
seating law.  Fourier proves `FixedAttention` from this law, but this file
does not invent an inhabitant and therefore does not change the unconditional
branch verdict.

No Selmer splitting, section, endpoint, relation (7a), or transformer is
constructed.
-/
import Fermat.Conservation.PrimeResidueFourier
import Fermat.FiftyNine.Conservation.GaugeSteering827
import Mathlib.NumberTheory.NumberField.Cyclotomic.Galois

open scoped BigOperators nonZeroDivisors NumberField
open Module

noncomputable section

namespace Fermat.FiftyNine.Conservation.SplitPrimeFourier827

open Fermat.Conservation
open Fermat.Conservation.SelmerEigenspace
open Fermat.Conservation.SteeringFiber
open Fermat.FiftyNine.Conservation.DetectorWitness827
open Fermat.FiftyNine.Conservation.GaugeSteering827

local instance : Fact (Nat.Prime 59) := ⟨by norm_num⟩
local instance : Fact (Nat.Prime Credit.attestationPrime) :=
  ⟨Credit.attestationPrime_isPrime⟩

/-! ## The arithmetic 58-place orbit -/

/-- The rational prime ideal generated by the attestation prime 827. -/
def rationalPrimeIdeal827 : Ideal ℤ :=
  Ideal.span ({(Credit.attestationPrime : ℤ)} : Set ℤ)

/-- The generated attestation prime is `1` modulo the conductor 59. -/
theorem attestationPrime_mod_fiftyNine :
    Credit.attestationPrime % 59 = 1 := by
  norm_num [Credit.attestationPrime]

theorem rationalPrimeIdeal827_ne_bot : rationalPrimeIdeal827 ≠ ⊥ := by
  simp [rationalPrimeIdeal827, Credit.attestationPrime]

theorem rationalPrimeIdeal827_isMaximal : rationalPrimeIdeal827.IsMaximal := by
  rw [rationalPrimeIdeal827]
  exact
    ((Ideal.span_singleton_prime
      (by norm_num [Credit.attestationPrime] :
        (Credit.attestationPrime : ℤ) ≠ 0)).mpr
      (by norm_num [Credit.attestationPrime] :
        Prime (Credit.attestationPrime : ℤ))).isMaximal
      (by norm_num [Credit.attestationPrime])

theorem attestationPrime_not_dvd_fiftyNine :
    ¬ Credit.attestationPrime ∣ 59 := by
  norm_num [Credit.attestationPrime]

/-- The Frobenius residue at 827 is the identity in `(ZMod 59)ˣ`. -/
theorem orderOf_attestationPrime_zmod59 :
    orderOf (Credit.attestationPrime : ZMod 59) = 1 := by
  have h : (Credit.attestationPrime : ZMod 59) = 1 := by
    decide +kernel +revert
  rw [h, orderOf_one]

universe uK

variable (K : Type uK) [Field K] [NumberField K]
  [IsCyclotomicExtension {59} ℚ K]

/-- The Galois group of the 59th cyclotomic field has 58 elements. -/
theorem gal_ncard_eq_fiftyEight : Nat.card Gal(K/ℚ) = 58 := by
  calc
    Nat.card Gal(K/ℚ) = Nat.card (ZMod 59)ˣ :=
      Nat.card_congr
        (IsCyclotomicExtension.Rat.galEquivZMod 59 K).toEquiv
    _ = 58 := by
      simp only [Nat.card_eq_fintype_card, Fintype.card_units]
      decide +kernel +revert

/-- Since 827 is unramified and has Frobenius order one, it has exactly 58
primes in the 59th cyclotomic field. -/
theorem primesOver827_ncard_eq_fiftyEight :
    (rationalPrimeIdeal827.primesOver (𝓞 K)).ncard = 58 := by
  letI : rationalPrimeIdeal827.IsMaximal :=
    rationalPrimeIdeal827_isMaximal
  letI : IsGalois ℚ K := IsCyclotomicExtension.isGalois {59} ℚ K
  letI : MulSemiringAction Gal(K/ℚ) (𝓞 K) :=
    IsIntegralClosure.MulSemiringAction ℤ ℚ K (𝓞 K)
  haveI : IsGaloisGroup Gal(K/ℚ) ℤ (𝓞 K) :=
    IsGaloisGroup.of_isFractionRing Gal(K/ℚ) ℤ (𝓞 K) ℚ K
  have h := Ideal.ncard_primesOver_mul_ramificationIdxIn_mul_inertiaDegIn
    (G := Gal(K/ℚ)) rationalPrimeIdeal827_ne_bot (𝓞 K)
  unfold rationalPrimeIdeal827 at h
  rw [IsCyclotomicExtension.Rat.ramificationIdxIn_eq_of_not_dvd
        Credit.attestationPrime K attestationPrime_not_dvd_fiftyNine,
      IsCyclotomicExtension.Rat.inertiaDegIn_eq_of_not_dvd
        Credit.attestationPrime K attestationPrime_not_dvd_fiftyNine,
      orderOf_attestationPrime_zmod59, mul_one, mul_one] at h
  unfold rationalPrimeIdeal827
  rw [h]
  exact gal_ncard_eq_fiftyEight K

/-- The existing height-one-place support subtype. -/
abbrev Place827 := {v // v ∈ placesOver827 K}

/-- The repository's height-one-place spelling is equivalent to Mathlib's
literal set of primes over the ideal `(827)`. -/
noncomputable def placeEquivPrimesOver827 :
    Place827 K ≃ rationalPrimeIdeal827.primesOver (𝓞 K) where
  toFun v := ⟨v.1.asIdeal, v.1.isPrime, ⟨v.2⟩⟩
  invFun P :=
    ⟨{
      asIdeal := P.1
      isPrime := P.2.1
      ne_bot := Ideal.ne_bot_of_mem_primesOver
        rationalPrimeIdeal827_ne_bot P.2
    }, P.2.2.over⟩
  left_inv v := by
    apply Subtype.ext
    exact IsDedekindDomain.HeightOneSpectrum.ext_iff.mpr rfl
  right_inv P := by
    apply Subtype.ext
    rfl

/-- Thus the actual support set `placesOver827` has cardinal 58. -/
theorem placesOver827_ncard_eq_fiftyEight :
    (placesOver827 K).ncard = 58 := by
  change Nat.card (Place827 K) = 58
  rw [Nat.card_congr (placeEquivPrimesOver827 K)]
  exact primesOver827_ncard_eq_fiftyEight K

/-- The action map from the cyclotomic Galois group to the primes over 827. -/
noncomputable def galOrbitMap827
    (base : rationalPrimeIdeal827.primesOver (𝓞 K))
    (sigma : Gal(K/ℚ)) : rationalPrimeIdeal827.primesOver (𝓞 K) := by
  letI : IsGalois ℚ K := IsCyclotomicExtension.isGalois {59} ℚ K
  letI : MulSemiringAction Gal(K/ℚ) (𝓞 K) :=
    IsIntegralClosure.MulSemiringAction ℤ ℚ K (𝓞 K)
  exact sigma • base

/-- Transitivity plus the equal cardinalities make the Galois orbit regular. -/
noncomputable def galEquivPrimesOver827
    (base : rationalPrimeIdeal827.primesOver (𝓞 K)) :
    Gal(K/ℚ) ≃ rationalPrimeIdeal827.primesOver (𝓞 K) := by
  letI : rationalPrimeIdeal827.IsMaximal :=
    rationalPrimeIdeal827_isMaximal
  letI : IsGalois ℚ K := IsCyclotomicExtension.isGalois {59} ℚ K
  letI : MulSemiringAction Gal(K/ℚ) (𝓞 K) :=
    IsIntegralClosure.MulSemiringAction ℤ ℚ K (𝓞 K)
  haveI : IsGaloisGroup Gal(K/ℚ) ℤ (𝓞 K) :=
    IsGaloisGroup.of_isFractionRing Gal(K/ℚ) ℤ (𝓞 K) ℚ K
  letI : Fintype (rationalPrimeIdeal827.primesOver (𝓞 K)) :=
    Fintype.ofFinite _
  refine Equiv.ofBijective (galOrbitMap827 K base) ?_
  apply (Fintype.bijective_iff_surjective_and_card _).mpr
  constructor
  · intro P
    obtain ⟨sigma, hsigma⟩ := Ideal.exists_smul_eq_of_isGaloisGroup
      rationalPrimeIdeal827 base.1 P.1 Gal(K/ℚ)
    exact ⟨sigma, Subtype.ext hsigma⟩
  · rw [Fintype.card_eq_nat_card, Fintype.card_eq_nat_card,
      gal_ncard_eq_fiftyEight K]
    exact (primesOver827_ncard_eq_fiftyEight K).symm

/-- A chosen place identifies the full support with its one regular Galois
orbit.  No class-group or Selmer splitting is involved. -/
noncomputable def placeOrbitEquiv827
    (selected : Place827 K) : Gal(K/ℚ) ≃ Place827 K :=
  (galEquivPrimesOver827 K (placeEquivPrimesOver827 K selected)).trans
    (placeEquivPrimesOver827 K).symm

/-- The canonical commutative index group for the cyclotomic Galois action. -/
abbrev GaloisIndex59 := (ZMod 59)ˣ

/-- Reindex the regular place orbit by `(ZMod 59)ˣ`. -/
noncomputable def indexedPlaceOrbitEquiv827
    (selected : Place827 K) : GaloisIndex59 ≃ Place827 K :=
  (IsCyclotomicExtension.Rat.galEquivZMod 59 K).symm.toEquiv.trans
    (placeOrbitEquiv827 K selected)

theorem galoisIndex59_card : Fintype.card GaloisIndex59 = 58 := by
  simp only [GaloisIndex59, Fintype.card_units]
  decide +kernel +revert

/-! ## Prime-generic residue Fourier analysis specialized at 59 -/

universe uDelta

section CharacterFunctions

variable {Delta : Type uDelta} [CommGroup Delta]

/-- A unit-valued character, viewed as a position vector. -/
abbrev characterFunction
    (chi : Delta →* (ZMod 59)ˣ) : Delta → ZMod 59 :=
  fun g ↦ (chi g : ZMod 59)

/-- The same character as a monoid homomorphism into the field. -/
abbrev characterMonoidHom
    (chi : Delta →* (ZMod 59)ˣ) : Delta →* ZMod 59 :=
  (Units.coeHom (ZMod 59)).comp chi

@[simp]
theorem characterMonoidHom_apply
    (chi : Delta →* (ZMod 59)ˣ) (g : Delta) :
    characterMonoidHom chi g = characterFunction chi g :=
  Fermat.Conservation.PrimeResidueFourier.characterMonoidHom_apply
    (p := 59) chi g

theorem characterMonoidHom_injective :
    Function.Injective (characterMonoidHom (Delta := Delta)) :=
  Fermat.Conservation.PrimeResidueFourier.characterMonoidHom_injective
    (p := 59) (Delta := Delta)

theorem characterFunction_apply_ne_zero
    (chi : Delta →* (ZMod 59)ˣ) (g : Delta) :
    characterFunction chi g ≠ 0 :=
  Fermat.Conservation.PrimeResidueFourier.characterFunction_apply_ne_zero
    (p := 59) chi g

/-- A vector lies in one pure character mode. -/
abbrev IsPureCharacter
    (chi : Delta →* (ZMod 59)ˣ) (v : Delta → ZMod 59) : Prop :=
  ∃ component : ZMod 59, v = component • characterFunction chi

/-- Point evaluation of a pure character vector is its character component
times the selected character value. -/
theorem pointEvaluation_of_pureCharacter
    (v : Delta → ZMod 59) (chi : Delta →* (ZMod 59)ˣ)
    (component : ZMod 59) (selected : Delta)
    (hv : v = component • characterFunction chi) :
    v selected = component * (chi selected : ZMod 59) :=
  Fermat.Conservation.PrimeResidueFourier.pointEvaluation_of_pureCharacter
    (p := 59) v chi component selected hv

end CharacterFunctions

section Fourier

variable {Delta : Type uDelta} [CommGroup Delta] [Fintype Delta]
  [IsCyclic Delta]

local instance : DecidableEq Delta := Classical.decEq Delta
local instance : Fintype (Delta →* (ZMod 59)ˣ) := Fintype.ofFinite _

omit [Fintype Delta] [IsCyclic Delta] in
theorem characterFunction_linearIndependent :
    LinearIndependent (ZMod 59)
      (characterFunction (Delta := Delta)) :=
  Fermat.Conservation.PrimeResidueFourier.characterFunction_linearIndependent
    (p := 59) (Delta := Delta)

/-- `ZMod 59` contains every root required by a cyclic group of order 58. -/
theorem enoughRootsForFourier (hcard : Fintype.card Delta = 58) :
    HasEnoughRootsOfUnity (ZMod 59) (Monoid.exponent Delta) :=
  Fermat.Conservation.PrimeResidueFourier.enoughRootsForFourier
    (p := 59) (Delta := Delta) hcard

theorem characterDual_card (hcard : Fintype.card Delta = 58) :
    Nat.card (Delta →* (ZMod 59)ˣ) = 58 :=
  Fermat.Conservation.PrimeResidueFourier.characterDual_card
    (p := 59) (Delta := Delta) hcard

theorem sum_characters_apply
    (hcard : Fintype.card Delta = 58) (x : Delta) :
    (∑ chi : Delta →* (ZMod 59)ˣ, (chi x : ZMod 59)) =
      if x = 1 then (58 : ZMod 59) else 0 :=
  Fermat.Conservation.PrimeResidueFourier.sum_characters_apply
    (p := 59) (Delta := Delta) hcard x

/-- Orthogonality of the 58 residue-field characters. -/
theorem character_orthogonality
    (hcard : Fintype.card Delta = 58) (s x : Delta) :
    (∑ chi : Delta →* (ZMod 59)ˣ,
        ((chi s : ZMod 59))⁻¹ * (chi x : ZMod 59)) =
      if s = x then (58 : ZMod 59) else 0 :=
  Fermat.Conservation.PrimeResidueFourier.character_orthogonality
    (p := 59) (Delta := Delta) hcard s x

/-- The normalized Fourier coordinate of a position vector in one character
mode. -/
abbrev fourierCoefficient (v : Delta → ZMod 59)
    (chi : Delta →* (ZMod 59)ˣ) : ZMod 59 :=
  (58 : ZMod 59)⁻¹ *
    ∑ s : Delta, ((chi s : ZMod 59))⁻¹ * v s

/-- Fourier inversion: the character modes reconstruct every position
vector. -/
theorem fourier_reconstruction
    (hcard : Fintype.card Delta = 58)
    (v : Delta → ZMod 59) (x : Delta) :
    (∑ chi : Delta →* (ZMod 59)ˣ,
        fourierCoefficient v chi * characterFunction chi x) = v x :=
  Fermat.Conservation.PrimeResidueFourier.fourier_reconstruction
    (p := 59) (Delta := Delta) hcard v x

omit [IsCyclic Delta] in
/-- A position delta has a nonzero coordinate in every character frequency. -/
theorem fourierCoefficient_positionBasis
    (selected : Delta) (chi : Delta →* (ZMod 59)ˣ) :
    fourierCoefficient (Pi.basisFun (ZMod 59) Delta selected) chi =
      (58 : ZMod 59)⁻¹ * ((chi selected : ZMod 59))⁻¹ :=
  Fermat.Conservation.PrimeResidueFourier.fourierCoefficient_positionBasis
    (p := 59) (Delta := Delta) selected chi

omit [IsCyclic Delta] in
theorem fourierCoefficient_positionBasis_ne_zero
    (selected : Delta) (chi : Delta →* (ZMod 59)ˣ) :
    fourierCoefficient (Pi.basisFun (ZMod 59) Delta selected) chi ≠ 0 :=
  by
    rw [fourierCoefficient_positionBasis]
    exact mul_ne_zero (inv_ne_zero (by decide +kernel +revert))
      (inv_ne_zero (Units.ne_zero (chi selected)))

/-- The vector obtained by retaining one Fourier component. -/
abbrev characterComponent (v : Delta → ZMod 59)
    (chi : Delta →* (ZMod 59)ˣ) : Delta → ZMod 59 :=
  fourierCoefficient v chi • characterFunction chi

omit [IsCyclic Delta] in
@[simp]
theorem characterComponent_apply
    (v : Delta → ZMod 59) (chi : Delta →* (ZMod 59)ˣ)
    (selected : Delta) :
    characterComponent v chi selected =
      fourierCoefficient v chi * (chi selected : ZMod 59) :=
  Fermat.Conservation.PrimeResidueFourier.characterComponent_apply
    (p := 59) v chi selected

/-- The character modes form the character basis dual to the position
basis. -/
noncomputable abbrev characterBasis
    (hcard : Fintype.card Delta = 58) :
    Basis (Delta →* (ZMod 59)ˣ) (ZMod 59) (Delta → ZMod 59) :=
  Fermat.Conservation.PrimeResidueFourier.characterBasis
    (p := 59) (Delta := Delta) hcard

@[simp]
theorem characterBasis_apply
    (hcard : Fintype.card Delta = 58)
    (chi : Delta →* (ZMod 59)ˣ) :
    characterBasis (Delta := Delta) hcard chi = characterFunction chi :=
  Fermat.Conservation.PrimeResidueFourier.characterBasis_apply
    (p := 59) (Delta := Delta) hcard chi

theorem characterBasis_fourier_sum
    (hcard : Fintype.card Delta = 58) (v : Delta → ZMod 59) :
    (∑ chi : Delta →* (ZMod 59)ˣ,
        fourierCoefficient v chi •
          characterBasis (Delta := Delta) hcard chi) = v := by
  funext x
  simp only [Finset.sum_apply, Pi.smul_apply, characterBasis_apply,
    characterFunction, smul_eq_mul]
  exact fourier_reconstruction (Delta := Delta) hcard v x

/-- The explicit Fourier coefficient is literally the corresponding basis
coordinate. -/
theorem characterBasis_repr_eq_fourierCoefficient
    (hcard : Fintype.card Delta = 58) (v : Delta → ZMod 59)
    (chi : Delta →* (ZMod 59)ˣ) :
    (characterBasis (Delta := Delta) hcard).repr v chi =
      fourierCoefficient v chi :=
  Fermat.Conservation.PrimeResidueFourier.characterBasis_repr_eq_fourierCoefficient
    (p := 59) (Delta := Delta) hcard v chi

theorem fourierCoefficient_pureCharacter
    (hcard : Fintype.card Delta = 58)
    (chi : Delta →* (ZMod 59)ˣ) (component : ZMod 59) :
    fourierCoefficient (component • characterFunction chi) chi =
      component :=
  Fermat.Conservation.PrimeResidueFourier.fourierCoefficient_pureCharacter
    (p := 59) (Delta := Delta) hcard chi component

theorem characterComponent_pureCharacter
    (hcard : Fintype.card Delta = 58)
    (chi : Delta →* (ZMod 59)ˣ) (component : ZMod 59) :
    characterComponent (component • characterFunction chi) chi =
      component • characterFunction chi :=
  Fermat.Conservation.PrimeResidueFourier.characterComponent_pureCharacter
    (p := 59) (Delta := Delta) hcard chi component

/-- Projecting a vector already lying in the selected pure mode returns the
same vector. -/
theorem characterComponent_eq_self_of_pure
    (hcard : Fintype.card Delta = 58)
    (chi : Delta →* (ZMod 59)ˣ) (v : Delta → ZMod 59)
    (hpure : IsPureCharacter chi v) :
    characterComponent v chi = v :=
  Fermat.Conservation.PrimeResidueFourier.characterComponent_eq_self_of_pure
    (p := 59) (Delta := Delta) hcard chi v hpure

omit [Fintype Delta] [IsCyclic Delta] in
/-- A nonzero pure character vector has full support. -/
theorem pureCharacter_support_eq_univ
    (chi : Delta →* (ZMod 59)ˣ) {component : ZMod 59}
    (hcomponent : component ≠ 0) :
    Function.support (component • characterFunction chi) = Set.univ :=
  Fermat.Conservation.PrimeResidueFourier.pureCharacter_support_eq_univ
    (p := 59) chi hcomponent

omit [Fintype Delta] [IsCyclic Delta] in
/-- In particular, a nonzero pure character vector cannot be a delta at one
place. -/
theorem pureCharacter_not_support_singleton
    [Nontrivial Delta]
    (chi : Delta →* (ZMod 59)ˣ) {component : ZMod 59}
    (hcomponent : component ≠ 0) (selected : Delta) :
    Function.support (component • characterFunction chi) ≠ {selected} :=
  Fermat.Conservation.PrimeResidueFourier.pureCharacter_not_support_singleton
    (p := 59) chi hcomponent selected

omit [IsCyclic Delta] in
/-- Pointed silence is impossible for a nonzero pure character.  If every
nonselected coordinate vanishes, the selected coordinate vanishes too. -/
theorem pureCharacter_pointed_silence
    (hcard : 1 < Fintype.card Delta)
    (chi : Delta →* (ZMod 59)ˣ) (v : Delta → ZMod 59)
    (selected : Delta) (hpure : IsPureCharacter chi v)
    (hsilence : ∀ position, position ≠ selected → v position = 0) :
    v selected = 0 :=
  Fermat.Conservation.PrimeResidueFourier.pureCharacter_pointed_silence
    (p := 59) hcard chi v selected hpure hsilence

end Fourier

/-! ## Seating the projected localization in the place orbit

The abstract q-relaxed representation currently has no theorem connecting
its supplied `GaloisIndex59` action to the arithmetic permutation of the
places over 827.  `QLocalizationEquivariance827` is the exact missing
interface.  Everything below is a consequence of an inhabitant of that
interface; none is manufactured here. -/

/-- Reduction of a 59-adic character to a residue-field Fourier character. -/
abbrev reducedCharacter59
    {Delta : Type*} [CommGroup Delta]
    (eta : InvolutiveBase.Character (PadicInt 59) Delta) :
    Delta →* (ZMod 59)ˣ :=
  (Units.map PadicInt.toZMod.toMonoidHom).comp eta

@[simp]
theorem reducedCharacter59_apply
    {Delta : Type*} [CommGroup Delta]
    (eta : InvolutiveBase.Character (PadicInt 59) Delta) (delta : Delta) :
    (reducedCharacter59 eta delta : ZMod 59) =
      PadicInt.toZMod (eta delta : PadicInt 59) :=
  Fermat.Conservation.PrimeResidueFourier.reducedCharacterAt_apply
    (p := 59) eta delta

section Seating

variable {K : Type uK} [Field K] [NumberField K]
  [IsCyclotomicExtension {59} ℚ K]
  [Invertible (Fintype.card GaloisIndex59 : PadicInt 59)]
  (rhoQ : QRelaxedSelmerDeltaRepresentation827 K GaloisIndex59)
  (omega chi : InvolutiveBase.Character (PadicInt 59) GaloisIndex59)

/-- The projected q-localization vector, read in the regular position basis
based at the selected place. -/
noncomputable def projectedLocalizationVector827
    (selected : Place827 K) (source : QRelaxedSelmerCarrier827 K) :
    GaloisIndex59 → ZMod 59 :=
  fun sigma ↦
    qLocalizationCoordinate827 rhoQ omega chi
      (indexedPlaceOrbitEquiv827 K selected sigma)
      (qRelaxedReflectedProjector827 rhoQ omega chi source)

/-- The missing arithmetic seating law.  It says that supported localization
is contragredient-equivariant for the supplied action while the 827 places
are read in their regular arithmetic orbit order.  Constructing this field
requires the absent action/localization comparison; the Fourier argument
does not assume it silently. -/
structure QLocalizationEquivariance827 (selected : Place827 K) : Prop where
  projected_coordinate_orbit :
    ∀ (sigma : GaloisIndex59) (source : QRelaxedSelmerCarrier827 K),
      qLocalizationCoordinate827 rhoQ omega chi
          (indexedPlaceOrbitEquiv827 K selected sigma)
          (qRelaxedReflectedProjector827 rhoQ omega chi source) =
        (((reducedCharacter59
          (InvolutiveBase.reflectedCharacter omega chi))⁻¹ sigma :
            (ZMod 59)ˣ) : ZMod 59) *
          qLocalizationCoordinate827 rhoQ omega chi selected
            (qRelaxedReflectedProjector827 rhoQ omega chi source)

set_option maxRecDepth 2000 in
/-- Under the missing seating law, every projected localization vector is a
single contragredient reflected-character mode. -/
theorem projectedLocalization_isPureCharacter
    (selected : Place827 K)
    (seating : QLocalizationEquivariance827 rhoQ omega chi selected)
    (source : QRelaxedSelmerCarrier827 K) :
    IsPureCharacter
      ((reducedCharacter59
        (InvolutiveBase.reflectedCharacter omega chi))⁻¹)
      (projectedLocalizationVector827 rhoQ omega chi selected source) := by
  let psi :=
    (reducedCharacter59
      (InvolutiveBase.reflectedCharacter omega chi))⁻¹
  let component := qLocalizationCoordinate827 rhoQ omega chi selected
    (qRelaxedReflectedProjector827 rhoQ omega chi source)
  refine ⟨component, ?_⟩
  funext sigma
  change qLocalizationCoordinate827 rhoQ omega chi
      (indexedPlaceOrbitEquiv827 K selected sigma)
      (qRelaxedReflectedProjector827 rhoQ omega chi source) =
    component * (psi sigma : ZMod 59)
  rw [mul_comm]
  exact seating.projected_coordinate_orbit sigma source

set_option maxRecDepth 2000 in
/-- Point evaluation at the selected place is evaluation of the selected
character component: Fourier coefficient times the corresponding character
value. -/
theorem pointedCoordinate827_eq_selectedCharacterComponent
    (selected : Place827 K)
    (seating : QLocalizationEquivariance827 rhoQ omega chi selected)
    (source : QRelaxedSelmerCarrier827 K) :
    pointedCoordinate827 rhoQ omega chi selected source =
      fourierCoefficient
          (projectedLocalizationVector827 rhoQ omega chi selected source)
          ((reducedCharacter59
            (InvolutiveBase.reflectedCharacter omega chi))⁻¹) *
        (((reducedCharacter59
          (InvolutiveBase.reflectedCharacter omega chi))⁻¹
            ((indexedPlaceOrbitEquiv827 K selected).symm selected) :
              (ZMod 59)ˣ) : ZMod 59) := by
  let orbit := indexedPlaceOrbitEquiv827 K selected
  let selectedIndex : GaloisIndex59 := orbit.symm selected
  let psi :=
    (reducedCharacter59
      (InvolutiveBase.reflectedCharacter omega chi))⁻¹
  let v := projectedLocalizationVector827 rhoQ omega chi selected source
  have hpure : IsPureCharacter psi v :=
    projectedLocalization_isPureCharacter rhoQ omega chi selected seating source
  have hself : characterComponent v psi = v :=
    characterComponent_eq_self_of_pure
      (Delta := GaloisIndex59) galoisIndex59_card psi v hpure
  calc
    pointedCoordinate827 rhoQ omega chi selected source = v selectedIndex := by
      simp [v, selectedIndex, orbit, projectedLocalizationVector827]
    _ = characterComponent v psi selectedIndex := congrFun hself.symm selectedIndex
    _ = fourierCoefficient v psi * (psi selectedIndex : ZMod 59) :=
      characterComponent_apply v psi selectedIndex
    _ = _ := rfl

set_option maxRecDepth 2000 in
/-- Once the projected localization is seated as its pure character, silence
at all 57 nonpointed places forces silence at the selected place.  This is
the conditional Fourier verdict `FIXED`. -/
theorem fixedAttention_of_fourierSeating
    (selected : Place827 K)
    (seating : QLocalizationEquivariance827 rhoQ omega chi selected) :
    FixedAttention
      (relaxedClassProjection827 rhoQ omega chi)
      (tameSilence827 rhoQ omega chi selected)
      (pointedCoordinate827 rhoQ omega chi selected) := by
  intro direction hdirection
  rw [LinearMap.mem_ker]
  let orbit := indexedPlaceOrbitEquiv827 K selected
  let selectedIndex : GaloisIndex59 := orbit.symm selected
  have hpure := projectedLocalization_isPureCharacter
    rhoQ omega chi selected seating direction
  have hsilence :
      ∀ sigma, sigma ≠ selectedIndex →
        projectedLocalizationVector827 rhoQ omega chi selected direction sigma = 0 := by
    intro sigma hsigma
    have hplace : orbit sigma ≠ selected := by
      intro h
      apply hsigma
      apply orbit.injective
      simpa [selectedIndex] using h
    let nonpointed : NonpointedPlace827 selected := ⟨orbit sigma, hplace⟩
    have hT := LinearMap.mem_ker.mp hdirection.2
    have hv := congrFun hT nonpointed
    change qLocalizationCoordinate827 rhoQ omega chi (orbit sigma)
        (qRelaxedReflectedProjector827 rhoQ omega chi direction) = 0 at hv
    exact hv
  have hcard : 1 < Fintype.card GaloisIndex59 := by
    rw [galoisIndex59_card]
    norm_num
  have hpoint := pureCharacter_pointed_silence
    hcard _ _ selectedIndex hpure hsilence
  change qLocalizationCoordinate827 rhoQ omega chi selected
      (qRelaxedReflectedProjector827 rhoQ omega chi direction) = 0
  simpa [projectedLocalizationVector827, orbit, selectedIndex] using hpoint

/-- Equivalently, the conditional Fourier seating excludes the steerable
future. -/
theorem no_transverseDirection_of_fourierSeating
    (selected : Place827 K)
    (seating : QLocalizationEquivariance827 rhoQ omega chi selected) :
    ¬ Nonempty
      (TransverseDirection
        (relaxedClassProjection827 rhoQ omega chi)
        (tameSilence827 rhoQ omega chi selected)
        (pointedCoordinate827 rhoQ omega chi selected)) := by
  rintro ⟨direction⟩
  exact direction.reading_ne_zero
    (LinearMap.mem_ker.mp
      (fixedAttention_of_fourierSeating rhoQ omega chi selected seating
        direction.direction_mem))

end Seating

end Fermat.FiftyNine.Conservation.SplitPrimeFourier827
