/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, OpenAI

# The Albert lift criterion specialized to the twisted lambda character

This file applies the constructive Albert theorem to the concrete local
Kummer extension generated by a 59th root of

`60 * (zeta_59 - 1)`.

A norm witness for the local primitive root therefore produces an actual
continuous lift of the already-defined twisted-lambda Kummer character from
`C59` to `C59²`.  Taking the contrapositive also records the exact non-norm
consequence of the current no-lift seam.

The reverse Albert implication (a lift produces a norm witness) is not
asserted here.
-/
import Fermat.Conservation.AlbertCyclicCompatibility59
import Fermat.FiftyNine.Conservation.TwistedLambdaCarryH2Class59

open scoped NumberField

noncomputable section

namespace Fermat.FiftyNine.Conservation.TwistedLambdaAlbertCriterion59

open Fermat.Conservation.AlbertCyclicCompatibility59
open Fermat.Conservation.AlbertCyclicQuotient59
open Fermat.Conservation.ContinuousCarryLiftObstruction59
open Fermat.FiftyNine.Conservation.LocalCompletion59
open Fermat.FiftyNine.Conservation.TwistedLambdaKummerQuotient59
open Fermat.FiftyNine.Conservation.TwistedLambdaCarryH2Class59

local instance : Fact (Nat.Prime 59) := ⟨by decide⟩
local instance : NeZero 3481 := ⟨by decide⟩

variable (K : Type) [Field K] [NumberField K]
variable [IsCyclotomicExtension {59} ℚ K]

/-- A norm witness in the concrete twisted-lambda Kummer extension produces
an exact continuous `C59²` lift of its existing Kummer character. -/
theorem exists_twistedLambdaAlbertCharacter3481_of_norm
    (beta : twistedLambdaKummerExtension59 K)
    (hbeta : Algebra.norm (LambdaField59 K) beta =
      lambdaLocalPrimitiveRoot59 K) :
    ∃ psi : Field.absoluteGaloisGroup (LambdaField59 K) →ₜ*
        CyclicGroup3481,
      cyclicReduction3481To59.comp psi =
        twistedLambdaKummerCharacter59 K := by
  obtain ⟨psi, hpsi⟩ :=
    concreteKummer_exists_albertCharacter3481
      (LambdaField59 K)
      (lambdaLocalPrimitiveRoot59 K)
      (twistedLambda59 K)
      (lambdaLocalPrimitiveRoot59_isPrimitive K)
      (twistedLambda59_not_pow K)
      beta hbeta
  refine ⟨psi, ?_⟩
  simpa [twistedLambdaKummerCharacter59] using hpsi

/-- The local Albert lift supplied by a norm witness is in fact onto
`C59²`, so its fixed field has the full expected degree `59²`. -/
theorem exists_surjective_twistedLambdaAlbertCharacter3481_of_norm
    (beta : twistedLambdaKummerExtension59 K)
    (hbeta : Algebra.norm (LambdaField59 K) beta =
      lambdaLocalPrimitiveRoot59 K) :
    ∃ psi : Field.absoluteGaloisGroup (LambdaField59 K) →ₜ*
        CyclicGroup3481,
      Function.Surjective psi ∧
      cyclicReduction3481To59.comp psi =
        twistedLambdaKummerCharacter59 K := by
  obtain ⟨psi, hsurj, hpsi⟩ :=
    concreteKummer_exists_surjective_albertCharacter3481
      (LambdaField59 K)
      (lambdaLocalPrimitiveRoot59 K)
      (twistedLambda59 K)
      (lambdaLocalPrimitiveRoot59_isPrimitive K)
      (twistedLambda59_not_pow K)
      beta hbeta
  refine ⟨psi, hsurj, ?_⟩
  simpa [twistedLambdaKummerCharacter59] using hpsi

/-- The reduction map used by the Albert construction is the same map as
the carry-obstruction reduction after normalizing `59 ^ 2 = 3481`. -/
theorem cyclicReduction3481To59_eq_reduction59 :
    (cyclicReduction3481To59 :
      Multiplicative (ZMod (59 ^ 2)) →ₜ* Multiplicative (ZMod 59)) =
      reduction59 := by
  apply ContinuousMonoidHom.ext
  intro x
  rfl

/-- Consequently, the explicit no-lift proposition forces the local
primitive root not to be a norm from the twisted-lambda Kummer extension.

This is the contrapositive of the constructive Albert direction.  The
converse implication, needed to deduce no-lift from an independently proved
non-norm statement, remains a separate theorem. -/
theorem primitiveRoot_not_norm_of_twistedLambdaNoContinuousLift
    (hnolift : TwistedLambdaNoContinuousLift59 K)
    (beta : twistedLambdaKummerExtension59 K) :
    Algebra.norm (LambdaField59 K) beta ≠
      lambdaLocalPrimitiveRoot59 K := by
  intro hbeta
  obtain ⟨psi, hpsi⟩ :=
    exists_twistedLambdaAlbertCharacter3481_of_norm K beta hbeta
  apply hnolift
  refine ⟨psi, ?_⟩
  rw [← cyclicReduction3481To59_eq_reduction59]
  exact hpsi

end Fermat.FiftyNine.Conservation.TwistedLambdaAlbertCriterion59
