/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, OpenAI

# The completed-log obstruction as an actual local Kummer class

The completed logarithm proves that the concrete principal unit
`twistUnit59 = 60` is not a 59th power in the full lambda-adic field.  This
file transports that result into the multiplicative Kummer quotient used by
the cohomological pairing stack.  The resulting class is nonzero and gives
an honest surjective cyclic Kummer character of degree 59.

The twisted-lambda radicand also has the exact quotient-level decomposition

`[60 * lambda] = [60] + [lambda]`.

Thus the completed-log calculation is now attached to the same local Kummer
state as the eventual Artin--Hasse pairing.  It still does not determine the
pairing of this nonzero class with the root-of-unity class: that is precisely
the remaining local reciprocity/nondegeneracy theorem, and no such value is
introduced here.
-/
import Fermat.FiftyNine.Conservation.CompletedLogLocalPowerObstruction59
import Fermat.FiftyNine.Conservation.TwistedLambdaNormalizedEndpoint59
import Fermat.Conservation.KummerCyclicQuotient59
import Fermat.Conservation.ContinuousCyclicH2Equiv59
import Fermat.Conservation.TameSymbol

open scoped NumberField
open Polynomial

noncomputable section

namespace Fermat.FiftyNine.Conservation.TwistUnitKummerObstruction59

open Fermat.Conservation.TameSymbol
open Fermat.Conservation.ContinuousCyclicH2Equiv59
open Fermat.Conservation.ContinuousCyclicH2Readout59
open Fermat.Conservation.CyclicCarryH2Class59
open Fermat.FiftyNine.Conservation.CompletedLogLocalPowerObstruction59
open Fermat.FiftyNine.Conservation.ContinuousKummerTateLocalization59
open Fermat.FiftyNine.Conservation.LocalCompletion59
open Fermat.FiftyNine.Conservation.TwistedLambdaCarryH2Class59
open Fermat.FiftyNine.Conservation.TwistedLambdaH2Inflation59
open Fermat.FiftyNine.Conservation.TwistedLambdaKummerCupComparison59
open Fermat.FiftyNine.Conservation.TwistedLambdaKummerLiftCriterion59
open Fermat.FiftyNine.Conservation.TwistedLambdaKummerNormCriterion59
open Fermat.FiftyNine.Conservation.TwistedLambdaKummerQuotient59
open Fermat.FiftyNine.Conservation.TwistedLambdaNormalizedEndpoint59

local instance : Fact (Nat.Prime 59) := ⟨by decide⟩

variable (K : Type) [Field K] [NumberField K]
variable [IsCyclotomicExtension {59} ℚ K]

/-- The principal unit `60`, bundled as a nonzero element of the actual
lambda-adic field. -/
def twistUnit59Unit : (LambdaField59 K)ˣ :=
  Units.mk0 (twistUnit59 K) (by
    intro hzero
    have hvaluation := twistUnit59_valuation K
    rw [hzero, map_zero] at hvaluation
    exact zero_ne_one hvaluation)

@[simp]
theorem twistUnit59Unit_val :
    (twistUnit59Unit K : LambdaField59 K) = twistUnit59 K :=
  rfl

/-- The completed-log principal unit in the genuine local multiplicative
Kummer quotient. -/
def twistUnitKummerClass59 : KummerClass 59 (LambdaField59 K) :=
  Additive.ofMul
    (QuotientGroup.mk'
      (powMonoidHom 59 : (LambdaField59 K)ˣ →* (LambdaField59 K)ˣ).range
      (twistUnit59Unit K))

/-- The completed-log power obstruction says exactly that the corresponding
local Kummer class is nonzero. -/
theorem twistUnitKummerClass59_ne_zero :
    twistUnitKummerClass59 K ≠ 0 := by
  intro hzero
  have hquotient :
      QuotientGroup.mk'
          (powMonoidHom 59 : (LambdaField59 K)ˣ →* (LambdaField59 K)ˣ).range
          (twistUnit59Unit K) = 1 := by
    exact Additive.ofMul.injective hzero
  obtain ⟨b, hb⟩ := (QuotientGroup.eq_one_iff (twistUnit59Unit K)).mp hquotient
  apply twistUnit59_not_pow_in_localField K
  refine ⟨(b : LambdaField59 K), ?_⟩
  have hbUnits : b ^ 59 = twistUnit59Unit K := by
    simpa only [powMonoidHom_apply] using hb
  exact congrArg Units.val hbUnits

/-- The Kummer polynomial of the completed-log principal unit. -/
abbrev twistUnitKummerPolynomial59 : (LambdaField59 K)[X] :=
  Polynomial.X ^ 59 - Polynomial.C (twistUnit59 K)

/-- The principal-unit Kummer polynomial is irreducible over the actual
local field. -/
theorem twistUnitKummerPolynomial59_irreducible :
    Irreducible (twistUnitKummerPolynomial59 K) := by
  exact
    Fermat.Conservation.KummerCyclicQuotient59.kummerPolynomial59_irreducible
      (LambdaField59 K) (twistUnit59 K)
      (fun b hb ↦ twistUnit59_not_pow_in_localField K ⟨b, hb⟩)

/-- The honest degree-59 Kummer extension generated by a 59th root of the
completed-log principal unit. -/
abbrev twistUnitKummerExtension59 :
    IntermediateField (LambdaField59 K)
      (AlgebraicClosure (LambdaField59 K)) :=
  Fermat.Conservation.KummerCyclicQuotient59.kummerExtension59
    (LambdaField59 K) (twistUnit59 K)

/-- The continuous cyclic Kummer character attached to the completed-log
principal unit. -/
def twistUnitKummerCharacter59 :
    Field.absoluteGaloisGroup (LambdaField59 K) →ₜ*
      Multiplicative (ZMod 59) :=
  Fermat.Conservation.KummerCyclicQuotient59.kummerCharacter59
    (LambdaField59 K)
    (lambdaLocalPrimitiveRoot59 K)
    (twistUnit59 K)
    (lambdaLocalPrimitiveRoot59_isPrimitive K)
    (fun b hb ↦ twistUnit59_not_pow_in_localField K ⟨b, hb⟩)

/-- Every cyclic coordinate occurs in the principal-unit Kummer character;
the completed-log obstruction therefore produces an actual nontrivial
degree-59 quotient of the local absolute Galois group. -/
theorem twistUnitKummerCharacter59_surjective :
    Function.Surjective (twistUnitKummerCharacter59 K) :=
  Fermat.Conservation.KummerCyclicQuotient59.kummerCharacter59_surjective
    (LambdaField59 K)
    (lambdaLocalPrimitiveRoot59 K)
    (twistUnit59 K)
    (lambdaLocalPrimitiveRoot59_isPrimitive K)
    (fun b hb ↦ twistUnit59_not_pow_in_localField K ⟨b, hb⟩)

/-- The canonical cyclotomic uniformizer, bundled as a field unit. -/
def canonicalLambda59Unit : (LambdaField59 K)ˣ :=
  Units.mk0 (canonicalLambda59 K) (by
    intro hzero
    have hvaluation := canonicalLambda59_valuation K
    rw [hzero, map_zero] at hvaluation
    exact (WithZero.exp_ne_zero : WithZero.exp (-1 : ℤ) ≠ 0)
      hvaluation.symm)

@[simp]
theorem canonicalLambda59Unit_val :
    (canonicalLambda59Unit K : LambdaField59 K) = canonicalLambda59 K :=
  rfl

/-- The bare lambda class in the local Kummer quotient. -/
def canonicalLambdaKummerClass59 : KummerClass 59 (LambdaField59 K) :=
  Additive.ofMul
    (QuotientGroup.mk'
      (powMonoidHom 59 : (LambdaField59 K)ˣ →* (LambdaField59 K)ˣ).range
      (canonicalLambda59Unit K))

/-- The 60-twisted lambda radicand, bundled as a field unit. -/
def twistedLambda59Unit : (LambdaField59 K)ˣ :=
  twistUnit59Unit K * canonicalLambda59Unit K

@[simp]
theorem twistedLambda59Unit_val :
    (twistedLambda59Unit K : LambdaField59 K) = twistedLambda59 K :=
  rfl

/-- The concrete radicand class underlying the existing twisted-lambda
Kummer extension. -/
def twistedLambdaRadicandKummerClass59 :
    KummerClass 59 (LambdaField59 K) :=
  Additive.ofMul
    (QuotientGroup.mk'
      (powMonoidHom 59 : (LambdaField59 K)ˣ →* (LambdaField59 K)ˣ).range
      (twistedLambda59Unit K))

/-- Exact Kummer-state decomposition of the twisted radicand into its
completed-log principal-unit part and its bare uniformizer part. -/
theorem twistedLambdaRadicandKummerClass59_eq_add :
    twistedLambdaRadicandKummerClass59 K =
      twistUnitKummerClass59 K + canonicalLambdaKummerClass59 K := by
  rfl

/-- The completed-log twist genuinely changes the local Kummer class of the
bare cyclotomic uniformizer. -/
theorem twistedLambdaRadicandKummerClass59_ne_canonicalLambdaKummerClass59 :
    twistedLambdaRadicandKummerClass59 K ≠
      canonicalLambdaKummerClass59 K := by
  intro heq
  have hquotient := congrArg Additive.toMul heq
  change
    QuotientGroup.mk'
          (powMonoidHom 59 : (LambdaField59 K)ˣ →* (LambdaField59 K)ˣ).range
          (twistUnit59Unit K * canonicalLambda59Unit K) =
      QuotientGroup.mk'
        (powMonoidHom 59 : (LambdaField59 K)ˣ →* (LambdaField59 K)ˣ).range
        (canonicalLambda59Unit K) at hquotient
  obtain ⟨z, hz, hproduct⟩ :=
    (QuotientGroup.mk'_eq_mk'
      (powMonoidHom 59 : (LambdaField59 K)ˣ →* (LambdaField59 K)ˣ).range).mp
        hquotient
  have htwist_mul_z : twistUnit59Unit K * z = 1 := by
    apply mul_right_cancel (b := canonicalLambda59Unit K)
    calc
      (twistUnit59Unit K * z) * canonicalLambda59Unit K =
          (twistUnit59Unit K * canonicalLambda59Unit K) * z := by
        ac_rfl
      _ = canonicalLambda59Unit K := hproduct
      _ = 1 * canonicalLambda59Unit K := by simp
  have htwist_mem :
      twistUnit59Unit K ∈
        (powMonoidHom 59 : (LambdaField59 K)ˣ →* (LambdaField59 K)ˣ).range := by
    rw [eq_inv_of_mul_eq_one_left htwist_mul_z]
    exact inv_mem hz
  obtain ⟨b, hb⟩ := htwist_mem
  apply twistUnit59_not_pow_in_localField K
  refine ⟨(b : LambdaField59 K), ?_⟩
  have hbUnits : b ^ 59 = twistUnit59Unit K := by
    simpa only [powMonoidHom_apply] using hb
  exact congrArg Units.val hbUnits

/-! ## Exact reduction of the remaining reciprocity seam -/

/-- Nonvanishing of the genuine twisted-lambda cup is sufficient to extend
the normalized finite-cyclic coordinate across inflation.  The extension is
noncanonical; the point is that no additional linear-algebra obstruction
remains once arithmetic has proved the cup nonzero. -/
theorem exists_normalizedInflationReadout_of_twistedLambdaKummerCup_ne_zero
    (hcup : twistedLambdaKummerCupH2Class59 K ≠ 0) :
    ∃ readout : LambdaRootsContinuousH2 K →ₗ[ZMod 59] ZMod 59,
      readout.comp (twistedLambdaH2Inflation59 K) =
        actualContinuousCyclicH2Readout59 := by
  obtain ⟨readout, hreadout⟩ :=
    exists_conditionalNoncanonicalLambdaH2Readout_eq_one K
      (twistedLambdaKummerCupH2Class59 K) hcup
  refine ⟨readout, ?_⟩
  apply LinearMap.ext
  intro x
  obtain ⟨a, rfl⟩ := continuousCarryH2Class59_spans x
  calc
    readout ((twistedLambdaH2Inflation59 K)
        (a • continuousCarryH2Class59)) =
        readout (a • (twistedLambdaH2Inflation59 K)
          continuousCarryH2Class59) := by
      exact congrArg readout
        ((twistedLambdaH2Inflation59 K).map_smul a
          continuousCarryH2Class59)
    _ = a • readout ((twistedLambdaH2Inflation59 K)
          continuousCarryH2Class59) := by
      exact readout.map_smul a
        ((twistedLambdaH2Inflation59 K) continuousCarryH2Class59)
    _ = a := by
      rw [twistedLambdaH2Inflation59_continuousCarryH2Class59, hreadout]
      simp
    _ = a • actualContinuousCyclicH2Readout59
          continuousCarryH2Class59 := by
      rw [actualContinuousCyclicH2Readout59_continuousCarryH2Class59]
      simp
    _ = actualContinuousCyclicH2Readout59
          (a • continuousCarryH2Class59) := by
      exact (actualContinuousCyclicH2Readout59.map_smul a
        continuousCarryH2Class59).symm

/-- The normalized-inflation readout seam is exactly cup nonvanishing.  The
forward implication is the already compiled normalized endpoint; the reverse
implication uses one-dimensionality of continuous `H²(C_59,F_59)` and does
not claim that the resulting readout is a canonical local invariant. -/
theorem exists_normalizedInflationReadout_iff_twistedLambdaKummerCup_ne_zero :
    (∃ readout : LambdaRootsContinuousH2 K →ₗ[ZMod 59] ZMod 59,
      readout.comp (twistedLambdaH2Inflation59 K) =
        actualContinuousCyclicH2Readout59) ↔
      twistedLambdaKummerCupH2Class59 K ≠ 0 := by
  constructor
  · rintro ⟨readout, hnormalized⟩
    exact twistedLambdaKummerCupH2Class59_ne_zero_of_normalized_readout
      K readout hnormalized
  · exact
      exists_normalizedInflationReadout_of_twistedLambdaKummerCup_ne_zero K

/-- Equivalently, the normalized readout exists exactly when the local
primitive root is not a norm from the concrete twisted-lambda Kummer
extension.  This is a reduction theorem, not a proof of either side. -/
theorem exists_normalizedInflationReadout_iff_primitiveRoot_not_norm :
    (∃ readout : LambdaRootsContinuousH2 K →ₗ[ZMod 59] ZMod 59,
      readout.comp (twistedLambdaH2Inflation59 K) =
        actualContinuousCyclicH2Readout59) ↔
      ¬ ∃ beta : twistedLambdaKummerExtension59 K,
        Algebra.norm (LambdaField59 K) beta =
          lambdaLocalPrimitiveRoot59 K := by
  rw [exists_normalizedInflationReadout_iff_twistedLambdaKummerCup_ne_zero]
  exact twistedLambdaKummerCupH2Class59_ne_zero_iff_primitiveRoot_not_norm K

/-- Equivalently again, the normalized readout exists exactly when the
twisted-lambda character admits no continuous lift from `C_59` to
`C_(59²)`. -/
theorem exists_normalizedInflationReadout_iff_noContinuousLift :
    (∃ readout : LambdaRootsContinuousH2 K →ₗ[ZMod 59] ZMod 59,
      readout.comp (twistedLambdaH2Inflation59 K) =
        actualContinuousCyclicH2Readout59) ↔
      TwistedLambdaNoContinuousLift59 K := by
  rw [exists_normalizedInflationReadout_iff_twistedLambdaKummerCup_ne_zero]
  exact twistedLambdaKummerCupH2Class59_ne_zero_iff_noContinuousLift K

end Fermat.FiftyNine.Conservation.TwistUnitKummerObstruction59
