/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, OpenAI

# A continuous uniformizer--Kummer quotient at the 59-adic place

Let `F` be the completion of the cyclotomic number field at
`lambda = (zeta_59 - 1)`.  The completion valuation is surjective onto
`WithZero (Multiplicative Int)`, so this file chooses an element `pi` of
valuation `exp (-1)`.  Valuations show directly that `pi` is not a
59th power.  Consequently `X^59 - pi` is irreducible.

Inside an algebraic closure of `F`, adjoining all roots of this polynomial
gives its degree-59 Kummer splitting field.  The chosen primitive 59th root
of unity identifies its Galois group with `Multiplicative (ZMod 59)`.
Restriction from the absolute Galois group then supplies an honest,
surjective continuous character

`AbsoluteGalois F -> Multiplicative (ZMod 59)`.

This module deliberately makes no claim that the character fails to lift
through

`Multiplicative (ZMod (59^2)) -> Multiplicative (ZMod 59)`.

That is the remaining cyclic-embedding obstruction.  Proving it for this
uniformizer Kummer extension requires arithmetic input such as a local
norm-group computation, an Albert embedding criterion, or an equivalent
local reciprocity/Hilbert-symbol theorem; none is silently packaged here.
-/
import Fermat.Conservation.ContinuousCyclicQuotient59
import Fermat.FiftyNine.Conservation.LocalCompletion59
import Mathlib.FieldTheory.KummerExtension
import Mathlib.Tactic

open scoped NumberField
open Polynomial WithZero

noncomputable section

namespace Fermat.FiftyNine.Conservation.UniformizerKummerQuotient59

open LocalCompletion59

variable (K : Type) [Field K] [NumberField K]
variable [IsCyclotomicExtension {59} ℚ K]

/-- A short name for the actual completion at
`lambda = (zeta_59 - 1)`. -/
abbrev LambdaField59 := LambdaLocalField59 K

/-- A noncomputably chosen element of valuation `exp (-1)` in the lambda
completion. -/
def uniformizer59 : LambdaField59 K :=
  (IsDedekindDomain.HeightOneSpectrum.valuedAdicCompletion_surjective
    K (lambdaPlace59 K) (WithZero.exp (-1 : ℤ))).choose

/-- The defining valuation of the chosen uniformizer. -/
@[simp]
theorem uniformizer59_valuation :
    Valued.v (uniformizer59 K) = WithZero.exp (-1 : ℤ) :=
  (IsDedekindDomain.HeightOneSpectrum.valuedAdicCompletion_surjective
    K (lambdaPlace59 K) (WithZero.exp (-1 : ℤ))).choose_spec

/-- An element of valuation one cannot be a 59th power: applying the
additive logarithm to the valuation equality would make `59` divide `-1`.
-/
theorem uniformizer59_not_pow (b : LambdaField59 K) :
    b ^ 59 ≠ uniformizer59 K := by
  intro h
  have hv := congrArg (Valued.v : LambdaField59 K → ℤᵐ⁰) h
  rw [map_pow, uniformizer59_valuation] at hv
  have hlog := congrArg (WithZero.log : ℤᵐ⁰ → ℤ) hv
  simp only [WithZero.log_pow, WithZero.log_exp] at hlog
  have hdvd : (59 : ℤ) ∣ (-1 : ℤ) :=
    ⟨WithZero.log (Valued.v b), by
      simpa [nsmul_eq_mul] using hlog.symm⟩
  norm_num at hdvd

/-- The Kummer polynomial attached to the chosen local uniformizer. -/
abbrev uniformizerPolynomial59 : (LambdaField59 K)[X] :=
  X ^ 59 - C (uniformizer59 K)

/-- The uniformizer Kummer polynomial has degree 59 and is irreducible. -/
theorem uniformizerPolynomial59_irreducible :
    Irreducible (uniformizerPolynomial59 K) := by
  exact
    (X_pow_sub_C_irreducible_iff_of_prime
      (by decide : Nat.Prime 59)).2 (uniformizer59_not_pow K)

/-- The concrete Kummer extension inside the chosen algebraic closure: the
field generated by all roots of `X^59 - pi`. -/
def uniformizerKummerExtension59 :
    IntermediateField (LambdaField59 K)
      (AlgebraicClosure (LambdaField59 K)) :=
  IntermediateField.adjoin (LambdaField59 K)
    ((uniformizerPolynomial59 K).rootSet
      (AlgebraicClosure (LambdaField59 K)))

/-- By construction, the concrete intermediate field is the splitting
field of the uniformizer Kummer polynomial. -/
theorem uniformizerKummerExtension59_isSplittingField :
    IsSplittingField (LambdaField59 K)
      (uniformizerKummerExtension59 K) (uniformizerPolynomial59 K) := by
  exact IntermediateField.adjoin_rootSet_isSplittingField
    (IsAlgClosed.splits
      ((uniformizerPolynomial59 K).map
        (algebraMap (LambdaField59 K)
          (AlgebraicClosure (LambdaField59 K)))))

local instance : TopologicalSpace (Multiplicative (ZMod 59)) := ⊥
local instance : DiscreteTopology (Multiplicative (ZMod 59)) := ⟨rfl⟩

/-- The finite Kummer Galois group, continuously identified with the
additive cyclic group `ZMod 59` written multiplicatively. -/
def uniformizerKummerGalEquiv59 :
    ((uniformizerKummerExtension59 K) ≃ₐ[(LambdaField59 K)]
      (uniformizerKummerExtension59 K)) ≃ₜ* Multiplicative (ZMod 59) := by
  letI : IsSplittingField (LambdaField59 K)
      (uniformizerKummerExtension59 K) (uniformizerPolynomial59 K) :=
    uniformizerKummerExtension59_isSplittingField K
  letI : FiniteDimensional (LambdaField59 K)
      (uniformizerKummerExtension59 K) :=
    Polynomial.IsSplittingField.finiteDimensional
      (uniformizerKummerExtension59 K) (uniformizerPolynomial59 K)
  letI : NeZero 59 := ⟨by decide⟩
  let e :
      ((uniformizerKummerExtension59 K) ≃ₐ[(LambdaField59 K)]
        (uniformizerKummerExtension59 K)) ≃* Multiplicative (ZMod 59) :=
    autEquivZmod (uniformizerPolynomial59_irreducible K)
      (uniformizerKummerExtension59 K)
      (lambdaLocalPrimitiveRoot59_isPrimitive K)
  exact
    { e with
      continuous_toFun := continuous_of_discreteTopology
      continuous_invFun := continuous_of_discreteTopology }

/-- The continuous Kummer character obtained by restricting the absolute
Galois action to the uniformizer extension. -/
def uniformizerKummerCharacter59 :
    Field.absoluteGaloisGroup (LambdaField59 K) →ₜ*
      Multiplicative (ZMod 59) := by
  letI : IsSplittingField (LambdaField59 K)
      (uniformizerKummerExtension59 K) (uniformizerPolynomial59 K) :=
    uniformizerKummerExtension59_isSplittingField K
  letI : IsGalois (LambdaField59 K)
      (uniformizerKummerExtension59 K) :=
    isGalois_of_isSplittingField_X_pow_sub_C
      ⟨lambdaLocalPrimitiveRoot59 K,
        (mem_primitiveRoots (by decide : 0 < 59)).2
          (lambdaLocalPrimitiveRoot59_isPrimitive K)⟩
      (uniformizerPolynomial59_irreducible K)
      (uniformizerKummerExtension59 K)
  exact Fermat.Conservation.ContinuousCyclicQuotient59.cyclicQuotient59
    (LambdaField59 K) (uniformizerKummerExtension59 K)
    (uniformizerKummerGalEquiv59 K)

/-- The local Kummer character is an algebraic quotient: every element of
`Multiplicative (ZMod 59)` occurs. -/
theorem uniformizerKummerCharacter59_surjective :
    Function.Surjective (uniformizerKummerCharacter59 K) := by
  letI : IsSplittingField (LambdaField59 K)
      (uniformizerKummerExtension59 K) (uniformizerPolynomial59 K) :=
    uniformizerKummerExtension59_isSplittingField K
  letI : IsGalois (LambdaField59 K)
      (uniformizerKummerExtension59 K) :=
    isGalois_of_isSplittingField_X_pow_sub_C
      ⟨lambdaLocalPrimitiveRoot59 K,
        (mem_primitiveRoots (by decide : 0 < 59)).2
          (lambdaLocalPrimitiveRoot59_isPrimitive K)⟩
      (uniformizerPolynomial59_irreducible K)
      (uniformizerKummerExtension59 K)
  exact Fermat.Conservation.ContinuousCyclicQuotient59.cyclicQuotient59_surjective
    (LambdaField59 K) (uniformizerKummerExtension59 K)
    (uniformizerKummerGalEquiv59 K)

end Fermat.FiftyNine.Conservation.UniformizerKummerQuotient59
