/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz, OpenAI

# The principal-unit Kummer norm obstruction at 59

The critical norm-image calculation proves that the genuine Kummer cup for
`60 * lambda` is nonzero.  The independently proved bare-lambda norm
witness makes the lambda contribution vanish, so the same nonzero class is
the genuine cup for the principal unit `60` alone.

Specializing the prime-generic norm/lift/H2 criterion to this unit therefore
excludes the primitive 59th root as a norm from the concrete Kummer
extension generated by a 59th root of `60`.  Equivalently, the already
constructed unit-60 Kummer character has no continuous `C_(59^2)` lift.
No readout, local invariant, reciprocity formula, or new arithmetic premise
is used.
-/
import Fermat.Conservation.PrimeKummerNormLiftH2Criterion
import Fermat.FiftyNine.Conservation.NormImageBridge59
import Fermat.FiftyNine.Conservation.TwistUnitKummerObstruction59
import Fermat.FiftyNine.Conservation.TwistedLambdaCupUnitReduction59

open scoped NumberField

noncomputable section

namespace Fermat.FiftyNine.Conservation.Unit60KummerNormObstruction59

open Fermat.Conservation.PrimeContinuousCarryLift
open Fermat.Conservation.PrimeKummerCarryLiftCriterion
open Fermat.Conservation.PrimeKummerNormLiftH2Criterion
open Fermat.FiftyNine.Conservation.CompletedLogLocalPowerObstruction59
open Fermat.FiftyNine.Conservation.LocalCompletion59
open Fermat.FiftyNine.Conservation.NormImageBridge59
open Fermat.FiftyNine.Conservation.TwistUnitKummerObstruction59
open Fermat.FiftyNine.Conservation.TwistedLambdaCupUnitReduction59
open Fermat.FiftyNine.Conservation.TwistedLambdaKummerQuotient59

local instance : Fact (Nat.Prime 59) := ⟨by decide⟩

variable (K : Type) [Field K] [NumberField K]
variable [IsCyclotomicExtension {59} ℚ K]

/-- The genuine principal-unit cup of `60` against the selected primitive
root is nonzero.  Its value is inherited from the twisted cup after the
bare-lambda summand has been killed by its explicit norm witness. -/
theorem unit60KummerCupH2Class59_ne_zero :
    unit60KummerCupH2Class59 K ≠ 0 := by
  rw [← twistedLambdaKummerCupH2Class59_eq_unit60KummerCupH2Class59 K]
  exact NormImageBridge59.twistedLambdaKummerCupH2Class59_ne_zero K

private def twistUnitNonpower59 :
    ∀ b : LambdaField59 K, b ^ 59 ≠ twistUnit59 K :=
  fun b hb ↦ twistUnit59_not_pow_in_localField K ⟨b, hb⟩

/-- The generic roots-valued obstruction for the radicand `60` is the
concrete unit-60 cup above, hence is nonzero. -/
private theorem genericUnit60KummerCupH2Class59_ne_zero :
    rootsKummerCupObstruction 59 (LambdaField59 K)
        (lambdaLocalPrimitiveRoot59 K) (twistUnit59 K)
        (lambdaLocalPrimitiveRoot59_isPrimitive K)
        (twistUnitNonpower59 K) ≠ 0 := by
  have hunit :
      Fermat.Conservation.PrimeKummerCharacterComparison.radicandUnit
          59 (LambdaField59 K) (twistUnit59 K) (twistUnitNonpower59 K) =
        unit60RadicandUnit59 K := by
    apply Units.ext
    rfl
  rw [rootsKummerCupObstruction, hunit]
  exact unit60KummerCupH2Class59_ne_zero K

/-- The selected primitive 59th root is not a norm from the honest Kummer
extension generated by a 59th root of the principal unit `60`. -/
theorem lambdaLocalPrimitiveRoot59_not_norm_from_twistUnit :
    ¬ ∃ beta : twistUnitKummerExtension59 K,
      Algebra.norm (LambdaField59 K) beta = lambdaLocalPrimitiveRoot59 K := by
  rw [show twistUnitKummerExtension59 K =
      Fermat.Conservation.PrimeKummerCyclicQuotient.kummerExtension
        59 (LambdaField59 K) (twistUnit59 K) by rfl]
  exact
    (primitiveRoot_not_norm_iff_rootsKummerCupObstruction_ne_zero
      59 (LambdaField59 K)
      (lambdaLocalPrimitiveRoot59 K) (twistUnit59 K)
      (lambdaLocalPrimitiveRoot59_isPrimitive K)
      (twistUnitNonpower59 K)).mpr
        (genericUnit60KummerCupH2Class59_ne_zero K)

/-- The concrete principal-unit Kummer character has no continuous lift
from `C_59` to `C_(59^2)`. -/
theorem twistUnitKummerCharacter59_noContinuousLift :
    NoContinuousLift (twistUnitKummerCharacter59 K) := by
  change KummerNoContinuousLift 59 (LambdaField59 K)
    (lambdaLocalPrimitiveRoot59 K) (twistUnit59 K)
    (lambdaLocalPrimitiveRoot59_isPrimitive K)
    (twistUnitNonpower59 K)
  exact
    (rootsKummerCupObstruction_ne_zero_iff_noContinuousLift
      59 (LambdaField59 K)
      (lambdaLocalPrimitiveRoot59 K) (twistUnit59 K)
      (lambdaLocalPrimitiveRoot59_isPrimitive K)
      (twistUnitNonpower59 K)).mp
        (genericUnit60KummerCupH2Class59_ne_zero K)

end Fermat.FiftyNine.Conservation.Unit60KummerNormObstruction59
